### ISSUE TITLE
Can you do pair programming via Internet in Codenvy

### ISSUE THREAD

**Issue by JCzz** [codenvy/codenvy#1001]
We have developers in different locations and looking for env. to do pair programming via the Internet.

**Comment by gazarenkov** [comment]
Now the "pair programming" term has too different meaning.
From XP programming practice (the origin of this term) to ability to GoogleDoc like experience with multi-cursors etc (which is more "pair" but less "programming" case I'd say).
Could you please elaborate what exactly use case you have in mind?

**Comment by JCzz** [comment]
Thanks for you reply

Well, I was thinking in terms of a GoogleDoc kind of scenario. I have also looked at https://codeanywhere.com

**Comment by TylerJewell** [comment]
Our workspaces allow for multiple users to share them at the same time. If you are in the same file at the same time, then file updates are made on each person's screen.  But we have not provided multi-cursor updates such that you can see where each person's cursor is at on the screen.  There is a pull request that we are evaluating which will provide this ability.  

Is pair programming in the sense of two people seeing what each other's edits what you need?  In our experience, most developers who want to do development require their own private workspace, but then to work collaboratively as part of a team -- such as what we are going to release this winter:  https://github.com/codenvy/codenvy/issues/916

**Comment by gazarenkov** [comment]
I see,
So, no, we do not support GoogleDoc out-of-the-box. 
You can share the workspace with several devs, open the same file on IDE or terminal, edit it and see (almost) live changes and notifications on others' devs window. This kind of things based on core Che VFS functionality (such as file watchers) but not really a collaborative editor which you look for. 
You can take a look here https://github.com/sunix/che-plugin-flux-live-edit it's a project of Che contributor which goal is to make a plugin with live editor experience.
HTH

**Comment by JCzz** [comment]
Thanks

2016-10-28 6:19 GMT+02:00 Tyler Jewell <notifications@github.com>:
