### ISSUE TITLE
Highlight in file .html.erb

### ISSUE THREAD

**Issue by gracyaneoliveira** [codenvy/codenvy#1007]
Rails files with extension .html.erb only open as text. 
How do I change the highlight of the file?

**Comment by TylerJewell** [comment]
@ashumilova - can you assign someone to comment on this?  @gracyaneoliveira - you mean for users, and not admins correct?  Codenvy's installation is done by puppet, so we have puppet templates with .erb files.  I just wanted to be clear on the scenario.

Our editor underlying the product is an Orion editor, so there is a configuration that is needed to register new file types in the right way.

**Comment by gracyaneoliveira** [comment]
File .html.erb is standard on Rails application. I found it strange the codenvy not recognize it.

thank you

**Comment by ashumilova** [comment]
@gracyaneoliveira we use Orion editor and it doesn't support text/x-html-erb mime type, but what we can do - is to register .html.erb extension in our system as html one, if such workaround suits you.

**Comment by gracyaneoliveira** [comment]
OK, thank you. That would be a great solution.

Without a highlight in .html.erb pages it is very difficult to develop in RubyOnRails.

**Comment by gracyaneoliveira** [comment]
Just to inform you that the IDE codeanywhere define htm.erb files as Embedded Ruby.
