### ISSUE TITLE
Can't deploy to GAE

### ISSUE THREAD

**Issue by joaquimcarmona** [codenvy/codenvy#1010]
For the last nine hours, I have been unable to deploy an app to GAE. Deployment starts normally, but never ends... It started to happen suddenly, from one minute to the other.

This is the last attempt (deployment started at 9:28, 13 minutes later it is still deploying): 

![screenshot 2016-10-23 at 09 33 14](https://cloud.githubusercontent.com/assets/12966705/19625018/a5983688-9904-11e6-9dce-f73c9eda15a8.png)

**Comment by TylerJewell** [comment]
Hi!  Sorry that you are having this issue.  I just did a quick test on the c3 system and could not reproduce it.  My app deployed right away.

We will be sunsetting this system and moving all users to codenvy.io a next generation system that offers better speed and flexibility.  It has a different approach for GAE.  I am giving you a heads up so that you can plan your move.  We will do the migration before the end of the year.

**Comment by joaquimcarmona** [comment]
Update:

Apparently deploying from the terminal works. However, in the GCP console there is no indication of an update (the last one dates to before the problem started) and indeed running the app shows it is the previous version.

Here is the terminal output:

`user@2d5453dde56f:~$ /home/user/appengine-java-sdk-1.9.19/bin/appcfg.sh --oauth2 update app ^M                                                                                                         
********************************************************                                                                                                                                               
There is a new version of the SDK available.                                                                                                                                                           
-----------                                                                                                                                                                                            
Latest SDK:                                                                                                                                                                                            
Release: 1.9.44                                                                                                                                                                                        
Timestamp: Fri Aug 19 21:41:38 UTC 2016                                                                                                                                                                
API versions: [1.0]                                                                                                                                                                                    
                                                                                                                                                                                                       
-----------                                                                                                                                                                                            
Your SDK:                                                                                                                                                                                              
Release: 1.9.19                                                                                                                                                                                        
Timestamp: Mon Apr 13 19:15:04 UTC 2015                                                                                                                                                                
API versions: [1.0]                                                                                                                                                                                    
                                                                                                                                                                                                       
-----------                                                                                                                                                                                            
Please visit https://developers.google.com/appengine/downloads for the latest SDK.                                                                                                                     
********************************************************                                                                                                                                               
Please open the following URL in your browser:                                                                                                                                                         
  https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&client_id=...                               
Please enter code: ...                                                                                                                                      
Reading application configuration data...                                                                                                                                                              
Oct 24, 2016 3:12:44 PM com.google.apphosting.utils.config.AppEngineWebXmlReader readAppEngineWebXml                                                                                                   
INFO: Successfully processed app/WEB-INF/appengine-web.xml                                                                                                                                             
Oct 24, 2016 3:12:44 PM com.google.apphosting.utils.config.AbstractConfigXmlReader readConfigXml                                                                                                       
INFO: Successfully processed app/WEB-INF/web.xml                                                                                                                                                       
Oct 24, 2016 3:12:44 PM com.google.apphosting.utils.config.AbstractConfigXmlReader readConfigXml                                                                                                       
INFO: Successfully processed app/WEB-INF/queue.xml                                                                                                                                                     
Oct 24, 2016 3:12:44 PM com.google.apphosting.utils.config.IndexesXmlReader readConfigXml                                                                                                              
INFO: Successfully processed app/WEB-INF/appengine-generated/datastore-indexes-auto.xml                                                                                                                
                                                                                                                                                                                                       
                                                                                                                                                                                                       
Beginning interaction for module default...                                                                                                                                                            
0% Created staging directory at: '/tmp/appcfg4270476812099338388.tmp'                                                                                                                                  
5% Scanning for jsp files.                                                                                                                                                                             
8% Compiling jsp files.                                                                                                                                                                                
Oct 24, 2016 3:12:49 PM com.google.apphosting.utils.config.AbstractConfigXmlReader readConfigXml                                                                                                       
INFO: Successfully processed /tmp/appcfg4270476812099338388.tmp/WEB-INF/web.xml                                                                                                                        
20% Scanning files on local disk.                                                                                                                                                                      
25% Initiating update.                                                                                                                                                                                 
28% Cloning 18 static files.                                                                                                                                                                           
31% Cloning 115 application files.                                                                                                                                                                     
40% Uploading 4 files.                                                                                                                                                                                 
52% Uploaded 1 files.                                                                                                                                                                                  
61% Uploaded 2 files.                                                                                                                                                                                  
68% Uploaded 3 files.                                                                                                                                                                                  
73% Uploaded 4 files.                                                                                                                                                                                  
77% Initializing precompilation...                                                                                                                                                                     
80% Sending batch containing 3 file(s) totaling 128KB.                                                                                                                                                 
82% Sending batch containing 1 blob(s) totaling 0KB.                                                                                                                                                   
90% Deploying new version.                                                                                                                                                                             
95% Closing update: new version is ready to start serving.                                                                                                                                             
98% Uploading index definitions.                                                                                                                                                                       
99% Uploading task queues.                                                                                                                                                                             
                                                                                                                                                                                                       
Update for module default completed successfully.                                                                                                                                                      
Success.                                                                                                                                                                                               
Cleaning up temporary files for module default...                                                                                                                                                      
user@2d5453dde56f:~$                                                                                                                                                                                   
`

> 

and an excerpt of GCP console:

`Activity


Ontem

00:31
Completed update of a new alternate version
Joaquim Carmona completed update of a new alternat`

**Comment by joaquimcarmona** [comment]
Thank you for your prompt reply.

The problem disappeared.

I have considered moving but have not done it as the new system does not seem to support deployment of java apps to GAE. Hope it will!

Kind regards,

JC

**Comment by TylerJewell** [comment]
We support that on the command line - and you can see examples of it in
eclipse.org/che docs.

We will not suppor the visual plugins anymore - they are heavy to maintain
and there are too many systems to connect to.

Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by TylerJewell** [comment]
@ddementieva - please have support investigate this and help resolve why GAE with command line utility isn't working for @joaquimcarmona.

**Comment by joaquimcarmona** [comment]
Here https://eclipse-che.readme.io/docs/che-and-gae only PHP and Python are
mentioned...

Em 25/10/2016 19:12, "Tyler Jewell" <notifications@github.com> escreveu:

**Comment by TylerJewell** [comment]
The instructions just use the CLI from GAE - so the syntax should effectively be about the same for different languages.

**Comment by joaquimcarmona** [comment]
Thank you, I'll try to figure it out.

Em 26/10/2016 02:29, "Tyler Jewell" <notifications@github.com> escreveu:
