### ISSUE TITLE
Codenvy Fails to start Factory. 

### ISSUE THREAD

**Issue by Wferr** [codenvy/codenvy#1014]
Sorry if this is the wrong place to get help for this. Not sure where else to ask.

[Short description of problem here]

**Reproduction Steps:**

 Just open up this factory image: https://codenvy.io/f?id=factory6evx1c9r4jkkn1d1
The file its self: http://typebin.xyz/ipofa.pl

**Expected behavior:**

The factory to be made using the image.
The same image and config works fine if setup as a new workstation

**Observed behavior:**

Factory times out on starting work space agent and eventually gives an error saying the build timed out.

**Codenvy version:** whatver codenvy.io is using? Sorry cant figure out.
**OS and version:** Host: Win10 Pro, Chrome 53, Factory Image codenvy/node with a install after it [here](https://raw.githubusercontent.com/sunix/jekyll4che/master/Dockerfile)

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy:  Unknown
Problem can be reliably reproduced: Yes

**Diagnostic bundle**
[error.txt](https://github.com/codenvy/codenvy/files/546887/error.txt)

**Comment by TylerJewell** [comment]
@ddementieva - please coordinate an engineer to take a look and respond on Monday.

**Comment by Wferr** [comment]
Any update? Sorry for bumping, but I need this relatively soon.

**Comment by ddementieva** [comment]
@Wferr I'm sorry for the late reply.

Problem with factory has been confirmed and we are still investigating. I'll inform you once we find any solution.

**Comment by eivantsov** [comment]
Interesting... it worked for me on one of our nightly servers.

@vparfonov can you please take a look. Definitely works on nightly5

**Comment by akorneta** [comment]
@Wferr Today was ship of 5.0.0-M6 codenvy version and I cannot reproduce this problem, so can you please check the state of this issue please.

**Comment by Wferr** [comment]
5.0.0-M6 fixed it, thanks Codenvy Team! 💯
