### ISSUE TITLE
OAuth for bitbucket

### ISSUE THREAD

**Issue by vbochenin** [codenvy/codenvy#1020]
I 've got exception while try to authenticate in bitbucket.org via OAuth

```
Invalid redirect_uri
This integration is misconfigured. Contact the vendor for assistance.
```

**Reproduction Steps:**
- Go to Workspace -> Import project -> Git
- Put https path to bitbucket repository inot field URL:
- Press button Import"
- In Authorization pop-up window with text "Remote host requests authorization through OAuth2 protocol" press button "Ok"

**Expected behavior:**

OAuth window with username/password fields, and successful authentication after that,
Repository should be imported successfully

**Observed behavior:**

Pop--up window with text:

```
Invalid redirect_uri
This integration is misconfigured. Contact the vendor for assistance.
```

**Codenvy version:** Current cloud version
**OS and version:** Windows 7, Chrome browser

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: Never try to import project via https urls and OAuth 
Problem can be reliably reproduced: Yes

**Diagnostic bundle**
Execute the script on [this page](https://github.com/codenvy/codenvy/wiki/Support-Diagnostics) and post public link to the bundle here.

**Comment by ddementieva** [comment]
@vbochenin try to setup SSH keys for Bitbucket (https://eclipse-che.readme.io/docs/git#versioning-with-ssh) and use SSH URL to import project. HTTPS will require username/password which is not supported.

**Comment by vbochenin** [comment]
@ddementieva I've tried, but with Connection timed out.
Anyway, why in this case, codenvy tried to authenticate via OAuth?

**Comment by TylerJewell** [comment]
If your repo is private on bitbucket then we use keys to authenticate to clone.  And all repos are private on bitbucket :) Bitbucket has changed their apis from time to time which has been frustrating but we have had no integration tests fail.

**Comment by TylerJewell** [comment]
@vbochenin - did you apply these changes and try to rerun?

**Comment by eivantsov** [comment]
Closed due to inactivity. Invalid redirect URI is fixed.

**Comment by albertshah** [comment]
In my experience, it was because I had already connected to another source control and the previous account existed in sourcetree desktop version. To solve, open client app, select the settings on top right of the screen, select both accounts and advanced tabs and remove items from there and retry cloning again from the menu.
