### ISSUE TITLE
Codenvy start in container doesn't work if development mode is on and codenvy.sh is called from outside of codenvy repo

### ISSUE THREAD

**Issue by garagatyi** [codenvy/codenvy#1030]
Steps to reproduce:
- Set development mode on
  - Set development mode repo to its real full path
- Go to folder where codenvy repo folder is placed.
- Call ./codenvy/codenvy.sh start

Expected:
Codenvy starts

Actual:
Codenvy start fails:

```
workspace$ ./codenvy/codenvy.sh start
WARNING: No swap limit support
INFO: (codenvy cli): Development mode is on and could not find valid Tomcat assembly
INFO: (codenvy cli): Have you built /assembly/onpremises-ide-packaging-tomcat-codenvy-allinone yet?
workspace$ export | grep CODENVY
declare -x CODENVY_CONFIG="/home/gaal/workspace/.codenvy/config"
declare -x CODENVY_DEVELOPMENT_MODE="on"
declare -x CODENVY_DEVELOPMENT_REPO="/home/gaal/workspace/codenvy"
declare -x CODENVY_INSTANCE="/home/gaal/workspace/.codenvy/instance"
```

**Comment by TylerJewell** [comment]
it behaved correctly - see the message.  DEV_MODE expects both a valid repo AND a valid assembly.  It could not find that you have built the assembly and so it fails.

**Comment by garagatyi** [comment]
Assembly is built. If I run codenvy and PWD is repo then everything is OK

**Comment by TylerJewell** [comment]
At the very top of the cli.sh, check the syntax around the "ls" command - it infers and tests for a valid assembly there.

**Comment by riuvshin** [comment]
fixed by https://github.com/codenvy/codenvy/commit/8b06591a1ba8ab223bf299f870f4eb6c065b6d39
@TylerJewell please test this on windows. problem was that we didn't respect user defined vars for 
both 
```
CODENVY_DEVELOPMENT_REPO
CODENVY_DEVELOPMENT_TOMCAT
```

**Comment by riuvshin** [comment]
Update here: https://github.com/codenvy/codenvy/commit/c4c5a2ba7696d0ea88f96407f02a1bfccb473df5
I forget that we should not allow override tomcat folder, and ask only `CODENVY_DEVELOPMENT_REPO`. Also I've added check is current dir  a codenvy repo for cases where user execute codenvy.sh not from repo and more clear error

**Comment by TylerJewell** [comment]
@garagatyi - I tried testing on windows, but was unable to build an assembly to test with the hackathon branch.  I was able to build an assembly on the master branch, though.

**Comment by riuvshin** [comment]
@TylerJewell just go to `assembly/onpremises-ide-packaging-tomcat-codenvy-allinone` and execute `mvn clean install`

**Comment by TylerJewell** [comment]
This is ok on the master branch but not in the hackathon branch.
