### ISSUE TITLE
CLI codenvy upgrade command

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#1033]
b. "codenvy upgrade y" will do the following:
---- Access the manifest that is in ~/.codenvy/manifests/upgrades to see if x -> y is allowed
---- If not allowed, terminate with friendly error message
---- If allowed, perform upgrade sequence of (cmd_stop(), cmd_backup()?, cmd_download() to get new images, cmd_start() (which does a config and launches Codenvy tomcat which does migration), and then if any errors along the way, some sort of rollback.

**Comment by TylerJewell** [comment]
I can help with some of the CLI upgrade() parts + education on how the system works.  There are two primary parts of the implementation;
1. Looking up from the manifest the valid upgrade paths and verifying that the user has entered a proper one.
2. Actually doing the upgrade by downloading the new images and starting the system.

This will probably not be that hard if you know the CLI --- but we will need two sets of images created by @skabashnyuk team so that we can practice upgrading from one format to another.  If we can get those images created on dockerhub with different tags and the manifest updated, then we can test.

**Comment by skabashnyuk** [comment]
Need more inputs.

1. ---- Access the manifest that is in ~/.codenvy/manifests/upgrades to see if x -> y is allowed
How this file "upgrades" will be  created, maintained, what format?
BTW in what cases in can be NOT allowed?
2. cmd_backup what it should do? exactly.

**Comment by TylerJewell** [comment]
Backup already implemented in cli so upgrade just reused that function.

Upgrades file is already generated by CI system and placed into codenvy/version image which is singleton that is downloaded when you first start the system.  This is all documented in the docs page :)

If it will help I can implement the function that checks upgrades for a valid upgrade request.

**Comment by dmytro-ndp** [comment]
@skabashnyuk: is Codenvy CLI https://github.com/codenvy/codenvy/tree/master/cli

**Comment by TylerJewell** [comment]
Completely new product - look at codenvy.sh and cli.sh in "hackathon" branch.

**Comment by dmytro-ndp** [comment]
Got it https://github.com/codenvy/codenvy/blob/hackathon/codenvy.sh
Thank you.

**Comment by TylerJewell** [comment]
I would like to implement a part of the upgrade method the part that verifies the upgrade version is acceptable.

-Tyler




On Thu, Oct 27, 2016 at 12:36 PM -0400, "Dmytro Nochevnov" <notifications@github.com> wrote:












Got it https://github.com/codenvy/codenvy/blob/hackathon/codenvy.sh

Thank you.

**Comment by TylerJewell** [comment]
@dmytro-ndp - I have implemented the logic in 'cmd_upgrade()' to check the currently installed version and then iterate through the list of upgradeable paths in the manifest to determine if the targeted upgrade to version is a version that we will accept.  So now we just have to implement the upgrade logic once we have versions that are upgradeable within images.

**Comment by JamesDrummond** [comment]
@vkuznyetsov We need this in the current sprint to make get this done by CheConf. Do you need additional resources/help from others to complete this task?

**Comment by TylerJewell** [comment]
This is not needed for current sprint.  Upgrade() is not expected nor required for CheConf.

**Comment by mshaposhnik** [comment]
Ok after some code investigation i see some points:
1) We need an utility method to know is codenvy is currently running
2) We need ability to download the specified version (which may differ from latest AFAIU)
3) Rollback is still a question for me
4) We need images of different versions to test everything

**Comment by TylerJewell** [comment]
@mshaposhnik - the existing CLI has some utility methods for checking that the server is already running.  You should be able to reuse that capability.

Also, the CLI also has tools for downloading images against a version, so you can reuse that, too.

**Comment by mshaposhnik** [comment]
Testing was performed by manually adding entries into updates manifest to allow fake updates to the same version, like nightly -> nightly
