### ISSUE TITLE
Navigate To File case sensitive?

### ISSUE THREAD

**Issue by bobpaige** [codenvy/codenvy#1038]
I'm used to Eclipse where the equivalent functionality is not case-sensitive.

Could we have (or does it already exist) a Navigate To File feature that is not case-sensitive?

**Codenvy version:** 5.0.0-M5
**OS and version:** [Enter OS name and version here]

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: [Yes / No]
Problem can be reliably reproduced: [Yes / No - it's random]

**Diagnostic bundle**
Execute the script on [this page](https://github.com/codenvy/codenvy/wiki/Support-Diagnostics) and post public link to the bundle here.

**Comment by tolusha** [comment]
@bobpaige 
Completely agree, we should rework our `Navigate To File` feature.
