### ISSUE TITLE
Remove latest sentence in the Team description label

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#1039]
Remove the second sentence in the following screen.

<img width="699" alt="screen shot 2016-10-27 at 08 29 14" src="https://cloud.githubusercontent.com/assets/1636769/19756824/8b377178-9c1f-11e6-8580-2af40bc14d31.png">

**Comment by ashumilova** [comment]
https://github.com/codenvy/codenvy/pull/1844
