### ISSUE TITLE
Improve "Add" experience in the left navbar with Team

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#1040]
Need to make the styles of the "Create Team" and "Create Workspace" consistent.

See mockup:
<img width="147" alt="screen shot 2016-10-27 at 08 31 44" src="https://cloud.githubusercontent.com/assets/1636769/19756872/e185e79e-9c1f-11e6-8027-3c852cc203d3.png">

**Comment by ashumilova** [comment]
https://github.com/codenvy/codenvy/pull/1844
