### ISSUE TITLE
Consistent styles for popups in Team

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#1041]
In Team capabilities we are using the old style of popups.
<img width="622" alt="screen shot 2016-10-27 at 08 34 03" src="https://cloud.githubusercontent.com/assets/1636769/19756935/313630f0-9c20-11e6-84b6-062efdf99dcf.png">

We need to stay consistent with the style of those and check to reuse the ones from @olexii4:
![selection_007_1024](https://cloud.githubusercontent.com/assets/1636769/19757032/ed4cff94-9c20-11e6-9216-9ad4165b12a2.png)

**Comment by ashumilova** [comment]
https://github.com/codenvy/codenvy/pull/1844
