### ISSUE TITLE
Avoid any sort of redrawing with inputs in Team's popups

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#1042]
The popup to add a new member to a team is redrawing itself depending on the value of the email textfield.

<img width="622" alt="screen shot 2016-10-27 at 08 34 03" src="https://cloud.githubusercontent.com/assets/1636769/19757101/4cb72842-9c21-11e6-89b1-c870653731de.png">

To reproduce the behavior:
1- remove content from the "Email" textfield
2- start to input "slem"
3- remove again the content

You'll see the height reset between step 1&2 and between step 2@3.

**Comment by ashumilova** [comment]
https://github.com/codenvy/codenvy/pull/1844
