### ISSUE TITLE
The factories from eclipse getting-started page still have links on beta.codenvy.com

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#1048]
**Reproduction Steps:**
Go to the https://www.eclipse.org/che/getting-started/cloud/ page and see links with examples.
![selection_009](https://cloud.githubusercontent.com/assets/1640058/19769271/71516252-9c63-11e6-8c2d-5a01f3e9e652.png)

**Expected behavior:**
The links should be changed on codenvy.io.

**Observed behavior:**
We have old links

**Che version:**    5.0.0-M7
**OS and version:** Ubuntu 14 TLS

**Comment by riuvshin** [comment]
today we have auto redirects for this but im +1 to update urls. @slemeur do you have permissions to do that?

**Comment by slemeur** [comment]
Yes sure. I'll do that Mr @riuvshin

**Comment by riuvshin** [comment]
@slemeur just remind you this :)

**Comment by slemeur** [comment]
Done
