### ISSUE TITLE
Extra Volumes Not Working

### ISSUE THREAD

**Issue by JamesDrummond** [codenvy/codenvy#1049]
I set codenvy.env `CODENVY_MACHINE_SERVER_EXTRA_VOLUME="/var/run/docker.sock:/var/run/docker.sock"`. I got the following error when trying to create a workspace `Unable to start workspace agent. Error when trying to start the workspace agent: Start of environment default failed. Error: Error response from docker API, status: 500, message: Error response from daemon: create "/var/run/docker.sock: "\"/var/run/docker.sock" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed`

Additionally if the information provided in CODENVY_MACHINE_SERVER_EXTRA_VOLUME is incorrect/invalid, this should be caught at server boot not when trying to create a workspace.

**Codenvy version:** Hackathon
**OS and version:** Debian - Linode Server

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: I think so. Never tried it on other versions.
Problem can be reliably reproduced: Yes

**Comment by TylerJewell** [comment]
What happens if you remove the double quotes, or if you put it in single quotes?

**Comment by JamesDrummond** [comment]
Changing it too `CODENVY_MACHINE_SERVER_EXTRA_VOLUME='/var/run/docker.sock:/var/run/docker.sock'` gives same error message `Could not start workspace wksp-vrl2. Reason: Start of environment default failed. Error: Error response from docker API, status: 500, message: Error response from daemon: create '/var/run/docker.sock: "'/var/run/docker.sock" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed`

**Comment by JamesDrummond** [comment]
@TylerJewell I tested without double/single quotes and it works. `CODENVY_MACHINE_SERVER_EXTRA_VOLUME=/var/run/docker.sock:/var/run/docker.sock
` Do you think we should keep this issue open or restrict the use of quotes and close issue?

**Comment by TylerJewell** [comment]
It should be documented that if you use this parameter then no quotes or if you add quotes special characters like colon need to be escaped in the quotes.

**Comment by garagatyi** [comment]
If this issue supposes fixing of docs, for whom it should be assigned?

**Comment by JamesDrummond** [comment]
@TylerJewell I am going to document this temporarily. However I think we should parse the quotes as it was acceptable before.

**Comment by garagatyi** [comment]
ok, please create an issue for platform team if you want us to implement that parsing in further sprints
