### ISSUE TITLE
Restart of Server Does Not Log Off User

### ISSUE THREAD

**Issue by JamesDrummond** [codenvy/codenvy#1050]
I can still click in the DI in an existing open browser tab after I restart the server. 

**Reproduction Steps:**

Start Codenvy server.
Open webpage to Codenvy Server in tab of Chrome browser.
Login which then shows DI.
Restart Codenvy server.
Click on DI links in existing tab of Chrome browser.
Goes to appropriate page but does not function correctly. 

**Expected behavior:**

After restarting Codenvy Server, user should be logged out on existing tab(s) and login screen displayed.

**Codenvy version:** Hackathon
**OS and version:** Debian - Linode Server

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: I think so. Never tried it on other versions.
Problem can be reliably reproduced: Yes

**Comment by bmicklea** [comment]
@JamesDrummond what is the "DI"?  User dashboard?

**Comment by JamesDrummond** [comment]
Dashboard Interface. I can start using UD.
