### ISSUE TITLE
Maintenance page's styling update

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#1051]
We need to update the styles of the maintenance page.

Attached the visual mockup:
![option3](https://cloud.githubusercontent.com/assets/1636769/19770671/6f980734-9c60-11e6-8df3-b28e4298962b.png)

**Comment by slemeur** [comment]
Seems it has not been fixed for all cases... 

![pasted_image_at_2016_12_09_05_00_pm](https://cloud.githubusercontent.com/assets/1636769/21148276/fdaa813e-c157-11e6-8ebc-2e2507dcad06.png)

**Comment by TylerJewell** [comment]
We also wanted different language for when the server is starting.  If you are just starting codenvy the first time, maintenance mode message seems odd.

**Comment by slemeur** [comment]
@vkuznyetsov could you please give a look on this?

**Comment by vkuznyetsov** [comment]
@slemeur can't reproduce on https://nightly5.codenvy-stg.com/site/maintenance or https://aio.codenvy-dev.com/site/maintenance for onprem. please provide the environment to reproduce this.

**Comment by TylerJewell** [comment]
1. Start codenvy using cli
3. Load the main page before codenvy finishes booting

**Comment by vkuznyetsov** [comment]
It seems we need to update separate maintenance page on HA-proxy

**Comment by riuvshin** [comment]
here is update of that page for haproxy https://github.com/codenvy/codenvy/pull/1384
