### ISSUE TITLE
System errors page styling update

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#1052]
We are covering maintenance page styling updates with the following issue:
https://github.com/codenvy/codenvy/issues/1051

We need to apply the same styles to the other error pages we are using into the system.

Attach a sample for "No Account Found":
![option3-account not found](https://cloud.githubusercontent.com/assets/1636769/19770792/eb8379aa-9c60-11e6-9fff-b6eff6734ba6.png)

Please update the styles for the following:
https://github.com/codenvy/codenvy/tree/master/site/app/site/error

**Comment by vkuznyetsov** [comment]
@slemeur What is the the link color when the visitor hovers over a link?

**Comment by slemeur** [comment]
I would prefer to not change the color but underline the text. Could you do that?

**Comment by vkuznyetsov** [comment]
Is there a clickable logo like in login page?
