### ISSUE TITLE
Add breadcrumb - project explorer / file sync

### ISSUE THREAD

**Issue by bobpaige** [codenvy/codenvy#1054]
*\* If you are a Codenvy customer or have a trial license please file your issues with Support through email. GitHub issues do not have a response SLA.**

When I'm editing a given source file, I can't tell which source path (or even project) it came from.

**Reproduction Steps:**
1. Open a source file using 'Navigate to file', i.e. "DTO.java"
2. Wonder where it came from

**Expected behavior:**

Eclipse has a neat feature (that I frequently only use for a short time since it slows things down) to keep the project explorer in sync with whatever source file you are in. Eclipse also has a "breadcrumb" showing file context.

The value is that sometimes I'm in similarly named files in different projects, or am looking for related files in the same Java package, but with Codenvy this is not possible AFAICT.

**Observed behavior:**
While editing a source file, I see no visual indication as to which project or source directory the file belongs.

**Comment by TylerJewell** [comment]
We have talked about adding a breadcrumb capability to the top of the editor for a long time. We have designs for this, but just haven't been able to get to it.  I can see us doing an editor revamp in early 2017 that allows us to provide this sort of capability.

**Comment by TylerJewell** [comment]
Replaced by che enhancement request.
