### ISSUE TITLE
Python Modules / Libraries not working?

### ISSUE THREAD

**Issue by Siranix** [codenvy/codenvy#1056]
*\* If you are a Codenvy customer or have a trial license please file your issues with Support through email. GitHub issues do not have a response SLA.**

[Short description of problem here]
Not being able to install all types of Python Modules or not being able to use them.

**Reproduction Steps:**

Install discord.py[voice] library
Get an error (Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-htj7j84l/PyNaCl/)
Stopped

Installed discord.py
Succesful
Try running an application using discord.py in the import
Error on Import

```
[STDERR] Traceback (most recent call last):
[STDERR]   File "bot.py", line 1, in 
[STDERR]     import discord
[STDERR] ImportError: No module named 'discord'
```

[Other Steps...]

**Expected behavior:**
Bot would tell us it's running.

**Observed behavior:**
Crashed....

**Codenvy version:** 5.0.0-M5
**OS and version:** Using the online Codenvy version...

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy:  No
Problem can be reliably reproduced: Yes

**Diagnostic bundle**
Execute the script on [this page](https://github.com/codenvy/codenvy/wiki/Support-Diagnostics) and post public link to the bundle here.

**Comment by TylerJewell** [comment]
Hi @Siranix - what was the base stack, Dockerfile or image that you used to create the initial workspace?

**Comment by Siranix** [comment]
@TylerJewell 
I used the basic ready-to-use stack for python (python 3.5)
install commands are included in the first message. We tried:
pip install discord.py[voice]
sudo pip install discord.py[voice]

**Comment by pastyljp** [comment]
I'm also having similar issues after running:

`sudo pip install fpdf`

Then importing the fpdf module within an application:

```
[STDERR] Traceback (most recent call last):
[STDERR]   File "../main.py", line 2, in
[STDERR]     from fpdf import FPDF
[STDERR] ImportError: No module named 'fpdf'
```

**Comment by TylerJewell** [comment]
I did a quick test and also confirm the error.  We need to revisit the default Python stack.  Our core engineering team does not have Python experts.  I will reach out to sourcegraph and bitnami to see if they have someone that could guide us.

**Comment by Siranix** [comment]
@TylerJewell That would be amazing! Thank you very much. Please keep us up-to-date regarding this through there?

**Comment by TylerJewell** [comment]
Hi @Siranix - in speaking with @sqs from Sourcegraph, he spotted the issue nearly immediately.

```
pip is installing Python 3.4's packages directory because it's Ubuntu's python3-pip, but the python is 3.5:

user@04c841581fd2:/projects$ python -c 'import sys; print(sys.path)'
['', '/usr/local/lib/python35.zip', '/usr/local/lib/python3.5', '/usr/local/lib/python3.5/plat-linux', '/usr/local/lib/python3.5/lib-dynload', '/usr/local/lib/python3.5/site-packages']
user@04c841581fd2:/projects$ pip -V
pip 8.1.1 from /usr/local/lib/python3.4/dist-packages (python 3.4)

This diff to the Dockerfile fixes it:
diff --git a/Dockerfile b/Dockerfile
index 46c59e6..6e850c0 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -11,7 +11,7 @@ FROM eclipse/ubuntu_jre
 # remove several traces of debian python 
 RUN sudo apt-get purge -y python.* && \
     sudo apt-get update && \
-    sudo apt-get install -y gcc make python3-pip
+    sudo apt-get install -y gcc make zlib1g-dev libssl-dev
 
 # http://bugs.python.org/issue19846 # > At the moment, setting "LANG=C" on a Linux system *fundamentally breaks Python 3*, and that's not OK. 
 ENV LANG C.UTF-8 
@@ -39,7 +39,9 @@ RUN set -ex \
        && sudo make -j$(nproc) \
        && sudo make install \
        && sudo ldconfig \
-       && sudo pip3 install --upgrade --ignore-installed pip==$PYTHON_PIP_VERSION \
+       && curl https://bootstrap.pypa.io/get-pip.py > /tmp/get-pip.py \
+       && sudo python3 /tmp/get-pip.py \
+       && rm /tmp/get-pip.py \
        && sudo find /usr/local \
                \( -type d -a -name test -o -name tests \) \
                -o \( -type f -a -name '*.pyc' -o -name '*.pyo' \) \

This works now:

user@5810444ac2fc:/projects$ sudo pip install requests
The directory '/home/user/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/user/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting requests
  Downloading requests-2.11.1-py2.py3-none-any.whl (514kB)
    100% |████████████████████████████████| 522kB 1.7MB/s 
Installing collected packages: requests
Successfully installed requests-2.11.1
user@5810444ac2fc:/projects$ python
Python 3.5.1 (default, Oct 29 2016, 15:00:48) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>>
```

**Comment by TylerJewell** [comment]
@eivantsov - can you see the changes proposed to the default Dockerfile for the python stack.  Can you make these changes to the default image, add any tests, and then update DockerHub wiht a quick fix?

**Comment by slampana** [comment]
@TylerJewell - I'm having the same issue still.  Can you give me any guidance on how to do the diff to the docker file until the issues is officially resolved?

**Comment by TylerJewell** [comment]
@JamesDrummond, @vkuznyetsov - please have this added to the next sprint.
@slampana - the diff to the Dockerfile is in my email above. It diffs the original Python Dockerfile with the one that resolves the issue.  The --- statements delete what is in the current Dockerfile. The +++ are additions to it.

**Comment by slampana** [comment]
@TylerJewell Thanks.  I don't have any docker experience.  Where do I go to input the diff code?

**Comment by TylerJewell** [comment]
This is the Dockerfile that should work.  You can test this by creating a workspace with a "custom stack" in the dashboard.  It will ask you for the Dockerfile contents.  This dockerfile updates our default python dockerfile - https://github.com/eclipse/che-dockerfiles/blob/master/recipes/ubuntu_python/3.5/Dockerfile - with the changes provided by @sqs.

```
FROM eclipse/ubuntu_jre

# remove several traces of debian python 
RUN sudo apt-get purge -y python.* && \
    sudo apt-get update && \
    sudo apt-get install -y gcc make zlib1g-dev libssl-dev

# http://bugs.python.org/issue19846 # > At the moment, setting "LANG=C" on a Linux system *fundamentally breaks Python 3*, and that's not OK. 
ENV LANG C.UTF-8 

# gpg: key F73C700D: public key "Larry Hastings <larry@hastings.org>" imported 
ENV GPG_KEY 97FC712E4C024BBEA48A61ED3A5CA953F73C700D 
ENV PYTHON_VERSION 3.5.1 

# if this is called "PIP_VERSION", pip explodes with "ValueError: invalid truth value '<VERSION>'" 
ENV PYTHON_PIP_VERSION 8.1.1 

RUN set -ex \
	&& sudo curl -fSL "https://www.python.org/ftp/python/${PYTHON_VERSION%%[a-z]*}/Python-$PYTHON_VERSION.tar.xz" -o python.tar.xz \
	&& sudo curl -fSL "https://www.python.org/ftp/python/${PYTHON_VERSION%%[a-z]*}/Python-$PYTHON_VERSION.tar.xz.asc" -o python.tar.xz.asc \
	&& export GNUPGHOME="$(mktemp -d)" \
	&& gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$GPG_KEY" \
	&& gpg --batch --verify python.tar.xz.asc python.tar.xz \
	&& sudo rm -r "$GNUPGHOME" python.tar.xz.asc \
	&& sudo mkdir -p /usr/src/python \
	&& sudo tar -xJC /usr/src/python --strip-components=1 -f python.tar.xz \
	&& sudo rm python.tar.xz \
	\
	&& cd /usr/src/python \
	&& sudo ./configure --enable-shared --enable-unicode=ucs4 \
	&& sudo make -j$(nproc) \
	&& sudo make install \
	&& sudo ldconfig \
       && curl https://bootstrap.pypa.io/get-pip.py > /tmp/get-pip.py \
       && sudo python3 /tmp/get-pip.py \
       && rm /tmp/get-pip.py \
	&& sudo find /usr/local \
		\( -type d -a -name test -o -name tests \) \
		-o \( -type f -a -name '*.pyc' -o -name '*.pyo' \) \
		-exec rm -rf '{}' + \
	&& sudo rm -rf /usr/src/python

# make some useful symlinks that are expected to exist 
RUN cd /usr/local/bin \
	&& sudo ln -s easy_install-3.5 easy_install \
	&& sudo ln -s idle3 idle \
	&& sudo ln -s pydoc3 pydoc \
	&& sudo ln -s python3 python \
	&& sudo ln -s python-config3 python-config
RUN sudo pip install --no-cache-dir virtualenv

EXPOSE 8080 

WORKDIR /projects

CMD tailf /dev/null
```

**Comment by slampana** [comment]
@TylerJewell It looked like it was going to work, but then at the end I get this:

![image](https://cloud.githubusercontent.com/assets/4888954/20109612/ba7916ce-a595-11e6-88ba-fe6811c2b368.png)

**Comment by slampana** [comment]
@TylerJewell Strange...I tried it again and everything worked perfectly.  Thanks for all your help!

**Comment by JamesDrummond** [comment]
@slampana We are closing this issue.
