### ISSUE TITLE
Generic GWT on Codenvy?

### ISSUE THREAD

**Issue by mpouttuclarke** [codenvy/codenvy#1057]
So I was looking to create a GWT app using Che and although there is an Eclipse Che sample workspace to build Che in Che there doesn't seem to be a way to build / run /debug a generic GWT app without the Che dependencies.  Is it possible to do this?  

I am using current version of Codenvy next gen on codenvy.io

**Comment by TylerJewell** [comment]
Hi Matt:

Yes - this is possible.  When you set up a Java project, you have to set up GWT commands.  If you go into the command editor, there are native GWT commands that you can use to structure GWT compilation.  You can run and debug it there.

**Comment by mpouttuclarke** [comment]
Awesome!  I work for Amazon Business now and I'm trying to get traction for both Che and GWT for next gen user experience.  To me you guys set the standard.

**Comment by TylerJewell** [comment]
That is cool!  @ddementiva - can we get a tutorial added to Che on creating and building a simple gwt app?
