### ISSUE TITLE
Workspace Creation Display Problem

### ISSUE THREAD

**Issue by JamesDrummond** [codenvy/codenvy#1061]
Workspace creation does not always display properly if you click on the workspace in DI. The processes interface does not expand and the projects do not display. 

![issue1](https://cloud.githubusercontent.com/assets/20580888/19819921/79ebf7a6-9d1c-11e6-95dc-95db16dbb986.gif)

**Reproduction Steps:**

Create new workspaces.
While load screen is up click on the workspace in DI.
The process interface does not expand.
Project sample is not shown.

**Expected behavior:**

Create new workspaces.
While load screen is up click on the workspace in DI.
The process interface does expands.
Project sample is not shown.

**Codenvy version:** codenvy.io
**OS and version:** Chrome

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: Yes I think so.
Problem can be reliably reproduced: No. I have had it happen a couple of time randomly when I click on an existing stopped workspace.

**Comment by slemeur** [comment]
What do you mean by **DI** ?

**Comment by JamesDrummond** [comment]
Dashboard Interface.

**Comment by JamesDrummond** [comment]
I don't think I have this problem anymore. If I get it again I will reopen.
