### ISSUE TITLE
Hidden folders

### ISSUE THREAD

**Issue by ETCaotico** [codenvy/codenvy#1062]
**I'm sorry for the silly question, but how to have hidden folders appear in Explorer?**

**Comment by TylerJewell** [comment]
In the Edit... or Project... menus, there should be a toggle option to enable / disable them.

**Comment by ETCaotico** [comment]
I've tried and only appears folders with "." At the beginning of them.

**Comment by TylerJewell** [comment]
Can you provide a scenario with reproduction steps that shows a situation where things that should appear are not appearing?  If you can make it reproducible, it may be a bug.

**Comment by ETCaotico** [comment]
This folder I want to appear is not hidden, but if it just is not appearing in Explorer.

**Comment by TylerJewell** [comment]
You have to be more explicit - show us a repository with an example, and perhaps even an animated gif that demonstrates it so that engineers can reproduce it exactly as you have seen it.  I am not able to reproduce it - when I toggle the flag, i can see all hidden directories.

**Comment by ETCaotico** [comment]
the command "la -a", they appear like this: `http://i.imgur.com/snZQPcR.png`

**Comment by TylerJewell** [comment]
That is not sufficient. Please see the contribution guidelines. 
1. Need to know all version & OS info.
2. Need to see sample repository with step by step instructions on how the ws was setup - these details matter
3. And potentially animated gif that shows this behavior
4. Any sample repositories, and / or open source code that make up your project would be helpful.

Just stating "ls -a" isn't sufficient as we cannot reproduce it with just that - it's not happening in the labs or with our unit tests.

**Comment by ETCaotico** [comment]
I managed to make the folder appears, however now she is like this: 
![sem titulo](https://cloud.githubusercontent.com/assets/13529337/19831560/a40b33c4-9deb-11e6-887c-b9156d33df92.png), I am unable to delete anything.
Another question how I saved an xml file modified?
