### ISSUE TITLE
Password root unsaved

### ISSUE THREAD

**Issue by ETCaotico** [codenvy/codenvy#1063]
Every time I restart the Workspace have to again set the password for root, if they can help me, thank you!

**Comment by tolusha** [comment]
@ETCaotico 
Every time you restart the Workspace you have the same workspace that have been configured. 
In other words, what have been done after starting workspace won't be persisted.

**Comment by eivantsov** [comment]
@ETCaotico can you elaborate on why you need to set root password? Also, do you use one of the ready to go stacks where password is already set and a user does not require one to act as a root user?

**Comment by eivantsov** [comment]
Closing the issue. All eclipse stacks have paswordless user.
