### ISSUE TITLE
apt-get: unable to locate package (i.e. nano, tesseract-ocr)

### ISSUE THREAD

**Issue by mathiasconradt** [codenvy/codenvy#1068]
In CodeEnvy terminal of the docker container, I try to install tesseract libraries via `apt-get`, but the package name cannot be located. It works fine in my local Ubuntu (14 / Trusty) docker container, but not on Codenvy (Ubuntu 16 / Xenial).

```
user@6408be1317f2:~/tomcat8$ sudo apt-get install tesseract-ocr                                                                                                                                   
Reading package lists... Done                                                                                                                                                                     
Building dependency tree                                                                                                                                                                          
Reading state information... Done                                                                                                                                                                 
E: Unable to locate package tesseract-ocr 
```

I also tried to install nano, but that package could also not be found.

```
user@6408be1317f2:~/tomcat8$ sudo apt-get install nano                                                                                                                                            
Reading package lists... Done                                                                                                                                                                     
Building dependency tree                                                                                                                                                                          
Reading state information... Done                                                                                                                                                                 
E: Unable to locate package nano
```

I found this on StackExchange/AskUbuntu: http://askubuntu.com/questions/378558/unable-to-locate-package-while-trying-to-install-packages-by-apt, but not sure what to make of it.

From my understanding, `nano` and `tesseract-ocr` should also be available for Ubuntu Xenial. 

http://packages.ubuntu.com/xenial/nano
http://packages.ubuntu.com/xenial/tesseract-ocr (this one is in the [universe] repository)

I checked `/etc/apt/sources.list` and all Ubuntu repos including the universe repository is enabled there.

Any idea?

**Comment by tolusha** [comment]
@mathiasconradt 
Hello.
Try `sudo apt-get update` and then `sudo apt-get install tesseract-ocr `

**Comment by mathiasconradt** [comment]
@tolusha Perfect, that worked.

**Comment by rahianeja** [comment]
@tolusha Great ! thanks

**Comment by ukreddy-erwin** [comment]
I am getting "Is the package apt-transport-https installed?" when I tried apt update

**Comment by Bishwas-py** [comment]
You need to add all the repositories in `sources.list`, check [this easy solution](https://blog.webmatrices.com/fix-e-unable-to-locate-package-error-in-kali-linux/).

**Comment by akasharunabharathi** [comment]
@tolusha Thanks so much!
