### ISSUE TITLE
Can not ssh to gitlab.com

### ISSUE THREAD

**Issue by uboot** [codenvy/codenvy#1071]
I can not connect to gitlab.com via SSH from the workspace console. As a consequence I can not clone gitlab repositories by their SSH address. 

**Reproduction Steps:**
- Create a VCS SSH key for gitlab.com in Codenvy (via "Profile" -> "Preferences", as explained in the documentation). Add the public key to your gitlab account.

- In the Codenvy console enter:
 `> ssh -v git@gitlab.com`

**Expected behavior:**
SSH connection should at least be established (even if the command above fails at a later stage). Cf. connecting to github.com.

**Observed behavior:**

`OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014 `
`debug1: Reading configuration data /etc/ssh/ssh_config ` 
`debug1: /etc/ssh/ssh_config line 19: Applying options for *   `
`debug1: Connecting to gitlab.com [104.210.2.228] port 22.  `
`debug1: connect to address 104.210.2.228 port 22: Connection timed out`
`ssh: connect to host gitlab.com port 22: Connection timed out `

**Codenvy version:** 5.0.0-M6 rev 219dac87e4c15201
**OS and version:** hosted on codenvy.io

**Comment by TylerJewell** [comment]
@JamesDrummond - please take a look.

**Comment by eivantsov** [comment]
@uboot we restrict outgoing traffic from workspaces at the moment.

I'll ask admins to whitelist gitlab.com

**Comment by eivantsov** [comment]
@uboot can you please give it a try again? After gitlab.com has been whitelisted, it works for me.

**Comment by uboot** [comment]
Everthing works fine if I create the SSH key on the CLI and import it via "Profile" -> "Preferences" -> "VCS" -> "Upload Key". If I create the key with "Generate Key", cloning a Gitlab-Repo from the SSH URL fails. However, this might be the same problem as #573  and or #491. Thanks a lot!
