### ISSUE TITLE
Test behaviors of workspace performance if rsync agent fails

### ISSUE THREAD

**Issue by JamesDrummond** [codenvy/codenvy#1079]
We should fail workspace start if rsync agent fails to start. This issue supposes that we will ensure that it works in such a way or fix otherwise

**Comment by mkuznyetsov** [comment]
The following cases were tested with `codenvy/ubuntu_jdk8` image:
- if `rsync` is removed from image, it does not try to install it on workspace startup, and it fails :
![selection_027](https://cloud.githubusercontent.com/assets/5712744/20062276/d0d7d250-a50b-11e6-8f88-529e71c4adc2.png)

However, when I use debug and stop at `RsyncAgentLauncherImpl`, and start stepping through methods, it will actually install `rsync` and start the workspace.

- if `rsync` is removed from image, and it's installation is impossible (cannot perform `apt-get update`), it is workspace startup will fail like this:
![selection_028](https://cloud.githubusercontent.com/assets/5712744/20062258/bc1216c8-a50b-11e6-92ec-33b6fdacb31c.png)

- if `openssh-client` is removed from image, it fails to startup, regardless of possibility to install it:
![selection_029](https://cloud.githubusercontent.com/assets/5712744/20062248/b33f21bc-a50b-11e6-87de-4cc235ca302a.png)

**Comment by NumidianDev** [comment]
Try to logout from codenvy and login again
