### ISSUE TITLE
Workspace is indicated as stopped but is still running.

### ISSUE THREAD

**Issue by JamesDrummond** [codenvy/codenvy#1082]
I am running a the hackathon version with all server resources and no external nodes on Debian Linode server with no proxy I am aware of between the server and my local machine. After an extended period of time maybe 3 hours the workspace throws error messages messages that the workspace is not running. After getting out of the workspace then back into the workspace, I get a workspace not found error message. Also when trying to run command from the UI. However the workspace is still accessible as I can still view the project folders and interact with the terminal in the Operations Perspective UI.

I extended the inactive time to `CODENVY_MACHINE_WS_AGENT_INACTIVE_STOP_TIMEOUT_MS=60000000` (~16hrs). Maybe there is something hard coded in the che server that is not picking up the increased timeout.

 The screen capture below doesn't show the terminal responding(forgot to record) but does show the new error message and IDE not functioning correctly.

![issue1](https://cloud.githubusercontent.com/assets/20580888/19944742/0c565144-a10b-11e6-93e4-653af6267a9e.gif)

**Comment by garagatyi** [comment]
Sorry but title of the issue is misleading. Workspace is not indicated as stopped. Probably we have a bug in API or client with machine detection.

**Comment by garagatyi** [comment]
Can you provide any steps to reproduce?

**Comment by mkuznyetsov** [comment]
@JamesDrummond
have you increased `CODENVY_MACHINE_WS_AGENT_INACTIVE_STOP_TIMEOUT_MS` value before or after you noticed the problems?
btw it's variable for maximum time of complete inactivity, after which workspace will be stopped.
Have you been active through all that "3 hours" time?

So far, can't reproduce it with the details described.

**Comment by JamesDrummond** [comment]
This is not happening anymore with the new nightly.
