### ISSUE TITLE
Is there a config option so Codenvy thinks it's browsable at subdomain.site.com instead of the IP of the system it runs on?

### ISSUE THREAD

**Issue by zackp30** [codenvy/codenvy#1084]
Hi,

(Apologies for not using the bug template, but this isn't really a bug, more a question)

I've installed Codenvy-onprem. Due to my main machine being an unsupported OS, I created a VM. I host multiple websites on the host machine, so I use a HTTP reverse proxy in Apache for Codenvy, instead of port forwarding the entire port 80/443.

Unfortunately, when I visit the subdomain I gave to Codenvy, I get redirected to:

https://subdomain.site.com/site/login?redirect_url=http%3A%2F%2F192.168.122.103%2F

I notice the `redirect_url` is incorrect, as it should point to https://subdomain.site.com. `192.168.122.103` is the VMs IP address.

My question is, is there a config option so I can tell Codenvy that it's accessible at https://subdomain.site.com and not the IP address it finds itself?

Thanks!

**Comment by TylerJewell** [comment]
Generally, Codenvy requires a DNS name for it. So it's rather interesting that you are getting redirected to the IP address instead.  I think the improvement you want is to change the hostname of Codenvy.  Which you can do during installation or after installation: 

http://codenvy.readme.io/docs/configuration#section-change-hostname

**Comment by eivantsov** [comment]
Closing the issue. Codenvy 5.x now does not require DNS.

https://codenvy.io/docs/admin-guide/installation/index.html
