### ISSUE TITLE
Change permission name from manageCodenvy -> manageSystem

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#1087]
Change permission name from manageCodenvy -> manageSystem
Related to https://github.com/codenvy/codenvy/issues/921

**Comment by mkuznyetsov** [comment]
It is stored in "systempermissions_actions" table.

Issue depends on https://github.com/eclipse/che/issues/2768

**Comment by mkuznyetsov** [comment]
SQL script:
```
UPDATE systempermissions_actions
SET actions='manageSystem'
WHERE actions='manageCodenvy';
```
