### ISSUE TITLE
Cannot configure a project after consuming factoty (regression)

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#1092]
**Reproduction Steps:**
1) Create any factory with maven project and run the factory
**Expected behavior:**
After creation workspace the project should be cloned and configured
**Observed behavior:**
The project is not configured, clonning does not finish

**Test server:** nightly5.codenvy-stg.com

**Codenvy version:** Version :5.0.0-M7
**OS and version:** Chrome browser, Ubuntu 14.0-TLS

**Comment by mshaposhnik** [comment]
Example factory?

**Comment by mshaposhnik** [comment]
Will be fixed when https://github.com/eclipse/che/tree/revert_2867  be applied

**Comment by musienko-maxim** [comment]
This is not checked yet

**Comment by bmicklea** [comment]
@musienko-maxim can you check this ASAP

**Comment by musienko-maxim** [comment]
On nightly server the tests passed
