### ISSUE TITLE
Codenvy in Docker: Fail to start a workspace on Windows

### ISSUE THREAD

**Issue by eivantsov** [codenvy/codenvy#1093]
Running a workspace results in the following error:

![image](https://cloud.githubusercontent.com/assets/5337267/20005199/10d615d0-a24e-11e6-829e-c0c2670c9c99.png)

Win 10

**Comment by riuvshin** [comment]
It seems I've reproduced same issue on mac. In my cause I've tried to configure and use codenvy with real dns. 
<img width="1680" alt="screen shot 2016-11-08 at 11 49 34 pm" src="https://cloud.githubusercontent.com/assets/1636732/20118683/1a81d150-a60e-11e6-9214-686670280c0d.png">

after revert back to ip it works again.

**Comment by TylerJewell** [comment]
Interesting.  My windows configuration is - by default - IP only.  Isn't that the default for all systems?

**Comment by riuvshin** [comment]
I can't reproduce this on mac or linux with IP. I wanted to test http \ https switch to provide proper docs but with configured DNS (this is real dns I;ve asked ADM team register real dns on godaddy for my IP to avoid paint with hosts) this I can't start WS with exactly same error.

**Comment by mkuznyetsov** [comment]
On Windows, there were problems with ssh key, that is used for rsync. (it's permissions are "too open", and cannot be changed on that exact file in container) which result in workspace startup failure.
It is solved by updating `rsyncrestore.sh` and `rsyncbackup.sh` scripts to use a copy of that key with correct permissions

**Comment by TylerJewell** [comment]
Worked perfectly on windows.  +1 to merge and close.

BTW - the new checks for docker host mounts also worked!  I had reset my docker for windows VM and it unsets the C drive.  And the CLI discovered that and told me what to do.

**Comment by riuvshin** [comment]
cool!
