### ISSUE TITLE
Automatically delete old workspaces

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#1096]
Works together with: https://github.com/codenvy/codenvy/issues/580.

The goal of this is to allow admins to implement an automatic removal of inactive workspaces.

Possible solution:
1a. Allow the admin to set a configuration parameter to define the maximum age (in days) of an unused workspace (Td) before it will be deleted.
1b. Allow admin to disable workspace age deletion check.
1c. By default this parameter is disabled so workspaces are not automatically removed.
2. System does a daily search for workspaces that can be deleted (those that are inactive for Td days).
3. Provide a popup in the dashboard for the user who owns the workspace: "The following workspaces will be deleted due to inactivity." : https://github.com/codenvy/codenvy/issues/943
4. Send an email to the user and admin:
- Subject: "Codenvy: inactive workspaces will be deleted"
- Body: "The following workspaces will be deleted tomorrow due to inactivity."
- List for each workspace: workspace name; username who owns the workspace; date of last access
5. Delete any workspaces which are inactive for Td+1 days.

Documentation should make it clear that this is a dangerous setting.

**Comment by gazarenkov** [comment]
Delete user workspace due to inactivity?
Like if I am not coding during T days my ws configuration and all the files will be deleted?
(please tell me I misunderstand that :) )

**Comment by bmicklea** [comment]
No, you didn't. Remember T could be 180.  Personally it's not something I'd set up in a system I was running but customers have requested it and there's no technical reason not to do it even if we disagree with it.

**Comment by gazarenkov** [comment]
Oh, yes, I can imagine that customer may want to delete some unnecessary things but the fact that noone put the hands to some code during even 5 years hardly may uniquely say that it should be automatically deleted. So, I would say "yes" to filters for admin, to notifications (as a low priority, just like you keep it I think) but definitely "no" to automatically deletion.
