### ISSUE TITLE
Where is the Codenvy User Discussion Forum these days?

### ISSUE THREAD

**Issue by chrisjj** [codenvy/codenvy#1098]
Assuming one still exists.

The nearest Google finds is https://groups.google.com/a/codenvy.com/forum/#!forum/codenvy , where "This group is deprecated" has been posted by someone who apparently doesn't know the meaning of the word deprecated, thinking it means discontinued.

**Comment by TylerJewell** [comment]
All support tickets and user discussion is done on GitHub, right here in this forum.  There is also another huge discussion on things related to Eclipse Che at github.com/eclipse/che/issues.

**Comment by chrisjj** [comment]
So any new discussion topic specific to CE should be opened here as an "issue"??

**Comment by TylerJewell** [comment]
Yes, since all questions are answered by support and engineers.  It keeps everything organized into a single queue.

**Comment by chrisjj** [comment]
What about discussion topics that are not questions? Or are not for support and engineers, but for users?

**Comment by TylerJewell** [comment]
We channel everything that is a question here until it is resolved and closed.  If there are aspects related to feature requests it turns into a kind/enhancement or perhaps a documentation issue.  But everything boils down to a kind/question, kind/enhancement or something related to improving the product.

**Comment by chrisjj** [comment]
> everything boils down to a kind/question, kind/enhancement or something related to improving the product.

OK, I take that to mean there's no place for Codenvy user discussion that doesn't. Thanks.
