### ISSUE TITLE
Anyone managed to find the advertised PHP GAE stack?

### ISSUE THREAD

**Issue by chrisjj** [codenvy/codenvy#1099]
I can't find it.

Support told me " you will be able to use GAE SDK natively - https://eclipse-che.readme.io/docs/che-and-gae " and that page https://eclipse-che.readme.io/docs/che-and-gae says:

> # When on the Dashboard create a new project with PHP GAE or Python GAE stack from the Stack Library and a sample PHP or Python project. 

But here's what i get: http://i.imgur.com/ZPAdZJ8.png .

No GAE to be seen.

**Comment by TylerJewell** [comment]
There are three tabs when you are creating a workspace - ready to go stacks, stack library, and custom stack.  Choose the "stack library" tab, and it is in there.  A future version will consolidate these three views into a nice single stack view that has an easy to manage filter on it.

![capture](https://cloud.githubusercontent.com/assets/392458/20025719/87fdde58-a2ae-11e6-9876-9574c6600943.PNG)

**Comment by chrisjj** [comment]
So PHP GAE is not a "Ready-to-go stack"?
