### ISSUE TITLE
How to I get lines to wrap?

### ISSUE THREAD

**Issue by chrisjj** [codenvy/codenvy#1103]
Rather than reach out of view like this:

![image](https://cloud.githubusercontent.com/assets/6157073/20026981/0268ac22-a2ff-11e6-9fe0-13b12fdb94cc.png)

**Comment by TylerJewell** [comment]
In the editor preferences, which is in the Profile menu.

**Comment by chrisjj** [comment]
Then I can't guess what it's labelled.

Not helped by the lack of an Apply button.
