### ISSUE TITLE
How to I get rid of this space-wasting thumbnail?

### ISSUE THREAD

**Issue by chrisjj** [codenvy/codenvy#1104]
![image](https://cloud.githubusercontent.com/assets/6157073/20026991/6c0d5a7e-a2ff-11e6-8288-85c113c0e84b.png)

**Comment by TylerJewell** [comment]
In the editor preferences - in the profile menu.  There are numerous options for configuring the behavior of the editor including removing the tracker.

**Comment by chrisjj** [comment]
> In the editor preferences - in the profile menu. 

Thanks.

> There are numerous options for configuring the behavior of the editor ...

Numerous indeed, since most seem to be duplicated.

![image](https://cloud.githubusercontent.com/assets/6157073/20027093/571bf406-a302-11e6-96a4-701126beaaa7.png)

below which:

![image](https://cloud.githubusercontent.com/assets/6157073/20027096/692210d6-a302-11e6-80e9-260c0db9bc4b.png)

Is this intended?

**Comment by TylerJewell** [comment]
@ashumilova
