### ISSUE TITLE
How to I disable the editor giving one more or one less character than I type?

### ISSUE THREAD

**Issue by chrisjj** [codenvy/codenvy#1105]
E.g. when here:

![image](https://cloud.githubusercontent.com/assets/6157073/20027018/670c9b2e-a300-11e6-9c5d-64952cbfe138.png)

I type a single quote but get two:

![image](https://cloud.githubusercontent.com/assets/6157073/20027025/880204a4-a300-11e6-80a7-accec23eed16.png)

And here 

![image](https://cloud.githubusercontent.com/assets/6157073/20027034/bf527c72-a300-11e6-9d70-9e09ee7fdd13.png)

I type a single quote and get none:

![image](https://cloud.githubusercontent.com/assets/6157073/20027039/dcff011e-a300-11e6-99d1-4990df089799.png)

Especially since this effect is not even consistent:

![image](https://cloud.githubusercontent.com/assets/6157073/20027043/08524056-a301-11e6-8d0d-0cfad1ff548c.png)

->

![image](https://cloud.githubusercontent.com/assets/6157073/20027045/18826dde-a301-11e6-92b9-0493aab41361.png)

**Comment by chrisjj** [comment]
Found the setting ... under Profile of all places.

**Comment by tolusha** [comment]
Correct.
`Profile -> Preferences -> Editor -> Typing`
