### ISSUE TITLE
Bugs in Profile Preference dialog

### ISSUE THREAD

**Issue by chrisjj** [codenvy/codenvy#1106]
This Cancel button fails to cancel the operation. Instead it closes the dialog, losing the changes!

![image](https://cloud.githubusercontent.com/assets/6157073/20027141/7c1515de-a303-11e6-927d-a4b78bd359fa.png)

This X button fails to either warn of unsaved changes or to save the changes or to discard the changes. Instead it closes the dialog leaving the changes ineffective but persistent in the closed dialog such that they reappear when it is next opened.

![image](https://cloud.githubusercontent.com/assets/6157073/20027159/fe82d2e0-a303-11e6-9827-83f341366ebf.png)

**Comment by mmorhun** [comment]
Fixed
