### ISSUE TITLE
Do the dialogs have to be so tiny?

### ISSUE THREAD

**Issue by chrisjj** [codenvy/codenvy#1107]
And unresizable.

E.g. this one http://i.imgur.com/f1JoVar.png .

No-one's screen is so small as to need that.

And no-one wants to waste time scrolling a keyhole up and down a list that the window is large enough to show entire.

**Comment by TylerJewell** [comment]
This is by design - a limitation of certain design elements from the previous generation.  We are going to work on a next generation interface that will have no popup.  I am going to close this because the work to eliminate popups is in another issue.
