### ISSUE TITLE
How can I operate the menus by keyboard?

### ISSUE THREAD

**Issue by chrisjj** [codenvy/codenvy#1108]
E.g.  press a key to pull down the Edit menu? And then step down its commands?

Even once I've pulled the menu down using the mouse, Down Arrow key is ignored.

**Comment by TylerJewell** [comment]
@slemeur

**Comment by slemeur** [comment]
Linked to #1194

**Comment by chrisjj** [comment]
"We are not handling the keyboard navigation in the main menu of the IDE."

Thanks for the info.

**Comment by slemeur** [comment]
Not yet @chrisjj ;) !

**Comment by chrisjj** [comment]
Indeed, and I'll look forward to news that you plan to address this. :)

**Comment by eivantsov** [comment]
Сдщыштп ершы щтую Ащддщц - https://github.com/codenvy/codenvy/issues/1194
