### ISSUE TITLE
Build project with java 7

### ISSUE THREAD

**Issue by charliefes** [codenvy/codenvy#1115]
Hi,

I see all recipes are with java jdk 8.

How can I configure and environment to build a project with java jdk7 in the new codenvy.io?

Regards

**Comment by TylerJewell** [comment]
If you want to use a different stack than the one that is provided, you will need to create a custom stack with a recipe that installs a java 7 client.

For reference:
1. Che's current recipes are all here. All of our recipes that require Java assume Java 8.  
https://github.com/eclipse/che-dockerfiles/tree/master/recipes

2. You can create different recipes and stacks.  Here is the link for how to do that. We now have a graphical editor in the dashboard. You can provide a Dockerfile in the screen and you can use the Dockerfiles that we provide as base images as a  sample, just replacing the Java 8 with a Java 7 version that you need.

Please note that our internal agents depend upon a JVM. So those agents do require a Java 8 JRE to be in the base image.  So even if you add in a java 7 JVM / JDK into your image, please do not remove the J8 one that our agents require.

**Comment by TylerJewell** [comment]
Closing due to answer being addressed.
