### ISSUE TITLE
Create a single class that can interrupt authentication

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#1116]
Depend on business logic we may want to block authentication for some group of users.
Right now it's not very easy to do. The goal of this issue is provide interface with default implementation what do nothing. If some codenvy assembly will want to provide some logic,  they will need to implement class that can cancel authentication. Both cases: usename-password and OAuth authentication must be covered.

**Comment by TylerJewell** [comment]
We should probably never block authentication if license expired.  Instead let users into dashboard but restrict product features by placing it into lockdown.

**Comment by skabashnyuk** [comment]
won't fix
