### ISSUE TITLE
Remove or replace api_token input on swagger landing page

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#1123]
```api_token``` input is legacy field that comes from original swagger. In codenvy we use ```token``` query parameter so we should either remove it either replace with ```token```
<img width="1440" alt="2016-11-09 16 22 09" src="https://cloud.githubusercontent.com/assets/1614429/20141484/357af0c8-a699-11e6-9bac-a2a91cd746ad.png">

**Comment by TylerJewell** [comment]
@skabashnyuk @mshaposhnik - is this still actual or has it already been resolved?

**Comment by eivantsov** [comment]
This issue was moved to eclipse/che#5664
