### ISSUE TITLE
When a workspace cannot start due to RAM limits, no error is displayed

### ISSUE THREAD

**Issue by eivantsov** [codenvy/codenvy#1144]
**Reproduction Steps:**

Start a workspace with 2 GB
Create a new workspace with 2 GB. Do not start it
Click on this ws in the recent workspaces
 
**Expected behavior:**

The IDE displays an error saying that total workspace RAM limit is reached.

**Observed behavior:**

Workspace start hangs. Errors in Chrome console

![image](https://cloud.githubusercontent.com/assets/5337267/20296169/ee56dfea-ab11-11e6-89f7-072aa3c92cc2.png)

**Comment by slemeur** [comment]
We are now displaying an error message to the user.
