### ISSUE TITLE
Codenvy development mode on windows not working properly

### ISSUE THREAD

**Issue by mkuznyetsov** [codenvy/codenvy#1146]
Problems when launching Windows with development mode

**Reproduction Steps:**

1. open cmd.exe, type in `set CODENVY_DEVELOPMENT_MODE=on`
2. in same cmd window, clone codenvy project, navigate inside of it and run `codenvy.bat start`

**Incorrect behavior**
1. During codenvy tomcat startup, there will be error "Unable to process Jar entry" with some random class from some random Jar, it's different each time):

codenvy/codenvy logs (tomcat startup part)
https://gist.github.com/mkuznyetsov/003cd921f36820f9bf75972f52972e8a
https://gist.github.com/mkuznyetsov/38aae65fc12eb7b0402c79392c8baa84
https://gist.github.com/mkuznyetsov/ce79b8c1aef0a0661cbfe9d1da555999

And then whole Codenvy start process is halted, though if you do `docker logs codenvy_codenvy_1`, you'll see "Server startup in xxxxx ms" in the end. But Codenvy doesn't work at that moment.

so codenvy.bat start command will abort with message `ERROR: (codenvy start): Timeout waiting for server. Run "docker logs codenvy_codenvy_1" to inspect the issue`

2. Destroying Codenvy

When trying to destroy such "installation", running `codenvy.bat destroy`, you'll see a following output:

```
C:\Users\Codenvy\codenvy>codenvy.bat destroy
INFO: (codenvy cli): Loading cli...
INFO:  destroy !!! Stopping services and !!! deleting data !!! this is unrecoverable !!!

     Are you sure? [N/y] y

INFO: (codenvy stop): Stopping containers...
INFO: (codenvy stop): Removing containers...
INFO: (codenvy destroy): Deleting instance and config
rm: can't remove '/root/codenvy-instance/dev/webapps/api/WEB-INF/lib': Directory not empty
rm: can't remove '/root/codenvy-instance/dev/webapps/api/WEB-INF': Directory not empty
rm: can't remove '/root/codenvy-instance/dev/webapps/api': Directory not empty
rm: can't remove '/root/codenvy-instance/dev/webapps/dashboard/WEB-INF/lib': Directory not empty
rm: can't remove '/root/codenvy-instance/dev/webapps/dashboard/WEB-INF': Directory not empty
rm: can't remove '/root/codenvy-instance/dev/webapps/dashboard': Directory not empty
rm: can't remove '/root/codenvy-instance/dev/webapps/factory/WEB-INF/lib': Directory not empty
rm: can't remove '/root/codenvy-instance/dev/webapps/factory/WEB-INF': Directory not empty
rm: can't remove '/root/codenvy-instance/dev/webapps/factory': Directory not empty
rm: can't remove '/root/codenvy-instance/dev/webapps/ROOT/WEB-INF/lib': Directory not empty
rm: can't remove '/root/codenvy-instance/dev/webapps/ROOT/WEB-INF': Directory not empty
rm: can't remove '/root/codenvy-instance/dev/webapps/ROOT': Directory not empty
rm: can't remove '/root/codenvy-instance/dev/webapps/site/images': Directory not empty
rm: can't remove '/root/codenvy-instance/dev/webapps/site/WEB-INF/lib': Directory not empty
rm: can't remove '/root/codenvy-instance/dev/webapps/site/WEB-INF': Directory not empty
rm: can't remove '/root/codenvy-instance/dev/webapps/site': Directory not empty
rm: can't remove '/root/codenvy-instance/dev/webapps': Directory not empty
rm: can't remove '/root/codenvy-instance/dev': Directory not empty
```

`instance` and `config` directories will be still present after that operation. 
If you run codenvy.bat destroy second time:

```
C:\Users\Codenvy\codenvy>codenvy.bat destroy
INFO: (codenvy cli): Loading cli...
INFO:  destroy !!! Stopping services and !!! deleting data !!! this is unrecoverable !!!

     Are you sure? [N/y] y

INFO: (codenvy stop): Stopping containers...
INFO: (codenvy stop): Removing containers...
INFO: (codenvy destroy): Deleting instance and config
rm: can't remove '/root/codenvy-instance/dev/webapps/api/WEB-INF/lib': Directory not empty
rm: can't remove '/root/codenvy-instance/dev/webapps/api/WEB-INF': Directory not empty
rm: can't remove '/root/codenvy-instance/dev/webapps/api': Directory not empty
rm: can't remove '/root/codenvy-instance/dev/webapps': Directory not empty
rm: can't remove '/root/codenvy-instance/dev': Directory not empty
```

Now if run codenvy.bat destroy on third time, it will cleanup everything as it should (`instance` and `config` directories will be removed).

**Codenvy version:** 5.0.0-M8-SNAPSHOT
**OS and version:** Windows 10

Problem can be reliably reproduced: [Yes]

**Comment by TylerJewell** [comment]
Does this issue exist when you run the cli in a container?  We no longer support it standalone.  See docs/readme.md

**Comment by mkuznyetsov** [comment]
I cannot launch CLI in container at all:
```
C:\Users\Codenvy\codenvy>docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v c:/Users/Codenvy/.codenvy:/codenvy -v c:/Users/Codenvy/.codenvy/backup:/backup -v c:/Users/Codenvy/codenvy:/repo codenvy/cli:nightly start
/repo/dockerfiles/cli/cli.sh: line 11: $'\r': command not found
```

**Comment by TylerJewell** [comment]
Your syntax is wrong.  On Windows the syntax for volume mounts is /c/ without a colon.

**Comment by garagatyi** [comment]
@mkuznyetsov Please recheck with correct syntax

@TylerJewell should we check such problem and print user-friendly error message in that case?

**Comment by TylerJewell** [comment]
We will not be able to catch that.  The error would happen in docker before the entrypoint as docker will say the volume mount is not properly entered.  It also happens when you forget to type -v.   But I think the syntax that docker gives is pretty clear. 

We could add a run.bat and run.sh to the root of the repo as simple shortcuts.

**Comment by TylerJewell** [comment]
This actually was a real bug - but we solved it in December and didn't close this.
