### ISSUE TITLE
Create  'Access Requires Fair Source Licence Acceptance' page in site project

### ISSUE THREAD

**Issue by vkuznyetsov** [codenvy/codenvy#1154]
This page needed for redirection if admin tries to log in before the Fair Source Licence have not been accepted by an admin.

When Codenvy is first installed:
  - In site ask the admin who logs in:
  > Title: Terms of Service
  > ~~Field: First Name~~
  > ~~Field: Last Name~~
  > ~~Field: Email~~
  > Message area with scroll bar: To access the system you must accept the terms of service. {add the license text from https://codenvy.com/legal/fair-source/}
  > Buttons: Accept (default)

~~- Fields cannot be blank, email must be correctly formatted~~
  ~~- If they choose "Accept" the user's info will be added to the Audit log with the message "{first name} {last name} with email {email} accepted Fair Source license agreement on {date and time}."~~
If they choose "Accept" the user's info will be added to the Audit log with the message "{date and time}  Fair Source license was accepted." (depends on https://github.com/codenvy/enterprise/issues/22, https://github.com/codenvy/enterprise/issues/23)

Only admin should have a permission to see this page.

#### _Accept Fair Source License_ method API
**POST /api/license/fair-source-license**
```
_Response Messages_:
201   
409    Fair Source License has been already accepted
500    Server error

**Comment by bmicklea** [comment]
@vkuznyetsov When an admin hits "accept" on this page then they'd go to the normal login screen and be able to enter the product.

**Comment by vkuznyetsov** [comment]
@bmicklea  But admin already logged in before they click 'Accept' button.

**Comment by bmicklea** [comment]
Right, of course. Then wen they hit accept they go the user dashboard.

**Comment by vkuznyetsov** [comment]
Are there any other buttons in form to reject/cancel licence agreement?

**Comment by slemeur** [comment]
![terms of service](https://cloud.githubusercontent.com/assets/1636769/20628213/f736095e-b324-11e6-87d0-3384ed18aa7f.png)

mockup, requested by @vkuznyetsov

**Comment by bmicklea** [comment]
Yes the user can cancel in which case there should be a pop up / page that
says "You must accept the license to use Codenvy."

**Comment by TylerJewell** [comment]
-1 - no need for cancel button.

**Comment by bmicklea** [comment]
Okay, that works.

**Comment by dmytro-ndp** [comment]
@vkuznyetsov: this should be done for SaaS version of Codenvy as well.
