### ISSUE TITLE
Don't allow users to login or to create new account if Fair Source license agreement isn't accepted

### ISSUE THREAD

**Issue by vkuznyetsov** [codenvy/codenvy#1155]
If admin tries to log in when Fair Source Licence agreement have not been accepted then redirect him to '_Access Requires Fair Source Licence Acceptance_' page at address "/site/auth/accept-fair-source-license".

If any non-admin user tries to login or to create new account, then return him an error:
> 403 Forbidden
> Access cannot be granted until the Fair Source license agreement is accepted by an admin.

This issue is related to https://github.com/codenvy/codenvy/issues/1154

**Comment by dmytro-ndp** [comment]
The changes are merged as part of PR https://github.com/codenvy/codenvy/pull/1428
