### ISSUE TITLE
DOCKER_HOST not detected on Mac

### ISSUE THREAD

**Issue by darrinsimmons** [codenvy/codenvy#1159]
I ran docker run codenvy/cli start from a terminal window on my mac and received the following error:
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
INFO:  Welcome to Codenvy!
INFO:  
INFO:  We did not detect a valid DOCKER_HOST.
INFO:  
INFO:  Rerun the CLI:
INFO:    docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock 
INFO:                        -v <local-path>:/codenvy 
INFO:                           codenvy/cli start

I currently have Docker  Version 1.12.3 (13776) installed and running on my Mac.
Darrins-MacBook-Pro:/ dsimmons$ docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64

**Reproduction Steps:**
Previously install Docker for Mac and make sure it is up and running.
run the following command:
docker run codenvy/cli start

**Expected behavior:**
I expected that a docker container would start and I would be able to connect to eclipse che on port 8080:  http://localhost:8080

Upon further reading (RTFM), looks like codenvy does not support Mac at this  time.  Perhaps an updated error message listing the valid operating systems that are supported, or a link to a list of currently supported operating systems may be a good enhancement.

**Observed behavior:**

[Describe observed behavior here]

**Codenvy version:** [Enter Codenvy version here]
I executed the above command at 3:45 on Tuesday, November 15th.

**OS and version:** [Enter OS name and version here]
MacOS Sierra, Version 10.12.1

**Additional information:**

First time install.

Problem only started happening recently, didn't happen in an older version of Codenvy: [Yes / No]
Problem can be reliably reproduced: [Yes / No - it's random]

**Diagnostic bundle**
Execute the script on [this page](https://github.com/codenvy/codenvy/wiki/Support-Diagnostics) and post public link to the bundle here.

**Comment by TylerJewell** [comment]
We absolutely support Mac!  That particular error is not about OS issues, though :)

That particular error is something that we place into the message to help you add additional command line options which are necessary to run codenvy.  

The real syntax is:
```
docker run -v /var/run/docker.sock:/var/run/docker.sock -v <path>/codenvy codenvy/cli start
```

We put the shorter syntax in the docs because it's fool proof and then we give you a help message on what you really need to type.  We do this because we found many other people were not typing the full syntax correctly the first time and this was a cleaner way to introduce you to the syntax.

**Comment by darrinsimmons** [comment]
Thanks @TylerJewell.  Here is the page that threw me off and made me think Mac was not supported:
http://codenvy.readme.io/docs/installation
_OPERATING SYSTEM
Core Codenvy requires an unmodified CentOS 7.1+ or RHEL 7.1+ operating system with access to the internet._ 

Also, I did not run it with sudo, so docker really was not able to connect to the docker daemon.

In fact, I just had to uninstall and re-install docker and now I got further in the installation, however, it still stopped after generating codenvy configuration and then complaining that it "Cannot enable tty mode on non tty input".  It appears someone has installed Jenkins on port 8080, so that may be tripping things up.  I'll go back to setting up Eclipse Che for now and come back to this later.  Thanks for your support!

**Comment by TylerJewell** [comment]
That error - with the tty input, just run it with "docker run -it .... rest of the stuff."   That should get you past that error.

We are going to transition away from the puppet-based intsallation, which is what you saw on the docs.codenvy.com (what is currently shipping), and instead move to this docker-based approach which is a ton simpler.

**Comment by darrinsimmons** [comment]
Thanks @TylerJewell, that got me past that error.  I've run into another, but will fall back to Eclipse Che for a while so that I don't continue to take your time with novice issues on your old installation framework.  

Hopefully this issue can get sorted: https://github.com/eclipse/che/issues/3092 as I would prefer to be able to use my Mac for my entire dev environment while I'm getting started.

**Comment by HalfEatenPie** [comment]
Experiencing something similar to original issue stated above (DOCKER_HOST) variable except on 64-bit Ubuntu 16.04.

I'd like to request a clarification on <path> in 

    docker run -v /var/run/docker.sock:/var/run/docker.sock -v <path>/codenvy codenvy/cli start

What path should be defined here?  The docker socket is defined but what additional path is necessary?

**Comment by TylerJewell** [comment]
The <path> in that particular exapmle is a local path where you want your Codenvy configuration and data to be saved.

**Comment by TylerJewell** [comment]
Closing as I assume this is resolved - we have many people running on Mac these days.

**Comment by darrinsimmons** [comment]
Thanks Tyler.

—Darrin
