### ISSUE TITLE
make it possible to use custom codenvy images like for codenvy saas

### ISSUE THREAD

**Issue by riuvshin** [codenvy/codenvy#1162]
Today in dockerized codenvy we support only codenvy/codenvy docker image aka codenvy onprem. But to use dockerized codenvy internally for development and put it to our dev/acceptance servers we should add possibility to switch between codenvy images somehow. For saas we have separate packaging and I (@riuvshin) can help with setting up docker image for codenvy saas packaging.
so here is some goals:

- dev mode should work with both codenvy onprem and codenvy saas packagings and switching between them must be really easy with CLI
- saas image must be same way respected during updates and version checks
- it seems we will need nightly and latest images for both packagings too

@TylerJewell I think  it will require your help on that also.

**Comment by TylerJewell** [comment]
We should wait for the consolidation of the codenvy cli and Che cli to be finished first.  We can create a custom assembly abstraction so the same cli can work for Che, codenvy onprem, saas and artik without constant reconfigure.

**Comment by riuvshin** [comment]
You are right. btw here I've created PR: https://github.com/codenvy/customer-saas/pull/82 which sync customer saas project with onrem which will allow use it dockerized.

**Comment by benoitf** [comment]
is this issue could be closed now ?

**Comment by TylerJewell** [comment]
+1

**Comment by riuvshin** [comment]
+1
