### ISSUE TITLE
Performance testing of workspace snapshotting opperation

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#1174]
Extensive testing on Amazon infrastructure with several agent nodes. Study of bottlenecks.

**Comment by mkuznyetsov** [comment]
Tested two scenarios on nightly5: if image contains lots of small files (10 000 files of 10KB size), or lesser amount of bigger ones (100 of 1MB each). Total size of snapshot image - 826.7MB

Created 10 workspace in parallel, and then ran a script that generates files, and then stopped those workspaces simultaneously with snapshotting.

Resulting graphics from Zabbix: https://docs.google.com/document/d/1wXFRMg8Y-3Rx4hSZ5_NUyZ_yRNEmtRHnWf-kzr2MIoQ/edit

**Comment by mkuznyetsov** [comment]
Usecase#1 with 100 x 1MB files
Time: 18:12 - 18:16

Network traffic, main node
![selection_100](https://cloud.githubusercontent.com/assets/5712744/20839996/67dcb850-b8b7-11e6-98d5-2130d2bf0bb8.png)

Network traffic, node 1
![selection_101](https://cloud.githubusercontent.com/assets/5712744/20839999/6c4ca53a-b8b7-11e6-8ca2-fd0b07112e95.png)
Network traffic, node 2
![selection_102](https://cloud.githubusercontent.com/assets/5712744/20840012/74eb4872-b8b7-11e6-9ed6-fa8ff186528b.png)

CPU load, main node
![selection_103](https://cloud.githubusercontent.com/assets/5712744/20840106/ba8f530a-b8b7-11e6-8d2d-6fa0dcc90b0d.png)
CPU load, node 1
![selection_104](https://cloud.githubusercontent.com/assets/5712744/20840116/c0fe9c50-b8b7-11e6-974b-d3d60a846232.png)
CPU load, node 2
![selection_105](https://cloud.githubusercontent.com/assets/5712744/20840124/c7e36096-b8b7-11e6-9cb0-b5d8565e6251.png)

Disk read/write, main node
![selection_106](https://cloud.githubusercontent.com/assets/5712744/20840133/d1382e60-b8b7-11e6-822a-4b87558a3c05.png)
Disk read/write, node 1
![selection_107](https://cloud.githubusercontent.com/assets/5712744/20840143/d96246e8-b8b7-11e6-9c43-973a83a427f1.png)
Disk read/write, node 2
![selection_108](https://cloud.githubusercontent.com/assets/5712744/20840154/e135c476-b8b7-11e6-91e1-a3358d2cd730.png)

**Comment by mkuznyetsov** [comment]
Usecase#1 with 10 000 x 10KB files
Time: 18:25 - 18:30

Network traffic, main node
![selection_115](https://cloud.githubusercontent.com/assets/5712744/20840391/c5585524-b8b8-11e6-97e0-5a180c90b1e6.png)
Network traffic, node 1
![selection_116](https://cloud.githubusercontent.com/assets/5712744/20840394/c9b794fe-b8b8-11e6-81e9-cb130062c9df.png)
Network traffic, node 2
![selection_117](https://cloud.githubusercontent.com/assets/5712744/20840395/cc61f122-b8b8-11e6-93db-179f129a39d4.png)


CPU load, main node
![selection_112](https://cloud.githubusercontent.com/assets/5712744/20840374/b36d993c-b8b8-11e6-9a5c-e23e87571c95.png)
CPU load, node 1
![selection_113](https://cloud.githubusercontent.com/assets/5712744/20840379/ba1e4024-b8b8-11e6-8069-a36c4f01a1f4.png)
CPU load, node 2
![selection_114](https://cloud.githubusercontent.com/assets/5712744/20840383/bef14826-b8b8-11e6-993d-24d5e3470645.png)

Disk read/write, main node
![selection_109](https://cloud.githubusercontent.com/assets/5712744/20840346/99c5e41c-b8b8-11e6-93a8-66c80073d412.png)
Disk read/write, node 1
![selection_110](https://cloud.githubusercontent.com/assets/5712744/20840352/9e682c82-b8b8-11e6-9a71-657473aa2df1.png)
Disk read/write, node 2
![selection_111](https://cloud.githubusercontent.com/assets/5712744/20840366/add8412a-b8b8-11e6-9e93-3288249ab872.png)

**Comment by mkuznyetsov** [comment]
Usecase#2 with 100 x 1MB files
Time: 18:54 - 19:00

Network traffic, main node
![selection_118](https://cloud.githubusercontent.com/assets/5712744/20840503/2172e36a-b8b9-11e6-80ec-630507516fca.png)
Network traffic, node 1
![selection_119](https://cloud.githubusercontent.com/assets/5712744/20840508/2545ddd0-b8b9-11e6-957b-6eff6e11ff47.png)
Network traffic, node 2
![selection_120](https://cloud.githubusercontent.com/assets/5712744/20840514/29339266-b8b9-11e6-90fa-b33f5abcd461.png)

CPU load, main node
![selection_121](https://cloud.githubusercontent.com/assets/5712744/20840517/2dde6f34-b8b9-11e6-9e74-b8eaa8c64146.png)
CPU load, node 1
![selection_122](https://cloud.githubusercontent.com/assets/5712744/20840522/3051187a-b8b9-11e6-9b43-77d1aec11d39.png)
CPU load, node 2
![selection_123](https://cloud.githubusercontent.com/assets/5712744/20840527/34542a16-b8b9-11e6-95ec-f2f1ec90b42c.png)

Disk read/write, main node
![selection_124](https://cloud.githubusercontent.com/assets/5712744/20840532/38913c0e-b8b9-11e6-91e9-bf2135f106f6.png)
Disk read/write, node 1
![selection_125](https://cloud.githubusercontent.com/assets/5712744/20840543/3ef08e24-b8b9-11e6-887a-ad511a513ae9.png)
Disk read/write, node 2
![selection_126](https://cloud.githubusercontent.com/assets/5712744/20840547/4328a6d4-b8b9-11e6-9e5b-e3ba3e1d860e.png)

**Comment by mkuznyetsov** [comment]
**Usecase#2 with 10 000 x 10KB files**
Time: 15:26 - 15:33

Network traffic, main node
![selection_132](https://cloud.githubusercontent.com/assets/5712744/20840648/9c9e5736-b8b9-11e6-828b-2e34be8109d4.png)
Network traffic, node 1
![selection_133](https://cloud.githubusercontent.com/assets/5712744/20840656/9f37ccd4-b8b9-11e6-851e-c8df90d852cd.png)
Network traffic, node 2
![selection_134](https://cloud.githubusercontent.com/assets/5712744/20840658/a14a31c4-b8b9-11e6-9771-a54fa5a38e53.png)

CPU load, main node
![selection_130](https://cloud.githubusercontent.com/assets/5712744/20840635/92acb484-b8b9-11e6-8abe-b19b3593bccf.png)
CPU load, node 1
![selection_135](https://cloud.githubusercontent.com/assets/5712744/20840665/a74e2fd0-b8b9-11e6-9d81-c0a19fc025ad.png)
CPU load, node 2
![selection_131](https://cloud.githubusercontent.com/assets/5712744/20840639/965df3e0-b8b9-11e6-9a97-d861ebccc3af.png)

Disk read/write, main node
![selection_129](https://cloud.githubusercontent.com/assets/5712744/20840619/86dae900-b8b9-11e6-9bb4-9ffb072e00bc.png)
Disk read/write, node 1
![selection_128](https://cloud.githubusercontent.com/assets/5712744/20840616/81ec1f04-b8b9-11e6-97fb-7f5b791b0acf.png)
Disk read/write, node 2
![selection_127](https://cloud.githubusercontent.com/assets/5712744/20840613/7f3f5758-b8b9-11e6-8cb1-ccd60d32c579.png)

**Comment by mkuznyetsov** [comment]
During those snapshot/restore processes, it was possible to use a browser to start another workspace.

Everything seems to be working in order for those usecases.
