### ISSUE TITLE
Test and document usage of codenvy in container using docker-machine to launch additional swarm nodes

### ISSUE THREAD

**Issue by garagatyi** [codenvy/codenvy#1176]
It is convenient way to use docker-machine tool to scale docker instances for the test sake.
We should try that too and document how to do that.

**Comment by skabashnyuk** [comment]
Creates scripts that use docker-machine to simulate adding / removing additional nodes for users and developers. This would allow users to run codenvy/cli add-node after running this to verify clustering. Then work with Tyler to integrate these scripts into the CLI.

https://github.com/codenvy/codenvy/issues/1256#issuecomment-264457083

**Comment by skabashnyuk** [comment]
@TylerJewell Any suggestions how it will looks like. Will it be a part of Codenvy CLI? What list of use cases it will cover?

**Comment by TylerJewell** [comment]
Not entirely sure.  I think we keep it out of the cli for now and just author it as a script or a set of steps for Windows, Mac and Linux.

I found these notes
https://docs.docker.com/swarm/provision-with-machine/

https://www.linux.com/learn/how-use-docker-machine-create-swarm-cluster

**Comment by skabashnyuk** [comment]
proposed syntax 
``` codenvy add-docker-machine  "$(docker-machine env default)" ```
or
``` docker-machine env default| codenvy add-docker-machine ```
@TylerJewell @garagatyi  wdyt?

**Comment by TylerJewell** [comment]
I don't think 'add-docker-machine' is a good user-friendly name.  Would it be more appropriate to say something like, 'create-simulated-node' or 'create-ws-node' as a way to indicate that you are creating a node for testing purposes, but that it wouldn't be appropriate for production?

**Comment by skabashnyuk** [comment]
Don't you think this method can't be used for production, just for simulation?
https://docs.docker.com/machine/drivers/ there is a pretty big list of drivers
I prefer to name method with something neutral name.  It have to have name somehow related to docker-machine, because it will use it syntax from output
```
[16:49:52]sj:~#: docker-machine env default
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/Users/sj/.docker/machine/machines/default"
export DOCKER_MACHINE_NAME="default"
# Run this command to configure your shell:
# eval $(docker-machine env default)
```

**Comment by TylerJewell** [comment]
I think, then that we should go with 'create-node' to match what we do with 'add-node' and 'remove-node' which is what the CLI currently does.  I don't think we need to expose to the admin the technology that we are using to make that happen.  We will provide that in the docs, and give admins two choices for creating nodes:
1. Provision one on their own manually and then install docker that is required
2. Or use our 'create-node' tool which uses virtualization to create a VM to use as a node, which you could run on different physical nodes.

**Comment by skabashnyuk** [comment]
what about?
```codenvy add-node docker-machine "$(docker-machine env default)"```
or
```docker-machine env default| codenvy add-node docker-machine```
or 
```codenvy add-node "$(docker-machine env default)"```
or 
```docker-machine env default| codenvy add-node ```

**Comment by TylerJewell** [comment]
create-node, not add-node.  We already have an add-node method in the CLI.

Why do you need the additional parameters after create-node?  It's not really a syntax I would want to show to admins.  

I would think that the create-node method would not need to take docker-machine as a parameter. It would just be the minimal parameters necessary to allow docker-machine to create a new VM.  Perhaps I do not understand what you are hoping to achieve.

**Comment by skabashnyuk** [comment]
I want to pipe two commands: existed docker-mashine to our command to add new node. 
I see this like that:
1. Admin need to start new node ```docker-machine create --driver amazonec2 aws01```
2. Admin have to add this node to codenvy ```codenvy add-node "$(docker-machine env aws01)"```

**Comment by TylerJewell** [comment]
I think those two commands are just fine.

Can you elaborate on the behavior of the codenvy add-node functionality?  Today, that will echo out a statement that must be run on the node itself.  Are you thinking of modifying add-node to connect to the VM and then run the statement in the VM?

**Comment by skabashnyuk** [comment]
We can modify or create new one, it's up to you. Idea is to have single command that parse output from 
docker-machine env command, find machine IP  and send it to codenvy.  Command have to be run on the same host where user run docker-machine create

**Comment by TylerJewell** [comment]
Let's see what it feels like in reality - let's get it working in a rough idea and then we can iterate to make it easier.

**Comment by skabashnyuk** [comment]
how to start node without tls
```docker-machine create -d virtualbox --engine-env DOCKER_TLS=no --engine-opt host=tcp://0.0.0.0:2375 node2```

**Comment by garagatyi** [comment]
I found that start of workspaces doesn't work on second node in multi-node scenario when overlay network is not configured. Error message says that network is not found. It is because network is created on first node and container can be created on another node. 
Default node is host docker that runs codenvy and it can't rely on key-value storage that can be in container on this host. 
That means that to run multi-node test we should:
1. Create docker node with docker-machine and start there key-value storage.
`docker-machine create  -d virtualbox --engine-env DOCKER_TLS=no kv`
`docker run -H <IP_of_kv_node:2376> -d -p 8500:8500 -h consul progrium/consul -server -bootstrap`
2. Create N docker nodes with docker-machine using next command:
`docker-machine create -d virtualbox
                                       --engine-env DOCKER_TLS=no 
                                       --virtualbox-memory "<megabytes_of_RAM>"
                                       --engine-opt host=tcp://0.0.0.0:2375 
                                       --engine-opt="cluster-store=consul://<ip_of_node_with_key_value_storage>:8500" 
                                       --engine-opt="cluster-advertise=eth1:2376" <node-#-name>`
Note: **megabytes_of_RAM** is mandatory and should be not less than 2048
3. Set value of variable **CODENVY_SWARM_NODES** in codenvy.env to: `<ip_of_node_1:2376>...<ip_of_node_N:2376>`
Note: original node should be removed from this list
4. Variable **CODENVY_HOST** in codenvy.env should be set to external IP (which is not true by default on Ubuntu 16.04) to be able to start workspaces

Here are an article where process of creation of VMs and addition them to overlay network is described https://medium.com/on-docker/docker-overlay-networks-that-was-easy-8f24baebb698

**Comment by TylerJewell** [comment]
@garagatyi - can you take a look at this command.  Is this right at the end?

`docker-machine create -d virtualbox --engine-env DOCKER_TLS=no kv`

**Comment by garagatyi** [comment]
yes, I think it is correct. What is confusing you?

**Comment by TylerJewell** [comment]
The space at the end. Can you have a space in a variable name?

Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by garagatyi** [comment]
The space separates variable and name of docker machine

**Comment by TylerJewell** [comment]
Ahhh, ok - thanks.

Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by TylerJewell** [comment]
@skabashnyuk @garagatyi - would it make sense for us to create a vagrantfile to automate creating 3 docker-machine VMs in a cluster with a proper codenvy.env and CODENVY_HOST?

**Comment by garagatyi** [comment]
By the way ignore error logs from docker-machine on machines creation. I think it is because of bug in docker-machine.

**Comment by garagatyi** [comment]
@TylerJewell AFAIK vagrant file runs inside VM. Do you want to create VMs with docker-machine inside of VM created by Vagrant?

**Comment by TylerJewell** [comment]
Just thinking about whether there is a technique we could give to admins who want to test a codenvy cluster - is there a tactic that could automate setting this up?  I was just thinking vagrant maybe would allow that.

**Comment by garagatyi** [comment]
Vagrant may be a solution, but in that case we probably drop usage of docker-machine and implement it manually inside of vagrant file

**Comment by TylerJewell** [comment]
Let me try setting up a cluser on my docker for windows box this weekend.  What is nice about docker-machine is that it should work on any system with docker.

**Comment by garagatyi** [comment]
If we need to use snapshots we also should add `--engine-insecure-registry <CODENVY_HOST:5000>`

**Comment by garagatyi** [comment]
Looks like snapshots won't work because of blocked traffic from VM to host. If we want to use snapshot we should workaround that somehow also.

**Comment by garagatyi** [comment]
And add-node won't work because of that also, so we have to manually change codenvy.env or rework add-node or workaround accessibility issue.

**Comment by TylerJewell** [comment]
@garagatyi - when you say that add-node doesn't work, I am confused a bit.  It seems that you have set up the swarm node between two machines, so why did add-node not work?  What specific adjustment must we make to get it to work right?

**Comment by garagatyi** [comment]
I didn't find IP that allowed me to access our API from within VM. Maybe
there is a way how to do that but I am not aware of it right now. Since I
can't access our API command returned by add-node doesn't work.

16 дек 2016 г. 8:43 PM пользователь "Tyler Jewell" <notifications@github.com>
написал:

**Comment by TylerJewell** [comment]
Help me understand the sequence:
1. Admin runs docker-machine to set up a VM.
2. Admin inside the VM then runs our docker run codenvy/cli to start Codenvy.
3. In the same VM, then admin runs `add-node` command, to get the curl option.
4. In the second VM, the admin runs the curl command.

Yes?

**Comment by garagatyi** [comment]
In my case admin runs Codenvy on the host.

**Comment by TylerJewell** [comment]
Ok - so that is funny.  no way to get to the API - but the entire point of the exercise was primarily to test add-node.  :)

**Comment by TylerJewell** [comment]
Here are some notes that I have had to do to get this to work on Docker for Windows where hyperv is the driver.

1. Must configure a new [primary virtual switch for hyperv](https://docs.docker.com/machine/drivers/hyper-v/). I labeled mine to be "primaryvs".
2. When using docker-machine must set `-d hyperv --hyperv-virtual-switch "primaryvs"`

**Comment by TylerJewell** [comment]
@skabashnyuk @garagatyi - ran my tests on this in the morning. I can see some of the challenges.

I have two follow up questions here, thinking about how we wrap up this exercise for now so that we can ship and document this properly.

1. Do the errors that you have go away if Codenvy master & the nodes are all running in separate docker-machine VMs?  Would we still need the overlay network to be created in this scenario?

2. If this simplifies the process, would it be possible for us to draft a simple automation bash script and step by step instructions for running a 2-node codenvy cluster on an Ubuntu node at Digital Ocean. The instructions would be something simple like showing exactly the commands to run:

a) Get digital ocean ubuntu node
b) Install virtualbox & docker toolbox for this node
c) Get the IP address of the host
d) Run an automation script that takes the host IP address and then
 -- a) creates two docker-machines, one for Codenvy, one as a node.
 -- b) if necessary, creates the overlay network
 -- c) starts the appropriate docker containers in each VM

We would not support this on windows, mac or other OS. Ok if we only wanted to do this on CentOS if that was easier. Alex's commands had a few locations where user had to configure CODENVY_SWARM or the overlay network IP address, and trying to see if we can avoid the admin from having to do this configuration by providing a very simple, very constrained sequence so that they can test this out.

If you think this is a massive exercise or not possible to automate in this way, then we may have to take a different approach around documenting this, and we would need a meeting to discuss.

**Comment by garagatyi** [comment]
> Do the errors that you have go away if Codenvy master & the nodes are all running in separate docker-machine VMs?

I don't know, but I'll try.

> Would we still need the overlay network to be created in this scenario?

Yes. We need it when we have 1+ nodes.

> If this simplifies the process, would it be possible for us to draft a simple automation bash script and step by step instructions for running a 2-node codenvy cluster on an Ubuntu node at Digital Ocean. The instructions would be something simple like showing exactly the commands to run: ...

I think it is neither possible nor convenient to run VMs inside of DigitalOcian VM. So I would stick to loca variant if it is possible.

**Comment by garagatyi** [comment]
Probably we can run adapted vagrant in DO droplet but we won't be able to use docker-machine.

**Comment by TylerJewell** [comment]
I was thinking that it would be docker machine and virtualbox together.

**Comment by garagatyi** [comment]
I tried running Codenvy in docker-machine and nodes are also docker-machine instances. Host OS  Ubuntu 16.04. Everything is working including saving/restoring workspaces from snapshot.

**Comment by TylerJewell** [comment]
Rock star!!!   Can you paste all of the commands again, and let's see them from beginning to end?

**Comment by garagatyi** [comment]
To start master I executed:
```
docker-machine create -d virtualbox --engine-env DOCKER_TLS=no --virtualbox-memory "2048" --engine-opt host=tcp://0.0.0.0:2375 --engine-opt="cluster-store=consul://192.168.99.100:8500" --engine-opt="cluster-advertise=eth1:2376" codenvymaster
```
To run nodes I used:
```
docker-machine create -d virtualbox --engine-env DOCKER_TLS=no --virtualbox-memory "3000" --engine-opt host=tcp://0.0.0.0:2375 --engine-opt="cluster-store=consul://192.168.99.100:8500" --engine-opt="cluster-advertise=eth1:2376" --engine-insecure-registry="192.168.99.101:5000" dnode2
```

Next step should be check that everything is OK on OSX and Windows.

**Comment by TylerJewell** [comment]
Can you amend your comment and also show the URL that you used from your browser to access the system?

I also want to see all of the docker run commands that you have to execute to start the cluster and add node commands.  So everything.

**Comment by garagatyi** [comment]
Start key value storage machine:
```
docker-machine  create  -d virtualbox  --engine-env DOCKER_TLS=no kv
```
Start KV storage:
```
docker -H <IP_of_kv_node:2376> run -d -p 8500:8500 -h consul progrium/consul -server -bootstrap
```
Start master:
```
docker-machine create -d virtualbox --engine-env DOCKER_TLS=no --virtualbox-memory "2048" --engine-opt host=tcp://0.0.0.0:2375 --engine-opt="cluster-store=consul://<IP_of_kv_node>:8500" --engine-opt="cluster-advertise=eth1:2376" codenvymaster
```
Run 1st node:
```
docker-machine create -d virtualbox --engine-env DOCKER_TLS=no --virtualbox-memory "3000" --engine-opt host=tcp://0.0.0.0:2375 --engine-opt="cluster-store=consul://<IP_of_kv_node>:8500" --engine-opt="cluster-advertise=eth1:2376" --engine-insecure-registry="<IP_of_master>:5000" dnode1
```
Run 2nd node:
```
docker-machine create -d virtualbox --engine-env DOCKER_TLS=no --virtualbox-memory "3000" --engine-opt host=tcp://0.0.0.0:2375 --engine-opt="cluster-store=consul://<IP_of_kv_node>:8500" --engine-opt="cluster-advertise=eth1:2376" --engine-insecure-registry="<IP_of_master>:5000" dnode2
```
Go into master's VM:
```
docker-machine ssh codenvymaster
```
I started codenvy, changed SWARM nodes list and restarted Codenvy. But instead we can do (didn't check correctness):
```
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/docker/.codenvy:/data  codenvy/cli:nightly init
sed -i "s/^#CODENVY_WORKSPACE_AUTO_SNAPSHOT=true.*/CODENVY_WORKSPACE_AUTO_SNAPSHOT=true/g" ~/.codenvy/codenvy.env
sed -i "s/^CODENVY_SWARM_NODES=.*/CODENVY_SWARM_NODES=<IP_OF_NODE1>:2376,<IP_OF_NODE2>:2376/g" ~/.codenvy/codenvy.env
```

**Comment by garagatyi** [comment]
I used IP returned by Codenvy CLI

**Comment by TylerJewell** [comment]
This is really nice work.

**Comment by garagatyi** [comment]
Thanks

**Comment by TylerJewell** [comment]
Where is the add-node commands that an admin must run to get the curl command to run on each node?  And where is the script where the admin runs on each node to add it into the cluster properly and register itself within the codenvy cluster?

**Comment by TylerJewell** [comment]
This is a draft of the docs.  Once we can confirm some of the details around using `codenvy add-node` we can commit the docs issue and then close this issue.

**Comment by garagatyi** [comment]
I checked this sequence on Docker for Mac and it is working too. Probably it also works on Windows.

Currently add-node command doesn't work. It was designed on the hackathon and all the things have changed since then except add-node command. So now it is outdated. 

Besides the fact that it is outdated we are considering it as error-prone and would want to change it completely. Instead of returning script than should be called on a node and uses our API this command should accept IP and port of docker daemon, add it into CODENVY_SWARM_NODES variable and restart swarm container.

**Comment by TylerJewell** [comment]
Whoa - fixing add-node is a blocker.  This is the only tactic that we have documented for customers.  This was not a decision approved by PM.

**Comment by garagatyi** [comment]
I've updated comment with the flow on addition of nodes. And I think in that case we can even start only 1 additional docker node and add it to existing node.
Fixing of add-node is not goal of that issue, so please create another issue where we with @riuvshin, @skabashnyuk and you can discuss possible solutions.

**Comment by skabashnyuk** [comment]
@TylerJewell  can we close this issue?

**Comment by TylerJewell** [comment]
Documented with this PR:
https://github.com/codenvy/codenvy/pull/1383

And improvements to simplify this workflow will be done with this issue:
https://github.com/codenvy/codenvy/issues/1386
