### ISSUE TITLE
C# intellisense not working

### ISSUE THREAD

**Issue by eat-sleep-code** [codenvy/codenvy#1183]
C# intellisense not working

**Reproduction Steps:**

Ensure that current Machine has C# language server agent and that State is set to enabled.
Open _.cs_ file
Create object oriented code, note how you are not prompted with Intellisense.

**Expected behavior:**

To be prompted with Intellisense

**Observed behavior:**

Not prompted with Intellisense

**Codenvy version:** Hosted?
**OS and version:** Windows 7 Enterprise

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: ? - Just started using Codenvy
Problem can be reliably reproduced:   Yes

**Comment by TylerJewell** [comment]
@tolusha @evidolob

**Comment by tolusha** [comment]
I've checked the latest CHE version. It works.

**Comment by bmicklea** [comment]
@eat-sleep-code you need to hit CTRL-Space to activate the auto-complete, when you do that does it appear?  If not can you send along details about the stack and project you were using?  

@tolusha is there a specific stack that is needed to use the C# intellisense?  Or an agent that needs to be added?

**Comment by tolusha** [comment]
@eat-sleep-code 
C# language server doesn't work on ubuntu. It is known issue. 
Try to create workspace from 'DEBIAN LSP' stack.

**Comment by eat-sleep-code** [comment]
@tolusha & @bmicklea  Setting up a workspace on the Debian LSP stack fixed it.    The CTRL-Space is a bit cumbersome.   Is it simply to much overhand have it work like Visual Studio where it triggers if you type a period, or opening parenthesis?

**Comment by bmicklea** [comment]
@vparfonov can you comment?  Most people do expect a "." or "(" to automatically open intellisense if it's available. Is the concern network traffic?

**Comment by eat-sleep-code** [comment]
Should a create a new "issue" requesting that the intellisense be triggered by a **_._** or _**(**_?

If we want it to work like Visual Studio (i.e. what people are used to when it comes to C# intellisense) it should also technically trigger on the first character directly following a tab, space, <, or [

**Comment by TylerJewell** [comment]
@tolusha - will you link in the issue on ubuntu C# to this thread?  Also, will you create an issue specific to adding in the additional triggers for the c# language server?

**Comment by tolusha** [comment]
https://github.com/eclipse/che/issues/2496

**Comment by tolusha** [comment]
https://github.com/eclipse/che/issues/3038

**Comment by evidolob** [comment]
Note: All that trigger characters should provide c# language server, see [language-server-protocol](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#initialize-request) **CompletionOptions**. So this feature will not work until author of c# language server will not add them.

**Comment by bmicklea** [comment]
Yes that makes sense - each language would need different triggers.

**Comment by eat-sleep-code** [comment]
Is the c# language server managed by Codenvy or is this something we have to beg and hope that a third-party developer fixes?  

It really does effect the usefulness of Codenvy for C# / .net development.   Without "automatic" intellisense, development is slowed so much with having to hit Ctrl-Space to manually invoke it over and over.

**Comment by TylerJewell** [comment]
@eat-sleep-code - sorry, don't know how we missed this additional question.  

Unfortunately, each language server is managed by the community that represents that language.  So the C# language server is run by the OmniSharp group and then we source it as a dependency.
