### ISSUE TITLE
Unexpected STDERR in the console after git checkout to a tag in console

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#1186]
**Reproduction Steps:**
1. Clone the project: https://github.com/musienko-maxim/artik-ide.git
2. After cloning run command in console like: cd /projects/your_project && git checkout 1.0.0
![anim](https://cloud.githubusercontent.com/assets/1640058/20432031/f1f7ddfc-ada5-11e6-95d6-eb7dda7749c9.gif)

**Expected behavior:**
The project should be checkouted without errors 
**Observed behavior:**
We have errors in the console
**Codenvy version:** 5.0.0-M8
**OS and version:** Ubuntu 14.0, TLS

**Comment by TylerJewell** [comment]
@musienko-maxim - is this still an actual issue?

**Comment by musienko-maxim** [comment]
Still actual

**Comment by musienko-maxim** [comment]
Not actual
