### ISSUE TITLE
Golang Debugging

### ISSUE THREAD

**Issue by JCzz** [codenvy/codenvy#1192]
[Short description of problem here]

Unable to debug the "web-go-simple" in go

**Reproduction Steps:**

[First Step]
Create a workspace from "Create new workspace from stack" and select go

Seta breakpoint

**Comment by TylerJewell** [comment]
@JCzz - I don't think this is enough steps to help reproduce your issue.  One of the things to take in to account is that Codenvy's debugging system is identical to Eclpise Che's. So in Che's debugging scenario you have to configure the debugger to connect to a debugging server.  We have lots of examples of how to do this in the Che docs.

**Comment by tolusha** [comment]
@JCzz Currently Go lang debugger is not supported.
