### ISSUE TITLE
Delete account does not work in Firefox

### ISSUE THREAD

**Issue by eivantsov** [codenvy/codenvy#1193]
As per subject

Browser console shows:

`Error: event is not defined
a</<.value@https://codenvy.io/dashboard/scripts/app-75c26559fd.js:1194:603
anonymous/fn@https://codenvy.io/dashboard/scripts/vendor-9974b0cd43.js line 77 > Function:2:282
@https://codenvy.io/dashboard/scripts/vendor-9974b0cd43.js:2808:3300
yn/this.$get</f.prototype.$eval@https://codenvy.io/dashboard/scripts/vendor-9974b0cd43.js:76:5877
yn/this.$get</f.prototype.$apply@https://codenvy.io/dashboard/scripts/vendor-9974b0cd43.js:76:6106
@https://codenvy.io/dashboard/scripts/vendor-9974b0cd43.js:2808:3280
fe.event.dispatch@https://codenvy.io/dashboard/scripts/vendor-9974b0cd43.js:68:2799
fe.event.add/g.handle@https://codenvy.io/dashboard/scripts/vendor-9974b0cd43.js:68:851
`

**Comment by ashumilova** [comment]
Merged
