### ISSUE TITLE
Add support for keyboard navigation in IDE menus

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#1194]
Keyboard navigation is oftenly used by developers.

We are not handling the keyboard navigation in the main menu of the IDE.

We need to make some improvement to make it easier to navigate through the menu with the keyboard.
- [ ] Once a menu is opened, the user should be able to use `Up Arrow` and `Down Arrow` to navigate in the menu.
- [ ] Once a menu is opened, the user should be able to navigate to the next menu by using `Tab` key

**Comment by TylerJewell** [comment]
Already in eclipse che - not for codenvy.
