### ISSUE TITLE
Confusion regarding how to store workspace definition in github

### ISSUE THREAD

**Issue by larrytalley** [codenvy/codenvy#1206]
Thanks for any info and for all the great work, Codenvy is an amazing advance for our industry!

But I'd like my workspace definition to live in github.

I know how to preserve a Dockerfile or a Docker compose file and how to consume it to source a stack. I know how to preserve project code and consume it. But I don't know how to store the entire workspace, tying together the stack and the project code (or project code reference.)

I have exported a workspace as a JSON file that seems to be the right artifact, but, I don't know how to import that file. When I try to use it as a custom stack definition there doesn't appear to be an option for the workspace JSON specification. I don't see any "import workspace from JSON" option anywhere.

Am I missing something or is this capability just not exposed yet?

**Comment by slemeur** [comment]
Hi @larrytalley,

You are right that this capability is not exposed at this moment. With the latest version, we did some changes in the flows to create workspaces and stacks and have not yet push this feature back.

The good news is that it will be there in the upcoming milestone of 5.0.0 - so this issue will be addressed with the release of 5.0.0-M8. You can follow the milestone [here](https://github.com/codenvy/codenvy/issues?q=is%3Aopen+is%3Aissue+milestone%3A5.0.0-M8). 

Here is a snapshot of it:
![create json](https://cloud.githubusercontent.com/assets/1636769/20542368/9d1b52dc-b101-11e6-8081-979db10fa357.png)

We are also planing some more work on this layout to make it easier and simpler to use.

Until M8 is out - if it's a blocker for you, you could create the workspace by using your json and the following rest api: https://codenvy.io/swagger/#!/workspace/create

Hope this help.

**Comment by larrytalley** [comment]
Perfect, thanks!
