### ISSUE TITLE
HTTPS on Docker with Apache Proxy?

### ISSUE THREAD

**Issue by HalfEatenPie** [codenvy/codenvy#1207]
I installed Codenvy on a standard Linux Installation (Ubuntu 16.04 64-bit).  I have deployed it using docker as suggested [here](https://github.com/codenvy/codenvy/blob/master/docs/README.md#installation).  I'd like to also install HTTPS for it, however I'll be using LetsEncrypt for the SSL certificate.  Therefore, I believe I'd need to configure Apache for the proxy.  

Now my question, is the readme.io correct?  Is there any way to proxy all traffic via apache and SSL without modifying the configuration file within the docker container?  I was originally thinking of binding all the ports needed for Codenvy locally and then proxying it through in that manner.  Would this work?

If I modify the docker container files, wouldn't it get overwritten or undone since I currently configured it to run with latest?  

**Reproduction Steps:**

Install Codenvy via Docker.  
Go to http://<FQDN>
Go to https://<FQDN>

**Expected behavior:**
Expect a valid SSL Certificate on https (port 443)

**Observed behavior:**

Currently all traffic is sent via HTTP (Port 80)

**Codenvy version:** 5.0.0-M7
**OS and version:** Ubuntu 16.04 64-bit

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: N/A
Problem can be reliably reproduced: Yes

**Diagnostic bundle**
Execute the script on [this page](https://github.com/codenvy/codenvy/wiki/Support-Diagnostics) and post public link to the bundle here.

**Comment by TylerJewell** [comment]
The README (docs.codenvy.com) are for an older version & puppet-based installation.  They are not compatible with the docs on the README.md file, located at github.com/codenvy/codenvy/docs/README.md.  We are in the process of switchign over to the Docker-ized version.

The docs on the README.md are accurate and tested.  All you need to do is to modify the /confing/codenvy.env file. There are two variables that you set within that file to configure Codenvy to use HTTP/S.  See the section "HTTP/S" in the docs.

I am not sure what you mean by modifying the docker container files ... can you elaborate?

**Comment by HalfEatenPie** [comment]
Thanks for the response.  It seems I misunderstood for a second there about where the configuration files was and I thought it was actually inside the container.  

This may be a bit unique, but would there be any support for automatic webroot access as well? For automated SSL certificates like LetsEncrypt, they verify domain ownership by placing a file in the webroot.  Would this automation be possible through modifying values in the env file?

**Comment by TylerJewell** [comment]
I am not sure I follow.  You provide your cert in the .env file, and then our system registers that.  I am not sure what automatic webroot access means beyond what we do with it.

See: https://github.com/codenvy/codenvy/tree/master/docs#https

**Comment by HalfEatenPie** [comment]
Ahh sorry what I meant by automatic webroot access as access to lets say <FQDN>/<file> or something.  LetsEncrypt's automatic SSL provisioning system either binds to port 80 or 443 and displays a key to authenticate to sign the SSL key (generally speaking).  However, if there is a webroot folder/access available then you can configure their automated certificate renewal system to use that instead of binding to port 80.  

It's not that big of an issue.  I'll simply just use a regular paid SSL then.  Thanks!

**Comment by TylerJewell** [comment]
Cool.
