### ISSUE TITLE
Workspace Runtime "Download Outputs" bug

### ISSUE THREAD

**Issue by HalfEatenPie** [codenvy/codenvy#1219]
When starting up a new workspace there's a box on the top that says "Starting Workspace runtime...  Retrieving the stack's image and launching it" with a link that says "Download outputs".  When you click on the download outputs link, you get a download to a .txt file, but when opened it contains the phrase "null". 

**Reproduction Steps:**

- Start a new instance
- While the instance is setting up click "download outputs"
- Download the file
- Open the file

**Expected behavior:**

I expect the outputs from the instance setting up

**Observed behavior:**

The file contains nothing but "null"

**Codenvy version:** 5.0.0-M7
**OS and version:** Ubuntu 16.04 64-bit

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: No idea
Problem can be reliably reproduced: Yes.  Every single time. 

**Diagnostic bundle**
Execute the script on [this page](https://github.com/codenvy/codenvy/wiki/Support-Diagnostics) and post public link to the bundle here.

**Comment by TylerJewell** [comment]
@ashumalova - was this fixed in m7 or was it for m8?

**Comment by AndrienkoAleksandr** [comment]
Actual for 5.0.0-M8-SNAPSHOT.

**Comment by TylerJewell** [comment]
This was solve in 5.0.0 GA release.
