### ISSUE TITLE
Persistent Container Online

### ISSUE THREAD

**Issue by HalfEatenPie** [codenvy/codenvy#1220]
Just a short question.  I read that if there's more than 10 minutes of inactivity the workspace/container is turned off.  As we currently have Codenvy Fair source license (free 3 users) on our on-premise hosted option, I was wondering if it's possible for us to either extend this inactivity or keep certain workspaces on constantly?

**Comment by TylerJewell** [comment]
That ten minutes of activity is only for our hosted version.  I believe the default is 4 hours in the installed version.  If you installed the docker version of codenvy then there is a property in codenvy.env you modify to change this.

**Comment by HalfEatenPie** [comment]
Found it.  Awesome thanks @TylerJewell.

Turned out the on-premise version was still configured to 10 minutes (assuming the variable was stored in milliseconds).
