### ISSUE TITLE
Bitnami Container Images

### ISSUE THREAD

**Issue by HalfEatenPie** [codenvy/codenvy#1222]
This may not be appropriate here but figured wouldn't be bad to ask. 

There has been deployment errors on our side with Bitnami Containers.  Codenvy "Ready-to-Go" stacks are not affected.  I've submitted an issue report to Bitnami's Github project.  

**Bitnami Laravel**
```
Could not start workspace test-wksp-1c7o. Reason: Start of environment default failed. Error: Restoring of workspace workspaceylt78i70ue5brgvx filesystem terminated on node. Process failed. Exit code 12
```

**Bitnami Codeigniter** and **Bitnami Symfony**
```
Could not start workspace test-wksp-8jhs. Reason: Start of environment default failed. Error: Error occurs while initializing command [/bin/sh, -c, trap '[ -z "$(jobs -p)" ] || kill $(jobs -p); [ -e /tmp/docker-exec-46.pid ] && rm /tmp/docker-exec-46.pid' EXIT; echo $$>/tmp/docker-exec-46.pid; command -v pidof >/dev/null 2>&1 && { pidof sshd >/dev/null 2>&1 && echo 0 || echo 1 } || { ps -fC sshd >/dev/null 2>&1 && echo 0 || echo 1 }] in docker container c1658d38e6ce0b773956a1ed7ad3f022bed72580a07cc205ad4876d81ce68443: Error response from docker API, status: 500, message: {"message":"Container c1658d38e6ce0b773956a1ed7ad3f022bed72580a07cc205ad4876d81ce68443 is not running"}
```

Surprisingly this issue does not occur on Bitnami Ubuntu base image.  I haven't tested this out with all Bitnami images so can't be certain if all are impacted. 

What is error code 12?  It seems something that's unique to Eclipse Che but not sure. 

**Reproduction Steps:**

1. Create a new workspace
2. Select a Bitnami image
3. Deploy
4. Wait for setup

**Expected behavior:**

For the container to be ready

**Observed behavior:**

Error messages. 

**Codenvy version:** 5.0.0-M7
**OS and version:** Ubuntu 16.04 64-bit

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: N/A
Problem can be reliably reproduced: Yes

**Diagnostic bundle**
Execute the script on [this page](https://github.com/codenvy/codenvy/wiki/Support-Diagnostics) and post public link to the bundle here.

**Comment by eivantsov** [comment]
@HalfEatenPie I was able to start Laravel on codenvy.io

The error you mentioned is not related to the image itself. Looks like problems with rsync when restoring projects for a workspace.

![image](https://cloud.githubusercontent.com/assets/5337267/20617534/96928596-b2f2-11e6-8e6f-4bff1c583e93.png)

Codeigniter does fail with error:

`[dev-machine] [STDERR] nami ERROR watch /opt/bitnami/mariadb/logs/mysqld.log EMFILE`

**Comment by HalfEatenPie** [comment]
Thanks @eivantsov.  It seems I was using an older version of the image (not sure how specifically as I was using it from the panel) and apparently it wasn't tested on 5.0.0-M7.  I'll be updating it to 5.0.0-M8 and see what happens from it.

**Comment by TylerJewell** [comment]
Assuming this was fixed...
