### ISSUE TITLE
Rename License in wsmaster/codenvy-hosted-api-license to SystemLicense

### ISSUE THREAD

**Issue by sleshchenko** [codenvy/codenvy#1223]
Rename `License` in [wsmaster/codenvy-hosted-api-license](https://github.com/codenvy/codenvy/blob/master/wsmaster/codenvy-hosted-api-license/) to `SystemLicense`.
So it is also needed to change path in [LicenseService](https://github.com/codenvy/codenvy/blob/master/wsmaster/codenvy-hosted-api-license/src/main/java/com/codenvy/api/license/server/LicenseService.java) to `/license/system/`

These changes should be made to void confusion License and AccountLicense

**Comment by dmytro-ndp** [comment]
@sleshchenko: is this issue connected to _Dockerised Codenvy_ only, or should be realized for Codenvy on-prem with _installation manager_ as well?
