### ISSUE TITLE
OAuth with VSTS

### ISSUE THREAD

**Issue by armartinez** [codenvy/codenvy#1230]
Login with Visua Studio Team Services credentials always asks for Authorization

**Reproduction Steps:**

-Login using VSTS credentials, authorization dialog shows up
-Logout
-Login again and authorization shows up again.

**Expected behavior:**

I would expect the authorization dialog to show up once.

**Observed behavior:**

Evert time I log in using VSTS, I need to authorize the application therefore creating duplicate entries in my authorized application list.

**Codenvy version:** codenvy.io
**OS and version:** Chrome 54

**Comment by TylerJewell** [comment]
@skabashnyuk - interesting, perhaps some sort of regresssion?

**Comment by skabashnyuk** [comment]
Yes. Confirms. Will take a look.

**Comment by skabashnyuk** [comment]
won't fix

**Comment by armartinez** [comment]
Any reason why ?
