### ISSUE TITLE
"https://www.codenvy.io" does not open.

### ISSUE THREAD

**Issue by ManasN** [codenvy/codenvy#1232]
When typed "https://www.codenvy.io" in browser, codenvy does not open.
![screenshot from 2016-11-26 21-12-27](https://cloud.githubusercontent.com/assets/9447030/20641775/5931fe6e-b425-11e6-95e9-889c0c36af9f.png)

**Reproduction Steps:**

1) Type "http://www.codenvy.io" in browser's address bar.

**Expected behaviour:**

Expected behaviour is that codenvy.io should open.

**Observed behaviour:**

Browser gets "https://www.codenvy.io/codenvy.io/codenvy.io/codenvy.io/codenvy.io/codenvy.io/codenvy.io...."
chain instead.

**Codenvy version:** Current website version of 'codenvy.io'
**OS and version:** Ubuntu 16.04, Firefox 50, Chrome 54.

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: Don't know.
Problem can be reliably reproduced: Yes

**Comment by TylerJewell** [comment]
Super weird.  Can you try in incognito mode, in chrome, and are you behind a firewall that is blocking access?

**Comment by ManasN** [comment]
Is it working for you?

I just tried it in incognito, same thing.
![screenshot from 2016-11-27 12-17-38](https://cloud.githubusercontent.com/assets/9447030/20646169/b84faeb6-b49b-11e6-9e69-215d9ea927f2.png)

The only firewall I had is ufw and I disabled it this time, still no avail. 
I think maybe the www redirection from Nginx/Apache is going wrong here.

**Comment by ManasN** [comment]
Can confirm it is not my local or netowrk problem. 
Tried on a different network, different laptop.

Tried using an online web proxy (kproxy) (screenshot attached).
![screenshot from 2016-11-27 12-22-21](https://cloud.githubusercontent.com/assets/9447030/20646230/70a82312-b49c-11e6-8943-0d076c9e0e46.png)


I am pretty sure server redirection is at fault here.

**Comment by gazarenkov** [comment]
Confirmed, use codenvy.com without leading "www." meantime

**Comment by gazarenkov** [comment]
Works for me now (in incognito since old page was cached apparently), thanks @skryzhny

**Comment by ManasN** [comment]
Works for me too. May I know what was wrong? 
Thanks.
