### ISSUE TITLE
How to build a project using Ant?

### ISSUE THREAD

**Issue by matthiashhh** [codenvy/codenvy#1233]
I'm trying to build a project using Ant. 

I've forked https://github.com/pentaho/pentaho-kettle, created a workspace using the Java stack and added a project by importing the forked github repo. Next I tried to build it using the default build command, and got the following error:

> [ERROR] [ERROR] Some problems were encountered while processing the POMs:
> [FATAL] Non-readable POM /projects/pentaho-kettle/pom.xml: /projects/pentaho-kettle/pom.xml (No such file or directory) @ 

Reading the [README of the github repo](https://github.com/pentaho/pentaho-kettle/blob/master/README.md) makes me realize that the project should be built using Ant:

> 1. Run `ant clean-all resolve create-dot-classpath`
> 2. Run `ant dist`

So I make a custom command:
`cd {current.project.path} && ant clean-all resolve create-dot-classpath`

Now I get the following error:

> [dev-machine] /bin/bash: ant: command not found
> [STDERR] /bin/bash: ant: command not found

At [Codenvy's blog](http://blog.codenvy.com/cooking-custom-build-environments/) it is written:

> At Codenvy we love Ant and Maven and have them as our default build environments.

So how can I build my project using Ant?

**Comment by eivantsov** [comment]
@matthiashhh Ant isn't installed in the default Java stack. You may do it yourself though.

First off, reconfigure your project to be Java project type, not Maven (Project > Update Project configuration).

Then, create a custom stack using the following recipe:

```
FROM eclipse/ubuntu_jdk8
RUN wget -qO- "http://www-us.apache.org/dist/ant/binaries/apache-ant-1.9.7-bin.tar.gz" | sudo tar -zx -C /opt/
ENV PATH /opt/apache-ant-1.9.7/bin:$PATH
```

**Comment by matthiashhh** [comment]
Thanks, it solved my problem!
