### ISSUE TITLE
Puppet should set Password Expires for the `codenvy` user to `never` explicitly

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#1241]
We should set the password expiration policy explicitly to `never` for the `codenvy` user. If we don't set this then the password expiration policy is taken from the underlying image. In the case of AWS the password expiry is auto-set in the image to every 6 months.

Once password expires, even with a working key, the master node can't connect to workspace nodes and no workspaces can be created.

**Comment by bmicklea** [comment]
@eivantsov has more details if needed.

**Comment by riuvshin** [comment]
yeah please provide more info, this is absolutely not clear what to do here. and why you decided it is a puppet thing.

**Comment by riuvshin** [comment]
Done https://github.com/codenvy/deployment/commit/4b80cbece99536c9757bb092e202c0022cfe8c77
