### ISSUE TITLE
SSH connection to aws codecommit fail

### ISSUE THREAD

**Issue by ogonbat** [codenvy/codenvy#1244]
I have a git repo in AWS codecommit. I use ssh connection.
when i test the connection between codenvy to aws codecommit

`ssh git-codecommit.us-east-2.amazonaws.com`

the ssh command return

`ssh: connect to host git-codecommit.us-east-2.amazonaws.com port 22: Connection timed out`

have some firewall restrictions?
could you open to amazon codecommit?

thanks in advance

**Comment by TylerJewell** [comment]
@bmicklea @eivantsov - is this a white listing issue?  We just certified codecommit support in codenvy so surprised that an ssh to codecommit would fail.

**Comment by gazarenkov** [comment]
@skryzhny need to whitelist amazonaws I think

**Comment by skryzhny** [comment]
Collected IPs from list of codecommit server http://docs.aws.amazon.com/codecommit/latest/userguide/setting-up-ssh-unixes.html

Added them to whitelist.

Problem is that these IPs may change  over time.
