### ISSUE TITLE
ssh and openshift

### ISSUE THREAD

**Issue by alespstemc** [codenvy/codenvy#1247]
Hello!

I'm trying to import my project hosted on openshift via git repository. I've already added the public key on openshift console, generated the key via IDE, but the connection always time out.

How can i resolve this?

Thanks in advance!

**Reproduction Steps:**

Generate SSH key via Profile>Preferences>SSH>VCS>Generate Key
Put on the host field, my host: manutencao-stemc.rhcloud.com
Copy the key to the openshift console
Import my project via Workspace>Import Project>Source Control>GIT
Put on the URL field the source code url: ssh://57712*****1e6691d700001d@manutencao-stemc.rhcloud.com/~/git/manutencao.git

**Expected behavior:**

Import the files from the repository and create the project

**Observed behavior:**

After a while, the following message has appeared: java.lang.IllegalStateException: org.eclipse.che.ide.websocket.rest.exceptions.ServerException: ssh://5771*****c1e6691d700001d@manutencao-stemc.rhcloud.com/~/git/manutencao.git: Connection timed out

**Codenvy version:** 5.0.0-M7
**OS and version:** Windows 7 Professional

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: Yes
Problem can be reliably reproduced: Yes

**Comment by gazarenkov** [comment]
rhcloud have to be whitelisted for SSH, @skryzhny

**Comment by bmicklea** [comment]
@skryzhny has this been resolved?

**Comment by eivantsov** [comment]
@alespstemc can you please4 check if you still have issues with rhcloud?

**Comment by alespstemc** [comment]
@eivantsov, it is publicly hosted.

**Comment by TylerJewell** [comment]
@skryzhny - FYI - we should try to address this or close as old issue.

**Comment by eivantsov** [comment]
We need IPs to be whitelisted.

**Comment by alespstemc** [comment]
I've faced the same problem under my corporate network (with restricted access - meaning the majority of ports are blocked). We tried to whitelist the names rhcloud.com and amazonaws.com and ports 22 and 443 with no success. I think that there is some other address involved in the transaction.

Thanks!

**Comment by eivantsov** [comment]
@alespstemc I mean IPs have to be whitelisted on our side.

Are you using a public RH service or an on prem openshift?

**Comment by TylerJewell** [comment]
I got an email from our admin about the whitelisting.  It seems that Red Hat is mixing their OpenShift instance IPs with their application user space IPs.  And as a result, there is a wide range of IP addresses that are making it challenging for us to know which IPs need to be whitelisted to gain access to Red Hat's services.  We cannot open the entire IP range as we have already received some security warnings from misbehaving apps within their infrastructure.  

We have opened port 443, by the way, to their entire range.  It's only port 22 that we have to white list one at a time.

**Comment by alespstemc** [comment]
@eivantsov, i'm using a public RH service.

**Comment by eivantsov** [comment]
@alespstemc can you give it a try? We have whitelisted IP of the instance that hosts your OpenShift application

**Comment by alespstemc** [comment]
@eivantsov, still getting the timeout message!

**Comment by alespstemc** [comment]
@eivantsov , now it's working flawlessly! Thanks for your attention.
