### ISSUE TITLE
Revamp Codenvy docs for 5

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#1248]
This is an epic to track progress toward a revamped doc set and structure for Codenvy 5.

## Intro
- [x] Brad: Updated homepage content (`index.html`)
- [x] James: Links for nightly and 5.0.0 versioned docs for `index.html`
- [x] Stevan: Updated homepage styles (`index.html`)

### Goal of Review
Identify:
- Confusing or out-of-date content
- Check all links
   - Links to other docs pages should be referenced as `[link text]({{base}}/docs/admin-guide/managing/index.html)`
- No line wraps in code boxes
- Code indents = 2 spaces
- Style problems (route to Stevan)
- Situations where "Che" is mentioned
- Situations where advice is inappropriate for Codenvy (e.g. setting Che variables)
- Images / diagrams are sized correctly and up-to-date

### Section Reviews
- [x] Eugene: Add new architecture graphic to `codenvy-docs/src/main/_docs/admin-guide/admin-installation.md`
- [x] Brad: CODENVY - admin-guide
- [x] Brad: CODENVY - integration-guide
- [x] Brad: CODENVY - getting-started
- [x] Brad: CHE - workspace-administration/ws-admin-intro.md
- [x] Brad: CHE - workspace-administration/ws-agents.md
- [x] ???: CHE - workspace-administration/ws-data-model-samples.md
- [x] ???: CHE - workspace-administration/ws-data-model-stacks.md
- [x] ???: CHE - workspace-administration/ws-machines.md
- [x] ???: CHE - workspace-administration/ws-recipes.md
- [x] ???: CHE - workspace-administration/ws-samples.md
- [x] ???: CHE - workspace-administration/ws-stacks.md
- [x] ???: CHE - workspace-administration/ws-volume-mounts.md
- [x] Stevan: CHE - user-guide
  - [x] Stevan: double-check image links
- [x] Stevan: CHE - chedir-portable-workspaces
  - [x] Stevan: double-check images links
- [x] Stevan: CHE - workspace-server
  - [x] Stevan: double-check images links
- [x] Stevan: CHE - write-plugins
  - [x] Stevan: double-check images links
- [x] ???: CHE - OpenShift
- [x] ???: CHE - Tutorials

## Doc writer tooling
- [x] `docs.sh` script to allow anyone to run Jekyll and edit docs on their local machine
- [x] Update pom.xml so maven builds code and docs

## Packaging
- [x] Stevan: Doc styles complete
- [x] Stevan: Docs integrated into the dashboard
- [x] James: CI setup for generating static HTML hosted at Che and Codenvy
- [x] Stevan: Docs available in on-prem distribution (depends on #1266)
- [x] James: Favicons missing from generated HTML
- [x] ???: Need to understand why docs are not working properly with nightly5

## Conversion to MD
- [x] Convert Get Started Guide to a set of markdown files
- [x] Convert Admin Guide to a set of markdown files
- [x] Convert LDAP Guide to a set of markdown files
- [x] Convert User Guide to a set of markdown files
- [x] Convert DevOps Guide to a set of markdown files
- [x] Convert White Label Guide to a set of markdown files
- [x] James: Experiment with "includes" for Che files to allow portions to be customized for Codenvy audience - start with `user guide > sharing` page

### Admin Guide changes
- [x] Add "Runbook" section as a new MD under the admin guide (runbook.md)
- [x] Add "Configuring Firewalls" to configuration.md

**Comment by JamesDrummond** [comment]
@bmicklea The structure has changed a lot. Now everything is broken up into more sections similar to how readme.io . was. Not sure if you want to rewrite the original issue. Majority of work is complete for conversion to md.

Should we create separate md file for the admin enhancements above or include them in existing docs below:
```yaml
- title: Admin Guide
  docs:
  - get-help
  - system-requirements
  - installation
  - usage
  - configuration
  - ldap-integration
  - managing
  - cli
  - team
```

**Comment by slemeur** [comment]
Integration of the docs inside of the product can be tested on a10.codenvy-stg.com
