### ISSUE TITLE
Codenvy in docker: Enable postgresql logs

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#1250]
I would like to see postgresql logs when running codenvy in docker. 
Proposed changes from current config
            log_min_duration_statement = 0 <- possible need to be configurable 
            log_line_prefix = 'user=%u,db=%d,app=%aclient=%h '
            log_checkpoints = on
            log_connections = on
            log_disconnections = on
            log_lock_waits = on
            log_temp_files = 0
            log_autovacuum_min_duration = 0
            log_error_verbosity = default

**Comment by riuvshin** [comment]
Done
