### ISSUE TITLE
Python3.5 requirements.txt

### ISSUE THREAD

**Issue by thalesmaoa** [codenvy/codenvy#1258]
I'm not able to import a module in Codenvy.
Tried adding it to requirements and using pip command directly but it didn't work.

main.py
`from Pillow import *
print("Hello, world!")`

`sudo virtualenv /env && sudo pip install --upgrade pip && sudo pip install -r requirements.txt && python main.py`

https://github.com/codenvy/codenvy/issues/385#issuecomment-233291499

pip runs fine, but when I run main.py I always get:

`No module named`

Any help?

**Comment by eivantsov** [comment]
This is the right command to use:

`sudo virtualenv --python=/usr/local/bin/python3 /env && sudo pip install --upgrade pip && sudo pip install -r requirements.txt && python main.py`

Also, your python script should be:

```
from PIL import *
print("Hello, world!")
```

**Comment by thalesmaoa** [comment]
--python=/usr/local/bin/python3

worked just fine!

Thank you!

-
Thales Alexandre Carvalho Maia


2016-12-13 6:41 GMT-02:00 Eugene Ivantsov <notifications@github.com>:
