### ISSUE TITLE
Docs packaging.

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#1266]
In branch jekyll-docs.
We need to 
1. build with maven docs ```jekyll build``` in docs/target/_site
2. Package docs/target/_site in war file
3. Deploy it as ```docs``` application in codenvy

Do not forget to configure ```mvn clean``` to correctly remove generated files.

**Comment by JamesDrummond** [comment]
@skabashnyuk I change the destination folder in the jekylll _config.yml . https://github.com/codenvy/codenvy/commit/1c1517efdb1f474a11eb66914d37901cc87aad30

**Comment by skabashnyuk** [comment]
Deploy it as docs application in codenvy - not done
