### ISSUE TITLE
Not all editor tabs are closed after stopping workspace (regression)

### ISSUE THREAD

**Issue by artaleks9** [codenvy/codenvy#1270]
**Reproduction Steps:**
* Expand a project and open two or more files.
* Perform the stop workspace.

**Expected behavior:**
* The editor tabs should be closed.

**Observed behavior:**
* Editor tabs still stay open.

**Codenvy version:**  5.0.0-M8
**OS and version:** Ubuntu 14.04

**Additional information:**
* Problem only started happening recently, didn't happen in an older version of Codenvy: No
* Problem can be reliably reproduced: Yes
* See the attachment:
![editor_tabs](https://cloud.githubusercontent.com/assets/5408906/20829176/a55f4514-b883-11e6-806a-6c26528d6432.png)

**Comment by riuvshin** [comment]
@garagatyi 
this happens only on codenvy in docker I think it may be related to rsync agent

**Comment by artaleks9** [comment]
I close this issue, because it is a duplicate of the https://github.com/eclipse/che/issues/2372.

**Comment by artaleks9** [comment]
Problem cannot be reliably reproduced on the Che, but on the hosted version it is reproduced.

**Comment by artaleks9** [comment]
The bug is fixed and not reproduced.
