### ISSUE TITLE
Add menus item to embed docs into the product

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#1274]
Related to the work in the following issue: https://github.com/codenvy/codenvy/pull/1257

We want to add links into the product in order to allow the user to directly access the documentation.

In the dashboard, we will add a new section:
![screen shot 2016-12-02 at 12 15 07](https://cloud.githubusercontent.com/assets/1636769/20832418/7baf5068-b88a-11e6-93f0-69419abc3b57.png)
When the user will click on it, it will open the docs into the same browser's tab and we will keep the left-sidebar (so it will be embedded as an iframe)

In the IDE, into the help menu, we will rework the menu with one more item:
- Support
- Docs
- About

![screen shot 2016-12-02 at 12 21 15](https://cloud.githubusercontent.com/assets/1636769/20832480/d07a8d42-b88a-11e6-9bf8-423b2bc7c56a.png)

**Comment by ashumilova** [comment]
Fixed by https://github.com/codenvy/codenvy/pull/1325
