### ISSUE TITLE
Codenvy in Docker: testing of  work behind http proxy

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#1275]
Setup http proxy scenario and verify that we can install and run behind a proxy. We had issues with a customer where certain ports were not being discovered, and it may not require some environment variables that we have. If possible, we can remove unnecessary variables from codenvy.env

Test this for both Che and Codenvy, as the syntax is similar but not quite identical.
See the new Che CLI docs at:
https://github.com/eclipse/che/tree/master/docs

**Comment by mshaposhnik** [comment]
To run Codenvy under proxy the following configuration setup needed:
 - Docker daemon - to be able to download images (_/etc/systemd/system/docker.service.d_ on Centos or _/lib/systemd/system/docker.service_ on Fedora)
```
Environment="HTTP_PROXY=http://proxy.ua.codenvy-dev.com:3128/" "HTTPS_PROXY=http://proxy.ua.codenvy-dev.com:3128/" "NO_PROXY=localhost,127.0.0.1"
```

 - Docker run - to start containers with correct settings
```
docker run -it --rm -e "https_proxy=http://proxy.ua.codenvy-dev.com:3128" \
                    -e "no_proxy=localhost,127.0.0.1,172.17.0.1" \
                    -v /var/run/docker.sock:/var/run/docker.sock \
                    -v /home/makis/.codenvy:/codenvy \
                    -v /home/makis/.codenvy/backup:/backup \
                    -v /home/makis/projects/codenvy:/repo  codenvy/cli:nightly $@
```
 - Agent and master configuration for java in _codenvy.env_ (set by puppet i believe) :
Master:
```
CODENVY_HTTP_PROXY_FOR_CODENVY=http://proxy.ua.codenvy-dev.com:3128/
CODENVY_HTTPS_PROXY_FOR_CODENVY=http://proxy.ua.codenvy-dev.com:3128/
CODENVY_NO_PROXY_FOR_CODENVY=localhost,127.0.0.1,172.17.0.1,codenvy-swarm,
```
Agent:
```
CODENVY_HTTP_PROXY_FOR_CODENVY_WORKSPACES=http://proxy.ua.codenvy-dev.com:3128/
CODENVY_HTTPS_PROXY_FOR_CODENVY_WORKSPACES=http://proxy.ua.codenvy-dev.com:3128/
CODENVY_NO_PROXY_FOR_CODENVY_WORKSPACES=localhost,127.0.0.1,172.17.0.1
```

**Comment by TylerJewell** [comment]
Max - when we tested a similar config within tiaa they could not create a workspace.  But we did not have the swarm added to the nonproxy.  Can you explain that part?

**Comment by mshaposhnik** [comment]
There is still issue when IDE occasionally loading slow - it is due to statically linked skippts in _IDE.jsp_ and _init.js_ - browser waits for the analytic scripts like http://www.googletagmanager.com/gtm.js and http://www.google-analytics.com/analytics.js to load.

**Comment by TylerJewell** [comment]
One other interesting detail for tiaa. On the docker run they could not get our internal curl commands to work with http proxy env vars.  Instead they had to pass in ALL_PROXY.

**Comment by mshaposhnik** [comment]
@TylerJewell yes, the swarm and HOST address (172.17.0.1)  are necessary to be in the no_proxy part.

**Comment by TylerJewell** [comment]
Why is that in the codenvy proxy but not in the workspace proxy?

**Comment by TylerJewell** [comment]
Another question for you.  Do you know if it is possible for a docker container to query a daemon for its proxy config?  If "yes" I could adapt the cli to auto detect daemon proxy and then automatically use that.

**Comment by TylerJewell** [comment]
Is there a way that others can test running the cli with your proxy config?  We will want to try and detect and auto set as many properties as possible.

**Comment by mshaposhnik** [comment]
@TylerJewell 
>Why is that in the codenvy proxy but not in the workspace proxy?
Because only master calls swarm. Workspaces are not using swarm directly.

>Do you know if it is possible for a docker container to query a daemon for its proxy config?
Need to investigate this.

>Is there a way that others can test running the cli with your proxy config?
Didn't fully understood the question. Anybody in the office can use our preoxy. People from the outside, need to configure another one.

**Comment by TylerJewell** [comment]
I would like to make a series of improvements to the CLI to auto-detect Docker's proxy settings and then automatically set the docker run attributes AND the Proxy for codenvy variables.  In order to implement these changes, I would need a proxy configuration that I can use.

Is there a way for me to VPN or SSH into a server that is inside of Cherkassy for me to test the CLI with a proxy?  I do not have an easy ability to set up a configuration here.

**Comment by skryzhny** [comment]
@TylerJewell 
We have no servers in Cherkasy anymore.
We use proxys on one of our AWS instances.
For obvious security reason we allowed connect to that proxys from limited IPs, currently only Cherkasy's office.
I can add your IP to list of allowed, If you have permanent one.

**Comment by TylerJewell** [comment]
I will need to create a digital ocean node and use that for testing.  I'll do that today and get you an IP address to be added to the white list.

@mshaposhnik - it seems that "docker info' provides information about the daemon configuration.  I think it should have the proxy configuration in there, so when we start the CLI, we could potentially parse that information during CLI bootstrap, auto-detect appropriate proxy settings, and then export the right variables, and also configure the codenvy.env properly as well.

**Comment by mshaposhnik** [comment]
Ok. Seems we need issue for that or even use https://github.com/eclipse/che/issues/3259 (just clarify it a bit)

**Comment by TylerJewell** [comment]
@mshaposhnik - I started working on this issue today, and ran into some challenges. It has proven difficult for me to setup a good proxy environment (the setup I did on digital ocean was difficult to demonstrate whether my machine was using the proxy for internet or not), so could not really test a situation where the proxy was on / off.

The basic idea of what I want to implement, and maybe you can help me with a screen share or doing it on your machine, as I don't think this would take more than 2 hours to do:

1) in the check_docker() method, we should check to see if the docker daemon has proxy environment variables set for it.  This would be running a "docker info" in the CLI container, and then (hopefully) this returns whether the daemon is configured with a proxy or not.  If the proxy information is not available then we have a problem.

2) We would then use these values to export the values for the container + scripts at large.  We would also then in the init() or config() method, we would update codenvy.env & che.env to set the PROXY_FOR_CODENVY values with the right values.

**Comment by mshaposhnik** [comment]
@TylerJewell Ok, is there any branch where you started implementing this?

**Comment by TylerJewell** [comment]
Yes, there is a cli-improvements branch in Che and codenvy repos where I am starting on a variety of changes.  

I will add the logic to pull the proxy values from the docker info command today and then I can share with you for testing.

**Comment by TylerJewell** [comment]
@mshaposhnik - can you please run through the same tests that you did for Codenvy with Che please?  The sequence is unclear for me with Che because there are fewer variables:
1. Obviously, the docker deamon does not change.
2. We can also pass in the proxy variables as part of the docker run, but we can do an export of those from within the script so that they get set.
3. But what is confusing for me is that Codenvy has two sets of proxy values - one for CODENVy and one for workspaces.  But the che.properties only has a single set of values - for workspaces. 

So can you attempt to just manually run Che with the CLI behind a proxy and let me know your configuration?

**Comment by TylerJewell** [comment]
@mshaposhnik - we are ready for some testing.

1. Get this branch:
https://github.com/eclipse/che/pull/3301

2. Build /dockerfiles/base

3. Get this Codenvy CLI branch:
https://github.com/codenvy/codenvy/pull/1294

4. You will need to build the CLI - /dockerfiles/cli

5. You can then set or unset your Docker daemon's proxy configuration.  We then use those values to set the right values in codenvy.env.  Now, one scenario is that if HTTP_PROXY is set but NO_PROXY is not set, then the additional 'codenvy-swarm' is not appended to the NO_PROXY.  If that must be set no matter what, then I need to make a modification.

**Comment by TylerJewell** [comment]
I've merged the PR for this.
