### ISSUE TITLE
figure out how to update users codenvy.env che.env files

### ISSUE THREAD

**Issue by riuvshin** [codenvy/codenvy#1278]
today we generate codenvy.env or che.env files for users and we never touch those files because it is the only place for users to edit and change configuration. 
Goal of that issue is to find a way how we will update env files in case of adding new props.
This is really serious issue because without that users after upgrades will not be able to configure any new property.

@TylerJewell @benoitf I think this is a blocker for shipping codenvy in containers.

**Comment by bmicklea** [comment]
@riuvshin can you start writing out and planning the integration and upgrade test scenarios?

**Comment by benoitf** [comment]
when I was thinking on this issue, I was thinking that we should have a version for the che.env file. Because today we have some variables but we don't know how to which version it was issued

so, when updating a version of che, we could launch migration or property names, etc to match the version of the current CLI

So I would say a requirement would be to have a version of the system that issue the first time the template for che.env
Then, any tools can upgrade the properties

**Comment by riuvshin** [comment]
agree with @benoitf my vision was to have for each version template of env file for that concrete version and some how merge it with existing one this way missing lines in existing env file will be added from template. I have no idea how to implement that but this is some thing close to idea solution.

other thought was just to add some logic for cmd_upgrade which will add something to existing env file it will  just append. this is simple but that will work ONLY on upgrade and for development that will not work. because if we will add this to cmd_config it will append env file on each start....

maybe we can do option 2 but in cmd_config with not only append but check if lines which should be appended already in env file. this way we can have like single pathc file in one place which always will examine users env file and will add missing lines to it. @benoitf @skabashnyuk @TylerJewell wdyt?

**Comment by benoitf** [comment]
we still need in che.env (or another file) the version of cli that has created the file or to which version it is now compliant if upgrade is performed

**Comment by TylerJewell** [comment]
In the upgrade() process, we already know the version of the install from the version file. And we know the version you are upgrading to based upon the image tag.  So we know the existing and the end versions, so the loop iteration is easy at that point.
