### ISSUE TITLE
Codenvy in container doesn't check availability of port 8000 in development mode

### ISSUE THREAD

**Issue by garagatyi** [codenvy/codenvy#1282]
Codenvy in container doesn't check availability of port 8000 in development mode. 
So it fails to start instead of checking port and not trying to start.

**Reproduction Steps:**

Start Che in development mode. 
Try to start Codenvy in development mode.

**Expected behavior:**

Codenvy says that port is occupied and start can't be finished.

**Observed behavior:**

Codenvy tries to start and fails with error: 
```
INFO: (codenvy start): Starting containers...
Creating codenvy_nginx_1
Creating codenvy_registry_1
Creating codenvy_rsyslog_1
Creating codenvy_socat_1
Creating codenvy_postgres_1
Creating codenvy_swarm_1
Creating codenvy_haproxy_1
Creating codenvy_codenvy_1

ERROR: for codenvy  Cannot start service codenvy: driver failed programming external connectivity on endpoint codenvy_codenvy_1 (040755d14d7c82d9e527117575c6c717033f1e5bc884491a9dd58cc62ee77416): Error starting u
serland proxy: listen tcp 0.0.0.0:8000: bind: address already in use
Encountered errors while bringing up the project.
```

**Codenvy version:** 5.0.0-M8-Snapshot
**OS and version:** Ubuntu 16.04

**Additional information:**

Problem can be reliably reproduced: [Yes]

**Comment by TylerJewell** [comment]
I'll take this after everything is merged.  Will combine this with improvement checks for -it on the command line.

**Comment by TylerJewell** [comment]
@garagatyi - I have a pull request pending.  You will need to rebuild the /init docker image and the /cli docker image to test it.
