### ISSUE TITLE
How to use Codenvy to Connect to Another Source via SSH

### ISSUE THREAD

**Issue by simonnarang** [codenvy/codenvy#1287]
I am not sure how to do this, does anyone know how?

**Comment by TylerJewell** [comment]
Hi Simon:

I do not think the question is clear. What is "another source"?

**Comment by gc-alexlong** [comment]
I was wondering this as well, or at least a similar situation. I am dabbling in using Codenvy for work. We already have another server that hosts a website, and SSH is available on that hosting solution. I tried using SSH from my Codenvy workspace to connect to the website host. I keep getting "connection has timed out" messages when I try. This scenario could be separate from what OP is asking, but I figured it fit here as a question, not necessarily as an issue.

**Comment by eivantsov** [comment]
@gc-alexlong we limit outgoing traffic from workspaces. We need to whitelist IP of your server.

Once connected to that server what are your expectations? How do you plan using Codenvy?

**Comment by gc-alexlong** [comment]
I was testing SSH to see if I could use rsync to copy some graphics/media assets over to Codenvy. My intention is to use Codenvy as a cloud-based dev environment for a company website. I see there's the ability to upload files and to utilize SSHFS with a local environment, so I can use those tools if that's preferable to whitelisting. It would be more convenient for me to use rsync, but it's not integral. :)

**Comment by eivantsov** [comment]
Closed due to inactivity

**Comment by wired2code** [comment]
Am trying to use Codenvy as a hosted development environment. One of the programs that I'm testing on Codenvy needs to connect to an informix server that resides in an AWS vpn. And the test cases access this informix server by tunnelling through a linux bastion. From the replies above, my understanding is that this linux bastion needs to be whitelisted. Is this possible on a hosted environment ? Or do I need to use an on prem install of codenvy ?

**Comment by eivantsov** [comment]
Yes, all outbound ssh connections from codenvy.io are blocked excepted for whitelisted IPs.

There's no such a restriction if you install On-Prem

**Comment by michacassola** [comment]
Hi,
may I request outbound ssh connections to be allowed?

**Comment by eivantsov** [comment]
@michacassola pease send IP of the server to be whitelisted to support (at) codenvy.com

**Comment by RafaelMiquelino** [comment]
Hi @eivantsov , does Codenvy have developed any simpler solution for this since your last answer or is it still necessary to send my server's ip to the support to be whitelisted? I am starting to work with Codenvy and I run a workflow to deploy to my production server with git (something like this: https://gist.github.com/noelboss/3fe13927025b89757f8fb12e9066f2fa), however I can't use it in Codenvy since I need ssh connection for it to work.
