### ISSUE TITLE
Add ability to configure "Super System privileges"

### ISSUE THREAD

**Issue by sleshchenko** [codenvy/codenvy#1302]
Now user with `manageSystem` permission is able to see workspaces' configuration by user or id, and stop any workspace. It can be problem for some onpremises installations.
It is needed to add ability to configure "Super System privileges" that will extend default opportunities for user who has `manageSystem` permission.

So by default user who has `manageSystem` permission should not be able to do stuffs described in https://github.com/codenvy/codenvy/issues/921. And he will be able to do that only when "Super System privileges" is enabled in configuration.

Also it is needed to remove [`manageOrganizations` on system](https://github.com/codenvy/codenvy/issues/669) domain and allow to users with `manageSystem` to get organizations by user, get organization's resources information, get suborganizations by parent organization id if `Super System privileges` is enabled.

**Comment by bmicklea** [comment]
@sleshchenko are you taking this yourself?  Or is it something for someone else?

**Comment by TylerJewell** [comment]
Is this going to merge before Tuesday night?  If yes, we can keep in the milestone.

**Comment by sleshchenko** [comment]
@TylerJewell Yes. I'm going to merge it tomorrow.

**Comment by riuvshin** [comment]
removed milestone because docs is not ready for this PR.
