### ISSUE TITLE
Remove request for workspace name when adding a new account

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#1303]
With the new Codenvy we no longer need users to create a workspace when they add an account. To simplify account creation we can remove this field from the account creation flow.

**Comment by vkuznyetsov** [comment]
![codenvy login](https://cloud.githubusercontent.com/assets/2101815/24918344/bc354ea2-1ee8-11e7-853f-cf7609ec0653.png)
It's already done.
