### ISSUE TITLE
User friendlier error message when opening factory

### ISSUE THREAD

**Issue by ghost** [codenvy/codenvy#1305]
"INVALID FACTORY URL" while trying to open (for testing) a repo that has .codenvy.json .

**Reproduction Steps:**

Open https://codenvy.io/factory/?url=https://github.com/fleacatcher/fontaine

**Expected behavior:**

A new workspace is created, or I get some error messages if .codenvy.json is not valid.

**Observed behavior:**

"INVALID FACTORY URL" - "Internal Server Error occurred"

**Codenvy version:** 5.0.0-M7 rev b682fff0a1c50f5a
**OS and version:** Online free workspace

**Additional information:**

Problem can be reliably reproduced: Yes

**Comment by skabashnyuk** [comment]
In this particular case repository ```https://github.com/fleacatcher/fontaine``` doesn't exists or we don't have permissions to it(we are not able to distinct this). Error look like this 
<img width="1280" alt="2017-04-24 10 59 07" src="https://cloud.githubusercontent.com/assets/1614429/25327546/2e7f48ac-28dd-11e7-9500-3acfe0dc31ae.png">

**Comment by eivantsov** [comment]
Closing as cannot reproduce. The error pops up exactly as @skabashnyuk demoed.
