### ISSUE TITLE
Update docs with exec-agent .

### ISSUE THREAD

**Issue by JamesDrummond** [codenvy/codenvy#1308]
When the [exec-agent](https://github.com/eclipse/che/issues/1943) is ready to be released we'll need to update the following docs with changes resulting from the new exec-agent. Please update docs content in codenvy `jekyll-docs` branch.

Docs that may need updates:
- [ ] https://github.com/codenvy/codenvy/blob/jekyll-docs/docs/_docs/che/use-che-as-a-workspace-server/server-rest-api.md
- [ ] https://github.com/codenvy/codenvy/blob/jekyll-docs/docs/_docs/che/use-che-as-a-workspace-server/server-events.md
- [ ] https://github.com/codenvy/codenvy/blob/jekyll-docs/docs/_docs/che/use-che-as-a-workspace-server/server-websocket-api.md

You need to leave the jekyll server required information in header between `----` as is. Let me know if you have any questions.

These docs will be merged into master branch or be moved to che repo eventually so the urls above might change.

**Comment by JamesDrummond** [comment]
This issue relates to issue https://github.com/eclipse/che/issues/1943 .

**Comment by TylerJewell** [comment]
@JamesDrummond - update to the latest status please.
