### ISSUE TITLE
CI - create process for pushing static docs version to codenvy.com/docs location

### ISSUE THREAD

**Issue by JamesDrummond** [codenvy/codenvy#1314]
We need to setup a CI task that updates documents are https://github.com/codenvy/codenvy.github.io.  We will take the generated static html/files from jekyll and push them to the codenvy.github.io repo. 
## Following are step I took to update files for a shipped release of docs:

git clone https://github.com/codenvy/codenvy.github.io.git
git clone https://github.com/codenvy/codenvy.git
git clone https://github.com/eclipse/che.git
rm -r codenvy.github.io/assets/
rm codenvy.github.io/index.html
rm -r codenvy.github.io/stable/*
mkdir codenvy.github.io/releases/5_0_0-M8
mkdir -m 777 /tmp/_site
docker run --rm -it --name jekyll -v ${PWD}/codenvy/docs/:/srv/jekyll -v /tmp/_site:/srv/jekyll/_site -v ${PWD}/che/docs/_docs/:/srv/jekyll/_docs/che jekyll/jekyll jekyll build
cp -r /tmp/_site/* codenvy.github.io/stable/
cp -r /tmp/_site/* codenvy.github.io/releases/5_0_0-M8/
cp /tmp/_site/docs/github.io/index.html codenvy.github.io/
cd codenvy.github.io/
git add .
git commit
git push

## For Nightly the following:

git clone https://github.com/codenvy/codenvy.github.io.git
git clone https://github.com/codenvy/codenvy.git
git clone https://github.com/eclipse/che.git
rm -r codenvy.github.io/nightly/*
mkdir -m 777 /tmp/_site
docker run --rm -it --name jekyll -v ${PWD}/codenvy/docs/:/srv/jekyll -v /tmp/_site:/srv/jekyll/_site -v ${PWD}/che/docs/_docs/:/srv/jekyll/_docs/che jekyll/jekyll jekyll build
cp -r /tmp/_site/* codenvy.github.io/nightly/
cd codenvy.github.io/
git add .
git commit
git push

**Comment by JamesDrummond** [comment]
@skabashnyuk @vkuznyetsov Please analyze this issue and update milestone/status labels. This needs to be done for the 5.0.0-M9 release but I will let you change this.

**Comment by skabashnyuk** [comment]
@JamesDrummond  when do you plan to merge jekyll-docs branch to master?

**Comment by evoevodin** [comment]
@JamesDrummond when the job should be triggered?

**Comment by JamesDrummond** [comment]
Please hold. I need to rewrite. There needs to be different versions available.

**Comment by evoevodin** [comment]
nevertheless the script that solves described issue

```bash
#!/bin/bash

# configuration
GH_TOKEN=
DOCS_MIRROR=https://$GH_TOKEN@github.com/codenvy/codenvy
DOCS_SOURCE=https://$GH_TOKEN@github.com/codenvy/codenvy.github.io

set -e

# cleanup
rm -rf docs-mirror
rm -rf docs-source

# sparse checkout, to avoid copying of the whole repo
mkdir docs-source
cd docs-source

git init
git remote add -f origin $DOCS_SOURCE
git config core.sparseCheckout true
echo "docs/" >> .git/info/sparse-checkout
git pull origin master

# get the latest commit hash
DOCS_SOURCE_LATEST_COMMIT_HASH=$(git rev-parse --short HEAD)

# go back
cd ..

# clone the mirror repository
git clone $DOCS_MIRROR docs-mirror

# remove all the files except of .git to make exact copy of
# the sources repo but save the history of mirror repo
rm -rf docs-mirror/*

# copy docs from the source repo
cp -R docs-source/docs/* docs-mirror/

cd docs-mirror

# permalink: docs/ -> permalink: /
cp -R _docs/index.html index.html
sed -i 's/permalink: \/docs\//permalink: \//g' index.html

# commit & push the changes
git add -A
git commit -m 'Synchronize with codenvy/docs commit '$DOCS_SOURCE_LATEST_COMMIT_HASH
git push origin master

# cleanup
cd ..
rm -rf docs-mirror
rm -rf docs-source
```

**Comment by JamesDrummond** [comment]
Please see above for updated process in updating codenvy.github.io repo.

**Comment by JamesDrummond** [comment]
Closing this issue and opening a new one for build.
