### ISSUE TITLE
How do I view this in a browser?

### ISSUE THREAD

**Issue by Gergling** [codenvy/codenvy#1315]
Hi,

I don't know how to view my project application. On my own machine I would go to http://localhost:8080/ (although I realise I would be using a different url). This is either a training issue (I don't know how to do it) or the feature doesn't exist.

**Reproduction Steps:**

1. Download/install project
2. Run server
3. Where do I view my application?

**Expected behavior:**

I expect to be able to see my web application running in a browser window somewhere.

**Observed behavior:**

I don't see what looks like an option to do this. Does the feature exist?

**Codenvy version:** This is the web application.
**OS and version:** I'm using a OSX El Capitan. I imagine it's more interesting to know that I'm using Chrome.

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: [I don't know]
Problem can be reliably reproduced: [Yes]

**Diagnostic bundle**
I don't have this installed on my machine. I'm purely using the web application.

**Comment by TylerJewell** [comment]
Hi @Gergling - welcome to Codenvy.  I think you are talking about how to run your project and then get a preview URL.  Codenvy is based upon Eclipse Che, so you can see how various servers are launchable from within the product with some of the docs here.

https://eclipse-che.readme.io/docs/previews

**Comment by Gergling** [comment]
Ok thanks. That does sound right, but looking at the rest of it I clearly need to read up on some codenvy or dev-ops related stuff.
