### ISSUE TITLE
Custom http/https ports

### ISSUE THREAD

**Issue by ghacproductions** [codenvy/codenvy#1317]
When starting codeenvy, it always uses ports 80 and 443. Is there a way to change these ports to some custom ones?

**Comment by TylerJewell** [comment]
We currently do not allow that.  We are thinking about it for the future, but it is tricky as there are numerous internal services mapped to these ports.

**Comment by TylerJewell** [comment]
@ghacproductions - Simon, just to confirm this, I did a quick test where I took the generated docker-compose.yml file that we created, and mapped the external HAProxy port from '80' to '9000'. While I could get the initial login screen to appear, it would not successfully log me in. We have browser rewriting rules inside of the product that we would have to modify as well for this.

**Comment by TylerJewell** [comment]
@ghacproductions - we will think about this for the 5.1 release. In doing some further investigations, we'd need to set up multiple configuration properties, modify how our haproxyis forwarding requests, and then also have the redirect URLs inherit this port for redirection.

**Comment by TylerJewell** [comment]
We do not plan to implement this support in codenvy.  We are porting to run on k8s and it may offer new capabilities.
