### ISSUE TITLE
Restart workspace from IDE ends up with an error (regression)

### ISSUE THREAD

**Issue by garagatyi** [codenvy/codenvy#1335]
When I restart WS from the IDE I get an ugly error hovering IDE. But workspace state is ok and refresh of page fixes IDE.

**Reproduction Steps:**

1. Start existing WS from UD.
2. Stop ws from IDE.
3. Press start in IDE after workspace stop is finished.
4. Wait until WS start ends.

**Expected behavior:**

WS starts and no error appears.

**Observed behavior:**

Error message hovering IDE appears.
![image](https://cloud.githubusercontent.com/assets/1851863/21143985/8e7daf3a-c151-11e6-865a-6f75c06601b9.png)

**Codenvy version:** M9-Snapshot Codenvy in container
**OS and version:** ubuntu 16.04

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: [Yes]
Problem can be reliably reproduced: [Yes]

**Comment by vitaliy-guliy** [comment]
Can not reproduce with the latest IDE and Codenvy in container.

eclipse/che version :5.0.0-M9-SNAPSHOT
eclipse/che revision :237e1edbce4e35f8
