### ISSUE TITLE
Logs of workspace containers and agents are not shown when WS starts in IDE (regression)

### ISSUE THREAD

**Issue by garagatyi** [codenvy/codenvy#1337]
When I start WS by clicking on its name in WSs list in UD logs panels takes whole screen but no logs is shown while WS is starting. 

**Reproduction Steps:**

1. Create WS in UD.
2. Click on WS name in WSs list in UD. UD opens IDE.
3. Logs panel is opened and takes almost whole screen.

**Expected behavior:**

Containers logs appear in this panel along with agents logs.

**Observed behavior:**

No logs appear at all. Panel is just empty until WS is started.

**Codenvy version:** M9 snapshot
**OS and version:** Ubuntu 16.04

**Additional information:**

Problem can be reliably reproduced: [Yes]
Also reproduced on @sleshchenko's PC with Ubuntu 16.04.
Codenvy CLI provides IP of Codenvy 172.17.0.1 and @riuvshin says that it should show another one - 172.17.20.12 for me. It is my public IP.
When I do the same from 172.19.20.12 IP behavior is the same. The same for Sergii's IP on his PC.

Screenshot of my screen with errors in chrome dev console:
![selection_012](https://cloud.githubusercontent.com/assets/1851863/21146138/52d64674-c159-11e6-98cd-a0b099ec1f43.png)

**Comment by vitaliy-guliy** [comment]
Spent 1.5 days
