### ISSUE TITLE
Port Che CLI for Codenvy SaaS

### ISSUE THREAD

**Issue by TylerJewell** [codenvy/codenvy#1340]
We need to have a process for how to run the Codenvy CLI with a SaaS packaging.

We use puppet today with Vagrant to create SaaS test environments. Can we use Vagrant with Dockerized version. We will need a different codenvy/init image with proper configuration and a custom binary assembly. Would we name the SAAS CLI then `codenvy/saas-cli:<version>`.  We would then package up these differences in the SaaS repository. We will also need Jenkins jobs for SaaS images to be built.

**Comment by benoitf** [comment]
https://github.com/codenvy/customer-saas/pull/91

**Comment by benoitf** [comment]
merged
