### ISSUE TITLE
Run Dockerized Codenvy in a Vagrant VM

### ISSUE THREAD

**Issue by TylerJewell** [codenvy/codenvy#1342]
Currently, when trying to run Codenvy in a Vagrant VM that has Docker 1.11 in it, it is able to start, but workspaces cannot start. Starting a workspace fails immediately with error "Start of environment default failed. Error: The system is out of resources."

Here is the Vagrantfile used:
```
Vagrant.configure(2) do |config|
  config.vm.box = "williamyeh/ubuntu-trusty64-docker"
  config.vm.network "forwarded_port", guest: 80, host: 80
end
```

**Comment by riuvshin** [comment]
docker version inside is `1.12.1`
I'm not able even login with to codenvy with that vagrant file.
but here is possible issues:
1) in that VM 23750 port already occupied by something so socat not able to start.
2) by default that VM will be started with `384MB`  of RAM :) which is actually should be a reason why you've got "The system is out of resources." because that VM is really don't have resources to run your WS with even 1GB.
here is how I modified vagrantfile to add more RAM and CPUS

```
Vagrant.configure(2) do |config|
  config.vm.box = "williamyeh/ubuntu-trusty64-docker"
  config.vm.network "forwarded_port", guest: 80, host: 80
    config.vm.provider :virtualbox do |vbox|
        vbox.customize [
            'modifyvm', :id,
            '--memory', 4096,
            '--cpus', 2
        ]
    end
end
```
also port forwarding does not for for me at all.
I'm not able access codenvy in VM. Can you please explain how you accessed that?

**Comment by riuvshin** [comment]
Finally it is working for me with following Vagrantfile
it is centos 7.2 with latest docker installed (1.12.4)
there is `8GB RAM` and `4CPUs`

```
box      = 'centos7.2'
url      = 'https://install.codenvycorp.com/centos7.2.box'
ram      = '8096'
cpus     = '4'
bridge   = 'eth0'

Vagrant.configure("2") do |config|
  config.vm.box = box
  config.vm.box_url = url
  config.ssh.insert_key = false
  config.vm.network :private_network, ip: "192.168.56.77"

config.vm.provider :virtualbox do |vbox|
    vbox.customize [
        'modifyvm', :id,
        '--memory', ram,
        '--cpus', cpus
    ]
 end
    config.vm.provision "shell", inline: "echo -e \"nameserver 8.8.8.8\n\" >> /etc/resolv.conf"
    config.vm.provision "shell", inline: "echo -e \"[dockerrepo]\nname=Docker Repository\nbaseurl=https://yum.dockerproject.org/repo/main/centos/7\nenabled=1\ngpgcheck=1\ngpgkey=https://yum.dockerproject.org/gpg\" > /etc/yum.repos.d/docker.repo"
    config.vm.provision "shell", inline: "yum install docker-engine -y"
    config.vm.provision "shell", inline: "iptables -I INPUT 1 -p tcp -m tcp --dport 80 -j ACCEPT"
    config.vm.provision "shell", inline: "iptables -I INPUT 1 -p tcp -m tcp --dport 23750 -j ACCEPT"
    config.vm.provision "shell", inline: "iptables -I INPUT 1 -p tcp -m tcp --dport 32768:65535 -j ACCEPT"
    config.vm.provision "shell", inline: "service docker start"
    config.vm.provision "shell", inline: "docker run -i --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/roman/development/codenvy_projects/.codenvy:/data -v /home/roman/development/denvy_projects/.codenvy/backup:/backup codenvy/cli:nightly start"
end

```

So I believe your issue was with RAM allocated to VM

**Comment by riuvshin** [comment]
in that VM docker version is 
```1.12.1```

**Comment by TylerJewell** [comment]
Thank you - I need to get on my alternative Windows box to test this.  I have to swithc between boxes since my primary machine that runs Docker for Windows is unable to run Vagrant, and vice versa.

Question - should we update this Vagrantfile in our root repository with this new Vagrantfile instead?
https://github.com/codenvy/codenvy/blob/master/Vagrantfile

**Comment by riuvshin** [comment]
@TylerJewell this https://github.com/codenvy/codenvy/blob/master/Vagrantfile is much smarter than mine, it able to handle proxy and other stuff maybe we just need to combine them.

**Comment by TylerJewell** [comment]
Yes, i agree that we could combine them. The proxy management means that we have to update systemd for Docker and then restart it.  Much simpler overall.

Question - do we want to update our root repo Vagrantfile, or just remove Vagrant all together?  I think this is a good exercise, but we should only do it if we see value in it.

**Comment by riuvshin** [comment]
I don't know why we still need that vagrant file. I think we should remove it.

**Comment by TylerJewell** [comment]
Ok - I agree.  Let's just remove it.  I will let you do the PR for this because I don't want to remove the Vagrantfile if our engineers are still using it for testing at all.  But if they are, then we need to get more people on the Dockerized version.

**Comment by riuvshin** [comment]
our devs are using completely different vagrant file from deployment project. I don;t know who is using that Vagrantfile in that project. So my proposal I will remove Vagrant file from that project once we move all devs to use only docker. and for now I close this issue, OK?

**Comment by TylerJewell** [comment]
I would go ahead and just remove the root repo Vagrantfile as part of this, then.  Let's do that and close them together.

**Comment by riuvshin** [comment]
Done.
