### ISSUE TITLE
Improve How CLI Gets List of Stack Images

### ISSUE THREAD

**Issue by TylerJewell** [codenvy/codenvy#1343]
Currently, the CLI has [hard-coded the list of stack images](https://github.com/eclipse/che/blob/master/dockerfiles/base/scripts/base/commands/cmd_offline.sh#L50) that can be downloaded for offline mode.  

We should:
1) Have our CI systems during the release process determine what this list of stack images are, and:

2) Place that list in the dockerfiles/cli/version/<version>/stack-images file.  We already have the core system images in that folder in a different file name. For example, we currently place the core system [images list here](https://github.com/eclipse/che/tree/master/dockerfiles/cli/version/5.0.0-M8).

3) Update the cmd_offline() method in the CLI to load the stack images from this location instead of the hard-coded array.

**Comment by skabashnyuk** [comment]
On yesterday's meeting we decided to postpone this issue to 5.1

**Comment by bmicklea** [comment]
@TylerJewell can you confirm that this should be in 5.1 - if so we'll remove the M9 milestone

**Comment by TylerJewell** [comment]
We said that we would postpone the issue around rewriting the internals of add-node but we did not say that about this particular issue.  The perception was that we would need something simple to start, I think.

**Comment by skabashnyuk** [comment]
Simple to start way is to keep existed list up to date manually

**Comment by TylerJewell** [comment]
Pull request: #3394

**Comment by TylerJewell** [comment]
PR was merged this morning.
