### ISSUE TITLE
Internal server error during sign up by email

### ISSUE THREAD

**Issue by sleshchenko** [codenvy/codenvy#1345]
When I try to sign up by email I can't do it because I get 500 Internal Server Error.
Log file contains error about mail sender.

**Reproduction Steps:**

1. Open Сodenvy
2. Click on `Create a New Account` link
3. Try to sign up with email

**Expected behavior:**

It is able to sign up by email, or there is reasonable error message why I am not able to do it.

**Observed behavior:**

There is only error message: Something went wrong. Please try again or contact support.

![errorpage](https://cloud.githubusercontent.com/assets/5887312/21174710/6afbd3ca-c1e7-11e6-902f-c9bbea8f399a.png)
![logs](https://cloud.githubusercontent.com/assets/5887312/21174713/7182add6-c1e7-11e6-99ab-11666b081bb2.png)

**Codenvy version:** 5.0.0-M9-SNAPSHOT, Build Time :2016-12-12 20:10:34
**OS and version:** Ubuntu 16.04

**Additional information:**

Problem can be reliably reproduced: [Yes]

**Comment by skabashnyuk** [comment]
This kind of expected because smtp is not configured. I think scope of this task should be focused on UX
1. Disallow email registration of smtp is not configured.
2. In HTTP responses we should add information about the fact that smtp is not configured.

**Comment by eivantsov** [comment]
Currently, a clear error message is displayed saying that example.smtp.com is a wrong smpt server.

**Comment by mmorhun** [comment]
Cannot reproduce.
Looks like already fixed.
