### ISSUE TITLE
Dockerized Install Behind Proxy - Workspaces Do Not Start

### ISSUE THREAD

**Issue by TylerJewell** [codenvy/codenvy#1351]
Could not get the workspace agent to complete the bootstrap sequence.

Performed an installation of nightly Codenvy at a financial services firm behind a firewall and a proxy.

1. Docker 1.11 installed

2. Updated the Docker daemon to use a proxy.  Set the NO_PROXY=<short-dns>

3. Ran the installer.

4. System started ok - no issues, also found the proper IP address and CODENVY_HOST automatically set to IP address of the machine.

5. Could not start a workspace. The workspace agent Tomcat output indicated that the agent had fully booted, but the system never proceeded to confirm that the agent was booted - could not start terminal, could not clone git, etc.

a) The end user was accessing Codenvy using DNS entry, but CODENVY_HOST=<ip>.  Is this an issue?
b) Adding both the short and long-form DNS entry to the workspace NO_PROXY did not change anything.

From the customer, here is the step by step configuration that we did.

```
Install docker-engine-1.12.4-1.el7
vi /lib/systemd/system/docker.service   # Add this Environment variable
Environment="HTTP_PROXY=http://proxy.ops.tiaa-cref.org:8080" "HTTPS_PROXY=http://proxy.ops.tiaa-cref.org:8080" "NO_PROXY=aweata3utcod03.cloud.tiaa-cref.org"
x systemctl start docker
x mkdir -p /root/codenvy
x docker run -it --rm  -v /var/run/docker.sock:/var/run/docker.sock -v /root/codenvy/:/data codenvy/cli:nightly start    
```
App started, but workspace creation hung
```
update /root/codenvy/codenvy.env:
replace
CODENVY_NO_PROXY_FOR_CODENVY_WORKSPACES=127.0.0.1,localhost,aweata3utcod03.cloud.tiaa-cref.org,10.22.10.72
with
CODENVY_NO_PROXY_FOR_CODENVY_WORKSPACES=127.0.0.1,localhost,aweata3utcod03.cloud.tiaa-cref.org,10.22.10.72,aweata3utcod03"
docker run -it --rm  -v /var/run/docker.sock:/var/run/docker.sock -v /root/codenvy/:/data codenvy/cli:nightly restart
```

This is a TAR file with the configuration they used.  https://dl.dropboxusercontent.com/u/9657839/tiaa-codenvy-2016-12-14.tar

**Comment by mshaposhnik** [comment]
Is that AIO type, with WS running on the same machine? And aweata3utcod03.cloud.tiaa-cref.org domain same for 10.22.10.72 IP?

**Comment by mshaposhnik** [comment]
Everything in conf-s looks very correct. The only point i can notice, is that in the logs there is lot of requests from IP 172.18.0.1 - it is also local address but from another subnetwork. We may try to add it into NO_PROXY sections for admin & agent.

**Comment by TylerJewell** [comment]
Well, with dockerized codenvy, we only have the AIO architecture. But yes it was just a single node and the DNS name of aweata3utcod03.cloud.tiaa-cref.org with IP 10.22.10.72.  Interestingly, TIAA had another completely different system installed using the puppet system and it has the same error at the same time yesterday.  So this could be a weird networking issue.

**Comment by mshaposhnik** [comment]
I propose to resolve issue for now, because the problem seems in the network issue of the customer. 
If problem persists after fixing networking, we can create new with specific problem or reopen again.
