### ISSUE TITLE
Terminal will not load

### ISSUE THREAD

**Issue by davidtaylorjr** [codenvy/codenvy#1363]
When loading a workspace the terminal will not load to to a websocket error

Exact error given:

>  2016-12-16 04:16:24,916[nio-4401-exec-8]  [INFO ] [a.c.w.i.BasicWebSocketEndpoint 49]   - Web socket session opened
> 2016-12-16 04:16:24,917[nio-4401-exec-8]  [INFO ] [a.c.w.i.BasicWebSocketEndpoint 50]   - Endpoint: 2080490865
> [STDERR] 2016/12/16 04:16:26 Websocket upgrade failed: websocket: version != 13

**Comment by TylerJewell** [comment]
We will need more details to reproduce.  Browser, version, dev console output, any firewall settings or proxy config that you may have.  Thanks.

**Comment by davidtaylorjr** [comment]
Browser is latest Google Chrome on Windows 10.

Not sure what you are looking for with the dev console output, I pasted that in.

Firewall just regular windows firewall.  Use Covenant Eyes filter and Circle by Disney.
On 12/15/2016 11:45:43 PM, Tyler Jewell <notifications@github.com> wrote:
We will need more details to reproduce. Browser, version, dev console output, any firewall settings or proxy config that you may have. Thanks.

**Comment by TylerJewell** [comment]
The terminal operates over port in the 4000 range and we also require ports in the ephemeral range. Can you check if those services are blocked?

**Comment by eivantsov** [comment]
@TylerJewell terminal port 4411 is exposed and the browser accesses it via one from the ephemeral port range.

@davidtaylorjr does a workspace start OK? Can you create a project? Open files in the editor etc?

Can you send a screenshot please?

**Comment by davidtaylorjr** [comment]
Workspace starts ok, everything appers to work except terminal:

On 12/16/2016 8:28:58 AM, Eugene Ivantsov <notifications@github.com> wrote:
@TylerJewell [https://github.com/TylerJewell] terminal port 4411 is exposed and the browser accesses it via one from the ephemeral port range.
@davidtaylorjr [https://github.com/davidtaylorjr] does a workspace start OK? Can you create a project? Open files in the editor etc?
Can you send a screenshot please?

**Comment by davidtaylorjr** [comment]
Any word on this?

**Comment by garagatyi** [comment]
Can you provide output of Chrome dev console? It can contain browser or application logs on why some requests were blocked or some component of app failed.

**Comment by davidtaylorjr** [comment]
VM645:35 WebSocket connection to 'wss://codenvy.io/37304_node7.codenvy.io/pty?token=machinegui9l4fi1ace9c2hbs…o62xdf3oq1yq0py2ii8dw8ayx9x024s194qzanns9l9g8fp32xxffg6kfe1b05o3gkbf0p5k8h' failed: Error during WebSocket handshake: Unexpected response code: 502
WrappedWebSocket @ VM645:35
_.Bl @ _app-0.js:4533
(anonymous) @ _app-0.js:1613
On 12/21/2016 2:59:29 AM, Alexander Garagatyi <notifications@github.com> wrote:
Can you provide output of Chrome dev console? It can contain browser or application logs on why some requests were blocked or some component of app failed.

**Comment by garagatyi** [comment]
Probably terminal agent didn't start.
Can you provide your machine id. Then I'll be able to grab logs of start of your machine. Maybe something useful is there.
![selection_013](https://cloud.githubusercontent.com/assets/1851863/21395815/a46bae18-c7a6-11e6-9394-db1b6d234afd.png)
![selection_014](https://cloud.githubusercontent.com/assets/1851863/21395837/a983032e-c7a6-11e6-9374-1d0532f4bc8a.png)

**Comment by davidtaylorjr** [comment]
machine1z8cifqbooh8o86r
On 12/21/2016 10:55:37 AM, Alexander Garagatyi <notifications@github.com> wrote:
Probably terminal agent didn't start.
Can you provide your machine id. Then I'll be able to grab logs of start of your machine. Maybe something useful is there.
[selection_013] [https://cloud.githubusercontent.com/assets/1851863/21395815/a46bae18-c7a6-11e6-9394-db1b6d234afd.png]
[selection_014] [https://cloud.githubusercontent.com/assets/1851863/21395837/a983032e-c7a6-11e6-9374-1d0532f4bc8a.png]

**Comment by garagatyi** [comment]
Can you take next screenshot 
![selection_015](https://cloud.githubusercontent.com/assets/1851863/21397171/6e1f6b1a-c7ab-11e6-8783-a23c102672a9.png)

**Comment by davidtaylorjr** [comment]
*
Accept-Encoding:
gzip, deflate, sdch, br
*
Accept-Language:
en-US,en;q=0.8
*
Cache-Control:
no-cache
*
Connection:
Upgrade
*
Cookie:
_mkto_trk=id:519-AYY-549&token:_mch-codenvy.io-1480474017753-60927; __utma=236179731.933372002.1480474019.1481861500.1482333936.5; __utmc=236179731; __utmz=236179731.1481595565.2.2.utmcsr=codenvy.com|utmccn=(referral)|utmcmd=referral|utmcct=/login/; session-access-key=jj9K80iXKerzXPP5LiKr09OGDu5rfn4KuuPS1ii9Di444jCXWWCqbjqn5jajuX1X4GKOCPe4eqL49rCq0Gfj9LPaKin0iCKz8vKXiD8j8C4XyWfzDDOXDXTW98HzP409zjbmSHKy5nHSjSi40yS0bXvHuLjmj1jWG5rjjHjbqn1enCn5Pb4O4PyqXKvy8Obj8bfy4qqOb8jOffiSq08G9Oe1WyyK9GXSerT5qDSGPeK8DinbLm1rTeaqCSrK1Kv; logged_in=true; _ga=GA1.2.933372002.1480474019; JSESSIONID=2CC32B59C08AB361502D9A4C8F70AC6D
*
Host:
codenvy.io
*
Origin:
https://codenvy.io
*
Pragma:
no-cache
*
Sec-WebSocket-Extensions:
permessage-deflate; client_max_window_bits
*
Sec-WebSocket-Key:
hCIfMfRqliI2nwHGmsseWg==
*
Sec-WebSocket-Version:
13
*
Upgrade:
websocket
*
User-Agent:
Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Mobile Safari/537.36
On 12/21/2016 11:29:42 AM, Alexander Garagatyi <notifications@github.com> wrote:
Can you take next screenshot
[selection_015] [https://cloud.githubusercontent.com/assets/1851863/21397171/6e1f6b1a-c7ab-11e6-8783-a23c102672a9.png]

**Comment by eivantsov** [comment]
@davidtaylorjr Do you have an opportunity to try it using a different internet connection?

**Comment by davidtaylorjr** [comment]
No I don't actually.

**Comment by TylerJewell** [comment]
@davidtaylorjr - should we keep this issue open for a longer period or time, or close it upon waiting for another issue to appear?

**Comment by davidtaylorjr** [comment]
@TylerJewell It has not yet been resolved so I'm not sure what you want to do.

**Comment by eivantsov** [comment]
We were unable to reproduce both with codenvy.io or On Prem installations.

**Comment by davidtaylorjr** [comment]
This is now working after creating a fresh workspace.
