### ISSUE TITLE
Clarify Codenvy configuration for using private docker registries

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#1378]
This is the same issue as for Che, but specific to Codenvy config.
https://github.com/eclipse/che/issues/3442

**Comment by riuvshin** [comment]
sorry but I have no Idea how it works in CHE I know only about codenvy. AFAIK for che we don't have ability to configure registries

**Comment by bmicklea** [comment]
@skabashnyuk - we need the following information:

1) Where are snapshots saved by default?
2) How can snapshots be configured to use a private registry I define?
3) Where is snapshot data stored?

**Comment by TylerJewell** [comment]
https://github.com/codenvy/codenvy/pull/1400
