### ISSUE TITLE
add docs for new LIMIT props

### ISSUE THREAD

**Issue by riuvshin** [codenvy/codenvy#1385]
today we've added few new props related to limits https://github.com/codenvy/codenvy/commit/8f06f6791c026cb88863237c74fc0c5278320395

so we've added 2 new props:

```
 #     The maximum number of workspaces that a organization is allowed to own. The organization will
 #     be presented with an error message if they try to create additional workspaces.
 #     This applies to the total number of both running and stopped workspaces. Since
 #     each workspace is saved as a snapshot, placing a cap on this number is a way
 #     to limit the disk consumption for workspace storage.
 #CODENVY_LIMITS_ORGANIZATION_WORKSPACES_COUNT=30
 
 #     The maximum number of running workspaces that a single organization is allowed to have.
 #     If the organization has reached this threshold and they try to start an additional workspace,
 #     they will be prompted with an error message. The organization will need to stop a running
 #     workspace to activate another.
 #CODENVY_LIMITS_ORGANIZATION_WORKSPACES_RUN_COUNT=10
```

we have to add this to docs because if users who running codenvy M8 will want to configure those props they will need manually add this to their codenvy.env files

**Comment by bmicklea** [comment]
Actually we don't document the specific limits in the docs, only in the .env file which I think makes sense (prevents the two locations from getting out-of-sync.  So since these are sufficiently documented in the env file they're good-to-go.
