### ISSUE TITLE
Improve Codenvy Scaling Logic

### ISSUE THREAD

**Issue by TylerJewell** [codenvy/codenvy#1386]
We have run into limitations with the current mode of scaling Codenvy. The current installation assumes a Dockerized bridge network, but any reasonable enterprise customer is always going to require an overlay network. Overlay networks require the configuration of a key-value storage AND a Docker daemon with settings for that key value storage.

We are going to require Codenvy systems that want to scale to do the following:
1. The master node does not need its Daemon reconfigured, and it can run in bridge mode initially so that we can preserve simplicity during trials.
2. We will add a ZooKeeper Docker container as part of our standard deployment of containers.
3. We will then have admins configure the Docker daemon on each additional node to connect to the Codenvy key-value storage.
4. We will then provide a utility to verify that a node is able to be added.
5. We will then modify our add-node and remove-node scripts to be run on the master node to add the IP address.

We will only (initially) support allowing additional ws nodes to be added on Linux as we can test the configuration more easily.

The inputs that we will ask an admin to do are:
1. On your node, install Docker
2. On your node, get the IP address of the master node
3. On your node, identify the network interface for where Docker is advertising itself on the ws node.

As a first step, I have documented what I believe the current manual process is for adding nodes in the `simulated-scaling` branch. We can at least publish this to customers as a first process for them to use.  This may not be entirely accurate, but we can update this as we learn more about scaling.  https://github.com/codenvy/codenvy/blob/simulated-scaling/docs/_docs/admin-guide/admin-managing.md#scaling

Tasks:
- [x] Add ZooKeeper key-value container to the Dockerized Codenvy start().
- [x] Add documentation on how to configure Linux Docker daemon to connect to already running ZooKeeper installation. Provide a "docker run" command that an admin can run on the node to verify that the Daemon is properly configured.
- [ ] Add a `codenvy check-node <master-ip>` CLI command. This command is to be run on the node-to-be-added. This command will verify that a) the Docker daemon is active and can be connected, b) that the ZooKeeper configuration is done properly on the local Daemon by inspecting its values, c) verify that we can connect to the Codenvy master node (error if it is not running), d) verify that Codenvy ZooKeeper is running (maybe this is not needed if the docker daemon is valid), e) if there are any additional port / networking checks, we can do this.  If the `add-node <master-ip>` command is run on the master node, then we should detect this situation and inform the admin that a master node cannot be added to the cluster AND we can print out nice info on what they can do to add a node by running the CLI on the node to be added.
- [ ] Rewrite the 'add-node <ws-node>' to run on the master() only and to update `codenvy.env` with the IP address and then to trigger a HUP signal to the swarm container.  Should we have any logic on what to do if this fails?
- [ ] Update the 'list-nodes' command to query the Codenvy server to get information about all of the nodes that are in the codenvy cluster and maybe their node state?  running / stopped / ?
- [x] Work to update the Managing.md docs to provide clear instructions to admins on adding, removing, listing, and working with nodes in a scaling situation.

FYI, some notes from Roman on checking node to master connectivity. He says we should use nmap to verify that ports are open with `nmap <MASTER-IP> -Pn -p 80,443,<KV-PORT>`.

**Comment by benoitf** [comment]
is that container will always start or it's based on a 'scale' property ( so container is not part of docker-compose file in all-in-one mode)

**Comment by TylerJewell** [comment]
For simplicity, I think it's better that we always start it for now.

**Comment by TylerJewell** [comment]
@skabashnyuk - because @benoitf is having his first child, we cannot expect him to be around for the next couple weeks.  Pushing this out to 5.1 because we now have very good documentation on how to manually set this up.  But the automation parts we will need to add into a sprint in the near future (perhaps next.next sprint) so that we can get it into 5.1.0

**Comment by TylerJewell** [comment]
No longer valid in the move to k8s.
