### ISSUE TITLE
Add ZooKeeper key-value container to the Dockerized Codenvy start().

### ISSUE THREAD

**Issue by riuvshin** [codenvy/codenvy#1388]
needed for  https://github.com/codenvy/codenvy/issues/1386

**Comment by TylerJewell** [comment]
Pushing this into 5.1.0.  This is REALLY important for 5.0, but if it slips out, we have manual process on what to do interim.

**Comment by riuvshin** [comment]
PR proposed https://github.com/codenvy/codenvy/pull/1421

I've tested this with following steps:

1) launched locally codenvy in docker (with my changes)
2) launched docker-machine with docker opts to use zookeeper from my host
```create -d virtualbox --engine-env DOCKER_TLS=no --virtualbox-memory "3000" --engine-opt="cluster-store=zk://<MY_HOST_IP>:2181" --engine-opt="cluster-advertise=eth1:2376" --engine-insecure-registry="<MY_HOST_IP>:5000" node1```
3)  in `codenvy.env`:
- enable overlay `CODENVY_MACHINE_DOCKER_NETWORK_DRIVER=overlay`
- replace default local swarm node with docker-machine node `CODENVY_SWARM_NODES=<DOCKER_MACHINE_NODE_IP>:2376`
4) codenvy/cli restart to apply changes
5) test and ensure workspace is able to start on that docker-machine node with overlay and docker connected to zookeeper kv which we provided.

**Comment by TylerJewell** [comment]
We need to also add some docs so will keep open until we close that loop.

1. Can we have overlay on by default in codenvy.env?
2. I noticed that Alex docker machine example did not activate overlay variable but it worked.  Any idea why?
3. What are the ports that must be open for zookeeper?

**Comment by riuvshin** [comment]
1) no because standart AIO will not work without docker demon modification which is not possible on windows and mac. by default we must be  in bridge mode and use same docker daemon which we used to run codenvy. 

2) I think he forgot about this he used bridge mode which actuall not always works if you have more than 1 node. 
(because with if you have 2 nodes and network driver "bridge" you won;t be able to start ws in 50% cases because 1) we create net work 2) we start container with that network and if you have more than one node and driver bridge you will run in to issue where network is created on node1 but container scheduled to start on node2 and it will fail because it will not be able to find network. So it means bridge driver IS ONLY for AIO, in any case with multi node we must use overlay with kv) 

3) zookeeper port is 2181, btw I;ve aready added check in CLI for that port

**Comment by riuvshin** [comment]
can we close this now?

**Comment by TylerJewell** [comment]
Documentation added.
