### ISSUE TITLE
On a fresh Android project - two Cannot find symbol errors

### ISSUE THREAD

**Issue by developer10** [codenvy/codenvy#1397]
I just used both example projects, and tried to build them. On both, the same 2 error appear:

`/projects/mobile-android-simple/src/main/java/org/hello/HelloActivity.java:[15,32] cannot find symbol
[ERROR] symbol:   variable hello_layout
[ERROR] location: class android.R.layout
[ERROR] /projects/mobile-android-simple/src/main/java/org/hello/HelloActivity.java:[22,57] cannot find symbol
[ERROR] symbol:   variable text_view
[ERROR] location: class android.R.id`

**Reproduction Steps:**

Create a project based on an Android sample project
Try to build
If the build fails, look for those errors

**Expected behavior:**

To build successfully and to have the emulator launch the app

**Observed behavior:**

As the build fails, I cannot launch the app

**Codenvy version:** [Enter Codenvy version here]
**OS and version:** [Enter OS name and version here]

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: [Yes / No]
Problem can be reliably reproduced: [Yes / No - it's random]

**Diagnostic bundle**
Execute the script on [this page](https://github.com/codenvy/codenvy/wiki/Support-Diagnostics) and post public link to the bundle here.

**Comment by eivantsov** [comment]
@developer10 there are auto generated classes that are not added to Java classpath. I will mark this as bug and have an engineer investigate.

**Comment by developer10** [comment]
Still no progress on this one?

**Comment by TylerJewell** [comment]
It probably fell out of visibility.  Setting P1, and we should invite support engineers and / or team/ide to look into it.

**Comment by eivantsov** [comment]
I tried converting this project into a plain Java project type and manually adding target/generated-sources/r to project sources, and it worked for me - the error's gone.

So, the problem is that with Maven project type, we cannot add source directories to classpath dynamically.  And it is an Android specific class  which is automatically generated during build.

**Comment by developer10** [comment]
@eivantsov Does that mean there's nothing you can do about it?

**Comment by eivantsov** [comment]
There's no immediate solution for this one. As a workaround, you may change priject type to Java at Project > Update Project Configuration and then manually add `target/generated-sources/r ` to classpath.
