### ISSUE TITLE
I cannot close curly braces on my non-EN keyboard layout

### ISSUE THREAD

**Issue by developer10** [codenvy/codenvy#1399]
My keyboard layout allows me to type the opening curly brace `{`, but not closing. Instead, the `Navigate to file` dialog launches. I was hoping to be able to unbind this combination `Ctrl+Alt+N` or `AltGr+N` but without success.

**Reproduction Steps:**

[First Step]
[Second Step]
[Other Steps...]

**Comment by TylerJewell** [comment]
This is an issue for eclipse che, for which we inherit from.  When Eclipse Che adds in key binding customization (2017) it will appear in Codenvy.
https://github.com/eclipse/che/issues/2748
