### ISSUE TITLE
Error: Fail launching agent org.eclipse.che.ssh. Workspace ID:workspace************

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#1407]
Got some errors like:

```
2016-10-27 12:26:31,024[aceManager-2316]  [ERROR] [.a.a.s.l.AbstractAgentLauncher 88]   - Fail launching agent org.eclipse.che.ssh. Workspace ID:workspace*******
```

**Reproduction Steps:**

Don't know

**Expected behavior:**

Error message contains more information, that may help to diagnose cause of failure.

**Observed behavior:**

No information except workspace ID.

**Codenvy version:** 5.0.0-M8
**OS and version:** Centos 7.2

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: Yes
Problem can be reliably reproduced: No - it's random

**Comment by mmorhun** [comment]
done
