### ISSUE TITLE
Allow fine-grained selection of JDK release

### ISSUE THREAD

**Issue by achristianson** [codenvy/codenvy#1409]
Some projects will fail to compile based on the JDK minor release/build. It would therefore be helpful to be able to pick a specific JDK release to run a workspace on, or otherwise provide instructions on how to properly swap the JDK for a specific release/build once it is created.

For example, see this Apache NiFi dev thread showing that the project fails to compile on versions of the JDK which come packaged with codenvy: https://lists.apache.org/thread.html/b2a1946a39f9f8b4c7af9ab45b6d05eb39d0f43778dc9bb1278e2602@%3Cdev.nifi.apache.org%3E

**Comment by TylerJewell** [comment]
@achristianson - codenvy is based upon Eclipse Che. You can create custom stacks, which have dockerfile recipes that install exactly the software that you need, overriding the software that Codenvy installs in the default stacks. This would allow you to install exactly the version of the JDK that you need for your workspace.

If you'd like some more information on how to do this, we can give you links in the Che docs and also you can start with reusing the Dockerfiles that we provide for Che as well.

**Comment by achristianson** [comment]
Would definitely be interested in a link to the docs for creating a custom stack as it pertains to codenvy.

**Comment by eivantsov** [comment]
@achristianson Here you go - https://eclipse-che.readme.io/docs/stacks

Basically, you may take the below Dockerfile and install any Java version there:

https://github.com/eclipse/che-dockerfiles/blob/master/recipes/ubuntu_jdk8/Dockerfile

You may also NOT install tools that you think you'll never need in your workspace.

**Comment by eivantsov** [comment]
@achristianson did you manage to create a custom stack that fits your needs?

**Comment by achristianson** [comment]
So I'm trying to start from the Java CentOS stack as that would be an appropriate starting point for this. I got to the stacks screen, then hit the "duplicate" button next to that stack (or any stack, really), and when I hit duplicate I get an error message in the top-right of the screen that just says "Failed." I'm assuming this is some kind of bug or internal error?

**Comment by achristianson** [comment]
@eivantsov Was able to solve my build issue by just hot-patching the latest JDK into /opt using the java centos task. Wondering if we could just update the java version in https://github.com/codenvy/dockerfiles/blob/master/centos_jdk8/Dockerfile to the latest release? 45 is a fairly outdated release at this point. I would submit a pull request but am currently only contractually able to contribute to certain FOSS projects. The change should be trivial (just a number change).

**Comment by TylerJewell** [comment]
@achristianson - we appreciate your help here.  The /codenvy/dockerfiles repository should be closed. We have moved all of these definitions into the open source realm and they are now hosted here: 
https://github.com/eclipse/che-dockerfiles/tree/master/recipes.  And then these images are pushed into DockerHub under the eclipse/* image names as well.

Would you still want us to make a change - or since this is open source would you like to have the PR?  We like to keep attribution to others wherever possible.

**Comment by achristianson** [comment]
@TylerJewell I see in the new code that it was switched to the built-in openjdk package. That means the image will track the openjdk version from the upstream centos repository. In that case, the only option is the custom stack, or wait until centos updates, which is fair enough.

I think we're all good for now. Really appreciate the assistance.

**Comment by TylerJewell** [comment]
Great, that is good to hear.  I am going to close this issue.  I am going to create another issue to have the codenvy/dockerfiles repository shut down.

Question for you - how did you find that repository?  Was there some zombie link on the internet somewhere that took you to that repo?  If so, we want to make sure that everything is pointing at the right eclipse repo.

**Comment by achristianson** [comment]
@TylerJewell I looked up the image in the official docker hub: https://hub.docker.com/r/codenvy/centos_jdk8/. That docker hub page links to the github repo in question.

**Comment by TylerJewell** [comment]
One last check - how did you find the name of the image that you were seeking? I think in the M8 release, our stacks still reference the codenvy/* version of the images, and in the master version they all release eclipse/* versions of the images.

So if that is true, once we push out 5.0.0 GA we should be able to take down the codenvy/* docker hub images, too.

**Comment by achristianson** [comment]
@TylerJewell Started out by poking around the codenvy.io UI looking for a github link so I could fork/clone instead of writing the custom stack from scratch. I didn't see links to the github repos in the UI, and figured I'd sure the docker hub. Searched for "codenvy centos" and it came up. Good to know that the eclipse/* images are the ones to look at in the future.
