### ISSUE TITLE
Pull request panel becomes hidden after page refresh

### ISSUE THREAD

**Issue by vinokurig** [codenvy/codenvy#1414]
Pull request panel becomes hidden after page refresh

**Reproduction Steps:**

1. Clone any project from GitHub to enable PR panel.
2. Open PR panel.
3. refresh the page and click the 'Pull Request' button.

**Expected behavior:**

Pull request panel is showed again.

**Observed behavior:**

Pull request panel is hidden. You have to resize the panel.

**Codenvy version:** nightly5.codenvy-stg.com, 5.0.0-M9-SNAPSHOT
**OS and version:** Chrome 55.0.2883.87 (64-bit), Ubuntu 16.04

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: Don't know
Problem can be reliably reproduced: Yes

![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/7668752/21438223/98b56e34-c890-11e6-9bb8-58d93243cbbe.gif)

**Comment by TylerJewell** [comment]
That is kind of random!  Nice, find @vinokurig.

**Comment by vinokurig** [comment]
Can not reproduce in 5.10-SNAPSHOT
