### ISSUE TITLE
Create new docs repos

### ISSUE THREAD

**Issue by JamesDrummond** [codenvy/codenvy#1416]
Create codenvy/codenvy-docs repo and temporary codenvy/che-docs . 

codenvy/che-docs will be delete as soon as eclipse creates the docs repo we requested and we copy content from codenvy/che-docs to eclipse repo.

**Comment by slemeur** [comment]
Precision:
The content of the repos must be initialized with the current state of master for the docs folder.

**Comment by JamesDrummond** [comment]
@slemeur We(PMs) will handle this. It can be empty.

**Comment by skryzhny** [comment]
Repos created.
They are public and all devs can push to it.
