### ISSUE TITLE
dev mode not consistent

### ISSUE THREAD

**Issue by riuvshin** [codenvy/codenvy#1431]
after introducing agents as separate container by @tolusha dev mode become not consistent because we mount only codenvy API server for dev mode but not agents. 
so we have to mount agents binaries to agents container same way as we do this with api server.
NOTE that we don;t need this for che as in che we don't have agents container so this is only needed for codenvy.

I've tried to do this but after consolidation of che and codenvy CLI I don't understand how to make something specific for codenvy only.

**Comment by TylerJewell** [comment]
Methods can be overridden so in the codenvy cli we can duplicate and override any method from the base cli. We also have pre and post logic methods for key commands like init.  I will show you on Wednesday.

**Comment by TylerJewell** [comment]
@riuvshin - I will be back in the office on Thursday. 

Prior to that, where I would start with modifications are files in this folder:
https://github.com/codenvy/codenvy/tree/master/dockerfiles/cli/scripts

These methods override the same methods called in the base CLI. if the method does not existing in this repository, then it uses the same method in the base.

I would do a search for all of the locations that have DEVELOPMENT_MODE statements, and then add the appropriate logic there.

**Comment by riuvshin** [comment]
@TylerJewell thx for explanations, i have already some progress on this.

**Comment by riuvshin** [comment]
PRs proposed.
