### ISSUE TITLE
Show pop-up that notifies user about login expiration

### ISSUE THREAD

**Issue by garagatyi** [codenvy/codenvy#1440]
Sometimes login data expires while user works in UD or IDE.
It may happen because of very long usage session or most frequently after restarting of master server.
In that case user see no sign that UD and IDE doesn't work. It is confusing.

**Reproduction Steps:**

1. Open UD
2. Restart codenvy
3. Take a look at UD. Navigate views. No sign that something is wrong.
4. Try to start WS or refresh page. There are signs that user was logged out.

**Expected behavior:**

Login data expiration should lead to showing user some useful message or dialog.

**Observed behavior:**

Nothing is shown until user starts WS or refresh page.

**Codenvy version:** 5.0.0-Snapshot
**OS and version:** Ubuntu 16.04

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: [No]
Problem can be reliably reproduced: [Yes]

**Comment by skabashnyuk** [comment]
won't fix
