### ISSUE TITLE
Make Codenvy not to include projects of workspace into snapshot 

### ISSUE THREAD

**Issue by garagatyi** [codenvy/codenvy#1443]
When Codenvy run in containers it includes projects of workspace into snapshot of workspace. But they are also stored in projects backup storage.
This means that we can speed up creation of snapshots by excluding projects from snapshot somehow.
Since snapshotting doesn't respect .gitignore or any other rules to reduce snapshot size in can take a lot of time to snapshot workspace with big amount of binaries in target folders for example.

**Reproduction Steps:**

1. Create and start WS.
2. Create project.
3. Snapshot WS.
4. Take snapshot image id (for example by catching it from WS output on WS restoring)
5. Execute in system terminal `docker run <caught snapshot image> ls /projects/` 

**Expected behavior:**

Error that path doesn't exist.

**Observed behavior:**

Project folder is shown.

**Codenvy version:** 5.0.0-Snapshot
**OS and version:** Ubuntu 16.04

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: [No]
Problem can be reliably reproduced: [Yes]

**Comment by JamesDrummond** [comment]
@garagatyi How is snapshotting done currently through `docker commit` ? All the subfolders in `/projects` are docker volumes if created through GUI right?

**Comment by garagatyi** [comment]
/projects is a single volume in Che. In Codenvy it is regular folder.

**Comment by JamesDrummond** [comment]
@garagatyi Thanks. I think I had some issues when running che while codenvy is running. I think che is messing with existing codenvy workspace containers. I had a codenvy project subfolder in a volume mount which may have been created after starting che. I have not had time to investigate this further.

**Comment by garagatyi** [comment]
I didn't get what problem you had. Please create an issue for this bug if you can reproduce it

**Comment by garagatyi** [comment]
Code is finished and passed review. Now PRs are in QA cycle.

**Comment by garagatyi** [comment]
Found a bug with backuping of projects. QA is delayed, I'll work on fix of that issue.
