### ISSUE TITLE
New deploy server.

### ISSUE THREAD

**Issue by JamesDrummond** [codenvy/codenvy#1447]
I would like to propose that we create another deploy server for master branch like https://nightly5.codenvy-stg.com/ to be something like https://half-hour.codenvy-stg.com/. It will deploy every half an hour on the hour such as 12:00, 12:30, 1:00 etc. 

I currently am faced with an issue working on docs build that I cannot determine if changes made will work correctly when built with CI. I can successfully build using my environment but I am not sure if I will have the same results when the CI builds.

CI system already builds constantly so the additional server resources would be in deploying to server. Not sure how we want to handle creation/storage of docker images. I would like to have codenvy/\<repo-name\>:dev on docker hub for these half and hour builds.

I am aware that the server will reboot every 30 minutes and all work will be lost. I would not use the server to develop on only to quickly test if features work correctly.

Dev teams has access to manually have CI build branches. However, PM's, contributors, and maybe certain dev team members may not have direct access to this. This also requires learning how to use the CI system.

The following should be done in order. The codenvy/\<repo-name\>:dev should be done without waiting for the deploy as developers can use it on their own machine for testing.

- [ ] Docker image codenvy/\<repo-name\>:dev on docker hub every half an hour.
- [ ] Create deploy server at https://half-hour.codenvy-stg.com/ .
- [ ] Update deploy server at https://half-hour.codenvy-stg.com/ every half an hour.

**Comment by JamesDrummond** [comment]
@TylerJewell Please review when ever you get a chance. No rush.

**Comment by TylerJewell** [comment]
@JamesDrummond - it is about a 3-4 hour process to build everything from scratch. So I think the biggest hurdle to what you are seeking is that it's not possible to just incrementally rebuild. If the issue is particularly around docs, why not just have a staging server just for the docs component?

**Comment by TylerJewell** [comment]
This is an infrastructure and production issue, not a code repo issue.
