### ISSUE TITLE
Add possibility to add agent in Codenvy using agent definition file as it is done in Che 

### ISSUE THREAD

**Issue by garagatyi** [codenvy/codenvy#1449]
Now Che adds agent definition files from jars. But we can't do that in Codenvy. 
So the only way to add agent in Codenvy is to to that in code. It is not convenient.

**Comment by tolusha** [comment]
Outdated.

Follow the doc how to add a new agent.
https://eclipse.org/che/docs/workspace/agents/index.html#creating-new-agents
