### ISSUE TITLE
Is codenvy on prem multi tenant?

### ISSUE THREAD

**Issue by levjason** [codenvy/codenvy#1459]
Does  codenvy on prem support multi tenancy? I just installed 5.0.0-M8 and don't see how to create tenants.

**Comment by TylerJewell** [comment]
Depends upon your definition of a "tenant". 

If a tenancy is defined as having a separated user database and domain management for a group of users, then no we do not support that (in this situation, just deploy a new version of Codenvy with a separate database).  

However, on a single deployment, there are mechanisms for creating multiple teams, each with their own isolation of resources, stacks, and membership. These capabilities are baked in at the API level only, and will be surfaced with a rich GUI in 5.1 - probably before the end of January.

Can you elaborate a bit more on the tenancy dynamic you are seeking?

**Comment by eivantsov** [comment]
Closed due to inactivity. Feel free to reopen if you still need clarification.
