### ISSUE TITLE
Cannot SSH to plan.io

### ISSUE THREAD

**Issue by mbrung** [codenvy/codenvy#1460]
I can not connect to plan.io (https://plan.io) via SSH from the workspace console, and therefore cannot clone GIT repositories they host on our behalf.  I understand from #1071 you restrict outbound traffic.  Is there a standard way to request whitelisting?

# Reproduction Steps

- Create a VCS SSH key for plan.io in Codenvy (<company_name>.plan.io) (via Profile > Preferences > SSH > VCS).
- Add the public key to your plan.io account.
- In the Codenvy console type (`ajileso` being our company name):
> ssh -v git@ajileso.plan.io

# Expected behavior
SSH connection should not time out.

# Observed behavior
```
$ ssh -v ajileso.plan.io                                                                        
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014                                                                                   
debug1: Reading configuration data /etc/ssh/ssh_config                                                                     
debug1: /etc/ssh/ssh_config line 19: Applying options for *                                                                
debug1: Connecting to ajileso.plan.io [82.98.82.207] port 22.                                                              
debug1: connect to address 82.98.82.207 port 22: Connection timed out                                                      
ssh: connect to host ajileso.plan.io port 22: Connection timed out      
```

Codenvy version: 5.0.0-M8
OS and version: hosted on codenvy.io

**Comment by TylerJewell** [comment]
@mbrung - I've forwarded your request to the support team which will take a look and if plan.io matches our whitelisting criteria, they will open it up.

**Comment by planio** [comment]
@TylerJewell let us know if we can help. Alternatively, all our repos are also accessible via HTTPS.

**Comment by mbrung** [comment]
Thanks @TylerJewell, it works!

**Comment by planio** [comment]
👍
