### ISSUE TITLE
Factory config not applied (regression)

### ISSUE THREAD

**Issue by eivantsov** [codenvy/codenvy#1462]
Workspace config isn't applied when a Factory is created from a GitHub repository.

**Reproduction Steps:**

Click https://codenvy.io/f?url=https://github.com/turngeek/JavaEEinaDay_My-Memo-Servlet

**Expected behavior:**

Workspace is created with machine based wildfly image 

**Observed behavior:**

For some reason, ubuntu_jdk8 is used and workspace config in the root of a GitHub repository isn't applied.

**Comment by TylerJewell** [comment]
As part of this fix, we should also look at making our Factory documentation clearer on the precedence ordering of .codenvy.json vs. Chefiles vs. Dockerfile vs. docker-compose.yml file.

**Comment by eivantsov** [comment]
@TylerJewell but right now we respect .codenvy.json only. I mean this Factory service.

**Comment by TylerJewell** [comment]
You may not be aware but I believe in M7 florent slipped in a feature that lets factories also use chefile along with the JSON in a repo.

**Comment by benoitf** [comment]
I'm removing the **"blocker"** status because the issue is that it's the json file that is invalid

Codenvy factories are expecting a "workspace" element in json file

fixing file in my fork is working : https://codenvy.io/f?url=https://github.com/benoitf/JavaEEinaDay_My-Memo-Servlet

**Comment by benoitf** [comment]
correct file is at https://github.com/benoitf/JavaEEinaDay_My-Memo-Servlet/blob/master/.codenvy.json

**Comment by schmolli** [comment]
You probably have tested it, but it still does not work (in your fork and in mine, too). 

The workspace does not start due to the following error:

"Incorrect workspace name, it must be between 3 and 20 charackters and may contain digits, latin letters, underscores, dots, dashes and should start and end only with digits, latin letters or underscores". 

But, the workspace name fulfills the mentioned requirements.

**Comment by benoitf** [comment]
@schmolli if you already have a workspace with the name, it will create a new name for the new workspaces by suffixing some digits
As "JavaEEinaDay_My-Memo-Servlet" is already having 20 characters I think it's why it fails in your case.
Try to remove any previous workspaces having "JavaEEinaDay_My-Memo-Servlet" as name or update json file with a shorter name to allow "-1", "-2, etc
