### ISSUE TITLE
Create new workspace with custom docker file "Error detecting content type for remote"

### ISSUE THREAD

**Issue by paratechnical** [codenvy/codenvy#1463]
[Short description of problem here]
I created a dockerfile in hub.docker.com so I can have a workspace with Android and docker.
I extended codenvy/ubuntu_android
[https://hub.docker.com/r/paratechnical/androidgradlecodenvy/~/dockerfile/](https://hub.docker.com/r/paratechnical/androidgradlecodenvy/~/dockerfile/)
The dockerfile seems to build succesfully
I am really new to codenvy and docker
**Reproduction Steps:**

[First Step]
I went to https://codenvy.io/dashboard/#/create-project
[Second Step]
Select Workspace->Create new workspace from stack->Stack import
Recipe URL: https://hub.docker.com/r/paratechnical/androidgradlecodenvy
I selected Gradlefile as recipe type
[Other Steps...]

**Expected behavior:**

I expected the workspace to be created succesfully

**Observed behavior:**

I received this error
https://hub.docker.com/r/paratechnical/androidgradlecodenvy

Error when starting agent
Unable to start workspace agent. Error when trying to start the workspace agent: Start of environment AndroidCuGradle failed. 
Error: Error response from docker API, status: 500, message: Error response from daemon: Error detecting content type for remote https://hub.docker.com/r/paratechnical/androidgradlecodenvy: unsupported Content-Type "text/html; charset=utf-8"

**Codenvy version:** The version on codenvy.io
**OS and version:** Windows 10
**Browser version:** Chrome 55

**Other questions:**
Problem happens at codenvy.io or with the installed Codenvy Enterprise?: codenvy.io
Problem can be reliably reproduced: Yes

**Comment by eivantsov** [comment]
@paratechnical you need to use a direct link to a Dockerfile content which in your case is https://raw.githubusercontent.com/paratechnical/DockerFiles/master/CodenvyAndroidGradle/Dockerfile

**Comment by mbrung** [comment]
If I may I find the Che documentation a bit misleading in this case:

https://eclipse-che.readme.io/docs/recipes#section-unsupported-compose-syntax

```
build:
  ## remote context will work
  context: https://github.com/eclipse/che-dockerfiles.git#master:recipes/ubuntu_jre
```

In this case, `context` needs to point to the actual Dockerfile...

**Comment by TylerJewell** [comment]
@JamesDrummond - can you please take a look at this, and identify if our documentation needs some more examples and clarification per @mbrung's point?

The docs for this page are saved here. We can get a PR for it.
https://github.com/codenvy/che-docs/blob/master/src/main/_docs/workspace-administration/ws-recipes.md

**Comment by eivantsov** [comment]
@paratechnical you are talking about different use cases - a direct link to a Dockerfile, and Dockerfile reference in a compose file as build context.

**Comment by paratechnical** [comment]
@eivantsov I don't understand exactly what you mean.

**Comment by TylerJewell** [comment]
I think Eugene was targeting his comment to James and probably just mistyped the handle.

In your case - eugenes instructions are correct - you just need our stack recipe to point directly to your dockerfile.

**Comment by paratechnical** [comment]
@TylerJewell  oh, ok. Yes, I did that and it works just fine. Thank you.

**Comment by nenads** [comment]
Hi,
Can you explain more about this url format

build:
  ## remote context will work
  context: https://github.com/eclipse/che-dockerfiles.git#master:recipes/ubuntu_jre

direct Dockfile url is working, while building image from context using this url are not. is this error in documentation or this is new feature that is not implemented yet.

**Comment by eivantsov** [comment]
@nenads can you elaborate please? I don't understand what exactly needs to be explained.

**Comment by nenads** [comment]
https://i.imgur.com/GBarsS9.png

i cant make this use case work. maybe i'm doing something wrong.

This is part of bigger problem, and i'm want to make/learn all casess from documentation so i could figure out how and what is best best way to store public and private images/docks

**Comment by eivantsov** [comment]
@paratechnical you are using the wrong URL. It should be a raw link to your Dockerfile

**Comment by nenads** [comment]
@eivantsov thanks for replay. 

That is my question is there case when this url is valid

https://github.com/eclipse/che-dockerfiles.git#master:recipes/ubuntu_jre

or this #master:recipes/ubuntu is just for us human to know what file we need to link

**Comment by eivantsov** [comment]
@nenads https://github.com/eclipse/che-dockerfiles.git#master:recipes/ubuntu_jre does not take me to the Dockerfile but this link does - https://raw.githubusercontent.com/eclipse/che-dockerfiles/master/recipes/ubuntu_jdk8/Dockerfile

**Comment by nenads** [comment]
@eivantsov thank you for replay.

on documentation url https://www.eclipse.org/che/docs/workspace/recipes/

![image](https://cloud.githubusercontent.com/assets/1824176/23658207/e65a297c-0341-11e7-9628-16ef86af5969.png)

What is this use case then, where it should be used? this is giving me so much confusion.

**Comment by eivantsov** [comment]
@JamesDrummond does the example in docs actually work?

**Comment by nenads** [comment]
@eivantsov that is the thing where should i use this url and in what context (ui)

1. have tried when adding recepie
2. when adding stack
3. changing .json manualy.

does this referse to docker-compose.yml file ?

**Comment by eivantsov** [comment]
@nenads I am confused.. can you elaborate on what exactly you are trying to achieve? What have you tried using with no luck?
