### ISSUE TITLE
Re: Trouble getting python and django urls

### ISSUE THREAD

**Issue by christophertodd** [codenvy/codenvy#1464]
cannot obtain url for django or python project

**Reproduction Steps:**
created the python or django app.

run the execution command 
"

**Expected behavior:**

to use on of the urls to view the app, displaying the usual welcome to django page

**Observed behavior:**

non of the urls provided in the servers tab work, and have the following errors:

**Codenvy version:** [Enter Codenvy version here]
**OS and version:** [Windows 7 Enterprise
**Browser version:** [chrome Version 55.0.2883.87 m]
**Other Questions
which URL address should i actually be using here?

many thanks

**Comment by eivantsov** [comment]
@christophertodd can you share your execution command please? Did you run Django server directly in the terminal or as a command through the command widget?

**Comment by christophertodd** [comment]
@eivantsov  Thanks for getting in touch so quickly, and sorry for not placing the execution command in the original post; an oversight on my part. Please find quoted below.

"cd ${current.project.path} && python manage.py runserver "

I have run the equilivant in the terminal, shown below, but i check every url on the server tab, and receive error messages.

![image](https://cloud.githubusercontent.com/assets/24678950/21645165/da94b22c-d288-11e6-8976-9c7ecc0fefe8.png)


Also, i have tried to run it from the command widget and the following screen appears with the same results of error messages in the html

![image](https://cloud.githubusercontent.com/assets/24678950/21645281/4f9b9838-d289-11e6-9822-e9e65cd72e70.png)

many thanks in advance

**Comment by christophertodd** [comment]
Hi,

I found how to expose a port, but I still cannot get this to work, any ideas?
![image](https://cloud.githubusercontent.com/assets/24678950/21808664/2988787a-d73c-11e6-90d1-28a1aeeae416.png)


Many thanks,

**Comment by eivantsov** [comment]
You may find Eclipse Che docs helpful: http://www.eclipse.org/che/docs/ide/previews/index.html

**Comment by christophertodd** [comment]
Thanks Eivantsov!
