### ISSUE TITLE
Investigate the ways to measure bootstrap performance using jvisualvm for codenvy in docker

### ISSUE THREAD

**Issue by evoevodin** [codenvy/codenvy#1466]
The issue #1364 describes components load time: overall tomcat load time is ~60seconds while components load time is just ~1/10-1/20 of it, so it's weird that it takes so much time to boot.

The goal of this issue is to provide detailed guide and instructions for connecting & using jvisualvm(or any worthy alternative) for measuring various metrics for codenvy in docker. Along with that bootstrap metrics must be measured and described in all the details.

**Comment by skabashnyuk** [comment]
Guide how to connect jprofiler to wsagent.
1. Create new workspace from dockerfile
```
FROM eclipse/ubuntu_jdk8

RUN wget -q http://download-aws.ej-technologies.com/jprofiler/jprofiler_linux_8_1_2.tar.gz -P /tmp/ &&\
  sudo tar -xzf /tmp/jprofiler_linux_8_1_2.tar.gz -C /usr/local &&\
  rm /tmp/jprofiler_linux_8_1_2.tar.gz

ENV CATALINA_OPTS=" $CATALINA_OPTS -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -agentpath:/usr/local/jprofiler8/bin/linux-x64/libjprofilerti.so=8849"

EXPOSE 8849
````
2. Run it. And take a look how 8849 port exposed
<img width="1440" alt="2017-01-06 15 24 19" src="https://cloud.githubusercontent.com/assets/1614429/21721740/5a276962-d432-11e6-96eb-f040f5ed99a3.png">
3. Connect jprofiler to this port 
<img width="1440" alt="2017-01-06 15 24 52" src="https://cloud.githubusercontent.com/assets/1614429/21721770/76235d2e-d432-11e6-9dee-c71e1ff2fb5b.png">

**Comment by skabashnyuk** [comment]
Results of ws-agent profiling.
Overall tomcat boot takes ~10 seconds.
<img width="1440" alt="2017-01-06 15 09 27" src="https://cloud.githubusercontent.com/assets/1614429/21721852/be373112-d432-11e6-8c61-d37fa8ccf83f.png">
~5 seconds takes tomcat initialization. Most of the time takes jar scanning for annotations.
~3 seconds takes war files initialization.

Longest components initialization takes <1sec
<img width="1440" alt="2017-01-06 15 11 37" src="https://cloud.githubusercontent.com/assets/1614429/21721914/fd47cc40-d432-11e6-827b-4e8c287fc75d.png">

**Comment by TylerJewell** [comment]
I have added this profiling workflow into the Wiki of our development flow.  One alternative thing you could have done was to use `docker inspect` to get the ephemeral port instead of the Che REST API.

**Comment by tareqhs** [comment]
Hi,

Notice that the delays you are observing are critically by by the static initialization ( ``<clinit>`` ) of ``DtoFactory``. It loads all the generated DTO implementation classes transitively. Class loading time is a direct product of the bytecode size, which is _huge_ in the current DTO generation method - DTO implementations classes in the workspace API alone is ~112KB.

One benefit my PR https://github.com/eclipse/che/pull/3103 is reducing the generated DTO code due to replacing it with native ``Gson`` methods.

**Comment by skabashnyuk** [comment]
My summary for this issue. I would say we have a couple of issues to do.
1. Take a look on tareq request https://github.com/eclipse/che/pull/3103. May be it somehow will help with DTO loading. Approximate ~1 second of boot time.
2. We should review our ws-agent war content it may reduce the size of all agent ,  it can reduce time of indexing etc. https://github.com/eclipse/che/issues/3718
