### ISSUE TITLE
Do not remove ignored artifacts on workspace stop per default

### ISSUE THREAD

**Issue by gbatalski** [codenvy/codenvy#1468]
I'm facing the problem that the ignored artifacts are removed automatically on workspace stop, while the untracked or changed artifacts aren't.

**Reproduction Steps:**
Create or clone a project with git scm 
Create .gitignore with some entries
Create a file that matching ignore pattern
Stop and restart workspace

**Expected behavior:**

Do not remove the ignored files per default and/or let us to configure this.

**Observed behavior:**

Ignored files are removed after restarting the workspace

**Codenvy version:**  
**OS and version:** Azure Team Image
**Browser version:** any

**Other questions:**
Problem happens at codenvy.io or with the installed Codenvy Enterprise?: On-premise Azure Team
Problem can be reliably reproduced: Yes

Regards Gena

**Comment by eivantsov** [comment]
@gbatalski we use rsync to backup and restore workspace projects with the following parameter:

`--filter=':- .gitignore'`

This is done on purpose, to avoid syncing huge files (usually binaries) and keep in sync source code only.

**Comment by gbatalski** [comment]
can i customize this behaviour?

**Comment by TylerJewell** [comment]
@gbatalski - would like to hear more about your use case here. It's entirely possible that our policy isn't the right one for choosing what we save to long term storage. But our basic reasoning is that if you are not wanting to save it to git, why would you want to incur the cost of saving it in longer term storage, which will be just as expensive?

@eivantsov - it could be argued that everything that is in .gitignore should be saved in the snapshot, whic we do not becuase the snapshot does not include /project.

**Comment by TylerJewell** [comment]
@gbatalski - you can customize your .gitignore - you cannot customize how our rsync background process saves your files into long term storage (easily) without running Codenvy on your own.

**Comment by gbatalski** [comment]
In a given project we use nodejs but won't commit the *node_modules* folder to git and put it to gitignore. So i must run `npm install` every time  workspace is restored and it produces some traffic and some delay . On the other hand, folders  *build*, *dist*, *target* which are also within the .gitignore shouldn't be automatically rsynced. Could we get some kind controll over the rsync process like .codenvyignore or so?  But i don't have an idea how it could  be an elegant pluggable addion to default behaviour: eg. rsync as usual using the .gitignore but include node_modules.

**Comment by TylerJewell** [comment]
There are two possibilities:
1. If you can have the artifacts from your `npm install` placed into a folder in the workspace that is outside of `/projects` then those files will be automatically saved when you stop your workspace with a snapshot. Snapshot is done by default and we image the container with everything but the files in `/projects`.  When you restart the workspace, we create a runtime from the snapshot image and then rsync stuff back into `/projects`.

2. You could install Codenvy on-prem with our new Dockerized system. And we could show you where the rsync command is implemented and then you could change the nature of the rsync command.  We have been working on this new installation type for many quarters and we are planning to ship it this week, so it's well tested.
https://github.com/codenvy/codenvy/tree/master/docs/_docs/admin-guide

**Comment by gbatalski** [comment]
Ok, the first solution could be a quick win for now. The dockerized installation is an alternative to the currently used Azure Codenvy Team On-Premi setup. I'll give it a try this week.

**Comment by eivantsov** [comment]
@TylerJewell I think it may make sense to let On Prem users decide if or not they want to backup everything that is in .gitignore. However, there are risks here. `/target` dir in Maven projects can be huge and syncing it may fail due to timeout. `node_modules` - totally agree! Running npm install each time isn't good.

**Comment by TylerJewell** [comment]
That could be one way to address it.  Another could be to replace our rsync engine with the unison sync capability that we use for fuse based file systems.  That capaibikity has a profile object which we expose to users that let users have explicit include and exclude definitions of what to sync onto their desktop.

If rsync has the same file definition then we could just expose that and allow for overrides in the codenvy.env file.

**Comment by eivantsov** [comment]
Closing this issue. Please follow https://github.com/codenvy/codenvy/issues/1518
