### ISSUE TITLE
Find steps to reproduce concurrent restore processes on the same workspace

### ISSUE THREAD

**Issue by mmorhun** [codenvy/codenvy#1473]
We have problem with concurrent restore processes on the same workspace (see #1403 ) and we should investigate the reasons of it or at least find steps to reproduce it.
Is needed for https://github.com/codenvy/codenvy/issues/1403

**Comment by mmorhun** [comment]
I've found the reason of concurrent restore processes. It is caused by injecting two rsync agents into workspace.
Steps to reproduce:
1. Click `Add workspace` on dashboard
2. Go to `Runtime` -> `Machines` -> `DEV-MACHINE`
3. Add `Rsync sync agent that uses rsync on host` and `Rsync sync agent`
4. Create and run this workspace
Workspace will fail to start with message: `Could not start workspace **********. Reason: Start of environment default failed. Error: Restore of workspace workspace************** failed. Another restore process of the same workspace is in progress`

**Comment by helpmewithcodenvy** [comment]
How do you resolve the problem though? I still can't access my workspace even if none of them seems to be running

**Comment by TylerJewell** [comment]
You are tripped up into this issue - we have a fix that we have merged and released.  We will ship it shortly to update codenvy.io with it.  https://github.com/codenvy/codenvy/issues/1803#issuecomment-280955009

**Comment by helpmewithcodenvy** [comment]
Sorry I'm new to codenvy. Can you please explain step by step how to resolve this problem because I don't want to restart all my work?

**Comment by TylerJewell** [comment]
Please refer to the other thread - there is a fix in the 5.3.0 release which we will push into codenvy.io very shortly.  Thanks for being patient!
