### ISSUE TITLE
MySQL Dockerfile location

### ISSUE THREAD

**Issue by mbrung** [codenvy/codenvy#1475]
In the Java-MySQL stack, I noticed you use a tailored MySQL Docker image for which I am unable to locate the Dockerfile in https://github.com/codenvy/dockerfiles; where can I find it?  (the goal being to do something similar for Postgres).

**Comment by eivantsov** [comment]
@mbrung we will be using official mysql image after codenvy.io is updated to the next version.

As to the Dockerfile, here it is:

```
FROM mysql
EXPOSE 3306
CMD mysql -uroot -e "CREATE USER '$MYSQL_USER'@'%' IDENTIFIED BY '"$MYSQL_PASSWORD"'" && \
    mysql -uroot -e "GRANT ALL PRIVILEGES ON *.* TO '$MYSQL_USER'@'%' IDENTIFIED BY '"$MYSQL_PASSWORD"'; FLUSH PRIVILEGES;" && \
    mysql -uroot -e "CREATE DATABASE $MYSQL_DATABASE;" && \
    tail -f /dev/null

```

**Comment by mbrung** [comment]
Thanks @eivantsov for your answer.  Do you mean that, once codenvy.io is updated to 5.0.0-M9 you will be using the official MySQL Docker image?

**Comment by eivantsov** [comment]
@mbrung yes, correct!

**Comment by JamesDrummond** [comment]
This issue is resolved. We are now using the official image https://github.com/eclipse/che/commit/5bb51e0344fa306b4ddf9dbbcf54e290a18cc593#diff-be4e3a94b98c39160862773dcffad022R49
