### ISSUE TITLE
Codenvy restart leaves unnamed volume which litters host system

### ISSUE THREAD

**Issue by garagatyi** [codenvy/codenvy#1477]
Each time codenvy is started it creates volume. Looks like this volume is empty.
After every restart existing volume is left and new is created. 

**Reproduction Steps:**

1. Start Codenvy.
2. Check volumes with `docker volume ls`
3. Restart Codenvy.
4. Check volumes with `docker volume ls`
5. Repeat 3,4 several times to see that number of volumes constantly grows.

**Expected behavior:**

Codenvy removes created volume or uses the same volume each time.

**Observed behavior:**

Codenvy doesn't remove volume and creates new one on each start.

**Codenvy version:** 5.0.0-Snapshot
**OS and version:** Ubuntu 16.04

**Other questions:**
Problem happens at codenvy.io or with the installed Codenvy Enterprise?: Codenvy Enterprise
Problem can be reliably reproduced: [Yes]

**Comment by mshaposhnik** [comment]
Fixed in https://github.com/eclipse/che/pull/4134
