### ISSUE TITLE
Custom stack and "user" directive

### ISSUE THREAD

**Issue by mbrung** [codenvy/codenvy#1478]
It seems there is no way to override the default user inside a container by using the `user` compose command.  The default user seems to be `root`, which prevents some programs (e.g. Postgres or ElasticSearch) from starting.

**Reproduction Steps:**

* Create a new workspace and go to the _Stack authoring_ tab
* Paste the following:
```
services:
  db:
    image: postgres
    user: postgres
  dev-machine:
    image: alpine_jdk8
    depends_on:
      - db
```
* Hit "Apply"

**Expected behavior:**

I expect the file to be saved, as the `user` command is not listed as *not supported* in https://eclipse-che.readme.io/docs/recipes#section-compose-syntax-support

**Observed behavior:**

An error occurs, indicating the `user` command is not allowed:

```
Parsing of recipe of environment 'wksp-ek8x' failed. Error: Parsing of environment configuration failed. Unrecognized field "user" (class org.eclipse.che.plugin.docker.compose.ComposeServiceImpl), not marked as ignorable (15 known properties: "expose", "networks", "container_name", "command", "build", "volumes_from", "mem_limit", "ports", "environment", "depends_on", "links", "volumes", "image", "entrypoint", "labels"]) at [Source: java.io.StringReader@2a3f5f17; line: 4, column: 19] (through reference chain: org.eclipse.che.plugin.docker.compose.ComposeEnvironment["services"]->java.util.LinkedHashMap["db"]->org.eclipse.che.plugin.docker.compose.ComposeServiceImpl["user"])
```

**Codenvy version:** 5.0.0-M8
**OS and version:** CentOS 7.3

**Other questions:**
Problem happens at codenvy.io or with the installed Codenvy Enterprise?: Codenvy Enterprise
Problem can be reliably reproduced: Yes

**Comment by eivantsov** [comment]
Marking it as docs issue.

This PR fixes the problem with using official DB images: https://github.com/eclipse/che/pull/3049

**Comment by mbrung** [comment]
In Postgresql's case, the container starts as expected but terminates, as the `postgres` program refuses to run as `root`.

My understanding of eclipse/che#3049 is there was something wrong with the way the Docker API was invoked (overriding `command` and `entrypoint`), thus preventing the container from starting properly.  Am I reading this correctly?  If so, the PR you mention does not appear to address this ticket.

**Comment by eivantsov** [comment]
@mbrung it's because this fix is not on codenvy.io yet.

As you can see, master uses mysql image https://github.com/eclipse/che/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json#L49

It works for postgres as well.

**Comment by mbrung** [comment]
Thanks @eivantsov!
