### ISSUE TITLE
Unexpected exception when restarting workspace after create new folder

### ISSUE THREAD

**Issue by artaleks9** [codenvy/codenvy#1481]
**Reproduction Steps:**
* Create new workspace
* Create new project from template (e.g. web-java-spring)
* Create new folder (it is important!)
* Perform restart the workspace

**Expected behavior:**
* The project should be restored

**Observed behavior:**
* Unexpected exception in the IDE
* Need to refresh web page

**Codenvy version:** 5.0.0
**OS and version:** [Ubuntu 14.04
**Browser version:**  Chrome, Version 55.0.2883.87 (64-bit)

**Other questions:** 
* Problem can be reliably reproduced: [Yes]
* See the attachment:
![restart_ws_after_create_folder](https://cloud.githubusercontent.com/assets/5408906/21680900/2812523a-d355-11e6-8973-001fd821411e.png)

**Comment by vzhukovskii** [comment]
PR: https://github.com/eclipse/che/pull/3626

**Comment by riuvshin** [comment]
PR is merged, closing issue
