### ISSUE TITLE
Create LDAP configuration guide

### ISSUE THREAD

**Issue by evoevodin** [codenvy/codenvy#1482]
It is usually a problem for customers to configure their LDAP to use it with codenvy.
DOD of the issue is to write a guide which will help customers to set up users synchronization and authentication appropriately. 
- Describe all the authentication types and configuration properties, maybe in interactive manner e.g.

  What LDAP is used?
  AD/OpenLDAP
      - if AD then authentication type is either AD or AUTHENTICATED
      - if authentication type is AD then only those should be used.

- Describe LOG points that allow user to understand whether synchronization/authentication is configured correctly
- Describe the kind of feedback that may be useful for US to understand customer's problems e.g.
kind of logs we want, schema if possible, whether customer uses groups or not etc

**Comment by evoevodin** [comment]
The example of pure feedback from customer:
https://github.com/codenvy/infrastructure/issues/42

**Comment by bmicklea** [comment]
Yevhenii has created the guide in Gist, I'm working on how to best integrate it into our docs.
