### ISSUE TITLE
Scripts that build Codenvy CLI and other images fail on Ubuntu 16.04

### ISSUE THREAD

**Issue by garagatyi** [codenvy/codenvy#1485]
When I try to build Codenvy CLI image on my system I get errors like this:
```
✔  16:52 ~/workspace/codenvy/dockerfiles/cli [ master ↓·1↑·17 | ⚑ 3 ] $ ./build.sh
./build.sh: 16: ./build.sh: [[: not found
Building Docker Image codenvy/cli from /home/gaal/workspace/codenvy/dockerfiles/cli directory with tag 
invalid argument "codenvy/cli:" for t: Error parsing reference: "codenvy/cli:" is not a valid repository/tag
See 'docker build --help'.
Failure when building docker image codenvy/cli:

✔  16:52 ~/workspace/codenvy/dockerfiles/cli [ master ↓·1↑·17 | ⚑ 3 ] $ 
```

Looks like it uses default shell (which is dash in my case I suppose) but syntax `if [[ ]]; then` is unsupported.

**Codenvy version:** 5.0.0-Snapshot
**OS and version:** Ubuntu 16.04

**Other questions:**
Problem can be reliably reproduced: [Yes]

**Comment by benoitf** [comment]
Fix provided by PR https://github.com/codenvy/codenvy/pull/1494
