### ISSUE TITLE
golang project not in gopath

### ISSUE THREAD

**Issue by wolski** [codenvy/codenvy#1491]
I did create a workspace for golang development at codenvy.io :

workspace -> ready-to-go Stacks -> GO 

In the terminal, I run 
go env
which shows that
GOPATH="/projects/go" 

If I create a project with project new it is created in 
"/projects"

although AFAIK go projects should reside in $GOPATH$/src/

**Comment by TylerJewell** [comment]
@wolski - thank you for reporting these issues.  I think we should ask some of our engineers to take a look at this.  As a default, we put all of the project root code into /projects as this is the folder that is volume mounted from the host into the project.  So if Go has certain best practices, we need to honor and respect those criteria for out of the box Go projects while still keeping files in the /projects folder within the container.

@skabashnyuk - I think this is a platform team issue. Please advise if you think different.

**Comment by skabashnyuk** [comment]
I think this is more for GO -stack developer.
As an idea it can be implemented like this 
- GOPATH="~/go"
- After each project's creation create a symlink from ~/projects/{projectname} to $GOPATH/project_domain/{projectname} 
- Remove symlink if needed

**Comment by slemeur** [comment]
Should update the stack

**Comment by TylerJewell** [comment]
@eivantsov - is this still actual, or can we close now?

**Comment by eivantsov** [comment]
@TylerJewell yes, there's no elegant solution here, since on one hand we have `/projects/projectName` and on the other GOPATH directory hierarchy. 

Right now `GOPATH` points to `/go`. Symlink approach will work.
