### ISSUE TITLE
Allow to specify alternative images instead of current codenvy infra images

### ISSUE THREAD

**Issue by garagatyi** [codenvy/codenvy#1492]
Sometimes we need to put results of our work to someone. With Codenvy in docker it is easier than with vagrant solution but still not convenient enough.
For example when I need get approval from QA team I should ensure that they have product in correct state to test. To do that QA engineers do:
1. Add my fork of Che as remote to git repo (can be form of side contributor).
2. Checkout correct branch.
3. Compile Che.
4. Add fork of Codenvy as remote to git repo.
5. Checkout correct branch.
6. Compile Codenvy.
7. Run Che & Codenvy with mounted sources.
8. Run QA on Che & Codenvy.

It is time consuming and error prone sequence.

I also consider possibility to provide state of feature branch to PM. In that case PM will be able to review it easily and even without asking developer to help during his work on the feature.

So I consider adding possibility to alternate docker images in codenvy to simplify these workflows.
Here is an explanation on how it can work and what it provides:
1. Developer creates feature branches in Che & Codenvy repos.
2. Developer works on it, push it.
3. Developer triggers build of Che or/and Codenvy images from his feature branches on CI.
4. CI builds Che & Codenvy, build needed images and tag it with some label, e.g. 
```
codenvy/dev_che_server:my_feature_1033
codenvy/dev_codenvy:my_feature_1033
codenvy/dev_codenvy_cli:my_feature_1033
codenvy/dev_codenvy_init:my_feature_1033
```
5. CI provides command how to start Che/Codenvy with these images.
6. QA engineer or PM or another developer runs Che/Codenvy, e.g.
```
# no changes in CLI
docker run -rm -it -v <docker sock> -v <data folder> -v <path to alternative images list file>:/images codenvy/cli:nightly start

# CLI is changed
docker run -rm -it -v <docker sock> -v <data folder> -v <path to alternative images list file>:/images codenvy/dev_codenvy_cli:my_feature_1033 start

# Che
docker run -rm -it -v <docker sock> -v <data folder> -v <path to alternative images list file>:/images eclipse/che-cli:nightly start
```

**Comment by TylerJewell** [comment]
This is a good suggestion.  But I would propose a simpler syntax.  I would not introduce a new volume mount.  I would have our CI systems just do a specialized version of the images tag & push onto dockerhub.  Something like :nightly-<job-id>.  And then we would have some way to clean up these special images when they are not needed.

The CI system knows how to do a "release" to create the necessary image lists in the /init and /version folders.  So we should take advantage of that, and just have job-specific releases with the images kept in tact.  Then no custom syntax required.  Just "docker run codenvy/cli:nightly-jobid start"

**Comment by JamesDrummond** [comment]
I would like to suggest a separate dockerhub repo like codenvy/cli-dev . The cli-dev(and codenvy-dev?) would have the job of detecting if it's image name has `-dev` and using the corresponding `-dev` images. I really want `Developer triggers build of Che or/and Codenvy images from his feature branches on CI.` to be done through a special message in the commit description like `**CI-build**`. The image could be tagged with commit sha number `codenvy/cli-dev:<sha>`. This would allow any contributors to use the CI system too build images while simplifying the build triggering process.

Additionally I would like to suggest each PR merged to have a docker image built for it. The docker image tag would have PR number so https://github.com/eclipse/che/pull/3626 would be codenvy/cli-dev:3626 . This would allow use to use these images to test but also find out which PR made a feature fail.

**Comment by garagatyi** [comment]
I also was thinking about separate dockerhub repo for this kind of stuff but Tyler's suggestion about custom tag looks interesting also. 

**CI-build** is reserved already for build. We can either build images on each build or have another command to trigger that (I don't know if second triggering phrase is supported by our CI). 

> The image could be tagged with commit sha number codenvy/cli-dev:<branch>-<sha>. This would allow any contributors to use the CI system too build images while simplifying the build triggering process.

I think we can tag each build with commit sha and some kinda latest tag. Then it would be possible to check states of each build and latest build.

I like the idea to tag images with PR's number too. I think we can have 2 jobs - building branch or building PR. Probably second one would be used more often.

 > Also to note codenvy/<name>-dev repos would never have current or nightly tags. This would prevent users from accidentally using these versions.

Having some kind of latest tag is needed in my opinion. But we can name it in another way to not interfere with non-dev workflow

**Comment by slemeur** [comment]
Raising this issue as blocker for
https://github.com/codenvy/infrastructure/issues/56

**Comment by TylerJewell** [comment]
Stevan - I don't think this issue is a blocker.  But the other issue is "blocked" waiting for this.  Blocker means that this is an issue that breaks the system.

**Comment by TylerJewell** [comment]
We provided a capability to support this with custom image names in the build of the images in the repository.
