### ISSUE TITLE
Prepare a mount of the root folder of codenvy image in dockerized version

### ISSUE THREAD

**Issue by vinokurig** [codenvy/codenvy#1496]
For Jenkins and Jira integration workflow we have to have configuration files in the root folder of `codenvy` image, so we have to have a specioal local folder, mounted to the root folder of the `codenvy` image, to save there those configuration files.
File examles: http://codenvy.readme.io/docs/continuous-integration#5-configure-connector-webhook-and-credentials-prop

**Comment by bmicklea** [comment]
@vkuznyetsov is this something that can be fit into the current sprint?  If not, please schedule for the coming sprint.

**Comment by bmicklea** [comment]
Closing this as a duplicate of the customer issue: https://github.com/codenvy/codenvy/issues/1597
