### ISSUE TITLE
Configuring workspace idle timeout in Codenvy on-prem

### ISSUE THREAD

**Issue by mbrung** [codenvy/codenvy#1500]
I have looked into the documentation but cannot seem to find a way to configure workspace idle timeout in a Codenvy on-prem installation (the same value for all workspaces would work for us) -- 10 minutes is a bit short for us.

I looked into https://github.com/codenvy/codenvy/blob/master/cdec/installation-manager-resources/src/main/resources/codenvy-properties/5.0.0-M8/codenvy-single-server.properties and couldn't find a property for it. 

Is this something that is at all configurable?

Version: Codenvy 5.0.0-M8

**Comment by TylerJewell** [comment]
Hi @mbrung.  

When you start Codenvy using the new CLI (please upgrade to 5.0.0, please), there will be a `codenvy.env` file injected into the folder that you volume mount to the `:/data` folder.

Inside of this file is a property that you can edit that alters the workspace idle timeout. And then you once you save this file just use the CLI to restart Codenvy.

The property is `CODENVY_MACHINE_WS_AGENT_INACTIVE_STOP_TIMEOUT_MS=600000`. It's commented out by default which makes workspaces for on-premises installs always-on.

https://github.com/codenvy/codenvy/blob/master/dockerfiles/init/manifests/codenvy.env#L148

Can you tell me where you were looking in the docs for this?  I can issue a PR to the docs to improve the configuration page to make it clear how you can configure this.  Clearly our docs did not make this easy to find.

**Comment by JamesDrummond** [comment]
@TylerJewell We should consider increasing the default time out of 10 minutes`600000` to maybe ~1.5hrs `6000000`.

**Comment by TylerJewell** [comment]
I believe that the embedded default is 4 hours for on-prem.

**Comment by JamesDrummond** [comment]
OK. Should the commented out values in codenvy.env match the embedded values? There are a couple variables where I see commented values not matching default values.

**Comment by TylerJewell** [comment]
They should, yes - but you should connect with engineers to find out what the source values are that are actually embedded first.

**Comment by JamesDrummond** [comment]
Docs updated. Default set to 4 hours.
