### ISSUE TITLE
It would be cool to support letsencrypt setup with haproxy and document it @

### ISSUE THREAD

**Issue by richtera** [codenvy/codenvy#1502]
https://letsencrypt.org/ allows for free SSL encryption for projects. It would be cool to document how to set it up for codenvy in an easy way.
@bmicklea

**Comment by bmicklea** [comment]
@skryzhny is this something that could be setup with HAProxy?

**Comment by richtera** [comment]
Just googled for this again and found https://www.digitalocean.com/community/tutorials/how-to-secure-haproxy-with-let-s-encrypt-on-ubuntu-14-04

**Comment by skryzhny** [comment]
I think it's not an easy way, and we have documented better way with startssl.com
https://codenvy.readme.io/docs/security
LetsEncrypt require to setup renewal script, that in other hand require to restart dockerized codenvy with downtime. I would not recommend doing that, it's more complex.
If you already using LetsEncrypt it might be easier for You just put that certificate to some path and point codenvy to use it.

**Comment by bmicklea** [comment]
@richtera so it looks like you can use Let's Encrypt with the instructions from DI or as Serhii pointed out use the method we've documented and startssl which is recommended.

Will that help?

**Comment by richtera** [comment]
Yes, thank you. For a normal deployment letsencrypt is probably not great. I was more thinking about using it for quickly deploying a machine for testing which is still protected with SSL. I was able to use it with the bitnami eclipse che deployment, but we can close this.
