### ISSUE TITLE
Unable to get "Show/Hide Hidden Files" menu to work

### ISSUE THREAD

**Issue by richtera** [codenvy/codenvy#1504]
**Reproduction Steps:**
Try the menu to reveal any file starting with "." like ".gitignore".

**Codenvy version:**    
5.0.0-M8

**OS and version:**    
CoreOS

**Docker version:**    
Docker version 1.12.3, build 34a2ead

**Codenvy cli.log output:**  
The file only contains old errors prior to last restart. This was when I was trying to load nightly but decided to revert. It has nothing to do with this problem.
```sh
.
.
.
INFO: (codenvy cli): Loading cli...
DEBUG: docker_run
DEBUG: is_boot2docker
DEBUG: is_initialized
DEBUG: is_initialized
DEBUG: is_initialized
ERROR:
ERROR: Your CLI version 'codenvy/cli:nightly' does not match your installed version '5.0.0-M8'.
ERROR:
ERROR: The 'nightly' CLI is only compatible with 'nightly' installed versions.
ERROR: You may not 'codenvy upgrade' from 'nightly' to a numbered (tagged) version.
ERROR:
ERROR: Run the CLI as 'codenvy/cli:<version>' to install a tagged version.
```

![image](https://cloud.githubusercontent.com/assets/708186/21824274/9958a5c0-d74c-11e6-8b1d-ae8ebf80fdb3.png)

**Comment by richtera** [comment]
@bmicklea Is there a cli command to ask the editor to open up a file? That way I could open a ".gitignore" file for editing even though I can't get it to show in the project hierarchy. Actually I prefer to open up files for editing using a cli anyways. On the mac I use "open" all the time.

**Comment by richtera** [comment]
Related to #1529

**Comment by bmicklea** [comment]
That's strange, I'm using 5.0.0-M8 on codenvy.io and showing hidden files does show the dotted directories:

![screen shot 2017-01-10 at 4 42 39 pm](https://cloud.githubusercontent.com/assets/7644938/21826003/e4184a78-d753-11e6-82f6-929401b7260e.png)

What stack are you using?

**Comment by richtera** [comment]
Hmm, ok. Not sure what changed but I stopped and restarted my instance and now the menu seems to work. Must be some kind of state thing blocking the menu from working in some cases. I'll try to monitor.

**Comment by bmicklea** [comment]
Good, if it remains consistently working please close the issue. Obviously
if it fails again let us know and add any further details.

**Comment by eivantsov** [comment]
Closing the issue as the problem seems to have fixed itself.
