### ISSUE TITLE
Command line git client in workspace not linked to GUI git

### ISSUE THREAD

**Issue by richtera** [codenvy/codenvy#1505]
**Reproduction Steps:**
Use the git command line client instead of the menu.
Problems:
1. The ssh seems to be different
2. global config for user.name and user.email are ignored (even running git config --global doesn't fix this)
3. Git pull and git push somehow causes access problems even though the ssh key is set.
4. git cherry-pick can't be used at all because it's not in the menu :-(

**Codenvy version:**    
5.0.0-M8

**OS and version:**    
CoreOs

**Docker version:**    

**Codenvy cli.log output:**

**Comment by richtera** [comment]
Setting up for branch.autosetuprebase=always doesn't seem to be possible either.

**Comment by richtera** [comment]
@bmicklea FYI: git functionality seems extremely limiting. We usually set up all projects for git rebase so things get rebased during git pull. And we use git cherry-pick quite a lot to cherry pick small changes between dev and master branches.

**Comment by TylerJewell** [comment]
The git GUI is purposefully minimal.  However, the expectation is that command-line git is fully functional. If anything doesn't work on that front, then there is certainly an issue for investigation.  And then over time, selectively we add in GUI elements related to git into the IDE.

**Comment by richtera** [comment]
Ok that makes sense. The problem I found is that the git command line client doesn't use the settings in the preference panel but somehow tries to. Changing setting using git config --global don't seem to stick but it doesn't properly get user.email and user.name. Setting the locally in the repo partially works. But git pull seems to use a different ssh key than what the pull menu uses. It's possible to upload a second ssh-genkey but that seems a bit involved for normal users :)

**Comment by TylerJewell** [comment]
I think @vkuznyetsov will help us by taking a look and thinking about it. He leads a team for Eclipse Che that does all of our git engineering.

**Comment by eivantsov** [comment]
@richtera @TylerJewell git installed in the workspace and JGit that Che uses are two different systems that are not related to one another.

**Comment by richtera** [comment]
I was hoping the system would transport the committer info from the preferences into git config --global user.(email/name) when the machine boots. I feel like it's TRYING to do something there, because no matter how many times I execute git config --global to set those variables they show up as empty when I do git config --global --list or try to do git commit.

Also if you shared the path to the ssh key for JGIT as a .ssh/config the git command line could pick up the same key.

As an add-on it would be nice to be able to add other keys to a "shared" global git config like branch.autosetuprebase=always from the preferences panel.

The reason this stuff seems important to me is that when sharing a workspace it should get the git config from the user's preferences and not from a custom setup within the workspace. Otherwise the sharing user will commit as the original user.

**Comment by TylerJewell** [comment]
+1 - I agree. I would have presumed it worked this way, but I think that all of our testing assumes that a user is either GUI-based or terminal-based.  So I don't think our integration tests have included moving in between the systems.  Thanks @bmicklea - for creating some tracking issues.

**Comment by eivantsov** [comment]
@TylerJewell a workspace may not have git installed at all. What to do in such a case?

**Comment by richtera** [comment]
Writing ~/.gitconfig should be fine if the user doesn't need it. If configured their git info in preference it's most likely that they want it anyways.

Writing ~/.ssh/config is useful for any client software that needs ssh keys and has them configured in the user's preferences.

**Comment by TylerJewell** [comment]
@eivantsov - yes good question, I think @richtera's answer makes sense.

**Comment by richtera** [comment]
The ~/.ssh folder is not being kept alive during restarts of the workspace. I constantly have to re-generate new ssh keys and give them to github. So there is definitely something important here.

**Comment by richtera** [comment]
Also the branches the git repo is on don't even show in the dialog. My current branch is called "dev" and all I see is "master"
![image](https://cloud.githubusercontent.com/assets/708186/23818704/a979690a-05b2-11e7-80b1-b454885f7339.png)

**Comment by eivantsov** [comment]
@richtera 

1. ~/.ssh should be snapshotted when a workspace stops if you configure your Codenvy installation to automatically create snapshots. You can configure it in `codenvy.env`:

```
CODENVY_WORKSPACE_AUTO_SNAPSHOT=true
CODENVY_WORKSPACE_AUTO_RESTORE=true

```

2. As far as I understand, you have imported your project using a native git, i.e. in a terminal.

I have just done the same - imported a project through a command line, checkout out to a branch, and then opened Git > Remotes menu in the IDE. All of my branches are there.

Is there anything specific in the way you have imported your project?

**Comment by richtera** [comment]
Ok I will try the AUTO_SNAPSHOT/AUTO_RESTORE stuff. I did use the normal git import during workspace creation. I just use the command line git client while pulling, pushing and committing. Usually I use branch.autosetuprebase=always and/or branch.MyBRANCH.rebase=true during pull.

**Comment by richtera** [comment]
Added #1924. Unfortunately without this I can't enable snapshots to an unprotected registry.

**Comment by slemeur** [comment]
Will be solved by: https://github.com/eclipse/che/pull/5285

**Comment by vkuznyetsov** [comment]
fixed by https://github.com/eclipse/che/pull/5285
