### ISSUE TITLE
Date header is missing when sending confirmation email

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#1511]
I observed that confirmation email sent from dockerized codenvy lack Date header 
```
Return-Path: <noreply@codenvy-stg.com>
X-Original-To: skryzhny@*****.com
Delivered-To: skryzhny@*****.com
Received: from codenvy-stg.com (ec2-52-91-105-228.compute-1.amazonaws.com [52.91.105.228])
	by mail (Postfix) with ESMTP id 4DB9717F425
	for <skryzhny@*****.com>; Fri,  6 Jan 2017 18:00:08 +0200 (EET)
Received: from ae89c991a583 (ip-172-18-0-11.ec2.internal [172.18.0.11])
	by codenvy-stg.com (Postfix) with ESMTP id B1B58B49
	for <skryzhny@*****.com>; Fri,  6 Jan 2017 16:00:07 +0000 (UTC)
From: noreply@codenvy-stg.com
To: skryzhny@c*****.com
Message-ID: <209379964.1.1483718407700.JavaMail.root@172.30.11.129>
Subject: Verify Your Codenvy Account
MIME-Version: 1.0
Content-Type: multipart/mixed; 
	boundary="----=_Part_0_1006851375.1483718407675"
```
In a typical email setup the Date: header is set by the mail client sending the message.
That possible was corrected by local postfix daemon when we used puppetized codenvy.
But now in dockerized codenvy postfix treat email from codenvy as coming from external host, so by default postfix doesn't insert missing Date header.
This may be the case why email considered SPAM by some email systems.

**Reproduction Steps:**

Try to register user via email from dockerized codenvy tied to local postfix, like nightly.
Go to the email client and show email headers.

**Codenvy version:**    5.0.0

**OS and version:**  Centos 7.3  

**Docker version:** 1.12.5

**Comment by JamesDrummond** [comment]
@bmicklea Do we know the severity of this issue for our existing customers.

**Comment by bmicklea** [comment]
This is a P2, most customer will use ldap or oauth.

**Comment by skryzhny** [comment]
Any progress on this issue?
I didn't checked but chances are high that all mails from codenvy would have such defect.
Fixing that isn't hard anyway.

**Comment by mmorhun** [comment]
Done
