### ISSUE TITLE
Upgrade to swarm 1.2.6 

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#1517]
Fixes https://github.com/eclipse/che/issues/2962

**Comment by riuvshin** [comment]
will do as soon as 1.2.6 will be released. https://github.com/docker/swarm/releases

**Comment by riuvshin** [comment]
swarm finally released 1.2.6 https://github.com/docker/swarm/releases/tag/v1.2.6 so now I'm able to start testing codenvy with new version of swarm

**Comment by riuvshin** [comment]
PRs proposed

**Comment by riuvshin** [comment]
Done
