### ISSUE TITLE
Problem importing OpenShift Git project in Eclipse Che on Codenvy.io

### ISSUE THREAD

**Issue by BvE-HU** [codenvy/codenvy#1520]
Hi, I'm getting an internal server error while importing an OpenShift git repo in Eclipse Che (running on codenvy.io). I created an SSH-key in Eclipse Che (Preferences > SSH > VCS), and uploaded it to my OpenShift account.

Next, I try to import the project, (URL: ssh://&lt;account&gt;@&lt;app-url&gt;.rhcloud.com:/~/git/codenvy.git) but i'm getting:

java.lang.IllegalStateException: org.eclipse.che.ide.websocket.rest.exceptions.ServerException: Internal Server Error occurred, error time: 2017-01-12 13:45:41

The SSH key was created for host &lt;app-url&gt;.rhcloud.com, without http or www. If I do a git clone on the same URL in the terminal, I get a timeout. If a try to create an SSH session to the same host, I also get a timeout.

Strangely, with an SSH connection to Github, this works like a charm in both the import wizard and the Terminal. It looks like a whitelist-issue, but I understand from other issues that rhcloud.com is already whitelisted.

Help would be very much appreciated!

**Reproduction Steps:**
- Create an OpenShift application (in their WebConsole)
- Create an SSH key for host &lt;app-url&gt;.rhcloud.com, and upload it to OpenShift
- Import the project into Eclipse Che (on codenvy.io).

**Codenvy version:** 5.0.0-M8 Revision : 3cacf890eda7d9ba Build Time :2016-12-07 14:37:08

**Comment by TylerJewell** [comment]
@JamesDrummond @eivantsov - you are the SSH experts, so can you take a quick look and advise, please?

**Comment by eivantsov** [comment]
@BvE-HU what happens if you generate a key right in the terminal and git clone there?

**Comment by BvE-HU** [comment]
Hi, thanks for your reply. I tried, but git clone results in a timeout, although I can ping the OpenShift URL from there. A direct SSH command also results in a timeout.

By the way, I am able to do a git clone of a Github repository from the terminal! 

________________________________________
Van: Eugene Ivantsov [notifications@github.com]
Verzonden: vrijdag 13 januari 2017 13:03
Aan: codenvy/codenvy
CC: Bart van Eijkelenburg; Mention
Onderwerp: Re: [codenvy/codenvy] Problem importing OpenShift Git project in Eclipse Che on Codenvy.io (#1520)

@BvE-HU<https://github.com/BvE-HU> what happens if you generate a key right in the terminal and git clone there?

�

**Comment by eivantsov** [comment]
@skryzhny can help I think. rhcloud.com has been whitelisted but maybe it is a different IP now.

**Comment by JamesDrummond** [comment]
@eivantsov Has this worked on codenvy.io before? If so I would like to have this documented as a tutorial to help others. Currently we only have documents for che https://eclipse.org/che/docs/openshift/user-guide/index.html#connect-account .

**Comment by eivantsov** [comment]
@JamesDrummond it is related to blocking all outgoing traffic from codenvy.io. We manually whitelist IPs.

**Comment by BvE-HU** [comment]
@JamesDrummond<https://github.com/JamesDrummond> I know there is an Openshift plugin, but I'm planning to use this in a course, and I want as less overhead as possible. And because I'm able to import a project from GitHub, I thought it would also be possible to import a Git-repo directly from OpenShift. This is also confirmed here: https://github.com/codenvy/codenvy/issues/491, I think.

________________________________
Van: Eugene Ivantsov <notifications@github.com>
Verzonden: dinsdag 24 januari 2017 13:47
Aan: codenvy/codenvy
CC: Bart van Eijkelenburg; Mention
Onderwerp: Re: [codenvy/codenvy] Problem importing OpenShift Git project in Eclipse Che on Codenvy.io (#1520)


@JamesDrummond<https://github.com/JamesDrummond> it is related to blocking all outgoing traffic from codenvy.io. We manually whitelist IPs.

-

**Comment by eivantsov** [comment]
I confirm the issue.

**Comment by BvE-HU** [comment]
The IP (currently) is: 52.3.216.108

**Comment by eivantsov** [comment]
@BvE-HU can you give it another go?

**Comment by BvE-HU** [comment]
Hi, I can git clone now. Thanks!

But is this a solution for future OpenShift-users of, for example, users of another platform?

**Comment by eivantsov** [comment]
All IPs have to be whitelisted by codenvy.io amin team

**Comment by BvE-HU** [comment]
Okay, clear. Thanks again.
