### ISSUE TITLE
For the last few days I noticed the whole system restarting after a while

### ISSUE THREAD

**Issue by richtera** [codenvy/codenvy#1521]
**Reproduction Steps:**
Wait a day or so after using. Then trying to connect initially gives an error. Then trying again takes a while. Looking at the logs I see the WebApps being redeployed (i.e. it looks like the whole codenvy system is starting up fresh)

**Codenvy version:**    
5.0.0-M8

**OS and version:**    
CoreOS stable (1235.6.0)

**Docker version:**    
Docker version 1.12.3, build 34a2ead

**Codenvy cli.log output:**  
No new content associated with these events.

@bmicklea

**Comment by TylerJewell** [comment]
@eivantsov - another coreos item.  Could this be related to the file system configuration issues we keep seeing from coreos?

**Comment by eivantsov** [comment]
@richtera what do you mean by `the whole system restarting?` Can you provide Tomcat logs at `/instance/logs/codenvy`?

**Comment by eivantsov** [comment]
Closed due to inactivity. Feel free to reopen is the issue persists.
