### ISSUE TITLE
My SQL stack does not start

### ISSUE THREAD

**Issue by artaleks9** [codenvy/codenvy#1524]
When I try to create workspace from java-mysql stack, the terminal agent does not start.

**Reproduction Steps:**
* Go to the dashboard
* Create new workspace from java-mysql stack

**Expected behavior:**
* the workspace should be started.

**Observed behavior:**
* the workspace agent does not start.
 
**Codenvy version:**  5.1.0-SNAPSHOT 
**OS and version:**  Ubuntu 14.04  

**Additional information:**
* Problem can be reliably reproduced: Yes 
* See the attachment:
![mysql_stack](https://cloud.githubusercontent.com/assets/5408906/21925818/cce37fc2-d987-11e6-906e-4d9bd2eb79b7.png)
![mysql_start](https://cloud.githubusercontent.com/assets/5408906/21925825/d2ae46ee-d987-11e6-9707-8e98e928ef74.png)

**Comment by eivantsov** [comment]
@artaleks9 please give it another try. Looks like some debian repos were unavailable when you tried it.

**Comment by mmorhun** [comment]
Fixed
