### ISSUE TITLE
Make  possible to manage of snapshotting workspaces

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#1525]
I think this feature should be customized. The auto snapshotting should be disabled in the global scope. But an user should have possibility do a snapshot at its discretion. (through UI).

**Comment by eivantsov** [comment]
By default, auto snapshotting is off. So, as a user I should be still able to snapshot my workspace, however all UI controls have been removed.

**Comment by eivantsov** [comment]
Closing the issue. It's on prem admin who can decide and configure Codenvy accordingly
