### ISSUE TITLE
How to know what web address & port you are running from in a Node.JS stack?

### ISSUE THREAD

**Issue by faddah** [codenvy/codenvy#1530]
Hello,

I don't know if this correct place to ask this — this seems more like a forum for bugs found than general support issues, but your web site for support said to write here, so here I am writing for support. My main question is: I have set up a docker stack using your Node.JS stack with simple web app. I have pulled into a directory in that docker stack a Node.JS learning module from a Udemy training module, and I run the package "nodemon" from the terminal to launch the SPA web app using Express.JS. My question — where do I find the web address and port my Node.JS/Express.JS web app is running? It usually runs on port 3000, but I have no idea what web address Codenvy.io should server it on, and frankly, this should be a bit more obvious in your documentation and menus in Codenvy.io.  I searched here — http://codenvy.readme.io/docs/run, and in the menus under "Run," such as "Edit Targets" or "Edit Commands," but can find nothing in any of the dialogues anywhere to tell me what web address and port I should put in my browser to view the served templates of my SPA web app. Where can I find this, please?

**Reproduction Steps:**
• My set-up – MacPro with 16 GB RAM, MacOS Sierra 10.12.2 with all the latest updates, and I log into the Codenvy.io site using the Google Chrome browser for MacOS, v.55.0.2883.95 (64-bit). I log-in to Codenvy.io using my GitHub OAuth (my_biz@me.com). I have loaded a Node.JS stack from your pre-set stacks, and have updated it to Node.JS v6.9.4 (as of this date, latest LTS version) and NPM v4.1.1 with Express.JS v4.14.0. 
• The Codenvy stack I created for this Node.JS stack is called "udemy_nodeauth." 
• I imported using your menus "Workspace > Import Project... > GitHub" to import this project:  https://github.com/faddah/nodeauth_user_login_system. I put this project in the Docker Ubuntu VM in `~/projects/nodeauth_user_login_system`.
• I installed all my dependencies from my `package.json` file included with that, using `$ npm install` in the directory.
• I also set up some global npm packages in this workspace, such as "(nodemon)[https://www.npmjs.com/package/nodemon]" to run my Node.JS/Express.JS web app and automatically re-start the Express server if any changes are made to the source. 
• With all dependencies installed i attempt to run and serve my Node.JS/Express.JS web app from the terminal within that project directory, using `$ nodemon` or `$ npm start`. 

Result -- it starts just fine, it would seem, but I simply cannot find where to go to find what web address url & port I need to go view my Node.JS/Express.JS web app.

**Codenvy version:**     
I have absolutely no idea where to go find and/or run this command to give you this information. I tried running it from your terminal command line in the web IDE, but I keep getting back a bash `command not found.` Also, in the web IDE, You need to be far more explicit, step-by-step, to be able to properly know where and how to retrieve this information for you? Also, in the web IDE in the dev-machine tab, there is no way to input anything there to return the info you want. And wouldn't this all be easier if you just added to your Web interface Dashboard a simple menu right up front that says *exactly* what version of Docker & Codenvy are running on my Workspace stacks right now? Making it easy, not a treasure hunt chore, to find tools that speed this support process along is better than giving us 1/2 measure instructions that lead us nowhere.

**OS and version:**    
MacPro with 16 GB RAM, MacOS Sierra 10.12.2 with all the latest updates, and I log into the Codenvy.io site using the Google Chrome browser for MacOS, v.55.0.2883.95 (64-bit)

**Docker version:**    
Same as above for asking me the Codenvy version - see the paragraph above on that.

**Codenvy cli.log output:**  
Again, same as above for asking me the Codenvy version & Docker version - see the paragraph above on that.

*  *  *  *  *  *  *  *  *  *  *  *  *  *  *  

All that said, I hope you can point me to documentation as to how to run this web app of mine.

best,

—  faddah

**Comment by bmicklea** [comment]
Hi Faddah, we're in the midst of revamping our docs and you're correct that it's a little too hard to find this information today.

All the ports for services registered in your stack are found today in the "Servers" tab in the operations perspective. To get to the operations perspective you have to click the button in the top-right:

<img width="142" alt="screen shot 2017-01-16 at 9 16 11 am" src="https://cloud.githubusercontent.com/assets/7644938/21986171/63b6b32e-dbcc-11e6-9b9c-aa4b430534ec.png">

There's some documentation here on preview URLs: https://eclipse.org/che/docs/ide/run/index.html#preview-url

**Comment by TylerJewell** [comment]
@faddah - there are two separate concepts that happen within our workspaces:
1. When you start a server that binds to a port inside of a workspace, that server gets bound to the port internally and then mapped to an ephemeral port externally.  That is (today) viewable in the servers tab in the IDE. But in the 5.0.0 release to codenvy that is about to be pusehd, there is a really nice "Servers" tab of your workspace that makes it really easy to see all this information.

2. Second, you can generate preview URLs for your workspace from commands.  So a command is what you run from the toolbar.  A preview URL can be generated dynamically with the right port, and we have some macros that you embed in the preview URL which will detect and derive that port number for you.  

Brad gave both links above.

**Comment by eivantsov** [comment]
Closed due to inactivity.

**Comment by 4d4tt4** [comment]
Hi can you please provide tutorial to set up nodejs project and to preview the application on web browser using url and port provided by codenvy
