### ISSUE TITLE
How to save a snapshot of your current Docker set-up (Node.JS stack)

### ISSUE THREAD

**Issue by faddah** [codenvy/codenvy#1531]
**Reproduction Steps:**

Hello,

I have noticed that every time I log back in to my Node.JS stack in Codenvy.io (user:  my_biz@me.com, using GitHub OAuth; Workspace - udemy_nodeauth), my updated NPM 4.1.1 is back to 3.10.x and my `node_modules` for my local project installed using `package.json` and `$ npm install` are gone at each re-boot of the Docker VM. Is there a way to take a snapshot of your current Workspace/project and have that be the snapshot it boots from on each restart of the Docker VM. I searched your documentation for this, including your section on [CLI](http://codenvy.readme.io/docs/cli), which says I should do `$ codenvy backup` from the terminal, but if i do that from within the Terminal within the Codenvy interface, it returns a bash `command not found.` for codenvy.

• My set-up – MacPro with 16 GB RAM, MacOS Sierra 10.12.2 with all the latest updates, and I log into the Codenvy.io site using the Google Chrome browser for MacOS, v.55.0.2883.95 (64-bit). I log-in to Codenvy.io using my GitHub OAuth (my_biz@me.com). I have loaded a Node.JS stack from your pre-set stacks, and have updated it to Node.JS v6.9.4 (as of this date, latest LTS version) and NPM v4.1.1.
• The Codenvy stack I created for this Node.JS stack is called "udemy_nodeauth."
• I imported using your menus "Workspace > Import Project... > GitHub" to import this project: https://github.com/faddah/nodeauth_user_login_system. I put this project in the Docker Ubuntu VM in ~/projects/nodeauth_user_login_system.
• I installed all my dependencies from my package.json file included with that, using $ npm install in the directory.
• I also set up some global npm packages in this workspace, such as "(nodemon)[https://www.npmjs.com/package/nodemon]" to run my Node.JS/Express.JS web app and automatically re-start the Express server if any changes are made to the source.

**Codenvy version:**    
I have absolutely no idea where to go find and/or run this command to give you this information. I tried running it from your terminal command line in the web IDE, but I keep getting back a bash command not found. Also, in the web IDE, You need to be far more explicit, step-by-step, to be able to properly know where and how to retrieve this information for you? Also, in the web IDE in the dev-machine tab, there is no way to input anything there to return the info you want. And wouldn't this all be easier if you just added to your Web interface Dashboard a simple menu right up front that says exactly what version of Docker & Codenvy are running on my Workspace stacks right now? Making it easy, not a treasure hunt chore, to find tools that speed this support process along is better than giving us 1/2 measure instructions that lead us nowhere.

**OS and version:**    
MacPro with 16 GB RAM, MacOS Sierra 10.12.2 with all the latest updates, and I log into the Codenvy.io site using the Google Chrome browser for MacOS, v.55.0.2883.95 (64-bit). I log-in to Codenvy.io using my GitHub OAuth (my_biz@me.com). I have loaded a Node.JS stack from your pre-set stacks, and have updated it to Node.JS v6.9.4 (as of this date, latest LTS version) and NPM v4.1.1.

**Docker version:**    
See paragraph above for "Codenvy versioin," same issue as there.

**Codenvy cli.log output:**  
See paragraphs above for "Codenvy versioin" & "Dockerversion," same issue as there.

*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   

I hope you can get back to me with an answer as to how to do this. It's not very clear in either your documentation or UI menus.

best,

—  faddah
      portland, oregon, u.s.a.

**Comment by bmicklea** [comment]
Hi Faddah,

Here again you'll have to go to the machine's perspective:
<img width="142" alt="screen shot 2017-01-16 at 9 16 11 am" src="https://cloud.githubusercontent.com/assets/7644938/21986217/945e43f2-dbcc-11e6-986c-965d73c44837.png">

Then in the "Machine" menu you'll see an option for "Create Snapshot". If a snapshot has been saved for a workspace then when it's next started you'll be asked if you want to load from snapshot or recreate.

**Comment by eivantsov** [comment]
@faddah Do you see "Snapshotting workspace message" when you stop the workspace at Workspace > Stop?

Now, some clarification required:

1. Do you expect node_modules to be there with the project when you restart your workspace?

The thing is that when a workspace is started we rsync your project, and rsync script respects .gitignore. node_modules is most certainly in .gitignore.

2. You said you installed some modules globally. Snapshotting the workspace and restarting it should keep them.

**Comment by eivantsov** [comment]
Closed due to inactivity
