### ISSUE TITLE
Authentication for Preview

### ISSUE THREAD

**Issue by dinvlad** [codenvy/codenvy#1535]
Hi Team,

I'd like to better understand what needs to be done to enable authentication for preview sessions. Currently, any time I preview my app, it not only uses an http (not s) URL, but it also doesn't require any kind of authentication. So anyone on the web can preview my app. I'd like it to be more closed without configuring any VPN or proxy.

Thanks

**Comment by TylerJewell** [comment]
Hi @dinvlad - on codenvy.io, we do no have any mechanism for placing an authentication against the preview URL.

However, you can now run Codenvy on your own `docker run codenvy/cli start` and place the installation behind a firewall that is proxied.

Even within the on-premises version we do not yet have a mechanism where you can place an explicit authentication against a single proxy URL.  We have discussed this and it would be some significant additional engineering that we want to consider working on this year.  This requires us to extend our nginx and HAProxy mechanism with tokenization for preview URLs, and also for us to intercept all preview URLs for tokenization.

In the mean time, you could consider using the factory capability, which is authenticated.  A factory may be a bit of a blunt instrument, but you can generate a password protected factory which creates a workspace clone.  Any user you give it to would get their own custom workspace that they would then have to open and press the "run button", which would then launch the preview URL for them to use.  You could on your on-prem configuration have these workspaces timeout rather quickly, so when the end user was done with that worksapce, it was effecitvely turn off and no longer reusable (including the preview).

**Comment by dinvlad** [comment]
Thank you for the details! I'll keep these in mind. I also wasn't aware of the factory mechanism, which seems great on itself. Looking forward to any future native proxying (unfortunately, this is currently the main show-stopper for us).

**Comment by TylerJewell** [comment]
@dinvlad - would you mind emailing me tyler@codenvy.com so that I can ask some probing questions on the use cases as we think about a possible specification for it.
