### ISSUE TITLE
CLI for creating organizations and users

### ISSUE THREAD

**Issue by levjason** [codenvy/codenvy#1537]
Will the Codenvy CLI support creating users and organizations?     

**Reproduction Steps:**

**Codenvy version:**    5.0.0-M8

**OS and version:**      Ubuntu 16.04

**Docker version:** 1.12.3

**Codenvy cli.log output:**

**Comment by TylerJewell** [comment]
The REST API certainly supports it. The current (supported) CLI has utilities for initiating broad-actions and working with REST, but we haven't yet included commands specific to working with users on the command-line.

@sleshchenko - are there additional command line utilities that have been built specific to working with users and organizations?  Perhaps utilities that engineering has been developing or our operations team uses, which we have not yet published?

**Comment by levjason** [comment]
The REST API for creating an organization requires an id, name and parent. What do I use for the parent when I create the first organization? Also, are there any restrictions on the id value?

**Comment by sleshchenko** [comment]
@TylerJewell As far as I know we don't have any additional command line utilities for organizations and users.

@levjason you can miss parent field then will be created root organization. 
And id field is ignored during organization creation. Id will be generated by server. So you also can miss it.

**Comment by levjason** [comment]
@sleshchenko Thanks, that works.
