### ISSUE TITLE
Unable to run Docker Codenvy, "please rerun CLI"

### ISSUE THREAD

**Issue by gc-alexlong** [codenvy/codenvy#1538]
While trying to troubleshoot another issue for Codenvy, a warning eventually appeared:
`WARN: Your 'nightly' image is over 24 hours old - checking for a newer image...`

And then after Docker pulled the image, another warning appeared:
`WARN: Pulled new 'nightly' image - please rerun CLI`

**Reproduction Steps:**
1. Completely deleted `data` folder created by codenvy/cli to start from scratch.
2. Ran codenvy/cli again: `docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/dockerprojects/codenvy/data:/data codenvy/cli:nightly start`
3. codenvy/cli image is pulled, warning to rerun CLI appeared

**Codenvy version:**    5.1.0-SNAPSHOT

**OS and version:**    10.11.6 (El Capitan)

**Docker version:** 1.12.6  

**Codenvy cli.log output:**  

Fri Jan 13 22:44:56 UTC 2017
INFO: (codenvy cli): Checking network... (hint: '--fast' skips version, network, and nightly checks)
/usr/bin/curl  "-I -k dockerhub.com -s -o /dev/null --write-out %{http_code}"
INFO: (codenvy cli): Loading cli...
DEBUG: docker_run
DEBUG: is_boot2docker
WARN: Your 'nightly' image is over 24 hours old - checking for a newer image...
DEBUG: update_image
INFO: (codenvy download): Pulling image codenvy/cli:nightly

docker pull codenvy/cli:nightly >> "/data/cli.log" 2>&1

WARN: Pulled new 'nightly' image - please rerun CLI
Fri Jan 13 22:45:21 UTC 2017
INFO: (codenvy cli): Checking network... (hint: '--fast' skips version, network, and nightly checks)
/usr/bin/curl  "-I -k dockerhub.com -s -o /dev/null --write-out %{http_code}"
INFO: (codenvy cli): Loading cli...
DEBUG: docker_run
DEBUG: is_boot2docker
WARN: Your 'nightly' image is over 24 hours old - checking for a newer image...
DEBUG: update_image
INFO: (codenvy download): Pulling image codenvy/cli:nightly

docker pull codenvy/cli:nightly >> "/data/cli.log" 2>&1

WARN: Pulled new 'nightly' image - please rerun CLI
Fri Jan 13 22:45:33 UTC 2017
INFO: (codenvy cli): Checking network... (hint: '--fast' skips version, network, and nightly checks)
/usr/bin/curl  "-I -k dockerhub.com -s -o /dev/null --write-out %{http_code}"
INFO: (codenvy cli): Loading cli...
DEBUG: docker_run
DEBUG: is_boot2docker
WARN: Your 'nightly' image is over 24 hours old - checking for a newer image...
DEBUG: update_image
INFO: (codenvy download): Pulling image codenvy/cli:nightly

docker pull codenvy/cli:nightly >> "/data/cli.log" 2>&1

WARN: Pulled new 'nightly' image - please rerun CLI
Fri Jan 13 22:47:19 UTC 2017
INFO: (codenvy cli): Checking network... (hint: '--fast' skips version, network, and nightly checks)
/usr/bin/curl  "-I -k dockerhub.com -s -o /dev/null --write-out %{http_code}"
INFO: (codenvy cli): Loading cli...
DEBUG: docker_run
DEBUG: is_boot2docker
WARN: Your 'nightly' image is over 24 hours old - checking for a newer image...
DEBUG: update_image
INFO: (codenvy download): Pulling image codenvy/cli:nightly

docker pull codenvy/cli:nightly >> "/data/cli.log" 2>&1

WARN: Pulled new 'nightly' image - please rerun CLI
Fri Jan 13 22:47:44 UTC 2017
INFO: (codenvy cli): Checking network... (hint: '--fast' skips version, network, and nightly checks)
/usr/bin/curl  "-I -k dockerhub.com -s -o /dev/null --write-out %{http_code}"
INFO: (codenvy cli): Loading cli...
DEBUG: docker_run
DEBUG: is_boot2docker
WARN: Your 'nightly' image is over 24 hours old - checking for a newer image...
DEBUG: update_image
INFO: (codenvy download): Pulling image codenvy/cli:nightly

docker pull codenvy/cli:nightly >> "/data/cli.log" 2>&1

WARN: Pulled new 'nightly' image - please rerun CLI
Mon Jan 16 16:46:28 UTC 2017
INFO: (codenvy cli): Checking network... (hint: '--fast' skips version, network, and nightly checks)
/usr/bin/curl  "-I -k dockerhub.com -s -o /dev/null --write-out %{http_code}"
INFO: (codenvy cli): Loading cli...
DEBUG: docker_run
DEBUG: is_boot2docker
WARN: Your 'nightly' image is over 24 hours old - checking for a newer image...
DEBUG: update_image
INFO: (codenvy download): Pulling image codenvy/cli:nightly

docker pull codenvy/cli:nightly >> "/data/cli.log" 2>&1

WARN: Pulled new 'nightly' image - please rerun CLI

**Comment by TylerJewell** [comment]
Run `--fast` to skip this check.

There was an improvement made over the weekend where we now compare the image digest of the nightly that you have on disk to the one that is pulled from Docker Hub.  If they are identical, then the CLI continues.  If they are not identical, then this message stops.

I am curious as to why your system is thinking that the newly pulled version and the existing one are different digests.  I am suspecting that it's because you are on boot2docker.  I'd need to access your system to diagnose it specifically.

But it's not a big issue - just append `--fast` to skip this check.

**Comment by TylerJewell** [comment]
@gc-alexlong - I just tested the new CLI improvements on Mac, Windows 10, and Linux - they were all ok.  I am wondering if being on VirtualBox with Boot2Docker is causing the odd behavior and why the digest detection is not working.

Is there a chance that you have a lot of images on your Docker system and perhaps they are now interfering with them? Can you "docker rmi -f $(docker images -q)" on your system to wipe out all existing Docker images and then rerun?  This will make sure that you are starting afresh.

**Comment by gc-alexlong** [comment]
@TylerJewell Here is output from `docker info`, hopefully it's helpful:

Containers: 10
 Running: 2
 Paused: 0
 Stopped: 8
Images: 15
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 83
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay null bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.41-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 4.832 GiB
Name: moby
ID: NXIY:FO4J:RIQN:NVWN:K3WO:PKRF:EAWW:Z5KX:GGS7:XMUF:HFSY:J3ND
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 33
 Goroutines: 41
 System Time: 2017-01-16T22:12:30.547033832Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Insecure Registries:
 localhost:5000
 192.168.65.2:5000
 127.0.0.0/8


I used the command you just mentioned, removing the images, and that solved the warning messages. Thanks!
