### ISSUE TITLE
workspaces does not start from snapshots on codenvy.io

### ISSUE THREAD

**Issue by riuvshin** [codenvy/codenvy#1544]
today we've updated codenvy.io to dockerized codenvy 5.0.1.
after update we've figured out bug which is seems bug in docker, the issue prevent start workspaces from snapshots created on previous version.
We did a workaround on codenvy.io to allow workspace start normally.
But we must fix potential issues which will appear after refactoring in 5.1.0.

**Comment by garagatyi** [comment]
Actually workaround fixed only part of failures. We don't know how to workaround another part without code changes

**Comment by benoitf** [comment]
is there a link to the docker bug ?

**Comment by garagatyi** [comment]
No, I'll create it tomorrow
