### ISSUE TITLE
Documentation for Permission API on Swagger

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#1546]
We recently introduced the Permission API and have documented some of them on our Swagger docs.

We need to double check that:
- we have swagger docs for all new API added
- we have updated docs of all existing API impacted (workspaces, accounts... )
- we are listing applicable permissions for each API and providing proper samples

**Comment by riuvshin** [comment]
@slemeur @TylerJewell do we need 5.2.0 milestone here? 5.2.0 release is in few days.
