### ISSUE TITLE
Documentation for Organization API on Swagger

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#1547]
We recently introduced the Organization API and have documented some of them on our Swagger docs.

We need to double check that:
- we have swagger docs for all new API added
- we have updated docs of all existing API impacted (accounts... )
- we are properly documenting the super privilege mode

**Comment by riuvshin** [comment]
@slemeur @TylerJewell do we need 5.2.0 milestone here? 5.2.0 release is in few days.

**Comment by TylerJewell** [comment]
The milestone should be applied by a team leader when there is a valid pr that they are confident will be merged. We don't have these items yet.

**Comment by riuvshin** [comment]
@TylerJewell exactly, that is why I've asked. those things are not ready but milestone is set.
@slemeur please drop the milestone

**Comment by slemeur** [comment]
Fixed
