### ISSUE TITLE
Docker command for running codenvy with your assembly

### ISSUE THREAD

**Issue by levjason** [codenvy/codenvy#1551]
The documentation for the command to run codenvy with your assembly has this:
docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock \
           -v <local-path>:/data \
	   -v $(pwd):/repo codenvy/cli:5.0.0 start

should this be:
docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock \
           -v <local-path>:/codenvy \
	   -v $(pwd):/repo codenvy/cli:5.0.0 start

I couldn't get codenvy to start until I changed /data to /codenvy.  Like this:
docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -v /home/xxxxxx/codenvy_docker:/codenvy -v /home/xxxxxx/git/codenvy:/repo codenvy/cli:5.0.0-M8 start

  5.0.0-M8

ubuntu 16.04  

  Docker version 1.12.3, build 6b644ec 

**Codenvy cli.log output:**  
INFO: (codenvy cli): Loading cli...
INFO: ---------------------------------------
INFO: ------------   CLI INFO   -------------
INFO: ---------------------------------------
INFO:
INFO: -----------  CODENVY INFO  ------------
INFO: CODENVY_VERSION           = 5.0.0-M8
INFO: CODENVY_INSTANCE              = /home/xxxxxx/codenvy_docker/instance
INFO: CODENVY_CONFIG                = /home/xxxxxx/codenvy_docker
INFO: CODENVY_HOST              = 172.17.0.1
INFO: CODENVY_REGISTRY          = /version
INFO: CODENVY_DEVELOPMENT_MODE  = on
INFO: CODENVY_DEVELOPMENT_REPO  = /home/xxxxxx/git/codenvy
INFO: CODENVY_BACKUP            = /home/xxxxxx/codenvy_docker/backup
INFO:
INFO: -----------  PLATFORM INFO  -----------
INFO: DOCKER_INSTALL_TYPE       = native
INFO: IS_NATIVE                 = YES
INFO: IS_WINDOWS                = NO
INFO: IS_DOCKER_FOR_WINDOWS     = NO
INFO: HAS_DOCKER_FOR_WINDOWS_IP = NO
INFO: IS_DOCKER_FOR_MAC         = NO
INFO: IS_BOOT2DOCKER            = NO
INFO:

**Comment by TylerJewell** [comment]
Hi @levjason - For M8 and earlier the mount was :/codenvy.  But starting in M9 we changed this to be a :/repo mount.  

We have had some problems with legacy images when we change the interface.  So you may want to wipe your older images and then start with 5.0.1 or the newly released 5.1.0 (not sure if it was pushed onto dockerhub yet).

**Comment by levjason** [comment]
I pulled the 5.1.0 version and the command works  as documented. Thanks.
