### ISSUE TITLE
Duplicate stacks broken on codenvy.io

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#1556]
You can't duplicate stacks on codenvy.io - you recieve a notification that just says "Failure". I would label this a blocker but you can create stacks from scratch though so setting as a P1.

**Reproduction Steps:**
- Go to the Stacks view in the user dashboard.
- Hit the duplicate stacks icon in the stack list.

**Codenvy version:**
5.1.0

**OS and version:**    
codenvy.io

**Docker version:**    
n/a

**Codenvy cli.log output:**  
n/a

**Comment by olexii4** [comment]
Cannot reproduce on https://nightly.codenvy-stg.com (5.3.0-SNAPSHOT)
