### ISSUE TITLE
Testing stack does not work provide the workspace

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#1560]
Testing a stack is not working on Codenvy.

See the following animated gif.
![codenvy-test-stacks-v3](https://cloud.githubusercontent.com/assets/1636769/22114908/5329ae48-de6b-11e6-9ebc-994c7a737bed.gif)

Once the workspace booted - it gives the small loader with codenvy logo and it's not possible to interact with the workspace.

**Reproduction Steps:**

**Codenvy version:**   5.1.0 (codenvy.io)

**Comment by slemeur** [comment]
@olexii4 could you pleas try to reproduce the issue on nightly or codenvy.io

**Comment by olexii4** [comment]
should be fixed in https://github.com/eclipse/che/pull/3694
