### ISSUE TITLE
CLI: action command does not work if codenvy not started locally

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#1562]
Codenvy CLI: action command does not work if codenvy not started locally

As a user, I just want to do a local sync of my cloud workspaces from `codenvy.io`.
Following the documentation, the first step is to list all workspaces I have on codenvy.io.

The command is then the following:
`docker run -it -v /var/run/docker.sock:/var/run/docker.sock -v /Users/stevanlemeur/dev/codenvy:/data codenvy/cli action list-workspaces --url https://codenvy.io/ --user slemeur@codenvy.com --password ******`

But I receive the following output:
`INFO: (codenvy action): The system is not running.`
This is because, I don't have started codenvy locally. 

User should not need a running codenvy, to be able to connect to remote workspaces (on codenvy.io or elsewhere).

**Codenvy version:**    5.1.0

**Comment by benoitf** [comment]
Fixed by https://github.com/eclipse/che/pull/3825
