### ISSUE TITLE
Did my services tab disappear on my workspace?

### ISSUE THREAD

**Issue by shai200** [codenvy/codenvy#1563]
I am trying to reach for the preview URL because I want to deploy my app to tomcat and test it.

There used to be a small icon on the top right corner but now it's gone. I'm quite puzzled, any help would be appreciated!
<img width="964" alt="screenshot 2017-01-19 19 36 09" src="https://cloud.githubusercontent.com/assets/25229562/22118416/573dc342-de80-11e6-8b1d-3be38f378f45.png">

**Comment by slemeur** [comment]
Hi @shai200 the servers are now available under the dashboard.

Go into workspaces's details and select the `runtime` tab, open the machine's details to get the list of servers.

![screen shot 2017-01-19 at 19 43 44](https://cloud.githubusercontent.com/assets/1636769/22120368/bc12a7ac-de7f-11e6-8f2c-753180572db9.png)

Note: the workspace must be running to see the list of servers provided by processes running in the machine.

![codenvy-servers](https://cloud.githubusercontent.com/assets/1636769/22120408/defdbc66-de7f-11e6-8cf9-95ad30be1517.gif)

See the following PR if you are interested:
https://github.com/eclipse/che/pull/3636

We have not properly documented this as week, so we will update the docs with the following issue: https://github.com/codenvy/che-docs/issues/77
