### ISSUE TITLE
CLI: sync command does not work

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#1564]
Anytime trying the sync command, it gives the following output:
`ERROR: You passed an unknown command.`

I used the following command:
`docker run -it -v /var/run/docker.sock:/var/run/docker.sock -v /Users/stevanlemeur/dev/codenvy:/data -v /Users/stevanlemeur/Desktop/local-sync:/sync codenvy/cli sync wksp-vh1c --url https://codenvy.io/ --user slemeur@codenvy.com --password ******`

By running the same command, but using eclispe/che CLI, it worked properly:
`docker run -it -v /var/run/docker.sock:/var/run/docker.sock -v /Users/stevanlemeur/dev/codenvy:/data -v /Users/stevanlemeur/Desktop/local-sync:/sync eclipse/che sync wksp-vh1c --url https://codenvy.io/ --user slemeur@codenvy.com --password codenvy555
`

I think it's related to this, where we have not updated `mount`by `sync` here: 
https://github.com/codenvy/codenvy/blob/master/dockerfiles/cli/scripts/cli.sh#L25

**Codenvy version:** 5.1.0

**Comment by benoitf** [comment]
Fixed by https://github.com/codenvy/codenvy/pull/1569
