### ISSUE TITLE
Create SystemService

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#1568]
We want to provide some REST API for CLI to make some activity before system shutdown.

 - ```POST /system/stop```
 Will iterate over all running workspaces and suspend them, also it will prevent new workspace starting.
 - ```GET  /system/status```
 Will return json with system ```state:running|preparetoshutdown|readytoshutdown ```

Related to https://github.com/codenvy/codenvy/issues/1554

**Comment by TylerJewell** [comment]
I believe this is needed for eclipse Che as well.

**Comment by skabashnyuk** [comment]
Yes it can be a part of che too.

**Comment by benoitf** [comment]
Can we have an issue in che as well ? (so we can implement it in cli)

**Comment by benoitf** [comment]
> state:running|preparetoshutdown|readytoshutdown
do we have another states
like: is it possible that the state is in an error ? for example some resources are not deployed correctly (one of the image, one of .war file, etc)
and that state is something like "booting" while system is not yet fully running ?

**Comment by skabashnyuk** [comment]
error - we will think about that.
booting - unlikely, no tomcat - no service ))

**Comment by benoitf** [comment]
@skabashnyuk I was referring to one of the resource deployed by Tomcat, not tomcat itself.  It could be other examples : if database is failing I suppose the system is in an error state no ? or if swarm is not answering.

**Comment by skabashnyuk** [comment]
No. In this case tomcat and all components inside behaves unpredictable and we can't guarantee anything.
