### ISSUE TITLE
Unable to remove the make a wish widget

### ISSUE THREAD

**Issue by levjason** [codenvy/codenvy#1574]
I am trying to remove the make a wish widget using the instructions in the white label guide. I have edited the html and built a custom  assembly. I mounted the repo in the docker ... start command but the widget remains.

**Reproduction Steps:**
1.  remove the che-support-email attribute in the che-footer element in the index.html:
    dashboard/src/index.html
 che-footer id="codenvyfooter"
              che-support-help-path="{{branding.helpPath}}"
              che-support-help-title="{{branding.helpTitle}}"
              che-logo="{{branding.logoURL}}"
              che-version="{{productVersion}}"
              che-product-name="Codenvy" ng-show="waitingLoaded && !showIDE"></che-footer
 

2.  build. mvn clean install

3.   Run Codenvy With Your Assembly
 sudo docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/xxxxxx/codenvy_docker:/data -v /home/xxxxxx/git/codenvy:/repo -e CODENVY_HOST=99.999.99.99 codenvy/cli:5.1.0 start

Right after the start command: 
WARNING: No swap limit support
INFO: (codenvy cli): :/repo mounted - using binaries from your local repository
INFO: (codenvy cli): Checking network... (hint: '--fast' skips version, network, and nightly checks)
INFO: (codenvy cli): Loading cli...
INFO: (codenvy cli): Checking registry for version '5.1.0' images
INFO: (codenvy config): Generating codenvy configuration...
INFO: (codenvy config): Customizing docker-compose for running in a container
INFO: (codenvy config): Copying local binaries to /home/usajlev/codenvy_docker/instance/dev...
INFO: (codenvy start): Preflight checks

**Codenvy version:**    5.1.0

**OS and version:**    Ubuntu 16.04

cli.log:

**Docker version:**        1.12.3

Fri Jan 20 18:10:13 UTC 2017
INFO: (codenvy cli): Checking network... (hint: '--fast' skips version, network, and nightly checks)
/usr/bin/curl  "-I -k dockerhub.com -s -o /dev/null --write-out %{http_code}"
INFO: (codenvy cli): Loading cli...
DEBUG: docker_run
DEBUG: is_boot2docker
DEBUG: is_initialized
DEBUG: is_initialized
DEBUG: is_initialized
DEBUG: cli_parse
DEBUG: cmd_start
DEBUG: is_docker_for_mac
DEBUG: is_initialized
INFO: (codenvy cli): Checking registry for version '5.1.0' images
eval IMAGE_HAPROXY=haproxy:1.5.18-alpine
eval IMAGE_NGINX=nginx:1.10-alpine
eval IMAGE_SWARM=swarm:1.2.5
eval IMAGE_REGISTRY=registry:2.5.0
eval IMAGE_POSTGRES=postgres:9.5.4
eval IMAGE_COMPOSE=docker/compose:1.8.1
eval IMAGE_ZOOKEEPER=zookeeper:3.4.9
eval IMAGE_SOCAT=codenvy/socat:5.1.0
eval IMAGE_INIT=codenvy/init:5.1.0
eval IMAGE_AGENTS=codenvy/agents:5.1.0
eval IMAGE_CODENVY=codenvy/codenvy:5.1.0
eval IMAGE_RSYSLOG=codenvy/rsyslog:5.1.0
DEBUG: docker_run
INFO: (codenvy config):  Generating codenvy configuration...
DEBUG: generate_configuration_with_puppet
DEBUG: is_docker_for_windows
docker_run                   --env-file="/data/codenvy.env"                   --env-file=/version/5.1.0/images                   -v "/home/xxxxxx/codenvy_docker/instance":/opt/codenvy:rw                    -e "PATH_TO_CHE_ASSEMBLY=/home/xxxxxx/codenvy_docker/instance/dev/codenvy-tomcat" -e "PATH_TO_WS_AGENT_ASSEMBLY=/home/xxxxxx/codenvy_docker/instance/dev/ws-agent.tar.gz" -e "PATH_TO_TERMINAL_AGENT_ASSEMBLY=/home/xxxxxx/codenvy_docker/instance/dev/websocket-terminal-linux_amd64.tar.gz" -v "/home/xxxxxx/git/codenvy/dockerfiles/init/manifests":/etc/puppet/manifests:ro -v "/home/xxxxxx/git/codenvy/dockerfiles/init/modules":/etc/puppet/modules:ro                   -e "POSTGRES_ENV_FILE=/home/xxxxxx/codenvy_docker/instance/config/postgres/postgres.env"                   -e "CODENVY_ENV_FILE=/home/xxxxxx/codenvy_docker/instance/config/codenvy/codenvy.env"                   -e "CHE_CONTAINER_ROOT=/data"                   -e "CHE_ENVIRONMENT=production"                   -e "CHE_CONFIG=/home/xxxxxx/codenvy_docker/instance"                   -e "CHE_INSTANCE=/home/xxxxxx/codenvy_docker/instance"                   -e "CHE_REPO=on"                   --entrypoint=/usr/bin/puppet                       codenvy/init:5.1.0                           apply --modulepath                                 /etc/puppet/modules/                                 /etc/puppet/manifests/ --show_diff >> "/data/cli.log"
DEBUG: docker_run
[mNotice: Compiled catalog for e7585da5a565.eur.ad.sag in environment production in 0.76 seconds[0m
[mNotice: Applied catalog in 0.15 seconds[0m
INFO: (codenvy config):  Customizing docker-compose for running in a container
docker_run -v "/home/xxxxxx/codenvy_docker/instance/dev":/root/dev alpine:3.4 sh -c "rm -rf /root/dev/*"
DEBUG: docker_run
rm -rf "/home/xxxxxx/codenvy_docker/instance/dev" >> "/data/cli.log"
INFO: (codenvy config):  Copying local binaries to /home/xxxxxx/codenvy_docker/instance/dev...
DEBUG: has_docker_for_windows_client
INFO: (codenvy start):  Preflight checks
DEBUG: port_open
         port 80 (http):        [0;32m[AVAILABLE][0m 
DEBUG: port_open
         port 443 (https):      [0;32m[AVAILABLE][0m 
DEBUG: port_open
         port 2181 (zookeeper): [0;32m[AVAILABLE][0m 
DEBUG: port_open
         port 5000 (registry):  [0;32m[AVAILABLE][0m 
DEBUG: port_open
         port 23750 (socat):    [0;32m[AVAILABLE][0m 
DEBUG: port_open
         port 23751 (swarm):    [0;32m[AVAILABLE][0m 
DEBUG: port_open
         port 32001 (jmx):      [0;32m[AVAILABLE][0m 
DEBUG: port_open
         port 32101 (jmx):      [0;32m[AVAILABLE][0m 
DEBUG: port_open
DEBUG: port_open
DEBUG: port_open
DEBUG: port_open
DEBUG: port_open
DEBUG: port_open
DEBUG: port_open
DEBUG: port_open

INFO: (codenvy start):  Starting containers...
DEBUG: docker_compose
DEBUG: docker_run
docker_compose --file="/data/instance/docker-compose-container.yml" -p="codenvy" up -d >> "/data/cli.log" 2>&1
DEBUG: docker_compose
DEBUG: docker_run
Creating codenvy_nginx_1
Creating codenvy_postgres_1
Creating codenvy_agents_1
Creating codenvy_socat_1
Creating codenvy_rsyslog_1
Creating codenvy_registry_1
Creating codenvy_zookeeper_1
Creating codenvy_swarm_1
Creating codenvy_haproxy_1
Creating codenvy_codenvy_1
docker inspect -f '{{.Id}}' codenvy_codenvy_1
INFO: (codenvy start):  Services booting...
INFO: (codenvy start):  Server logs at "docker logs -f codenvy_codenvy_1"
DEBUG: docker_compose
DEBUG: docker_run
DEBUG: Container with id 3b34c822f36a is matching postgres service
DEBUG: Running state of container 3b34c822f36a is true
DEBUG: Container with id 2c5af0bbc5ef is matching nginx service
DEBUG: Running state of container 2c5af0bbc5ef is true
DEBUG: Container with id 060733d94e19 is matching agents service
DEBUG: Running state of container 060733d94e19 is true
DEBUG: Container with id 12384a061f6a is matching rsyslog service
DEBUG: Running state of container 12384a061f6a is true
DEBUG: Container with id 0dafc02aac21 is matching registry service
DEBUG: Running state of container 0dafc02aac21 is true
DEBUG: Container with id fad49740e872 is matching zookeeper service
DEBUG: Running state of container fad49740e872 is true
DEBUG: Container with id dfb113dcb11a is matching haproxy service
DEBUG: Running state of container dfb113dcb11a is true
DEBUG: Container with id 573d080113fe is matching socat service
DEBUG: Running state of container 573d080113fe is true
DEBUG: Container with id e55035261882 is matching swarm service
DEBUG: Running state of container e55035261882 is true
DEBUG: Container with id d41484082dea is matching codenvy service
DEBUG: Running state of container d41484082dea is true
/usr/bin/curl  "-I -k 99.999.99.999/api/ -s -o /dev/null --write-out %{http_code}"
000
sleep 2
DEBUG: is_docker_for_windows
DEBUG: is_docker_for_mac
/usr/bin/curl  "-I -k 99.999.99.999/api/ -s -o /dev/null --write-out %{http_code}"
200
DEBUG: docker_compose
DEBUG: docker_run
DEBUG: Container with id 3b34c822f36a is matching postgres service
DEBUG: Running state of container 3b34c822f36a is true
DEBUG: Container with id 2c5af0bbc5ef is matching nginx service
DEBUG: Running state of container 2c5af0bbc5ef is true
DEBUG: Container with id 060733d94e19 is matching agents service
DEBUG: Running state of container 060733d94e19 is true
DEBUG: Container with id 12384a061f6a is matching rsyslog service
DEBUG: Running state of container 12384a061f6a is true
DEBUG: Container with id 0dafc02aac21 is matching registry service
DEBUG: Running state of container 0dafc02aac21 is true
DEBUG: Container with id fad49740e872 is matching zookeeper service
DEBUG: Running state of container fad49740e872 is true
DEBUG: Container with id dfb113dcb11a is matching haproxy service
DEBUG: Running state of container dfb113dcb11a is true
DEBUG: Container with id 573d080113fe is matching socat service
DEBUG: Running state of container 573d080113fe is true
DEBUG: Container with id e55035261882 is matching swarm service
DEBUG: Running state of container e55035261882 is true
DEBUG: Container with id d41484082dea is matching codenvy service
DEBUG: Running state of container d41484082dea is true
/usr/bin/curl  "-I -k 99.999.99.999/api/ -s -o /dev/null --write-out %{http_code}"
200
DEBUG: is_docker_for_mac
INFO: (codenvy start):  Booted and reachable
DEBUG: is_initialized
INFO: (codenvy start):  Ver: 5.1.0
INFO: (codenvy start):  Use: http://99.999.99.999
INFO: (codenvy start):  API: http://99.999.99.999/swagger

**Comment by vinokurig** [comment]
@levjason Have you tried to clean the browsers cache?
By the way, if you want to remove only the 'make a wish' you should remove only one line:
`che-support-email="{{branding.supportEmail}}"`.

**Comment by levjason** [comment]
@TylerJewell @vinokurig 
I'm starting from scratch  with  5.2.2.  Which versions of npm and nodejs do I need to build dashboard?

Thanks.

**Comment by levjason** [comment]
@vinokurig @TylerJewell 
I installed npm 3.10.10 and nodejs 6.9.5 and installed Jekyll and the build was successful. Still, I'd like to know which versions of npm and nodejs you use. 

I can't start my assembly:
usajlev@usrscp29:~/git/codenvy$  docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -v /home/usajlev/codenvy_data:/data -v /home/usajlev/git/codenvy:/repo codenvy/cli:5.2.2 start
WARNING: No swap limit support
INFO: (codenvy cli): :/repo mounted - using assembly and manifests from your local repository
/scripts/base/startup_funcs.sh: line 468: /repo/dockerfiles/cli/scripts/cli.sh: No such file or directory

Is /repo still supported?

**Comment by TylerJewell** [comment]
Yes, definitely - but there are some quirks with it that will get in the way because :/repo  mode sources scripts from within the repository.  So if the codenvy/cli:5.2.2 image has bootstrap scripts inside of it that do not match the version of the Codenvy repository that you checked out, then you start to get these mismatch errors.  

We just implemented a big set of CLI refactoring changes so that now images do a hard API match so detect when you are using a Codenvy CLI image that is different from what the branch is that your Codenvy repo has.

So to get around your particular issue, I suggest you develop with repo mode the way that we do it:
1. Wipe your existing docker images
2. Get the codenvy/cli:nightly image and use it with `:/repo` mode.
3. With the latest nightly, there is also now a `--skip:scripts` option which will have the image only use the CLI scripts that are contained in the image and not use those that are sourced in the repository.  For the work that you are doing, you would rarely want the scripts from the repository.
4. I generally also append `--skip:nightly` check to mine, which prevents the CLI from checking to see if there is a newer nightly version.  This is helpful because I also tend to build the image myself so that I can guarantee that the "codenvy/cli:nightly" image that I am using is made up of files that I want it to be made up of, as opposed to downloaded files that would come from an updated nightly image.
5. And if you want to use your own built CLI images instead of the ones our CI pushes onto DockerHub it's fairly easy.

a. Clone Che
b. cd dockerfiles/base && bash build.sh
c. Clone Codenvy
d. cd dockerfiles/cli && bash build.sh
e. You will then have a locally built "codenvy/cli:nightly" image built from source.

**Comment by levjason** [comment]
@TylerJewell The "Make a Wish" is gone. Thanks for the help.
