### ISSUE TITLE
Custom Stack -  Parsing of recipe of environment failed

### ISSUE THREAD

**Issue by giorgiopiatti** [codenvy/codenvy#1577]
I wanted to create a new stack from a existing recipe on docker hub. I tried also with other recipes, for example I tried with codenvy built-in recipes, but it didn't work.

**Reproduction Steps:**
I clicked on import button and then paste the command to import an existing recipes: 
`FROM sunix/chefluxworkspace`
Then when I wanted to test it appeared this error:
Parsing of recipe of environment 'flux' failed. Error: Content type 'null' of recipe of environment is unsupported. Supported values are: text/x-dockerfile

**Codenvy version:**    5.1.0

**OS and version:**    Windows 10

**Docker version:** 1.10

**Comment by slemeur** [comment]
I confirm the issue.
![import stack](https://cloud.githubusercontent.com/assets/1636769/22165969/e6c631be-df5e-11e6-80b4-3bbda5a133b2.gif)

We will give a look. @ashumilova + @akurinnoy 

Alternatively, I can propose you the following workaround for the time being:
When you create your workspace, you can provide your recipe:
![workspace-from-recip](https://cloud.githubusercontent.com/assets/1636769/22165994/0f4c637e-df5f-11e6-954a-bd6d7cb16519.gif)

**Comment by giorgiopiatti** [comment]
Thanks a lot!

**Comment by olexii4** [comment]
fixed in https://github.com/eclipse/che/pull/3694
