### ISSUE TITLE
Impossible to create a custom stack from simple recipe

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#1578]
Creating a custom stack from a simple recipe is almost not possible.

The use case is simple:
I want to create a custom stack with a simple recipe 
"FROM stevanlm/my_custom_stack"

I ran into different sort of issues which are making the flow very complex:
1- The custom stack was already "preconfigured" with a recipe, I didn't know how to change it
2- I added a second machine, but was still not able to delete the previous "dev-machine"
3- I renamed my new machine by "dev-machine" and I had some mixed values

![new stack](https://cloud.githubusercontent.com/assets/1636769/22166101/ae5b7e96-df5f-11e6-9a0c-a448fad2cc0c.gif)

**Codenvy version:**    5.1.0

**Comment by JamesDrummond** [comment]
Are there any work arounds like deleting and creating a new workspace. Trying to determine the severity.

**Comment by JonasT** [comment]
Same problem here. The main issue is that the UI gives me no obvious reason why I can't delete the default machine from my new custom stack in favor of my own specified machine. If there is one, it should actually leave the delete button available but give me a verbose popup with an explanation why exactly the default machine is needed in the current configuration. (so the user has a chance to understand why the setup is required to be like it is, and why the new machine doesn't satisfy those conditions)
