### ISSUE TITLE
Can't create a factory

### ISSUE THREAD

**Issue by ExusVX** [codenvy/codenvy#1580]
When I try to create a factory, firstly from a project whenerver I click the button nothing happens.
When I try to create it from a GitHub  project the create button just stays greyed out so I can't even click it.

**Reproduction Steps:
Go to your dashboard, then factories and try to create a factory from a GitHub URL or from a project**

**Codenvy version: 5.1.0**    

**OS and version: **    

**Docker version: unable to get on my iPad, I will get it on my laptop later**

**Comment by MattHirdler** [comment]
Why is this closed? I still am seeing this and it's very unfortunate...

**Comment by TylerJewell** [comment]
That is more a question for the OP - it never got labeled or handled by support.  If there is a legitimate issue, then we need a list of reproducibility steps for analysis.
