### ISSUE TITLE
Documentation does not list all firewall ports to open

### ISSUE THREAD

**Issue by mbrung** [codenvy/codenvy#1585]
The documentation lists [here](https://codenvy.com/docs/admin-guide/installation/index.html#running-codenvy-behind-a-firewall-linuxmac) the ports to configure on your machine's firewall in order to start Codenvy.

Using only this list I could not get Codenvy to boot on a stock CentOS 7 + Docker 1.13 install -- I would get stuck at 
```
INFO: (codenvy start): Server logs at "docker logs -f codenvy_codenvy_1"
```

Looking further into the documentation I came up with the following list (and I am now happily running Codenvy!):

```
declare -a ports=( 80/tcp 81/tcp 443/tcp 2181/tcp 2375-2376/tcp 4789/udp 5000/tcp 5432/tcp 7946/tcp 7946/udp 8080/tcp 23750/tcp 23751/tcp 32001/tcp 32101/tcp 32768-65535/tcp )
for port in ${ports[@]}
do
    sudo firewall-cmd --permanent --add-port=$port
done
```

If you agree I'd be happy to fix the documentation -- do you accept pull requests?

**Codenvy version:**    5.1.1

**OS and version:**    CentOS 7

**Docker version:** 

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by benoitf** [comment]
thanks @mbrung you may contribute with pull request on https://github.com/codenvy/codenvy-docs/blob/40869e945975b201f6403e4a3613af962b1914c0/src/main/_docs/admin-guide/admin-installation.md#firewall-tests

**Comment by eivantsov** [comment]
@mbrung you said Codenvy did not start without these ports being opened. I do not think it is possible at all, since Tomcat does not seem to check on any connectivity.. What `docker logs -f codenvy_codenvy_1` say?

To run Codenvy you need `80` and `23750` ports opened, as well as ephemeral port range - `32768-65535`. That's it.

**Comment by eivantsov** [comment]
@mbrung you only need port 80, 23750 and the ephemeral port range opened.

**Comment by mbrung** [comment]
@eivantsov I apologize it's been a while since I opened this, and I cannot quite remember what the exact error was.  All I recall is: the error message was pointing me to the log, which didn't contain anything useful.  I'll take another look at this outside of business hours, and will get back to you.
