### ISSUE TITLE
Problems with the terminal?

### ISSUE THREAD

**Issue by cstrutton** [codenvy/codenvy#1586]
I was checking out codenvy today and I ran into an issue.  I was using Chrome on Windows 10.  I created an account, then, I created a rails workspace and ran rails new to generate an app.  

I added some gems and ran bundle install.  So far so good.  

Then I tried to paste a rails generate command into the terminal.  Shift-Insert did not work but Ctrl-V did.  That one isn't a deal breaker but cutting and pasting windows style would go a long way to making it more intuative for more users.  Besides, it works in the editor why not the terminal?

So I finally get the command pasted into the terminal.  Oh No... it fails and I get a stack trace... Wait... where is the scroll bar?  I can't read the stack trace.  Needless to say, this is a deal breaker.

Am I doing something wrong?

**Comment by TylerJewell** [comment]
This is a limitation of term.js. Eclipse Che is doing a port to xterm.js terminal which solves these issues.  It should appear in codenvy in the next couple weeks.

**Comment by TylerJewell** [comment]
This is the Che cross-linked issue.  We hope it is merged for 5.2, which will be release next week.

**Comment by eivantsov** [comment]
Ctrl+Insert for 'copy', Shift+Delete for 'cut' and Shift+Insert for 'paste' . 

Closing the issue.

**Comment by cstrutton** [comment]
Thankyou... Scroll bars and windows style cut and paste now work as expected.
