### ISSUE TITLE
Cant find the localhost address/operations view

### ISSUE THREAD

**Issue by Veerand** [codenvy/codenvy#1591]
I made a Java stack workplace and made a simple maven spring webapp there that successfully deployed to tomcat. However i now cant find a way to the tomcat localhost address. I have gotten it from Operations view before but i just cant find it anymore there.

Nothing would make me happier than knowing i screwed something up and it is an easy fix.

**Comment by eivantsov** [comment]
@Veerand if you go to dashboard, workspace, choose your running workspace, Runtime, dev-machine> servers, you will see all of the exposed and published ports with URLs.

![image](https://cloud.githubusercontent.com/assets/5337267/22247565/75cfe106-e208-11e6-8a8a-8b984b8a740f.png)

I recommend that you start any process in a workspace using Commands Widget with a preview URL, for example, `http://${server.port.8080}` for a Tomcat.

**Comment by Veerand** [comment]
Thanks a lot

**Comment by andreSants** [comment]
Is there a way to get this $server.port value from inside the java code?
This is important, for example, when one app needs to consume  a webservice. The app news to know the target service URL.
