### ISSUE TITLE
CLI unbound var in some cases

### ISSUE THREAD

**Issue by riuvshin** [codenvy/codenvy#1599]
How I run CLI:
```
docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock \
                    -v /Users/roman/development/codenvy_projects/.codenvy_saas:/data \
                    -v /Users/roman/development/codenvy_projects/.codenvy_saas/backup:/backup \
                    codenvy/cli-saas:nightly start --debug --fast
```
error i've got:

```
INFO:
INFO: (codenvy start): Booted and reachable
INFO: (codenvy start): Ver: nightly
INFO: (codenvy start): Use: http://localhost
INFO: (codenvy start): API: http://localhost/swagger
/scripts/base/library.sh: line 72: CHE_DEBUG_PORT: unbound variable
```

@TylerJewell @benoitf I think this is something that happen after debug refactoring. Please not this is not happen if use only `--debug` without `--fast`

**Comment by TylerJewell** [comment]
This is an issue with Eclipse Che base CLI assembly.  Added fix in: https://github.com/eclipse/che/pull/3862.

**Comment by TylerJewell** [comment]
https://github.com/eclipse/che/pull/3862

**Comment by TylerJewell** [comment]
This error uncovered a couple places where we are assuming `CHE_DEBUG_PORT` when it really should be ${CHE_PRODUCT_NAME}_DEBUG_PORT.   Thanks, @riuvshin.

**Comment by riuvshin** [comment]
@TylerJewell should we close this?

**Comment by TylerJewell** [comment]
Thanks - good catch..
