### ISSUE TITLE
User should be clearly notified if user id is the same with team name

### ISSUE THREAD

**Issue by vzhukovskii** [codenvy/codenvy#1604]
When I've logged into IDE via oAuth and want to create new team with the same name which my email has, I should be notified with different message that I'm trying to use reserved name.

Actual state see on the screenshot:

![codenvy - dashboard - new team 2017-01-25 17-49-14](https://cloud.githubusercontent.com/assets/1968177/22299027/486ea08e-e32b-11e6-994a-fc15fb59fc82.png)

**Comment by ashumilova** [comment]
Fixed by reworking unique team names.
