### ISSUE TITLE
IDE error message is displayed when click on billing invoices

### ISSUE THREAD

**Issue by vitaliy-guliy** [codenvy/codenvy#1605]
IDE script become injected to the main page when clicking Invoices on the Billing page.

![billing](https://cloud.githubusercontent.com/assets/1655894/22299145/bf040914-e32b-11e6-8ad9-3bc67a93c74c.png)

![head](https://cloud.githubusercontent.com/assets/1655894/22299150/c18ef9d2-e32b-11e6-884c-6253eb77a348.png)

**Comment by ashumilova** [comment]
https://github.com/codenvy/codenvy/commit/5dcb3e38c9c7f97afe9d1a6ebfcae6d9527784a1
