### ISSUE TITLE
User should be redirected somewhere if it is trying to rich nonexisted team

### ISSUE THREAD

**Issue by vzhukovskii** [codenvy/codenvy#1606]
When user is trying to open nonexisted team he should be redirected somewhere or 404 page should be displayed:

![codenvy - dashboard - meee 2017-01-25 18-14-49](https://cloud.githubusercontent.com/assets/1968177/22299263/1ee863de-e32c-11e6-809b-9ca8724dd67f.png)

**Comment by ashumilova** [comment]
https://github.com/codenvy/codenvy/commit/9a1e0224e8bea8cedc4c0900fe7e020e4e402398
