### ISSUE TITLE
Impossible to create workspace into a team

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#1609]
**Reproduction Steps:**
1- Create a new team
2- Go into team's workspace tab
3- Click "Add workspace"
4- Do not change anything in the settings of the workspace
5- Click "create"

Result:
![screen shot 2017-01-25 at 18 47 01](https://cloud.githubusercontent.com/assets/1636769/22302357/ae69d89c-e32e-11e6-923b-9c933d478854.png)

**Codenvy version:** A1

**Comment by vitaliy-guliy** [comment]
The next showcase:
- create new user `user1`
- logout current user
- login as `user1`
- create new team
- go to team workspaces and create new workspace

![error1](https://cloud.githubusercontent.com/assets/1655894/22472341/fba560aa-e7dd-11e6-98e7-05b62fb6b79c.png)

![error2](https://cloud.githubusercontent.com/assets/1655894/22472373/192b33ca-e7de-11e6-9102-acad7abd90fc.png)

Pay attention on the `Workspace Cap` is not configured and user by default.

![workspace cap](https://cloud.githubusercontent.com/assets/1655894/22472440/51012ba6-e7de-11e6-8d8e-1b49b669ea57.png)

**Comment by JamesDrummond** [comment]
@slemeur Think this should be severity/P1 . Might have another case that we release without teams.

**Comment by slemeur** [comment]
This issue has been fixed.
