### ISSUE TITLE
dash "-" character should be enabled for team name

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#1610]
It should be possible to use "-" in name of teams

**Reproduction Steps:**

**Codenvy version:**    A1

**Comment by vitaliy-guliy** [comment]
And also "_" as a regular character.

**Comment by ashumilova** [comment]
https://github.com/codenvy/codenvy/commit/b012b1a53ce5d7f68ebe9f44f76390fed8ab0975

**Comment by ashumilova** [comment]
![name_restriction](https://cloud.githubusercontent.com/assets/1611939/22544179/5df5c308-e93c-11e6-9d09-a49a32fa617e.png)

**Comment by slemeur** [comment]
Ok for me
