### ISSUE TITLE
Handle Enter keypress for name field to instant team creation

### ISSUE THREAD

**Issue by vzhukovskii** [codenvy/codenvy#1613]
Go to _Create New Team_ page and enter team name. It would be better to handle _Enter_ keypress to instant team creation instead of clicking button _Create Team_. Because there is a one editable field so it will force creation workflow.

![codenvy - dashboard - new team 2017-01-26 10-49-46](https://cloud.githubusercontent.com/assets/1968177/22325129/75b645bc-e3b5-11e6-9d4c-df81b56daa74.png)

**Comment by ashumilova** [comment]
https://github.com/codenvy/codenvy/commit/e35e380974d43c7ffb173a6223347314b9ac7c0a
