### ISSUE TITLE
Administration title is not aligned

### ISSUE THREAD

**Issue by vitaliy-guliy** [codenvy/codenvy#1614]
Administration title is not aligned in navigation bar.

![administration title](https://cloud.githubusercontent.com/assets/1655894/22325475/eb1a1d3c-e3b6-11e6-8dcf-b7a1893228d0.png)

**Comment by slemeur** [comment]
And it is not using the same style as "TEAMS" either.
@olexii4 is that something you could fix very quick?

**Comment by olexii4** [comment]
Will fix in 
https://github.com/codenvy/codenvy/pull/1965
![selection_010](https://cloud.githubusercontent.com/assets/6310786/24288131/e9251ce8-1084-11e7-8546-d779a8fcbeaa.png)

**Comment by slemeur** [comment]
ok for me with #1965

**Comment by ashumilova** [comment]
Fixed
