### ISSUE TITLE
Check the license before displaying popup for new user

### ISSUE THREAD

**Issue by vitaliy-guliy** [codenvy/codenvy#1615]
When I clicked on 'Add User' button a popup for new user is displayed. I entered login, email and password for new user and click 'Create' button. As result new user is not created and I got a message that the license is not allow to have more than 3 users.

The proposal is to check the license before displaying a form for new user.

![add user](https://cloud.githubusercontent.com/assets/1655894/22328266/076d2760-e3c4-11e6-85df-51ff49e8e9a7.png)

**Comment by TylerJewell** [comment]
Will not fix - moving to EPL license.
