### ISSUE TITLE
Wrong subtitle displayed for delete billing info

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#1616]
<img width="460" alt="screen shot 2017-01-26 at 12 23 08" src="https://cloud.githubusercontent.com/assets/1636769/22329847/7be00e38-e3c3-11e6-8a70-c7ac0033f747.png">

The description is incorrect. 

When we are deleting billing information, the teams are not deleted. 

**Codenvy version:**   5.2.0-Team

**Comment by akurinnoy** [comment]
https://github.com/codenvy/codenvy/commit/7aa05099d8ea1a371f4b7faec2b644efc37cb073
