### ISSUE TITLE
Unexpected behavior while setting Workspace Cap and Running Workspace Cap values

### ISSUE THREAD

**Issue by vzhukovskii** [codenvy/codenvy#1622]
Saving _Workspace Cap_ and _Running Workspace Cap_ values performs with unexpected behavior. 

![shit happens](https://cloud.githubusercontent.com/assets/1968177/22332621/7b36caaa-e3da-11e6-95e3-2d4db197a17c.gif)

**Comment by ashumilova** [comment]
https://github.com/codenvy/codenvy/commit/43736b24af3b7c8236579c4a690e6a8e27cc1535
