### ISSUE TITLE
Improve Workspace RAM Cap description

### ISSUE THREAD

**Issue by vzhukovskii** [codenvy/codenvy#1623]
It isn't obvious that _Workspace RAM Cap_ consumes value in gigabytes. There is a proposal to add into description that this field consumes value in GB.

![codenvy - dashboard - meadmin 2017-01-26 15-20-28](https://cloud.githubusercontent.com/assets/1968177/22332718/01a2b8c4-e3db-11e6-9f6c-3890636d1031.png)

Ten of what?

**Comment by ashumilova** [comment]
![ram_gb](https://cloud.githubusercontent.com/assets/1611939/22586310/b06b583c-ea04-11e6-9462-4ad70295d466.png)
@slemeur please, choose where to put GB label: in the title or inside the input

**Comment by slemeur** [comment]
I like better the GB inside the input

**Comment by ashumilova** [comment]
https://github.com/codenvy/codenvy/commit/3f67a5f0202b0ba92ec5a8ed93a1904057660b16#diff-f4ea51a9d02a215c866f69159ea2431cR106
