### ISSUE TITLE
Double scroll on billing invoices

### ISSUE THREAD

**Issue by vitaliy-guliy** [codenvy/codenvy#1629]
Double scroll is appeared on Billing > Invoices page

![double scroll](https://cloud.githubusercontent.com/assets/1655894/22374386/aa7b69f4-e4ae-11e6-966f-a42dc4def74a.png)

**Comment by ashumilova** [comment]
https://github.com/codenvy/codenvy/commit/366a245436fe0e6e40bf3852a086d3a8f8e54a6e
