### ISSUE TITLE
Stop workspace by timeout does not work (regression)

### ISSUE THREAD

**Issue by artaleks9** [codenvy/codenvy#1631]
**Reproduction Steps:**
* Create and open a workspace in the IDE
* Do not make any actions in the IDE

**Expected behavior:**
* workspace should stop after 10 min

**Observed behavior:**
workspace is not stopped

**Codenvy version:**  5.2.0-SNAPSHOT
**OS and version:**   Ubuntu 14.04 

**Additional information:**
* Problem can be reliably reproduced: Yes

**Comment by riuvshin** [comment]
that was missconfiguration issue, on nightly we've applied 4h timeout. now it is set back to 10min
