### ISSUE TITLE
Display idle timeout on workspace details

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#1633]
We need to display the configured idle timeout for the workspace, in the workspace details.

![screen shot 2017-01-27 at 18 36 53](https://cloud.githubusercontent.com/assets/1636769/22380907/98f77860-e4bf-11e6-962c-0f3cf3455443.png)

Display "Buy more ram to get more idle timeout" next to the value. When the link is clicks, display the "Get More Ram" popup.

**Codenvy version:**  5.2.0

**Comment by ashumilova** [comment]
https://github.com/codenvy/codenvy/commit/0b5fd04f253b859c852c4665f3a6b2d89790ccb2
