### ISSUE TITLE
Add mention about idle timeout in "Get More RAM" popup

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#1634]
Need to add a line bellow the first one here:
![screen shot 2017-01-27 at 18 27 59](https://cloud.githubusercontent.com/assets/1636769/22381113/9eed6ed6-e4c0-11e6-8edc-3adbf8e45094.png)

This line will mention the idle timeout:
"All workspaces of your account will be granted an idle timeout of 4 hours."

**Comment by bmicklea** [comment]
@slemeur - wouldn't it be easy to add a line of text below the RAM chooser: "Purchasing RAM increases your workspace idle timeout to 4 hours."

**Comment by slemeur** [comment]
+1 we can do like this, np. Thanks

**Comment by ashumilova** [comment]
https://github.com/codenvy/codenvy/commit/8a32c52cc037865b4e95f6a71b0e54858010d83e
