### ISSUE TITLE
Add ability to get support on subscriptions

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#1635]
In the billing screens, we need to add the ability for the user to reach us.

In Billing Card:
![billing_cc](https://cloud.githubusercontent.com/assets/1636769/22381591/779d3eae-e4c2-11e6-8167-9d2de98da7e7.png)

In Billing Invoices:
![screen shot 2017-01-27 at 19 03 58](https://cloud.githubusercontent.com/assets/1636769/22381815/627edf0e-e4c3-11e6-8f9a-2aebdffa840d.png)

At the top of the screens, add a line:

"Having a question about subscriptions and billings in Codenvy - contact us at account-help@codenvy.com"

**Comment by akurinnoy** [comment]
https://github.com/codenvy/codenvy/commit/04d43981fd7c46a98e62f7b1669850e9df05c58b


![screenshot-localhost 3000-2017-02-03-11-11-46](https://cloud.githubusercontent.com/assets/16220722/22585773/2769e0c8-ea02-11e6-8a12-c8d2ce2186f4.png)
![screenshot-localhost 3000-2017-02-03-11-13-41](https://cloud.githubusercontent.com/assets/16220722/22585777/29dc95f8-ea02-11e6-8a6c-02615417a179.png)
