### ISSUE TITLE
Impossible to create a workspace when team has not configured properly

### ISSUE THREAD

**Issue by vzhukovskii** [codenvy/codenvy#1639]
Try to create a new team and not to configure Ws Cap, Running Ws Cap and Ws Memory limits. Go to Workspace tab and try to create a new workspace in newly created team. You won't be able to do this.

![240-workspaces](https://cloud.githubusercontent.com/assets/1968177/22418305/2560f4fc-e6e1-11e6-940b-b763090fc808.gif)

**Comment by slemeur** [comment]
Will be fixed by: https://github.com/codenvy/codenvy/issues/1729

**Comment by slemeur** [comment]
Fixed
