### ISSUE TITLE
Set credit card number input max value

### ISSUE THREAD

**Issue by ashumilova** [codenvy/codenvy#1649]
The credit card input for the card number should give ability to enter less than 16 digits.

![image](https://cloud.githubusercontent.com/assets/1611939/22424914/6f61fcc0-e701-11e6-9c4c-1bc2a4cad306.png)

**Comment by akurinnoy** [comment]
https://github.com/codenvy/codenvy/commit/fcabb3403bd025e8ee6ea0159461f819721990b8
