### ISSUE TITLE
Show user email somewhere

### ISSUE THREAD

**Issue by vitaliy-guliy** [codenvy/codenvy#1650]
I cannot see email of the current user. It's displayed only when creating a team.
It would be great to display email in user menu or somewhere else.

![edit user](https://cloud.githubusercontent.com/assets/1655894/22425752/4cfa5868-e705-11e6-9a86-646c44039e7e.png)

![create team](https://cloud.githubusercontent.com/assets/1655894/22425775/600d4848-e705-11e6-9a49-5aef0022e9c0.png)

**Comment by eivantsov** [comment]
This issue was moved to eclipse/che#5663
