### ISSUE TITLE
Improve User Management page

### ISSUE THREAD

**Issue by vitaliy-guliy** [codenvy/codenvy#1651]
Improve User Management page:
- don't scroll action buttons and table header
- apply scroll only to the user list

![user management improved](https://cloud.githubusercontent.com/assets/1655894/22427114/80580ae8-e70a-11e6-870f-623db803ce87.png)

**Comment by vitaliy-guliy** [comment]
In current version pager displays only one page but there are two.

![incorrect pager](https://cloud.githubusercontent.com/assets/1655894/22460666/9c72e76c-e7ae-11e6-8a31-b795246168e4.png)

**Comment by TylerJewell** [comment]
@ashumilova - is this still actual given the latest redesigns?

**Comment by ashumilova** [comment]
still actual

**Comment by eivantsov** [comment]
This issue was moved to eclipse/che#5660
