### ISSUE TITLE
application url still requires adding alias on mac

### ISSUE THREAD

**Issue by riuvshin** [codenvy/codenvy#1653]
after merge of https://github.com/codenvy/codenvy/commit/6ee96a7467a0ff91a5777c7eeaaa4aa549d8774b now codenvy does not require alias to access codenvy on mac, but I;ve noticed that in codenvy.env

CLI still write:
`CODENVY_SWARM_NODES=192.168.65.2:23750`

and as result of that if I run my app in a workspace ide gives me url with that ip
http://192.168.65.2:32769/spring/hello which will not be accessible without alias.

**Comment by riuvshin** [comment]
issue is still actual

**Comment by garagatyi** [comment]
@TylerJewell related to swarm. What should we do with this issue?
