### ISSUE TITLE
Cannot Load Web Interface After Login. ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by jtcressy** [codenvy/codenvy#1654]
Tested with chrome, firefox, MS edge.
Chrome shows error of "ERR_TOO_MANY_REDIRECTS"
Fresh deployment via codenvy/cli on CentOS 7 host, docker 1.13.0, firewall rules set to accept all packets
**Login page accessible**, but errors out after login. Occurs with both normal admin user and github login via OAuth.

**Reproduction Steps:**
Deploy new codenvy stack, ENV has SSL, custom hostname defined (che.<mydomain>.net), and oauth keys installed from github. Admin account has user/pass. After services start, login to che.<mydomain>.net and then you get the error. 

**Codenvy version:** 5.1.2

**OS and version:** CentOS 7

**Docker version:** 1.13.0

**Codenvy cli.log output:** 
[cli.zip](https://github.com/codenvy/codenvy/files/739621/cli.zip)

**Comment by TylerJewell** [comment]
This error is usually an indication that there is some sort of proxy (usually no proxy) that must be configured and is not yet.

Is there any configuration of proxies in your daemon?

**Comment by jtcressy** [comment]
No, i'm not sure what to configure for proxying. I'm connecting directly to the host running this, and i'm not using the loadbalancer I normally use. I have not setup any proxies between me and the server.

**Comment by TylerJewell** [comment]
Grab the nightly version of codenvy and then run "info --bundle" and provide the generated support bundle.  Someone can take a look.

**Comment by jtcressy** [comment]
Generated bundle here: 
[codenvy-diagnostic-bundle.zip](https://github.com/codenvy/codenvy/files/739755/codenvy-diagnostic-bundle.zip)

**Comment by eivantsov** [comment]
@jtcressy I am trying to reach Codenvy login page by IP and it does not seem that Codenvy is running there at the moment. When tyring hostname, it's toomany redirects out of the box.

Have you taken a look at https://codenvy.io/docs/admin-guide/configuration/index.html#https?

**Comment by jtcressy** [comment]
Accessing my hostname externally will push you through my load balancer, but I *just now* disabled it, so try again and tell me what you see. I have ssl configured properly, since it was working for a little while. Trying now, it's still giving the same error about too many redirects.

**Comment by jtcressy** [comment]
So, now i'm running into all kinds of issues with the postgres container when trying to re-deploy codenvy (using the same .env btw). It keeps saying that the folder has wrong permissions set, even after a full "codenvy/cli destroy" command. Diagnosing any issues with the nfs server backing the mount directory. This is really getting to be a pain in the ass.

**Comment by jtcressy** [comment]
Caught the output the last two lines of "codenvy_codenvy_1" and the only output of "codenvy_postgres_1"
```
psql: FATAL:  password authentication failed for user "pgcodenvy"
[INFO]: Postgres is unavailable. Trying in 5 seconds...
[root@centos7-codenvy data]# docker logs codenvy_postgres_1
LOG:  redirecting log output to logging collector process
HINT:  Future log output will appear in directory "pg_logs".
[root@centos7-codenvy data]#
```

**Comment by eivantsov** [comment]
I have tried it again, but it looks like you have never logged in as admin and accepted License Agreement. By the way, the default admin user and password does not work. Have you changed the password?

**Comment by jtcressy** [comment]
Yes, i changed the password. i'll PM it to you. (it's not a terribly secure password, so i'm not worried about leaking it) I havent been able to accept the license agreement since as soon as i login, we get the redirect loop.

**Comment by jtcressy** [comment]
New Testing Results:
- Deployed a 1vCPU 3.75GB compute instance on google cloud. Image is based on centos7. 
- Copied letsencrypt SSL certificate to /home/jtcressy/haproxy.pem (File contains cert, chain, and privkey)
- Enabled SSL and set path to location above in codenvy.env
- Started codenvy/cli with this command: ``docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /che-data:/data -e CODENVY_HOST=104.198.10.40 codenvy/cli start``
- After logging in with ``admin:password`` we are greeted with the redirect loop!
- Note: no redirect loop when logging in without SSL enabled
- Not tested: Selfsigned cert or cert from other cert authority (not letsencrypt)

**Comment by eivantsov** [comment]
@jtcressy it looks like Java in a Codenvy container does not respect this certificate and it has to be added to Java trust store.

Can you share server logs please?

**Comment by jtcressy** [comment]
Here you go: https://gist.github.com/jtcressy/47df75f05959eabcd080988962b0adea

**Comment by eivantsov** [comment]
@jtcressy this log says you have logged in but cannot start a workspace. Can you make sure port 23750 is opened? This is how Swarm communicates with Docker.

**Comment by jtcressy** [comment]
It seems to start the workspace runtime now, but gets stuck and never finishes. Or at least, it looks like it finishes but it doesnt recognize that, thus the workspace agent never starts. 

I'm going to go ahead and just wipe and re-image the centos server

**Comment by eivantsov** [comment]
FYI, you need to open the entire ephemeral port range or at least first 100 ports from that range.

**Comment by jtcressy** [comment]
also did that. opened a range of 50 for the ephemerals starting at 32768. 

Right now, however, my ISP just crapped out and i'm waiting on a service call for them to come fix my internet connection. 

So I can't do more testing for now. I was only half-way through re-deploying the new centOS vm.

**Comment by jtcressy** [comment]
So, internet's back up, and I have found the solution. 

(Keep in mind before I continue: This server is behind an NAT router configured with NAT reflection)

I need to open ports starting at the VERY BEGINNING of the ephemeral range. i.e. port 32000, instead of 32768. I assumed 32768 was all i needed since that was the first port the workspaces started on. HOWEVER I noticed some services using port 32102 or so in the logs, and I though that would be sorta important to document. Nonetheless, changing the port to start at 32000 worked since it included that port seen in the logs. 

CODENVY_HOST=che.jtcressy.net

DNS Setup is as such: che.jtcressy.net points to the external IP for the whole NAT'd network. It seems the codenvy server loves to refer to the host it's working on as the CODENVY_HOST IP address, so internal network connections will bounce out of the network then back in to the host. Is this by design? I know that the codenvy server deploys perfectly fine on cloud infrastructure, but is it actually looping back through the public IP? 

My setup is working for now, and I think i'll get sat down and start using it.

Now, assuming what I said before is true, I would highly recommend implementing a CODENVY_EXTERNAL_HOST variable, and a CODENVY_INTERNAL_HOST variable to distinguish between external endpoints and internal (LAN) endpoints. When CODENVY_HOST was set to the internal IP address (via che.jtcressy.net = lan IP) I was getting this error in the logs for the "codenvy_codenvy_1" container: ``[WARN ] [c.c.a.s.c.HttpSsoServerClient 67]    - No route to host``

Hopefully this is enough information to move forward.

**Comment by TylerJewell** [comment]
Glad that there is a productive solution to this. but for the life of us, we cannot understand why you needed a different port range. THAT is a very very interesting scenario that has us scratching heads.

It is expected that Codenvy uses public IP for all communications. In his case every client (including codenvy itself) goes to external network and then returns to codenvy host back because of that.  So a `CODENVY_INTERNAL_HOST` would not be appropriate.

**Comment by jtcressy** [comment]
Also, these were the ports I was referring to.
![image](https://cloud.githubusercontent.com/assets/7663028/22558907/a7676dbc-e92c-11e6-82cb-c21f8744ce9c.png)

I suppose we can just make sure to structure networks around codenvy when deploying to private cloud. 
For reference to others that find this issue, necessary items are:
- Native NAT reflection (hairpin) 
- Forward ports 32000-32800*, 23750, 23751, 443, 80, 5000**
- DNS name referenced in CODENVY_HOST needs to point to public IP
- Optional: Codenvy still works if using an external haproxy reverse proxy on ports 80, 443. All other ports are NAT port-forwarded directly to the host's internal IP.

\* can be increased past 32800 if using A LOT of workspaces
** only needed for registry connections.

Some of this is already in the documentation, but I can't recall if the port range was documented. I remember only seeing that you need 32768 and up, but I could be wrong.

If for some reason your router/firewall does *not* support hairpin NAT, there is almost no way around it.

**Comment by TylerJewell** [comment]
Thanks for the documentation, @jtcressy.  I have updated the title so that it will be easier for people to find this thread in the future.
