### ISSUE TITLE
codenvy.io has che-in-che stack - should not be there for hosted scenarios

### ISSUE THREAD

**Issue by olivieryolene** [codenvy/codenvy#1656]
Cannot run che in che : => Cannot connect to the Docker daemon. Is the docker daemon running on this host?

**Reproduction Steps:**
1. Create a workspace in codenvy : choose ready to go stack "Eclipse Che",
2. Create project from sample project che in che,
3. Launch command "2. build che in che" => create assembly,
4. Try to launch commands : "1. setup che in che", or "3. run che in che" :
=> Cannot connect to the Docker daemon. Is the docker daemon running on this host?

**Codenvy version:**    
5.1.2 (running in codenvy cloud)

**Comment by joblini** [comment]
Having the same problem.

**Comment by TylerJewell** [comment]
Hmmm.  Che in Che should not be permitted in the codenvy.io public cloud.  It requires access of your workspace to the hosts docker daemon which is a security problem.  Our cloud assembly should remove that stack selection but it seems to appear.   It should be in codenvy onprem though where an admin can define the access.  Will label this a bug but encourage you to down the onprem codenvy to get this specific behavior.

Thanks for reporting.

**Comment by bmicklea** [comment]
@skryzhny is this unblocked now?

**Comment by skryzhny** [comment]
Che-in-che removed from DB for SaaS and doesn't included in default stacks for codenvy now.
