### ISSUE TITLE
Show summary section on Get more RAM popup

### ISSUE THREAD

**Issue by ashumilova** [codenvy/codenvy#1659]
The Get more RAM widget should contains purchase summary section at the bottom:

![image](https://cloud.githubusercontent.com/assets/1611939/22464417/6b504ab0-e7bf-11e6-9b23-166ef4cbe4f8.png)

Follow the section from spec https://github.com/codenvy/planning/issues/34
At time of purchase or upgrade we charge for portion of the month remaining
- **Initial purchase example:** May 26th I buy 1GB RAM package 
  - May 26, my credit card is charged $1.92 (5*0.32)
  - At the start of each month until I cancel I am charged another $10
- **Same package upgrade:** June 17 I buy 1GB more 
  - Jun 17, my credit card is charged $4.48 (14*0.32)
  - At the start of each month until I cancel I am charged another $20
- **New package upgrade:** June 27 I upgrade to buy 1 more developer seat
  - June 27, my credit card is charged $3.84
  - Because I'm upgrading to a new package I have to pay the new package price of $0.96 per day for 1 developer seat
    At the start of each month until I cancel I am charged another $30 (50$ in total)

**Comment by TylerJewell** [comment]
Minor nit - the '$' sign should always be in front.   "Your request will cost $100/month/user".

**Comment by ashumilova** [comment]
https://github.com/codenvy/codenvy/commit/a2e9ceac82387f38baa07384706d40f0f3b3bb78
