### ISSUE TITLE
Launch backup of workspaces should be disabled if restoration of workspace was failed

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#1663]
Analysing logs from https://github.com/codenvy/codenvy/issues/1662 I found that:
After we failed to restore projects from backup we still trying to synchronize projects back to backup storage.
This may lead to situation when we effectively erasing backup.
Possible steps:
- Start workspace
- Restoration job failed  - /projects in BAD, inconsistent state.
- Stop of workspace
- Backup procedure starts to synchronise /projects. So GOOD backup from backup storage is replaced with BAD one from workspace

**We should not launch backup procedure if previous restoration procedure was failed.**
Maybe we need to have separate API method that removes workspace without attempting to backup projects.

**Reproduction Steps:**
Don't know

**Codenvy version:**   5.1.2

**Comment by bmicklea** [comment]
@gazarenkov - this looks like a legitimate blocker. I'm not sure who would fix this but it feels like a 5.2.1 emergency bug fix issue because it affects the integrity of backups.  Do you agree?

**Comment by riuvshin** [comment]
@bmicklea included to 5.2.1
