### ISSUE TITLE
Improve button styles

### ISSUE THREAD

**Issue by vitaliy-guliy** [codenvy/codenvy#1664]
When creating a workspace we have buttons `Run`, `Export As A File`, `Export To Private Cloud` and `Delete` which are disabled by default but have different styles. `Run` and `Delete` buttons have hovered state which has to be removed.

![disabled buttons](https://cloud.githubusercontent.com/assets/1655894/22470340/9f84665a-e7d7-11e6-9577-3cd84b14e728.png)

Also take a look on `Cancel` buttons when creating and removing a user. These buttons are active but look differently.

![add user](https://cloud.githubusercontent.com/assets/1655894/22470497/33b016bc-e7d8-11e6-955b-2637d32f7043.png)

![remove user](https://cloud.githubusercontent.com/assets/1655894/22470517/3b46cb3c-e7d8-11e6-869f-83fcdc479e25.png)

**Comment by vitaliy-guliy** [comment]
Improve `Remove workpaces` popup
 - place `Delete` button on the right
 - rename `Close` button on `Cancel` to be consistent with other popups

![remove workspaces buttons](https://cloud.githubusercontent.com/assets/1655894/22514748/0249597c-e8a9-11e6-85b8-1b766f0760fb.png)

**Comment by eivantsov** [comment]
Closing the issue since this is likely to be addressed in a new Workspace details page.
