### ISSUE TITLE
Unnecessary checkbox on Stacks list

### ISSUE THREAD

**Issue by vitaliy-guliy** [codenvy/codenvy#1665]
Remove unnecessary checkbox from list of stacks.

![extra checkbox](https://cloud.githubusercontent.com/assets/1655894/22472902/a867aea0-e7df-11e6-90af-b00672b9ff75.png)

**Comment by eivantsov** [comment]
This checkbox is required. UX will be improved when stacks management with permissions model will be implemented in UD.
