### ISSUE TITLE
CLI restart does not work properly

### ISSUE THREAD

**Issue by riuvshin** [codenvy/codenvy#1669]
after merging graceful stop changes `cmd_restart` does not work

if I do `restart` it says me 
```
ERROR: (codenvy action/graceful-stop): Call on rest url /api/system/state returned invalid response code (401) with error:User not authorized to call this method.
```

but even with 
`restart --user admin --password password` it gives the same error it seems restart does not support those agrs

**Comment by riuvshin** [comment]
also restart does not support `--force` for stop, this is not that critical as auth but still missing part

**Comment by benoitf** [comment]
Fixed by https://github.com/eclipse/che/pull/3986
