### ISSUE TITLE
Wrong alignment in team workspaces table

### ISSUE THREAD

**Issue by vitaliy-guliy** [codenvy/codenvy#1671]
Fix alignment in team workspaces table.

![wrong alignment](https://cloud.githubusercontent.com/assets/1655894/22505970/9f4299d2-e886-11e6-9efd-a9b443314dd2.png)

**Comment by vitaliy-guliy** [comment]
The same we have in Menu -> Workspaces

![wrong alignment 2](https://cloud.githubusercontent.com/assets/1655894/22506034/f31a6288-e886-11e6-8425-7e493145e144.png)

**Comment by eivantsov** [comment]
This issue was moved to eclipse/che#5656
