### ISSUE TITLE
Workspace of team member is not visible for team admin/owner

### ISSUE THREAD

**Issue by vitaliy-guliy** [codenvy/codenvy#1672]
Workspaces of team members are not visible for team admin/owner.

To reproduce do like following:

- log in as `admin`, create team `adminTeam1` and add a user `Vitaliy` as a team member

![team admin and member](https://cloud.githubusercontent.com/assets/1655894/22506541/ae6e9a7a-e889-11e6-8f75-bb7cab54fac5.png)

- go to `adminTeam1` -> `Workspaces` and create a workspace `adminWorkspace` ( just to test )

![admin team workspaces](https://cloud.githubusercontent.com/assets/1655894/22506645/43a6bf28-e88a-11e6-8218-056063f997e6.png)

- open an incognito tab and login as `Vitaliy`

- go to `adminTeam1` -> `Workspaces` and create workspaces `vitaliyWorkspace1` and `vitaliyWorkspace2`

![team member workspaces](https://cloud.githubusercontent.com/assets/1655894/22506734/b97d6878-e88a-11e6-851b-2b80d1bee7bf.png)

- refresh the dashboard page where `admin` is logged in and go to `adminTeam1` -> `Workspaces`

![admin workspaces refreshed](https://cloud.githubusercontent.com/assets/1655894/22506810/1df5f5a4-e88b-11e6-826c-332f998a0bac.png)

Result: workspaces of team member are not visible for team admin/owner.

**Comment by vitaliy-guliy** [comment]
There is another issue. 
Workspaces created by team admin/owner are not visible for team members:
The workspace `adminTeam1/adminWorkspace` created by `admin` is not visible for `Vitaliy`.

**Comment by ashumilova** [comment]
@slemeur can we show small warning or info message at the top or bottom of the list - that member of the team doesn't have access to the whole list of team workspaces, but still can see his own ones?

**Comment by slemeur** [comment]
I don't think we need that. We are in the context of a team, not an account. The people who I invite to the team and give them roles, are people that I trust to work with for certain purposes.
- A team owner / admin must be able to see all the workspaces of a team.
- A team members can only see the workspace he has been invited in, or the ones he created.

Team admin should be able to stop workspaces, keep the team organized and and manage resources, if he can't see all the workspaces, he can't do that. 

As it'll be very easy to create multiple teams - if there are things that are not interesting a whole team, an admin will still be able to create another (smaller and more restricted) team to not bother other members.

As enhancement, we should have default scenarios:
- When an admin is creating a workspace in a team, he should be able to share it with all team or just specific team members
- When a member is creating a workspace in a team, all admins should be added to the workspace.

Also, in the workspaces list from a team, we need to display the members of the workspaces as here:
https://cloud.githubusercontent.com/assets/1636769/18475431/a6eb711a-79c6-11e6-93c5-b494f6591abf.png
