### ISSUE TITLE
Option to set tcp port other than 80?

### ISSUE THREAD

**Issue by koustuvsinha** [codenvy/codenvy#1673]
How to run docker codenvy with setting http port _other_ than 80? I saw no related documentation. I am running the instance like this : 

```
docker run -it --rm -e DOCKER_HOST=<..> -v /tmp:/data codenvy/cli start
```

And I get this error : 

```
port 80 (http):          [ALREADY IN USE]
```

**Comment by TylerJewell** [comment]
Unfortunately, we require port 80 available for Codenvy right now.  Changing the port is not as simple as flipping a port inside of our internal nginx. We are considering this for the future, but right now we need port 80.

**Comment by koustuvsinha** [comment]
It would be very helpful to have this configuration.

**Comment by TylerJewell** [comment]
We could think about it.  If your company has a support arrangement please open a ticket with support to discuss the need.

**Comment by TylerJewell** [comment]
We are moving to k8s - and any capabilities such as this will be delegated to that implementation.
