### ISSUE TITLE
Team name should be unique inside personal organization, not system wide

### ISSUE THREAD

**Issue by ashumilova** [codenvy/codenvy#1674]
The team name is now used as namespace and has to be unique in the system. Need to rework the namespace usage to give ability team name to be unique only per personal account (root organization).

In this case the namespace will become a composite key like this: 
 `parent_organization_name/sub_organization_name/sub_organization_name`

**Comment by sleshchenko** [comment]
Depends on https://github.com/eclipse/che/issues/4061
