### ISSUE TITLE
Nightly CLI failed after release of 5.2

### ISSUE THREAD

**Issue by garagatyi** [codenvy/codenvy#1681]
After release of 5.2 I tried to restart codenvy but CLI failed.
```
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/gaal/workspace/.codenvy:/data -v /home/gaal/workspace/codenvy:/repo codenvy/cli:nightly restart
WARNING: No swap limit support
INFO: (codenvy cli): :/repo mounted - using assembly and manifests from your local repository
/scripts/base/startup_funcs.sh: line 411: cli_pre_init: command not found
```
After manual pull of codenvy/cli:nightly everything is fine. But it was not obvious that I had to manually pull nightly tag.
Maybe we should fix something right now or consider some improvements/policies to avoid such issues in future. 

**OS and version:**    Ubuntu 16.04

**Docker version:** 1.12.5

**Comment by benoitf** [comment]
About improvements, we should mount CLI scripts of local repository by default when `:/repo` is used as I think expectation number one is to start a local assembly, not to code/debug CLI

**Comment by TylerJewell** [comment]
I believe we have two separate improvements to solve.
1. If you mount `:/repo`, then we should also use scripts from `dockerfiles/base` and not use the scripts that are contained within the image.
2. Add extra nightly check to ensure that the version you have installed matches the pom.xml version. This check allows for those that are mounting `:/repo` for us to see if the version that is in the master repository is perhaps newer than the version that was contained in the nightly image and then print a warning message.  If your existing installation for your nightly image is `5.2.0-SNAPSHOT`, but the repository has moved to `5.3.0-SNAPSHOT` then this could lead to unintended consequences.

You can get the version from the repository with:
` cat /repo/pom.xml | grep "<version>.*</version>$" | awk -F'[><]' 'NR==1{print $3}'`

**Comment by TylerJewell** [comment]
I think I foudn a way to solve this issue.  I am now adding in the pom.xml version of the repository when `eclipse/che-base` is built and then compare that to the `:/repo` if it is mounted.

**Comment by bmicklea** [comment]
@garagatyi please add a `kind/bug`, `kind/task`, `kind/enhancement` or `kind/docs` label to every issue when you file it.

**Comment by TylerJewell** [comment]
@bmicklea - no that is not correct.  As Alex is just reporting behavior, it is for the engineer that owns the area to either confirm it as a bug or to think about it as an enhancement request.  Until that time, it's just a question.  This particular issue wasn't clear whether it was bug or just expected behavior until we had further conversations.

**Comment by bmicklea** [comment]
Then it should be labelled as `kind/question` my point was just that the person reporting the issue when they're a committer should add the label themselves rather than wait for issue triage to guess at it.

**Comment by TylerJewell** [comment]
We have solved this with a merge into master.  We now have the CLI do a hard check against its API versioning so that derivative CLIs have to match the base to avoid any issues in the future.
