### ISSUE TITLE
Improve UX of graceful shutdown error message

### ISSUE THREAD

**Issue by garagatyi** [codenvy/codenvy#1682]
After merging graceful shutdown feature I tried to shutdown codenvy as usual: `docker ... codenvy/cli:nightly stop`.
I got next error:
```ERROR: (codenvy action/graceful-stop): Call on rest url /api/system/state returned invalid response code (401) with error:User not authorized to call this method.```
It was not obvious how to handle that situations since I missed demo of it and its usage. CLI help say nothing about that. Looks like we don't provide any information about per-action options. And there was no information about graceful shutdown. BTW docs were not shipped yet.
Can we put there additional message on what should be provided and how to skip it, e.g. 
`Please add -user <admin username> -password <admin password> to gracefully shutdown server or --force to skip graceful shutdown`?

**Comment by TylerJewell** [comment]
1. We should not be including the action output into the CLI.
2. Probably should be routing any of those action messages into the logs.
3. The output should simply be `(codenvy stop): Stopping workspaces`
4. If there is an error, we should provide an error message in the CLI with pretty formatting and explanation.

**Comment by benoitf** [comment]
do we have priority for this issue ?

**Comment by TylerJewell** [comment]
Relatively soon-ish because I am not really a big fan of our end users seeing the output of the stop message.  I would have required this for 5.2 if I had seen the output.  But I didn't test it properly and missed  it.

**Comment by benoitf** [comment]
ok, timeframe to implement was quite short as API was only merged a couple of days before the release.

**Comment by TylerJewell** [comment]
Yeah - we did rush out the feature.  I didn't test it properly enough and we required it for the release.  Let's clean it up now.  There was nother bug filed just a few minutes ago.

**Comment by mshaposhnik** [comment]
I have proposal:  always skip graceful shutdown call result in development mode, e.g. dev mode = "--force" to make  developer life a bit easier. Sometimes we have our api war broken and cannot shutdown then, have to stop all containers manually.

**Comment by benoitf** [comment]
Fixed by https://github.com/eclipse/che/pull/4064
