### ISSUE TITLE
Improve team selector to better handle situations where many teams exist

### ISSUE THREAD

**Issue by vitaliy-guliy** [codenvy/codenvy#1686]
Current version of team selection look not good and does not allow to select more than one team.

![team buttons](https://cloud.githubusercontent.com/assets/1655894/22589255/102503c4-ea12-11e6-9e93-dfe2d8f2f677.png)

**Comment by slemeur** [comment]
It's fine for the time being, but having all the teams on multiple rows does not provide an easy way to find and select a team. 

We'll need to improve this and provide a selector using a popover (with search and list similar to selecting project to import here: https://github.com/eclipse/che/issues/3515#issuecomment-269182360)

**Comment by eivantsov** [comment]
@slemeur is this still a good enhancement?

**Comment by ashumilova** [comment]
![image](https://user-images.githubusercontent.com/1611939/28275806-b02ce7ce-6b1d-11e7-851e-62b075281bb6.png)
Fixed
