### ISSUE TITLE
Strange behavior when user is not authorized

### ISSUE THREAD

**Issue by vitaliy-guliy** [codenvy/codenvy#1688]
Dashboard does not redirect to the login page when the user session is expired.

![user is not authorized](https://cloud.githubusercontent.com/assets/1655894/22590312/3ff9c710-ea17-11e6-8448-bc371b233972.gif)

**Comment by sleshchenko** [comment]
Your session is valid. Looks like steps to reproducing are following:
1. Create team.
2. Add any other admin there.
3. Remove himself from team.
3. Try to open this team directly by URL {host}/dashboard/#team/{teamName}.

Then team exists but you don't have permissions to open it by Dashboard.
Dashboard should handle it correctly.

Another issue - looks like we should allow to see team, manage workspace and members to Team owner, even when he doesn't have permissions in this team

**Comment by sleshchenko** [comment]
Also I've checked database on a1 instance and there is no any member in adminTeam1. So API doesn't allow to remove last member with `setPermissions` action. Looks like there is issue with concurrency.

**Comment by sleshchenko** [comment]
When user tries to open team where he is not a member he'll following page
![image](https://cloud.githubusercontent.com/assets/5887312/24137487/a7200778-0e1c-11e7-8907-f82f6dee435c.png)
