### ISSUE TITLE
Error when trying to create workspace from old images

### ISSUE THREAD

**Issue by olexii4** [codenvy/codenvy#1697]
**Reproduction Steps:**
1. Open dashboard/workspaces. Add a new workspace from custom recipe
"FROM exoplatform/che"
2. Save and run it.
![selection_027](https://cloud.githubusercontent.com/assets/6310786/22597404/27646a5e-ea38-11e6-9b03-0b120c768777.png)
Restoring workspace error. It was not produced in CHE (5.3.0-SNAPSHOT).

**Codenvy version:**    
https://nightly.codenvy-stg.com  (5.3.0-SNAPSHOT)
https://codenvy.io (5.2.1)

**OS and version:**    
Ubuntu 15.10 wily
Google Chrome 55.0.2883.87 

![selection_023](https://cloud.githubusercontent.com/assets/6310786/22645972/8f82f556-ec72-11e6-94ca-b67fe518fd99.png)

**Comment by olexii4** [comment]
As far as I know in CHE we mount image directly. That is why we haven't  any problems.
In  case with Codenvy we use https://github.com/codenvy/codenvy/blob/26570ed62d11c273f0de1d0249e546f12e4ba299/dockerfiles/init/modules/codenvy/templates/rsyncrestore.sh.erb
for restore an image in workspace. Some time ago it's algorithm was  simplified.
I guess we have some problem with new algoritm and some packages in old images.  We need more research for this issue.

**Comment by eivantsov** [comment]
It happens because a user in eXo image is not only passwordless but also has a disabled login.

Adding the following to the recipe will help:

`RUN sudo usermod -p "*" exo`

**Comment by garagatyi** [comment]
@eivantsov @TylerJewell I think the reason of failure is clear. Can we close this issue?

**Comment by eivantsov** [comment]
Yes, we have strict requirements for a dev machine - it shoudl be built from an image where a user allows ssh connection/login.
