### ISSUE TITLE
Can not reset password

### ISSUE THREAD

**Issue by AaronZhangL** [codenvy/codenvy#1700]
I can not reset my password in below page.
https://codenvy.io/site/recover-password

![image](https://cloud.githubusercontent.com/assets/3395362/22619408/7264d610-eb37-11e6-9d63-37ccca62183c.png)

**Comment by TylerJewell** [comment]
Yes - this is a known issue.  A fix is being worked on and we will have a push made live shortly.  Sorry about the inconvenience.  You can email support@codenvy.com in the mean time for help.
