### ISSUE TITLE
CLI graceful stop does not work

### ISSUE THREAD

**Issue by riuvshin** [codenvy/codenvy#1708]
graceful stop with CLI does failed on environments with https.
normal CLI output looks like (local codenvy on 80 port):
```
INFO: (codenvy action/graceful-stop): Authenticating as admin on "192.168.65.2:80".
INFO: (codenvy action/graceful-stop): System going into status 'PREPARING_TO_SHUTDOWN' (was 'RUNNING')
INFO: (codenvy action/graceful-stop): Success: system is now in status 'READY_TO_SHUTDOWN'.
INFO: (codenvy stop): Stopping containers...
```

in our case wit https output was:

```
INFO: (codenvy action/graceful-stop): Authenticating as root-prod on "172.30.11.4:80".
INFO: (codenvy stop): Stopping containers...
INFO: (codenvy stop): Removing containers...
```

there is 2 issues 
1) instead of `codenvy.io` it wants to do auth on intenral IP
2) hardcoded port 80 does not work here because port is 443. we must remove all hardcoded `:80` ports from cli we should always go to `HOST_URL`

@TylerJewell @benoitf please take a look on that

**Comment by benoitf** [comment]
AFAIK for me it's normal that the container try to login through internal IP as it's inside the docker container

**Comment by riuvshin** [comment]
@benoitf maybe but the issue is that we may move haproxy to another node in case of high load and  then it will fail to do auth. it should use what is in codenvy.env defined as a host url

**Comment by riuvshin** [comment]
@benoitf btw `--url=https://codenvy-stg.com` that you've suggested works

```
INFO: (codenvy action/graceful-stop): Authenticating as admin on "codenvy-stg.com:443" using SSL.
INFO: (codenvy action/graceful-stop): System going into status 'PREPARING_TO_SHUTDOWN' (was 'RUNNING')
INFO: (codenvy action/graceful-stop): Success: system is now in status 'READY_TO_SHUTDOWN'.
```

**Comment by benoitf** [comment]
yes but it's a workaround

**Comment by riuvshin** [comment]
sure this is workaround, CLI must do this automatically.

**Comment by JamesDrummond** [comment]
@benoitf Will you be taking this next sprint?

**Comment by JamesDrummond** [comment]
Is this still an issue?
