### ISSUE TITLE
Conflict with permissions

### ISSUE THREAD

**Issue by vitaliy-guliy** [codenvy/codenvy#1709]
There is an extra switcher to remove a member role from a user in a team.

![extra switcher](https://cloud.githubusercontent.com/assets/1655894/22650800/5e3cc3ca-ec89-11e6-84cf-b3872c8e1cac.png)

After turning on `Team Admin`, turning off `Team Member` switchers and clicking `Add` button user become `Team Admin` and not `Team Member`.

![only admin role](https://cloud.githubusercontent.com/assets/1655894/22651537/0d725ba0-ec8c-11e6-90f0-62dfa451e1f3.png)

That's strange how the user can be admin and not a member.

Having `Team Admin` role means the user can edit the team settings, manage workspaces, resources and members.
Then go to `Workspaces` section and click `Add Workspace`. We get `New Workspace` section is opened but team name is not selected. Then select corresponding team name, click `Save` button and get the following.

![unable to create workspace](https://cloud.githubusercontent.com/assets/1655894/22651056/4e066c26-ec8a-11e6-8c55-13daff8f686b.png)

And also it's unable to edit team settings.

![team settings](https://cloud.githubusercontent.com/assets/1655894/22651937/36c578ec-ec8d-11e6-818c-11735a4371c9.png)

**Comment by ashumilova** [comment]
https://github.com/codenvy/codenvy/commit/3f67a5f0202b0ba92ec5a8ed93a1904057660b16
