### ISSUE TITLE
Should be able to remove CAP or set it to 0

### ISSUE THREAD

**Issue by vitaliy-guliy** [codenvy/codenvy#1710]
Dashboard doesn't store revomed CAP and CAP that is equals to 0

![anim](https://cloud.githubusercontent.com/assets/5887312/23499660/ac833a1e-ff35-11e6-9aec-f08af01415af.gif)

**Comment by vitaliy-guliy** [comment]
I get another error when enter -1

![should be greater than 0](https://cloud.githubusercontent.com/assets/1655894/22653658/c67b09c0-ec92-11e6-9e4d-2bf277318d86.png)

**Comment by slemeur** [comment]
Will be fixed by https://github.com/codenvy/saas/issues/150
