### ISSUE TITLE
User with manageSystem permission can't delete or add Predefined Stack

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#1711]
For https://github.com/codenvy/codenvy/issues/1656 I tried to delete stack via swagger and got 403 error.
Looks like predefined stacks has no permission set that allow to manage them.

We need to have ability to delete or add Predefined stacks.
Either give the user with manageSystem permission ability to bypass permisions on Predefined stacks or set permissions for Predefined stacks that allow someone to manage them

**Reproduction Steps:**

Try to delete predefined stack.

**Codenvy version:**    5.2.2

**OS and version:**    Centos 7.2

**Docker version:** 1.12.5

**Comment by mmorhun** [comment]
Here we are going to implement edit and deletion of predefined stacks.
According to some internal stuffs addition of predefined stacks will be implemented in [this](https://github.com/codenvy/codenvy/issues/1780) issue.

**Comment by mmorhun** [comment]
done
