### ISSUE TITLE
Improve Developers section

### ISSUE THREAD

**Issue by vitaliy-guliy** [codenvy/codenvy#1715]
To not confuse the user we have to improve Team Developers section.

Considering team has developers and administrators we have to rename `Developers` section to `Members`. Rename `Add Developer` button to `Add Member` because it's used to add developers and administrators. And also to have everything clear we have to rename roles `Team Member` to `Developer` and `Team Admin` to `Admin`.

![team members](https://cloud.githubusercontent.com/assets/1655894/22686642/84719558-ed2d-11e6-9805-3e54972553b1.png)

**Comment by slemeur** [comment]
Ok for me

**Comment by ashumilova** [comment]
https://github.com/codenvy/codenvy/commit/3f67a5f0202b0ba92ec5a8ed93a1904057660b16
