### ISSUE TITLE
Codenvy Agile Plugin for JIRA support for JIRA 7.3.x

### ISSUE THREAD

**Issue by asthomasdk** [codenvy/codenvy#1717]
When will a version of the Codenvy Agile Plugin for JIRA be avialable for JIRA 7.3.x ? 

Searching for the add-on from JIRA at the moment does not give any results because the latest version has JIRA version 7.1 as the highest supported version. 

This is using JIRA Software Server - local install, not the cloud version. 

**Reproduction Steps:**

**Codenvy version:**   5.2.2

**Comment by bmicklea** [comment]
@asthomasdk - we have this in our backlog, but it's not in the current sprint. The team that works on the plugin is quite small and there are a number of other items they need to address first. Are you using JIRA on-prem or in the cloud?

**Comment by asthomasdk** [comment]
Not a problem. 

We are using JIRA Software Server - on premise. Actually in Docker ;-)

**Comment by bmicklea** [comment]
@asthomasdk just a quick update - we've just pushed our latest plugin which has been tested with 7.2. We think it will work with 7.3 as well so if you're feeling adventurous you can try to install it with a 7.3 system and integrate it with Codenvy using [these instructions](https://codenvy.com/docs/integration-guide/issue-management/index.html).

**Comment by asthomasdk** [comment]
Great - I will give that a go.

**Comment by asthomasdk** [comment]
I am afraid the install fails from the start with "An unexpected error occurred.." - and when I refresh, I get an incompatibility error. 

I download the .jar file directly from the Atlassian Marketplace and the upload it manually - as it does not show up in the list of compatible add-ons for our JIRA instance.

**Comment by eivantsov** [comment]
@asthomasdk I started Jira 7.3.1 as a Docker container, and this is what I got when uploading plugin jar:

![image](https://cloud.githubusercontent.com/assets/5337267/23123832/bc956f78-f772-11e6-855f-55a8eb9485f3.png)

![image](https://cloud.githubusercontent.com/assets/5337267/23124044/986dbd3e-f773-11e6-9546-e0d3bb1e7efa.png)

The plugin is compatible with 7.3.x.

To debug your issue, please provide logs.

**Comment by eivantsov** [comment]
Closing the issue due to inactivity. @asthomasdk feel free to reopen if the issue persists.

**Comment by asthomasdk** [comment]
No problem. I have not had a complete my testing - but will let you know if I run into issues.
