### ISSUE TITLE
Improve renaming a team

### ISSUE THREAD

**Issue by vitaliy-guliy** [codenvy/codenvy#1719]
For now team is renamed by timeout when typing a new name.

It would be better to rename a team when pressing Enter key or losing the focus and restore the old value when pressing Escape.

Also we have to add a tool tip to the red star to explain the user the field is mandatory.

![rename a team](https://cloud.githubusercontent.com/assets/1655894/22693024/3e3525a6-ed4a-11e6-959c-4fe949709373.png)

It should be explained what are the special characters. A space character is not mentioned somewhere but can not be used for team name.

![special characters](https://cloud.githubusercontent.com/assets/1655894/22693917/e5b399a4-ed4d-11e6-930f-5741bef3ba61.png)

**Comment by slemeur** [comment]
we would need to handle that the same way we are handling changes in the workspace details' screen. With the "save"/"cancel" bar that we are displaying at the bottom

**Comment by ashumilova** [comment]
Fixed by https://github.com/codenvy/codenvy/commit/f5310e71de788d7a5438265ef3425d953e863f3b
