### ISSUE TITLE
Unable to start workspace when RAM Cap is unlimited

### ISSUE THREAD

**Issue by vitaliy-guliy** [codenvy/codenvy#1720]
It's unable to start a workspace when the `Workspace RAM Cap` is not defined.
In this case a text `Workspace RAM has not been limited` is writted in `Workspace RAM Cap` field.

![unlimited ram](https://cloud.githubusercontent.com/assets/1655894/22695483/9793c446-ed53-11e6-9483-44f377c0e900.png)

But wokspace doesn't want to be started and an error message is appeared.

![unable to start workspace](https://cloud.githubusercontent.com/assets/1655894/22695645/1b74ee5c-ed54-11e6-9b8a-3a3f09597168.png)

**Comment by slemeur** [comment]
Fixed.
