### ISSUE TITLE
CLI fails in dev mode (regression)

### ISSUE THREAD

**Issue by riuvshin** [codenvy/codenvy#1736]
devs reported that codenvy CLI fails with mounted `:/repo`

error is:

```
ERROR: for agents  Cannot start service agents: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/Users/roman/development/codenvy_projects/.codenvy/instance/dev/ws-agent.tar.gz\\\" to rootfs \\\"/var/lib/docker/overlay2/f5f29f24d85d0eec60acd1fb195978440d8440a1a652726dd9eec65174d6efd9/merged\\\" at \\\"/var/lib/docker/overlay2/f5f29f24d85d0eec60acd1fb195978440d8440a1a652726dd9eec65174d6efd9/merged/data/ws-agent.tar.gz\\\" caused \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
Encountered errors while bringing up the project.
ERROR: Error during 'compose up' - printing 30 line tail of /Users/roman/development/codenvy_projects/.codenvy/cli.log:
```

I did investigation on this and figured out that this happens because in codenvy CLI when we doing `start` command [cmd_config_post_action()](https://github.com/codenvy/codenvy/blob/master/dockerfiles/cli/scripts/cmd_config.sh#L10)  is never executed where we prepare ws agent dev binary tobe mounted to container.

what is interesting that if I do `config` command instead of `start`  [cmd_config_post_action()](https://github.com/codenvy/codenvy/blob/master/dockerfiles/cli/scripts/cmd_config.sh#L10) is executed and `ws-agent.tar.gz` showed up in place.

I believe that this regression happend after @TylerJewell intorduced refactoring https://github.com/eclipse/che/commit/8287fb66d32e8983b8b238609efa1d84c0d30daa#diff-d0e0b1718a2a59b3614cc764a8dc23feL78

**Comment by TylerJewell** [comment]
@riuvshin @skabashnyuk - I think there has been some significant refactoring of the Codenvy repository.  I went into Codenvy repository to build the `allinone` module, but it no longer exists.  It now looks a bit more like the Che assembly folder hierarchy.  So this would be the root cause of the error.  I don't think this is a cause of the CLI refactoring, as much as a refactoring of the assembly folder without a proper matching PR for the CLI.

**Comment by riuvshin** [comment]
@TylerJewell me (again!!!) and most devs  who using CLI still have this issue 

I did same thing as we did with you. wipeout everything > build base > build cli 
it is there again. I think we should think about back to previous way of scrits loading maybe it was a bit slower but it was predictable working now we have this weird issue which magically appear and some times disappear.
:(

**Comment by TylerJewell** [comment]
Reverting poses all sorts of problems.  This isn't just about speed it was about maintainabikity and to huger the help messages.  Need to diagnose this further.

**Comment by riuvshin** [comment]
agree let's do more diagnose

**Comment by TylerJewell** [comment]
This should fix this problem permanently.  It was related to recursive functions and global variables.  https://github.com/eclipse/che/pull/4083/
