### ISSUE TITLE
Do not make additional http request on each license check in SystemLicenseLoginFilter

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#1739]
Making additional http request on each license check in SystemLicenseLoginFilter is very slow. Please use some smart logic to reduce time of license checking

**Comment by skabashnyuk** [comment]
P1 blocker critical. Since it' double time of each request and made huge performance lost.

**Comment by dmytro-ndp** [comment]
@skabashnyuk: You set **status/blocker** for this issue. Could you, please, explain which function of Codenvy it blocks (that is makes as inaccessible)?

**Comment by skabashnyuk** [comment]
The function is our performance. Making for almost each http request additional http request that sometimes (not sure is it always or not ) make query to database   - is unacceptable solution.

**Comment by dmytro-ndp** [comment]
Our selenium tests demonstrates almost the same performance for Che (without licensing) and Codenvy (with licensing):
- [4h 2 minutes for 326 tests for Che](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/213/);
- [4h 10 minutes for 360 tests for Codenvy](https://ci.codenvycorp.com/view/qa/job/nightly-onprem-selenium-tests/265/).

IMHO, it disapproves assumption that current implementation of licensing leads to huge performance lost.

**Comment by skabashnyuk** [comment]
@dmytro-ndp  you comparing hot and round. 
Can you give me result of simple http request. For instance ```-X OPTIONS /api``` or ```GET /api/user``` with and without license check?
How many times did we make DB query ```select count(id) from user``` ? when loading ide or dashboard. What for? Do we really need that?

**Comment by dmytro-ndp** [comment]
> Can you give me result of simple http request. For instance -X OPTIONS /api or GET /api/user with and without license check?

I could check it. But, such kind of testing should precede conclusion about huge impact on performance.

> How many times did we make DB query select count(id) from user ? when loading ide or dashboard. What for? Do we really need that?

Requesting number of registered users is needed to protect our product from illegal usage: when this number reaches or exceeds allowed limit defined by license, and so stimulate users to pay for usage.

We do it on ~every requests so as new user can be registered at any time.

**Comment by skabashnyuk** [comment]
Thx @dmytro-ndp

**Comment by dmytro-ndp** [comment]
@skabashnyuk: you are welcome :-)

Also, we check license on ~every requests which require login to Codenvy so as we doesn't allow users to login when _Fair Source License_ doesn't accepted by admin.

**Comment by skabashnyuk** [comment]
Thx @dmytro-ndp

**Comment by dmytro-ndp** [comment]
Welcome, @skabashnyuk :-)

**Comment by dmytro-ndp** [comment]
By the way, as far as I know, our JPA implementation uses cache at the database level. So, repetitive requests to database shouldn't be the problem.

**Comment by dmytro-ndp** [comment]
@sleshchenko proposed to use event-listener model to work around HTTP requests cache, where events kind of "**fair-source-license-accepted**" will lead to clean up of cache for requests to **api/license/system/legality** service.
It allows us to update system license status just in time, when change occurred.

**Comment by dmytro-ndp** [comment]
There were ~ 3000 requests to **SystemLicenseLoginFilter** in log during the half an hour of outage ща codenvy.io https://github.com/codenvy/infrastructure/issues/76

**Comment by TylerJewell** [comment]
Ouch


Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by mmorhun** [comment]
done
