### ISSUE TITLE
Move classes related to permissions checking to shared modules

### ISSUE THREAD

**Issue by sleshchenko** [codenvy/codenvy#1740]
Move following constants SystemDomain#DOMAIN_ID, SystemDomain#MANAGE_SYSTEM_ACTION AbstractPermissionsDomain#SET_PERMISSIONS out of codenvy-hosted-api-permissions because they is used in few war archives but only ws-master war should depend on codenvy-hosted-api-permissions.

Also it is need to move out of codenvy-hosted-authorization implementation of PermissionsChecker(PermissionsCheckerImpl and HttpPermissionsChecker) to avoid dependency on codenvy-hosted-api-permissions in each war.

**Comment by bmicklea** [comment]
@sleshchenko please add a `kind/...` label to each issue when you create it. I've taken a guess here but you should correct it if I'm wrong.
