### ISSUE TITLE
On fresh Android Stack workspace maven won't work

### ISSUE THREAD

**Issue by kragil** [codenvy/codenvy#1743]
mvn clean install -f /projects/mobile-android-simple
/bin/bash: mvn: command not found

New Workspace > Android
Wait
Build 
/bin/bash: mvn: command not found

**Codenvy version:Nothing in the dashboard**    

**Fedora 25**

**Comment by eivantsov** [comment]
I have updated the image. Can you give it another go?

**Comment by kragil** [comment]
Thanks. Sure. On it.

**Comment by kragil** [comment]
Maven seems to work now! Thanks a lot! Great support!
