### ISSUE TITLE
Maven should inherit JAVA OPTS to be able to use proxy settings

### ISSUE THREAD

**Issue by eivantsov** [codenvy/codenvy#1750]
This approach works only when a user enters a shell: https://github.com/eclipse/che-dockerfiles/blob/master/recipes/ubuntu_jdk8/Dockerfile#L17

We cannot do it in a Dockerfile as ENV since JAVA_OPTS are added to a container when it is created.

There should be a mechanism for Maven to use system proxy settings or inherit JAVA_OPTS.

**Comment by bmicklea** [comment]
Which team would need to fix this?  Is this IDE or Enterprise or Platform?

**Comment by eivantsov** [comment]
Definitely not IDE.

**Comment by evoevodin** [comment]
Fixed by https://github.com/eclipse/che/pull/4119
