### ISSUE TITLE
How do I deploy a PHP app to GAE?

### ISSUE THREAD

**Issue by chrisjj** [codenvy/codenvy#1751]
Support said:

The new Codenvy does not have GAE plugin but you will be able to use GAE SDK natively - https://eclipse-che.readme.io/docs/che-and-gae

but that link gives

https://eclipse-che.readme.io/inactive
"Not yet active"

**Comment by TylerJewell** [comment]
We just moved all of our docs over to eclipse.org/che.  Can you let us know where you got the source link?  We have been working to try and get Google to update all of its search references, but it's taking time.  If someone (or something) gave you that readme.io link, it's outdated and we need to work to remove it.  Thx.

What you needed - https://www.eclipse.org/che/docs/tutorials/gae/index.html

**Comment by chrisjj** [comment]
> We just moved all of our docs over to eclipse.org/che.

And forgot to redirect??

> Can you let us know where you got the source link?

Codenvy Support email, Nov 2016.

> What you needed - https://www.eclipse.org/che/docs/tutorials/gae/index.html

Thanks.

**Comment by TylerJewell** [comment]
Unfortunately, our docs provider - readme.io - does not offfer redirects among other things.  This is why we now self host our docs and build them off of Jekyll.  I think it may be a good idea for us to go through the last six months of blog posts to update any links to readme within those posts.  Thanks for letting us know.
