### ISSUE TITLE
Trouble accessing services on ports 

### ISSUE THREAD

**Issue by themcclure** [codenvy/codenvy#1752]
I am using the hosted codenvy.io and I created a workspace to test some python and web frameworks.
I am following along a simple tutorial - but I am launching the server but I can't access the web site it's serving.

**Reproduction Steps:**

1. Follow the instructions to create a workspace with port 5050 exposed by adding the line in the server config screen:
![screenshot 2017-02-10 00 08 50](https://cloud.githubusercontent.com/assets/13382574/22819320/6eb04494-ef26-11e6-88dc-5f182b410b59.png)

2. [Basic Firebase tutorial](https://codelabs.developers.google.com/codelabs/firebase-web)

3. When you get to the step where you launch the firebase server (on port 5050) it doesn't matter if I launch it from the Run menu or from the terminal directly, I can't access it using the Preview URL!
![screenshot 2017-02-10 00 12 37](https://cloud.githubusercontent.com/assets/13382574/22819296/53bbe058-ef26-11e6-98bc-268caa5d10e2.png)

My browser gives me this error:
![screenshot 2017-02-10 00 18 58](https://cloud.githubusercontent.com/assets/13382574/22819379/b63662d0-ef26-11e6-952c-7dfde8b5c731.png)

I know that the service is running because in a second terminal window I can use lynx to browse to http://localhost:5050 and interact with the web site.

I have looking through these issues, I have googled for solutions and I have found the documentation to be disjointed and a little out of date in places - especially around exposing ports.

I'm really hoping there's just a step missing to expose the port to the outside - please help!

Thanks in advance.

**Codenvy version:**    5.2.2 (hosted)

**OS and version:**    OS/X & Chrome browser

**Comment by eivantsov** [comment]
@themcclure do you have troubles with previewing our sample projects? I suspect you may have issues wit the ephemeral port range.

**Comment by themcclure** [comment]
Thanks - I forgot to add that I did try a couple of the sample projects. Definitely the Node.js Hello World and that worked fine!

I'll try something more complex as well - but at least one success suggests that the NATing is working from one source but not another.

**Comment by eivantsov** [comment]
@themcclure one thing that you may want to try is to unbind the server from localhost. I am not familiat with firebase, but for instance when launching GAE apps, one has to set host as 0.0.0.0

**Comment by themcclure** [comment]
We have a winner!

Thanks!

firebase --host 0.0.0.0 --port 5050
