### ISSUE TITLE
Codenvy not binding to https

### ISSUE THREAD

**Issue by lynxloco** [codenvy/codenvy#1754]
Codenvy not binding to https

**Reproduction Steps:**
Point codenvy.env to certificates, run codenvy docker start command, codenvy still binds to http.
**Codenvy version:**

5.2.2

**OS and version:**    
Ubuntu 16.04
**Docker version:**
1.13.1 both
**Codenvy cli.log output:**  

docker inspect -f '{{.Id}}' codenvy_codenvy_1
/usr/bin/curl  "-I -k 192.168.2.211/api/ -s -o /dev/null --write-out %{http_code}"
200
Fri Feb 10 08:15:41 UTC 2017
/usr/bin/curl  "-I -k dockerhub.com -s -o /dev/null --write-out %{http_code}"
Checking registry for version '5.2.2' images
eval BOOTSTRAP_IMAGE_ALPINE=alpine:3.4
eval BOOTSTRAP_IMAGE_CHEIP=eclipse/che-ip:5.2.2
eval IMAGE_HAPROXY=haproxy:1.5.18-alpine
eval IMAGE_NGINX=nginx:1.10-alpine
eval IMAGE_SWARM=swarm:1.2.6
eval IMAGE_REGISTRY=registry:2.5.0
eval IMAGE_POSTGRES=postgres:9.5.4
eval IMAGE_COMPOSE=docker/compose:1.8.1
eval IMAGE_ZOOKEEPER=zookeeper:3.4.9
eval IMAGE_SOCAT=codenvy/socat:5.2.2
eval IMAGE_INIT=codenvy/init:5.2.2
eval IMAGE_AGENTS=codenvy/agents:5.2.2
eval IMAGE_CODENVY=codenvy/codenvy:5.2.2
eval IMAGE_RSYSLOG=codenvy/rsyslog:5.2.2
eval UTILITY_IMAGE_CHEACTION=eclipse/che-action:5.2.2
eval UTILITY_IMAGE_CHEDIR=eclipse/che-dir:5.2.2
eval UTILITY_IMAGE_CHETEST=eclipse/che-test:5.2.2
eval UTILITY_IMAGE_CHEMOUNT=eclipse/che-mount:5.2.2
INFO: (codenvy cli):  5.2.2 - using docker 1.13.1 / native
WARN: CODENVY_HOST (192.168.2.211) overridden by codenvy.env (codenvy.domain.com)
/usr/bin/curl  "-s https://hub.docker.com/v2/repositories/codenvy/cli/tags/"
DEBUG: cli_parse
DEBUG: cmd_start
docker inspect -f '{{.Id}}' codenvy_codenvy_1
/usr/bin/curl  "-I -k 192.168.2.211/api/ -s -o /dev/null --write-out %{http_code}"
200
INFO: (codenvy start):  Booted and reachable
INFO: (codenvy start):  Ver: 5.2.2
INFO: (codenvy start):  Use: http://codenvy.domain.com:80
INFO: (codenvy start):  API: http://codenvy.domain.com:80/swagger
docker inspect -f '{{.Id}}' codenvy_codenvy_1
/usr/bin/curl  "-I -k 192.168.2.211/api/ -s -o /dev/null --write-out %{http_code}"
200

**Comment by eivantsov** [comment]
@lynxloco have you changed CODENVY_HOST_PROTOCOL=https in the .env file?

**Comment by lynxloco** [comment]
@eivantsov Most certainly, it almost seems as if it ignores https settings entirely.

**Comment by eivantsov** [comment]
Did you run start or restart command?

**Comment by lynxloco** [comment]
Start, yes, restart errors with `ERROR: (codenvy action/graceful-stop): Call on rest url /api/system/state returned invalid response code (401) with error:User not authorized to call this method.`

**Comment by eivantsov** [comment]
@lynxloco 

`docker rm -f $(docker ps -aq)`

Then start normally

**Comment by lynxloco** [comment]
That worked but still no ball. Still port 80.

**Comment by eivantsov** [comment]
Can you share your codenvy.env or the entire data directory as zip?

**Comment by lynxloco** [comment]
I don't know why but if I try to upload my zip it says it's not supported as a filetype.

**Comment by eivantsov** [comment]
Upload it elsewhere. Logs will help us help you.

**Comment by lynxloco** [comment]
http://pastebin.com/XjWUT1hS

**Comment by eivantsov** [comment]
@lynxloco when I try switching to https and provide no cert, Codenvy isn't available both http and https. In your case it does not switch at all? Is that correct?

**Comment by lynxloco** [comment]
No that is not the problem, in both cases is it the same domain name, I can guarantee that.

**Comment by eivantsov** [comment]
Are you certain you haven't mounted :/data into two different host locations? I have double checked it on my side and all changes are immediately applied after restart.

**Comment by lynxloco** [comment]
`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /data:/data codenvy/cli start` 
That's the code I use to start. Where can I check if :/data is mount on more places?

**Comment by eivantsov** [comment]
OK, remove everything you have in `/data` on your host.

`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /data:/data -e codenvy/cli init`

In `/data/codenvy.env` uncomment and edit HTTPS related envs. Make sure you provide the right path to your cert file. In your codenvy.env you have an example value....

Once the file is saved, run:

`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /data:/data -e codenvy/cli start`

**Comment by lynxloco** [comment]
`Unable to find image 'init:latest' locally
docker: Error response from daemon: repository init not found: does not exist or no pull access.` Any clues?

**Comment by eivantsov** [comment]
Sorry, I have updated the command. There was a typo.

**Comment by lynxloco** [comment]
Now I get a completely different error `HTTP Status 500 - org.eclipse.che.api.core.ServerException: Internal Server Error occurred, error time: 2017-02-10 15:10:45`.

**Comment by eivantsov** [comment]
@lynxloco it is very difficult to tell you what's wrong having just one line from logs. Can you elaborate on when this exception occurred, what steps did you take etc?

**Comment by lynxloco** [comment]
Now I can't connect at all, apparently it was just a temporary error. Is it possibly a certificate error or something? What is the format that the certificate should be?

**Comment by lynxloco** [comment]
It is supposed to say  `INFO: (codenvy start): Use: https://codenvy.example.com:443
INFO: (codenvy start): API: https://codenvy.example.com:443/swagger` when ssl is enabled right?

**Comment by eivantsov** [comment]
When ssl is enabled and properly configured.

It won't work with self signed certs or the ones that you may get at startssl and similar cervices since Java does not trust them and you have to manually add them to Java trust store (we have not implemented it yet). So, it has to be a paid certificate that Java will be OK with.

Again, without logs and details from your side it is very difficult to say what is going on.

**Comment by lynxloco** [comment]
What logs should I provide then? It's truly poorly documented what format the ssl certificate should be.

**Comment by eivantsov** [comment]
Your /instance directory. Can you zip it and share?

**Comment by eivantsov** [comment]
As to format, this should be `.pem` file with certificate, key and intermediate certificates.

Again, this certificate has to be issues by a trusted issuer.

**Comment by TylerJewell** [comment]
@lynxloco - I wrote the original Codenvy HTTPS docs and wasn't aware that we had limitations on the certificate issuer. Agree that the docs were missing this and just added them in as a PR.

**Comment by lynxloco** [comment]
https://expirebox.com/download/a5249ff04ecd0eb20e5cda1519a106e9.html

**Comment by eivantsov** [comment]
expirebox.com does not resolve for me.

You may email the archive to support(at)codenvy.com

**Comment by lynxloco** [comment]
The problem was permissions for my certificate.

**Comment by asthomasdk** [comment]
@lynxloco - what exactly were the permissions settings you needed for your certificate to get this to work? 

I am trying to use a letsencrypt generated certificate (where I have concatenated the generated .pem and key files to create a file that I _have_ had working) - and for some reason it is being ignored - and I suspect it may be the codenvy containers not being able to see it.

**Comment by lynxloco** [comment]
I tried 777'ing the letsencrypt files and that worked, but in the end what I did is because I'm using esxi on a server is just moving it to a dedicated VM and proxying it to a different VM with nginx, and applying the ssl certificates there. And that seemed to work the best, but I do realise that is not an option for everyone.

**Comment by asthomasdk** [comment]
In case anyone else is trying this - I managed to get this to work by making sure that the directory and .pem files were owned by the `rancher`user (using RancherOS). 

I did the same for the hosts data directory structure to be on the safe side. 

Starting codenvy with the .pem file location in the codenvy.env file now works - and everything looks fine to start with. 

However, as has also been mentioned, the letsencrypt certs are not accepted by the internal java stack for codenvy/che - so trying to test a new stack I am building is failing because the SSL cert cannot be accepted...

**Comment by eivantsov** [comment]
@asthomasdk yes, certs have to be from a trusted issuer. Well, building a mechanism of adding them to Java trust store is a matter of priority.

@TylerJewell may decide

**Comment by asthomasdk** [comment]
Thanks @eivantsov! 

Do you have any manual instructions for how to add a cert to the java trusted store now? I am happy to try it out if you do - as I am sort of stuck right now. 

I suppose I can always disable HTTPS until you have this fixed if this is not possible at the moment. it does limit our use cases for Codenvy as ti is right now though.

**Comment by asthomasdk** [comment]
BTW - is there a separate issue for adding the certs to the Java trusted store? Or do we need one created?

**Comment by eivantsov** [comment]
@asthomasdk the problem is that you can manually move the cert to container and add it to Java trust store but as soon as you restart a container everything's gone.

**Comment by TylerJewell** [comment]
@asthomasdk - can you elaborate a little bit on how the certificates you need to insert into the Java trust store are different from the ones referenced in the codenvy.env file?  If the *same* .pem file is needed in multiple locations, then perhaps this is an issue for the configuration system such that we need to take any user-provided *.pem files and volume mount them into the right Codenvy servers with the JVM.  

If there is an improvement here, we probably need to be more explicit on what it is and then open a new tocket on it.

@riuvshin - this may be for you + I to work on.

**Comment by asthomasdk** [comment]
@TylerJewell - the .pem file I am using is only referenced in the codenvy.env file. 

As far as I can work out, all I need to do is add the full path of a file that haproxy accepts, and this then gets volume mounted into the haproxy container  - correct? 

The .pem file I have is created using the Letsencrypt certbot tool and is therefore issued by letsencrypt. 

From what I can see from the issue I had earlier, whatever java version you are using, does not accept LE certs - although I thought that had actually been updated everywhere as of a few months ago. I have not checked if this is actually the case or not - but assumed I could update the java trusted store to recognize my cert. Something I think we did on some of our servers early last year when we were using LE certs and they were not accepted everywhere.  

So if you can update the trusted store to accept LE certs - then we are good from where I stand ;-) 

FYI - letsencrypt creates a cert.pem, fullchain.pem and privkey.pem - of which I then combine the last 2 into one .pem file for haproxy to accept it. See this for more details:  
https://www.digitalocean.com/community/tutorials/how-to-secure-haproxy-with-let-s-encrypt-on-ubuntu-14-04

**Comment by TylerJewell** [comment]
@asthomasdk - I think this needs to be moved into another issue.  We need @riuvshin or @skabashnyuk to offer an opinion on what this means for us.

**Comment by asthomasdk** [comment]
OK - I have logged a new issue for this: #1795
