### ISSUE TITLE
CLI litters host system with untagged images after each pull of nightly images

### ISSUE THREAD

**Issue by garagatyi** [codenvy/codenvy#1773]
Nightly tags change each night. When CLI pulls it each day docker removes tags from old images and they are left untouched until user decides to manually cleanup host system. 

**Reproduction Steps:**
1. Have yesterdays nightly images
2. call CLI start to let it pull new images.
3. Check with `docker images | grep none`

**Codenvy version:**    5.3.0-Snapshot

**OS and version:**    Ubuntu 16.04

**Docker version:** 1.12.5

**Comment by TylerJewell** [comment]
Why is this a bug? The CLI has an RMI method - I do not think it's the place of the CLI to clean up old images in this way.  It could lead to unepxected consequences.

**Comment by garagatyi** [comment]
Our cli pulls the images each day. So each day host gets several new images. And no one removes them. So in 30 days you get hundred images?

**Comment by TylerJewell** [comment]
Yep.  You are using nightly - which by definition is a development image, which doesn't guarantee any sort of mutability of your development environment.

If we managed images instead by digest, then we would be able to detect the digest of the current image and remove other images in a cleanup routine that do not match the digest list.  But this wasn't hte intention of the original design.

**Comment by garagatyi** [comment]
Well if no one is bothered with this I'm ok that you will close it

**Comment by benoitf** [comment]
We could keep old image digest before pulling new one and remove it after pulled new one

**Comment by TylerJewell** [comment]
If we did that - then I would save the image digest in the :/data folder, and couple it to the destroy method.  Though it would be super tricky to keep mutability.  This just doesn't feel like a very safe thing to do.

**Comment by garagatyi** [comment]
Why not just removing images that have the same names as codenvy images but doesn't have tag?

**Comment by TylerJewell** [comment]
Can you explain more - wouldn't they still have the same tag previously set?
Is there a simple 'docker rmi' syntax for these orphaned images?
When would you have this done - as part of the "rmi" command that we have, or different lifecycle.

**Comment by garagatyi** [comment]
![image](https://cloud.githubusercontent.com/assets/1851863/23096000/e7c6cb4e-f61c-11e6-9c07-557b53cbbcf9.png)

**Comment by garagatyi** [comment]
Second description is missing "Bad".

Our current images have tags nightly. Orphaned images don't have tags. It looks like you pulled image by digest. 
Since we don't use digests and use tags we can remove all images that belong to us but don't have tags.

**Comment by TylerJewell** [comment]
When would you expect that cleanup to run - at the natural end of the CLI execution, perhaps?  We could put it into the cleanup() method, which today only executes if an 'return 3' code.

**Comment by garagatyi** [comment]
If we call pull of nightly manually then the best place is right after pulling of each new nightly image

**Comment by TylerJewell** [comment]
That sequence would potentially miss images to clean.  We have not yet loaded the image manifest with the list of all the other images that we use at this point in time.  And if we clean up the cli image we should clean up the others too.

**Comment by garagatyi** [comment]
I don't remember cli algorithm enough to identify the best place for cleanup. 
Yes, other images should be cleaned up as well.
I meant that every pull of image with tag nightly can clean orphaned image. Not only cli image but each image we pull in cli workflow.

**Comment by TylerJewell** [comment]
We could only remove `eclipse/che-cli` orphaned images at that point.  But there would be a lot of other orphaned images. I think the only safe way to do this is to add in some cleanup into the cleanup() method.  At that point, the image manifest would have been loaded and similar to the offline() method, we can optionally remove all orphaned images.  It will slow the stopping of the CLI, but we will skip it if --fast.

**Comment by TylerJewell** [comment]
Added in a temporary fix - https://github.com/eclipse/che/pull/4179

**Comment by eivantsov** [comment]
@TylerJewell can we merge https://github.com/eclipse/che/pull/4179?

**Comment by TylerJewell** [comment]
No plans to merge that pr for awhile.  Docs on custom assemblies needs to be rewritten from ground up before we merge archetypes command into cli.
