### ISSUE TITLE
"Could not start workspace" - is my work gone?

### ISSUE THREAD

**Issue by wtfpcloadletter** [codenvy/codenvy#1776]
I was writing some code yesterday in a workspace that was probably open for an hour or so. I made some good progress, tried out the code and it worked as expected, so I started the process of pushing my local branch to my remote git repository. Suddenly I got an "Updating file..." dialog box on the screen and the IDE went unresponsive. I left it in the background for a while hoping it would resolve itself, but nothing. I gave up and went home for the day, and tried to reconnect when I got home and was greeted with this error message (note, I selected "Yes" to the prompt to recover the workspace from snapshot):

"Could not start workspace _nameofmyworkspace_. Reason: Start of environment 'default' failed. Error: Restore of workspace workspace7pq6ar000poa3zn6 failed. Another restore process of the same workspace is in progress"

Tried a few times last night and again this morning, still getting the same error. I checked other instances of this error found #1403 but that doesn't seem to apply since I don't have any rsync agents enabled. Also tried selecting "No" to the prompt to recover the workspace from snapshot, and get the same error message. I can start a new workspace and that works fine, but I was hoping that there was a snapshot of my workspace saved that I could restore and not lose my work. Is this possible, or is it a goner?

**Reproduction Steps:**
Start existing workspace

**Codenvy version:**
5.2.2

**OS and version:**    
Tried on both Windows 7, Windows 10; both Firefox and Chrome

**Docker version:**    
Not sure how to get this if workspace won't run

**Codenvy cli.log output:**  
Ditto.

**Comment by eivantsov** [comment]
@wtfpcloadletter we're investigating: https://github.com/codenvy/codenvy/issues/1403

**Comment by pierbettassa** [comment]
@eivantsov Same issue with workspace workspace61sjx9uxrg5wkpkz

**Comment by eivantsov** [comment]
@pierbettassa the issue's in progress. We plan updating production server soon.

**Comment by bmicklea** [comment]
@pierbettassa can you try it again, we updated codenvy.io with a fix in 5.3.

**Comment by pierbettassa** [comment]
Thanks! It works!

**Comment by wtfpcloadletter** [comment]
Indeed, can declare success. My work is *not* gone! Thanks!
