### ISSUE TITLE
Unexpected workspace data after launching of selenium cycle

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#1778]
**Preconditions:** the folder with Codenvy data should be empty.
**Reproduction Steps:** Launch Codenvy with CLI. Run selenium test cycle. Go to the codenvy data after that by path like: (`your_assembly/codenvy-data/instance/data/codenvy/fs`).
**Expected result:** the folder should be empty.
**Actual result:** we have unexpected folder with workspaces. But API and dashboard do not display workspaces.
**Codenvy version:**    5.3.0 - SNAPSHOT
**OS and version:**   Ubuntu 14.0
**Docker version:** 1.13.1

**Additional information:** the test workspaces are removed after each test and whole testsuite with REST API

**Comment by riuvshin** [comment]
@skabashnyuk @vparfonov guys please take a look
