### ISSUE TITLE
Explain in docs that swarm nodes hosts/IPs should be accessible for clients to work properly

### ISSUE THREAD

**Issue by garagatyi** [codenvy/codenvy#1779]
Right now we don't state in docs that SWARM_NODES variable should point to hosts/IPs that are accessible for clients (browsers).
If such host/IP is not accessible then software that runs in a WS on that node won't be accessible from browser. Basically that means that if user runs http server in WS he won't be able to browse it.

**Comment by TylerJewell** [comment]
This improvement was added awhile ago.
