### ISSUE TITLE
Docs for recipe structure not enabled?

### ISSUE THREAD

**Issue by asthomasdk** [codenvy/codenvy#1785]
I am trying to create a custom stack, and wanted to look at the docs for the recipe structure. Clicking on the link in the UI trying to add a new machine, I get directed to this link: 

https://eclipse-che.readme.io/inactive#section-authoring-custom-recipes

I get the following error on the screen: 

"Not Yet Active

The creators of this project are still working on making everything perfect!

Admin Login"

**Reproduction Steps:**

**Codenvy version:**    5.2.2

**OS and version:**    RancherOS 0.7.1

**Docker version:** 1.12.3

**Comment by TylerJewell** [comment]
@asthomasdk - can you be more specific on which link in which UI you clicked on.  We need some reproduction steps.  We have worked to remove all references to readme in the product, so the only remaining references to readme should only be coming from Google searches with old indexes.

**Comment by TylerJewell** [comment]
@JamesDrummond @ashumilova @slemeur - I just did a search of the Codenvy code base and found four references to readme.io.  I consider these bugs.  I thought we got rid of all of these.

```
C:\codenvy\codenvy>grep -r readme.io c:\codenvy\codenvy
c:\codenvy\codenvy/dashboard/src/app/factories/factory-details/information-tab/factory-information/factory-information.html:          <a href="https://codenvy.readme.io/docs/factories" target="_blank">Factory configuration docs</a>

c:\codenvy\codenvy/dashboard/src/app/factories/list-factories/list-factories.html:<che-description che-link-title="Learn more." che-link="http://codenvy.readme.io/docs/factories">

c:\codenvy\codenvy/site/app/site/email-templates/user_created_without_password.html:                                                        <a href="http://codenvy.readme.io/docs/introduction" style="color: #4787ff;">Documentation</a>

c:\codenvy\codenvy/site/app/site/email-templates/user_created_with_password.html:                                                        Documentation: <a href="http://codenvy.readme.io/docs/introduction" style="color: #4787ff;">http://codenvy.readme.io/docs/introduction</a>
```

**Comment by asthomasdk** [comment]
Sure - I will list them here if I find any that you have not listed. 

There are several places in here (Github) where there are references to readme.io as well. Not sure if they can be changed though.
