### ISSUE TITLE
Implement Phase 1 of team capabilities in onprem

### ISSUE THREAD

**Issue by ashumilova** [codenvy/codenvy#1786]
The concept of Teams as it exists in the SaaS Model could be valuable for certain enterprise customers. We should provide ability to use those features as well for their installation.

In this case, we would stick with the current model:
Each user will be able to create teams, personal organization will be enabled for all users
Codenvy Admins would grant resources to a specific user using API only

**Impacts on resources control would be the following:**
- Keep Workspace Cap, Running Workspace Cap and Workspace RAM Cap
- Display RAM widget on Dashboard page (otherwise, the info is available nowhere) 

 **Impacts on paid license:**
As OnPrem license is based on the number of seats, teams will also get the same limitation applied. But this is an indirect impact, as it is impossible to create account when the number of seats paid is reached - so it will be impossible to create teams with more users than authorized.

**Impacts on Dashboard:**
- Remove the Billing page
- Remove any “Buy More RAM Mention”
- Remove Idle timeout (Get more RAM button) from Workspace Details

**Comment by slemeur** [comment]
Closed for new requirements https://github.com/codenvy/codenvy/issues/1900
