### ISSUE TITLE
Investigate how to secure swarm to docker nodes communication with certificates

### ISSUE THREAD

**Issue by garagatyi** [codenvy/codenvy#1797]
Now communication between swarm and docker daemons is not secured with certificates. We need to investigate how to do that.
We should allow not secured communication by default since secured communication requires reconfiguration of docker daemons.
We should investigate whether it is possible to use self-signed certificates.
We should investigate is it possible to configure swarm to use different certificates for different nodes.
We should investigate how to generate certificates from CLI to simplify enabling this feature for customer.

**Comment by TylerJewell** [comment]
No longer valid with our move to k8s.
