### ISSUE TITLE
Can't start workspace

### ISSUE THREAD

**Issue by luisinserra** [codenvy/codenvy#1803]
I had a problem when starting my workspace. My machine shut down.
When I try to open workspace I get the message:
**Could not start workspace geosmarty. Reason: Start of environment 'default' failed. Error: Restore of workspace workspace5iml1z9g0072beti failed. Another restore process of the same workspace is in progress**

Everytime I try to open workspace I see the same message.
I can't stop it and I can't start.

nickname luisinserra
workspace geosmarty

Any idea of how to fix it?

**Comment by BaddMann** [comment]
ditto on this problem.
Been trying to recover for last 30 minutes.
Don't have my work-space linked to github or any other location, panicking a little as I don't want to start over.. :P
Its funny how "trying out" something quickly escalates!

**Comment by TylerJewell** [comment]
Hi - your workspaces and data are safe.  It looks like you tripped into this problem - https://github.com/codenvy/codenvy/issues/1403.  We have issued a number of PRs to both workaround (and permanently solve this problem). They are included in 5.3.0 release that was made yesterday.  We are now prepping codenvy.io for deployment with this release.

**Comment by BaddMann** [comment]
ETA?
I'm still stuck.

**Comment by skabashnyuk** [comment]
Merged in 5.3.0 3 days ago.

**Comment by TylerJewell** [comment]
I pointed that out in the previous comment.  I think he asks about when that release is shipped to codenvy.io.  It is about 1-3 biz days after release usually.

**Comment by BaddMann** [comment]
Is it possible that I'm seeing the same issue but I caused it some other way?
I just happened to be renaming my work-space when all of this started happening? Related?

I just want to get back into a working environment, I'll be happy to restore to an earlier snapshot, but I've been unable to figure out how that is done yet.

Advice?

**Comment by TylerJewell** [comment]
The issue appeared in a small number of workspaces.  The workspaces that were affected were not entirely predictable.  So I am unsure of what the triggers are that got you into this state.  But we are confident that the fix that has been made will restore workspace access for those that got into this state.

You should be able to create a new workspace and then re-clone your source code from a public git repository.  Have you tried to re-create an identical workspace?

**Comment by luisinserra** [comment]
Yesterday I created a new workspace and cloned from repository as you recommended.

that didn't work. Anyway I will try again.

**Comment by luisinserra** [comment]
I just created a new workspace with the sample java-web-spring and started tomcat in debug mode.

Didn't work.
Sorry.

**Comment by luisinserra** [comment]
Ok, I did it and the new workspace is ok.

Thanks.
