### ISSUE TITLE
JavaScript appears again in Project->New Menu after New JavaScript File

### ISSUE THREAD

**Issue by iladin** [codenvy/codenvy#1804]
Running from codenvy/ubuntu_jdk8_x11 

let me know if you need more debugging information

![image](https://cloud.githubusercontent.com/assets/3768247/23097108/5a14e506-f5e0-11e6-882f-d1619375d547.png)

**Comment by eivantsov** [comment]
Duplicate of https://github.com/eclipse/che/issues/4145
