### ISSUE TITLE
The cfp.io factory doesn't start properly.

### ISSUE THREAD

**Issue by SkorikSergey** [codenvy/codenvy#1807]
**Reproduction Steps:**

1. Go to the - **http://www.eclipse.org/che/getting-started/cloud/**
2. Create the **cfp.io** workspace

**Expected behavior:**
The workspace works properly

**Observed behavior:**
The workspace stops in processing of initialization

![screenshot from 2017-02-20 15-40-18](https://cloud.githubusercontent.com/assets/7760565/23127223/e90ce5b2-f782-11e6-89a4-12b880cd2d38.png)

**Comment by eivantsov** [comment]
1GB RAM isn't enough for that project.
