### ISSUE TITLE
Unexpected kill of ws. agent process after consuming some specific factories

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#1810]
**Reproduction Steps:**
*Consume the factory:* https://nightly.codenvy-stg.com/f/?url=https%3A%2F%2Fgithub.com%2Fbitnami%2Fbitnami-docker-codeigniter%2Ftree%2Fche
**Codenvy version:** 5.4.0-SNAPSHOT
**Expected result:** The workspace should be created without errors

![com codenvy ide factory checkbitnamyfactoriestest codeigniterurl_cdwindow-7e73fac7-3538-4a98-98fc-763f95d5ca9e](https://cloud.githubusercontent.com/assets/1640058/23160569/af62cb3a-f82f-11e6-837e-dd7790394e49.png)

**Actual result:** The ws. agent is killed
**Server location:** nightly.codenvy-stg.com
**OS and version:** Ubuntu 14.0

**Docker version:** 1.13

**Comment by garagatyi** [comment]
For some reason container created by this factory on my instance didn't applied memory limit from configuration and used default 1GB

**Comment by SkorikSergey** [comment]
WS-MACHINE RAM equals 0.
![selection_021](https://cloud.githubusercontent.com/assets/7760565/24652510/dff2d160-193a-11e7-8fe0-761b9a19ed35.png)

**Comment by garagatyi** [comment]
There is an error in workspace configuration. Attribute `memoryLimitsBytes` should be changed to `memoryLimitBytes` to by applied to the workspace. 
I created PR to fix that workspace configuration https://github.com/bitnami/bitnami-docker-codeigniter/pull/61.
