### ISSUE TITLE
Limiting of resources works wrong when configured value equals to -1

### ISSUE THREAD

**Issue by sleshchenko** [codenvy/codenvy#1812]
When there are configured [default accounts' resources](https://github.com/codenvy/codenvy/blob/master/dockerfiles/init/manifests/codenvy.env#L171-L205) with -1 value, then limiting of resources works incorrect.

Expected:
User will be able to use unlimited resources.

Actual: 
User gets error message when he tries to use resource
`You are only allowed to create -1 workspaces.`
`You are only allowed to start -1 workspaces.`
`Workspace needs 1000mb to start. Your account has -1 mb and 0mb in use. The workspace can't be start. Stop other workspaces or grant more resources.`

**Comment by bmicklea** [comment]
@sleshchenko is this something you're working on in this sprint?

**Comment by sleshchenko** [comment]
@bmicklea I've prepared changes that are needed on server side https://github.com/codenvy/codenvy/pull/2174 and @ashumilova will adapt dashboard. So then we'll merge our changes together.

**Comment by ashumilova** [comment]
Took to the next sprint - will start work on it tomorrow.
