### ISSUE TITLE
Default encoding. How could I change?

### ISSUE THREAD

**Issue by luisinserra** [codenvy/codenvy#1818]
I checked out a project that originally was written in ISO-8859-1

Eclipse che has UTF-8 as default encoding.

It's a lot of work change everything.

Is there a way to change the default charset?

![delt](https://cloud.githubusercontent.com/assets/19390679/23197459/4d7b3644-f89f-11e6-83bf-36f2a99b6413.jpg)

Thanks.

**Comment by eivantsov** [comment]
Currently, it is not configurable for a user

**Comment by luisinserra** [comment]
Thanks.
