### ISSUE TITLE
On Prem on Windows. Cannot start a workspace

### ISSUE THREAD

**Issue by eivantsov** [codenvy/codenvy#1826]
This issue can be reproduced only on Windows. Steps to reproduce:

1. Launch Codenvy nightly
2. Go to 10.0.75.2
3. Start a workspace.

When browser tries to reach ws agent, the following thing happens:

`Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://10.0.75.2' is therefore not allowed access. The response had HTTP status code 401.`

When accessing Codenvy at http://localhost, the issue cannot be reproduced.

**Comment by slemeur** [comment]
@skabashnyuk Please take this issue into account for your next sprint.

**Comment by bmicklea** [comment]
@skabashnyuk it looks like all the referenced issues here are merged/closed - should this be closed as fixed?

**Comment by skabashnyuk** [comment]
I'll check that

**Comment by mshaposhnik** [comment]
Done - we corrected filter order to be CORS first, and corrected CLI to use localhost on Mac & Win.
