### ISSUE TITLE
.Net sample application is broken

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#1827]
When starting the .net stack on codenvy.io with the built-in sample application `aspnet-web-simple` the workspace is started correctly but the sample application is not cloned and the project appears to be setup as a blank project:

![screen shot 2017-02-23 at 10 49 30 am](https://cloud.githubusercontent.com/assets/7644938/23266433/c98ead12-f9b5-11e6-94a6-3f5ecd13d18c.png)

The stack itself and commands appear to be correct so if the sample application was cloned in correctly and the project type was correctly set to .net I believe everything would work.

**Reproduction Steps:**
1. Log into codenvy.io.
1. Create a new workspace with the .net stack and `aspnet-web-simple` project.
1. When IDE opens notice that the project code is not loaded and it appears to be a blank project type instead of the C# project type.

**Codenvy version:**    
5.3.1

**OS and version:**    
codenvy.io

**Docker version:**    
codenvy.io

**Codenvy cli.log output:**  
codenvy.io

**Comment by bmicklea** [comment]
@riuvshin not sure if you're the right person for this - feel free to assign elsewhere.

**Comment by riuvshin** [comment]
@bmicklea yes, this is not something I can help but let's start with what exactly is not OK with that stack ? how those commands should look then?  I mean to do something I have to know what are your expectations here.

**Comment by bmicklea** [comment]
The stack is fine (at least it appears to be fine), but the sample application `aspnet-web-simple` doesn't pull in any code and the project type is blank instead of C#. I've added a screenshot and updated the issue description to try and be more clear.

**Comment by riuvshin** [comment]
strange... I've just created again new workspace from .net stack and everything is fine here... 
![dotnet](https://cloud.githubusercontent.com/assets/1636732/23266890/c70872f8-f9f1-11e6-9fca-11696c02b4e5.png)
that is actually why I've asked for expectations because everything looks fine to me here

**Comment by bmicklea** [comment]
GAH, caching strikes again - just tried this in an incognito window and everything was fine so it must have something to do with caching...
