### ISSUE TITLE
Unable to git push repo to Gitlab after Feb 22 production updated to 5.3.1

### ISSUE THREAD

**Issue by marcelobern** [codenvy/codenvy#1837]
Unable to git push repo to Gitlab after Feb 22 production updated to 5.3.1

Since Feb 22, I have been unable to git push to Gitlab, with the result being "Connection timed out" error

**Reproduction Steps:** Execute git push to Gitlab from codenvy.com

**Codenvy version:**    5.3.1

**OS and version:**    N/A

**Docker version:** N/A

**Codenvy cli.log output:**  N/A

**Comment by TylerJewell** [comment]
@skryzhny @eivantsov - could this be a whitelist issue with Gitlab changing IP addresses?

**Comment by eivantsov** [comment]
It is quite possible that IP has changed

**Comment by marcelobern** [comment]
Not sure what happened but it is working now. Thanks for the help!
