### ISSUE TITLE
Unable to locate dev machine URL, which is running a nodejs server, for connection over browser.

### ISSUE THREAD

**Issue by 4d4tt4** [codenvy/codenvy#1840]
Hi I am not able to find the url of dev machine to connect to my nodejs server running on local host,
port i have set to 3000 and but not able to find url to connect to application via web browser.

Thanks

**Comment by 4d4tt4** [comment]
I just checked in other cloud IDE like codeanywhere , in readme they listed url to connect to dev machine via browser, is there some mechanism to connect to codenvy machine .

**Comment by TylerJewell** [comment]
Hi - Codenvy is based upon Eclipse Che.  We have a node.js tutorial that walks you through all of these steps here.  The steps are mostly the same inside of Codenvy - you just do not need to start Che.

https://www.eclipse.org/che/docs/tutorials/nodejs/index.html

**Comment by eivantsov** [comment]
@4d4tt4 did @TylerJewell's response help you?

**Comment by 4d4tt4** [comment]
thanks @TylerJewell's, it worked for me but when i reloaded the project the run configuration button disappeared, nay way to reload it

**Comment by TylerJewell** [comment]
You need to share reproduction steps along with an animated gif to understand what youa re asking.

**Comment by eivantsov** [comment]
@4d4tt4 can you giver us an update on this please?

**Comment by eivantsov** [comment]
Closed due to inactivity.
