### ISSUE TITLE
Add mecanism to allow invitating users who are not registered

### ISSUE THREAD

**Issue by ashumilova** [codenvy/codenvy#1851]
# Goal
Since we have introduced teams we have improved the way users can share their work with other users. 

Today, the problem we face is that when a user is inviting other users into a team (or a workspace), they need to already have registered onto codenvy.io.
We want to improve this so that it allow to invite people who are not yet registered onto codenvy.io.

The benefits are that it helps to get viral and get more account created. Those accounts created are usually interesting because they are introduced to codenvy by other people that they know and that they trust. 

## Flow
1. From dashboard, user can provide emails of un-registered users when adding members to a team
2. An email is sent to the un-registered users with a link to the create account page
3. User fill the form and email will automatically be pre-filled with the same email adress than in `1.` 
4. User is created onto the system
5. User is added into the team he was initially invited

## Technical tradeoff
- We might limit the number of invitation a user can send per a certain period of time
- We might use reCapcha
- We can envision using hash to identify email that a team admin wanted to invite and compare it with the one given in account creation form

## Long term ideas
- We can imagine a mecanism to check if the invitation sent to an email have been accepted (=account created) and resend an email for those who have not yet registered.

**Comment by TylerJewell** [comment]
Some important aspects here:
1. If a user initiates the account creation process from an invitation email, it should not be necessary for the user to have to re-verify their email address.  It is known from the initiation link in the email sent to their address.

2. Once the user creates their account in Codenvy, then they should not have to take additional steps to join the team.

3. If an invitation over email address is sent to an existing user associated with that same email address, we should recognize that in the invitation window and add them like a permanent user.

**Comment by slemeur** [comment]
Cross linking with initial issue: https://github.com/codenvy/saas/issues/161

**Comment by slemeur** [comment]
Updating description of the issue.

**Comment by sleshchenko** [comment]
@slemeur Do we have template for inviting members via email?
