### ISSUE TITLE
Update old style of email notifications to new one

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#1853]
With the introduction of the new Codenvy's brand and the team capabilities, we have changed the layout of emails sent by the product. 

We need to be consistent and use the same styles for all emails that are sent by the product.

OLD style:
<img width="762" alt="screen shot 2017-03-01 at 16 01 14" src="https://cloud.githubusercontent.com/assets/1636769/23462932/6a964f30-fe98-11e6-8ce8-50dff253fed7.png">

NEW style:
<img width="793" alt="screen shot 2017-03-01 at 16 01 27" src="https://cloud.githubusercontent.com/assets/1636769/23462943/70457f82-fe98-11e6-908b-aeac79da5ac0.png">

**Comment by vkuznyetsov** [comment]
Could you provide a new style for button we have had in old style? 
![verify your codenvy account](https://cloud.githubusercontent.com/assets/2101815/24410338/7efe8ad4-13db-11e7-90c3-9309a74665aa.png)

**Comment by slemeur** [comment]
Please check the styles from the new website and use the one from the footer:
![screen shot 2017-03-29 at 12 01 07](https://cloud.githubusercontent.com/assets/1636769/24449477/a3345284-1477-11e7-85bc-8e77b3fb83a6.png)

**Comment by vkuznyetsov** [comment]
What the style for the links?

**Comment by slemeur** [comment]
you can find that style (for links) in the templates we had for teams invitations.

**Comment by vkuznyetsov** [comment]
Here is the style for links in team email - underlined blue text.
![added to a codenvy organization](https://cloud.githubusercontent.com/assets/2101815/24546529/5dcdfc6a-1614-11e7-91ed-4db81de5c6bb.png)

**Comment by vkuznyetsov** [comment]
Depends on https://github.com/codenvy/codenvy/issues/2015. It needs to update template generator.
