### ISSUE TITLE
Cannot consume factories

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#1854]
**Reproduction Steps:**
* Go to the workspace create a project 
* Workspace -> Create factory
* Try to consume the factory

**Expected result:** We should consume the factory
**Actual result:** We are redirected on Dashboard
**Codenvy version:**    5.4.0 SNAPSHOT

**OS and version:**    Ubuntu 14 TLS
**Docker version:** 1.13.1
**Server location:** https://nightly.codenvy-stg.com

**Comment by akorneta** [comment]
fixed by: https://github.com/codenvy/saas/pull/169
