### ISSUE TITLE
Codenvy does not start behind a proxy

### ISSUE THREAD

**Issue by eivantsov** [codenvy/codenvy#1855]
When Docker daemon is configured to work behind a proxy and CLI inherits these envs, Tomcat tries to reach Swarm at `http://codenvy-swarm:2375/v1.20/info">http://codenvy-swarm:2375/v1.20/info` but for some reason it tries to go through proxy even though codenvy-swarm is added to no_proxy in JAVA_OPTS.

**Comment by riuvshin** [comment]
fixed by https://github.com/codenvy/codenvy/commit/f8a15ed13d7c49621ccba6e65f647462c430c592
