### ISSUE TITLE
Change email styles for Silexica assembly

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#1862]
For Silexica we need to update the email styles for their assembly:
- [ ] Change Codenvy logo to Silexica logo
- [ ] Change black banner to the Silexica color
- [x] Update email content to [remove mentions of Codenvy](https://github.com/codenvy/silexica/pull/2)

**Comment by vkuznyetsov** [comment]
moved to enterprise project https://github.com/codenvy/enterprise/issues/58
