### ISSUE TITLE
Unexpected browser alert pop up after switching between ws. from nav bar

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#1871]
**Reproduction Steps:** Create a team with two workspaces. Ws.#1 should be launched. Ws.#2 should be restricted by RAM. Try to switch between the workspaces from nav. bar.
![anim](https://cloud.githubusercontent.com/assets/1640058/23514551/57db144c-ff70-11e6-9c27-98c2cdc640f3.gif)

**Codenvy version:**  5.4.0
**OS and version:**    Ubuntu 14.0 TLS

**Server location:**

**Comment by slemeur** [comment]
seems like normal behaviour - but error message not clear.
@ashumilova could you check the use case please?
