### ISSUE TITLE
Can't quite figure out how to install git-crypt as part of my stack

### ISSUE THREAD

**Issue by richtera** [codenvy/codenvy#1878]
**Reproduction Steps:**
Without adding it to the stack I loose git-crypt whenever the workspace restarts.
Getting errors when git clean is called and so on.

**Codenvy version:**    
5.0.0-M9

**OS and version:**    
CoreOS

**Docker version:**    

**Codenvy cli.log output:**

**Comment by richtera** [comment]
Posted #1879 to see if I can just build my own docker but I can't add my registry.

**Comment by eivantsov** [comment]
@richtera you need to build a custom stack

Some docs to help you http://www.eclipse.org/che/docs/workspace/stacks/index.html

**Comment by richtera** [comment]
I think we can close this but I still cannot create a custom docker using my google component registry due to the length of the password.

**Comment by eivantsov** [comment]
OK, i am closing this one and doing my best to help you with the registries.
