### ISSUE TITLE
Cannot start codenvy on local machine

### ISSUE THREAD

**Issue by tim-e-de-vries** [codenvy/codenvy#1880]
**Reproduction Steps:**
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/dockerdata:/data codenvy/cli start
visit URL
**Codenvy version:**    

**OS and version:**    
Distro: Linux Mint 18.1 Serena
Desktop: Cinnamon 3.2.7 (Gtk 3.18.9) dm: mdm 

INFO: (codenvy cli): 5.4.0 - using docker 1.12.6 / native

**Docker version:**    

**Codenvy cli.log output:**  
dev-machine] [DOCKER] Step 1 : FROM eclipse/ubuntu_jdk8
[dev-machine] [DOCKER] Pulling repository docker.io/eclipse/ubuntu_jdk8 
[dev-machine] [DOCKER] [ERROR] Error while pulling image: Get https://index.docker.io/v1/repositories/eclipse/ubuntu_jdk8/images: dial tcp: lookup index.docker.io on [::1]:53: read udp [::1]:43002->[::1]:53: read: connection refused
[dev-machine] [ERROR] Docker image build failed. Image id not found in build output.

**Comment by TylerJewell** [comment]
@tim-e-de-vries - your title and error messages do not connect for me.  The error message that you are showing is what would happen if you try to start a workspace.  So it seems that Che started successfully.

Can you update your reproduction steps, and also what happens when you run diagnostics (button in lower right of the dashboard that loads)?

**Comment by tim-e-de-vries** [comment]
Yes, the title s/b "Cannot start codenvy **machine instances** using local machine"
Running Diagnostics 
Server Test all good

Workspace tests failed on step 1 "Connectivity checks to Dockerized workspaces"
Output:

EventChannel : {"eventType":"STARTING","status":"STARTING","workspaceId":"workspace5bjxh5vaym9jekom","prevStatus":"STOPPED"}
StatusChannel : {"machineId":"machinepny8e2kysvez4ej0","eventType":"CREATING","dev":true,"machineName":"dev-machine","workspaceId":"workspace5bjxh5vaym9jekom"}
[DOCKER] Step 1 : FROM openjdk:8-jre-alpine
output channel message :{"machineName":"dev-machine","content":"[DOCKER] Step 1 : FROM openjdk:8-jre-alpine"}
[DOCKER] Pulling repository docker.io/library/openjdk 
output channel message :{"machineName":"dev-machine","content":"[DOCKER] Pulling repository docker.io/library/openjdk "}
[DOCKER] [ERROR] Error while pulling image: Get **https://index.docker.io/v1/repositories/library/openjdk/images**: dial tcp: lookup index.docker.io on [::1]:53: read udp [::1]:47574->[::1]:53: read: connection refused
output channel message :{"machineName":"dev-machine","content":"[DOCKER] [ERROR] Error while pulling image: Get https://index.docker.io/v1/repositories/library/openjdk/images: dial tcp: lookup index.docker.io on [::1]:53: read udp [::1]:47574->[::1]:53: read: connection refused"}
[ERROR] Docker image build failed. Image id not found in build output.
output channel message :{"machineName":"dev-machine","content":"[ERROR] Docker image build failed. Image id not found in build output."}
StatusChannel : {"machineId":"machinepny8e2kysvez4ej0","eventType":"ERROR","dev":true,"machineName":"dev-machine","workspaceId":"workspace5bjxh5vaym9jekom"}
Error while starting the workspace : {"machineId":"machinepny8e2kysvez4ej0","eventType":"ERROR","dev":true,"machineName":"dev-machine","workspaceId":"workspace5bjxh5vaym9jekom"}
 --- ERROR

**Comment by TylerJewell** [comment]
@benoitf @eivantsov @garagtyi

**Comment by benoitf** [comment]
```
https://index.docker.io/v1/repositories/eclipse/ubuntu_jdk8/images: dial tcp: lookup index.docker.io on [::1]:53: read udp [::1]:43002->[::1]:53: read: connection refused
```

Are you behind a proxy ? Or firewall

**Comment by tim-e-de-vries** [comment]
No, just me on my home network.  FWIW, When I visit the page via a web browser it renders (albeit just a "[]").  And when I visit the one level up (e.g. https://index.docker.io/v1/repositories/eclipse/ubuntu_jdk8) I get an authentication challenge from the Docker site.

**Comment by TylerJewell** [comment]
What happens if you "docker pull eclipse/ubuntu_jdk8"?

**Comment by benoitf** [comment]
@tim-e-de-vries 
`
$ docker run --entrypoint curl codenvy/cli -v http://index.docker.io/v1/
`
?

**Comment by tim-e-de-vries** [comment]
"docker pull eclipse/ubuntu_jdk8"  from the command line -- I get the same errors as above 
"docker run --entrypoint curl codenvy/cli -v http://index.docker.io/v1/"  gets me:
*   Trying 52.200.132.201...
* TCP_NODELAY set
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to index.docker.io (52.200.132.201) port 80 (#0)
> GET /v1/ HTTP/1.1
> Host: index.docker.io
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Content-length: 0
< Location: https://index.docker.io/v1/
< Connection: close
< 
* Curl_http_done: called premature == 0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0

**Comment by TylerJewell** [comment]
This doesn't seem like an issue with Che.  It seems like there is something preventing docker from working with your networking.  Firewall on?  Misconfigured daemon?  Proxy?

**Comment by tim-e-de-vries** [comment]
I did the old uninstall/re-install of the docker.io package (as well as deleting the ~/.docker directory) and voila, all better.  I've been poking at Docker for a couple of years on and off, so more than likely I just had some old configuration gunk hanging around.  Sorry for the goose chase.  

P.S.  You guys are awesome.  Thanks for the prompt follow up.

**Comment by TylerJewell** [comment]
Great - glad it worked out.  Have fun
