### ISSUE TITLE
root password

### ISSUE THREAD

**Issue by aipersoni** [codenvy/codenvy#1883]
i have a problem with the password, i know that the password was secret but now its not working what can i do plz help

**Comment by eivantsov** [comment]
@aipersoni we have rebuilt all images and recreated the user without password. If you want to ssh into a running workspace, use SSH keys - http://www.eclipse.org/che/docs/ide/ssh/index.html

**Comment by eivantsov** [comment]
@aipersoni do you have any further questions? Are you trying to ssh into a container? Or do you need root password for something else?

**Comment by Anid4u2c** [comment]
I'm running into the need for the password too... when following the instructions here (https://codenvy.com/docs/user-guide/using-desktop-ides/index.html), and are prompted for the password (it's not "secret" and it's not "password") running the following code: `docker run --rm -it \
	  --cap-add SYS_ADMIN \
           --device /dev/fuse \
           --name codenvy-mount \
           -v /c/Users/%USERNAME%/mount:/mnthost \
           codenvy/che-mount <codenvy-server-ip> <codenvy-server-ssh-port>`

Example:  `user@node1.codenvy.io's password:`

**Comment by eivantsov** [comment]
@Anid4u2c docs need to be updated then. We have removed passwords for security reasons.

To sync your workspace projects, use the following syntax:

`docker run --rm -it --cap-add SYS_ADMIN --device /dev/fuse --name che-mount -v /var/run/docker.sock:/var/run/docker.sock -v /c/Users/%USERNAME%/mount:/mnthost eclipse/che-mount $ws-name --url https://codenvy.io --user $yourLogin  --password $yourPass`

**Comment by Anid4u2c** [comment]
Thanks Eugene!

**Comment by eivantsov** [comment]
I am closing this issue. Feel free to reopen if you have further questions.

**Comment by Teg79** [comment]
The command is not working for me:

```
docker run --rm -it --cap-add SYS_ADMIN -e CHE_VERSION=6.5.0 --device /dev/fuse --name che-mount -v /var/run/docker.sock:/var/run/docker.sock -v sync:/mnthost eclipse/che-mount Industria --url http://172.16.14.87:8080 --user $user --password $password
Authorization token is missed
---------------------------------------
!!!
!!! ERROR: Error when trying to get workspace data for workspace named Industria
!!!
---------------------------------------
List of workspaces are:
ERROR: (Eclipse Che action/list-workspaces): Unable to connect to the remote host 192.168.65.3 on port 8080. Please check the server is listening and that there is no network issue to reach this host. Full error: Error: connect ECONNREFUSED 192.168.65.3:8080
```

The **Authorization token is missed** is the same error I get when using list-workspaces alone
