### ISSUE TITLE
Python Jupyter Notebooks on codenvy 

### ISSUE THREAD

**Issue by kuatroka** [codenvy/codenvy#1898]
**Reproduction Steps:**
in Python environment, run command `pip install jupyter` and then run jupyter  with command `jupyter noteboook`. But when I run it I get the error message

> no web browser found: could not locate runnable broswer

**Codenvy version:**    

**OS and version:**    

**Docker version:**    

**Codenvy cli.log output:**

**Comment by TylerJewell** [comment]
I think this is a question for the jupyter team.  Your workspace at Codenvy is a Docker container, and the browser is connected through agents and terminal.  So if Jupyter is a server-based program that has to be configured with a browser, then you need to get the instructions for how it should be installed inside of a remote running container that is disconnected from a browser.

**Comment by kuatroka** [comment]
Thanks Tyler, so if I understand you correctly, the Docker container has Chrome installed in it, its just that this precise Python module - jupyter notebook is not correctly configured to use it yet, but the Docker itself does have Chrome and supports it's installation and use? Thanks

**Comment by eivantsov** [comment]
@kuatroka you need a custom environment with x server and Chrome installed.

**Comment by eivantsov** [comment]
@kuatroka I'd use `eclipse/x11_vnc` image, install python there and create a command (any command like `echo hello world`) with the following preview URL `http://${server.port.6080}`. Once in a noVNC window, right click gray area, open a terminal, navigate to `/projects/yourProject` and run python commands from there.

**Comment by eivantsov** [comment]
Closed due to inactivity.
