### ISSUE TITLE
After consuming a factory the cloned project may be broken (regression)

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#1908]
**Reproduction Steps:** try to use factory like: https://nightly.codenvy-stg.com/f?url=https://github.com/musienko-maxim/codenvy/tree/master/dashboard

**Expected result:** The project should be cloned. Project type should be set. 

**Actual result:** We have inconsistent project like on screenshot:
![selection_029](https://cloud.githubusercontent.com/assets/1640058/23849259/96bd41c8-07e3-11e7-8fc4-951c4accf29e.png)

**Codenvy version:**  5.5.0-SNAPSHOT

**OS and version:**    Chrome browser Ubuntu 14.0 TLS

**Note:** the problem reproduce randomly

**Comment by riuvshin** [comment]
@skabashnyuk  please take a look

**Comment by mshaposhnik** [comment]
Is that possible that is fixed together with https://github.com/codenvy/codenvy/issues/1958 ?
Did it reproduced lately @musienko-maxim ?

**Comment by mshaposhnik** [comment]
Reproduced very rarely and only in multithread conditions (at least 4 threads). So no way it can be catch or reproduced manually.

**Comment by musienko-maxim** [comment]
Still actual, need to investigate
