### ISSUE TITLE
Unable to use all parent organization resources

### ISSUE THREAD

**Issue by sleshchenko** [codenvy/codenvy#1909]
Unable to use all parent organization resources.

Steps to reproduce:
1. Login as admin.
2. Set free resource limit to 4 GB.
3. Create team and two workspaces there which require 2GB to start.
4. Try to start both of workspaces.

Expected: Both workspaces start successfully.
Actual: The first workspace starts successfully. Start of the second workspace fails with error `Workspace admin/test/ws1 needs 2048MB to start. Your account has 0MB available and 2048MB in use. The workspace can't be start. Stop other workspaces or grant more resources.`

**Comment by TylerJewell** [comment]
Yes, agree with the characterization as severity/blocker.
