### ISSUE TITLE
Connection timeout with git. Please add beanstalkapp.com git servers to a whitelist.

### ISSUE THREAD

**Issue by Htarlov** [codenvy/codenvy#1915]
**Reproduction:**

Tried to use webvizarts.git.beanstalkapp.com server for git integration in a workspace.
It failed with a timeout error: "... Connection timed out (Connection timed out)"

Same from command line through ssh by git pull or push command:

```
ssh: connect to host webvizarts.git.beanstalkapp.com port 22: Connection timed out
fatal: Could not read from remote repository.
```
**Codenvy version:**  5.4.1 rev. cd0fbfff84c4729b

**OS and version:**    Ubuntu 16.10

Here is the [link to beanstalkapp IP list](http://support.beanstalkapp.com/article/863-ip-addresses-for-access-to-beanstalk).

**Comment by TylerJewell** [comment]
@skryzhny - FYI, this is a valid git provider.  We can be ok to open up the whitelist for this.

**Comment by skryzhny** [comment]
Whitelisted.
Can you confirm it works now?

**Comment by ligett** [comment]
same here with git.assembla.com, can you open that up as well please?

**Comment by eivantsov** [comment]
@skryzhny can you whitelist it please?

**Comment by skryzhny** [comment]
git.assembla.com whitelisted
