### ISSUE TITLE
Doesnt support GitHub organizations' private repo 

### ISSUE THREAD

**Issue by kmaillet-arcane** [codenvy/codenvy#1916]
Codenvy's built in git functionnalities are unable to handle GitHub organizations' private repositories. For instance, when I try to use "import project>GitHub" in a existing workspace I get the error "Invalid remote origin", even though I am able to clone the repo using CLI in the same workspace.

**Reproduction Steps:**
- In a codenvy workspace : Import Project> GitHub > git@github.com:<MyOrganisation>/<the private repo>.git

**Expected Behavior**
- The project is imported from the organization's private repo

**Observed Behavior**
Error message "Importing project <project name> ; Invalid remote : origin"

**Codenvy version:**    
5.4.1

**Comment by eivantsov** [comment]
@kmaillet-arcane have you used GitHub oAuth? Your repositories are automatically populated or do you manually enter it?

**Comment by eivantsov** [comment]
Try cllicking Load repos button when in Import Project Wizard

**Comment by kmaillet-arcane** [comment]
To register a new ssh key I did the following in codenvy :
profile> preferences > VCS > Github icone
Codenvy is shown as an authorized applications in github, so I guess the oAuth worked

when I click on the load button only my repos are shown, not my organization's private ones

I am able to access my organization's repo with codenvy when they are public

**Comment by eivantsov** [comment]
Did you see your organization in the list when you authorized application on GitHub?

Can you revoke app access in your GitHub settings at https://github.com/settings/applications/ and go through oAuth again? This time, pay attention to the list of organizations in the bottom left:

![image](https://cloud.githubusercontent.com/assets/5337267/23935423/9f63896e-0954-11e7-8192-2fc8d6a4c2bc.png)

and then:

![image](https://cloud.githubusercontent.com/assets/5337267/23935465/c72ea83e-0954-11e7-8a2a-842fe110510b.png)

As you can see, I have no access to che-samples organization, although I have access to repositories in this organization.

**Comment by kmaillet-arcane** [comment]
Ok it works now, 
Thanks for your help @eivantsov !
