### ISSUE TITLE
Permission denied, please try again. Codenvy SSH

### ISSUE THREAD

**Issue by the-black-potato** [codenvy/codenvy#1918]
First I launch my workspace, on the Consoles panel I click "Connect via SSH"
I copy the command giving by the terminal: ssh user@${hostname} -p ${port} [-i /path/to/your/private/ssh/key]
I paste on my terminal, then it's ask "user@node15.codenvy.io's password: " I type my codenvy account password and I get this message " Permission denied, please try again.". I don't understand where is the problem.

**Comment by TylerJewell** [comment]
You need to provide clear steps to reproduce this.  In order for the community to help you better, you need to provide explicit details.

**Comment by maxime-coutte** [comment]
Thank you for your advice, I just updated my post, hoping not to be too imprecise.

**Comment by TylerJewell** [comment]
It wants your workspace password for SSH, not your codenvy password.  Your workspace password changes for each workspace and it should be printed out in the SSH panel.

**Comment by maxime-coutte** [comment]
Is the password the "RSA PRIVATE KEY" ? Because I  have trying copy pasting the "RSA PRIVATE KEY" and it still print "Permission denied, please try again.".

**Comment by TylerJewell** [comment]
These are the docs on how it is applied.
https://codenvy.com/docs/user-guide/ssh/index.html

@JamesDrummond  - please take a look

@eivantsov @benoitf - fyi

We'll need to know which version you are running on-prem or if it's codenvy.io.  The password and key mechanism recently changed.

**Comment by maxime-coutte** [comment]
I use codenvy.io.

**Comment by maxime-coutte** [comment]
To be sure that the error does not come from this, "/ path / to / your / private / ssh / key" means that I have to have on this directory the SSH private key of codenvy or another private key?

**Comment by benoitf** [comment]
you need the private key on your computer. The public key is added on each machine of the workspace

Note that cli allows you to use a single command to connect through ssh ( it handles the private key retrieval)

**Comment by the-black-potato** [comment]
So I have to copy the private key of my workspace and paste it on a text file, and with this command " ssh user@${hostname} -p ${port} [-i /path/to/your/private/ssh/key]" remplace "/path/to/your/private/ssh/key" with the path of the key? Did I have to add ".ssh" at the end of the files if it is what I have to do ?

**Comment by benoitf** [comment]
correct and name of the private key can be whatever you want

**Comment by the-black-potato** [comment]
And for the password ?

**Comment by benoitf** [comment]
With a correct key there is no password. If password is prompted it means the key file is invalid or have invalid permissions

**Comment by the-black-potato** [comment]
So my key is incorrect, but I copy the "RSA PRIVATE KEY" that I found when I click on "Connect via SSH", I past it on a text file, and I add the "ssh" extension. What step is wrong or what I forgot?

**Comment by eivantsov** [comment]
@the-black-potato the file needs no extension at all. Say, its name is `key`. However, after you have created it, run the following command:

`chmod 400 key`

Then connect:

`ssh user@${hostname} -p ${port} -i key`

**Comment by the-black-potato** [comment]
Thanks, it's okey i'm now connect. Than I try this: sshfs user@${hostname}:/projects /your/local/directory/ -p ${port}
And it's ask a password, wich password I have to type?

**Comment by eivantsov** [comment]
@the-black-potato perhaps this or similar threads will help you - http://unix.stackexchange.com/questions/61567/sshfs-specify-key

**Comment by eivantsov** [comment]
The issue seems to have been resolved. Feel free to reopen if you have any further questions.
