### ISSUE TITLE
Webpack Dev Server & Preview URL

### ISSUE THREAD

**Issue by gemmadlou** [codenvy/codenvy#1919]
Webpack dev server doesn't work with Codenvy. There are no error messages, and I'm still learning how to use Codenvy. Any help will be deeply appreciated.

**Reproduction Steps:**

I currently run this command on a static app project in Codenvy using a command:

   ` webpack-dev-server --inline --hot`

I get the following response from the terminal:

command: cd /projects/CAAS && npm run dev
preview:node15.codenvy.io:33373
 
> hello@1.0.0 dev /projects/CAAS
> webpack-dev-server --inline --hot
 
Project is running at http://localhost:8080/
webpack output is served from /dist/
404s will fallback to /index.html
(node:2768) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

**Codenvy version:**  
  
5.4.1

**OS and version:**   

Chrome OSX 

**Docker version:**

???

**Comment by eivantsov** [comment]
@gemmadlou i am bit confused. What command are you trying to run and what preview URL does not work for you?

Sharing your project and command you use to run it will help.

**Comment by gemmadlou** [comment]
Hi @eivantsov 

I created a preview url within the CMD tool referencing the following rules:
http://${server.port.8080}

![image](https://cloud.githubusercontent.com/assets/4562670/23956135/c4286834-0993-11e7-9c6e-a0a3ff01495c.png)

I  map my npm webpack-dev-server to the port using the following command:
webpack-dev-server --host 0.0.0.0 --port 8080 --inline --hot

However, when I go to the generated url - it doesn't load anything and ends up timing out.

I have created a factory of my project so far:
https://codenvy.io/dashboard/#/load-factory?id=factorywhgqf6zy47fbu3ta

**Comment by eivantsov** [comment]
![image](https://cloud.githubusercontent.com/assets/5337267/23961242/fd258706-09b2-11e7-84d4-770fc9a42b87.png)

@gemmadlou please check if the ephemeral port range `32768-65535` isn't blocked in your network. I was able to run your project.

**Comment by gemmadlou** [comment]
Yeah - that was it @eivantsov! Thank you so much!
