### ISSUE TITLE
CODENVY_DOCKER_REGISTRY_FOR_WORKSPACE_SNAPSHOTS settings

### ISSUE THREAD

**Issue by richtera** [codenvy/codenvy#1924]
**Reproduction Steps:**
When trying to set CODENVY_DOCKER_REGISTRY_FOR_WORKSPACE_SNAPSHOTS, how do I add a prefix? The docs just say DNS:PORT but I need DNS:PORT/path to prefix the tag.
So for example:
us.gcr.io/PROJECT_NAME/WORKSPACE_NAME where WORKSPACE_NAME is the name you choose when doing SNAPSHOT and RESTORE operations.

**Codenvy version:**    

**OS and version:**    

**Docker version:**    

**Codenvy cli.log output:**

**Comment by TylerJewell** [comment]
You only set the registry identifier.  Codenvy internals are responsible for setting organization and repository names of snapshots within the system.  

So I do not think I understand your request - and why you are trying to override project and workspace parameters set by the system.

**Comment by richtera** [comment]
I need to control the organization name using an environment variable since only my google PROJECT_ID will allow access to the repository using the login I specify in the private docker repositories section of the environment file.

**Comment by eivantsov** [comment]
I think this is smth we don't support at the moment. I'll give more details a bit later

**Comment by richtera** [comment]
... there might be a solution here using the local registry ...
Is the access to the local registry limited to the internal network or is it accessible through haproxy?

**Comment by richtera** [comment]
Nope guess not.
It's trying to use my external IP at port 5000 which I definitely don't want open if this registry is not password protected. Trying to use the internal IP causes errors since the registry is assuming TLS and can't talk http only. So I guess I am stuck waiting. When will this go in?
The error is:
```
Get https://<mydns>:5000/v1/_ping: dial tcp 104.196.65.95:5000: i/o timeout
```

**Comment by eivantsov** [comment]
Maybe adding this local registry as an insecure registry to docker daemon options may help?

**Comment by richtera** [comment]
Good idea. I had assumed it was a java implementation issue to allow insecure registries. I got that to work. I think the best way forward would be to allow "allow configuration of the organization for snapshots" and probably "protect the builtin registry with a user/password or apikey".

**Comment by TylerJewell** [comment]
@eivantsov - a lot of these concepts are just outside of my comfort zone.  So it's going to be challenging for me to pick out the nuggets of best practices here to write into a specification for improvement.  But in reading through the threads, it clearly looks like there are some configurable items that we will want to make available for these various registry scenarios.  Do you have enough details to write a short specification / enhancement request that would allow us to capture these ideas?

**Comment by eivantsov** [comment]
@TylerJewell I registered an issue https://github.com/codenvy/codenvy/issues/1936

Also, we discovered another bug and Roman has provided a fix that has been merged https://github.com/codenvy/codenvy/pull/1931

**Comment by eivantsov** [comment]
@richtera are you all set with using a 3rd party docker registry to save snapshots?

**Comment by eivantsov** [comment]
Closing this issue. Both PR have been merged.
