### ISSUE TITLE
DOCKER_HOST needs a port

### ISSUE THREAD

**Issue by wernight** [codenvy/codenvy#1925]
**Reproduction Steps:**
 1. Running codenvy:latest via Docker and mounting the docker socket.
 2. In the terminal of a workspace, running on `codenvy/alpine_jdk8`, run a `docker-compose` command.

EXPECTED: Works

ACTUAL: Shows an error like: `docker.errors.DockerException: Bind address needs a port: ...`

This issue is like https://github.com/docker/docker/issues/19813 and the fix is to update `DOCKER_HOST` to include the port like `export DOCKER_HOST="$DOCKER_HOST:2375"`. Since this environment variable seems to be defined by Codenvy's workspace, I'm reporting the issue.

**Codenvy version:**
5.4.1

**OS and version:**    
Linux Ubuntu-like

**Docker version:**
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:53:29 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:53:29 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Codenvy cli.log output:**
N/A

**Comment by wernight** [comment]
I'm partially wrong here. The port should be specific but it looks like `DOCKER_HOST` is actually wrong in my case.

**Comment by wernight** [comment]
I was wondering about the origin of the current `DOCKER_HOST` which seems incorrect.

Yes mounting the docker sockets works, and it seems there is no way to access the host by port which would be the safest supposing one does setup TLS properly.

**Comment by TylerJewell** [comment]
I haven't tested it yet, but I don't see any reason why a workspace container can use TCP with the client.  You can bind a docker daemon to multiple sockets cloth unix and tcp at the same time.

And then your workspace does not need to have the volume mount added as a parameter.

**Comment by eivantsov** [comment]
By default, out of the box, we use socat container as a unix socket proxy. As a result, Docker is available over tcp at 23750.

Can you elaborate how you make sure docker and docker-compose work in a workspace container?  I can see some weird instructions here - https://github.com/codenvy/dockerfiles/blob/master/alpine_jdk8/Dockerfile#L97

So, probably just a bad stack. However, I managed to run a hello-world there:

```
bash-4.3$ docker-compose up
Pulling helloworld (ubuntu:14.04)...
14.04: Pulling from library/ubuntu
30d541b48fc0: Pull complete
8ecd7f80d390: Pull complete
46ec9927bb81: Pull complete
2e67a4d67b44: Pull complete
7d9dd9155488: Pull complete
Digest: sha256:62a5dce5ceccd7f1cb2672a571ebee52cad1f08eec9b57fe4965fb0968a9602e
Status: Downloaded newer image for ubuntu:14.04
Creating user_helloworld_1
Attaching to user_helloworld_1
helloworld_1  | Hello world
user_helloworld_1 exited with code 0
bash-4.3$
```

`DOCKER_HOST` was set to `tcp://$eth0_IP:23750`

I am pretty sure this is not what you are trying to achieve, so I am all ears :) Please, do elaborate on the use case step by step. Thanks

**Comment by wernight** [comment]
What I did is mount `/var/run/docker.sock` using `CODENVY_MACHINE_SERVER_EXTRA_VOLUME=/var/run/docker.sock:/var/run/docker.sock:ro,Z;` in `codenvy.env` and give read/write access to that file to the $UID/$GID of the user running in Che/Codenvy workspace. Also installed `docker-compose` inside that workspace.

The other "hard" part is ensuring that `/projects` on host points to `/projects` in the workspace. This is easier on Che than on Codenvy because the later has a random directly (for various users I guess). An idea would be to "leak" the absolute path of the workspace on the host to the workspace. For example `CODENVY_WORKSPACE_HOST_DIR=/home/codenvy/instance/data/codenvy/fs/85/5f/31/workspace6ckxx23415gl9u75/`.

Given I only need a single workspace that can build docker images, I just did that manually for just that workspace for now.

**Comment by wernight** [comment]
Ha I see there is a `DOCKER_HOST` in `codenvy.env`. Just seems the default value wasn't correct.

**Comment by eivantsov** [comment]
The default value must be coming from here https://github.com/codenvy/dockerfiles/blob/master/alpine_jdk8/Dockerfile#L97

DOCKER_HOST in your codenvy.env must be commented.

**Comment by TylerJewell** [comment]
@JamesDrummond - I think we should update the docs on Che & Codenvy Docker sections.  I believe in our docs, we have a section that discusses how a workspace can work with Docker, and the only option we describe today is volume mounting a unix socket.

We should outline the specifics for how to setup the following:
1. Unix socket
2. TCP socket - requires daemon to be launched (without TLS)
2a - How to setup a workspace docker client to use TLS for a secure daemon
3. fd socket - for systemd

**Comment by eivantsov** [comment]
@TylerJewell @JamesDrummond also, why do we set DOCKER_HOST in a Dockerfile?

**Comment by TylerJewell** [comment]
I have no idea.  Seems like it should not be set there.  It probably seems like it should not be in the Dockerfile itself.  Instead, we should probably think about having some sort of DOCKER_HOST injection variable performed by Che or Codenvy when starting a workspace.

**Comment by eivantsov** [comment]
@TylerJewell in case of Che we should do it only if we know that Docker listens on tcp.

**Comment by TylerJewell** [comment]
Yeah, great point.

Actually, we know that there is *always* a daemon and we know how Che is
connecting to that daemon on the command line (tcp or unix), so why do we
require users to add a Docker socket mount to their environment file?

We could just have a flag in the configuration of
"CHE_WORKSPACE_DOCKER=true|false". If it is true, then we would either
volume mount the unix socket or set DOCKER_HOST based upon what the admin
used when starting Che.


Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by eivantsov** [comment]
In fact, we can see if DOCKER_HOST is set systemwide or in che.env.

**Comment by wernight** [comment]
I changed `DOCKER_HOST` in `codenvy.env` but that didn't affect anything within the workspace.

**Comment by TylerJewell** [comment]
Yes, there is no way to set a codenvy.env property that will have environment variables updated into a workspace.  You can only set this with the REST API or the dashboard on a per workspace basis right now.

**Comment by wernight** [comment]
That makes me wonder about the use of `DOCKER_HOST` but I'd say even though it's really not ideal, it's not critically blocking either.

**Comment by TylerJewell** [comment]
This is partially influenced by our thinking on this issue - https://github.com/eclipse/che/issues/3625.  So we are starting to think about how to source a workspace's definition from an existing git repository, and then recognize that if that git repo has a Dockerfile or a docker-compose.yml file in the root, then that workspace needs to be tailored for making use of that.  That means the WS needs to have a docker client installed automatically and then a unix socket mount or DOCKER_HOST properly set.

This workflow would really help people who are accustomed to "git clone" "docker run" syntax.

But the more challenging part is that right now, git utilities and any repository reading is done inside of a ws runtime.  But if we want to source a workspace recipe from a git repo, we need to move some default git functionality into the codenvy or che master server, so that the core system can provide this functionality.

It's not hard work, but it's detailed work and can be a bit tricky to secure and scale.

**Comment by TylerJewell** [comment]
I am going to close this issue as the nature of the implementation and issue will change with Che on k8s.
