### ISSUE TITLE
Update documentation: Cannot limit port range

### ISSUE THREAD

**Issue by wernight** [codenvy/codenvy#1927]
The [current documentation](https://codenvy.com/docs/admin-guide/installation/index.html#required-ports) states that `This range can be limited.` but this doesn't seem to be the case. The only way to limit that range would be to change `/proc/sys/net/ipv4/ip_local_port_range` affecting all program on that machine.

See also https://github.com/eclipse/che/issues/1560

**Comment by bmicklea** [comment]
That's correct - I have added a clarification that the only way to limit the ephemeral range is at the host OS level.
