### ISSUE TITLE
Factory url unable to get .codenvy.json configuration in private repo

### ISSUE THREAD

**Issue by kmaillet-arcane** [codenvy/codenvy#1933]
Hi guys,

I'm unfortunately unable to use properly factory url when the .codenvy.json file is in a private repo.
To be a little clearer : 
- When .codenvy.json is in mypublicrepo the factory url https://codenvy.io/f?url=https://github.com/myorganization/mypublicrepo works perfectly, the workspace is configured and the project specified in .codenvy.json is imported

- When .codenvy.json is in myprivaterepo the factory url https://codenvy.io/f?url=https://github.com/myorganization/myprivaterepo works but the workspace gets a standard configuration ( 2000mb Ram with codenvy/ubuntu_jdk8), the project myprivaterepo is then imported regardless of what is specified in .codenvy.json

-When I use the same configuration in a regular factory, using the UI, everything works as expected

Would you guys know wether this is a bug?

Thanks

**Reproduction Steps:**
- Use the factory url https://codenvy.io/f?url=https://github.com/myorganization/myprivaterepo

**Expected Behavior**
The workspace gets configured in accordance with .codenvy.json

**Observed Behavior**
The workspace gets a standard configuration (2000mb Ram, codenvy/ubuntu_jdk8) and imports the repo in the url regardless of what is specified in .codenvy.json 

**Codenvy version:**    
5.4.1

**Comment by eivantsov** [comment]
@kmaillet-arcane afaik, currently only public repos are supported

**Comment by kmaillet-arcane** [comment]
Thank you for your answer @eivantsov I'm not sure I've ever seen that in the documentation. It might be worth it to mention it.

Cheers

**Comment by TylerJewell** [comment]
The Factory docs were written very thoroughly.  It is expected that it should work with a private repository.

**Comment by eivantsov** [comment]
@TylerJewell there's no way a Factory service can ask for credentials or oAuth before grabbing `.codenvy.json` and creating env from it. So, the behavior @kmaillet-arcane has described is the way it works now.. we start a default env from eclipse/ubuntu_jdk8 and THEN try to import a private project.

**Comment by kmaillet-arcane** [comment]
@eivantsov, @TylerJewell Just out of curiosity, will this functionality be supported any time soon? Is it on the roadmap already?

Cheers

**Comment by TylerJewell** [comment]
Probably not for at least 6 months.  We do not have anything near term that we would work on here.
