### ISSUE TITLE
Cannot use index.docker.io to store snapshots

### ISSUE THREAD

**Issue by eivantsov** [codenvy/codenvy#1936]
Steps to reproduce:

1. In codenvy.env provide credentials for your docker hub account as well as registry url as index.docker.io
2. Turn on auto snapshotting when stopping workspaces.

```
[DOCKER] [ERROR] denied: requested access to the resource is denied
Snapshot storing failed. org.eclipse.che.plugin.docker.client.exception.DockerException: Docker image pushing failed. Cause: denied: requested access to the resource is denied
```

**Comment by bmicklea** [comment]
Eugene - what severity level do you see this as?  P1?

**Comment by TylerJewell** [comment]
It's a limitation, but not something that is destabilizing.  But I believe there is already a PR open for it.

**Comment by eivantsov** [comment]
No, Roman's PR does not entirely solve it. I still have hard time pushing snapshots to dockerhub. Do you want @mmorhun take a look?

**Comment by mmorhun** [comment]
Just use `https://index.docker.io/v1/` or alias `docker.io` and registry should work.
But I agree, that alias `index.docker.io` is a good idea. I will add it soon.

**Comment by mmorhun** [comment]
done
