### ISSUE TITLE
Angular-Cli Support

### ISSUE THREAD

**Issue by markblandford** [codenvy/codenvy#1939]
I'm looking to use Codenvy for angular-cli development (https://cli.angular.io/). I thought I could just use the existing Node stack and then run `npm install -g @angular/cli`. However, this does not work (needs to be run as an administrator, not to mention the Node version in the Node stack is too old).

Can anyone help please? I'm sure this is relatively trivial but I have little idea where to start.

**Comment by eivantsov** [comment]
Run it with sudo then.

As to upgrading node version, I have updated the image - node is 7.7.3 now.

**Comment by markblandford** [comment]
Thank you so much! I have it working now.

**Comment by TylerJewell** [comment]
Awesome.
