### ISSUE TITLE
java intellisense code completion no longer working

### ISSUE THREAD

**Issue by 90301** [codenvy/codenvy#1943]
Logged into java ee workspace (tomcat 8 stack, ubuntu, with mysql installed), hit ctrl space, no window appeared. typed a known class, hit '.' then hit ctrl space, no code completion showed up. tried restarting workspace and browser, no luck on my end.
**Reproduction Steps:**
(see above)
**Codenvy version:** 
5.5.0

**OS and version:**    
windows 10 Pro
google chrome

**Comment by 90301** [comment]
Nevermind, it just stopped seeing my project as a project, or source files (src/packages) didn't register. I fixed it by making one folder below into a project. (See image for project config.)

![image](https://cloud.githubusercontent.com/assets/6025683/24058386/521acf4a-0b21-11e7-9b72-f7583217f15d.png)

**Comment by TylerJewell** [comment]
:)
