### ISSUE TITLE
Eclipse che user management

### ISSUE THREAD

**Issue by srinivasmaybank** [codenvy/codenvy#1956]
I want to maintain user management from admin side with the api. Do we have any api available for eclipse che

create user
use the credentials to login into the che.
Maintain session if required.

 

**Reproduction Steps:**

**Codenvy version:**    

**OS and version:**    

**Docker version:**    

**Codenvy cli.log output:**

**Comment by TylerJewell** [comment]
Eclipse Che does not have a concept of user management.  But codenvy does.  See the rest API and navigate it with swagger for details.
