### ISSUE TITLE
Unexpected warning dialog after consume a factory (regression)

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#1958]
**Step to reproduce: ** Consume a factory several times.
![com codenvy ide factory checkbitnamyfactoriestest checkgitlaburl_3tg27ef9](https://cloud.githubusercontent.com/assets/1640058/24094408/3ae69f2e-0d61-11e7-8f68-45f2606781d3.png)

**OS and version:**   Ubuntu 14.0 TLS
**Codenvy version:** 5.6.0-SNAPSHOT
**Server location:** nightly.codenvy-stg.com
**The problem can be related on:** https://github.com/codenvy/codenvy/issues/1908

**Comment by mshaposhnik** [comment]
Can you explain a little more?  I see that project clone is still in progress, but a warning appeared ?  What happened when cloning finished? What is factory WS creation policy?

**Comment by musienko-maxim** [comment]
This widget  appears in any cases (if a project is cloned as properly or wrong). **Step for reproduce:** Create a project -> create the factory from IDE and consume it. I think it problem appeared after changes Valery Svidenko (synchronization of content project explorer with file system). You can clarify this one with him
