### ISSUE TITLE
All history and installed apps are gone

### ISSUE THREAD

**Issue by rajat1saxena** [codenvy/codenvy#1961]
**Reproduction Steps:** I am using free account. So, it went on "stop mode" when left un-operated for like 10+ minutes. When I restarted the workspace, everything seemed to have reset itself, to a `fresh installation` state.

**Codenvy version:**    

**OS and version:**    

**Docker version:**    

**Codenvy cli.log output:**

**Comment by bmicklea** [comment]
@rajat1saxena - we have implemented a snapshot on stop in the system now. This should not occur again but if it does please let us know.
