### ISSUE TITLE
How do I get a mysql DB machine?

### ISSUE THREAD

**Issue by JeffRocchio** [codenvy/codenvy#1962]
Am trying to end up with an Apache, PHP and MySql (or MariaDB) environment. I have tried to create a few different workspaces that say MySql or MariaDB is part of the environment, but I never seem to end up with the database installed. I don't see any DB machine, and any attempt to connect to mysql from the terminal fails with 'unable to connect to socket' error.

For example, creating a new workspace using the Ready-to-Go stack "PHP"; which says it includes MySql, yet MySql doesn't actually seem to get installed.

Also, how do I know what the admin password is for the virtual OS (that is, in Terminal, to, say install software or otherwise act at root)? As I presume I could just install MySql myself from there?

Codenvy.io SaaS

Codenvy Version: 5.5.0

**Comment by TylerJewell** [comment]
@JeffRocchio - try the java / mysql stack as a default stack.  it defines a docker compose service that has multiple containers, with one of them being mysql.

**Comment by eivantsov** [comment]
@JeffRocchio mysql is part of php stack. You just need to start it - `sudo service mysql start`

And you do not need any password to install software as root.

**Comment by JeffRocchio** [comment]
That is too easy, duh on me for not trying that. Will I need to
run mysql_secure_installation to set up the root user and such, or did the
build scripts already do that?

**Comment by eivantsov** [comment]
root user should be already there.

**Comment by JeffRocchio** [comment]
MySql root user apparently was not there as attempting to login as root
caused MySql to spit out it's help response (vs bad password if root had
existed). So I did run mysql_secure_installation, set up root with my own
password, got rid of anoyn user and all that jazz. I was then able to
create my development database shell. So all seems to be well on the MySql
front. Now on to importing my existing dev tables into it...  Getting there
one step at a time. Thanks so much for your help with this.


Jeffrey Rocchio
704-584-9133 | jeffrocchio@gmail.com

<http://www.linkedin.com/in/jeffrocchio>

**Comment by eivantsov** [comment]
I was able get into mysql shell `mysql -u root`

**Comment by JeffRocchio** [comment]
hmmm... ok. I could swear I did try it without a password; but maybe my
memory is bad. It might be a good idea to put the mysql info into the
readme.txt file that the stack build creates so that users have a natural
way to know what the state of mysql is in after the build; along with some
hints on usage, like the readme does for Apache notes in the readme.


Jeffrey Rocchio
704-584-9133 | jeffrocchio@gmail.com

<http://www.linkedin.com/in/jeffrocchio>

**Comment by eivantsov** [comment]
@JeffRocchio yes, that's definitely a good idea. Will do that in a few days.

**Comment by JeffRocchio** [comment]
To add to the readme, and can you help me now - _what is the hostname to use to connect to MySql_ from a PHP script?  

I am just trying to make a simple connection to prove I can. But haven't been able to do so yet. I can't get the debugger to work, which is another thread running here, so can't see everything. But it looks to me like I don't have the right hostname to make the MySql connection. I started with the assumption it would be 'localhost.' but that failed. Then I used ini_get(), but that comes up NULL. So I queried MySql itself to see what it thinks the hostname is (mysql> select @@hostname;), and it returned: "b1b6dbd64bf8."

My php code, for what it's worth:
`$mysqlHost = ini_get(mysql.default_host); `
`echo "MySql Host using ini_get(): {$mysqlHost}<BR />";`
`$mysqlHost = "b1b6dbd64bf8";`
`echo "MySql Host hard-coded: {$mysqlHost}<BR />";`
`$link = mysql_connect($mysqlHost, 'php', 'php');`

The output:
MySql Host using ini_get():
MySql Host hard-coded: b1b6dbd64bf8

But then the page terminates right after the mysql_connect() call (php, with password php is a user I created in the MySql instance).

**Comment by eivantsov** [comment]
So, you want an example of php code that connects to a db?

**Comment by JeffRocchio** [comment]
Hey - the description for the stack say's "php 5.6"; so I didn't even think to run phpinfo(); but in doing so just now I see it is running php 7.x; so that's why mysql_connect() is failing; it is now fully removed from PHP 7. I do apologize if I am being dense with all my questions. I am definitely not used to running in virtual/cloud environments and am obviously struggling to work it all out. But, I do actually need a PHP 5.x environment so I can migrate to PHP 7.

**Comment by eivantsov** [comment]
This has just worked for me:
```
<?php
$servername = "localhost";
$username = "che";
$password = "che";

// Create connection
$conn = mysqli_connect($servername, $username, $password);

// Check connection
if (!$conn) {
    die("Connection failed: " . mysqli_connect_error());
}
echo "Connected successfully";
?>
```

**Comment by eivantsov** [comment]
And it's php7. Stack description is wrong.

**Comment by eivantsov** [comment]
This PR fixes  - https://github.com/eclipse/che/pull/4561

**Comment by eivantsov** [comment]
And this commit adds clarity to db access - https://github.com/che-samples/web-php-simple/commit/765842059a3a1c85225215bd4eab0b2cc6bc88da

Closing the issue.

**Comment by Khayrabadi** [comment]
Same issue:
first i start mysql by sudo command and then
next command: 
`mysql -u root` 

issue happend:
`ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)`

**Comment by eivantsov** [comment]
@Khayrabadi what stack did you use?

**Comment by Khayrabadi** [comment]
Php 5.6 is my stack

در تاریخ ۵ اکتبر ۲۰۱۷ ۱۷:۲۷، "Eugene Ivantsov" <notifications@github.com>
نوشت:

**Comment by eivantsov** [comment]
https://github.com/eclipse/che-dockerfiles/blob/master/recipes/php/5.6/Dockerfile#L40
So, it's `root`

**Comment by Khayrabadi** [comment]
```
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run
/mysqld/mysqld.sock' (111)
```

**Comment by eivantsov** [comment]
@Khayrabadi perhaps you need to start MySQl first?

**Comment by Khayrabadi** [comment]
i did it at first
cli says it's running

**Comment by eivantsov** [comment]
Perhaps, you are doing smth wrong. Here's how it works on my side with php 5.6 stack:

```
user@e7fb11ad8f3f:/projects$ sudo service mysql start
[ ok ] Starting MySQL database server: mysqld ..
[info] Checking for tables which need an upgrade, are corrupt or were
not closed cleanly..
user@e7fb11ad8f3f:/projects$ sudo service mysql status
[info] /usr/bin/mysqladmin  Ver 8.42 Distrib 5.5.57, for debian-linux-gnu on x86_64
Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Server version          5.5.57-0+deb8u1
Protocol version        10
Connection              Localhost via UNIX socket
UNIX socket             /var/run/mysqld/mysqld.sock
Uptime:                 7 sec

Threads: 1  Questions: 587  Slow queries: 0  Opens: 173  Flush tables: 1  Open tables: 41  Queries per second avg: 83.857.
user@e7fb11ad8f3f:/projects$ mysql -u root --password="root"
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 45
Server version: 5.5.57-0+deb8u1 (Debian)

Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| che_db             |
| mysql              |
| performance_schema |
+--------------------+
4 rows in set (0.00 sec)
```

**Comment by Khayrabadi** [comment]
thanks
 it works

**Comment by trupnil** [comment]
yeah its works !

**Comment by trupnil** [comment]
can we get GUI link for the database?
