### ISSUE TITLE
It's not allowed to share personal workspace

### ISSUE THREAD

**Issue by sleshchenko** [codenvy/codenvy#1963]
It's not allowed to share personal workspace

**Reproduction Steps:**
1. Login on codenvy onprem instance
2. Create a workspace.
3. Try to share the workspace.

![anim](https://cloud.githubusercontent.com/assets/5887312/24140907/5836b928-0e2a-11e7-9553-80fd084ed229.gif)

**Codenvy version:**    
5.6.0-SNAPSHOT

**Comment by bmicklea** [comment]
@akurinnoy what's the status of this fix?  Is there a PR open yet?

**Comment by akurinnoy** [comment]
@bmicklea PR is opened
