### ISSUE TITLE
Did I lose my work ?

### ISSUE THREAD

**Issue by mbenmass** [codenvy/codenvy#1966]
Dear Codenvy team,

I am a complete newbie to cloud computing in general and to Codenvy in particular.

I created a workspace yesterday, and worked on some Java code during a couple of hours.
At some point, I fell asleep. 

When I tried to run my workspace today, I got an error message :

[DOCKER] Step 1 : FROM codenvy.io:5000/machine_snapshot_lswwcqb3qrd07bb3:latest
[DOCKER] latest: Pulling from machine_snapshot_lswwcqb3qrd07bb3 
[DOCKER] 8aec416115fd: Already exists 
[DOCKER] 695f074e24e3: Already exists 
...
[DOCKER] 520bfce68828: Already exists 
[DOCKER] 4aa9269702fc: Pulling fs layer 
[DOCKER] bc32314d210c: Pulling fs layer 
[DOCKER] 4aa9269702fc: Retrying in 5 seconds 
[DOCKER] bc32314d210c: Downloading 154.2 kB/14.29 MB
[DOCKER] bc32314d210c: Downloading 318.1 kB/14.29 MB
...
[DOCKER] 4aa9269702fc: Retrying in 1 second 
[DOCKER] 4aa9269702fc: Downloading 113.7 MB/113.7 MB
[DOCKER] 4aa9269702fc: Retrying in 15 seconds 
...
[DOCKER] 4aa9269702fc: Retrying in 2 seconds 
[DOCKER] 4aa9269702fc: Retrying in 1 second 
[DOCKER] 4aa9269702fc: Downloading 113.7 MB/113.7 MB
[DOCKER] [ERROR] unexpected EOF
[ERROR] Docker image build failed. Image id not found in build output.

Could not start workspace xxxx. Reason: Start of environment 'default' failed. Error: Docker image build failed. Image id not found in build output.

Is there a way I could recover my work please ?

Thanks for your help
Mehdi

**Comment by eivantsov** [comment]
It looks like some issues with Docker. Can you give it a try again? By the way, you may not recover your machine from a snapshot - project sources are backed up independently.

**Comment by mbenmass** [comment]
Thank you for your prompt reply.

I tried several times without success.

**Comment by mbenmass** [comment]
Grateful if some charitable soul helps me recover my work.

**Comment by eivantsov** [comment]
@mbenmass when starting a workspace, do you see a prompt if you want to recover it from a snapshot? When prompted, click No, and your workspace will start.

**Comment by mbenmass** [comment]
Much appreciated. Working now.
