### ISSUE TITLE
Run docker inside workspaces

### ISSUE THREAD

**Issue by josezuazo** [codenvy/codenvy#1967]
Hi,

I need to use docker inside the workspaces but I can not find documentation regarding the subject (I only find docs about [Che in Che](https://codenvy.com/docs/tutorials/che-in-che/index.html))
Is there anything I need to consider when creating a recipe for ubuntu with docker?

Thanks,
José

**Comment by TylerJewell** [comment]
We discuss the elements about details for it here - https://www.eclipse.org/che/docs/ide/docker/index.html.  

To add Docker to a stack, you either need to install it, use one of the docker-certified images that has docker already installed, or consider a docker-in-docker image, which also poses some risks.

**Comment by josezuazo** [comment]
Hi @TylerJewell,

Maybe I'm doing something wrong...
I create a new workspace using the **Blank Stack** in **codenvy.io** and then install docker as specify in that document.

> Add Docker CLI To Your WorkspacePermalink
> There are many ways to do this. If you are in the terminal, you can follow the instructions to install Docker on the command line at Docker’s web site.

Everything goes fine but when I try to use docker, I see the following error:

![screen shot 2017-03-21 at 12 07 25](https://cloud.githubusercontent.com/assets/19619549/24154324/9c7f996a-0e2f-11e7-93af-c5e7c9322c66.png)

What I'm doing wrong?

Thanks in advance,
José

**Comment by TylerJewell** [comment]
This would be an issue for you to raise with Docker.  But why are you starting with a blank stack?  Why not create a recipe that inherits from one of the certified Docker images that already has Docker installed?

This is one - for example - florentbenoit/che-in-che.

**Comment by eivantsov** [comment]
@josezuazo @TylerJewell  this is not possible with codenvy.io but possible in Che.

Running Docker in a workspace is possible either if a container is running in a privileged mode - a true dind, or DOCKER_HOST is exported. None is possible on codenvy.io due to security reasons.

**Comment by josezuazo** [comment]
@TylerJewell @eivantsov thanks for the help!
