### ISSUE TITLE
C++ header files with extension .h are not highlighted

### ISSUE THREAD

**Issue by achristianson** [codenvy/codenvy#1980]
C++ header files (extension .h) are not syntax-highlighted. This makes it very difficult to develop C++ projects. The project in question is Apache MiNiFi.

**Reproduction Steps:**

Create C++ project, create header file with .h extensions, add some C++ code. Note that it is not syntax-highlighted.

**Codenvy version:**    codenvy.io 5.5.0

**OS and version:**    

**Docker version:**

**Codenvy cli.log output:**

**Comment by TylerJewell** [comment]
This capability would be added as part of a clangd / CDT C++ language server that is coming shortly. 

https://github.com/eclipse/che/issues/699
