### ISSUE TITLE
Opening a .py file hangs on "Initializing Language Server for py" and causes a crash

### ISSUE THREAD

**Issue by 20avva** [codenvy/codenvy#1983]
I am trying to open a `.py` file from the [octokit/octokit.py](https://github.com/octokit/octokit.py) that I cloned using "Import Project." All the `.py` files are being displayed in the Project Explorer as `.c` files. When I double click on them to open them in the Editor, a dialog box pops up and read `Initializing Language Server for py` and I cannot close it. After a minute of waiting, it caused by browser tab to freeze and crash. 

**Reproduction Steps:**

1. `Workspace -> Import Project -> GITHUB`
2. Clone from `git@github.com:octokit/octokit.py`
3. When the cloning is complete, the `.py` files have a the appearence of C files in the Project Explorer
4. Double click the `.py` files to open them in the Editor
5. The dialog mentioned above appears and I can't do anything in the Codenvy window I had open

**Codenvy version:**    Wed IDE v5.5.0, Ubuntu 14.04 Stack

**OS and version:**  Running from a Chromebook 56.0.2924.110 (Official Build) (64-bit), using the web Codenvy IDE v5.5.0

**Docker version:** N/A

**Codenvy cli.log output:** N/A

**EDIT**: This problem only occurs in an Ubuntu stack, and works fine with a Python stack

**Comment by eivantsov** [comment]
@20avva i cannot reproduce this behavior. Did you choose Python stack for your workspace?

![image](https://cloud.githubusercontent.com/assets/5337267/24323693/e55dbc16-1136-11e7-8358-d315f97f97db.png)

Files can be opened:

![image](https://cloud.githubusercontent.com/assets/5337267/24323741/c4dfbd8a-1137-11e7-82ac-af256d2fa91a.png)

**Comment by 20avva** [comment]
I was using a generic Ubuntu stack, but I will try using a Python stack.

**Comment by 20avva** [comment]
So, I just started up a new Python stack, and it works fine, just like @eivantsov mentioned. Is this supposed to happen? The Ubuntu stack doens't open python files

**Comment by TylerJewell** [comment]
Definitely not good behavior.  @eivantsov - I am not able to get GitHub
access directly for tagging.  But this would be a `kind/bug` with
`severity/p1`.

Blanks stacks without a project type shouldn't cause any hanging scenarios
when opening unrecognized file types.


Tyler Jewell // CEO // tyler@​codenvy.​com // 978.884.5355

**Comment by eivantsov** [comment]
@20avva can you provide detailed steps to reproduce? I was able to open .py files in an Ubuntu stack.

**Comment by 20avva** [comment]
@eivantsov Yes, I have the Python language server enabled.

**Comment by eivantsov** [comment]
There's a registered issue: https://github.com/eclipse/che/issues/4586

**Comment by 20avva** [comment]
I figured out what the problem was, pip3 wasn't installed, and when the workspace was launched, I noticed

```
[STDERR]pip3 isn't installed
```

so when I installed pip3 through the command line, I relaunched the workspace, and my python files opened up fine. Thanks for all the help anyway!

**Comment by eivantsov** [comment]
https://github.com/eclipse/che/issues/4586 is foxed in masted
