### ISSUE TITLE
No PHP 5 stack?

### ISSUE THREAD

**Issue by JeffRocchio** [codenvy/codenvy#1984]
Despite the descriptions for the available PHP stacks, they all build with the newer PHP 7 (several of the descriptions still say 'php 5...' but you really get php 7 when the workspace builds).

However, I do actually need php 5. I don't suppose there is any fast and easy way to php 5.x LAMP stack is there?

**Reproduction Steps:**
   1. Select this stack to build a new workspace: "_Default PHP Stack with PHP 5.6, most popular extensions..._"
   2. Have it build the new workspace.
   3. Modify the hello.php file to add line `echo phpinfo();`
   4. Start Apache.
   5. Run the hello.php file.
   6. See that the version of PHP is actually 7.0 despite all the descriptions.

**Codenvy version:**  SaaS ver 5.0

**OS and version:**   I am on a Fedora 25, KDE spin workstation

**Docker version:** NA I assume

**Codenvy cli.log output:**  NA

**Comment by eivantsov** [comment]
Yes, we have upgraded PHP stack to 7.0

Here's a PR that fixes it in a description https://github.com/eclipse/che/pull/4561

You can create your own custom stack though with any PHP version.

**Comment by JeffRocchio** [comment]
Ok. Creating my own stack may be an adventure for me. Time permitting tho I
may give it a go. Thanks.


Jeffrey Rocchio
704-584-9133 | jeffrocchio@gmail.com

<http://www.linkedin.com/in/jeffrocchio>

**Comment by eivantsov** [comment]
Some docs: http://www.eclipse.org/che/docs/workspace/stacks/index.html

I may help you a bit later this weekend with an actual Dockerfile. It's not as difficult as it might seem.

**Comment by JeffRocchio** [comment]
Cool, I shall study the documentation. Timing may be an issue for me only
in that I am getting ready to drive across the country mid-next week
(Charlotte to Portland, OR) and am packing and getting chores done and
such. But this is something I am definitely interested in working out.


Jeffrey Rocchio
704-584-9133 | jeffrocchio@gmail.com

<http://www.linkedin.com/in/jeffrocchio>

**Comment by eivantsov** [comment]
Thsi PR https://github.com/eclipse/che/pull/4633 adds PHP5 stack to stack library: will be there in the next version. Meanwhile you may use eclipse/php:5.6 when creating a custom stack - https://www.eclipse.org/che/docs/workspace/stacks/index.html

**Comment by JeffRocchio** [comment]
Thanks so much Eugene!


On Mar 30, 2017 3:20 AM, "Eugene Ivantsov" <notifications@github.com> wrote:

Thsi PR eclipse/che#4633 <https://github.com/eclipse/che/pull/4633> adds
PHP5 stack to stack library: will be there in the next version. Meanwhile
you may use eclipse/php:5.6 when creating a custom stack -
https://www.eclipse.org/che/docs/workspace/stacks/index.html

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/codenvy/codenvy/issues/1984#issuecomment-290324231>,
or mute
the thread
