### ISSUE TITLE
Giving bad url to remote dockerfile causes build to hang

### ISSUE THREAD

**Issue by jonathanjfshaw** [codenvy/codenvy#1985]
Stack hangs when bad remote url is given as recipe location.

**Reproduction Steps:**
Clone the PHP stack
Set the default environment recipe to:
```
        "recipe": {
          "location": "https://somebadurl.com/here",
          "type": "dockerfile",
          "contentType": "text/x-dockerfile"
        },
```
Save the stack
Press "Test"
See it hang

**Codenvy version:**    online 5.5.0

**OS and version:**    

**Docker version:**    

**Codenvy cli.log output:**

**Comment by garagatyi** [comment]
@TylerJewell should we move it to Che?

**Comment by eivantsov** [comment]
This issue was moved to eclipse/che#5657
