### ISSUE TITLE
Queries related to organization resources are most time consuming

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#1986]
<img width="1069" alt="2017-03-27 10 59 58" src="https://cloud.githubusercontent.com/assets/1614429/24346494/3f9d2ae8-12dd-11e7-9c69-0659fc899980.png">
There is couple of suggestion how to improve it.

1. Reduce number of queries. Logic should be revised, may be with some kind of caching or event listening technique we can avoid 64k queries per day
2. Now we define unlimited number of sub-organization.  This is potentially hard to implement on relational database.  Suggested to limit number of level to 4 and replace queries ```t0.name LIKE 'donjitsu/%'```  with some simple comparison. It can be done if each level of organization will be put in distinct column.

**Comment by sleshchenko** [comment]
Postresql queries with LIKE can be improved by creating special text_pattern_ops index.
`CREATE INDEX index_account_pattern ON account(name text_pattern_ops);`
Output of `EXPLAIN ANALYZE` queries:
Without index
![2](https://cloud.githubusercontent.com/assets/5887312/24398037/c9825f66-13b0-11e7-9037-5339da0eb4ac.png)
With index
![1](https://cloud.githubusercontent.com/assets/5887312/24398044/d2930c68-13b0-11e7-810c-a135da90ec39.png)

**Comment by sleshchenko** [comment]
Pattern index for speed up LIKE-based queries added by following commit https://github.com/codenvy/codenvy/pull/2058/files#diff-02db4ee88714cc4d41349aac909d4655R16
