### ISSUE TITLE
Previewing projects at http://domain:port/, not at http://domain:port/project-name/

### ISSUE THREAD

**Issue by jonathanjfshaw** [codenvy/codenvy#1991]
Using codenvy.io, is it possible to preview a project using a top-level URL?

Some web apps like Drupal or Laravel get complicated when you try to run them in a subfolder, not at the top of the domain.

I could try having 1 project per workspace, and just dump it into the projects folder. I think what I lose by this is speed of spinning up new codebases to review patches etc, because a) I don't get to do so much caching of dependencies and reference codebases, so everything has to be recalculated and installed from remote, and b) I have the considerable overhead of firing up the workspace itself.

**Comment by eivantsov** [comment]
@jonathanjfshaw If you can configure Drupal or Laravel running on a top domain, you will have the same preview URL. Setting document root to `/projects` is what we do in a PHP stack now since we don't know what projects will show up there.

**Comment by eivantsov** [comment]
Closed due to inactivity.
