### ISSUE TITLE
Deciding between stacks, workspaces, project templates, and projects

### ISSUE THREAD

**Issue by jonathanjfshaw** [codenvy/codenvy#1992]
It's not obvious from the Codenvy documents what the pros and cons of workspaces vs project templates vs projects are. It would be helpful if the docs could provide guidance on the decision tree involved in choosing which I need to modify to achieve a certain goal.

I could have 1 custom stack and no project template and only 1 project per workspace. Or I could have 2 custom stacks, multiple project templates, and multiple projects per workspace. Or anything in between. The tradeoffs are not obvious.

What can a project template do that a stack can't?
What do I get from having multiple projects in a single workspace?
What really is a project in Codenvy land anyway?

I'm not expecting an answer, I just hope my confusion is helpful for planning what docs are needed

**Comment by TylerJewell** [comment]
​Hi Jonathan:

I just reread the docs, and I think they are relatively clear, so not quite
sure the confusion you are running into.

Stacks = customized runtimes (ie, software that is installed and booted).
Recipe = Dockerfile or Composefile part of a stack, to define how it will
be built and started
Environments = an instance of a runtime ... workspaces can have multiple
runtimes but only 1 running at any given time.  You may want a dev runtime
vs. a qa runtime, for example.
Templates (or Samples) = source code project trees that can be cloned into
a running workspace ... or you can have a user git clone from within the
workspace that is running.
Projects = a mapping of source code to a single repository.  Projects can
have "type" which imbues special types of visualizations in the project
tree, loads additional command, provides command types (ie, such as a maven
command).

This is largely similar to what happens on a desktop IDE, the only real
difference is the introduction of a stack concept.​


Tyler Jewell // CEO // tyler@​codenvy.​com // 978.884.5355

**Comment by eivantsov** [comment]
Closing the issue. @jonathanjfshaw feel free to reopen if you have more questions.
