### ISSUE TITLE
Add user details page (for system admin only)

### ISSUE THREAD

**Issue by ashumilova** [codenvy/codenvy#2005]
As a system admin, I must be able to see the list of organization/sub-org for a particular user (need a user's details screen)

**Comment by olexii4** [comment]
![selection_009](https://cloud.githubusercontent.com/assets/6310786/25431961/602e6b8a-2a8b-11e7-8025-269ad7e7846c.png)
![selection_008](https://cloud.githubusercontent.com/assets/6310786/25431966/62b051fc-2a8b-11e7-9288-20a69b7e6bbf.png)
