### ISSUE TITLE
Loading of sub-organization details is flickering

### ISSUE THREAD

**Issue by ashumilova** [codenvy/codenvy#2006]
Loading of sub-organization details is flickering
![previous-content-displayed](https://cloud.githubusercontent.com/assets/1636769/24362339/bf962946-130c-11e7-8365-c6adf625b662.gif)

**Comment by akurinnoy** [comment]
https://github.com/codenvy/codenvy/pull/1965/commits/d3b8dd837b8790ae757c71579828400e16d4e656
