### ISSUE TITLE
How to deploy codenvy in swarm?

### ISSUE THREAD

**Issue by bobowang2017** [codenvy/codenvy#2007]
How to deploy codenvy in swarm which made the workspace running in different swarm node?

**Comment by eivantsov** [comment]
@bobowang2017 swarm is already part of Codenvy. There's no need for any extra configuration. All you need is to add machine nodes and swarm will deploy containers depending on health of swarm nodes.

**Comment by bobowang2017** [comment]
I used command 'docker run codenvy/cli start' to start the Codenvy, and my swarm has 3 nodes in.
--------------------------------------------------------------------------------------------------------------
docker node ls
ID                                                    HOSTNAME        STATUS  AVAILABILITY  MANAGER STATUS
0nfdwbqxf3ov667ap1v5d51vo    wh-2.novalocal       Ready        Active        
k7gf9etm2ucejsi0ezooqycge               wh-3                Ready        Active        
nga0fp7281rismasmh0c2y4bs   *        wh-1                Ready        Active                Leader
--------------------------------------------------------------------------------------------------------------
The description above is my swarm, and I start the codenvy in the leader node. But I find that all the docker container running in the leader node and not distributed to the worker node? Is the something wrong in my prodecure?
Can you provide your procedure to me? thank you

**Comment by eivantsov** [comment]
@bobowang2017 there's nothing wrong with your configuration. Codenvy uses own Swarm engine deployed as a Docker container. All Codenvy containers are running on one node and it is intended to be so. Workspace containers can run on different swarm nodes, but again, it is Codenvy's swarm that is responsible for it.

Here are some docs - https://codenvy.io/docs/admin-guide/installation/index.html

**Comment by bobowang2017** [comment]
@eivantsov thank you very much
