### ISSUE TITLE
Add "resend invitation" option for team member invites

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#2010]
When you invite a user to join your Codenvy team you should be able to choose to resend the same invitation in the event that they did not receive it.

**Comment by eivantsov** [comment]
@bmicklea @slemeur is this still a valid enhancement request?

**Comment by bmicklea** [comment]
Yes, it's expected functionality that we are missing.

**Comment by eivantsov** [comment]
This issue was moved to eclipse/che#5702
