### ISSUE TITLE
Cover organization management feature with automation tests

### ISSUE THREAD

**Issue by ashumilova** [codenvy/codenvy#2014]
The organization management feature is rather big and should be divided by user stories, which are determined by type of assembly (saas or onprem) and user's role (sysem admin, common member of the organization, admin of the organization).

**System Admin in onprem**
- [ ] The "Organizations" menu item is present in Administration section (Users | Organizations | Settings); the number of root organizations in displayed in brackets
- [ ] The "Organizations" menu item redirects to the list of **only** root organizations. On the page button "Add organization" is present
- [ ] The "Organizations" list contains following columns: Name, Members, Total RAM, Available RAM ,  Sub-Organizations, Actions.
- [ ] The "Add organization" button redirects to Create New Organization page with input to provide the name, members section and "Create Organization" button (has disabled state when name input is empty or invalid).
- [ ] After organization creation - admin is redirected to created organization details.
- [ ] Organization details page contains: the title, back button in the left corner (redirects to the organization list). Settings page: name (can be edited), Workspace CAP, Running Workspace CAP, RAM CAP, Delete button (displays confirmation dialog before deletion). Members page: the list of members, Add Member button. Sub-Organizations page: the list of sub-organizations, or the empty list message, Add Sub-Organization button.
- [ ] Sub-Organization creation redirects Sub-Organization details. The back button on Sub-Organization details page toolbar redirects to parent organization.
- [ ] Member to the root organization is invited by providing email(s) in the input box
- [ ] Member to the sub-organization is invited through the list of members of the parent organization

**Organization Admin in onprem**
- [ ]  The "Organizations" menu item is present in the main navbar section (Factories | Organizations); the number of **all** organizations in displayed in brackets
- [ ]  The "Organizations" menu item redirects to the list of **all** organizations with sub-organizations as a plain list. On the page button "Add organization" is absent.
- [ ] Organization details page contains: the title, back button in the left corner (redirects to the organization list or parent organization if there is so). Settings page: name (can be edited if is admin of this organization), CAPs (editable if admin of parent organization), Delete button (if is admin of this organization) (displays confirmation dialog before deletion). Members page: the list of members, Add Member button(if is admin of this organization). Sub-Organizations page: the list of sub-organizations, or the empty list message, Add Sub-Organization button (if is admin of this organization).
- [ ] The workspace creation page contains the list of all organizations, where user is member of (roots as well + personal).

**Organization Member in onprem** 
- [ ]  The "Organizations" menu item is present in the main navbar section (Factories | Organizations); the number of all organizations in displayed in brackets
- [ ]  The "Organizations" menu item redirects to the list of **all** organizations with sub-organizations as a plain list. On the page button "Add organization" is absent.
- [ ] Organization details page contains: the title, back button in the left corner (redirects to the organization list). Settings page: name, CAPS. Members page: non-editable list of members. Sub-Organizations page: the list of sub-organizations (only those where he is really member of, not whole list ), or the empty list message, Add Sub-Organization button (if is admin of this organization).
- [ ] The workspace creation page contains the list of all organizations, where user is member of (roots as well + personal).

**NOTE** The organization list for NOT system admin user can contain organizations where he has some management permissions or not, that's why the actions on organization pages will differ for this very user, depending on his permission in the concrete organization.

**NOTE** NO Teams menu present in onprem.

**System Admin in SAAS**
- [ ] The "Organizations" menu item is present in Administration section (Users | Organizations | Settings); the number of root organizations in displayed in brackets.
- [ ] The organizations behave the same as for System Admin in onprem.
- [ ] Has the Teams menu sections and there are duplicates there from sub-organizations. 

**Common SAAS user**
- [ ] No Organization menu is present
- [ ] The Team section is present in navigation bar

**Comment by dmytro-ndp** [comment]
@ashumilova: FYI: selenium tests from **[organization_tests](https://github.com/codenvy/qa/tree/organization_tests)** branch were merged into **master** branch of [qa](https://github.com/codenvy/qa) repo.

**Comment by ashumilova** [comment]
thank you

**Comment by dmytro-ndp** [comment]
Test list:
- [Organization tests](https://github.com/codenvy/qa/blob/master/che-selenium-test/src/test/resources/suites/OrganizationSuite.xml)
- [Team tests](https://github.com/codenvy/qa/blob/master/che-selenium-test/src/test/resources/suites/TeamSuite.xml)

Commands to start tests:
1. Organization tests: 
`./webdriver.sh --codenvy --https --host=nightly-onprem.codenvy-stg.com --suite=OrganizationSuite.xml --threads=1 -Mlocal`
1. Team tests: 
`./webdriver.sh --saas --https --host=nightly.codenvy-stg.com --suite=TeamSuite.xml --threads=1`
