### ISSUE TITLE
Android emulator not starting

### ISSUE THREAD

**Issue by luisinserra** [codenvy/codenvy#2024]
In a Android project, i get VNC address.
When connected, it shows the green screen, where I was used to right click to open the menu:
Terminal
Emulator

Clicking Emulator would start android emulator.

It is not starting.

![delt](https://cloud.githubusercontent.com/assets/19390679/24557023/a7f7d282-160c-11e7-8377-1e90c77358c7.jpg)

**Comment by eivantsov** [comment]
It starts, but takes a while to load:

![image](https://cloud.githubusercontent.com/assets/5337267/24576242/e3102dba-16c0-11e7-9601-d0f2e53ed7eb.png)

**Comment by eivantsov** [comment]
Closed due to inactivity.
