### ISSUE TITLE
I want run codenvy in my local,but failed  and prompt me your admin has not accepted the license agreement

### ISSUE THREAD

**Issue by leihuf** [codenvy/codenvy#2026]
I want run codenvy in my local,but failed and prompt me "your admin has not accepted the license agreement", I don't no why ，someone can help me？

**Comment by eivantsov** [comment]
Login with admin/password and accept license agreement.

**Comment by leihuf** [comment]
But  when I  register my account also failed, and prompt "your admin has not accepted the license agreement"

**Comment by eivantsov** [comment]
First login as admin. Credentials are admin/password

**Comment by leihuf** [comment]
@eivantsov  thank you!
