### ISSUE TITLE
PostgresSQL stack

### ISSUE THREAD

**Issue by deveborn** [codenvy/codenvy#2027]
Sorry if this question should have been asked in another forum but  I did not find another place (please redirect me if I am wrong). I am new to codenvy (and not a professional programmer). I wanted to setup an environment with java and postgresSQL but have not been successfull. As I understand there is no ready-to-go stack that includes postgres? I tried to install postgresSQL on the dev-machine but had trouble get it started.

Is there an easy way to setup a workspace with java and postgres? If so what steps would that include? Should I avoid to make custom installations on the dev-machine for other reasons than simplification of reproduction of the workspace?

**Comment by eivantsov** [comment]
@deveborn I will share a custom recipe that you may reuse. Probably by Monday.

**Comment by eivantsov** [comment]
@deveborn here's how you can create a Java/maven env with Postgresql installed. psql is started in the cmd, so when you are in your workspace it's up and running.

```
FROM eclipse/ubuntu_jdk8
USER root
RUN set -ex; \
    key='B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8'; \
    export GNUPGHOME="$(mktemp -d)"; \
    sudo gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
    sudo gpg --export "$key" > /etc/apt/trusted.gpg.d/postgres.gpg; \
    rm -r "$GNUPGHOME"; \
    sudo apt-key list
ENV PG_MAJOR 9.6
ENV PG_VERSION 9.6.2-1.pgdg80+1
RUN sudo echo 'deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main' $PG_MAJOR > /etc/apt/sources.list.d/pgdg.list
USER user
RUN sudo apt-get update \
    && sudo apt-get install -y postgresql-common \
    && sudo sed -ri 's/#(create_main_cluster) .*$/\1 = false/' /etc/postgresql-common/createcluster.conf \
    && sudo apt-get install -y \
	postgresql-$PG_MAJOR=$PG_VERSION \
	postgresql-contrib-$PG_MAJOR=$PG_VERSION \
    && sudo rm -rf /var/lib/apt/lists/*
RUN sudo mv -v /usr/share/postgresql/$PG_MAJOR/postgresql.conf.sample /usr/share/postgresql/ \
    && sudo ln -sv ../postgresql.conf.sample /usr/share/postgresql/$PG_MAJOR/ \
    && sudo sed -ri "s!^#?(listen_addresses)\s*=\s*\S+.*!\1 = '*'!" /usr/share/postgresql/postgresql.conf.sample
RUN sudo mkdir -p /var/run/postgresql && sudo chown -R postgres:postgres /var/run/postgresql && sudo chmod g+s /var/run/postgresql
ENV PATH /usr/lib/postgresql/$PG_MAJOR/bin:$PATH
ENV PGDATA /var/lib/postgresql/data
RUN sudo mkdir -p "$PGDATA" && sudo chown -R postgres:postgres "$PGDATA" && sudo chmod 777 "$PGDATA"
VOLUME /var/lib/postgresql/data
CMD sudo pg_createcluster 9.6 main --start && sudo service postgresql start & tail -f /dev/null
```

**Comment by deveborn** [comment]
Thanks evantsov! 

I tried to use your stack definition by navigating to "Stacks" > "Import". Then I pasted your recipe and tested the new stack. I also saved the stack and made a new workspace with it. When testing/starting the stack/workspace, the process window output ends with the the following error:

> [DOCKER] Removing intermediate container 8d82e1a1766a
> [DOCKER] [ERROR] The command '/bin/sh -c sudo apt-get update sudo apt-get install -y postgresql-common sudo sed -ri 's/#(create_main_cluster) .*$/\1 = false/' /etc/postgresql-common/createcluster.conf sudo apt-get install -y PG_VERSION PG_VERSION sudo rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
> [ERROR] Docker image build failed. Image id not found in build output.
>

**Comment by eivantsov** [comment]
@deveborn Thanks for reporting a bug - https://github.com/eclipse/che/issues/4689

You may go to Workspace > Add Workspace > Runtime - Stack Authoring, and paste this recipe there. It should work.

![image](https://cloud.githubusercontent.com/assets/5337267/24643436/a6d6ffe2-1916-11e7-95a8-31200db5619f.png)

**Comment by deveborn** [comment]
Thanks again! However, when I follow your instruction above I still get the same error:

> [DOCKER] Removing intermediate container 5fb7cbb4aea8
> [DOCKER] [ERROR] The command '/bin/sh -c sudo apt-get update sudo apt-get install -y postgresql-common sudo sed -ri 's/#(create_main_cluster) .*$/\1 = false/' /etc/postgresql-common/createcluster.conf sudo apt-get install -y PG_VERSION PG_VERSION sudo rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
> [ERROR] Docker image build failed. Image id not found in build output.

I noticed some small changes between the pasted code and the stored (when looking under "view"). At least some backslash was removed.

**Comment by eivantsov** [comment]
Yes, sorry, the same problem here. 

Here's a workaround - you may use a Gist I have created for you: https://gist.githubusercontent.com/eivantsov/bb0edc01d62b6f6e25488d4b73f0f97d/raw/f6c34530ec0dfdd43711016f34bfc6b0b3d68245/Dockerfile

![image](https://cloud.githubusercontent.com/assets/5337267/24691449/26f2da3c-19dc-11e7-8a67-05b13fff137d.png)

![image](https://cloud.githubusercontent.com/assets/5337267/24691484/5466df90-19dc-11e7-90fa-9dd498efe11f.png)

**Comment by deveborn** [comment]
Great! Its working! Many thanks! 

Probably a stupid question but how do I know the 'user' password in the dev-machine? When using psql I switch to the postgres user but then I have trouble to switch back since I do not know the password of the 'user' user (or root). Can I read about how to manage and understand basic things like this in the dev-machine somewhere? I have some linux experience but usually I have full control of the installation and setup process.

**Comment by eivantsov** [comment]
@deveborn user is paswordless and added to sudoers. This is how it goes on my side:

```
user@1214034bbae7:/projects$ sudo su postgres
postgres@1214034bbae7:/projects$ id
uid=107(postgres) gid=111(postgres) groups=111(postgres),110(ssl-cert)
postgres@1214034bbae7:/projects$ exit
exit
user@1214034bbae7:/projects$ sudo su root
root@1214034bbae7:/projects# id
uid=0(root) gid=0(root) groups=0(root)
root@1214034bbae7:/projects# sudo su user
user@1214034bbae7:/projects#
```

**Comment by eivantsov** [comment]
@deveborn any update on the issue please? Were you able to browse psql databases?

**Comment by eivantsov** [comment]
I think this comment answers your question https://github.com/codenvy/codenvy/issues/2027#issuecomment-292066460

Closing the issue. Feel free to reopen.
