### ISSUE TITLE
Unable to connect debugger to java projects in 5.6.0

### ISSUE THREAD

**Issue by alexcorvino** [codenvy/codenvy#2029]
**Reproduction Steps:**

Create a java workspace with a simple console project.

Copy the console-java-simple:run maven command. Change the mvn command to mvnDebug. Change the goal from clean install to exec:exec and delete the java -jar command. Run the command and note that it's listening on port 8000 for a debugger to connect.

Under Run->Edit debug configurations... Under Java and a remote java debugging and click debug. Previously, the debugger would attach. Now nothing happens. 

**Codenvy version:**  5.6.0  

**OS and version:**    
`user@df0fa6782eea:/projects$ cat /proc/version`
`Linux version 3.10.0-514.10.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Fri Mar 3 00:04:05 UTC 2017`

**Docker version:**    
Docker not found on my workspace.

**Codenvy cli.log output:**  
Not on prem.

**Comment by eivantsov** [comment]
@alexcorvino this is a known issue: https://github.com/eclipse/che/issues/4582

As a workaround, flush your browser's local storage.

**Comment by eivantsov** [comment]
I am closing this issue, please follow https://github.com/eclipse/che/issues/4582
