### ISSUE TITLE
Error appears when creating workspace from predefined stack

### ISSUE THREAD

**Issue by vinokurig** [codenvy/codenvy#2031]
Error appears when creating workspace from predefined stack

**Reproduction Steps:**
1. Make `destroy` to your local Codenvy installation or start new Codenvy from latest image.
(`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/ivinokur/codenvyTemp:/data codenvy/cli:nightly start`).
2. Go to 'Dashboard' -> 'Create workspace'.
3. Choose any stack and click 'Create' button.

Error appears:
![screenshot-172 17 0 1-2017-04-03-13-35-55](https://cloud.githubusercontent.com/assets/7668752/24605687/83624264-1872-11e7-95e4-73e8edd1c624.jpeg)

**Codenvy version:**    
5.7.0-SNAPSHOT

**OS and version:**    Ubuntu 16.04

**Docker version:**    
```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:45:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:45:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Codenvy cli.log output:**

**Comment by riuvshin** [comment]
@ashumilova please take a look

**Comment by riuvshin** [comment]
@vinokurig can you reproduce this on nightly?

**Comment by vinokurig** [comment]
It is not reproduced on nightly

**Comment by ashumilova** [comment]
it's caused by wrong url usage, when the one provided by cli(printed in console) is used (everything works fine).

**Comment by vinokurig** [comment]
@ashumilova I used `localhost` as a url.

**Comment by eivantsov** [comment]
Using your eth0 IP should fix it.
