### ISSUE TITLE
The Eclipse Vert.x and Spring Boot stacks don't exist in the "Stacks" list on codenvy.io.

### ISSUE THREAD

**Issue by SkorikSergey** [codenvy/codenvy#2036]
The Eclipse Vert.x and Spring Boot stacks don't exist only on codenvy.io. 

Server location: codenvy.io

Additional information:
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![anim](https://cloud.githubusercontent.com/assets/7760565/24612491/185328be-188e-11e7-85d3-78704831f979.gif)

**Comment by skryzhny** [comment]
Stacks added
