### ISSUE TITLE
Teams onprem

### ISSUE THREAD

**Issue by josezuazo** [codenvy/codenvy#2044]
There is a workaround available to manage teams onprem?

When I access the configuration of a workspace, I see the share tab. But when I try to add new developers to the work space, I see the following message: 

> No members in team
> The workspace is already shared with all members of the team .

Thanks

**Comment by TylerJewell** [comment]
We will have an on-prem version with team & organizational capabilities
released in 4-6 weeks.  The concept of a team is different in on-prem than
in our hosted saas, so we have to do some adaptation.


Tyler Jewell // CEO // tyler@​codenvy.​com // 978.884.5355

**Comment by josezuazo** [comment]
Great! I'll be looking forward to the release.
