### ISSUE TITLE
ng serve host:port. How to get preview URL

### ISSUE THREAD

**Issue by karlkras** [codenvy/codenvy#2045]
Repro steps on "How do you perform an $> ng serve --host xxxxx --port yyyy  from the terminal so you can access your server output?" ? How does that equate? What does OS version have to do with this?

**Comment by eivantsov** [comment]
When running ng serve the host should be 0.0.0.0. As to the port, it should be one of the exposed ports for your workspace. You can use ports 3000 4200 5000 9000 8003. The best way to get preview URL is to create a command for your process and use preview URL macro in it: https://www.eclipse.org/che/docs/ide/commands/index.html

Feel free to ask your questions here on GitHub, they'll all be answered.

**Comment by eivantsov** [comment]
Closing the issue. Feel free to reopen if my suggestion never helped.
