### ISSUE TITLE
Swagger for ws agent uses wrong API endpoint

### ISSUE THREAD

**Issue by eivantsov** [codenvy/codenvy#2047]
When feeding the right json for codenvy.io/swagger (the one with machinetoken and ws-agent port), swagger makes calls to the wrong API endpoint because of https://github.com/codenvy/codenvy/blob/master/assembly/assembly-wsagent-war/src/main/java/com/codenvy/ext/java/server/MachineServletModule.java#L50

As a result the request looks like this:

https://github.com/codenvy/codenvy/blob/master/assembly/assembly-wsagent-war/src/main/java/com/codenvy/ext/java/server/MachineServletModule.java#L50

**Comment by skabashnyuk** [comment]
related to https://github.com/codenvy/codenvy/issues/403
