### ISSUE TITLE
Auto snapshots not working

### ISSUE THREAD

**Issue by eimhin** [codenvy/codenvy#2050]
Auto snapshots don't seem to be working by default or when enabled in the config file. I see in the documentation (which seems slightly old) that you can snapshot to disk (like Eclipse Che does by default) instead of using a local or remote private registry:

https://codenvy.com/docs/getting-started/machines/index.html

I'm referring to this option:

"If false, snaps are saved to disk. If true, snaps are saved in a registry.
The namespace is how the snapshots will be organized in the registry."
CODENVY_DOCKER_REGISTRY__FOR__SNAPSHOTS=false

It's not available in the 5.6.0 configuration.

**Reproduction Steps:**

**Codenvy version:**  5.6.0

**OS and version:**  Ubuntu 16.04

**Docker version:** 17.03.1-ce

**Comment by eimhin** [comment]
I'll add that this is using the on-prem version and not codenvy.io

**Comment by eivantsov** [comment]
@eimhin you need to provide your registry host:port in codenvy.env

`#CODENVY_DOCKER_REGISTRY_FOR_WORKSPACE_SNAPSHOTS=<your_private_registry_url>:<port>`

You should also add this registry to Docker daemon options as an insecure registry.

**Comment by eimhin** [comment]
Thanks @eivantsov !
