### ISSUE TITLE
cann't pull a project when create workspace through api

### ISSUE THREAD

**Issue by wzdnzd** [codenvy/codenvy#2052]
Hi,
when i create a workspace through the api,i cann't pull a project successfully，the workspace config such as:

{
  "defaultEnv": "default",
  "environments": {
    "default": {
      "machines": {
        "dev-machine": {
          "attributes": {
            "memoryLimitBytes": "2147483648"
          },
          "agents": [
            "org.eclipse.che.terminal",
            "org.eclipse.che.ws-agent",
            "org.eclipse.che.ssh"
          ]
        }
      },
      "recipe": {
        "location": "eclipse/hadoop-dev",
        "type": "dockerimage"
      }
    }
  },
  "projects": [
    {
      "name": "hadoop",
      "type": "maven",
      "attributes" : {
       "contribute_to_branch" : [
            "master"
            ]
   },
      "source": {
        "location": "https://github.com/apache/zookeeper.git",
        "type": "git",
        "parameters" :{
           "branch": "master",
           "commitId": "null"
       }
      },
      "path": "/hadoop",
      "mixins": [
        "pullrequest"
      ]
    }
  ],
  "name": "test",
  "commands": [
    {
      "commandLine": "mvn -f ${current.project.path} clean install",
      "name": "build",
      "attributes": {
        "previewUrl": ""
      },
      "type": "mvn"
    },
    {
      "commandLine": "cd ${current.project.path} && mvn exec:java -Dexec.mainClass='org.eclipse.che.wordcount.WordCount'",
      "name": "run",
      "attributes": {},
      "type": "custom"
    }
  ],
}

![image](https://cloud.githubusercontent.com/assets/8565764/24735975/0da907f4-1ab8-11e7-821f-f6279357b339.png)

docker version:1.12.5
codenvy version: 5.3.0

**Comment by eivantsov** [comment]
@wzdnzd you need to import a project into your workspace, while you have just added it to workspace config. You need to:

1. Start a workspace
2. POST to `$host_url/ws-agent_url/api/project?token=token` where

`host_url` is your Codenvy host url, `ws_url` is retrieved at `host_url/api/workspace/ws-id` - runtime > servers. You will need a machine token that you can obtain at `$host_url/api/machine/token/workspace-id`. You can get your workspace ID by its name: `$host_url/api/workspace/:$workspace-name`

3. Request payload:

`{"name":"blank", "type":"blank", "source":{"location":"https://github.com/che-samples/blank", "type":"git"}, "path":"/blank"}`

**Comment by wzdnzd** [comment]
@eivantsov  thank you for your reply.

**Comment by wzdnzd** [comment]
Hi,I tried to import a project from github according to your method.However,i cann't pull any source code in any way.

Request payload such as:
{  
    "name":"hadoop",        
    "path":"/hadoop",       
    "type":"Maven",         
    "mixins":["pullrequest"],                      
    "attributes":{                    
      "language":[
        "java"
      ]
    },                  
    "source":{                        
      "type":"git",                  
      "location":"https://github.com/apache/hadoop.git",                         
      "parameters":{
          "branch":"master"
      }                 
    }
  }

**Comment by eivantsov** [comment]
Error code and message will help

**Comment by wzdnzd** [comment]
{
    "links": [
        {
            "href": "http://10.20.32.202/32809_10.20.32.202/api/project/hadoop",
            "parameters": [],
            "rel": "update project",
            "method": "PUT",
            "produces": "application/json",
            "consumes": "application/json"
        },
        {
            "href": "http://10.20.32.202/32809_10.20.32.202/api/project/children/hadoop",
            "parameters": [],
            "rel": "children",
            "method": "GET",
            "produces": "application/json"
        },
        {
            "href": "http://10.20.32.202/32809_10.20.32.202/api/project/tree/hadoop",
            "parameters": [],
            "rel": "tree",
            "method": "GET",
            "produces": "application/json"
        },
        {
            "href": "http://10.20.32.202/32809_10.20.32.202/api/project/hadoop",
            "parameters": [],
            "rel": "delete",
            "method": "DELETE"
        }
    ],
    "name": "hadoop",
    "attributes": {
        "contribute_to_branch": [
            "master"
        ]
    },
    "type": "blank",
    "source": {
        "location": "https://github.com/apache/hadoop.git",
        "type": "git",
        "parameters": {
            "branch": "master"
        }
    },
    "path": "/hadoop",
    "problems": [
        {
            "message": "Primary type Maven defined for /hadoop is not registered. Base Project Type assigned.",
            "code": 12
        }
    ],
    "mixins": [
        "pullrequest"
    ]
}

Perhaps i need to definite what's mean the error code "12"

**Comment by gazarenkov** [comment]
As stated
"Primary type Maven defined for /hadoop is not registered. Base Project Type assigned."

I think it should be lowercased "maven"

**Comment by wzdnzd** [comment]
But,when i change it to "maven",then i get the response {"message":"Missed required attribute artifactId"},i don't know what the artifactId is.

![Uploading 2017-04-10_100528.png…]()

**Comment by eivantsov** [comment]
Artifact ID, Group ID and versions are in your pom.xml.

Here's an example for a sample Spring project:


```
"attributes":{  
      "maven.artifactId":[  
         "web-java-spring"
      ],
      "maven.parent.version":[  
         ""
      ],
      "maven.test.source.folder":[  
         "src/test/java"
      ],
      "java.output.folder":[  
         ""
      ],
      "maven.version":[  
         "1.0-SNAPSHOT"
      ],
      "maven.parent.groupId":[  
         ""
      ],
      "languageVersion":[  
         "1.8.0_121"
      ],
      "language":[  
         "java"
      ],
      "maven.groupId":[  
         "org.eclipse.che.examples"
      ],
      "maven.packaging":[  
         "war"
      ],
      "containsJavaFiles":[  
         "true"
      ],
      "java.source.folder":[  
         "src/main/java"
      ],
      "maven.resource.folder":[  
         "src/main/resources",
         "src/test/resources"
      ],
      "maven.parent.artifactId":[  
         ""
      ]
   }
```

**Comment by wzdnzd** [comment]
I'm so confused that why i need config there attributes,because i just want pull source codes from an existed source-code repository.Otherwise,when i change "type" to "javac",i can get some source codes,but i  don't know where they are from,because they aren't form the repository i specified.
I'm looking forward for your reply and help,thank you.

**Comment by eivantsov** [comment]
If you want just source code, set it to blank project type, and then configure as maven in the IDE.

If you want to import a fully configured maven project, you need to specify mandatory attributes. You can get those at `api/project-type/maven`

**Comment by wzdnzd** [comment]
I have tried it,but i just get a README  file instead of source codes when i set project type to blank.And when i add maven's attributes i saw the ide create a new maven project but don't have any codes.

screenshot：
![2017-04-11_162608](https://cloud.githubusercontent.com/assets/8565764/24899731/ecaad22e-1ed3-11e7-89b9-58e41b28d14f.png)
![2017-04-11_162729](https://cloud.githubusercontent.com/assets/8565764/24899741/f1b3791a-1ed3-11e7-8730-608ffcefe118.png)

**Comment by eivantsov** [comment]
@wzdnzd sorry for the confusion.

`/api/project/batch` is the right endpoint, and 

`[{"name":"web-java-spring-petclinic", "type":"blank", "source":{"location":"https://github.com/che-samples/web-java-spring-petclinic.git", "type":"git"}, "path":"/web-java-spring-petclinic"}]`

is the right payload. 

Go ahead and give it a try with maven project type and must have attributes.

**Comment by wzdnzd** [comment]
Thank you your reply,now i can pull a project from github.Can i ask a problem?If i need pull codes from a privace repository,then what's the payload looked like?I cann't found the answer from official documents.
Thx again。

**Comment by eivantsov** [comment]
I see two approaches:

1. username:password in git URL - not secure:

`https://userName:password@host.com/user/repo.git`

2. Add SSH key to preferences of a user who created a workspace. Then add public key part to your GitHub account settings. Use ssh git URL.

**Comment by wzdnzd** [comment]
I see,thank you
