### ISSUE TITLE
Rsync restore fail with ssh permission denied error

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#2053]
Sometime `rsync` restore fails with permission denied error from ssh when starting workspace:
<details>

```
017-04-05 10:56:37,248[ceSharedPool-10]  [ERROR] [DockerEnvironmentBackupManager 509]  - Error occurred during backup/restore of workspace 'workspacer7gox0sraal6jf2k' on node 'node2.c5.codenvy-stg.com' : Warning: Permanently added '[node2.c5.codenvy-stg.com]:34033,[172.30.12.84]:34033' (ECDSA) to the list of known hosts.
Permission denied (publickey,password).
Warning: Permanently added '[node2.c5.codenvy-stg.com]:34033,[172.30.12.84]:34033' (ECDSA) to the list of known hosts.
Permission denied (publickey,password).
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.2]
2017-04-05 10:56:37,249[ceSharedPool-10]  [ERROR] [DockerEnvironmentBackupManager 319]  - Synchronization process failed. Exit code 255
java.io.IOException: Synchronization process failed. Exit code 255
```
</details>

It happens about 5% of launches factory we use for monitoring health of our system.
Probably there is synchronisation issues: ssh public key file haven't copied yet in workspace while ssh trying to connect.

Possible workaround: in `rsyncbase.sh` script add checking for `ssh` error and retry several times waiting some seconds before retries.
Like: If connection fails wait 2 seconds and retry 3 times before giving up.
 
**Reproduction Steps:**
- Launch CI job https://ci.codenvycorp.com/view/qa/job/factory-check-stg
- Wait some hours
- Watch logs for errors

**Codenvy version:**    5.6.0-SaaS

**Comment by mmorhun** [comment]
Done
