### ISSUE TITLE
Contributions buttons have been removed from product

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#2054]
With the migration of the factories to Che, for some reasons the contributions buttons have been removed.

The following images:
- https://codenvy.io/factory/resources/codenvy-contribute.svg
- https://codenvy.io/factory/resources/codenvy-review.svg

Needs to be available.
The URL must be kept - as those buttons are used by partners in their documentation, on their repository, on their internal trainings and so on. It's a feature we provided, which have been used and promoted by partners, we need to maintain it.

Moreover they are used in the Pull Request workflow - so they need to be there with Che as well.

**Comment by musienko-maxim** [comment]
I've just created Contribution flaw from nightly server. The image is present and href looks as well. Whats wrong?
![selection_033](https://cloud.githubusercontent.com/assets/1640058/24746376/8c4ec342-1ac1-11e7-9e4a-b04d7637f9a3.png)

**Comment by mshaposhnik** [comment]
Image is still present on codenvy.io because new version not applied

**Comment by riuvshin** [comment]
@mshaposhnik this is not codenvy.io it is nightly

**Comment by riuvshin** [comment]
ok we found the issue, it is removed from codenvy but still exist in saas. So guys will remove it from saas to make it consistent with codenvy and then they will add images back somehow

**Comment by mshaposhnik** [comment]
Fixed in 
https://github.com/eclipse/che/pull/4725
https://github.com/codenvy/codenvy/pull/2056
