### ISSUE TITLE
Cannot create a new team from navbar with a opened workspace

### ISSUE THREAD

**Issue by SkorikSergey** [codenvy/codenvy#2057]
**Reproduction Steps:**

- Start any workspace
- Click on the Create Team link

**Expected behavior:**
The Create Team page opened

**Observed behavior:**
Nothing happened

**Server location:** nightly.codenvy-stg.com

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![anim](https://cloud.githubusercontent.com/assets/7760565/24754310/9ba2fe86-1ade-11e7-97ce-6e519cb91fb1.gif)

**Comment by bmicklea** [comment]
@ashumilova This seems like a big deal - can it wait until next sprint or should it be fixed now?

**Comment by ashumilova** [comment]
Fixed by https://github.com/codenvy/codenvy/commit/13e399b8265789d76f6dfbce66d198fe07dd05cc#diff-480d0e0abb0e3a87999cb7707dd4da12R100
