### ISSUE TITLE
Not able to accept factory if user is not authorized

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#2061]
**Reproduction Steps:**
1. Logout from codenvy.
2. Click on link https://codenvy-stg.com/f?name=replace&user=ivantsoft
3. Login.
4. Stuck on dashboard.
Factory not started. 
Same factory is working if user authorized before factory acceptance

**Codenvy version:**    
5.8.0

**Comment by mkuznyetsov** [comment]
Issue for corresponding test for QA:
https://github.com/codenvy/qa/issues/781

**Comment by mshaposhnik** [comment]
Fixed in https://github.com/codenvy/codenvy/pull/2062

**Comment by vkuznyetsov** [comment]
Bug is actual if user log in with username and password.

**Comment by mshaposhnik** [comment]
Fixed;
