### ISSUE TITLE
Can't create a new workspace

### ISSUE THREAD

**Issue by codeHatcher** [codenvy/codenvy#2064]
**Reproduction Steps:**
Fresh install of codenvy, logged in, create new workspace, click start workspace

**OS and version:**    
Windows 10 Pro 64bit

**Codenvy version:**    
  5.6.0

**Docker version:**    
```
λ docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Codenvy cli.log output:**  
**Diagnostics Logs**

`
Create Workspace 
EventChannel : {"eventType":"STARTING","status":"STARTING","prevStatus":"STOPPED","workspaceId":"workspaceruv392bu1z5o0j9t"} StatusChannel : {"machineId":"machinexyk9ubqlke2oom3d","eventType":"CREATING","dev":true,"machineName":"dev-machine","workspaceId":"workspaceruv392bu1z5o0j9t"} [DOCKER] Step 1/2 : FROM openjdk:8-jre-alpine output channel message :{"machineName":"dev-machine","content":"[DOCKER] Step 1/2 : FROM openjdk:8-jre-alpine"} [DOCKER] 8-jre-alpine: Pulling from library/openjdk output channel message :{"machineName":"dev-machine","content":"[DOCKER] 8-jre-alpine: Pulling from library/openjdk "} [DOCKER] 627beaf3eaaf: Already exists output channel message :{"machineName":"dev-machine","content":"[DOCKER] 627beaf3eaaf: Already exists "} [DOCKER] 1de20f2d8b83: Already exists output channel message :{"machineName":"dev-machine","content":"[DOCKER] 1de20f2d8b83: Already exists "} [DOCKER] 74e619d34827: Already exists output channel message :{"machineName":"dev-machine","content":"[DOCKER] 74e619d34827: Already exists "} [DOCKER] Digest: sha256:e663151c5fdfa89bda49af65b3d477fa1433491290cd35c8f09afa16072f35c4 output channel message :{"machineName":"dev-machine","content":"[DOCKER] Digest: sha256:e663151c5fdfa89bda49af65b3d477fa1433491290cd35c8f09afa16072f35c4 "} [DOCKER] Status: Downloaded newer image for openjdk:8-jre-alpine output channel message :{"machineName":"dev-machine","content":"[DOCKER] Status: Downloaded newer image for openjdk:8-jre-alpine "} [DOCKER] ---> c017141bdaa8 output channel message :{"machineName":"dev-machine","content":"[DOCKER] ---> c017141bdaa8"} [DOCKER] Step 2/2 : CMD tail -f /dev/null output channel message :{"machineName":"dev-machine","content":"[DOCKER] Step 2/2 : CMD tail -f /dev/null"} [DOCKER] ---> Running in 655fc7ab1a37 output channel message :{"machineName":"dev-machine","content":"[DOCKER] ---> Running in 655fc7ab1a37"} [DOCKER] ---> 889f6c02124f output channel message :{"machineName":"dev-machine","content":"[DOCKER] ---> 889f6c02124f"} [DOCKER] Removing intermediate container 655fc7ab1a37 output channel message :{"machineName":"dev-machine","content":"[DOCKER] Removing intermediate container 655fc7ab1a37"} StatusChannel : {"machineId":"machinexyk9ubqlke2oom3d","eventType":"RUNNING","dev":true,"machineName":"dev-machine","workspaceId":"workspaceruv392bu1z5o0j9t"} [STDOUT] fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz output channel message :{"machineName":"dev-machine","content":"[STDOUT] fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz"} [STDOUT] fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz output channel message :{"machineName":"dev-machine","content":"[STDOUT] fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz"} [STDOUT] v3.5.2-39-g9f17745511 [http://dl-cdn.alpinelinux.org/alpine/v3.5/main] output channel message :{"machineName":"dev-machine","content":"[STDOUT] v3.5.2-39-g9f17745511 [http://dl-cdn.alpinelinux.org/alpine/v3.5/main]"} [STDOUT] v3.5.2-23-g0306a37de3 [http://dl-cdn.alpinelinux.org/alpine/v3.5/community] output channel message :{"machineName":"dev-machine","content":"[STDOUT] v3.5.2-23-g0306a37de3 [http://dl-cdn.alpinelinux.org/alpine/v3.5/community]"} [STDOUT] OK: 7960 distinct packages available output channel message :{"machineName":"dev-machine","content":"[STDOUT] OK: 7960 distinct packages available"} [STDOUT] (1/3) Installing openssh-client (7.4_p1-r0) output channel message :{"machineName":"dev-machine","content":"[STDOUT] (1/3) Installing openssh-client (7.4_p1-r0)"} [STDOUT] (2/3) Installing openssh-sftp-server (7.4_p1-r0) output channel message :{"machineName":"dev-machine","content":"[STDOUT] (2/3) Installing openssh-sftp-server (7.4_p1-r0)"} [STDOUT] (3/3) Installing openssh (7.4_p1-r0) output channel message :{"machineName":"dev-machine","content":"[STDOUT] (3/3) Installing openssh (7.4_p1-r0)"} [STDOUT] Executing busybox-1.25.1-r0.trigger output channel message :{"machineName":"dev-machine","content":"[STDOUT] Executing busybox-1.25.1-r0.trigger"} [STDOUT] OK: 84 MiB in 52 packages output channel message :{"machineName":"dev-machine","content":"[STDOUT] OK: 84 MiB in 52 packages"} [STDOUT] ssh-keygen: generating new host keys: RSA DSA ECDSA ED25519 output channel message :{"machineName":"dev-machine","content":"[STDOUT] ssh-keygen: generating new host keys: RSA DSA ECDSA ED25519 "} [STDOUT] fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz output channel message :{"machineName":"dev-machine","content":"[STDOUT] fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz"} [STDOUT] fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz output channel message :{"machineName":"dev-machine","content":"[STDOUT] fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz"} [STDOUT] v3.5.2-39-g9f17745511 [http://dl-cdn.alpinelinux.org/alpine/v3.5/main] output channel message :{"machineName":"dev-machine","content":"[STDOUT] v3.5.2-39-g9f17745511 [http://dl-cdn.alpinelinux.org/alpine/v3.5/main]"} [STDOUT] v3.5.2-23-g0306a37de3 [http://dl-cdn.alpinelinux.org/alpine/v3.5/community] output channel message :{"machineName":"dev-machine","content":"[STDOUT] v3.5.2-23-g0306a37de3 [http://dl-cdn.alpinelinux.org/alpine/v3.5/community]"} [STDOUT] OK: 7960 distinct packages available output channel message :{"machineName":"dev-machine","content":"[STDOUT] OK: 7960 distinct packages available"} [STDOUT] (1/4) Installing libattr (2.4.47-r4) output channel message :{"machineName":"dev-machine","content":"[STDOUT] (1/4) Installing libattr (2.4.47-r4)"} [STDOUT] (2/4) Installing libacl (2.2.52-r2) output channel message :{"machineName":"dev-machine","content":"[STDOUT] (2/4) Installing libacl (2.2.52-r2)"} [STDOUT] (3/4) Installing popt (1.16-r6) output channel message :{"machineName":"dev-machine","content":"[STDOUT] (3/4) Installing popt (1.16-r6)"} [STDOUT] (4/4) Installing rsync (3.1.2-r2) output channel message :{"machineName":"dev-machine","content":"[STDOUT] (4/4) Installing rsync (3.1.2-r2)"} [STDOUT] Executing busybox-1.25.1-r0.trigger output channel message :{"machineName":"dev-machine","content":"[STDOUT] Executing busybox-1.25.1-r0.trigger"} [STDOUT] OK: 84 MiB in 56 packages output channel message :{"machineName":"dev-machine","content":"[STDOUT] OK: 84 MiB in 56 packages"} [STDOUT] fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz output channel message :{"machineName":"dev-machine","content":"[STDOUT] fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz"} [STDOUT] fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz output channel message :{"machineName":"dev-machine","content":"[STDOUT] fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz"} [STDOUT] v3.5.2-39-g9f17745511 [http://dl-cdn.alpinelinux.org/alpine/v3.5/main] output channel message :{"machineName":"dev-machine","content":"[STDOUT] v3.5.2-39-g9f17745511 [http://dl-cdn.alpinelinux.org/alpine/v3.5/main]"} [STDOUT] v3.5.2-23-g0306a37de3 [http://dl-cdn.alpinelinux.org/alpine/v3.5/community] output channel message :{"machineName":"dev-machine","content":"[STDOUT] v3.5.2-23-g0306a37de3 [http://dl-cdn.alpinelinux.org/alpine/v3.5/community]"} [STDOUT] OK: 7960 distinct packages available output channel message :{"machineName":"dev-machine","content":"[STDOUT] OK: 7960 distinct packages available"} [STDOUT] (1/3) Installing libssh2 (1.7.0-r2) output channel message :{"machineName":"dev-machine","content":"[STDOUT] (1/3) Installing libssh2 (1.7.0-r2)"} [STDOUT] (2/3) Installing libcurl (7.52.1-r2) output channel message :{"machineName":"dev-machine","content":"[STDOUT] (2/3) Installing libcurl (7.52.1-r2)"} [STDOUT] (3/3) Installing curl (7.52.1-r2) output channel message :{"machineName":"dev-machine","content":"[STDOUT] (3/3) Installing curl (7.52.1-r2)"} [STDOUT] Executing busybox-1.25.1-r0.trigger output channel message :{"machineName":"dev-machine","content":"[STDOUT] Executing busybox-1.25.1-r0.trigger"} [STDOUT] OK: 85 MiB in 59 packages output channel message :{"machineName":"dev-machine","content":"[STDOUT] OK: 85 MiB in 59 packages"} [STDOUT] Exec Agent will be downloaded from Workspace Master output channel message :{"machineName":"dev-machine","content":"[STDOUT] Exec Agent will be downloaded from Workspace Master"} [STDERR] tar: invalid magic output channel message :{"machineName":"dev-machine","content":"[STDERR] tar: invalid magic"} [STDERR] tar: short read output channel message :{"machineName":"dev-machine","content":"[STDERR] tar: short read"} [STDERR] /bin/sh: /root/che/exec-agent/che-exec-agent: not found output channel message :{"machineName":"dev-machine","content":"[STDERR] /bin/sh: /root/che/exec-agent/che-exec-agent: not found"} StatusChannel : {"machineId":"machinexyk9ubqlke2oom3d","eventType":"DESTROYING","dev":true,"machineName":"dev-machine","workspaceId":"workspaceruv392bu1z5o0j9t"} StatusChannel : {"machineId":"machinexyk9ubqlke2oom3d","eventType":"DESTROYED","dev":true,"machineName":"dev-machine","workspaceId":"workspaceruv392bu1z5o0j9t"}
`
![image](https://cloud.githubusercontent.com/assets/5360982/24822577/ec1e9d76-1baa-11e7-8443-53b2dc975fd7.png)

**Comment by eivantsov** [comment]
@codeHatcher what is the error when you start a normal workspace not a diagnostic one? Can you share a screenshot? What starting Codenvy were there any errors or warnings?

**Comment by eivantsov** [comment]
Also, try access your Codenvy installation at localhost, not IP. There's a known bug for Windows https://github.com/codenvy/codenvy/issues/1826

**Comment by codeHatcher** [comment]
Looks like that is my issue. My plan was to access the web IDE from another computer using a VPN. It seems with this bug I can't do that. Is this is a new bug that is planned on being fixed or probably not?

**Comment by TylerJewell** [comment]
It's a P1 bug, and they are not kept in the backlog for too long - they are treated as severe.  Have you set the  *_EXTERNAL properties in the che.env file to the external IP address of your VM, and does this also generate the same issue?

**Comment by eivantsov** [comment]
@codeHatcher can you describe the issue in details please?

**Comment by codeHatcher** [comment]
when I use localhost it works. when I use the docker ip address, it doesn't. when I use my machine ip address, it doesn't. I connect my remote computer to the VPN where my 'server' is. I was expecting to be able to type in my server's ip address and access it via the network. @TylerJewell I'm not sure what you are referring to. Do you have a place in the documentation you can direct me to?

**Comment by codeHatcher** [comment]
I'm trying to uninstall and start fresh, it seems to be stuck on 
![image](https://cloud.githubusercontent.com/assets/5360982/25109448/74dd2036-2391-11e7-9806-78458368ceed.png)

**Comment by eivantsov** [comment]
@codeHatcher when you say `id doesn't work` - can you provide details on how exactly it does not work.

Note that when Codenvy is running remotely, your client machine should have access to server over the ephemeral port range. So, think of firewall or any other restrictions that may occur on the way.

**Comment by codeHatcher** [comment]
@eivantsov I get the following error
![image](https://cloud.githubusercontent.com/assets/5360982/25122439/c6f0f896-23d9-11e7-91e5-fac3bc7a1301.png)
I'm not sure how to add the --remote flag/argument. I don't see it in the codenvy nor the che documentation

**Comment by codeHatcher** [comment]
disabled firewalls between the two computers, I'm also on the same local network
