### ISSUE TITLE
BrowserIDE seems to fail to Initialize

### ISSUE THREAD

**Issue by sr229** [codenvy/codenvy#2065]
the Browser IDE somehow fails to load with this error popout : 
```prolog

window.IDE.eventHandlers.initializationFailed@https://codenvy.io/aguilarralph13/clara-wksp?uid=403942&factory-id=factoryl1iicjquy5kxshvd&factory=true&workspaceId=workspace5x75ky7dcrw0yi7w:40:27
C6f@https://codenvy.io/aguilarralph13/clara-wksp?uid=403942&factory-id=factoryl1iicjquy5kxshvd&factory=true&workspaceId=workspace5x75ky7dcrw0yi7w:181:23
S6f@https://codenvy.io/aguilarralph13/clara-wksp?uid=403942&factory-id=factoryl1iicjquy5kxshvd&factory=true&workspaceId=workspace5x75ky7dcrw0yi7w:179:60
hXi@https://codenvy.io/aguilarralph13/clara-wksp?uid=403942&factory-id=factoryl1iicjquy5kxshvd&factory=true&workspaceId=workspace5x75ky7dcrw0yi7w:88:19
jXi@https://codenvy.io/aguilarralph13/clara-wksp?uid=403942&factory-id=factoryl1iicjquy5kxshvd&factory=true&workspaceId=workspace5x75ky7dcrw0yi7w:1:5714
CQe@https://codenvy.io/aguilarralph13/clara-wksp?uid=403942&factory-id=factoryl1iicjquy5kxshvd&factory=true&workspaceId=workspace5x75ky7dcrw0yi7w:103:80
wQe/<@https://codenvy.io/aguilarralph13/clara-wksp?uid=403942&factory-id=factoryl1iicjquy5kxshvd&factory=true&workspaceId=workspace5x75ky7dcrw0yi7w:394:55
```
**Reproduction Steps:**

- Open from a Factory, [I provided one for testing](https://codenvy.io/f?id=factoryl1iicjquy5kxshvd)
- Wait for the IDE to load

Expected: IDE Window should load normally
What I got: the error message above

**Codenvy version:**    5.6.0

**Comment by eivantsov** [comment]
@sr229 your Factory worked perfectly on my side:

![image](https://cloud.githubusercontent.com/assets/5337267/24851866/e95f2274-1ddd-11e7-88fe-05f68fe084ec.png)

**Comment by eivantsov** [comment]
The error says that your browser cannot connect to ws-agent. It may be a networking issue on your side.

**Comment by eivantsov** [comment]
@sr229 any update please? I checked the Factory again and it worked for me.

**Comment by sr229** [comment]
I can assure I have a very stable connection. @eivantsov , not sure why it hapened, although the machine I tested has a problem on the HDD (keeps locking out in Read-Only mode)

**Comment by eivantsov** [comment]
@sr229 it is not about stability of your connection. It is about blocked ports. I have used your factory 4-5 times and found no issues. Make sure that in the network you use, the ephemeral port range isn't blocked for outbound connections.

**Comment by sr229** [comment]
there's no blocked ports in my laptop though, and the ephemeral port range aren't blocked too

**Comment by eivantsov** [comment]
I cannot reproduce it on my side on different networks.
