### ISSUE TITLE
User with name that starts on 'f' symbol cannot go to the just created workspace

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#2071]
**Reproduction Steps:**
Create new user, name of the user should start of 'f'. Login to Dashboard. Create a workspase. Try to use the workspace.
**Expected result:** An user should go to the workspace.
**Actual result:** User see only progress icon of starting the workspace but cannot go to the IDE.
**Codenvy version:**    5.7.2

**OS and version:**    Ubuntu 14 TLS, chrome browser.

**Docker version:** 17.04.0-ce

**Comment by mshaposhnik** [comment]
Fixed
