### ISSUE TITLE
Error starting Codenvy on-prem 5.7.2

### ISSUE THREAD

**Issue by gautamdeb** [codenvy/codenvy#2074]
Error starting Codenvy on-prem 5.7.2, verified on two different windows machines running Win7 with same results.

**Reproduction Steps:**
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /c/Users/gad/codenvy:/data codenvy/cli start

**Codenvy version:**    On-prem version 5.7.2 retrieve by 'docker run codenvy/cli version'

**OS and version:**  Windows   7

**Docker version:**  Client:17.03.0-ce / Server:17.04.0-ce

**Codenvy cli.log output:**  

ERROR: (codenvy start): Timeout waiting for server. Run "docker logs codenvy_codenvy_1" to inspect.

**Docker logs codenvy_codenvy_1 output:**
Waiting for Postgres to boot...
psql: could not connect to server: Connection refused
        Is the server running on host "postgres" (172.18.0.8) and accepting
        TCP/IP connections on port 5432?

**Comment by TylerJewell** [comment]
This is a very unusual issues. What is the Docker packaging that you are using?  Is it virtualbox?  Do you know the particular vbox version of boot2docker that is being used?  Is there any chance that there is a firewall setup blocking ports within the VM?

**Comment by gautamdeb** [comment]
Yes, it is a virtualbox, No, it is not behind any firewall where ports are blocked.

**Comment by eivantsov** [comment]
@gautamdeb @TylerJewell I suspect these a file permissions issues that does not let postgres container start properly.

@gautamdeb can you run `docker logs -f codenvy_postgres_1`? Or share content of a logs file with is in `/c/Users/gad/codenvy/data/postgres/pg_logs`?

Also, can you try it this way please?

`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /codenvy-data:/data codenvy/cli start`

This way you won't have a backup folder in your Win file system, but this experiment will prove or dispel my suspicions.

**Comment by gautamdeb** [comment]
Thanks! It worked that way.

On a different note, I am trying to evaluate the multi-tenancy aspect of Codenvy, for that I tried downloading the on-prem version, could you please guide me to some document which describes how the multi-tenancy configuration works, like, managing the build and run queue etc.

**Comment by TylerJewell** [comment]
Those items are delegated to Swarm, which has embedded properties for how
it delegates workspace creation to different nodes.  It either has a
density mode, focused on filling up a single node or a spread mode, where
it distributes services to different nodes itself.

Our default configuration is the density mode.


Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by gautamdeb** [comment]
Thank you Tyler, I read it in one of the Codenvy arch paper and I understand that this is delegated to Docker Swarm, my question was more on does Codenvy exposes an (admin) interface which allows this configuration to be controlled, or what is the preferred way to view/modify these?

**Comment by TylerJewell** [comment]
We do not expose any controls over swarm. We treat swarm as an internal
subsystem and make determinations internally.

We expose to admins the ability to set limits on how workspaces are managed
in the codenvy.env file.  We prefer admins think at the workspace
construct, not the technical infrastructure construct and try to expose
configuration with that abstraction in mind.


Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by gautamdeb** [comment]
Ok, I follow that, but again with reference to the technical paper, it was mentioned that in on-prem mode, the number of nodes dedicated to a workspace (and hence a team) can be controlled, i.e. how many build / run nodes are allocated. Just trying to figure out how to control/configure that.

And, thank you for the prompt replies!

Regards,
Gautam

**Comment by TylerJewell** [comment]
In the Codenvy docs, see the "Managing" page.  That page discusses how to
add / remove physical nodes to the Codenvy cluster.


Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by gautamdeb** [comment]
Thank you, this can be closed now.

Regards,
Gautam

**Comment by eivantsov** [comment]
@TylerJewell i think we should say in docs that Codenvy supports Win 10 only when it comes to data persistence. Or we change CLI in order to be able to detect win 7 and 8.

**Comment by TylerJewell** [comment]
There is a check in the CLI today that tests if you are able to write to
the host disk, and if you are unable to, it should print out a warning
message along with a statement about the restrictions of boot2docker and
%userprofile%.  So the basic checks are there.  But it seems like certain
vbox environments are not getting tested?


Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by eivantsov** [comment]
@TylerJewell no, not those tests. On Win 7 and * CLI thinks it is on Linux.
