### ISSUE TITLE
Preview macro won't work (returns the "macro" without parsing)

### ISSUE THREAD

**Issue by janat08** [codenvy/codenvy#2077]
The macro for port returns in terminal as exactly is what is in command's preview section.
I'm not sure if I'm suppose to select the project as applicable.

5.7.1 on web client

**Comment by janat08** [comment]
The relevant documentation for macros and meteor is severely outdated, it would appear if you can only preview under certain ports rather than whatever you like.

**Comment by TylerJewell** [comment]
I just checked the documentation and it's current and accurate.  Previews are objects that are part of commands, which are special objects.  They are not items that are available within a terminal window, which is pure bash.

**Comment by janat08** [comment]
@TylerJewell  Maybe meteor stack builder is bugged then? What I mean is that when I start the command it doesn't appear to recognize the macro and as such outputs ${servert.port... in terminal rather than proper http address.

**Comment by janat08** [comment]
PS While it does return http if port param is the one that's listed in macros list linked in che editor.

**Comment by eivantsov** [comment]
Macros work only in the commands editor, not in the terminal. 

Closing this issue. Please, follow https://github.com/eclipse/che/issues/4800

**Comment by janat08** [comment]
@eivantsov I did use macro in commands editor: bottom section, but it took it for string literal. Using macro for general purpose port (the one that looks at local hosts I imagine) or some of specific ports won't work in such a way (literal).

**Comment by eivantsov** [comment]
I am not sure I understand now what problem we're trying to solve now.

**Comment by janat08** [comment]
Using run rommand with preview macro for most ports listed will result in container not doing what it does to enable preview as it belief that ${servert.port.x} is not a command but rather a comment or something, I take it, as it will then message that preview is availabe on "${servert.port.x}" in terminal.

**Comment by eivantsov** [comment]
What stack do you use? And what port? Note that the port you use in a macro has to be exposed in a container.

**Comment by janat08** [comment]
I use meteor stack. I was using the port that was exposed according to macro list for meteor (of which one took me to codenvy.com. Well so port 4403 works for me.

**Comment by janat08** [comment]
The general purpose macro for using "some port" (like I suppose it auto-picks one) also doesn't work.

**Comment by eivantsov** [comment]
It should not be "some port". This port HAS to be exposed.

I supposed you have started your workspace from a custom recipe?

```
FROM eclipse/meteor
EXPOSE 3000

```

This is my command:

![image](https://cloud.githubusercontent.com/assets/5337267/25238735/d9f347e0-25f6-11e7-8f65-ca7d64b9041a.png)

And running app:

![image](https://cloud.githubusercontent.com/assets/5337267/25238796/fd3b6c6e-25f6-11e7-986f-5dbfa444f579.png)


Meteor tutorial needs to be updated. Indeed, the macro suggested there, does not work.

**Comment by eivantsov** [comment]
@janat08 any further questions?

**Comment by janat08** [comment]
nope
