### ISSUE TITLE
Optimistic ide input

### ISSUE THREAD

**Issue by janat08** [codenvy/codenvy#2081]
Any chance that ide input could be rendered outright on client side, as for example when you delete stuff there's lag.

**Comment by eivantsov** [comment]
@janat08 please be more specific. Do you mean input in the editor or the terminal?

**Comment by janat08** [comment]
Editor, although you could try doing it with terminal too.

**Comment by eivantsov** [comment]
@janat08 are you talking about codenvy.io or your own on prem installation? There's no lag for me on codenvy.io and my local Codenvy installation.

**Comment by janat08** [comment]
Codenvy. You mean you got optimistic ui: client just simulates changes himself and doesn't depend on server. Tunneling yourself to africa and back should produce lag without optimistic ui.

**Comment by eivantsov** [comment]
@janat08 such a lag is expected. Changes in the editor are automatically saved to the server. And the further the node is (geographically) the more time these PUT calls take.

**Comment by janat08** [comment]
Yes, you could just render ide and input on users browser only expecting server to correct what client got if there was a error on server or something. You're for most part entering text, at least that part could try and detach from server.

**Comment by eivantsov** [comment]
Btw, we're working on switching atuo save on and off.

**Comment by janat08** [comment]
I imagine with pair coding you'd still want optimistic ui with auto save on where unlike with optimistic ui server plays integral role needlessly if you're some distance away from nearest codenvy server. You could instead make optimistic ui and batch updates and enable user to force update to server.

**Comment by eivantsov** [comment]
` enable user to force update to server`

is saving manually

**Comment by janat08** [comment]
I imagine with autosave off, what's rendered on your screen isn't bound to server's image of file. In optimistic ui that also happens, it just doesn't wait to make sure that server and client are in sync, instead allowing server to correct image on client version to sync them back.

**Comment by TylerJewell** [comment]
@janat08 - optimistic UI paradigms work well for specific singular objects that can be tracked and managed through a lifecycle, such as moving a work item from one column to another on a kanban board. We are moving portions of the IDE to support more forms of async communications as we are replacing certain elements of our REST APIs with JSON-RPC backbones that have cleaner, more structured way for dealing with events.

However, Eugene is correct that we are working to allow auto-save to be turned off, but the editor at large is not a component that would allow each key stroke to be managed in an optimistic approach.  The optimistic aspects would be applied to things like IDE loading where we can activate terminal and trees ahead of agents being booted within a workspace, for example.
