### ISSUE TITLE
Please add scalingo.com to Git whitelist

### ISSUE THREAD

**Issue by mbrung** [codenvy/codenvy#2087]
We use @scalingo (https://scalingo.com) as a Platform As A Service to deploy our applications (similar to Heroku).

In order to support our development lifecycle from within Codenvy.io we need to be able to push to Scalingo's GIT repository (hence triggering an application deployment).

Would you be so kind to add scalingo.com (185.60.151.19) to the Git target whitelist?  Thank you!

**Comment by skabashnyuk** [comment]
What kind of issue you are trying to solve?

**Comment by mbrung** [comment]
Allow me to rephrase.

I can not connect to Scalingo (https://scalingo.com) via SSH from the workspace console, and therefore cannot push GIT repositories to them (which is a prerequisite to deploy applications to the platform). I understand from #1071 you restrict outbound traffic -- hence my request to white-list them.

## Reproduction Steps

* Create a VCS SSH key for scalingo.com in Codenvy (via Profile > Preferences > SSH > VCS).
* Add the public key to your scalingo.com account.

In the Codenvy console type:
```
ssh -v git@scalingo.com
```
## Expected behavior

SSH connection should not time out.

## Observed behavior

```
$ ssh -v git@scalingo.com
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to scalingo.com [185.60.151.19] port 22.
debug1: connect to address 185.60.151.19 port 22: Connection timed out
ssh: connect to host scalingo.com port 22: Connection timed out
```
  
Codenvy version: 5.8.0
OS and version: hosted on codenvy.io

**Comment by eivantsov** [comment]
@skryzhny can you whitelist this IP please?

**Comment by skryzhny** [comment]
Whitelisted scalingo.com
Can You confirm it works now?
