### ISSUE TITLE
question: is typescript supported?

### ISSUE THREAD

**Issue by olivoil** [codenvy/codenvy#2089]
I'm new to codenvy. I've tried editing typescript files on a new workspace. It seems .ts files are not recognized and there isn't any typescript specific support.

I see on che's repo that it seems they now support using TSServer (and thanks to that, typescript syntax highlighting, intellisense-like completion, etc.)

Is this supposed to work in codenvy? If it's not in the out-of-the box experience, how would one proceed to add support for typescript?

**Comment by eivantsov** [comment]
@olivoil currently, Eclipse Che, which Codenvy is based on, does not have a TS language server with syntax coloring, code-autocompletion etc. You are welcome to open an enhancement request at https://github.com/eclipse/che/issues

**Comment by olivoil** [comment]
@eivantsov I believe support for typescript in che has already been introduced, at least that's what they state here: https://che.eclipse.org/release-notes-eclipse-che-5-0-fde5626194f1

Is there more that we would need from Che to enable it in Codenvy? Or is there some configuration to enable in codenvy to setup che with typescript support?

**Comment by eivantsov** [comment]
My bad. Yes, you can enable this LS for your stack in User Dashboard, or add it to workspace config if you create your workspaces using a different client.

**Comment by eivantsov** [comment]
When in User Dashboard, choose your workspace, navigate to runtime tab, expand dev-machine and enable TS lang server.

**Comment by olivoil** [comment]
@eivantsov thanks, I've done that already actually, but it still sees files with a `.ts` or `.tsx` extension as javascript, does not recognize the syntax at all, and doesn't provide any typescript-intellisense suggestions... I'm thinking it's either a bug or I'm doing something wrong. Is there any other setting to enable or is it supposed to work right away once you enable the setting in the dev-machine runtime menu?

**Comment by eivantsov** [comment]
@olivoil I have checked, and indeed, typescript language server isn't launched when a workspace starts. This will be fixed in the next version (already fixed in master)

**Comment by Zhigalin** [comment]
@eivantsov So when it will be fixed in codenvy.io?

**Comment by eivantsov** [comment]
@olivoil we expect update of codenvy.io middle next week.

**Comment by eivantsov** [comment]
@olivoil can you check if it works for your now?

**Comment by olivoil** [comment]
@eivantsov looks like syntax highlighting is supported on `.ts` files now, not on `.tsx` though. I didn't see any intellisense type of autocompletion, not sure if that's supposed to be there?

**Comment by eivantsov** [comment]
afaik, there's no auto completion for typescript. As to tsx, Orion editor does not recognize it as a TyperScript file.

**Comment by kylecordes** [comment]
(Drive-by outsider comment:)

The result here is surprising. From reading high-level info that went by, like the Che release notes also linked above, which mentions "auto completion", it looked like TypeScript support was present including the sorts of obviously things that such support typically includes. This isn't a complaint - it's an open source project, and I don't have time to add it either :-) but it is perhaps an unfortunate gap between the status of the code and the marketing-ish language in the release notes?

**Comment by eivantsov** [comment]
@kylecordes I am sorry for this confusion - indeed, release notes said typescript auto completion would be there. Eventually, it will. There are already some plans for proper TyperScript support in Che.
