### ISSUE TITLE
Wrong color applied on watermark logo

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#2095]
See the snapshot:
![screen shot 2017-04-18 at 11 17 30](https://cloud.githubusercontent.com/assets/1636769/25123485/cbd7467c-2428-11e7-857c-058da96a54c9.png)

The color of the codenvy logo used in watermark is wrong and must be #294D6F

**Comment by slemeur** [comment]
How can we have such issue?

**Comment by slemeur** [comment]
Raising priority to P1 so that it could be taken into account.

**Comment by 20avva** [comment]
Shouldn't this be a kind/enhancement instead of kind/bug?
