### ISSUE TITLE
I need help on to create web service (RESTFul or SOAP) in codenvy tool 

### ISSUE THREAD

**Issue by malligvt** [codenvy/codenvy#2096]
**Reproduction Steps:**

**Codenvy version:**    

**OS and version:**    

**Docker version:**    

**Codenvy cli.log output:**

**Comment by TylerJewell** [comment]
We don't accept tickets that are not properly filled out with clear issues and reproducibility steps.  We get 100s of tickets each week, so need clear details before we can help - so please think about that when opening a ticket.

**Comment by malligvt** [comment]
It is more generic ,I need options in codenvy tool to create Web service (REST/SOAP).
