### ISSUE TITLE
Node stack/angular-patternfly-starter broken

### ISSUE THREAD

**Issue by Zhigalin** [codenvy/codenvy#2099]
Trying to create a workspace for Angular development
I have created a workspace from Node.js ready-to-go stack and _angular-patternfly-starter_ template.
Inside there is a built-in command to run the project but it fails with the following output:
> grunt-cli: The grunt command line interface (v1.2.0)
>
>Fatal error: Unable to find local grunt.
>
>If you're seeing this message, grunt hasn't been installed locally to
>your project. For more information about installing and configuring grunt,
>please see the Getting Started guide:
>
>http://gruntjs.com/getting-started

**Codenvy version:**    
5.8.0 (codenvy.io)

**Comment by eivantsov** [comment]
You need to install dependencies first. In the terminal run:

```
cd angular-patternfly-starter 
npm install
bower install
```

After that, run the `run` command, however, before that you need to edit Gruntfile.js to unbind the server from localhost:

```
   connect:  {
      options:    {
        base: '<%= projectSettings.src %>',
        port: grunt.option("port") || 8003,
        hostname:   '0.0.0.0', // 0.0.0.0 allows access from outside
        livereload: 37830
      }
```

**Comment by Zhigalin** [comment]
For 4 minutes it just does nothing than it says:

> npm WARN deprecated grunt-ngmin@0.0.3: use grunt-ng-annotate instead
> npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
> npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
> npm WARN deprecated ngmin@0.4.1: use ng-annotate instead
> angular-patternfly-demo-app@0.0.1 /projects/angular-patternfly-starter
> 
> ... Omitted ...
> 
> bower patternfly#3.13.0                               invalid-meta for:/tmp/f018d0ae2785c44d7e79ea451e18a4e4/bower/ecd5a67191fbb1ae56f51993f1a892a3-450-s9v7tE/bower.json
> 
> bower patternfly#3.13.0                               invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .css files: ["dist/css/patternfly.css","dist/css/patternfly-additions.css"]
> 
> ... Omitted ...
> 
> bower matchHeight#~0.7.0                              invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
> 
> ... Omitted ...
> 
> bower patternfly-bootstrap-treeview#~2.1.0            invalid-meta for:/tmp/f018d0ae2785c44d7e79ea451e18a4e4/bower/459af7aba6f742784cdd328a78935107-450-o8xvCV/bower.json
> bower patternfly-bootstrap-treeview#~2.1.0            invalid-meta The "main" field cannot contain minified files
> 
> ... Omitted ...
> 
> bower eonasdan-bootstrap-datetimepicker#~4.17.37      invalid-meta for:/tmp/f018d0ae2785c44d7e79ea451e18a4e4/bower/76bd398ee7174f6f95c3ab9b1ab3c397-450-wFrqoD/bower.json
> bower eonasdan-bootstrap-datetimepicker#~4.17.37      invalid-meta The "main" field cannot contain minified files
> bower eonasdan-bootstrap-datetimepicker#~4.17.37      invalid-meta The "main" field cannot contain minified files
> 
> ... Omitted ...
> 
> bower datatables#~1.10.12                             invalid-meta for:/tmp/f018d0ae2785c44d7e79ea451e18a4e4/bower/06669348abd69fdff10f03f7c7ff1571-450-q0p9VV/bower.json
> bower datatables#~1.10.12                             invalid-meta The "main" field cannot contain font, image, audio, or video files
> bower datatables#~1.10.12                             invalid-meta The "main" field cannot contain font, image, audio, or video files
> bower datatables#~1.10.12                             invalid-meta The "main" field cannot contain font, image, audio, or video files
> bower datatables#~1.10.12                             invalid-meta The "main" field cannot contain font, image, audio, or video files
> bower datatables#~1.10.12                             invalid-meta The "main" field cannot contain font, image, audio, or video files
> bower datatables#~1.10.12                             invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .png files: ["media/images/sort_asc.png","media/images/sort_asc_disabled.png","media/images/sort_both.png","media/images/sort_desc.png","media/images/sort_desc_disabled.png"]
> bower bootstrap#>=2.3.2                                    extract archive.tar.gz
> bower google-code-prettify#~1.0.5                     invalid-meta for:/tmp/f018d0ae2785c44d7e79ea451e18a4e4/bower/8b46b49e999a9774c040fd46f81a68a5-450-NM9QuY/bower.json
> bower google-code-prettify#~1.0.5                     invalid-meta The "main" field cannot contain minified files
> bower google-code-prettify#~1.0.5                     invalid-meta The "main" field cannot contain minified files
> bower datatables#~1.10.12                                 resolved https://github.com/DataTables/DataTables.git#1.10.15
> bower datatables#>=1.7.0                              invalid-meta for:/tmp/f018d0ae2785c44d7e79ea451e18a4e4/bower/06669348abd69fdff10f03f7c7ff1571-450-8m1HQs/bower.json
> bower datatables#>=1.7.0                              invalid-meta The "main" field cannot contain font, image, audio, or video files
> bower datatables#>=1.7.0                              invalid-meta The "main" field cannot contain font, image, audio, or video files
> bower datatables#>=1.7.0                              invalid-meta The "main" field cannot contain font, image, audio, or video files
> bower datatables#>=1.7.0                              invalid-meta The "main" field cannot contain font, image, audio, or video files
> bower datatables#>=1.7.0                              invalid-meta The "main" field cannot contain font, image, audio, or video files
> bower datatables#>=1.7.0                              invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .png files: ["media/images/sort_asc.png","media/images/sort_asc_disabled.png","media/images/sort_both.png","media/images/sort_desc.png","media/images/sort_desc_disabled.png"]
> bower bootstrap-datepicker#~1.6.4                     invalid-meta for:/tmp/f018d0ae2785c44d7e79ea451e18a4e4/bower/5302a8e90732aef5f2e93a0af3490637-450-AioStu/bower.json
> bower bootstrap-datepicker#~1.6.4                     invalid-meta The "main" field cannot contain minified files
> bower bootstrap-datepicker#~1.6.4                         resolved https://github.com/eternicode/bootstrap-datepicker.git#1.6.4
> bower datatables#>=1.10.8                             invalid-meta for:/tmp/f018d0ae2785c44d7e79ea451e18a4e4/bower/06669348abd69fdff10f03f7c7ff1571-450-zWzRE7/bower.json
> bower datatables#>=1.10.8                             invalid-meta The "main" field cannot contain font, image, audio, or video files
> bower datatables#>=1.10.8                             invalid-meta The "main" field cannot contain font, image, audio, or video files
> bower datatables#>=1.10.8                             invalid-meta The "main" field cannot contain font, image, audio, or video files
> bower datatables#>=1.10.8                             invalid-meta The "main" field cannot contain font, image, audio, or video files
> bower datatables#>=1.10.8                             invalid-meta The "main" field cannot contain font, image, audio, or video files
> bower datatables#>=1.10.8                             invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .png files: ["media/images/sort_asc.png","media/images/sort_asc_disabled.png","media/images/sort_both.png","media/images/sort_desc.png","media/images/sort_desc_disabled.png"]
> bower google-code-prettify#~1.0.5                         resolved https://github.com/tcollard/google-code-prettify.git#1.0.5
> bower datatables#>=1.7.0                                  resolved https://github.com/DataTables/DataTables.git#1.10.15
> bower datatables#>=1.10.8                                 resolved https://github.com/DataTables/DataTables.git#1.10.15
> bower jquery#~1.9.0                                     deprecated Package jquery is using the deprecated component.json
> bower jquery#~1.9.0                                       resolved https://github.com/jquery/jquery-dist.git#1.9.1
> bower bootstrap-select#~1.10.0                            resolved https://github.com/silviomoreto/bootstrap-select.git#1.10.0
> bower bootstrap#~3.3.7                                    resolved https://github.com/twbs/bootstrap.git#3.3.7
> bower bootstrap#>=3.0.0                                   resolved https://github.com/twbs/bootstrap.git#3.3.7
> bower bootstrap#>=2.3.2                                   resolved https://github.com/twbs/bootstrap.git#3.3.7
> bower font-awesome#~4.6.3                                 resolved https://github.com/FortAwesome/Font-Awesome.git#4.6.3
>  
> Please note that,
>     angular-resource#1.3.20 depends on angular#1.3.20 which resolved to angular#1.3.20
>     angular-bootstrap#0.13.0 depends on angular#>=1.3.0 which resolved to angular#1.3.20
>     angular-patternfly#3.13.0 depends on angular#1.3.0 - 1.5.* which resolved to angular#1.3.20
>     angular-animate#1.5.11, angular-aria#1.5.11, angular-route#1.5.11, angular-sanitize#1.5.11 depends on angular#1.5.11 which resolved to angular#1.5.11
>     angular-mocks#1.6.4 depends on angular#1.6.4 which resolved to angular#1.6.4
> Resort to using angular#1.5.* which resolved to angular#1.5.11
> Code incompatibilities may occur.
> 
> bower                                                    ECONFLICT Unable to find suitable version for jquery

And than it breaks:
> Workspace agent is no longer responding. To fix the problem, restart the workspace.

**Comment by eivantsov** [comment]
You should do it in the terminal, not as a command.

**Comment by Zhigalin** [comment]
Ok, thanks.
Now the example application works.
But In the IDE I'm getting errors like
> 'angular' is undefined
> 'module' is undefined
> 'require' is undefined

**Comment by eivantsov** [comment]
You need to apply suggestions provided by Orion: 
![image](https://cloud.githubusercontent.com/assets/5337267/25234780/cd0001aa-25eb-11e7-933f-ebfb35aefe67.png)

**Comment by Zhigalin** [comment]
@eivantsov I see no button inside the error message

**Comment by eivantsov** [comment]
Click the red cross icon. You will see a popup.

**Comment by eivantsov** [comment]
Can you share a screenshot? What browser do you use?

**Comment by Zhigalin** [comment]
![2017-04-20 16 18 12](https://cloud.githubusercontent.com/assets/8227915/25235321/168603bc-25e5-11e7-8b04-34d553781806.png)
Linux, Firefox 51

**Comment by eivantsov** [comment]
I see, you are using a light theme. It is a bug then. But you can still try to click on that white area.

**Comment by Zhigalin** [comment]
Yes, now it works, thanks
