### ISSUE TITLE
How to create Web service(REST/SOAP) in Codenvy using tomcat server.

### ISSUE THREAD

**Issue by malligvt** [codenvy/codenvy#2101]
Hi ,I am working on Web based applications using JAVA/J2EE technologies.I learn't Web service and planning to practice using this tool.

I am new to codenvy, I need step by step procedure how to create Web service (SOAP/REST) using this tool,So that i can practice Web service by creating sample applications.

**Reproduction Steps:**
   Need steps to create Web service(REST/SOAP) in codenvy.

**Codenvy version:**    5.8.0 (codenvy.io)

**Comment by eivantsov** [comment]
@malligvt perhaps you need to start with studying some tutorials like https://www.eclipse.org/che/docs/tutorials/maven/index.html

Codenvy provides IDE which is similar to what you got used on desktop - there are no Codenvy specific features that you should know when building a rest service.

**Comment by eivantsov** [comment]
Closed due to inactivity. Feel free to reopen if you have more specific questions

**Comment by cyberglad** [comment]
The tutorial from the link is not working. Codenvy doesn't like Spring Boot Apps: I specified a new "run" command (mvn spring-boot:run), but it brings up an error: "No plugin found for prefix 'spring-boot' in the current project". In POM file there is obviously a Spring Boot plugin....

**Comment by eivantsov** [comment]
@cyberglad I will take a look. What project are we talking about? The standard spring boot app?

**Comment by cyberglad** [comment]
yep, in fact create any spring boot app en CodeNvy and try to start it with mvn spring-boot:run

**Comment by eivantsov** [comment]
@malligvt if maven complains about not having spring plugin in root pom.xml, i do not see any reasons why it might a be Codenvy fault. Probably smth is wrong with your project or you select the wrong project when executing your command.

What I did is:

1. Started a java workspace
2. Imported https://github.com/spring-projects/spring-boot
3. Created the following command and tried a tomcat sample app:

![image](https://user-images.githubusercontent.com/5337267/27944184-d8b99026-62ed-11e7-9e49-a52c392e77aa.png)

Hope this helps

**Comment by cyberglad** [comment]
well, if the same project runs ok in Eclipse but doesn't run in Codenvy, which do you think I  have to look for the error? If spring plugin weren't in root pom.xml, the project wouldn't have run on Eclipse neither.

**Comment by eivantsov** [comment]
Can you share a screenshot please? I am pretty sure the command is run int he wrong context.

**Comment by cyberglad** [comment]
I tried to execute the commands manually: cd from the terminal to project folder and mvn spring-boot:run . It seems to work (got the message "Tomcat started on port(s): 8080 (http)"). But I can't access the app from node21.codenvy.io:39685 (as noted in Runtime Properties). No firewall on my side. What might be the problem?

**Comment by eivantsov** [comment]
I can access your app:

![image](https://user-images.githubusercontent.com/5337267/27955835-617374dc-631f-11e7-9071-7c0ec59deec7.png)

**Comment by eivantsov** [comment]
Closed due to inactivity
