### ISSUE TITLE
ssh publickey works via IDE to access a repo, but not via terminal

### ISSUE THREAD

**Issue by thorstenKoch** [codenvy/codenvy#2105]
In my workspace i cloned a repo of a git server. that this can happen, i created a ssh public key in profile->preferences->ssh-vcs with domain.tld. this in imported in my profile in the git server. cloning worked fine.

this is an angular2 project. In the project's packages the same server, but other repo is referenced too. But with 

> npm install 

the other repo cannot be accessed, because it throwns an 

> Permission denied (publickey)

Looks like, that the publickey will not be served within the terminal. 

**Reproduction Steps:** create workspace, import project from a git repo (which requires a project from the same repo server), run num install

**Codenvy version:**    5.8.0

**OS and version:**    node-default

**Comment by eivantsov** [comment]
The IDE git and git installed in a workspace are two different git systems. When you clone in the IDE the key is retrieved from user prefs. In the terminal, git is looking for a default ~/.ssh/id_rsa

**Comment by thorstenKoch** [comment]
Thank you eivantsov for this info. Would be nice, if there is a button in the VCS Config to copy certs to terminal to get this done automatically. I finally got it work and for others i want to describe the long way road:

First of all: It is really NOT useful, that i cannot copy & paste in the terminal and that the context menu isn't working as well. Therefore we have to do some extra work.

According to the doku of bitbucket, i created a ssh key in the terminal: https://confluence.atlassian.com/bitbucket/set-up-ssh-for-git-728138079.html

First step: Create ssh key:

> ssh-keygen

I left the password blank for faster use.
The id_rsa file has wrong permissions, "ssh-add" will complain. Therefore we change them to 

> sudo chmod 0700 ~/.ssh/id_rsa

We have to start the ssh agent and we can add the ssh key

> ssh-agent /bin/bash
> ssh-add ~/.ssh/id_rsa 

Now we want to create the public key:

> cat ~/.ssh/id_rsa.pub

But how can we access the public key? We could install vim to have a text editor. But as i allready said, copy&paste isn't working in the terminal. Therefore we have to copy the id_rsa.pub file to our workspace and use the che editor for that:

> cp ~/.ssh/id_rsa.pub .

Now open it in the che editor, copy it and insert it in the profile of your favorite repo software.
.
