### ISSUE TITLE
Newbie Alert!  How do I import my Maven settings.xml into my Java/Maven workspace?

### ISSUE THREAD

**Issue by ghoelzer-rht** [codenvy/codenvy#2106]
Created new Java/Maven workspace and imported Java/Maven project into workspace with pom.xml in root.  Assuming I can import my .m2/settings.xml to specify the external Maven Repo's needed?  Where do I do this, quick google search of docs, etc. doesn't give me any clues other than creating settings.xml on my workspace container?

**Reproduction Steps:**
Import existing Java/Maven project

**Codenvy version:**    
 5.8.0 

**OS and version:**    
Ubuntu 16.04

**Docker version:**    
N/A

**Codenvy cli.log output:**  

N/A

**Comment by ghoelzer-rht** [comment]
p.s.  This is a Fuse/Apache Camel Project, anyway I can import those Plugins and customize my workspace?

**Comment by eivantsov** [comment]
@ghoelzer-rht you may keep your settings.xml with the project and then provide a path to it in your maven commands. I think it is `-s` option.

Also, you can create it in ~/.m2 and it will be persisted since when you stop a workspace it is snapshotted.

**Comment by ghoelzer-rht** [comment]
Excellent, good deal.  I will give that a shot.  Thanks for the quick response!

**Comment by eivantsov** [comment]
@ghoelzer-rht did any of my suggestions work for you?

**Comment by eivantsov** [comment]
@ghoelzer-rht I am closing the issue. Feel free to reopen if none of my suggestions worked for you
