### ISSUE TITLE
Failed to create stack

### ISSUE THREAD

**Issue by acidblue** [codenvy/codenvy#2117]
How do you create a stack??
Every time I try to create a PHP stack I get an error saying "User doesn't have permissions". 
Sorry I just dont get it. I am the only user on my account, why dont I have permission to create a stack????

**Comment by eivantsov** [comment]
@acidblue can you provide me with some more information? You simply go to User Dashboard, choose php stack and click create?

**Comment by acidblue** [comment]
There isnt any option to create a stack in my dashboard, there is only Teams, Workspace and Factories.

**Comment by eivantsov** [comment]
Can you share a screenshot? Are you on codenvy.io?

**Comment by acidblue** [comment]
Never mind I figured it out, you have to create a workpspace first.
