### ISSUE TITLE
Files/applications deleted from project after workspace restart

### ISSUE THREAD

**Issue by bardascat** [codenvy/codenvy#2118]
Hello,
I have the following issue:

**Reproduction Steps:**
1.I started a workspace using ubuntu/php stack, and I downloaded my project source files from gitlab.
2. Install bower/npm packages using bower install, npm install
3. Restart workspace
4. Bower/Npm packages installed previously are deleted. Other files from git are persisted.

Did anyone encounter this issue?

Thanks,
Catalin

**Comment by TylerJewell** [comment]
Yes this is by design.  You can control this in how you save.

If you save without snapshot then only your project files (code) are saved in offline strategy.  If you save with snapshot then we capture the entire binary.

The only exception is that if you have files in gitignore we do not include them in the offline store of the project files.

Tyler

**Comment by bardascat** [comment]
Hi Tyler,

I appreciate  your fast answer.

The only question left is, how do I save with snapshot ?
When i right click on the workspace name It pops up to options:, **stop, and stop without snapshot.**

Should I consider that by default the "stop" option will create a snapshot and save the state of the workspace? (entire binary).

Thanks,
Catalin

**Comment by TylerJewell** [comment]
Yeah correct - stop with snapshot should be the default unless you are running an enterprise version where the admin configured the default to be the opposite.

So I would verify things and check your gitignore.

Tyler

**Comment by bardascat** [comment]
Yes the problem is with .gitignore.
Basically node_modules, and bower_components, are ignored by git, so each time I restart the workspace I lose them.

Did anyone find a "workaround" to persist gitignore files? Or the only option is to install them everytime I start developing.
Pushing them to git is not an option at the moment.

**Comment by TylerJewell** [comment]
We are working on an improvement now that will give you configurable control over what is included or not in the offline storage.  But it will take some time.  This gitignore problem disappears as a result.

Tyler

**Comment by bardascat** [comment]
Thanks for your support !

**Comment by mrmachine** [comment]
@TylerJewell Any ETA on this? I'm testing out Codenvy and we also need a lot of files to run our project that are ignored by git (bower_components, node_modules, and a Python virtualenv)... Having to download and install all these every time the workspace is restarted seems like a big problem that will hold up our adoption of Codenvy.

**Comment by TylerJewell** [comment]
Probably 3-6 months.  We need to finish our port of Che to run on Kubernetes and it will solve these problems with persistent volumes eliminating the need to have to specify these attributes.

**Comment by mrmachine** [comment]
@TylerJewell is there any workaround we can use in the meantime, besides removing files from `.gitignore`? We don't want to accidentally commit 200MB of node modules to our git repository, and even if we avoid that it will clutter up `git status` output for all developers all the time :)

**Comment by TylerJewell** [comment]
The gitignore is the only known work around.  It is not a great answer but if you can wait the Kubernetes solution will be much stronger.

**Comment by mrmachine** [comment]
@TylerJewell is this still a problem?
