### ISSUE TITLE
The 'Docs' link from the Ide 'Help' menu is brocken

### ISSUE THREAD

**Issue by SkorikSergey** [codenvy/codenvy#2124]
**Reproduction Steps:**
Start any workspace
**Menu** -> **Help** -> **Docs**

**Server location:** nightly.codenvy-stg.com, nightly-onprem.codenvy-stg.com

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![anim](https://cloud.githubusercontent.com/assets/7760565/25277497/946d289c-26a7-11e7-89ee-b81ee6393ff9.gif)

**Comment by slemeur** [comment]
It must redirects to the docs that are embed.
As it is handled in the dashboard's footer
