### ISSUE TITLE
Authentication failed, won't close connection or interrupt until timeout

### ISSUE THREAD

**Issue by janat08** [codenvy/codenvy#2125]
Authentication failed. Please check username and password.
---------------------------------------
!!!
!!! ERROR: Error when trying to get workspace data for workspace named meteor
!!!
---------------------------------------
List of workspaces are:
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^CERROR: (Eclipse Che action/list-workspaces): HTTP error: Error: connect ETIMEDOUT 172.17.0.1:8080
Received interrupt signal. Exiting.

**Comment by TylerJewell** [comment]
Please consider reopening when you provide full diagnostic and steps to reproduce for engineers otherwise they will not know how to help.
