### ISSUE TITLE
Making missing mandatory parameters unmandatory?

### ISSUE THREAD

**Issue by janat08** [codenvy/codenvy#2126]
Are the possible root causes are for why parameters are mandatory since they're not ever mentioned in guides. I'm on opensuse and granted myself docker rights. Rest of it I don't understand what it's about.

//pasted the whole thing for search results of others
```
INFO: Welcome to Codenvy!
INFO: 
INFO: You are missing a mandatory parameter:
INFO:    1. Mount 'docker.sock' for accessing Docker with unix sockets.
INFO:    2. Or, set DOCKER_HOST to Docker's location (unix or tcp).
INFO: 
INFO: Mount Syntax:
INFO:    Start with 'docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock' ...
INFO: 
INFO: DOCKER_HOST Syntax:
INFO:    Start with 'docker run -it --rm -e DOCKER_HOST=<daemon-location> ...'
INFO: 
INFO: Possible root causes:
INFO:    1. Your admin has not granted permissions to /var/run/docker.sock.
INFO:    2. You passed '--user uid:gid' with bad values.
INFO:    3. Your firewall is blocking TCP ports for accessing Docker daemon.
```

**Comment by eivantsov** [comment]
@janat08 try granting permissions for `/var/run/docker.sock` and give it a shot again:

`sudo chmod 777 /var/run/docker.sock`

**Comment by janat08** [comment]
docker run -it --rm  -v ~/Docker/:/data -v ~/Documents/Docker/:/sync eclipse/che sync meteor --url https://codenvy.io --password * --user * --unison-verbose

I've granted permissions to socket.

**Comment by janat08** [comment]
@eivantsov So I'm guessing the .sock parameter is truly mandatory rather than remedial measure.
