### ISSUE TITLE
Ctrl+C won't won't interrupt che sync unison processs

### ISSUE THREAD

**Issue by janat08** [codenvy/codenvy#2128]
**Reproduction Steps:**
Will not work for anything
**Codenvy version:**    
INFO: (che cli): 5.8.0 - using docker 1.13.0 / native

**OS and version:**    
Opensuse tumbleweed.
**Docker version:**    
```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7
 Git commit:   78d1802
 Built:        Wed Mar 22 23:25:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7
 Git commit:   78d1802
 Built:        Wed Mar 22 23:25:45 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
**Codenvy cli.log output:**  
INFO: (che mount):  Starting sync process to /home/jk/Documents/Docker/
Mon Apr 24 00:29:47 UTC 2017
/usr/bin/curl  "-I -k https://hub.docker.com -s -o /dev/null --write-out %{http_code}"
Checking registry for version '5.8.0' images
eval BOOTSTRAP_IMAGE_ALPINE=alpine:3.4
eval BOOTSTRAP_IMAGE_CHEIP=eclipse/che-ip:5.8.0
eval IMAGE_INIT=eclipse/che-init:5.8.0
eval IMAGE_CHE=eclipse/che-server:5.8.0
eval IMAGE_COMPOSE=docker/compose:1.8.1
eval UTILITY_IMAGE_CHEACTION=eclipse/che-action:5.8.0
eval UTILITY_IMAGE_CHEDIR=eclipse/che-dir:5.8.0
eval UTILITY_IMAGE_CHETEST=eclipse/che-test:5.8.0
eval UTILITY_IMAGE_CHEMOUNT=eclipse/che-mount:5.8.0
INFO: (che cli):  5.8.0 - using docker 1.13.0 / native
/usr/bin/curl  "-s https://hub.docker.com/v2/repositories/eclipse/che/tags/"
INFO:  Newer version '5.8.1' available
\033[0;32mINFO:\033[0m (che download): Checking for image 'eclipse/che-action:5.8.0'... found
\033[0;32mINFO:\033[0m (che download): Checking for image 'eclipse/che-dir:5.8.0'... found
\033[0;32mINFO:\033[0m (che download): Checking for image 'eclipse/che-test:5.8.0'... found
\033[0;32mINFO:\033[0m (che download): Checking for image 'eclipse/che-mount:5.8.0'... found
INFO: (che mount):  Starting sync process to /home/jk/Documents/Docker/

**Comment by eivantsov** [comment]
@janat08 can you be more specific in your issues? It's sometime really difficult to guess what problems you have with the product.

**Comment by janat08** [comment]
I'm sorry, It's the ctrl+C on local that I'm talking about.

**Comment by garagatyi** [comment]
@TylerJewell should we move it to Che?

**Comment by eivantsov** [comment]
Fixed in the latest nightly image
