### ISSUE TITLE
Forbidden error in time of starting PHP application by Apache

### ISSUE THREAD

**Issue by dmytro-ndp** [codenvy/codenvy#2132]
**Reproduction Steps:**
1. Create workspace from PHP stack.
1. Create PHP-application from samples.
1. Start apache server.
1. Go to preview url.

**Expected result:**
There is start page of php-application

**Actual result:**
there is FORBIDDEN error message on application page:
![screenshot from 2017-04-24 16 18 02](https://cloud.githubusercontent.com/assets/1197777/25339186/7765302c-290a-11e7-9882-e81721a734dd.png)

![out](https://cloud.githubusercontent.com/assets/1197777/25339441/6df19926-290b-11e7-93c8-4b3fbb814bb8.gif)

Start apache command output:
```
==> /var/log/apache2/error.log <==
[Mon Apr 24 13:22:50.230388 2017] [core:error] [pid 1548] (13)Permission denied: [client 172.19.20.32:40890] AH00035: access to /php denied (filesystem path '/projects/php') because search permissions are missing on a component of the path, referer: http://172.19.20.32/admin/wksp-y7oy
 
==> /var/log/apache2/access.log <==
172.19.20.32 - - [24/Apr/2017:13:22:51 +0000] "GET /favicon.ico HTTP/1.1" 403 517 "http://172.19.20.32:42888//php" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36"
 
==> /var/log/apache2/error.log <==
[Mon Apr 24 13:22:51.175409 2017] [core:error] [pid 1548] (13)Permission denied: [client 172.19.20.32:40890] AH00035: access to /favicon.ico denied (filesystem path '/projects/favicon.ico') because search permissions are missing on a component of the path, referer: http://172.19.20.32:42888//php
```

**Root problem:**
There is lack of read permissions on project directory:
```
user@bbeac5137d63:~$ ls -la /projects/php
total 12
drwxr-x--- 2 user user 4096 Apr 24 13:00 .
drwxr-x--- 3 user root 4096 Apr 24 13:00 ..
-rw-r----- 1 user user   30 Apr 24 13:00 hello.php
```

**Codenvy version:**
Version: 5.9.0-SNAPSHOT
Revision: e817976b9ea2c668
Build Time: 2017-04-22 08:37:27

**OS and version:**    
Ubuntu 14.04

**Docker version:**
```ndp@ndp:~/projects/che$ docker info
Containers: 16
 Running: 12
 Paused: 0
 Stopped: 4
Images: 70
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 440
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.0-66-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 23.55 GiB
Name: ndp
ID: MQQY:YLPQ:OOVF:QKDE:NFD7:26MQ:CFLB:DKSU:4KVP:BNYD:BRNW:7GTX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

This issue is related to https://github.com/eclipse/che/issues/4843

There is selenium tests [com.codenvy.ide.debugger.PhpProjectDebuggingTest#shouldDebugWebPhpScriptFromNonDefaultPortAndNotFromFirstLine](https://github.com/codenvy/qa/blob/ca03d5444eedca895c489ea5c14c00bbc8eaf769/src/test/java/com/codenvy/ide/debugger/PhpProjectDebuggingTest.java#L163-L163) which fails because of this bug.

**Comment by eivantsov** [comment]
Not sure why this has not happened before. Running the right `chmod` on `/projects` fixes it. Maybe, it's ws-agent script that creates `/projects` dir and runs chown on it is what causes the problem.

**Comment by riuvshin** [comment]
fixed
