### ISSUE TITLE
files missing on reload

### ISSUE THREAD

**Issue by startupgurukul** [codenvy/codenvy#2133]
After each reload(after container is shutdown, due to inactivity) files are missing. Until now only node_modules was missing which was unexpected but still was ok as we can do npm install, but recently a config file started missing 

**Reproduction Steps:**
firebase init (create few configuration files for us.) On snapshot and reload, one of firebase.json file is missing. 

Version :5.8.1
Revision :dd5f15c94b783035
Build Time :2017-04-22 12:11:11

**Comment by TylerJewell** [comment]
This is probably the same question as - https://github.com/codenvy/codenvy/issues/2025.  This is likely expected behavior given our current (changing soon) behavior with .gitignore files.

**Comment by startupgurukul** [comment]
yes thank you. same issue

**Comment by TylerJewell** [comment]
Ok - can you track the other issue - will close this one.

**Comment by startupgurukul** [comment]
Thank you as usual for the super quick responses
