### ISSUE TITLE
worskpace agent stop abruply in the middle of a command, container gets restarted 

### ISSUE THREAD

**Issue by startupgurukul** [codenvy/codenvy#2134]
running a heavy process kills the workspace agent and then the workspace

**Reproduction Steps:**
sudo npm install -g create-react-app 
create-react-app someapp
cd someapp
npm run build

Thats all snapshotting and workspace is shutdown 

**Codenvy version:**    
Version :5.8.1
Revision :dd5f15c94b783035
Build Time :2017-04-22 12:11:11

**OS and version:**    

**Docker version:**    

**Codenvy cli.log output:**

**Comment by TylerJewell** [comment]
Docker containers are somewhat more vulnerable than VMs. If you over consume the memory and CPU allocated to it in an aggressive way, then that can cause other processes that we have running inside the container to get clobbered.

What was the RAM you allocated?

**Comment by startupgurukul** [comment]
2GB, the deafult

**Comment by TylerJewell** [comment]
That should be enough RAM - you'd need to look at the entire system to get a sense of whether the agents and the other processes are interfering with one another.  Let's see if some engineers can try the sample you propose.

**Comment by startupgurukul** [comment]
more detailed repro steps, 

its a node template and with 2 GB default RAM..(its shouldnt matter but sample code used is the nodejs-hello-world --BTW it would be great if there is an option with no sample code instead of mandating it)


Once it is up, do
sudo npm install -g create-react-app
create-react-app someapp
cd someapp
npm run build

we will hit the issue at least once every 2-3 times, it some times work if we are feeling lucky ;)

**Comment by eivantsov** [comment]
@startupgurukul this is expected behavior and you should have got a self explanatory error message in the IDE. @TylerJewell's suggestion to allocate more RAM is the way to go. Closing the issue.

**Comment by startupgurukul** [comment]
It would be nice to kill that process rather than shutting down workspace..So the message it said was workspace agent not responding.

**Comment by eivantsov** [comment]
It is not Codenvy that kills any processes but Linux kernel. And usually it kills the "fattest" process which is usually ws-agent.

**Comment by startupgurukul** [comment]
Aah So aggressive in c9.io I think I noticed something like disk swapping, I may be wrong though. 

But in general moving to 3GB, solved the problem I am facing. Thanks for the support.
