### ISSUE TITLE
Unable to connect via offical eclipse plugin

### ISSUE THREAD

**Issue by HLOL29KUHD232** [codenvy/codenvy#2135]
Official Codenvy plugin for Eclipse plugin authorization does not work.
"Authentication failed" message appears. It might be connected with fact that https://52.55.17.101 have incorrect SSL certificate according to Firefox.

**Reproduction Steps:**

1. Install Eclipse 4.6.3
2. Install official Codenvy plugin "Codenvy Eclipse Plugin	1.2.0"
3. Create new project (Codenvy ->Projects from Codenvy)
4. Enter login/password info
5. Click next.

![error_codenvy](https://cloud.githubusercontent.com/assets/26456824/25394198/d6756aae-29dd-11e7-8853-b6ee62c43307.png)

**Codenvy version:**    5.8.1

**OS and version:**    Windows 7

**Comment by TylerJewell** [comment]
Hi!  Can you let us know where you found that plugin?  That plugin was only certified for Codenvy 3.x.  We have not maintained it for Codenvy 4.x or 5.x.  We need to remove it from any download sites.

**Comment by HLOL29KUHD232** [comment]
https://install.codenvycorp.com/eclipse-plugin/updates/

**Comment by eivantsov** [comment]
@HLOL29KUHD232 and what page references this download link? It'll be removed.

**Comment by romilpunetha** [comment]
@TylerJewell Why discontinue with the plugin? Is there an alternative that provides this functionality? Isn't the idea to be able to use your local IDE, one that you're comfortable with, along with harnessing the power of the cloud great?

**Comment by TylerJewell** [comment]
There was no demand for the solution and it was not used.  There was more demand for a pure browser solution and we have invested all our resources into our own ide.   The code is open source so you could update it yourself if you want.
