### ISSUE TITLE
[Question] Is there a way to disable error checking?

### ISSUE THREAD

**Issue by Zhigalin** [codenvy/codenvy#2138]
Hello!
Due to #2089 I see a lot of pesky errors and warnings in the editor.
Also there are errors because strange parsing so it needs things like `/*eslint-env es_modules */` and if I can't/don't want to add these annotations to my files I must just stick with these, indeed bothersome, warnings, so I ask:
Is there a way to disable error checks in the editor?

**Comment by eivantsov** [comment]
Currently, there is no way to disable orion js support.

**Comment by Zhigalin** [comment]
Ok, thanks
