### ISSUE TITLE
Sync Inotify instead of scan

### ISSUE THREAD

**Issue by janat08** [codenvy/codenvy#2152]
Adding projects to the same workspace causes sync to take a while, and even then 2 second intervals aren't great. Would it be possible to listen for changes instead of scanning?

**Comment by TylerJewell** [comment]
That is a great idea, but it would require custom client implementations. We do have file system watchers with notifications optimized for how we keep the IDE client light and fast. The IDE gets events for major file events related to what is currently visible.  It would require a custom sync client for each OS to do the same.  I don't think we would plan to do this in the near future, but would accept a pull request.

**Comment by janat08** [comment]
Could you make a docker contained folder for this instead with watcher code
ported from ide?

**Comment by TylerJewell** [comment]
Anything is possible, but it would not be simple. The IDE client-side code is optimized for a project tree that has expansions and selected views. A synchronizer has to be optimized for full synchronization. It does not have the luxury of understanding that a portion of the screen is only being used to view files.

**Comment by janat08** [comment]
Well windows as far as I know doesn't even support anything like inotify so
docker based solution is possibly what you'd want to be after.
