### ISSUE TITLE
Updating file... popup message interrupts development

### ISSUE THREAD

**Issue by MPNull** [codenvy/codenvy#2154]
![image](https://cloud.githubusercontent.com/assets/7377310/25621316/bbf0afb4-2f59-11e7-97b0-43961ba62172.png)

I don't know about the version stuff etc, but this is distracting af. Sometimes I save the file and this popups randomly and it keeps doing it forever or one hour. I have only one .php file on the workspace at the moment. This time while it says "Updating file..." the workspace will timeout or something since it never finish if I remember so. Yesterday I just let it ran as long as needed and after some hours it was gone, but workspace was turned off.

Yes. I have deleted and re-created the workspaces and such, but actually nothing helps. I don't even know what it is. And yes. I have a stable connection.

Wondering whats the exact thing it even does when it popups this message. Says like "File Saved..." and it starts after it sometimes, but whenever it starts I already know that my workspace will fk up again and requires reloading, restarting etc.

**Comment by 20avva** [comment]
This happens to me a lot but never lasts to the point of time-out. Try reloading the webpage whenever you get the problem.

**Comment by MPNull** [comment]
It keeps loading the workspace then. Workspace needs to be turned off and opened again. It's just kinda boring while doing debugging and trying to get some script work by saving frequently so it have higher chance to popup.

I've loaded the whole page again and cleared cache and stuff, but if it popups it always gets stuck.

**Comment by eivantsov** [comment]
I just tried it with a node stack and it worked for me. What stack did you use for this language server?

**Comment by eivantsov** [comment]
Related to https://github.com/codenvy/codenvy/issues/2146

**Comment by eivantsov** [comment]
Closing as fixed
