### ISSUE TITLE
Allow codenvy.io users to change their email

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#2156]
Right now there is no way for a user with a codenvy.io account to change their email and retain their stacks, workspaces, factories, etc...

It would be helpful for us to provide a way for a user to change the email associated with an account. The process would be:
- User changes their email in the Account > Profile page of the user dashboard (we'd have to add email there)
- System send an account verification email to the new address
- Clicking a link in the email finalizes the change
- The new email address is also added to the marketing automation system so that operational emails can be sent to the user as needed

**Comment by TylerJewell** [comment]
Will not fix.
