### ISSUE TITLE
A web page is not redirect correctly after delete an account

### ISSUE THREAD

**Issue by SkorikSergey** [codenvy/codenvy#2159]
**Server location:** nightly.codenvy-stg.com, nightly-onprem.codenvy-stg.com

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![accountdeleting](https://cloud.githubusercontent.com/assets/7760565/25660535/61bcaa5e-3015-11e7-8ebb-03c9fbb54346.gif)

**Comment by bmicklea** [comment]
@ashumilova can this be tackled in this sprint? It's a big problem for users because they think the account isn't deleted and contact support.

**Comment by ashumilova** [comment]
yes, took to current. but the user who wrote email to wish list - really could not delete himself.

**Comment by bmicklea** [comment]
That's a different issue

> --

Brad Micklea // Codenvy // bmicklea@​codenvy.​com // 4​16​.7​07​.07​92
