### ISSUE TITLE
web IDE Editor hanging/freeze

### ISSUE THREAD

**Issue by gymadarasz** [codenvy/codenvy#2169]
IDE still says: "Updating file..."  in a popup when I try to edit/update my files and totally freeze no chance to use the IDE anymore...

**Reproduction Steps:**
Open https://codenvy.io => login
Open a file in Project Explorer
Start coding..
Little popup shows up and said: "Updating file..."
and loading.. loading.. loading.. forever..

(I don't use docker or any magical stuff, only added a default "php-stack" in workplace menu and clone my own github project into projects folder via terminal)
**Codenvy version:**    

**OS and version:**    

**Docker version:**    

**Codenvy cli.log output:**

**Comment by TylerJewell** [comment]
I think this is the same issue from Che - https://github.com/eclipse/che/issues/4974

**Comment by gymadarasz** [comment]
I agree, the issue is very similar but unfortunately I can't recreate because all of my files which was in a separated git folders in project sub-folders lost after an automatized snapshot.. :(

**Comment by TylerJewell** [comment]
Right now if you have a .gitignore file in your repository, we do not
include those files in the snapshot of the workspace to save space. We are
working on a version that will make this configurable.


Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by gymadarasz** [comment]
yes sure, I I thought of same after it's happened so just close this issue I think it's duplicated. Some extra info may help: in my project also contains composer and I didn't changed the file permissions after the git clone and composer update (if I remember correctly)

**Comment by bmicklea** [comment]
closed as duplicate.
