### ISSUE TITLE
Getting Django workspace started

### ISSUE THREAD

**Issue by khanzf** [codenvy/codenvy#2170]
I am trying to use Codenvy.io, but have no idea how to get a Django workspace started. `pip install -r requirements.txt` gives me permission errors. Is there a quick-start guide to get this working? I have not been able to find any documentation, and it is not one of the default environments.

**Comment by bmicklea** [comment]
@khanzf are you using the PHP stack in Codenvy? If so you will have to:

1. Install pip (`sudo apt-get install python-pip`) - you'll need `sudo`
2. `pip install -r requirements.txt`

Of course you'll need a requirements.txt (the sample PHP app doesn't have one).

**Comment by khanzf** [comment]
ahh, I get it! So, you are provided root access within the docker container.
Also, you have to create your virtualenv within the workspace and then set
the Run command accordingly.
Thank you, I was not familiar with how it worked. I might use this
long-term.! I appreciate it!

If I could suggest one thing, there is not sufficient documentation out
there. I have been trying to figure out how to use Codenvy for a while.
Granted, it was my fault due to misunderstanding how to configure a
Workspace, but it would be nice to have some more documentation.

--
Farhan Khan
PGP Fingerprint: 782F 342B 5B08 0D2F F4E8 82C3 FFA1 CAE1 6536 51CA

**Comment by bmicklea** [comment]
No problem @khanzf glad to help. By the way - if you are going to be using Django a lot you're best off to create a new stack with Django already in it. That way if you need to spin up a different project or projects you can simply create a new stack that will match your preferred set of tools. See https://codenvy.com/docs/getting-started/runtime-stacks/index.html
