### ISSUE TITLE
Workspace not loading

### ISSUE THREAD

**Issue by Damienh6657** [codenvy/codenvy#2172]
Could not start workspace. Reason: Start of environment 'default' failed. Error: Restoring of workspace workspace4j0n2hzkhvihi2cy filesystem terminated due to timeout on node30.codenvy.io node.

**Reproduction Steps:**
This can be reproduced every time I attempt to load my workspace.
1. Log in to codenvy
2. Click on recent workspace

**Expected Result**
Codenvy loads workspace correctly

**Actual Result**
Error appears: Could not start workspace. Reason: Start of environment 'default' failed. Error: Restoring of workspace workspace4j0n2hzkhvihi2cy filesystem terminated due to timeout on node30.codenvy.io node.

**Codenvy version:**    
5.9.1

**OS and version:**    
Windows 10 using chrome

**Docker version:**    

**Codenvy cli.log output:**

**Comment by eivantsov** [comment]
@Damienh6657 do you have any large files in your workspace projects? There's a 1 min timeout to restore workspace projects.

**Comment by Damienh6657** [comment]
There would be large files in the workspace

**Comment by eivantsov** [comment]
@Damienh6657 hosting huge files is an antipattern for Codenvy use. It should be just source code.

**Comment by tosinosibodu** [comment]
I'm having the same issue logging into my instance as described above. How do i get into the environment to  remove the large files?

Cheers,
Tosin

**Comment by eivantsov** [comment]
We will need your workspaceID that you can great at /api/workspaces
