### ISSUE TITLE
Setting up postgres with Rails

### ISSUE THREAD

**Issue by Obi-TOB** [codenvy/codenvy#2178]
I'm trying to setup a Rails environment with postgres via the codeenvy.io web environment.

I'm struggeling with the postgres part:

1. **I can** startup the standard Rails image: eclipse/ubuntu_rails
2. **I can** startup as well the eclipse/ubuntu_rails standard Rails image via "stack authoring" changing to the ruby and rails versions I need
3. **I'm not able** to run the standard postgres image: https://github.com/docker-library/postgres/blob/3d4e5e9f64124b72aa80f80e2635aff0545988c6/9.6/Dockerfile via "stack authoring -> Stack import "
```
[DOCKER] [ERROR] The command '/bin/sh -c set -x 	
&& apt-get update && apt-get install -y --no-install-recommends ca-certificates wget 
&& rm -rf /var/lib/apt/lists/* 	
&& wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture)" 	
&& wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture).asc" 	
&& export GNUPGHOME="$(mktemp -d)" 	
&& gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 	
&& gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu 	
&& rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc 	
&& chmod +x /usr/local/bin/gosu 	
&& gosu nobody true 	
&& apt-get purge -y --auto-remove ca-certificates wget' 

returned a non-zero code: 2
```
4. **I'm not able** to use a .yml file in "stack authoring"
```
services:
  db:
    image: postgres
    user: postgres
  dev-machine:
    image: alpine_jdk8
    depends_on:
      - db

Frontend error 1: "Cannot parse recipe from line: services:"
Frontend error 2: "The environment should contain exactly one dev machine. Switch on Dev property to have terminal, SSH and IDE tooling injected to the machine."
```
5. So I looked at other example using postgres: I am able to run a custom python docker image
https://hub.docker.com/r/aneesh14/custom_python/~/dockerfile/
but still a bit struggeling

As I'm new to Che & not an expert in Docker neither, I have difficulties to fully understand what's going wrong and where to look next to get this up and running.

Could you please pin point me in the right direction to create a working recipe? I would have assumed there should already be something there. I think using 5. I might get the image to run, however I would much more prefer to have it modular, and using standard images - which seems less possible with my issues in 4.

Many thanks in advance

**Comment by eivantsov** [comment]
@Obi-TOB looks like you have found a bug with stack authoring from a composefile - https://github.com/eclipse/che/issues/5047

You may try to install postgres right in your rails env, but yes, I agree, it is not the right way to go.

**Comment by eivantsov** [comment]
A fix has been merged https://github.com/eclipse/che/issues/5050 which means it should be OK running a workspace from a custom composefile after codenvy.io update.

**Comment by eivantsov** [comment]
@Obi-TOB I am closing the issue. Feel free to reopen if you have further questions.
