### ISSUE TITLE
ssh and openshift #1247

### ISSUE THREAD

**Issue by oscardelgado** [codenvy/codenvy#2179]
I need to clone an openshift repo in codenvy. I have seen in other issues that you need to open the IP of openshift.

**Comment by eivantsov** [comment]
@oscardelgado yes, please provide IP of your openshift instance.

**Comment by stubz100** [comment]
Hi,
same issue - instance IP 52.2.182.233, could you whitelist me please?

**Comment by stubz100** [comment]
Hi,
Sorry for being a pain - but after happily using codenvy with my free openshift account on the above IP (by the way many thanks for sorting this out for me), I have encountered the same issue (git ssh timeout) and realized my IP was changed to 52.90.3.223. 
I don't know if there's a way to fix this permanently, or am I supposed to report all IP changes to you?
Thanks,
Zoltan

**Comment by skryzhny** [comment]
Done.
