### ISSUE TITLE
Porting packages from Atom

### ISSUE THREAD

**Issue by janat08** [codenvy/codenvy#2180]
Would it be possible to try and let Atom IDE packages, in javascript that they are, to run on che? I imagine you'd largely have to mirror their package api.

**Comment by eivantsov** [comment]
@janat08 I don't think that we

> largely have to mirror their package api

And I am not aware of any similar community efforts.

**Comment by janat08** [comment]
Well i mean javascript runs in browser, and atom is javascript. Transcompiling their package api for fonts would be awesome since there's all kinds of javascript.

**Comment by janat08** [comment]
anyway where exactly is documentation for syntax highlighting for comparison to atom package for vue?

**Comment by eivantsov** [comment]
@janat08 there's no such documentation. Some ppl from Che community are working on plugins that inject native JavaScript into the IDE. You may want to search for such issues at https://github.com/eclipse/che
