### ISSUE TITLE
You are not allowed to start more workspaces. But I only have one.

### ISSUE THREAD

**Issue by Handyman101** [codenvy/codenvy#2181]
I can't start a workspace I can create on but not start it and when I do I get a message that says "You are not allowed to start more workspaces." I only have one workspace and have it shared with 2 other people I don't know what to do.
You are not allowed to start more workspaces.

**Comment by eivantsov** [comment]
Free tier users can only use 3GB RAM at a time. You may purchase more RAM though.

**Comment by eivantsov** [comment]
@Handyman101 do you need any help or clarification with this?

**Comment by Handyman101** [comment]
No, I got it working.



Colton J Nolan
