### ISSUE TITLE
How to create a .gitignore file?

### ISSUE THREAD

**Issue by bat1** [codenvy/codenvy#2185]
I'm trying to create file called .gitignore into Codeenvy, and it's impossible cause some error.

**Reproduction Steps:**

**Codenvy version:**    

**OS and version:**    

**Docker version:**    

**Codenvy cli.log output:**

**Comment by mmorhun** [comment]
@bat1 I've just created `.gitignore` file without any problem.
By default in *nix systems all files which names starts with `.` are considered hidden. To show hidden files use: `Main menu` -> `Project` -> `Show / Hide Hodden Files`.

**Comment by 20avva** [comment]
You could also use `touch .gitignore` and use a terminal editor (like vim or nano) if it is hassle to show hidden files every time you launch the workspace, as files starting with `.` are hidden by default.

**Comment by bat1** [comment]
Thanks, the problem has solved.

**Comment by TylerJewell** [comment]
Great - thanks.
