### ISSUE TITLE
Running run commands from ssh?

### ISSUE THREAD

**Issue by janat08** [codenvy/codenvy#2187]
How do I run ssh commands from ssh, so that I wouldn't have to spend half a gig of ram for seeing terminal output? I don't even know where the projects folder is, and sh ./entrypoint.sh does nothing.

**Comment by eivantsov** [comment]
Projects are in `/projects` in a workspace. You can ssh into your workspace https://www.eclipse.org/che/docs/ide/sync/index.html

**Comment by janat08** [comment]
That's the wrong one. All i get is che and entrypoint.sh.

**Comment by eivantsov** [comment]
@janat08 please elaborate. I have hard time understanding issues you are running into

**Comment by janat08** [comment]
You linked wrong doc article. What i'm looking for is having app server-side errors show up on local machine without opening codenvy in browser. When I SSH into codenvy, ls outputs entrypoint.sh and che.

**Comment by eivantsov** [comment]
@janat08 are you talking about your own on on prem install?

**Comment by janat08** [comment]
No.

**Comment by eivantsov** [comment]
@janat08 most likely you are in a user home directory. `cd ../..` may help

**Comment by janat08** [comment]
So how do I launch run commands from ssh?

**Comment by eivantsov** [comment]
@janat08 I don't understand what you ask for now. You were looking to a directory where projects are located.

**Comment by janat08** [comment]
Well yes, I imagined I'd have to run the run command with preview in the project directory.

**Comment by eivantsov** [comment]
@janat08 commands and preview macros are IDE features while you have got a shell into a Linux container.

**Comment by janat08** [comment]
so there's no way of running what macros do for port 3000?

**Comment by eivantsov** [comment]
@janat08 no, not in a terminal

**Comment by janat08** [comment]
I suppose I could just run it twice :P.

**Comment by janat08** [comment]
and this deserves to be a feature.
