### ISSUE TITLE
Error: Meteor-deque Npm.depends()

### ISSUE THREAD

**Issue by janat08** [codenvy/codenvy#2188]
Error: Can't find npm module 'meteor-deque'. Did you forget to call 'Npm.depends' in package.js within the 'meteor' package?

For Rocket.chat it will say:
While loading plugin compileVersion from package rocketchat:version:
error: Can't load npm module 'meteor-deque' from packages/meteor.js. Check
your Npm.depends().

**Reproduction Steps:**
Clone into some meteor repository, for example rocket.chat (they got specific run instructions), although my app will get this error after I've cloned into it again with ssh.
**Codenvy version:**   5.10
**OS and version:**    Opensuse tumbleweed

**Comment by janat08** [comment]
Node 4.6.2 for Meteor 1.4.x in https://guide.meteor.com/deployment.html#custom-deployment
docker got 5.6.0 version.

**Comment by eivantsov** [comment]
@janat08 what I have found out is that this app requires the latest Node. So, I installed 7.6.0.

There were also some permissions issues on the way (you will see prompts) but all in all it worked for me:

![image](https://cloud.githubusercontent.com/assets/5337267/26045028/cbf41a9e-3950-11e7-9046-08dfc50cedc6.png)

Just fyi, you may require to configure your workspace with 3GB of RAM.

**Comment by eivantsov** [comment]
@janat08 I have updated eclipse/meteor image with node 7.7.3

**Comment by janat08** [comment]
ty

**Comment by janat08** [comment]
Still won't run my own project. From what I remember with meteor moving to something like node 4 was a big and painful deal. I imagine rocket.chat starts as meteor npm start since it just ported itself over to 7.7.3.

Meteor version 1.4.4.2 is what I run.

**Comment by janat08** [comment]
Although rocket.chat doesn't run either. Do I reset my workstation or something?

**Comment by janat08** [comment]
/bin/bash: line 1:   459 Killed                  meteor
this also happens on new workstation.

**Comment by eivantsov** [comment]
Allocate 3GB for your workspace. I got it running just like I said before.

**Comment by janat08** [comment]
The previous workspace had 4gb, and new one run on 2gb (after the 1st error which is what youre reffering to then.)

**Comment by janat08** [comment]
You wana take a look at my previous workspace, or label this as a bug?

**Comment by eivantsov** [comment]
I see no bug so far. Please be more specific. What error do you have now? I got rocket chat running on codenvy.io.

**Comment by janat08** [comment]
Well I'm referring to previous workspace not running anything.
