### ISSUE TITLE
Error node: npm run dev

### ISSUE THREAD

**Issue by kenyk7** [codenvy/codenvy#2195]
(node:1534) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3
(node:1534) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Codenvy version: 5.10.0

**Comment by eivantsov** [comment]
@kenyk7 please edit your issue to add details and information on the problem you have. Right now, there is zero helpful information for me to help you.

What stack do you use? What project do you have? How can I reproduce the same behavior?

**Comment by kenyk7** [comment]
Stack: Nodejs
Proyect: Generated vía vue-cli
Reproduce: run command in folder proyect: npm run dev

**Comment by eivantsov** [comment]
This is just a warning.

In your app, open `config/index.js`, and change the port to 3000

```
  dev: {
    env: require('./dev.env'),
    port: 3000
```

Create a command https://www.eclipse.org/che/docs/ide/commands/index.html

Your preview URL should be `${server.3000}`

When the command is executed you will see a preview URL.

You may get more info on previews at https://www.eclipse.org/che/docs/ide/previews/index.html

**Comment by eivantsov** [comment]
@kenyk7 any update please?

**Comment by eivantsov** [comment]
@kenyk7 I'm cloding the issue. Feel free to reopen if you still have questions.
