### ISSUE TITLE
Don't snapshot /tmp folder

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#2199]
We have big snapshots on codenvy.io while limit for image is 10GB one snapshot is 89GB.
Examining that snapshot shows that overall image size is 8.7GB, but combined layers size is 89GB.
Most part of FS is /tmp folder, which is 5.5GB

I'm propose does not include in snapshot /tmp folder, 
https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard
http://www.thegeekstuff.com/2010/09/linux-file-system-structure

**Reproduction Steps:**
Just watch size of snapshot after real usage of workspace.

**Codenvy version:**    5.10.0-SaaS

**Comment by 20avva** [comment]
That's why those images take forever to boot up! I have this issue too!

**Comment by garagatyi** [comment]
BTW binaries of ws-agent, exec, the terminal also litter snapshots. We can exclude their folders too.

**Comment by mmorhun** [comment]
We should discuss that question. And I think that should be another issue.

**Comment by mmorhun** [comment]
Done.
