### ISSUE TITLE
Bitbucket SSH Can't store ssh key. Unable to get private ssh key.

### ISSUE THREAD

**Issue by janat08** [codenvy/codenvy#2204]
I've already got SSH keys on both ends, according to instructions. I couldn't pull also, which I forget what it said error was, so I'm trying to import it again.

**Comment by eivantsov** [comment]
What hostname did you generate the key for? I tried it on my side and it worked.

**Comment by janat08** [comment]
Sorry, shitposting at night. It's .org.

**Comment by airiny** [comment]
I have the same problem.
I created a new SSH key in my workspace, and installed the public key on my  external GIT repository.
But I'm getting the following error when triyng to pull from my GIT:

> Can't store ssh key. Unable get private ssh key.
