### ISSUE TITLE
Networking down

### ISSUE THREAD

**Issue by marcelobern** [codenvy/codenvy#2205]
Networking is down within codenvy.io docker instances. I suspect this is the root cause for all other issues reported by users in the last 24 hours.
ping fails to respond github.com, google.com but works for localhost and codenvy.io

**Reproduction Steps:** ping github.com; ping localhost; ping codenvy.io

**Codenvy version:**    5.10.0

**OS and version:**    

**Docker version:** command not found

**Codenvy cli.log output:**  N/A

**Comment by eivantsov** [comment]
@marcelobern it does look like AWS networking issues. I cannot run apt-get update for example.

**Comment by startupgurukul** [comment]
it working now..(Y)
