### ISSUE TITLE
Rework stacks loading policy

### ISSUE THREAD

**Issue by eivantsov** [codenvy/codenvy#2208]
Currently, stacks displayed to all users are sourced from stacks.json. The problem with this file is that in Codenvy it lives in a container, and thus cannot be edited. It makes it impossible for an On-Prem admin to manage global stacks.

Proposed solution:

1. Have two stacks management policies

* **automated**, i.e. when Codenvy starts it **always** sources stacks from json which is in Codenvy tomcat binaries. This is a SaaS use case like codenvy.io. It is also ok for On Prems that have no custom stacks and rely on Codenvy updates to get new stacks.

* **admin controlled**, i.e. when stacks.json is sourced **only once** (when Codenvy first starts it populates database with stacks that Codenvy provides). Once a db is populated, stacks.json is ignored on subsequent restarts and stacks are managed through API only. It should be possible to restore defaults though, i.e. wipe global stacks from db and re-source them from the default stacks.json.

2. These policies can be switched in codenvy.env

@riuvshin @skabashnyuk @skryzhny @gazarenkov thoughts?

**Comment by eivantsov** [comment]
Alternatively, we may have stacks in slq scripts that are executed once, on first start, and then the admin manages stacks using API only.

**Comment by slemeur** [comment]
Nice.

In *admin controlled*, admin should also be able to re-source the list from an uploaded new stacks.json file.

**Comment by eivantsov** [comment]
So, we agreed on the following

1. automated and admin controlled mode. automated mode is default.
2. admin can reset stacks, i.e. reinitialize db from the default stacks.json
3. admin can reset stacks from a custom json

**Comment by skabashnyuk** [comment]
After discussing this task with leads and @gazarinkov we think that we need to not to extend functionality with stacks.json. Instead of that, we should go back to https://github.com/eclipse/che/issues/3629. Where all data about stack will be populated during database initialization phase. + we need a reach UI on Dashboard to help user customize existed stacks how they want.

**Comment by akorneta** [comment]
Stacks initialization script for `che` (without permissions) please take a look: 
[stacks.sql](https://gist.github.com/akorneta/04832f31f95313286e1321ca648d3bda)

**Comment by akorneta** [comment]
To summarize we decide to keep `stacks.json` but change the strategy of its loading. For now stacks will be loaded only once, and also they moved from `../tomcat/stacks/` to jar where `StackLoader` placed.

**Comment by gazarenkov** [comment]
OK, then make sure this json is not expected to be changed by user.
In fact it is part of the source code, so better to put it somewhere inside and make sure we do not have documentation about modifying it.

**Comment by TylerJewell** [comment]
+1 on the strategy.

However, this likely could have significant impacts to documentation and existing installations.  We will need to create a variety of QA scenarios to verify upgrades and also the documentation.  Today we spend a lot of time explaining how the stacks.json object is structured and supposed to work. This PR will make that obsolete, correct?

**Comment by eivantsov** [comment]
We can easily change the location here - https://github.com/codenvy/codenvy/blob/master/assembly/assembly-main/src/assembly/assembly.xml#L88-L92

As to existing installations, all the stacks are already in a db.

And json does not go anywhere, since you will be able to add a new stack in UD in a json format.

**Comment by TylerJewell** [comment]
I think there is another use case, however.

Imagine a scenario where a custom assembly is using stacks.json to force-load a custom set of stacks on every reboot. They use the stacks.json as a way to override (or ignore) what has been loaded into the database. In this weird scenario, couldn't it be possible that someone has an installation that depends upon stacks.json and purposely ignores the database? If they upgrade then, they could see weird behaviors,

**Comment by gazarenkov** [comment]
@TylerJewell it should not impact on existed intsllation unless user expect the changes from stacks.json to be applied on database
Since it is what they probably expected before we should make it clear that it is not the case anymore

Wait, the main ide was to avoid the "weird scanario" you talked about... No *force-load* stuffs.
this json is a part of our source code and is taken into account only when database is empty.
That's what we discussed

**Comment by eivantsov** [comment]
And this isn't possible in Codenvy, since stacks.json lives in a container and is not mounted into a host filesystem. I do not think someone exec'ed into a codenvy container and edited this file.

**Comment by TylerJewell** [comment]
Ok, cool Thanks for setting me straight. It's possible that we have been through a couple variations of the stacks.json concept, so maybe I was confusing the behavior again.

**Comment by eivantsov** [comment]
In any case, it'll be possible to add stacks from dashboard, so if any of those weird scenarios somehow take place, a user will know what to do.
