### ISSUE TITLE
OutOfMemory error message display when stopping without snapshot

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#2210]
When trying to stop a workspace without using snapshotting, I'm having an error message displayed in the dashboard, while the workspace is stopping.

See attached gif:
![out-of-memory-when-delete](https://cloud.githubusercontent.com/assets/1636769/26153468/b9ba8004-3b0b-11e7-8657-f19879c87710.gif)

**Reproduction Steps:**
1- Get two workspaces running and using all the RAM you have
2- Stop one of the workspace by using the right-click action in the sidebar "Stop without snapshot"

*Expected behaviour:* the workspace is stopped and no warning message displayed
*Current behaviour:* the workspace is stopped but a weird "OutOfMemory" error message is shwon on the dashboard.

**Codenvy version:**    5.10 / codenvy.io

**Comment by ashumilova** [comment]
may depend on https://github.com/eclipse/che/issues/5105

**Comment by vkuznyetsov** [comment]
can't reproduce on https://nightly.codenvy-stg.com It seems this issue is not actual.
