### ISSUE TITLE
An error occurred while creating a workspace using dockerfile import

### ISSUE THREAD

**Issue by SkorikSergey** [codenvy/codenvy#2217]
**Reproduction Steps:**

1. **Workspaces** -> **Add workspace** button -> **Runtime** tab
2. Select the **Stack Import** tab and click the **dockerfile** button
In the **Recipe URL** field type the next url: 
 https://gist.githubusercontent.com/idexmai/4fa66309e6923679c5e0/raw/d0a595d4eacd2637ed7e7910dabb76777285c75e/customDockerStack 
3. Save and start workspace

**Observed behavior:**
There is error while the workspace is starting
![selection_040](https://cloud.githubusercontent.com/assets/7760565/26210470/541c0a36-3bf8-11e7-9ee8-651f043cca81.png)

It happens  on acceptance servers.

Additional information:
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![out](https://cloud.githubusercontent.com/assets/7760565/26210554/a4b4719a-3bf8-11e7-8bd5-993205cfd4d6.gif)

**Comment by SkorikSergey** [comment]
This bug not reproduced.

**Comment by SkorikSergey** [comment]
It happens again on acceptance servers.

**Comment by mmorhun** [comment]
Fixed
