### ISSUE TITLE
Regression: Fallback to start from recipe if snapshot is unavailable doesn't work

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#2228]
As described in #2227 start from snapshots doesn't work after renaming host.
It is expected to start workspace from recipe if snapshot is unavailable.
But I'm getting errors like:
```
[DOCKER] Step 1/1 : FROM some-host.com:5000/machine_snapshot_z7mij6c43mghah5d:latest
[DOCKER] [ERROR] Get https://some-host.com:5000/v1/_ping: http: server gave HTTP response to HTTPS client
```

**Reproduction Steps:**
Same as in #2227 

**Codenvy version:**   5.10.0

**Comment by mmorhun** [comment]
Done
