### ISSUE TITLE
can not push when i changed the git password

### ISSUE THREAD

**Issue by wzdnzd** [codenvy/codenvy#2232]
I pull source code from a privete repository,then do some changes,and i change my git password ,now i can not push it because “No Authenticated”.Though i reinitialize the local repository i can't push it also.What should i do to reset the git password?Thank you.

**Reproduction Steps:**
1.pull source code from a private repository
2.coding,and change the git's password
3.push

**Codenvy version: 5.10

**Comment by eivantsov** [comment]
@wzdnzd are you using the terminal to git push?

**Comment by wzdnzd** [comment]
No,i push it by click the push button. I want know how reset the git password.Thx.

**Comment by eivantsov** [comment]
Codenvy does not use git passwords, ssh keys only. How did you import your private repo?

**Comment by wzdnzd** [comment]
https://userName:password@host.com/user/repo.git

**Comment by eivantsov** [comment]
I see. There's no way to edit a remote. However, at Git > Remote > Remotes you may add a new one with the updated pass, and use it when pushing changes

**Comment by wzdnzd** [comment]
Yeap,i tried it already,i reinitialize the local repository and add git url at Git > Remote > Remotes,but i cannot push it also.

**Comment by eivantsov** [comment]
What error do you get?

**Comment by wzdnzd** [comment]
xxx.git no authorized

**Comment by eivantsov** [comment]
Are you certain you use the right remote here?

**Comment by wzdnzd** [comment]
yeap,because the git url copyed from gitlab.

**Comment by eivantsov** [comment]
Can you push using git in the terminal?

**Comment by wzdnzd** [comment]
oh,sorry,it works well when i delete the original git url and add a new git url throughat Git > Remote > Remotes.Thank you.
