### ISSUE TITLE
Limit username length to 39 chars

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#2242]
Sometime we have very long usernames.
Taking in account that username is a part of an image built by docker we may want to limit length.

**Codenvy version:**    5.11.1-SaaS

**Comment by vkuznyetsov** [comment]
There are two use cases here:
1 - User created with oauth:
-- automatically cut username to 39 chars (replace the last 4 chars with a random ones if username exists)

2 - User created by API
-- If username contains more then 39 chars return the error message: "Username should contain less then 39 chars." or " Username is too long (maximum is 39 characters)"

BTW Github has a restriction for length of user's email. They set limit for email length up to 99 chars.

**Comment by vkuznyetsov** [comment]
We can solve this issue by removing the username  from image name.

**Comment by vinokurig** [comment]
Should be fixed by https://github.com/codenvy/codenvy/issues/2256
