### ISSUE TITLE
create a shared volume between machines in codenvy

### ISSUE THREAD

**Issue by achabahe2** [codenvy/codenvy#2245]
I WANT TO MAKE A SHARED FOLDER BETWEEN TWO MACHINES dev-machine and other-machine so i thought that using a volumes would solve the problem. when i use  this recipe
**Reproduction Steps:**
**1**
`services:\n db:\n  image: eclipse/mysql\n  environment:\n   MYSQL_ROOT_PASSWORD: password\n   MYSQL_DATABASE: petclinic\n   MYSQL_USER: petclinic\n   MYSQL_PASSWORD: password\n  mem_limit: 1073741824\n dev-machine:\n  image: eclipse/ubuntu_jdk8\n  mem_limit: 2147483648\n  depends_on:\n    - db\n  volumes_from:\n    - db`
 i get 500 internal server error
but when i use this recipe
**2**
`services:\n db:\n  image: eclipse/mysql\n  environment:\n   MYSQL_ROOT_PASSWORD: password\n   MYSQL_DATABASE: petclinic\n   MYSQL_USER: petclinic\n   MYSQL_PASSWORD: password\n  mem_limit: 1073741824\n  volumes:\n    - /someVolume\n dev-machine:\n  image: eclipse/ubuntu_jdk8\n  mem_limit: 2147483648\n  depends_on:\n    - db\n  volumes_from:\n    - db`
codenvy detects that i use volumes tag so it yells at me that volumes is not allowed.

**Codenvy version:**    
5.11.2    
**Codenvy cli.log output:**  
error of the recipe 1
Could not start workspace test-wksp-05q7. Reason: Start of environment 'default' failed. Error: Error response from docker API, status: 500, message: Unable to find a node that satisfies the following conditions [available container slots] [--volumes-from=workspacexxxxxxxxxxxxxxxx_machinexxxxxxxxxxxxxxxxx_achabahe_db] [image==eclipse-che/workspacexxxxxxxxxxxxxxxx_machinexxxxxxxxxxxxxxxxxxx_achabahe_dev-machine (soft=false)]

**Comment by eivantsov** [comment]
@achabahe2 are you using codenvy.io or own on-prem installation?

**Comment by achabahe2** [comment]
ok i will find a turn around solution and post it here

**Comment by achabahe2** [comment]
I am using codenvy . The company iam working for uses codenvy services

Le 1 juin 2017 9:32 AM, "Eugene Ivantsov" <notifications@github.com> a
écrit :

**Comment by eivantsov** [comment]
@achabahe2 art the moment, you cannot share volumes between containers. You may install Codenvy On-Prem though as a single node install and give it a try. It should work.

**Comment by TylerJewell** [comment]
This is going to be resolved as part of the Che 6 update and the support for Che on Kubernetes.
