### ISSUE TITLE
New  password for a user is not set properly

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#2250]
**Reproduction Steps:**
1. Login into account and wait loading of Dashboard.
2. Profile & Account -> Security -> Set new password with '&' symbol in the end from Dashboard.
3. Logout ->Login into account with form again: (enter login and password and click on Login button)
**Expected behavior:** the current user should login into account with new password
**Actual behavior:** the user is not authorized and cannot login into account with new password
**Additional info:** it happens because symbol '&' breaks the password on 2 string
**Codenvy version:** 5.12.0 SNAPSHOT
**OS and version:** Chrome browser, Ubuntu 14.0, nightly.codenvy-stg.com server

**Comment by skabashnyuk** [comment]
Just checked on ```https://nightly-onprem.codenvy-stg.com```  works as expected

**Comment by skabashnyuk** [comment]
```https://nightly.codenvy-stg.com/``` -  is working too.

**Comment by musienko-maxim** [comment]
So after clarifying some details we've found tha this error can be reproduced if we set new password with '&' symbol. I've just updated the steps to reproduce with taking into account this details
