### ISSUE TITLE
Stack management in user dashboard

### ISSUE THREAD

**Issue by ashumilova** [codenvy/codenvy#2252]
The system admin should be able to do following with the help of UI:
- [ ]  add stack(s) from json file - need to show "Import" button in the header of stack list
- [ ] export stacks - need "Export" button in the header of stack list, which exports selected stacks
- [ ] switch stack from personal to public and vice versa for existing stack and on creation

**Comment by slemeur** [comment]
In the flow to create a new stack. Let's add a new section.

Section Title: “System stack”
Section Description: “Register the stack at system level and allow others to use it.”
Form component: switcher

If it’s Che -> by default yes
If it’s Codenvy -> if user is admin - by default yes. Other users will not see the section

**Comment by TylerJewell** [comment]
@slemeur - I changed the description to make it clearer.

**Comment by eivantsov** [comment]
This issue was moved to eclipse/che#5674
