### ISSUE TITLE
Can't create or start a workspace after creating account using GitHub OAuth

### ISSUE THREAD

**Issue by praxiq** [codenvy/codenvy#2256]
I'm a new user. When I signed up, I used the "Log in with github" feature. I got an email from Codenvy saying my username is "github1234567891011121314151617181920212223242526272829303132333435363738394041424344454647484950515253545556575859606162636465666768697071727374757677787980818283848586878889909192". That's not a very useful username, but I can't find any place to change it.

Now, every time I try to create a workspace, I get an error message saying, `Error response from docker API, status: 500, message: Error response from daemon: repository name must not be more than 255 characters`. The username is only 181 characters, but I suspect that it's used as part of the repository name, and is making it too long.

The relevant code appears to be [here](https://github.com/codenvy/codenvy/blob/master/wsmaster/codenvy-hosted-sso-auth-bearer/src/main/java/com/codenvy/auth/sso/server/BearerTokenAuthenticationService.java).

I suspect that for some reason it tried to assign me the username "github", and when that was taken, it then for some other reason kept appending instead of replacing integers until it found an available name... in which case you should find find 91 other Codenvy users called "github", "github1", "github12", "github123", and so on... :)

Which begs the question, why was it trying to assign me the username "github" in the first place? The email address I use for my github login is "github@...", so perhaps it automatically uses the first part of the email address as the username? If so, than if I were, say, "bob@..." or any other common email prefix, I probably would have the same problem.

It seems like it's important to let users change their usernames, or at least to choose one at sign-up - even if the keep-appending-numbers bug is fixed, I don't see why users should get stuck with automatically appended numbers at all.

**Reproduction Steps:**
1. Create an account using Github oauth.
2. Click "Create Workspace" on the dashboard.
3. Create a new Workspace from any stack.
4. Click "Create."
5. Get error message.

**Codenvy version:**    5.11.2

**Comment by eivantsov** [comment]
@praxiq in your github settings, is your primary email `github1234567891011121314151617181920212223242526272829303132333435363738394041424344454647484950515253545556575859606162636465666768697071727374757677787980818283848586878889909192@example.com`? If so, yes, we take everything that precedes `@` and use it as username. Indeed, we do not limit it which is a bug.

You may delete this account and register with email, and then associate your github account with a newly created Codenvy account.

**Comment by skryzhny** [comment]
i think it reasonable to move UserID and environment name and forthcoming organization names to container's label. 
So image name would contain only WorkspaceID and MachineID and thus not cause problems with creating images, WDYT?

**Comment by eivantsov** [comment]
Closing the issue as it seems to have been resolved

**Comment by flxwu** [comment]
Hey,
I wanted to try out codenvy yesterday and it seems like there is still this issue, as I logged in using Github and thus got the following ID
```
mail1234567891011121314151617181920212223242526272829303132333435363738394041424344454647484950515253545556575859606162636465666768697071727374757677787980818283848586878889909192939495
```
(185 characters long)
which, of course, leads to the same docker error as mentioned:
```
[DOCKER] [ERROR] Error response from daemon: repository name must not be more than 255 characters
```

It would be super nice if this would be fixed soon :)

**Comment by skryzhny** [comment]
I see no fixes in near term.
Can You try workaround:
- Delete current account (Profile & Account -> Security tab)
- Create new account by registering via email, and choose shorter `User Name`
Note you still may login with github to this new account.
