### ISSUE TITLE
Error creating php5.6-default workspace

### ISSUE THREAD

**Issue by argfa** [codenvy/codenvy#2257]
Hello, I'm just registered on codenvy. Trying to create a workspace with php5.6, I get an error at the end of the creation.

**Reproduction Steps:**
1- Registration to codenvy with Google
2- Creation of new workspace with "stack library", "PHP-5.6"
3- Automatic progress of download and extraction
4- Error about "Could not start workspace wksp-xdjp. Reason: Start of environment 'wksp-xdjp' failed. Error: Restoring of workspace workspaceemxxtx5408kek0o7 filesystem terminated on node16.codenvy.io node. Synchronization process failed. Exit code 255"

**Codenvy version:**   5.11.2

**Comment by eivantsov** [comment]
@argfa I have updated php5.6 image. Give it a try again

**Comment by argfa** [comment]
Now it's ok. Thank you!
