### ISSUE TITLE
Login form ignores capital letters

### ISSUE THREAD

**Issue by eivantsov** [codenvy/codenvy#2264]
Steps to reproduce:

1. Create a user an email like `myAwesomeEmail@host.com`
2. Try to login with this email

When the page calls auth API, username is sent as `myawesomeemail@host.com` and as a result the user cannot log in.

**Comment by vkuznyetsov** [comment]
It needs to make an email address case insensitive on server side.

**Comment by vkuznyetsov** [comment]
It needs to downcase an email address on client side.

**Comment by vkuznyetsov** [comment]
Is not actual
