### ISSUE TITLE
Unable to Git Clone via ssh from app.deveo.com

### ISSUE THREAD

**Issue by ikha3551** [codenvy/codenvy#2268]
Hi @eivantsov,

I was just reading some of the other issues related to white-listing external IPs of git providers (like #1071). I am facing a similar issue with deveo.com which is a new service I am trying. Originally I thought it might have been an issue on their side but after reading the issues here I understand its a codenvy security thing. 

I would appreciate it if you can please add app.deveo.com to the whitelist. 

Thanks

**Comment by eivantsov** [comment]
@skryzhny can you whitelist it please?

**Comment by skryzhny** [comment]
Done.

**Comment by ikha3551** [comment]
Many thanks, working now!
