### ISSUE TITLE
rsync and gitignore

### ISSUE THREAD

**Issue by spillinova** [codenvy/codenvy#2272]
Need to confirm that rsync respects all syntax and flags of gitignore file. 

**Reproduction Steps: 
I keep loosing all node modules in project subfolders.  Rather than removing "node_modules" from every gitignore file in every subfolder, I am trying to use git unignore.
I added "!node_modules/" to root project gitignore file so that all subfolders with the name "node_modules" will be spared, but the snapshot is still deleting node_module folders in all subfolders.
**

**Codenvy version:**    5.12.0

**OS and version:**    Windows 10

**Docker version:** Can't find 

**Codenvy cli.log output:**

**Comment by eivantsov** [comment]
@spillinova yes, rsync respects gitignore.

Maybe it should be this way?

`!node_modules/*`

**Comment by garagatyi** [comment]
Unfortunately, rsync doesn't support ignore negation with the exclamation mark

**Comment by eivantsov** [comment]
@garagatyi what would be the right syntax to keep a particular module when rsyncing?

**Comment by garagatyi** [comment]
In this particular case, I suppose there is no pattern that can help. So the solution is to remove node_modules exclusion from all gitignore files.
But I can miss something from rsync syntax. In case you want to explore yourself we use rsync option `--filter=':- .gitignore' \`

**Comment by eivantsov** [comment]
Closing the issue. It will fix itself once all SaaS and enterprise features are moved to Eclipse Che.
