### ISSUE TITLE
teminal saying permission denied

### ISSUE THREAD

**Issue by Loading64** [codenvy/codenvy#2273]
**Reproduction Steps:**
the command im using is project/main.py

**Codenvy version:**    
5.12.0
**OS and version:**    
chromebook
**Docker version:**    
i dont know how to access this
**Codenvy cli.log output:**  
or this

**Comment by eivantsov** [comment]
@Loading64 please provide more information on the problem, along with steps to reproduce.

**Comment by TylerJewell** [comment]
closed due to inactivity
