### ISSUE TITLE
Installing emscripten in a new stack fails

### ISSUE THREAD

**Issue by wvdschel** [codenvy/codenvy#2279]
I'm trying to create a new stack for Rust & emscripten, but it fails to run with the following error:
```
[DOCKER] [91mTraceback (most recent call last):
  File "/root/emsdk-portable/emsdk", line 4, in 
    import sys, optparse, subprocess, os, os.path, errno, zipfile, string, json, platform, shutil, tarfile, tempfile, multiprocessing, re, stat, copy
  File "/usr/lib64/python2.7/tempfile.py", line 35, in 
[0m

[DOCKER] [91m    from random import Random as _Random
  File "/usr/lib64/python2.7/random.py", line 885, in 
[0m

[DOCKER] [91m    _inst = Random()
  File "/usr/lib64/python2.7/random.py", line 97, in __init__
    self.seed(x)
  File "/usr/lib64/python2.7/random.py", line 113, in seed
    a = long(_hexlify(_urandom(2500)), 16)
OSError: [Errno 38] Function not implemented
```

At first glance, it seems like access to `/dev/urandom` is blocked?

**Reproduction Steps:**
Create a new stack -> Import from Dockerfile, using the Dockerfile found at https://gist.github.com/wvdschel/abb9a419b09f200abb2fffc75d4df4fd

**Codenvy version:**  5.12.0

**OS and version:**    Occurred on Codenvy.io

**Docker version:** Unknown (Codenvy.io)

**Codenvy cli.log output:**  Not an on-prem install

**Comment by TylerJewell** [comment]
@eivantsov - can you take a look please

**Comment by eivantsov** [comment]
@wvdschel docker build fails locally as well. This is not a Codenvy issue. Closing the issue.
