### ISSUE TITLE
Codenvy runs "git clean" or similar recursively on the project

### ISSUE THREAD

**Issue by Vilsol** [codenvy/codenvy#2283]
Currently codenvy runs `git clean` recursively on the entire project, which means that any files created would be deleted before making a snapshot. This is really bad, because there can be files which were created before the ignore file, and they have to be inside the repository, but codenvy removes them.

It should be either disabled or be possible to be toggled in the workspace config.

**Reproduction Steps:**

Make a new project, create a git repo, create a new file and an ignore file and put the file in the ignore file, then restart the workspace and file will be gone.

**Codenvy version:** 5.13.0

**Comment by eivantsov** [comment]
Codenvy restores and backs up workspaces projects using rsync that respects .gitignore. This is the default behavior now that isn't configurable fro a user, unfortunately.

**Comment by Vilsol** [comment]
This is very unexpected behavior and should be definitely removed as it breaks many in-place systems that require the ignored files to function. Many repositories use ignore files to lock their state and prevent any global modifications to the file.

**Comment by TylerJewell** [comment]
Please follow the tracking issue on this - we will make this improvement soon.
