### ISSUE TITLE
User is able to see general team details without dedicated permissions

### ISSUE THREAD

**Issue by SkorikSergey** [codenvy/codenvy#2289]
**Reproduction Steps:**
Add to end of this url -"https://nightly.codenvy-stg.com/dashboard/#/team/" an existed user name(for example **user**).
Open this url "https://nightly.codenvy-stg.com/dashboard/#/team/user" in a browser.

**Expected behavior:**
There will be "The team could be deleted by its owner or you do not have permissions to access the team." message.

**Observed behavior:**
User is able to see general team details without dedicated permissions.

**Codenvy version:** 5.14.0
**Server location:** https://nightly.codenvy-stg.com.
**Additional information**:
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![config](https://user-images.githubusercontent.com/7760565/27593595-3641b614-5b60-11e7-8ce2-f006d7885039.gif)

![out-2](https://user-images.githubusercontent.com/7760565/27584866-7f4e82e2-5b42-11e7-8a2b-aa9d8d7a2647.gif)

**Comment by riuvshin** [comment]
@ashumilova can you please take a look.

**Comment by ashumilova** [comment]
@slemeur @bmicklea is it needed for 5.14.0?

**Comment by slemeur** [comment]
would be better - but can go in a bug fix release.
