### ISSUE TITLE
Custom commands don't save with the workspace

### ISSUE THREAD

**Issue by martinambrus** [codenvy/codenvy#2293]
Every time I leave a workspace, which I have configured for gradle build according to [this link](https://codenvy.com/docs/tutorials/gradle/index.html), the configuration disappears on the next workspace start. I though this would be saved, as a snapshot is being taken as I turn the workspace off but it always resets.

**Reproduction Steps:**
1. create gradle projects according to [this link](https://codenvy.com/docs/tutorials/gradle/index.html).
2. create custom command for build action
3. stop the workspace
4. start workspace again

**Codenvy version:**
5.13.0

**OS and version:**    
Ubuntu 16.04 64-bit, latest Chrome (Version 59.0.3071.115 (Official Build) (64-bit))

**Docker version:**
built-in (terminals does not know the docker command)

**Codenvy cli.log output:**
N/A

**Comment by TylerJewell** [comment]
@eivantsov - can you investigate. if this is true, this would be a P1 severity issue and we should elevate visibility.

**Comment by martinambrus** [comment]
Not sure if this was looked at or fixed in any way yet but I just tried on my Windows machine and the save worked. Will re-try with the Ubuntu machine again on Friday and let you know the result.

**Comment by TylerJewell** [comment]
Thanks for investigating @martinambrus

**Comment by eivantsov** [comment]
I failed to reproduce this one.

**Comment by martinambrus** [comment]
This seems to be now fixed in 5.14.0 even on the Ubuntu box, thank you for looking into this guys.
