### ISSUE TITLE
An user has a possibility to use more RAM than available 

### ISSUE THREAD

**Issue by SkorikSergey** [codenvy/codenvy#2295]
**Reproduction Steps:**

- By default any user has 3 Gb of available RAM
- Create **java-mysql** and **java** workspaces and don't start them
- In the **Workspaces** list click on the **Run workspace** button of the **java-mysql** workspace and quickly on the **Run workspace**  button of the **java** workspace.

 **Expected behavior:**
The **java** workspace is not started because there is not enough RAM

**Observed behavior:**
Both workspaces started and use 5 Gb RAM. 
The **java-mysql** stack has 2 machines(a **db** with 1 GB RAM and a **dev-machine** with 2 GB RAM). While the **db** machine(1 GB RAM) is starting there is a possibility to start next workspace. 

**Codenvy version:** 5.14.0, 5.15.0
**Server location:** https://codenvy.io

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![config-2](https://user-images.githubusercontent.com/7760565/27742366-0549c732-5dc1-11e7-913f-307535d09db3.gif)

**Comment by riuvshin** [comment]
this pretty critical for SaaS, @ashumilova is that UD issue?

**Comment by ashumilova** [comment]
@riuvshin no, both workspaces were running, so need to be solved on resource management side.

**Comment by slemeur** [comment]
@sleshchenko and @akorneta  : Could you give alook please?

**Comment by riuvshin** [comment]
@slemeur no worries @akorneta and @sleshchenko  will handle that ;)
