### ISSUE TITLE
Cannot determine why snapshotting is failing

### ISSUE THREAD

**Issue by jpapejr** [codenvy/codenvy#2296]
I've enabled workspace snapshotting in the codenvy.env file as directed and he tried both the internal registry and another private registry I have running colocated with Codenvy and snapshots fail to be created. No indication of why is given. Logs in my registry show that Codenvy never even contacted the registry server

```
2017-06-30 16:43:43,059[aceSharedPool-1]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 861]   - Creating snapshot of workspace 'workspaceumotyq3glbd6k1k1', machines to snapshot: '1'
2017-06-30 16:43:44,143[aceSharedPool-1]  [WARN ] [o.e.c.a.w.s.WorkspaceManager 817]    - Could not create a snapshot of the workspace 'admin/wksp-sapj' with workspace id 'workspaceumotyq3glbd6k1k1'. The workspace will be stopped
```

**Reproduction Steps:**
1. Start Codenvy locally
2. Edit codenvy.env file to enable workspace snapshotting to a private registry
3. Create and start a new workspace
4. Stop it while watching logs to see error

**Codenvy version:**    
5.14.0

**OS and version:**    
Ubuntu 16.04

**Docker version:** 
17.06.0-ce

**Codenvy cli.log output:**  
n/a

**Comment by jpapejr** [comment]
Just found this: 

```
Snapshot storing failed. org.eclipse.che.plugin.docker.client.exception.DockerException: Error response from docker API, status: 500, message: invalid reference format```

in **/codenvy/instance/logs/codenvy/che-machines-logs/machinemq1vfh65un2hasdn**

Not sure yet what that means..

**Comment by TylerJewell** [comment]
That log file is interesting - it should be a clue for one of the engineers. Though what is odd is that the message is happening from within your workspace container as it attempts to talk to the Docker daemon. I would expect that the workspace master would have the issue, not the container itself as it is the workspace master that instructs Docker to snapshot the containers.

**Comment by jpapejr** [comment]
I was able to resolve this.. It seems that the config file for a machine with docker installed via `docker-machine` using a generic driver puts the real config for the dockerd service at `/etc/systemd/system/docker.service.d/10-machine.conf` instead of `/lib/systemd/system/docker.service` which was where I put the `--insecure-registry x.x.x.x:5000` for the Codenvy-provided internal registry. Once I corrected this and attempted to stop a workspace, it snapshot like expected.. 

Sorry 'bout that.. Keep up the good work with this project and Che - looking forward to v6
