### ISSUE TITLE
"CSRF nonce validation failed" during SSH key upload

### ISSUE THREAD

**Issue by Sakul6499** [codenvy/codenvy#2299]
I created a new Workspace (C++-Workspace template, 2GB RAM, Default starter project) and then tried to upload my public SSH key through the interface.
The upload fails and a 'broken' error messages appear in the top right corner, as well as in the Events menu.

I also tried uploading from different locations:
C:/Users/Sakul/.ssh/id_rsa.pub
C:/Users/Sakul/Desktop/id_rsa.pub
A:/id_rsa.pub

The file has the default ssh key file permissions and is fully accessible.

The Message is: [it got displayed like this, **with all HTML-Tags visible** ]
<h1>HTTP Status 403 - CSRF nonce validation failed</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u>CSRF nonce validation failed</u></p><p><b>description</b> <u>Access to the specified resource has been forbidden.</u></p><hr class="line"><h3>Apache Tomcat/8.5.11</h3>

**Reproduction Steps:**
1. Create a new Workspace using the C++ Template and leave all options to default (2GB RAM, first starter project)
2. Go to "Profile -> Preferences -> SSH -> Machine" and click "Upload Key"
3. Choose ssh key and try uploading

**Codenvy version:**    
5.14.0

**OS and version:**     
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0 

**Docker version:**
Tipped within Codenvy:
$ docker version
bash: docker: command not found

The currently used Docker version on Codenvy I guess.

Thanks in advance

**Comment by eivantsov** [comment]
@Sakul6499 I failed to reproduce it on my side. Are you talking about codenvy.io?

**Comment by Sakul6499** [comment]
I am really sorry for that.
Just tried it again and everything works.
Not quite sure what did change.

My apologies.
