### ISSUE TITLE
Change Source License to EPL

### ISSUE THREAD

**Issue by riuvshin** [codenvy/codenvy#2300]
As we are going to opensource codenvy sources and move some code to eclipse CHE we have to apply EPL on codenvy sources.

**target repos:**
- github.com/codenvy/docs
- github.com/codenvy/codenvy

**repos to check if that action should be applied:**
- github.com/codenvy/saas - codenvy.io
- github.com/codenvy/customer-tiaa  - customer 

**Other codenvy repos where we already have EPL lincese:**
- github.com/codenvy/plugin-openshift
- github.com/codenvy/redhat
- github.com/codenvy/silexica
- github.com/codenvy/everrest

**Comment by TylerJewell** [comment]
@riuvshin - before you do this task, please touch base with me.  I want to verify something with upper management at RHT first on legal side.

**Comment by riuvshin** [comment]
@TylerJewell Sure, FYI we are not in a rush to do this task, I;ve just summarized scope and what we have now.

**Comment by gazarenkov** [comment]
@TylerJewell I have this request from my upper management so, I am sharing this info in e-mail to discuss if needed (you included).

**Comment by riuvshin** [comment]
fixed by: https://github.com/codenvy/codenvy/issues/2323
