### ISSUE TITLE
There is an error while starting a workspace after snapshotting

### ISSUE THREAD

**Issue by SkorikSergey** [codenvy/codenvy#2301]
**Reproduction Steps:**
Create and start a workspace
Stop this workspace with snapshot and start again

**Observed behavior:**
There is en error while the workspace is starting. After refreshing this page the workspace works correctly.

**Codenvy version:** 5.15.0
**Server location:** https://nightly.codenvy-stg.com, https://nightly-onprem.codenvy-stg.com.
**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![screenshot from 2017-07-06 09-59-41](https://user-images.githubusercontent.com/7760565/27899299-4fe06556-6232-11e7-8920-c1b78c78b622.png)

![config-4](https://user-images.githubusercontent.com/7760565/27899324-6bb03c52-6232-11e7-9b87-f2201d5f9800.gif)

**Comment by riuvshin** [comment]
agree this is blocker becuase on prod we have autosnapshots enabled so all users will experience this.

**Comment by eivantsov** [comment]
The problem is that the client connects to ws agent without machine token. Refreshing page fixes it, but of course this is not even a workaround.

**Comment by SkorikSergey** [comment]
This bug is not reproduced.
