### ISSUE TITLE
<alt>+<.> does not work at the bash prompt in Che.

### ISSUE THREAD

**Issue by aspurrier** [codenvy/codenvy#2303]
I am a big fan of using <alt>+<.> at the Bash command line all the time.  In Che at the Workspace terminal window Bash shell, <alt>+<.>  does nothing.

**Reproduction Steps:**
In Che at the Workspace terminal window Bash shell:
1. Hold down the <alt> key.
2. Tap the <.> key.  Multiple times to work your way back through the command history.
3. Observe that the last parameter of history of commands is not shown.

**Codenvy version:**    
Version 5.14.0  - hosted online at codenvy.io

**OS and version:**    
hosted online at codenvy.io

**Docker version:** 
   
If find these instructions unclear as I am running hosted and the terminal window in reports "command not found" for the command "docker".

**Codenvy cli.log output:**  
hosted online at codenvy.io

**Comment by eivantsov** [comment]
@aspurrier well, up and down arrows still work. As to `ALT+.` it indeed does not do what it does in a Unix terminal.

**Comment by aspurrier** [comment]
<Esc>+<.> does the same thing.  I am all good, back in the game!   
Maybe it is the web browser sucking up the <Alt> key?  Other <Alt> key bindings are affected too.
