### ISSUE TITLE
Unable to accept the Fair Source License at login

### ISSUE THREAD

**Issue by gdgeorge** [codenvy/codenvy#2304]
At first login, clicking on the accept button yields "Something went wrong. Please try again or contact support." 

**Reproduction Steps:**

**Codenvy version:** 
5.14

**OS and version:**    
Virtualbox: Ubuntu 16.04 host with Ubuntu 16.04 guest.
**Docker version:**    
17.06.0ce
**Codenvy cli.log output:**

**Comment by eivantsov** [comment]
@gdgeorge can you provide server logs?

`docker logs -f codenvy_codenvy_1`

Have you logged as `admin/password`?

**Comment by gdgeorge** [comment]
Actually I'm going to go ahead and close this. I think it's an issue with VirtualBox on my Dell Poweredge 2900 server.  And / or a reverse proxy issue.  

OT question: is it possible to switch ports 80 / 443 using the Docker command line?  I'd much rather be running it on my hardware-space server than virtualbox.  The latter has been an issue with this machine in the past and the old fixes are not working any more.

Thanks,
Jerry

**Comment by eivantsov** [comment]
@gdgeorge Codenvy On-Prem officially support 80/443 ports. Any custom Haproxy configs may lead to unpredictable results.
