### ISSUE TITLE
C#/.NET stack - editor not tokenizing the @"<string>" correctly.

### ISSUE THREAD

**Issue by keratos68** [codenvy/codenvy#2305]
```
using System.IO;
using System.Text;
using System;

using Microsoft.AspNetCore.Hosting;

namespace HelloWeb
{
    public class Program
    {

        public static void Main(string[] args)
        {
            String x = @"123" ;
       
            Console.WriteLine("x=]"+ x +"]");
        }
    }
}
```

Unable to specify verbatim string literals to the editor/compiler using C# and .NET. 

The above verbatim literal text @"123" is not tokenized correctly in the editor/compiler. Notice how the text following the line terminator (;) is seen as part of the string literal. Try it for yourself. All of the text following the @" is seen as the string itself !!

**Reproduction Steps:**
On laptop, PC and phone. Same behaviour on all.

**Codenvy version:** 
5.14.0
Using the standard ".NET" stack unmodified.

**OS and version:**    
Windows 10

**Docker version:** 
command "docker" is not recognised at the terminal.

**Codenvy cli.log output:** 
/data not mounted

**Comment by eivantsov** [comment]
@keratos68 even though Orion editor highlights `@"string"` like it does, verbatim string literal is not affected.

`String x = @"hello \t world" ;` produces `hello world`
and
`String x = "hello \t world" ;` produces `hello \t world]`

**Comment by eivantsov** [comment]
Closing the issue, as Orion highlights tokenized strings excatly same way at orionhub.org. 

Hopefully, this bug is fixed in future Orion releases.
