### ISSUE TITLE
Whitelist linux bastion on AWS

### ISSUE THREAD

**Issue by wired2code** [codenvy/codenvy#2306]
Am trying to use Codenvy as a hosted development environment. One of the programs that I'm testing on Codenvy needs to connect to an informix server that resides in an AWS vpn. And the test cases access this informix server by tunnelling through a linux bastion. From the replies to this [issue](https://github.com/codenvy/codenvy/issues/1287), my understanding is that this linux bastion needs to be whitelisted. Is this possible on a hosted environment ? Or do I need to use an on prem install of codenvy ?

**Comment by eivantsov** [comment]
Please, provide us with the IP to be whitelisted.

**Comment by wired2code** [comment]
codenvy.appseb.com is the linux bastion.

**Comment by skryzhny** [comment]
Done.

**Comment by wired2code** [comment]
This - tunnelling through - seems to have stopped working.

**Comment by eivantsov** [comment]
@wired2code is the sever IP the same?

**Comment by wired2code** [comment]
Haven't restarted the linux bastion. So the machine [would have the same ip address](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-instance-addressing.html#concepts-public-addresses).

**Comment by eivantsov** [comment]
@skryzhny can you check if the server IP is still whitelisted?

**Comment by skryzhny** [comment]
It still present in our whithelist.
@wired2code can you recheck?

**Comment by wired2code** [comment]
No - am not able to connect through the command line or programmatically. And am able to do so from other aws accounts and azure. Tried both codenvy.appseb.com as well as 54.191.110.207.

**Comment by skryzhny** [comment]
Found out some of new nodes wasn't picked update of whitelist.
It should work OK now.
