### ISSUE TITLE
nodejs/webpack preview not available

### ISSUE THREAD

**Issue by thorstenKoch** [codenvy/codenvy#2309]
Some times ago, this did work. but now the preview is not available: http://node29.codenvy.io:38461/
i configured webpack-dev-server with these url, but the preview isnt available. run command startup is

```
Running in ahead of time compilation mode
Project is running at http://0.0.0.0:38461/
webpack output is served from http://node29.codenvy.io:38461
Content not from webpack is served from ./src/public
404s will fallback to /index.html
```

**Reproduction Steps:**

start my "BKW" image and then starting run command "npm run server"

**Codenvy version:**    docker command not found

**OS and version:**    eclipse/node

**Docker version:** "docker version" command not found

**Codenvy cli.log output:**

**Comment by eivantsov** [comment]
@thorstenKoch each time preview URL changes. Each time you run a workspace. So, when running a server , let it run on a default port, and just configure preview URL that will be translated into an actual URL.

https://www.eclipse.org/che/docs/ide/previews/index.html

**Comment by thorstenKoch** [comment]
Thank you @eivantsov for your answer. But still didn't got things right. 

Review of my settings:
config.output.public_path = something like http://node24.codenvy.io:4200 (this is the every time changing preview url)
config.host = 0.0.0.0
config.devServer.port = 4200 (standard)

This outputs

`Running in ahead of time compilation mode
Project is running at https://0.0.0.0:4200/
webpack output is served from http://node23.codenvy.io:
Content not from webpack is served from ./src/public

404s will fallback to /index.html
`

Still got connection refused error. Do i miss another configuration issue? Somewhere in the dashboard?

Sorry for stupid questions, i am blocked and i didn't understand the docs you've send me to solve my problem.

**Comment by eivantsov** [comment]
@thorstenKoch I don't think you need this one - config.output.public_path

Just unbind from localhost, and use the macro.

The app can start on any from 29 nodes, you should make no assumptions around it in your config.

**Comment by thorstenKoch** [comment]
No i managed to get webpack dev-server running:

config.output.public_path = "/"
config.devServer.host = 0.0.0.0
config.devServer.port = 3000 (ssl standard)
config.devServer.https = true

running this command:

command-line: npm run server
preview-url: https://${server.port.3000}

Hope anyone else will help that too.
