### ISSUE TITLE
404 Response from Android Emulator

### ISSUE THREAD

**Issue by mhammonde** [codenvy/codenvy#2310]
I am having an issue with the Android emulator not launching after I hit 'run' in the IDE.

I have created a new workspace using the 'mobile-android-simple' sample and have not touched the code or configuration at all. I hit the 'run' command and get a large amount of output on the console including the pinned noVNC URL at the top. When I follow that URL I get the following message:

```
Error response
Error code 404.
Message: File not found.
Error code explanation: 404 = Nothing matches the given URI.
```

Is there something in my workspace configuration that I need to change to make the emulator work? Or is there a known issue?

**Reproduction Steps:**
1. Create new workspace using the Android 'ready-to-go' stack option
2. Ensure the 'mobile-android-simple' sample app is selected
3. Launch the workspace
4. Run the 'mobile-android-simple: run' command by clicking the blue 'play' icon on the toolbar
5. Click on the provided Codenvy node URL

**Codenvy version:** 5.14.0
**OS and version:** Windows 7 Enterprise (Service Pack 1)
**Browser and version:** Google Chrome 59.0.3071.115 (Official Build) (64-bit)
**Docker version:** N/A (local to the Che on Codenvy)
**Codenvy cli.log output:**  N/A

**Comment by eivantsov** [comment]
Indeed, the landing page has changed. I will update the image, but for now, you may manually replace `auto_vnc.html` with `vnc.html`

**Comment by eivantsov** [comment]
Image fixed

**Comment by mhammonde** [comment]
Many thanks Eugene. I can confirm I get the noVNC page now.
