### ISSUE TITLE
Jupyter Notebook on codenvy with browser access - how to??

### ISSUE THREAD

**Issue by ngehrlein** [codenvy/codenvy#2315]
Hi all

I'd really like to switch using codenvy for my big data projects... however I would need to be able to run jupyter notebook & access it via browser.. any expert around who could provide a short how-to?

I'm currently using c9 where it works fine, but I'd prefer codenvy..

Cheers.

**Comment by eivantsov** [comment]
@ngehrlein Have you tried creating a custom stack with jupyter in it? Or start a python workspace and install all dependencies in the runtime?

**Comment by TylerJewell** [comment]
It looks like there are standard jupyter Docker images available for you to make a custom stack from.  https://hub.docker.com/r/jupyter/

**Comment by eivantsov** [comment]
Closed due to inactivity
