### ISSUE TITLE
Are there Apache2 Reverse Proxy Dox?  Is there a sample file?

### ISSUE THREAD

**Issue by gdgeorge** [codenvy/codenvy#2318]
All
Are there dox available for running Codenvy behind and Apache2 Reverse Proxy?  Is there a sample virtual host file?

Thanks!

**Comment by TylerJewell** [comment]
The Codenvy installation for on-prem embeds its own reverse proxy. This proxy is not something that you can replace with another proxy.

**Comment by gdgeorge** [comment]
Thanks for getting back to me Tyler.  Have you suggestions for running on-prem on a single IP that's shared with other servers?  The gimme is, of course, to set up another IP, but it seems to me that I'm missing something very elementary.  

Best,
Jerry George

**Comment by TylerJewell** [comment]
Codenvy only needs one ip.  It is launched as a set of containers that require access to certain ports.  As long as you have the ram and the ports available, including 80 and 443 then you will be ok.

Why would you run codenvy with so many other services on the same machine?

**Comment by gdgeorge** [comment]
Because it's what I've got... Thanks man.

Best,
JG
