### ISSUE TITLE
[Regression] Actions that open new tab in browser don't work 

### ISSUE THREAD

**Issue by SkorikSergey** [codenvy/codenvy#2319]
**Reproduction Steps:**

- Create and start a workspace
- Menu 'Help' -> 'Docs' and Menu 'Profile' -> 'Account'**

**Expected behavior:**
New browser tab must be opened.

**Observed behavior:**
Nothing happens. Similar issue on CHE: https://github.com/eclipse/che/issues/5578.

**Codenvy version:** 5.15.0
**Server location:** https://nightly.codenvy-stg.com, https://nightly-onprem.codenvy-stg.com

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![config-13](https://user-images.githubusercontent.com/7760565/28212062-6735eace-68a8-11e7-8703-91b581c3e275.gif)

**Comment by riuvshin** [comment]
@vparfonov please take a look
