### ISSUE TITLE
There is an error message after renaming a java class

### ISSUE THREAD

**Issue by SkorikSergey** [codenvy/codenvy#2320]
**Reproduction Steps:**

- Open a java class in the **Editor** and rename it by Menu "**Assistant**" -> "**Refactoring**" -> "**Rename**"

**Observed behavior:**

- There is an error message in the **Events**("Failed to update content of file(s)) and in the **dev-machine** console.

**Codenvy version:** 5.15.0
**Server location:** https://nightly.codenvy-stg.com, https://nightly-onprem.codenvy-stg.com

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![config-17](https://user-images.githubusercontent.com/7760565/28212285-649fcc52-68a9-11e7-84b4-a039cd84ed63.gif)

**Comment by eivantsov** [comment]
@SkorikSergey is it a Codenvy only problem? Can it be reproduced with Che?

**Comment by SkorikSergey** [comment]
Moved in CHE: https://github.com/eclipse/che/issues/5645.
