### ISSUE TITLE
There is not a number of created factories after refreshing a page

### ISSUE THREAD

**Issue by SkorikSergey** [codenvy/codenvy#2321]
**Reproduction Steps:**

- Create one or more factories
- Click on the **Workspaces** link and refresh a page

**Observed behavior:**
There is not a number of created factories in the end of the Factories link. The number appears if click on the Factories or the Dashboard links.
This issue reproduced only in Codenvy.

**Codenvy version:** 5.15.0
**Server location:** https://nightly.codenvy-stg.com, https://nightly-onprem.codenvy-stg.com

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![config-25](https://user-images.githubusercontent.com/7760565/28267393-93e3b1bc-6b02-11e7-8ef5-980b97c5bdf3.gif)

**Comment by eivantsov** [comment]
@SkorikSergey is this Codenvy only issue? Can you reproduce it in Che? If it can be reproduced in Che, please create an issue there.

**Comment by SkorikSergey** [comment]
This issue reproduced only in Codenvy.

**Comment by SkorikSergey** [comment]
This issue reproduced only in Codenvy.

**Comment by SkorikSergey** [comment]
Not relevant anymore. Closing.
