### ISSUE TITLE
Error of creation of workspace in case of license has reached its user limit

### ISSUE THREAD

**Issue by dmytro-ndp** [codenvy/codenvy#2329]
**Reproduction Steps:**
1. Open _Codenvy_ as admin and add codenvy license with more then 3 users allowed.
1. Add 3 users to _Codenvy_ to have 4 ones (including _admin_).
1. Remove Codenvy license.
1. Go to "**Workspaces**" section and click on "**Add Workspace**" button, and then click on "**Create**" button.

**Expected result:**
workspace creates correctly, and dashboard displays error message:
>  Workspace has created successfully, but Codenvy license has reached its user limit - you can access the user dashboard but not the IDE.

**Actual wrong result:**
click on "**Create**" doesn't affect; 
at the same time workspace is present of "Workspaces" tab in stopped status.

![screenshot from 2017-07-19 14 50 04](https://user-images.githubusercontent.com/1197777/28366003-8077acc2-6c93-11e7-95d1-076df9445620.png)

![out](https://user-images.githubusercontent.com/1197777/28366185-47028786-6c94-11e7-9381-526b1e51f2ba.gif)

**Codenvy version:**
5.15.0-SNAPSHOT

**OS and version:**    
Ubuntu 14.04 LTS

**Comment by dmytro-ndp** [comment]
@bmicklea: could you, please, check error message at the workspace creation time?
>  Workspace has created successfully, but Codenvy license has reached its user limit - you can access the user dashboard but not the IDE.

**Comment by bmicklea** [comment]
Error should be:
> Workspace created but cannot be run as the license seats have been exceeded.

However, let's put this on hold for now. We're discussing changes to the Codenvy business that might affect this.

**Comment by dmytro-ndp** [comment]
Won't fix because of system license has been removed from Codenvy entirely (an issue #2350).
