### ISSUE TITLE
Is there a config to change projects root directory?

### ISSUE THREAD

**Issue by Alspaladin** [codenvy/codenvy#2331]
I want to use some environment variable or parameter in `codenvy.env` file which will set a root directory for projects to something different from `/projects`

Was thinking that I can use one of these:

`CHE_PROPERTY_che_machine_projects_internal_storage`
`CHE_PROPERTY_che_user_projects_storage`
`CHE_PROPERTY_che_workspace_projects_storage`

but setting any of them in `docker run` command, adding to `codenvy.env` or adding to environment variables in custom stack config does not work, when I create new project, it then always go to `/projects` folder

Should it work or this kind of configuration is not possible and I need to add line to my recipe, creating symlink with my custom projects folder and `/projects`?

**Reproduction Steps:**
set all these parameters in `docker run ... codenvy/cli start` with `-e` option, pointing to any directory
create new workspace from any stack
create blank project from IDE interface
run in terminal `ls /projects`, project will be there

**Codenvy version:**    
5.14.0

**OS and version:** 
macOS Sierra, Version 10.12.5

**Docker version:**
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by eivantsov** [comment]
@Alspaladin In Codenvy this directory isn't configurable by design. You may create a symlink if that helps.

**Comment by Alspaladin** [comment]
Thanks for response!
