### ISSUE TITLE
Creating a file/folder with '%' in the name returns 400 Bad Request

### ISSUE THREAD

**Issue by balzer814** [codenvy/codenvy#2337]
When adding a file/folder with '%' in the name codenvy returns 400 Bad Request.
It is possible to create a folder with such a name using the terminal, but this folder can later not be opened in the ide.
When creating such a file over the terminal and than open it in the IDE the opened Editor only says 'An error occoured while loading the file.'

**Reproduction Steps:**

1. open new...-> folder dialog
2. type in '%name' as directory name
3. click ok
4. codenvy shows an error message:
![image](https://user-images.githubusercontent.com/23092994/28578382-e436d2d6-7159-11e7-860b-fa1e27455394.png)

**Codenvy version:**    
5.15.0

**Comment by eivantsov** [comment]
This issue was moved to eclipse/che#5810
