### ISSUE TITLE
Using codenvy with two bitbucket accounts

### ISSUE THREAD

**Issue by wired2code** [codenvy/codenvy#2341]
Have created a codenvy account with two workspaces. One for writing code for my employers and the other for my personal use. Have two bitbucket repositories for this setup. On my computer followed [these instructions](https://stackoverflow.com/a/21712226) to work with two bitbucket accounts. On codenvy it appears as if I need to change my profile (the committer and vcs pulldowns) when I switch workspaces. Am I missing something ?

**Comment by eivantsov** [comment]
@wired2code yes, git committer name is saved in user prefs for all git operations. Probably changing it every time you switch workspaces isn't the best option.

You may also use terminal git only by the way and snapshot workspaces. This way, git config will be saved across workspace restarts.

**Comment by eivantsov** [comment]
Closing the issue due to inactivity. Feel free to reopen if you have further questions.
