### ISSUE TITLE
Browser tab hangs while running Angular 2 app

### ISSUE THREAD

**Issue by sandeshwar** [codenvy/codenvy#2342]
The browser tab hangs for around 10-20 minutes when I run the Angular 2 app. Below is the command I have created to run the app:
 cd ${current.project.path}/card-editor \n
ng serve --host 0.0.0.0 --disable-host-check true

**Reproduction Steps:** Run an Angular 2 project

**Codenvy version:**    

**OS and version:**    

**Docker version:**    

**Codenvy cli.log output:**

**Comment by eivantsov** [comment]
@sandeshwar any particular project?

**Comment by sandeshwar** [comment]
Yes I tried creating a new app using ng new and still it got stuck after I ran the command

**Comment by eivantsov** [comment]
@sandeshwar got stuck how? What do you mean hangs? Tab crashes?

**Comment by sandeshwar** [comment]
@eivantsov Yes, it says that the tab is not responsive. If I click on 'wait' again and again for a few times (around 3-5 times) it becomes responsive.

**Comment by eivantsov** [comment]
@sandeshwar I cannot reproduce it.

**Comment by sandeshwar** [comment]
Here's a screenshot taken from firefox, this time there's an error in the terminal, and webpack compilation has failed. And the window is not responding.

![codenvy error](https://user-images.githubusercontent.com/10569159/29308275-d99f1c92-81c2-11e7-9bd0-bc24230ad91b.png)

**Comment by eivantsov** [comment]
@sandeshwar provide me with step by step instructions please on how to reproduce.

**Comment by dinvlad** [comment]
Seems to be an issue for any sufficiently large project. I have only 30 tests but running `ng test` already hangs the entire Codenvy UI indefinitely.

**Comment by eivantsov** [comment]
@sandeshwar can you provide with step by step instructions, including how you generate the project? Thanks

**Comment by sandeshwar** [comment]
Sorry, I have stopped using Codenvy, hence closing this issue now.
