### ISSUE TITLE
node_modules folder gets deleted every time the workspace is stopped

### ISSUE THREAD

**Issue by sandeshwar** [codenvy/codenvy#2343]
I have an angular 2 project, and every I stop the workspace the node_modules folder gets deleted and I have to do an 'npm install' every time I start the project/workspace

**Reproduction Steps:**

**Codenvy version:**    

**OS and version:**    

**Docker version:**    

**Codenvy cli.log output:**

**Comment by eivantsov** [comment]
`node_modules` is in `.gitignore` and Codenvy uses rsync to backup and restore workspace projects. As a workaround you may save node_modules outside `/projects` directory and always snapshot a workspace (creating a symlink will help too)

**Comment by AlexHGaming** [comment]
I have this issue too. And it is really annoying.

**Comment by eivantsov** [comment]
Closing the issue as it's how it is currently implemented. Once all SaaS features are moved to Eclipse Che, this issue's gone
