### ISSUE TITLE
Change defalt email

### ISSUE THREAD

**Issue by billyprice1** [codenvy/codenvy#2344]
How do i change this 
![image](https://user-images.githubusercontent.com/15332565/28886140-4946d0ac-77b0-11e7-8ba4-90c7bb1dc494.png) to my email

**Comment by eivantsov** [comment]
@billyprice1 in your `codenvy.env` uncomment and edit the following envs, and then restart Codenvy:

```
#CODENVY_ADMIN_NAME=admin
#CODENVY_ADMIN_INITIAL_PASSWORD=password
#CODENVY_ADMIN_EMAIL=admin@codenvy.com

```

**Comment by eivantsov** [comment]
Closed due to inactivity.
