### ISSUE TITLE
How to get preview URL?

### ISSUE THREAD

**Issue by AlexHGaming** [codenvy/codenvy#2348]
Hi everyone.
I just joined Codenvy, but I have 1 question I can't figure out myself.
I want my URL to the project. So I can put this URL, followed by the port after. But how to get the URL?
I may sound stupid, but I just joined codenvy for SSH terminal use! Thanks :-)

**Comment by eivantsov** [comment]
@AlexHGaming https://www.eclipse.org/che/docs/ide/previews/index.html

**Comment by eivantsov** [comment]
Closed due to inactivity.

**Comment by rebek** [comment]
Hi , if you see this post now look this tips :

For to see the Adress URL first RUN your workspace , after go to CONFIGURE WORKSPACE,  so select the tab SERVERS  - look for your adress in runtime ( in my case node-3000) 

look this video [https://drive.google.com/file/d/1GtoTMpY-PiRRiEQQu3yGHBQO4E8rugFK/view?usp=sharing](url)
Have Fun  !
