### ISSUE TITLE
"Unable to load preferences" error when trying to access/view a workspace through a web browser

### ISSUE THREAD

**Issue by mustafa-yilmaz** [codenvy/codenvy#2349]
Hi to all Codenvy team and fans,

Being a programming newbie, I have been seeking for some potential ways to use Codenvy's web-browser based IDE on my smartphone as well. While Codenvy is indeed accessible already through mobile browsers, they are actually far away from providing a workable view of Codenvy, except for the internal web browsers of two Android (user interface, launcher) apps named [Sentio](https://play.google.com/store/apps/details?id=com.andromium.os&hl=en) and [Leena](https://play.google.com/store/apps/details?id=de.m_lang.leena&hl=en). Those two browsers are the ones giving the closest results to the desktop browsers. While Sentio's one works with Codenvy IDE without any error, I am getting the error below when trying to access my workspace through Leena's internal browser. 

Since Sentio's browser has not a "zoom in/out" feature and (therefore) it is currently not allowing users to work with screens as small as those of phones, I am searching for a way to solve the problem that I face on Leena. The problem probably arises from Leena's side, since it is the only browser that I face with the issue but nevertheless, I would be so pleased to get Codenvy's support in order to clarify what the problem itself is at least.

Thanks very much in advance.                  

**Error Message:**
`Page at http://codenvy.io says:`
`Error : Unable to load preferences` 
`at Object.window.IDE.eventHandlers.initializationFailed (https://codenvy.io/mustafayilmaz/internodz/internodz?uid=408136:40:27)`
`at emg (_app-0.js:7828:140)`
`at umg (_app-0.js:7838:254)`
`at Obj (_app-0.js:14300:204)`
`at Pbj.Obj [as Hm] (_app-0.js:14302:64)`
`at v0e (_app-0.js:5252:367)`
`at eval (_app-0.js:5242:116)`
`at <anonymous>`

A screenshot of the error message is also available at http://www.twitter.com/mustafa_yilmaz/status/892370689633726464

**Reproduction Steps:**
1-)Enter "https://codenvy.io/mustafayilmaz/internodz/internodz?uid=408136:40:27" into the address bar of the internal browser of Leeana Android App.
2-) Request the page

**Codenvy version:**     5.15.0
**OS and version:**    Linux
**Docker version:**    N/A
**Codenvy cli.log output:**   N/A

**Additional info for Leena's internal web Browser:** (Taken from http://www.esolutions.se/whatsmyinfo)

**User-Agent:** Mozilla/5.0 (Linux; 7.0; SM-N920C Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like 
Gecko) Version/4.0 Chrome/59.0.3071.125 Safari/537.36
**Browser:** Chrome 59.0.3071.125
**Engine:** WebKit 537.36
**JavaScript Version:** 1.7
**EcmaScript Version:** 3.0
**Is Mobile Device:** No
**OS:** Linux 
**Supports Frames:** Yes
**Supports Tables:** Yes
**Supports Cookies:** Yes
**Supports JavaScript:** Yes
**Supports Java Applets:** Yes
**Supports ActiveX Controls:** No

![leena](https://user-images.githubusercontent.com/878471/28946327-f09d3b04-78b2-11e7-9aed-aae89c28c448.png)

**Comment by eivantsov** [comment]
@mustafa-yilmaz Codenvy supports Chrome, Firefox and Safari only.

**Comment by eivantsov** [comment]
Closed due to inactivity.
