### ISSUE TITLE
Remove the fair source license check in the CLI during installation

### ISSUE THREAD

**Issue by riuvshin** [codenvy/codenvy#2351]
needed for https://github.com/codenvy/codenvy/issues/2350

**Comment by riuvshin** [comment]
@TylerJewell I did quick investigation on this and here is my thoughts on what should we do.
I don;t think we have to remove license check functionality from CLI.
In CHE we have this:
[DEFAULT_CHE_LICENSE=false](https://github.com/eclipse/che/blob/master/dockerfiles/base/scripts/base/startup_01_init.sh#L154) which means that no license accept will be shown to user.
[DEFAULT_CHE_LICENSE_URL="https://www.eclipse.org/legal/epl-v10.html"](https://github.com/eclipse/che/blob/master/dockerfiles/base/scripts/base/startup_01_init.sh#L125)

In Codenvy:
[CHE_LICENSE=true](https://github.com/codenvy/codenvy/blob/master/dockerfiles/cli/scripts/pre_init.sh#L26)
[CHE_LICENSE_URL="https://codenvy.com/legal/fair-source/"](https://github.com/codenvy/codenvy/blob/master/dockerfiles/cli/scripts/pre_init.sh#L27)

So my proposal is just make license settings for Codenvy / saas same as in CHE WDYT?

**Comment by TylerJewell** [comment]
+1

I forgot that we made it that flexible!

**Comment by riuvshin** [comment]
@TylerJewell you did :)
