### ISSUE TITLE
CLI offline command fails to execute

### ISSUE THREAD

**Issue by Alspaladin** [codenvy/codenvy#2354]
Trying to execute any command for store images in offline, all of them fails with this message. The `start` command works without problems, but any offline (`--list`, `--image`, also without params)  fails with the same thing.

**Reproduction Steps:**
Create a folder for data, execute this command
`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v {data_folder_path}:/data codenvy/cli offline`

**Codenvy version:**
5.15.0

**OS and version:** 
macOS Sierra
Version 10.12.6

**Docker version:**
17.06.0-ce, build 02c1d87/ docker4mac

**Codenvy cli.log output:**
```
WARN: Bound 'codenvy/cli' to 'codenvy/cli:5.15.0'
INFO: Proxy: HTTP_PROXY=, HTTPS_PROXY=, NO_PROXY=*.local, 169.254/16
INFO: (codenvy cli): 5.15.0 - using docker 17.06.0-ce / docker4mac
/scripts/base/commands/cmd_offline.sh: line 40: /version/5.15.0/images-stacks: No such file or directory
```

**Comment by TylerJewell** [comment]
@riuvshin - FYI - this seems odd. Was the latest version not packaged with standard files that lists the stacks?

**Comment by riuvshin** [comment]
@TylerJewell this is strange... it seems we never had `images-stacks` in codenvy CLI I don't see that file in any previous version. 
and link you looked is CHE CLI not CODENVY.

**Comment by TylerJewell** [comment]
Yeah, I saw the differenct, but the question is why didn't the derivative inherit from Che CLI if there is a matching version? Perhaps it's a regression somehow.

**Comment by riuvshin** [comment]
@TylerJewell CHE and CODENVY CLIs are two different instances with own versions and images but they use same [base](https://github.com/codenvy/codenvy/blob/master/dockerfiles/cli/Dockerfile#L18) 
It is two different things. Codenvy never inherited Che cli, they are completely separate CLIs and yeah in codenvy CLI we never had `images-stacks` file.

**Comment by riuvshin** [comment]
@Alspaladin Once I will merge PRs with fix, I will rebuild 5.15.0 tag with the fix and let you know. Thanks for the reporting this!

**Comment by Alspaladin** [comment]
@riuvshin thank you too for workaround and quick reaction!

**Comment by riuvshin** [comment]
@Alspaladin, I;ve just pushed fix, all you need to do is: `docker pull codenvy/cli` and re run offline command. Feel free to reopen if you will have more questions.
