### ISSUE TITLE
Import project fromGitHub does not work  

### ISSUE THREAD

**Issue by mvidhya86** [codenvy/codenvy#2355]
Hi,
In Codenvy version 5.14.0:

Create new factory – use Template (leave as is – project = https://github.com/codenvy-templates/web-spring-java-simple.git and name=Spring)
    open factory => project is not imported to workspace 

In Che - the above steps are going and project is imported (Version = 5.14.0)

**Comment by eivantsov** [comment]
@mvidhya86 can you perhaps share a factory link?

**Comment by mvidhya86** [comment]
Hi,
Below is the factory link:
http://fe0vmc1363.de.bosch.com/dashboard/#/ide/admin/wss

**Comment by eivantsov** [comment]
@mvidhya86 this is not a factory link, it is a workspace URL. Can you go to User Dashboard - Factories and grab Factory json?

**Comment by mvidhya86** [comment]
Here is the factory json;
{
  "v": "4.0",
  "name": "testfact",
  "workspace": {
    "environments": {
      "wss": {
        "machines": {
          "dev-machine": {
            "attributes": {
              "memoryLimitBytes": "2147483648"
            },
            "servers": {},
            "agents": [
              "org.eclipse.che.terminal",
              "org.eclipse.che.ws-agent",
              "org.eclipse.che.ssh",
              "org.eclipse.che.exec"
            ]
          }
        },
        "recipe": {
          "location": "codenvy/ubuntu_jdk8",
          "type": "dockerimage"
        }
      }
    },
    "defaultEnv": "wss",
    "projects": [
      {
        "links": [],
        "name": "Spring",
        "attributes": {
          "languageVersion": [
            "1.6"
          ],
          "language": [
            "java"
          ]
        },
        "type": "maven",
        "source": {
          "location": "https://github.com/codenvy-templates/web-spring-java-simple.git",
          "type": "git",
          "parameters": {
            "branch": "3.1.0",
            "keepVcs": "false"
          }
        },
        "path": "/Spring",
        "problems": [],
        "mixins": [
          "git"
        ]
      }
    ],
    "name": "wss",
    "commands": [],
    "links": []
  },
  "id": "factoryuf8xglpsxr9059bn",
  "creator": {
    "name": "admin",
    "email": "admin@codenvy.onprem",
    "created": 1502343456683,
    "userId": "admin"
  }
}

**Comment by eivantsov** [comment]
@mvidhya86 you json worked for me.

**Comment by eivantsov** [comment]
Can you perhaps record a screencast?

**Comment by eivantsov** [comment]
Closed due to inactivity. Feel free to reopen if the issue persists.
