### ISSUE TITLE
[Regression] There is an error notification while import a project from Visual Studio Team Services

### ISSUE THREAD

**Issue by SkorikSergey** [codenvy/codenvy#2356]
**Reproduction Steps:**
1. Create a workspace.
2. Menu **Workspace** -> **Import Project**.
3. Select the **GIT** from left menu and type **https://iedexmain1.visualstudio.com/_git/MyFirstProject** in the URL field.
4. Click the **Import** button.

**Observed behavior:**
There is error notification: **Authentication is required but no CredentialsProvider has been registered**.

**Codenvy version:** 5.16.0
**Server location:** https://nightly.codenvy-stg.com, https://nightly-onprem.codenvy-stg.com
**Failed test:** CheckWorkWithVSTSProviderTest.

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![config-42](https://user-images.githubusercontent.com/7760565/29021642-de2ca7de-7b6e-11e7-9c61-87d586a221ff.gif)

**Comment by musienko-maxim** [comment]
May be related with https://github.com/codenvy/codenvy/issues/2386

**Comment by mmorhun** [comment]
Fixed
