### ISSUE TITLE
How to decrease the amount of purchased RAM?

### ISSUE THREAD

**Issue by mbrung** [codenvy/codenvy#2364]
I purchased an additional 3 GB of RAM on Codenvy.io, and no longer need it.  I can't find where to decrease the amount of subscribed RAM in the UI.  Am I missing something or is this something that cannot be altered by the user?

Thanks!

**Comment by eivantsov** [comment]
@ashumilova @bmicklea can you assist please?

**Comment by ashumilova** [comment]
@mbrung Hi, at the moment there is no ability to decrease purchased amount from UI, but to cancel subscription - you can unbind your credit card from your codenvy account by removing it.

**Comment by mbrung** [comment]
Easy enough -- thanks, @ashumilova !
