### ISSUE TITLE
Bugs on the Billing page

### ISSUE THREAD

**Issue by SkorikSergey** [codenvy/codenvy#2369]
**Selecting teams**
1. Create two or more team
2. Click on the **Bulk** checkbox and uncheck any team

Observed behavior:
The **Bulk** checkbox is still checked

**Team sorting doesn't work**
1. Create two or more team
2. In the **Team list** click on the **NAME** to sort the teams names by alphabet

Observed behavior:
Nothing changes

**The delete button enabled for all members in a team**
1. Create a team with other account and invite this user as a member

Observed behavior:
The delete team button enabled in the **Team list**

**Codenvy version:** 5.17.0
**Server location:** https://nightly.codenvy-stg.com

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![ws-4](https://user-images.githubusercontent.com/7760565/29215996-dd6dd5c6-7eb5-11e7-813e-acd4ce279c20.gif)

**Comment by riuvshin** [comment]
@ashumilova please take a look

**Comment by SkorikSergey** [comment]
Not relevant anymore. Closing.
