### ISSUE TITLE
New to Codenvy, some questions

### ISSUE THREAD

**Issue by drock577** [codenvy/codenvy#2370]
Hi all,

New to codenvy and have some questions about the service! So far it seems really awesome to use but some stuff is unclear.

For the free plan...

For work workspaces hosted on codenvy.io , are they considered private (one needs to be logged in and added to a specific workspace) ? If I wanted to share a workspace I Would need to set up a team (limited to 3 total).

With the memory limit ... If I have multiple workspaces, is the memory limit only counted for the active workspaces or the total memory allocated for all workspaces? 

When selecting a stack am I limited to that option in the development environment. If one project requires executing C++ Python files would I need to create 2 separate workspaces? Is it possible to tailor an environment to do both in one Workspace?

Thanks in advance!

**Comment by eivantsov** [comment]
1. Yes, your workspace is only yours. If you want to share your workspace, you invite another user. There's no need to create a team for it.

2. RAM limit is applied for a running workspace. There's also a limit for the overall number of workspaces a free tier user can have.

3. Yes, you can create a workspace from a custom recipe and install anything you want there. Alternatively, you may start with a blank stack, and install all dependencies in the runtime. In this case, however, you should always snapshot a workspace (in fact, this is done automatically when you stop a workspace).
