### ISSUE TITLE
Remove redundant ReportSender

### ISSUE THREAD

**Issue by tolusha** [codenvy/codenvy#2373]
`ReportSender` is used to send weekly data to `data@codenvy.com`

* Ip Address
* Host name
* the total number of users

It is not more relevant. 

@bmicklea Could you confirm pls.
@riuvshin Could you confirm that it is already broken due to configuration issue.

**Comment by bmicklea** [comment]
I think this is still relevant - isn't this the data that I use for analytics reports?

**Comment by tolusha** [comment]
I don't know. Could you check pls?

**Comment by bmicklea** [comment]
@skryzhny - can you confirm if this is used by the daily/weekly/monthly analytics reports I receive?

**Comment by TylerJewell** [comment]
@tolusha @bmicklea - labels, please

**Comment by skryzhny** [comment]
@bmicklea data@codenvy.com not used. I can't find any mention of sending emails to data@codenvy.com in last 6 months on our test onprem instance.
You are receiving reports from script that analyse logs.

**Comment by bmicklea** [comment]
Thanks @skryzhny - let's remove it @tolusha

**Comment by mmorhun** [comment]
Done
