### ISSUE TITLE
Disable syntax error warnings

### ISSUE THREAD

**Issue by mweaver** [codenvy/codenvy#2377]
I'm interested in using Codenvy in my high school classroom.  However, I don't want my students to get much "help" from the IDE.  I've ignored all of the other warnings/errors in Preferences, but there is no option to disable syntax error warnings (AFAIK).

Is there a way to do this?

Thanks!

**Comment by eivantsov** [comment]
Syntax checking is enabled for all java and maven projects. There's no way to disable it other than change project type.
