### ISSUE TITLE
[REGRESSION] Project wizard does not closed after maven project creating 

### ISSUE THREAD

**Issue by Ohrimenko1988** [codenvy/codenvy#2379]
This bug also reproduce in the "onprem"

**Reproduction Steps:**
- Create java workspace without project 
- After workspace will be started, click on "Create project" link
- Choose "web-java-spring" project, input project name and click "Create" button
- Pay attention that project is created but project wizard is not closed, and default commands are not added

**Codenvy version:** 
Codenvy 5.17.0 ; Chrome 59.0 ; Fedora 25

**Comment by SkorikSergey** [comment]
The project wizard hangs while creating command for maven projects.

**Comment by Ohrimenko1988** [comment]
Some clarification, bug is reproduced if ( profile -> preference -> maven -> Show artifact id in project explorer ) checkbox is enabled , if this checkbox is disabled (artifact id is not shown in project explorer) all works correctly.

**Comment by riuvshin** [comment]
@vparfonov please check this

**Comment by Ohrimenko1988** [comment]
Issue is moved https://github.com/eclipse/che/issues/6025
