### ISSUE TITLE
[Regression] A workspace status doesn't refresh in the Recent Workspaces list

### ISSUE THREAD

**Issue by SkorikSergey** [codenvy/codenvy#2380]
**Reproduction Steps:**
1. Create a workspace and start it
2. Wait until the workspace starts

**Observed behavior:**
Status of the workspace on the **Recent Workspaces** list didn't change(it's still has **STARTING** status). Similar happens when click on the Action buttons in the Workspaces list.

**Codenvy version:** 5.17.0
**Server location:** https://nightly.codenvy-stg.com, https://nightly-onprem.codenvy-stg.com

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![teams-14](https://user-images.githubusercontent.com/7760565/29407149-18cf0d48-834c-11e7-82bc-4d29fdbc5586.gif)

**Comment by riuvshin** [comment]
@ashumilova please take a look

**Comment by riuvshin** [comment]
@SkorikSergey same issue on CHE?

**Comment by SkorikSergey** [comment]
Only codenvy.
