### ISSUE TITLE
Created files that matches a specific entry in .gitignore does not save after Workspace restart

### ISSUE THREAD

**Issue by eivantsov** [codenvy/codenvy#2381]
_From @sr229 on August 18, 2017 8:43_

I somehow found this "bug" while adding a ignored file from ``.gitignore `` on our project.

A [Factory](https://nightly.codenvy-stg.com/f?id=factoryyjqh34keob34i0rc) has been created for easier reproduction

**Reproduction Steps:**
1:) using the factory above, create a file named ``config.json`` 
2:) restart the workspace

**Expected**: The file should persist even in restart
**Result**: The file disappears after restart

**OS and version:**    
Codenvy 5.17.0-SNAPSHOT on Windows 10 

_Copied from original issue: eclipse/che#6039_

**Comment by eivantsov** [comment]
@sr229 rsync that stands behind restoring and backuping projects does not respect all of the gitignore rules.

I have hard time loading your factory, can you share your gitignore here in this issue?

**Comment by sr229** [comment]
@eivantsov this is my [``.gitignore``](https://github.com/ClaraIO/Clara/blob/development/.gitignore)

as you can see, it has ``config.json`` ignored during commits.

**Comment by eivantsov** [comment]
Rsync ignores files that are in gitignore. This is the default behavior at the moment.

**Comment by sr229** [comment]
Ah, it's a real pain though since I have to create the configuration file again and again after restarts. It would be nice if we can change the behavior of Rsync

**Comment by eivantsov** [comment]
Once Codenvy features are moved to Eclipse Che, project backup will have a different mechanism. So the issue will fix itself.
