### ISSUE TITLE
Incorrectly parsing commands

### ISSUE THREAD

**Issue by anantoghosh** [codenvy/codenvy#2385]
I have just started using codenvy, any multi line command is parsed incorrectly.
Windows 10
Tried on latest stable chrome, opera and firefox
  
![cdls](https://user-images.githubusercontent.com/12339068/29509542-3f63953c-8676-11e7-9a5f-c124837b6894.PNG)
![lsls](https://user-images.githubusercontent.com/12339068/29509552-484ba4fa-8676-11e7-9658-4575186aa58b.PNG)
  
  
  
**This works though**
  
![works](https://user-images.githubusercontent.com/12339068/29509615-72cee91c-8676-11e7-82be-819e64588a7d.PNG)

**Comment by SkorikSergey** [comment]
I am unable to reproduce this use case. Could you provide more information?

**Comment by anantoghosh** [comment]
I'm not doing anything special

went to workspace -> add workspace -> select stack blank -> create
after booting
clicked run button at top -> create Run Command
on Command Line write
```
ls
ls
```
Run
``` /bin/bash: $'ls\r': command not found ```

https://youtu.be/gNxZDw1FpIc
Here's the video showing the same.

I'm running Windows 10 Pro 1703.
Opera 47.0.2631.55
Firefox 55.0.2

If there is any logs that you need, do inform me.

**Comment by SkorikSergey** [comment]
This bug is really reproduced if create a command for projects using browsers in Windows.

**Comment by SkorikSergey** [comment]
Moved to https://github.com/eclipse/che/issues/6055.
