### ISSUE TITLE
The factory with BitBucket repository does not clone the project

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#2386]
**Reproduction Steps:** try to consume the next factory: https://nightly.codenvy-stg.com/f?id=factoryxsn5zbj9rc67r43k 
 
**Expected result**: after creation the workspace should appear authorization window for BitBacket. After entering credentials, the Spring project should be set  as maven.
**Actual result:** the authorization window does not appear. The Spring project is nor cloned and set.
**Additional information:** i think it may be related with: https://github.com/codenvy/codenvy/issues/2356
**Env.**: chrome browser, Codevy 5.17.0-Snapshot, https://nightly.codenvy-stg.com/ server

**Comment by riuvshin** [comment]
fixed by https://github.com/eclipse/che/pull/6053
