### ISSUE TITLE
A factory with GitLab repo in the config does not clone the project properly

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#2387]
**Reproduction Steps:** try to consume the next factory: https://nightly.codenvy-stg.com/f?id=factory4mzcznqcj3w59pn0
 
**Expected result**: after creation the workspace the project should be set as blank.
**Actual result:** the project is not set as blank but as unknown. After trying to open - appears the import dialog window. If we click on import button the project still as unknown. But after refreshing browser the project is set properly.

**Additional information:** i think it may be related with: https://github.com/codenvy/codenvy/issues/2356
**Env.**: chrome browser, Codevy 5.17.0-Snapshot, https://nightly.codenvy-stg.com/ server

**Comment by riuvshin** [comment]
fixed by https://github.com/eclipse/che/pull/6053
