### ISSUE TITLE
The change password feature works without checking

### ISSUE THREAD

**Issue by SkorikSergey** [codenvy/codenvy#2388]
**Reproduction Steps:**
1. Go to the **Profile & Account** page 
2. In the **Security** tab type a new password in the **New password** field

**Expected behavior:**
The **Update Password** button disabled 

**Observed behavior:**
The **Update Password** button is enabled and if press it then the password will change without checking.

**Codenvy version:** 5.17.0
**Server location:** https://nightly.codenvy-stg.com, https://nightly-onprem.codenvy-stg.com

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![teams-21_1](https://user-images.githubusercontent.com/7760565/29523641-5146b0fc-8696-11e7-8d81-e2adb11ea440.gif)

**Comment by riuvshin** [comment]
@ashumilova check this please

**Comment by SkorikSergey** [comment]
This issue is not reproduced in 5.19.0 version.
