### ISSUE TITLE
Remove Codenvy references in email templates.

### ISSUE THREAD

**Issue by vkuznyetsov** [codenvy/codenvy#2389]
Remove Codenvy references in email templates.

**Comment by eivantsov** [comment]
@slemeur are you sure this is smth you have asked for? Maybe making email templates configurable is a better choice here?

**Comment by slemeur** [comment]
@vkuznyetsov + @eivantsov : You are right. I have not asked for making the codenvy templates different.

But, while we will move the permissions, teams and organization, we will also move the email notifications from Codenvy to Che. We need to apply Che styles and review the languages that are in those emails.

So it's not a task in Codenvy repo.
