### ISSUE TITLE
error in workspace

### ISSUE THREAD

**Issue by akostadinov** [codenvy/codenvy#2392]
I'm a new user. Created a new workspace. Trying to open it with FF 55.0.1 on Fedora 26 fails with:

```
window.IDE.eventHandlers.initializationFailed@https://codenvy.io/akostadinov/rene-tracker?uid=695364:40:27
Qlg@_app-0.js:7832:101
emg@_app-0.js:7842:254
xcj@_app-0.js:14331:204
zcj@_app-0.js:14333:64
b0e@_app-0.js:5256:349
U_e/f<@_app-0.js:5247:116
```

**Comment by eivantsov** [comment]
@akostadinov can you open dev console and share a screenshot here? It does look like a networking issue on your side - when the browser (client) cannot connect to a workspace agent.

**Comment by akostadinov** [comment]
I don't see this error today. Thank you!
