### ISSUE TITLE
Cannot run docker from terminal (codenvy cloud hosted version)  

### ISSUE THREAD

**Issue by cepix** [codenvy/codenvy#2396]
**Reproduction Steps:**

1.Create a workspace using Java,Maven  stack.
2.Download and install docker using terminal commands 
3. Try to run any docker image:

Result:

```
user@5a8f5170b603:/projects$ docker run --name instanc_name  -d mongo
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
```

**Codenvy version:**   Cloud Hosted

**OS and version:**   Cloud Hosted (Ubuntu VM?)

**Docker version:** 
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:51:12 2017
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Comment by eivantsov** [comment]
@cepix you need to start your workspaces in a privileged mode, and this way you will be able to run Docker in Docker. 

In your codenvy.env, make sure CODENVY_SYSTEM_SUPER_PRIVILEGED_MODE is set to true, and restart Codenvy.

**Comment by cepix** [comment]
@eivantsov thanks for the tip.  I cannot find the file within my workspace.
This only applies for self hosted codenvy right? Im using a free account in @ codenvy.com.

**Comment by eivantsov** [comment]
Yes, this config is available if you install Codenvy On-Prem. If you are a user at codenvy.io there's no way to use Docker due to security reasons.
