### ISSUE TITLE
Php7 - Laravel - Problem with htaccess

### ISSUE THREAD

**Issue by reina3596** [codenvy/codenvy#2404]
Hello

I have install a fresh installation of Laravel in a workspace of PHP7 from default stacks.

The problem seems to be in the file ".htaccess" since it does not apply the redirect to the file index.php.

I use default .htaccess from fresh installation of Laravel.

If I execute from terminal "a2enmod rewrite" >>>>>> Module rewrite already enabled

For example:
http://node13.codenvy.io:39776/laravel/public/index.php/hello         IT IS OK
http://node13.codenvy.io:39776/laravel/public/hello                          404 NOT FOUND

**Comment by reina3596** [comment]
Anybody?

**Comment by eivantsov** [comment]
@reina3596 perhaps this is what you should try https://stackoverflow.com/questions/24784606/laravel-routes-not-working-apache-configuration-only-allows-for-public-index-ph

**Comment by eivantsov** [comment]
Closed due to inactivity.
