### ISSUE TITLE
max threads can not exceed aproximatly 512 threads 

### ISSUE THREAD

**Issue by achabahe** [codenvy/codenvy#2405]
the workspace machine (container) can  not handel more than 512 threads,  i am crurrently working on a software that might require more than this upper limit;the container does not consume much of the memory while trying forking the threads , when it hits that number it stops forking even if the container still have so much memory.
 

**Reproduction Steps:**
use the folowing C program to span threads and test the limit:
/* compile with:   gcc -pthread -o thread-limit thread-limit.c */
/* originally from: http://www.volano.com/linuxnotes.html */

#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <pthread.h>
#include <string.h>

#define MAX_THREADS 100000
int i;

void run(void) {
  sleep(60 * 60);
}

int main(int argc, char *argv[]) {
  int rc = 0;
  pthread_t thread[MAX_THREADS];
  printf("Creating threads ...\n");
  for (i = 0; i < MAX_THREADS && rc == 0; i++) {
    rc = pthread_create(&(thread[i]), NULL, (void *) &run, NULL);
    if (rc == 0) {
      pthread_detach(thread[i]);
      if ((i + 1) % 100 == 0)
    printf("%i threads so far ...\n", i + 1);
    }
    else
    {
      printf("Failed with return code %i creating thread %i (%s).\n",
         rc, i + 1, strerror(rc));
      // can we allocate memory?
      char *block = NULL;
      block = malloc(65545);
      if(block == NULL)
        printf("Malloc failed too :( \n");
      else
        printf("Malloc worked, hmmm\n");
    }
  }
sleep(60*60); // ctrl+c to exit; makes it easier to see mem use
  exit(0);
}

**View number of threads**
you can use htop beacause ps might no work because when you will try to run it you will find that linux can not fork a thread to run the ps process. so launch htop then launch stresser!
you should configure htop to see number of threads NLWP

**Codenvy version:**5.17.0

**Comment by eivantsov** [comment]
@achabahe I guess this is Docker limitation. Can you do the same in a container that you manually start locally?

**Comment by achabahe** [comment]
i have found the issue it is a codenvy property that exists in the file instance/config/codenvy/conf/machine.properties the property name is che.docker.pids_limit i changed and i was gooooood to go ; thanks m8
