### ISSUE TITLE
[branch CHE-5258] To by more RAM, is not possible 

### ISSUE THREAD

**Issue by Ohrimenko1988** [codenvy/codenvy#2409]
**Reproduction Steps:**
- Go to the billing page -> Credit card or click on "Get More RAM" widget
- Fill the fields with valid values
- Pay attention that fields validation is not worked, and "Continue" button is disabled

**Codenvy version:**  
Codenvy 5.18.0 ; Chrome 59.0 ; Fedora 25

**Comment by SkorikSergey** [comment]
Fixed.
