### ISSUE TITLE
Do we have CHE_DOCKER_ALWAYS__PULL__IMAGE in Codenvy?

### ISSUE THREAD

**Issue by marami52** [codenvy/codenvy#2416]
I noticed that we can set `CHE_DOCKER_ALWAYS__PULL__IMAGE=false` in Che to run it offline but could not find similar setting in Codenvy. Is there any way in Codenvy to have the same setting for pulling images locally? Codenvy fails in _offline_ mode if it cannot reach to the hub.

**Comment by eivantsov** [comment]
@marami52 there's no such env in Codenvy which is a cloud solution by design. You may set up a local Docker registry and pull images from there.

**Comment by marami52** [comment]
ok. Thanks.
