### ISSUE TITLE
fail to ssh connect to digitalocean

### ISSUE THREAD

**Issue by machinefriendly** [codenvy/codenvy#2436]
I tried to ssh connect from codenvy workspace to my digitalocean droplet, like this:
ssh root@139.59.xxx.xx
but I always got error : ssh: connect to host 139.59.xxx.xx port 22: Connection times out 

I checked:
- port is 22 in digitalocean ssh configuration file
- ssh server is set on digitalocean ubuntu server
- tried with Mac and c9.io, both succeeded in connection.

Thanks for your attention.

**Comment by achabahe** [comment]
have you tried to telnet from the workspace to the machine in digital ocean in port 22
`telnet 139.59.XXX.XX 22`

is there a restriction over ip you have configured in digital ocean machin

**Comment by eivantsov** [comment]
@machinefriendly you need to whitelist your IP for outbound connections.

@skryzhny can do that but he needs your IP address.

**Comment by machinefriendly** [comment]
@eivantsov thanks.
@skryzhny it's 139.59.169.43 , thanks.

**Comment by skryzhny** [comment]
Whitelisted.

**Comment by machinefriendly** [comment]
Thanks @skryzhny 
However, I just got mail from Digitalocean telling that my server/droplet is used for DDOS and is therefore banned, do you think that it's not good to publish my IP publicly as I did above, which could be used by someone for attack, FYI, according to the metric trend change it start when IP is whitelisted? I'm a new man in dev so I'm kind of lost in this, thanks for your thought, for example, I'll have new IP for new droplet, how can I transfer to your team? which mail or private message? Thanks.
