### ISSUE TITLE
Getting Rust syntax highlighting to work?

### ISSUE THREAD

**Issue by peterwilli** [codenvy/codenvy#2439]
Hi everyone,

I just created a new workspace, with Ubuntu as stack, and installed Rust using their original manual.
Everything works fine, except that syntax highlighting is not supported.

I started looking up how to install additional languages on Codenvy and found out about Language Server which supports syntax highlighting.

But I'm stuck on how to install this language server for Rust in particular. 

I found this repo: https://github.com/rust-lang-nursery/rls which contains the Rust language server, but I'm stuck on how to install this on my Ubuntu workspace. I couldn't find this in the docs.

Do you know how to install a custom language server or get Rust syntax highlighting to work? Thanks!

**Comment by eivantsov** [comment]
@peterwilli there's no dynamic support of 3rd party language servers. So, in case of codenvy.io the answer would be - it is not currently possible.

**Comment by peterwilli** [comment]
@eivantsov do you think it will be implemented? Is there something else I can do about it?

**Comment by eivantsov** [comment]
@peterwilli there are no immediate plans.

You may create an enhancement request at https://github.com/eclipse/che/issues
