### ISSUE TITLE
codenvy.io hangs a lot

### ISSUE THREAD

**Issue by startupgurukul** [codenvy/codenvy#2440]
codenvy.io hangs a lot, browser will prompt if users wants to kill the page,  Please take a look. Behind all this amazing engineering product,  there seems to be a long running script thats  giving a bad User Experience 
**Reproduction Steps:**
latest build on condevy.io there seems to be a long running script..

**Codenvy version:**  Version :5.18.0Revision :44970264fd881111Build Time :2017-09-20 11:00:16
**OS and version:**    
Windows, Mac , Linux chrome 

**Docker version:**    

**Codenvy cli.log output:**

**Comment by eivantsov** [comment]
@startupgurukul any particular scenarios that lead to page going unresponsive?

**Comment by eivantsov** [comment]
Closed due to inactivity.
