### ISSUE TITLE
Cover with selenium tests the "Profile" page 

### ISSUE THREAD

**Issue by Ohrimenko1988** [codenvy/codenvy#2450]
We need to cover with selenium test next usecase:
 - Go to profile page
 - Change first name and last name
 - Check that changes are saved and name and lastname are changed in the dashboard footer.

**Comment by riuvshin** [comment]
@Ohrimenko1988 please move this issue to che if che has this functionality as we are not interested in new tests for codenvy.

**Comment by Ohrimenko1988** [comment]
Moved to the "che" repository https://github.com/eclipse/che/issues/8222
