### ISSUE TITLE
[CHE-multiuser branch] Wizard project form is wrong

### ISSUE THREAD

**Issue by artaleks9** [codenvy/codenvy#2457]
**Reproduction Steps:**
* Build and run the `codenvy` project in the `che-multiuser` branch
* Create and start workspace
* Try to create maven project from template

**Expected behavior:**
* Should be a possibility to select type of project

**Observed behavior:**
* There is only `Blank' type of project

**Codenvy version:**  5.19.0
**OS and version:**  Fedora 25   
**Docker version:** 17.06
**API docker version:** 1.30

**Additional informatio**n:
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:
![project-wizard](https://user-images.githubusercontent.com/5408906/31132006-5beb32ea-a864-11e7-95bb-03c1e62426df.png)

**Comment by akorneta** [comment]
Fix [commit](https://github.com/codenvy/codenvy/commit/750c71c5a79d22f8aa53cf3972c3b7355520cae4)
