### ISSUE TITLE
Rework AuthenticateAndAcceptFactoryThroughGitHubOAuthTest test to remove github user after test execution

### ISSUE THREAD

**Issue by dmytro-ndp** [codenvy/codenvy#2471]
There is **AuthenticateAndAcceptFactoryThroughGitHubOAuthTest** which has [_tearDown()_](https://github.com/codenvy/codenvy/blob/master/selenium/codenvy-selenium-test/src/test/java/com/codenvy/selenium/factory/AuthenticateAndAcceptFactoryThroughGitHubOAuthTest.java#L69) method aimed to remove github test user, but it is broken and remove default user instead.
To fix it we should provide github user email so as **testUserServiceClient.findByName(gitHubUsername)** doesn't work as expected.

**Codenvy version:**    
5.19.0-SNAPSHOT

**OS and version:**    

**Docker version:**    

**Codenvy cli.log output:**

**Comment by Ohrimenko1988** [comment]
Done
