### ISSUE TITLE
[Regression] The Delete button on organization members tab doesn't appear if select a member by checkbox

### ISSUE THREAD

**Issue by SkorikSergey** [codenvy/codenvy#2473]
**Reproduction Steps:**

- Create an organization and add members
- Try to select members by checkbox and delete 

**Observed behavior:**
After checking a member the **Delete** button doesn't appear.
Similar issue is with teams on https://nightly.codenvy-stg.com.

**Codenvy version:** 5.19.0
**Server location:** https://nightly-onprem.codenvy-stg.com
**Related selenium test:** OrganizationMembersTest

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![teams-11-24](https://user-images.githubusercontent.com/7760565/31391287-c3631666-adde-11e7-8581-0514d684cb6f.gif)

**Comment by dmytro-ndp** [comment]
Duplicates https://github.com/eclipse/che/issues/7897

**Comment by SkorikSergey** [comment]
Moved to https://github.com/eclipse/che/issues/7897.
