### ISSUE TITLE
Cannot use preview URL with ASP.NET Core Web Application

### ISSUE THREAD

**Issue by alexharvey52** [codenvy/codenvy#2478]
Cannot access ASP .NET CORE Web application with preview URL. I am trying to access a .net core web application I have made. I am not sure how to correctly bind the local host URL to the preview URL I am given.

I have tried using this is the program.cs

```
            var host = new WebHostBuilder()
                    .UseKestrel()
                    .UseContentRoot(Directory.GetCurrentDirectory())
                    .UseUrls("http://node24.codenvy.io:37899")
                    .UseIISIntegration()
                    .UseStartup<Startup>()
                    .Build();
                    
            host.Run();
```

however the console then outputs this and with the preview the site cannot be reached.

```
Preview: http://node29.codenvy.io:37899
Hosting environment: Production
Content root path: /projects/aspnetcore-Vue-starter-signalR
Now listening on: http://[::]:37899
Application started. Press Ctrl+C to shut down.
```

What is the correct way to setup a ASP.NET Core Web Application on Codenvy.

Please note I am using the codenvy shared cloud.

**Reproduction Steps:**

Created and setup new ASP.NET Core Web Application, build and run the site, attempt to view the URL.

**Codenvy version:**    5.18.0

**OS and version:**    Linux

![image](https://user-images.githubusercontent.com/12846946/31449192-2d85e676-ae9e-11e7-8737-31d61e15ed07.png)

**Comment by eivantsov** [comment]
@alexharvey52 `.UseUrls("http://node24.codenvy.io:37899")` is wrong. It should be `0.0.0.0:5000`

**Comment by alexharvey52** [comment]
Thanks, that worked. I also set it to .UseUrls("http://node24.codenvy.io:5000") and that worked. :)
