### ISSUE TITLE
mvn clean install failed on Mac Sierra

### ISSUE THREAD

**Issue by hfuhuang** [codenvy/codenvy#2479]
The build and installation of codenvy on Mac OS failed because of dashboard component

I think it is because of bower package.

mvn --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /usr/local/Cellar/maven@3.3/3.3.9/libexec
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac"

npm --version
5.3.0

node --version
v8.6.0

npm config set proxy <with correct http://host:port> 
npm config set https-proxy <with correct http://host:port> 

**Reproduction Steps:**
1. git clone https://github.com/codenvy/codenvy.git
2. cd to codenvy
3. mvn clean install

**Codenvy version:**    
The git master

**OS and version:**    
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac"
**Docker version:**    
Docker version 17.03.1-ce, build c6d412e
**Codenvy cli.log output:**  
....
 [exec] bower che-dashboard#master       retry Download of https://github.com/eclipse/che/archive/master.tar.gz failed with ECONNRESET, trying with git..
     [exec] bower che-dashboard#master    checkout master
     [exec] bower che-dashboard#master    progress Checking out files:  39% (4894/12361)
     [exec] bower che-dashboard#master    progress Checking out files:  70% (8670/12361)
     [exec] bower che-dashboard#master    progress Checking out files:  93% (11558/12361)
     [exec] bower che-dashboard#master    resolved https://github.com/eclipse/che.git#21e73d4942
     [exec] bower angular-dropdowns#1.0.0       ECONNRESET Request to https://registry.bower.io/packages/angular-dropdowns failed: tunneling socket could not be established, cause=connect EHOSTUNREACH 0.0.12.56:80 - Local (192.168.15.183:62050)
     [exec] npm ERR! code ELIFECYCLE
     [exec] npm ERR! errno 1
     [exec] npm ERR! userDashboard@4.0.0 postinstall: `bower install && typings install && cd bower_components/che-dashboard/dashboard && npm install`
     [exec] npm ERR! Exit status 1
     [exec] npm ERR! 
     [exec] npm ERR! Failed at the userDashboard@4.0.0 postinstall script.
     [exec] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by eivantsov** [comment]
@hfuhuang must be a connectivity issue with https://registry.bower.io/packages/angular-dropdowns 

Please try it again

**Comment by hfuhuang** [comment]
@eivantsov Thanks for your answers. Yes, it was because of connectivity. The solution is:
add proxy setting in .bowerrc.
And must have other tools mentioned in /codenvy/site/README.md.
