### ISSUE TITLE
Cannot share 

### ISSUE THREAD

**Issue by samplenty** [codenvy/codenvy#2496]
I cannot seem to add developers to a project.

**Reproduction Steps:**
 - Create a new workspace.
 - Go to settings for that workspace
 - Click add developer
 - Nothing happens

**Codenvy version:** 
5.19.0

**OS and version:**    
Mac OS 10.12

**Docker version:**
N/A

**Codenvy cli.log output:** 
N/A

**Comment by eivantsov** [comment]
Bug confirmed

![image](https://user-images.githubusercontent.com/5337267/31927252-846d4f98-b893-11e7-9561-a696c5798775.png)
