### ISSUE TITLE
Zip importing from wizard does not works properly

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#2501]
**Reproduction Steps:**
- Import project -> ZIP -> paste to URL: paste url like: https://github.com/maxura/spring-demo-project/archive/master.zip

**Expected result:** The project should be imported and configured as maven.

**Actual result:**  We have errors like on  screenshot.
![selection_013](https://user-images.githubusercontent.com/1640058/31825817-104b209c-b5bc-11e7-8262-842581e1b45b.png)

**OS and version:**  Fedora 25, chrome browser.

**Comment by Rit11** [comment]
hope, same file with the same name present already
