### ISSUE TITLE
Cannot preview application using Ruby stack

### ISSUE THREAD

**Issue by cesarcastanon** [codenvy/codenvy#2503]
**Reproduction Steps:**

execute the cd ${current.project.path} && rails server -b 0.0.0.0 command I get the following error 

[2017-10-21 18:16:32] INFO  WEBrick 1.3.1
[2017-10-21 18:16:32] INFO  ruby 2.3.0 (2015-12-25) [x86_64-linux]
[2017-10-21 18:16:32] INFO  WEBrick::HTTPServer#start: pid=621 port=3000

My preview URL is automatically set to http://node10.codenvy.io:38393 but If I click that then I get a page with an error 

This site can’t be reached

node10.codenvy.io refused to connect.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

**OS and version:**    
Linux version 3.10.0-514.26.2.el7.x86_64
**Docker version:**    

**Codenvy cli.log output:**  
This is what I have in IDE
![screenshot 2017-10-21 at 12 26 38 pm - display 2](https://user-images.githubusercontent.com/22456622/31856039-15ad23be-b675-11e7-9e24-290a3bc42e9f.png)
This is the error I get when clicking on the "PreviewURL"
![screenshot 2017-10-21 at 2 10 06 pm - display 2](https://user-images.githubusercontent.com/22456622/31856040-15dbbf58-b675-11e7-8a46-813ea751503b.png)

**Comment by cesarcastanon** [comment]
![screenshot 2017-10-21 at 12 26 38 pm - display 2](https://user-images.githubusercontent.com/22456622/31854747-7d27d7a6-b65b-11e7-815d-40ec9e372ebc.png)
Here is a screen capture of what I see. Any help will be highly appreciated.

**Comment by eivantsov** [comment]
@cesarcastanon you need to make sure the ephemeral port range is not filtered (32768-65535)

I was able to run the app:

![image](https://user-images.githubusercontent.com/5337267/31859809-28d603bc-b719-11e7-9200-4f1ca56affcb.png)

**Comment by cesarcastanon** [comment]
Thank you, I tried in a different network and that resolved the issue.
