### ISSUE TITLE
How to configure React proxy on Codenvy

### ISSUE THREAD

**Issue by kmaillet** [codenvy/codenvy#2504]
Hi All,
I'm trying to configure a Codenvy dev environment to develop a web app with a React front end and a Flask API. To redirect the api calls from React's hot reload server to the Flask development server, I use the "proxy" functionnality [https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#proxying-api-requests-in-development](url) when I develop locally (or on eclipse/che) . Unfortunately I'm unable to do so when developping on Codenvy. 

Did anyone find a workaround for this ? What is the best way to set up Codenvy for React development ?

I love the idea behind Codenvy, my team would greatly benefit from it if we could find a hack for this issue

Thanks

**Reproduction Steps:**

**Codenvy version:**    5.19.0

**OS and version:**    

**Docker version:**    

**Codenvy cli.log output:**

**Comment by eivantsov** [comment]
@kmaillet-arcane what exact errors do you see? I'd try setting proxy to `0.0.0.0` instead of localhost.

**Comment by kmaillet-arcane** [comment]
Hi, 

Thanks for your feedback. 
When I configure the proxy with 0.0.0.0, I get a "Invalid Host header" error from React. This error is documented https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#invalid-host-header-errors-after-configuring-proxy 
Unfortunately, none of the workaround mentioned by facebook are working for me.

**Comment by eivantsov** [comment]
@kmaillet-arcane each time you start a workspace it is started on a different node (not necessarily but it cannot be predicted). But you can find out what node you are currently on in User Dashboard, workapaces - your workspace - servers

**Comment by frank0631** [comment]
I also ran into the "Invalid Host header" while running in eclipse che. I found that setting "disableHostCheck: true" in webpack.config.js fixed it.
