### ISSUE TITLE
Unable to start Workspace

### ISSUE THREAD

**Issue by rajborborah** [codenvy/codenvy#2507]
Getting the following error when starting workspace. Not sure I understand what the error is
------
Could not start workspace HeyKellieWorkspace. Reason: Start of environment 'default' failed. Error: Restoring of workspace workspacejemldtywxf8mjlkl filesystem terminated on node10.codenvy.io node. Synchronization process failed. Exit code 255

**Comment by eivantsov** [comment]
@rajborborah do you have any big files in your project? Also, what stack do you use?

**Comment by eivantsov** [comment]
Closed due to inactivity. Feel free to reopen if the problem persists.

**Comment by wired2code** [comment]
Am unable to start any workspace after I login - via google. The email address is tough2remember@gmail.com. Was able to use the work space earlier this Monday (11 March). On running diagnostics, get the following message - No reply of websocket test after 5 seconds. Websocket is failing to connect to wss://codenvy.io:443/api/ws
 --- ERROR
