### ISSUE TITLE
GDB debugger

### ISSUE THREAD

**Issue by Honpray** [codenvy/codenvy#2509]
I have problem with C++ program debugging. I've read about the debugger section in the doc and remote debugger can connect to localhost successfully. But nothing shows in the frame when I add some breakpoint.
If I run the gdb in terminal, this message shows.
`
Starting program: /projects/cpptest/a.out
warning: Error disabling address space randomization: Operation not permitted
During startup program exited normally.
`
I'm compiling using `g++ -g hello.cpp` , and run the IDE using `docker run --privileged codenvy/cli start`

And as the events show the Remote debugger disconnected as soon as it connected. How can I fix this?

**Codenvy version:**    5.19.0

**OS and version:**    Mac OS Sierra 10.12.6

**Docker version:**   17.09.0-ce-mac35 (19611)

**Comment by eivantsov** [comment]
Currently, this is expected behavior. GDB debugger requires `seccomp:unconfined` mode for a container which is disabled for codeny.io due to security reasons.

**Comment by Honpray** [comment]
Ok. Thank you for the reply!
So what about the local docker image? Can I solve that by adding some flag to the docker run command?

**Comment by eivantsov** [comment]
@Honpray only if you use Eclipse Che https://github.com/eclipse/che

**Comment by Honpray** [comment]
Appreciated.
