### ISSUE TITLE
How can I use Jekyll with the Ruby on Rails Stack?

### ISSUE THREAD

**Issue by jrdnbrn** [codenvy/codenvy#2514]
I am trying to use Jekyll with the Ruby on Rails stack, but I'm not sure how to connect to the server

**Reproduction Steps:**
I made a workspace using the Ruby on Rails stack
`gem install jekyll`
`jekyll new mytheme`
`cd mytheme`
`bundle install`
`jekyll serve`

**Codenvy version:**  
5.19.0

**Comment by eivantsov** [comment]
What port is your server bound to?

**Comment by jrdnbrn** [comment]
What server?

**Comment by eivantsov** [comment]
Jekyll

**Comment by jrdnbrn** [comment]
When running `jekyll serve` I says 4000

**Comment by eivantsov** [comment]
OK, you need to go to Dashboard, Workspaces, select your workspace, Servers and add this server.

Once done, the workspace will be restarted. Create a command with a previwew URL using a macro

**Comment by jrdnbrn** [comment]
Add what server? 127.0.0.1:4000?

**Comment by jrdnbrn** [comment]
Below is what I did in the 'Servers' tab, but when using my run command, which is `cd ${current.project.path} && jekyll serve`, and going to the preview URL, it says that it refused to connect.

![Servers Tab](https://user-images.githubusercontent.com/32971750/32338943-a042cfaa-bfcc-11e7-83ab-b2ba92dfce33.png)

**Comment by eivantsov** [comment]
@jrdnbrn what's the preview URL macro is there?

Also, you may want to try appending `--host=0.0.0.0` to your `jekyll serve` command.

Hope it helps.

**Comment by jrdnbrn** [comment]
Adding `--host=0.0.0.0` worked! Thank you so much for your help! Could you explain why it worked though?

**Comment by eivantsov** [comment]
Jekyll runs in a Docker container, and when bound to localhost it accepts only local connections. When you try to reach it, you are coming from outside. So, unbinding server from localhost fixes the problem.
