### ISSUE TITLE
OAuth instructions Codenvy cloud to Github

### ISSUE THREAD

**Issue by Titus-Riley** [codenvy/codenvy#2516]
I am doing my best to coast by on the free options of Codenvy and Github. So I am trying to follow your instructions on how to setup OAuth from your free cloud offering of Codenvy to my Github repository. I can pull down from the repository but not push back. 

The instructions at https://codenvy.com/docs/user-guide/git-svn/index.html are not getting me there. The screenshot of the Github pages seems out of date with what I see, but my main challenge is that I do not know what to put for the <HOST_IP>:<SERVER_PORT> section of the instruction for http://<HOST_IP>:<SERVER_PORT>/wsmaster/api/oauth/callback. 

What do I put for these values for the cloud version of Codenvy?
Many thanks.

**Comment by eivantsov** [comment]
@Titus-Riley are you talking about codenvy.io or a self hosted Codenvy On Prem?

**Comment by Titus-Riley** [comment]
I am referring to codenvy.io.

I do not know what values to put for the host ip. Is there a generic value for that, or is it specific to each workspace I create, or specific to the instance of the workspace when I run it?

The Github repository I am using is just a public access repository because I am using the free version.

Many thanks
________________________________

**Comment by eivantsov** [comment]
You don't need to setup anything for GitHub. Profile - Preferences - SSH Keys - VCS. You will see GitHub icon. Click it.

**Comment by Titus-Riley** [comment]
Fantastic! Thank you!

I knew I was making life too difficult for myself.
________________________________
