### ISSUE TITLE
Troubleshooting Git Project Import via SSH

### ISSUE THREAD

**Issue by rosensama** [codenvy/codenvy#2522]
I'm test diving my first workspace and am trying to import a project from a Git repository.  How can I tell what's going wrong?

**Reproduction Steps:**
1. Add SSH key pair for hostname in profile
1. Upload public key to remote repository
1. Enter full ssh:// URL to repository
1. Click import
1. UI says it's importing, but when it finishes dialog is still open and import button is still active.
 a. there is no new project on the filesystem or listed in the workspace
 a. there are no messages, error or otherwise 

**Codenvy version:**    
5.20.0

**OS and version:**    
Windows 10 Pro 1703 15063.608

**Docker version:** 
docker: command not found from terminal

**Codenvy cli.log output:**  
couldn't find a file with this name on the filesystem

**Comment by eivantsov** [comment]
@rosensama can you share a screenshot please?

**Comment by rosensama** [comment]
@eivantsov Sure.  What would like like a screenshot of?

**Comment by eivantsov** [comment]
With import finished and dialogue opened.

**Comment by rosensama** [comment]
@eivantsov sent you an email at the address on your github profile

**Comment by eivantsov** [comment]
@rosensama when the UI says it's importing, do you see a notification with progress?

**Comment by rosensama** [comment]
Yes, I see a notification with an animated icon.

**Comment by eivantsov** [comment]
@rosensama I have hard time reproducing it. 

Can you check if a folder is created in `/projects?`

**Comment by rosensama** [comment]
It's not.   Is there somewhere I can find logs of the svn import process?

**Comment by rosensama** [comment]
What is the appropriate URL format for git over SSH w/ a cert?

**Comment by eivantsov** [comment]
Is it Git or SVN?

**Comment by rosensama** [comment]
Git

**Comment by eivantsov** [comment]
The one you use is the connect one - url are validated before you hit import button

**Comment by rosensama** [comment]
Just tried again and caught a second notification with an error message.
It took so long to appear and didn't display for long, so I might have
missed it before.  It appears as the Import button transitions back from an
animated icon to an enabled button with Import label.

It says "connection timed out"

**Comment by eivantsov** [comment]
What's IP of your server? It has to be whitelisted.

**Comment by rosensama** [comment]
I know the IP address.  Can you whitelist by domain name?  Otherwise, I can
see if the vendor has static IPs to share.

**Comment by eivantsov** [comment]
It has to be IP address

**Comment by rosensama** [comment]
They cannot guarantee permanent static IPs, but will use the following for
"the foreseeable future".

107.22.171.232, 174.129.252.219, 52.200.27.161, and 52.7.128.82

Is that something you could accomodate?

**Comment by eivantsov** [comment]
@skryzhny can you whitelist those?

**Comment by eivantsov** [comment]
@rosensama can you give it a try now? IPs have been whitelisted

**Comment by rosensama** [comment]
Thanks.  That did it.  Project is imported.
