### ISSUE TITLE
[feature request] Movable frames on mobile browsers as well

### ISSUE THREAD

**Issue by mustafa-yilmaz** [codenvy/codenvy#2525]
Hi,
Just an input to ask whether or not the Codenvy team may be able to make the frames of the IDE movable on mobile browsers just as they are already on desktop browsers as shown in the image below.

Thanks.
Mustafa

![codenvy](https://user-images.githubusercontent.com/878471/32636243-f6f941a0-c5c4-11e7-9680-e52940716ba2.gif)

**Comment by eivantsov** [comment]
@mustafa-yilmaz there are a few issues opened for Eclipse Che which Codenvy is based on: https://github.com/eclipse/che/issues/6527
https://github.com/eclipse/che/issues/6106
