### ISSUE TITLE
Process killed without messages

### ISSUE THREAD

**Issue by pgrandinetti** [codenvy/codenvy#2536]
A python script is killed without any error message apart from one string: "Killed". The script is correct (it runs with the same input in my local computer). Also, the same scripts with different inputs runs just fine in my codenvy workspace.

I apologies, but I don't even know where/how to find more information. The scripts does some heavy computation, but the behavior is odd nevertheless.
Any hints?
Thanks a lot

**Codenvy version:**    5.20.0

**OS and version:**    default machine with python3

**Comment by eivantsov** [comment]
@pgrandinetti probably OOM, and the kernel kills the process. Try allocating more RAM for your workspace.

**Comment by pgrandinetti** [comment]
yes, I logged in again and checked the syslog file
