### ISSUE TITLE
Avoid automatic logout

### ISSUE THREAD

**Issue by pgrandinetti** [codenvy/codenvy#2537]
When I leave some process running for a bit of time, at some point the workspace freezes (well, it seems it's shut down completely) and I need to start it again. I haven't been able to understand
- The moment (amount of time) after the workspace freezes
- whether the process is still running after re-starting the workspace
- most importantly, if there is a way to avoid this behavior.

Thank you!

**Codenvy version:**    5.20.0
**OS and version:**    default linux with python3

**Comment by eivantsov** [comment]
@pgrandinetti there's inactivity timeout set to 15 mins. If you do not use your workspace (the IDE) for 15 mins it's automatically stopped. Premium accounts have this cap removed.

**Comment by pgrandinetti** [comment]
Great, thanks!
