### ISSUE TITLE
Stacks based on CentOS do not start

### ISSUE THREAD

**Issue by SkorikSergey** [codenvy/codenvy#2549]
**Reproduction Steps:**
- On https://nightly-onprem.codenvy-stg.com or https://nightly.codenvy-stg.com try to create any workspace based on CentOs.

**Observed behavior:**
All stacks, that based on **CentOs**, don't start:
- **CentOs**
- **CentOS WildFly Swarm**
- **Eclipse Vert.x**
- **Java CentOS**
- **Java-MySQL CentOS**
- **Spring Boot**

**Codenvy version:** 5.22.0
**Server location**: https://nightly-onprem.codenvy-stg.com, https://nightly.codenvy-stg.com

**Additional information:**
Problem can be reliably reproduced, doesn't happen randomly: [Yes]
![screenshot-nightly-onprem codenvy-stg com-2017-11-30-15-55-20-844](https://user-images.githubusercontent.com/7760565/33434139-fb8a8f12-d5e6-11e7-9954-9dfd5270eed0.png)

**Comment by SkorikSergey** [comment]
On **Codenvy** don't start all stacks that based on CentOs:
- **CentOs**
- **CentOS WildFly Swarm**
- **Eclipse Vert.x**
- **Java CentOS**
- **Java-MySQL CentOS**
- **Spring Boot**

![codenvy wksp-jx2w - google chrome_052](https://user-images.githubusercontent.com/7760565/33262303-867133b8-d36e-11e7-85e8-716731780b4c.png)

**Comment by iotdog** [comment]
I face the same issue, is it solved?

**Comment by SkorikSergey** [comment]
Not relevant anymore. Closing.
