### ISSUE TITLE
Project deleted accidentally. Is there a way to recover it?

### ISSUE THREAD

**Issue by arunkumar413** [codenvy/codenvy#2568]
Hi Team,

I accidentally deleted a project. Is there a way to recover it? Unfortuanley I didn't have a copy of it on github. Please help me. 

Thanks,
Arun

**Comment by bmicklea** [comment]
@skryzhny can you investigate?

**Comment by arunkumar413** [comment]
@skryzhny @bmicklea

I was suggested on twitter to raise issue on eclipse/che repo. Here is the issue #7845 for your reference

**Comment by arunkumar413** [comment]
Issue solved on th ticket: https://github.com/eclipse/che/issues/7845). Please close this.
