### ISSUE TITLE
Can’t do Git pull/push requests with AWS CodeCommit repository on codenvy.io.

### ISSUE THREAD

**Issue by nigol** [codenvy/codenvy#2571]
Hello team,

since yesterday I am not able to do any Git operations with remote repository hosted on AWS CodeCommit. I am working with hosted service on codenvy.io. Error message is ‘ssh://git-codecommit.eu-west-1.amazonaws.com/v1/repos/svj: Connection timed out (Connection timed out)’. It used to be working without problems until this Monday (11th of December). Do you have any idea, why it is not working anymore?

Thanks in advance.
 Martin

**Comment by Jwilliamsr** [comment]
Any chance you guys could update the whitelist for AWS IPs? My team is having the same issue.

**Comment by eivantsov** [comment]
@Jwilliamsr @nigol whitelisting all of AWS IPs does not sound like something that @skryzhny can do. He might have other ideas though.

**Comment by skryzhny** [comment]
Whitlisted again, can you recheck?

**Comment by nigol** [comment]
skryzhny: Thanks, now it is working again.
