### ISSUE TITLE
Issue previewing apache2 page

### ISSUE THREAD

**Issue by samr28** [codenvy/codenvy#2574]
New codenvy user here. Really liking it so far. So I am developing an application using php and thus, apache2. I have installed apache2 with apt. Apache defaults to port 80 (I double checked in the config file). I then went and made a preview command as the guide here showed: https://codenvy.com/docs/user-guide/previews/index.html. I just wanted to see the default index.html page which is in the correct dir for apache2 (/var/www/html). Everything looks the same, my servers tab shows the http (apache) server in it but when I click the link, I get an ERR_CONNECTION_REFUSED form chrome. I have checked on the server with `sudo status apache2 status` which returns that it is running.

**Codenvy version:**    Not sure where to type this in... My dashboard doesn't have a place to enter text, just shows my projects and stuff. It should be the newest as I just created this workspace today.

**OS and version:**    

**Docker version:** See above

**Codenvy cli.log output:**  bash: cd: /data: No such file or directory

**Comment by eivantsov** [comment]
@samr28 can you make sure the ephemeral port range isn't filtered?

**Comment by samr28** [comment]
I was able to fix this by creating a new workspace with the PHP template. I'm not sure what I did wrong the first time but I'll try to do some investigating when I get the chance.
