### ISSUE TITLE
Postflight checks [NOT OK]

### ISSUE THREAD

**Issue by adnanshaheen** [codenvy/codenvy#2577]
Codenvy is started but something went wrong, fail with postflight checks, hence can't create workspace. Firewall is completely off.
 (13.59.4.51:23750/info):  [NOT OK]

ERROR: Could not reach all Swarm nodes - workspaces may not start.
ERROR:   1. Are the swarm ports open on your firewall?
ERROR:   2. Did the Docker daemon fail to start on any node?
ERROR:   3. Are the swarm entries entered properly in codenvy.env?

**Reproduction Steps:**
git clone github.com/codenvy/codenvy.git
cd codenvy/assembly/assembly-main
mvn clean install
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/domani-inc:/data -e CODENVY_HOST=13.59.4.51 -e CHE_DOCKER_MACHINE_HOST=13.59.4.51 codenvy/cli start

**Codenvy version:**    latest

**OS and version:**    #50-Ubuntu SMP Wed Nov 15 22:18:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Docker version:** Docker version 1.13.1, build 092cba3  

**Codenvy cli.log output:** 
Sat Dec 16 03:40:27 UTC 2017
/usr/bin/curl  "-I -k https://hub.docker.com -s -o /dev/null --write-out %{http_code}"
Checking registry for version '5.22.0' images
eval BOOTSTRAP_IMAGE_ALPINE=${BOOTSTRAP_IMAGE_ALPINE:-alpine:3.4}
eval BOOTSTRAP_IMAGE_CHEIP=${BOOTSTRAP_IMAGE_CHEIP:-eclipse/che-ip:5.22.0}
eval IMAGE_HAPROXY=${IMAGE_HAPROXY:-haproxy:1.5.18-alpine}
eval IMAGE_NGINX=${IMAGE_NGINX:-nginx:1.10-alpine}
eval IMAGE_REGISTRY=${IMAGE_REGISTRY:-registry:2.5.0}
eval IMAGE_COMPOSE=${IMAGE_COMPOSE:-docker/compose:1.8.1}
eval IMAGE_ZOOKEEPER=${IMAGE_ZOOKEEPER:-zookeeper:3.4.9}
eval IMAGE_SWARM=${IMAGE_SWARM:-codenvy/swarm:5.22.0}
eval IMAGE_SOCAT=${IMAGE_SOCAT:-codenvy/socat:5.22.0}
eval IMAGE_INIT=${IMAGE_INIT:-codenvy/init:5.22.0}
eval IMAGE_AGENTS=${IMAGE_AGENTS:-codenvy/agents:5.22.0}
eval IMAGE_CODENVY=${IMAGE_CODENVY:-codenvy/codenvy:5.22.0}
eval IMAGE_RSYSLOG=${IMAGE_RSYSLOG:-codenvy/rsyslog:5.22.0}
eval UTILITY_IMAGE_CHEACTION=${UTILITY_IMAGE_CHEACTION:-eclipse/che-action:5.22.0}
eval UTILITY_IMAGE_CHEDIR=${UTILITY_IMAGE_CHEDIR:-eclipse/che-dir:5.22.0}
eval UTILITY_IMAGE_CHETEST=${UTILITY_IMAGE_CHETEST:-eclipse/che-test:5.22.0}
eval UTILITY_IMAGE_CHEMOUNT=${UTILITY_IMAGE_CHEMOUNT:-eclipse/che-mount:5.22.0}
INFO: (codenvy cli):  5.22.0 - using docker 1.13.1 / native
/usr/bin/curl  "-s https://hub.docker.com/v2/repositories/codenvy/cli/tags/"
docker inspect -f '{{.Id}}' codenvy_codenvy_1
/usr/bin/curl  "-I -k 13.59.4.51/api/ -s -o /dev/null --write-out %{http_code}"
000
\033[0;32mINFO:\033[0m (codenvy download): Checking for image 'haproxy:1.5.18-alpine'... found
\033[0;32mINFO:\033[0m (codenvy download): Checking for image 'nginx:1.10-alpine'... found
\033[0;32mINFO:\033[0m (codenvy download): Checking for image 'registry:2.5.0'... found
\033[0;32mINFO:\033[0m (codenvy download): Checking for image 'docker/compose:1.8.1'... found
\033[0;32mINFO:\033[0m (codenvy download): Checking for image 'zookeeper:3.4.9'... found
\033[0;32mINFO:\033[0m (codenvy download): Checking for image 'codenvy/swarm:5.22.0'... found
\033[0;32mINFO:\033[0m (codenvy download): Checking for image 'codenvy/socat:5.22.0'... found
\033[0;32mINFO:\033[0m (codenvy download): Checking for image 'codenvy/init:5.22.0'... found
\033[0;32mINFO:\033[0m (codenvy download): Checking for image 'codenvy/agents:5.22.0'... found
\033[0;32mINFO:\033[0m (codenvy download): Checking for image 'codenvy/codenvy:5.22.0'... found
\033[0;32mINFO:\033[0m (codenvy download): Checking for image 'codenvy/rsyslog:5.22.0'... found
\033[0;32mINFO:\033[0m (codenvy download): Checking for image 'alpine:3.4'... found
\033[0;32mINFO:\033[0m (codenvy download): Checking for image 'eclipse/che-ip:5.22.0'... found
\033[0;32mINFO:\033[0m (codenvy download): Checking for image 'eclipse/che-action:5.22.0'... found
\033[0;32mINFO:\033[0m (codenvy download): Checking for image 'eclipse/che-dir:5.22.0'... found
\033[0;32mINFO:\033[0m (codenvy download): Checking for image 'eclipse/che-test:5.22.0'... found
\033[0;32mINFO:\033[0m (codenvy download): Checking for image 'eclipse/che-mount:5.22.0'... found
INFO: (codenvy init):  Installing configuration and bootstrap variables:
mkdir -p "/data"
mkdir -p "/data/instance"
docker_run -v "/home/domani-inc":/copy  codenvy/init:5.22.0
INFO: (codenvy init):    CODENVY_HOST=13.59.4.51
INFO: (codenvy init):    CODENVY_VERSION=5.22.0
INFO: (codenvy init):    CODENVY_CONFIG=/home/domani-inc
INFO: (codenvy init):    CODENVY_INSTANCE=/home/domani-inc/instance
INFO: (codenvy config):  Generating codenvy configuration...
DEBUG: generate_configuration_with_puppet
docker_run                   --env-file="/data/codenvy.env"                   --env-file=/version/5.22.0/images                   -v "/home/domani-inc/instance":/opt/codenvy:rw                    -e "CODENVY_HOST=13.59.4.51" -e "CHE_DOCKER_MACHINE_HOST=13.59.4.51"                   -e "POSTGRES_ENV_FILE=/home/domani-inc/instance/config/postgres/postgres.env"                   -e "CODENVY_ENV_FILE=/home/domani-inc/instance/config/codenvy/codenvy.env"                   -e "CHE_CONTAINER_ROOT=/data"                   -e "CHE_ENVIRONMENT=production"                   -e "CHE_CONFIG=/home/domani-inc/instance"                   -e "CHE_INSTANCE=/home/domani-inc/instance"                   -e "CHE_REPO=off"                   --entrypoint=/usr/bin/puppet                       codenvy/init:5.22.0                           apply --modulepath                                 /etc/puppet/modules/:/etc/puppet/addon/                                 /etc/puppet/manifests/ --show_diff >> "/data/cli.log"
Notice: Compiled catalog for 1ff66d2bf576.us-east-2.compute.internal in environment production in 0.57 seconds
Notice: /Stage[main]/Base/File[/opt/codenvy/data]/ensure: created
Notice: /Stage[main]/Base/File[/opt/codenvy/config]/ensure: created
Notice: /Stage[main]/Base/File[/opt/codenvy/logs]/ensure: created
Notice: /Stage[main]/Base/File[/opt/codenvy/logs/zookeeper]/ensure: created
Notice: /Stage[main]/Haproxy/File[/opt/codenvy/config/haproxy]/ensure: created
Notice: /Stage[main]/Haproxy/File[/opt/codenvy/config/haproxy/haproxy.cfg]/ensure: defined content as '{md5}b3cb0901b4d9a594df798b088144d938'
Notice: /Stage[main]/Haproxy/File[/opt/codenvy/config/haproxy/maintenance.html]/ensure: defined content as '{md5}47534e2a73dfd698f919e8649fbe51e2'
Notice: /Stage[main]/Nginx/File[/opt/codenvy/config/nginx]/ensure: created
Notice: /Stage[main]/Nginx/File[/opt/codenvy/config/nginx/nginx.conf]/ensure: defined content as '{md5}6fbb89966176c3a76967225ebb5bde0e'
Notice: /Stage[main]/Postgres/File[/opt/codenvy/config/postgres]/ensure: created
Notice: /Stage[main]/Postgres/File[/opt/codenvy/config/postgres/postgresql.conf]/ensure: defined content as '{md5}e90e6c32c3265a0e58b933ae1094b290'
Notice: /Stage[main]/Postgres/File[/opt/codenvy/config/postgres/postgres.env]/ensure: defined content as '{md5}815726f095a7d112897d37d6611941ee'
Notice: /Stage[main]/Swarm/File[/opt/codenvy/config/swarm]/ensure: created
Notice: /Stage[main]/Swarm/File[/opt/codenvy/config/swarm/node_list]/ensure: defined content as '{md5}c9daa829c27a76c62f9c6461741cb4ed'
Notice: /Stage[main]/Swarm/File[/opt/codenvy/config/swarm/swarm_entrypoint.sh]/ensure: defined content as '{md5}6679d451acf330840b72e5d462e29cee'
Notice: /Stage[main]/Registry/File[/opt/codenvy/config/registry]/ensure: created
Notice: /Stage[main]/Registry/File[/opt/codenvy/config/registry/config.yml]/ensure: defined content as '{md5}9ce2881a150def983614c81282df29f9'
Notice: /Stage[main]/Registry/File[/opt/codenvy/config/registry/registry_entrypoint.sh]/ensure: defined content as '{md5}6310969162049a6921fcaf114d3b8c79'
Notice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/]/ensure: created
Notice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf]/ensure: created
Notice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/ssh]/ensure: created
Notice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/logback]/ensure: created
Notice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/server.xml]/ensure: defined content as '{md5}11b2dec50521643a4e609c286e4a92ea'
Notice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/codenvy.env]/ensure: defined content as '{md5}c36d2a6050a547797b4cf4f2b1d4c0dc'
Notice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/oauth.properties]/ensure: defined content as '{md5}8c76872fe573f470aa7f068a4e4c04d2'
Notice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/email-connection.properties]/ensure: defined content as '{md5}38933f0b64e84f980f510ba0bd040573'
Notice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/email.properties]/ensure: defined content as '{md5}ec46f3418443acfde1f06552cc0e53b4'
Notice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/logback/logback-additional-appenders.xml]/ensure: defined content as '{md5}f55efcc20c4a8c524c323d4831181ffb'
Notice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/general.properties]/ensure: defined content as '{md5}c6c62772bff4f5107886c74b0d91d6a5'
Notice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/metrics.properties]/ensure: defined content as '{md5}e4a4ba9f02406b0b55218ef81743ea11'
Notice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/everrest.properties]/ensure: defined content as '{md5}dc2d611d1df898e9f95bb78bdc771371'
Notice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/machine.properties]/ensure: defined content as '{md5}cba3d1dbe551e43b40a41cc8430a5b86'
Notice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/admin.properties]/ensure: defined content as '{md5}a1b947c4a0a4d1e629bebdc74d1d8d73'
Notice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/report.properties]/ensure: defined content as '{md5}79cab3588664e7753721c2079219108e'
Notice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/ldap.properties]/ensure: defined content as '{md5}841ca04fc0be9fcc4768ed5dd9dfe92d'
Notice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/rsyncbase.sh]/ensure: defined content as '{md5}9d04a5445b7f1cb3dd4e85875e9ae163'
Notice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/rsyncbackup.sh]/ensure: defined content as '{md5}e619d0433abcbb2ebcd20efb6b32fd80'
Notice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/rsyncrestore.sh]/ensure: defined content as '{md5}c2cc16aa99d8eae8bd545af551a1a08a'
Notice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/add-node.sh]/ensure: defined content as '{md5}356a09f9d4def49192ff1dbeaa8a63d6'
Notice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/jmxremote.access]/ensure: defined content as '{md5}a951b5b6624cad3b0ec555c40d624a9c'
Notice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/jmxremote.password]/ensure: defined content as '{md5}cb05d0ae49d28c22a21ccc874c6688c6'
Notice: /Stage[main]/Codenvy/Exec[generate_ssh_key]/returns: executed successfully
Notice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/cleanUpWorkspaceStorage.sh]/ensure: defined content as '{md5}4cd140e8dde3e86703719062e82ec454'
Notice: /Stage[main]/Codenvy/File[/opt/codenvy/config/codenvy/conf/user-mail-blacklist.txt]/ensure: defined content as '{md5}d41d8cd98f00b204e9800998ecf8427e'
Notice: /Stage[main]/Rsyslog/File[/opt/codenvy/config/rsyslog]/ensure: created
Notice: /Stage[main]/Rsyslog/File[/opt/codenvy/config/rsyslog/rsyslog.conf]/ensure: defined content as '{md5}78b6c428785475d9f632a571c9755c45'
Notice: /Stage[main]/Rsyslog/File[/opt/codenvy/config/rsyslog/haproxy.conf]/ensure: defined content as '{md5}386dca312192c0fd0d1a0cff7a020645'
Notice: /Stage[main]/Lighttpd/File[/opt/codenvy/config/lighttpd]/ensure: created
Notice: /Stage[main]/Lighttpd/File[/opt/codenvy/config/lighttpd/lighttpd.conf]/ensure: defined content as '{md5}df36baf11e4da58f17dd9ef0e8ca8bcc'
Notice: /Stage[main]/Compose/Compose::Generate_compose_file[docker-compose-container.yml]/File[/opt/codenvy/docker-compose-container.yml]/ensure: defined content as '{md5}77fabe3ddd32bf6444a5f5ec8a4c7851'
Notice: /Stage[main]/Compose/Compose::Generate_compose_file[docker-compose.yml]/File[/opt/codenvy/docker-compose.yml]/ensure: defined content as '{md5}a30edcb26ef59ee78822343a9ecf214e'
Notice: Applied catalog in 0.45 seconds
INFO: (codenvy config):  Customizing docker-compose for running in a container
INFO: (codenvy start):  Preflight checks
         mem (1.5 GiB):           [OK]
         disk (100 MB):           [OK]
         port 80 (http):          [AVAILABLE]
         port 443 (https):        [AVAILABLE]
         port 2181 (zookeeper):   [AVAILABLE]
         port 5000 (registry):    [AVAILABLE]
         port 23750 (socat):      [AVAILABLE]
         port 23751 (swarm):      [AVAILABLE]
         port 32000 (jmx):        [AVAILABLE]
         port 32001 (jmx):        [AVAILABLE]
963e2c46d8a1ed5b1889b62809283c14d916544d3c2207366f4094667e055677
/usr/bin/curl  "-I localhost:32768/alpine-release -s -o /dev/null --connect-timeout 5 --write-out %{http_code}"
28
/usr/bin/curl  "-I 13.59.4.51:32768/alpine-release -s -o /dev/null --connect-timeout 5 --write-out %{http_code}"
         conn (browser => ws):    [OK]
         conn (server => ws):     [OK]
fakeagent-80

INFO: (codenvy start):  Starting containers...
docker_compose --file="/data/instance/docker-compose-container.yml" -p="codenvy" up -d >> "/data/cli.log" 2>&1
Creating codenvy_zookeeper_1
Creating codenvy_nginx_1
Creating codenvy_rsyslog_1
Creating codenvy_socat_1
Creating codenvy_postgres_1
Creating codenvy_agents_1
Creating codenvy_registry_1
Creating codenvy_swarm_1
Creating codenvy_haproxy_1
Creating codenvy_codenvy_1
docker inspect -f '{{.Id}}' codenvy_codenvy_1
INFO: (codenvy start):  Services booting...
INFO: (codenvy start):  Server logs at "docker logs -f codenvy_codenvy_1"
DEBUG: Container with id 343cdf8a70d0 is matching zookeeper service
DEBUG: Running state of container 343cdf8a70d0 is true
DEBUG: Container with id 1a07455f1c47 is matching postgres service
DEBUG: Running state of container 1a07455f1c47 is true
DEBUG: Container with id 34e137c36562 is matching nginx service
DEBUG: Running state of container 34e137c36562 is true
DEBUG: Container with id e7158c967300 is matching agents service
DEBUG: Running state of container e7158c967300 is true
DEBUG: Container with id 1e1fef396ddd is matching registry service
DEBUG: Running state of container 1e1fef396ddd is true
DEBUG: Container with id 5a5fe0417faa is matching rsyslog service
DEBUG: Running state of container 5a5fe0417faa is true
DEBUG: Container with id a3e0c919f955 is matching haproxy service
DEBUG: Running state of container a3e0c919f955 is true
DEBUG: Container with id 762376d37b9b is matching socat service
DEBUG: Running state of container 762376d37b9b is true
DEBUG: Container with id 8352cbe0e9e3 is matching swarm service
DEBUG: Running state of container 8352cbe0e9e3 is true
DEBUG: Container with id 21afe87e224e is matching codenvy service
DEBUG: Running state of container 21afe87e224e is true
/usr/bin/curl  "-I -k 13.59.4.51/api/ -s -o /dev/null --write-out %{http_code}"
000
sleep 2
/usr/bin/curl  "-I -k 13.59.4.51/api/ -s -o /dev/null --write-out %{http_code}"
000
sleep 2
/usr/bin/curl  "-I -k 13.59.4.51/api/ -s -o /dev/null --write-out %{http_code}"
000
sleep 2
/usr/bin/curl  "-I -k 13.59.4.51/api/ -s -o /dev/null --write-out %{http_code}"
000
sleep 2
/usr/bin/curl  "-I -k 13.59.4.51/api/ -s -o /dev/null --write-out %{http_code}"
200
DEBUG: Container with id 343cdf8a70d0 is matching zookeeper service
DEBUG: Running state of container 343cdf8a70d0 is true
DEBUG: Container with id 1a07455f1c47 is matching postgres service
DEBUG: Running state of container 1a07455f1c47 is true
DEBUG: Container with id 34e137c36562 is matching nginx service
DEBUG: Running state of container 34e137c36562 is true
DEBUG: Container with id e7158c967300 is matching agents service
DEBUG: Running state of container e7158c967300 is true
DEBUG: Container with id 1e1fef396ddd is matching registry service
DEBUG: Running state of container 1e1fef396ddd is true
DEBUG: Container with id 5a5fe0417faa is matching rsyslog service
DEBUG: Running state of container 5a5fe0417faa is true
DEBUG: Container with id a3e0c919f955 is matching haproxy service
DEBUG: Running state of container a3e0c919f955 is true
DEBUG: Container with id 762376d37b9b is matching socat service
DEBUG: Running state of container 762376d37b9b is true
DEBUG: Container with id 8352cbe0e9e3 is matching swarm service
DEBUG: Running state of container 8352cbe0e9e3 is true
DEBUG: Container with id 21afe87e224e is matching codenvy service
DEBUG: Running state of container 21afe87e224e is true
docker inspect -f '{{.Id}}' codenvy_codenvy_1
/usr/bin/curl  "-I -k 13.59.4.51/api/ -s -o /dev/null --write-out %{http_code}"
200
INFO: (codenvy start):  Postflight checks
/usr/bin/curl  "-s 13.59.4.51:23750/info -o /dev/null --write-out %{http_code}"
         (13.59.4.51:23750/info):  [NOT OK]

ERROR: Could not reach all Swarm nodes - workspaces may not start.
ERROR:   1. Are the swarm ports open on your firewall?
ERROR:   2. Did the Docker daemon fail to start on any node?
ERROR:   3. Are the swarm entries entered properly in codenvy.env?

docker inspect -f '{{.Id}}' codenvy_codenvy_1
/usr/bin/curl  "-I -k 13.59.4.51/api/ -s -o /dev/null --write-out %{http_code}"
200
INFO: (codenvy start):  Booted and reachable
INFO: (codenvy start):  Ver: 5.22.0
INFO: (codenvy start):  Use: http://13.59.4.51:80
INFO: (codenvy start):  API: http://13.59.4.51:80/swagger

**Comment by eivantsov** [comment]
@adnanshaheen you need to open port 23750 as well as the ephemeral port range.

**Comment by adnanshaheen** [comment]
But firewall is inactive. So what else I have to do?

**Comment by adnanshaheen** [comment]
OS firewall is inactive. The OS is in AWS. I have enabled the ports in security group. But still have the same issue.

**Comment by adnanshaheen** [comment]
The problem is fixed. For some reason, 'CODENVY_HOST=13.58.186.164' from command line overriding 'CODENVY_HOST=18.217.115.222' from codenvy.env, CODENVY_HOST remaind to old IP. So giving the same problem.
So now the question is, why the command is not overriding the CODENVY_HOST in codenvy.env?
