### ISSUE TITLE
does ssh not working on codenvy ide?

### ISSUE THREAD

**Issue by sanjaygir** [codenvy/codenvy#2589]
When i run 

`ssh server.com
`

It hangs forever. I am wondering whether ssh is not allowed?

**Comment by eivantsov** [comment]
You need to ssh to your particular workspace. There's ssh button in the processes panel

**Comment by sanjaygir** [comment]
sorry i will clarify my question. I know that i can access my workspace. My question is whether it is possible to ssh from the workspace to another external server. In the terminal in my workspace can i run the command ssh myexternalserver.com? Can this succeed? Thanks!

**Comment by eivantsov** [comment]
@sanjaygir we need to whitelist your IP then.

**Comment by sanjaygir** [comment]
if that can be done then i can switch back to codenvy. can you please whitelist karaokesagar.com?

**Comment by eivantsov** [comment]
@sanjaygir can you give it a try now?

**Comment by sanjaygir** [comment]
great! thanks it is now working.

**Comment by sanjaygir** [comment]
problem solved!
