### ISSUE TITLE
Create the list of features which are not covered by functional tests

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#2604]
On this moment we have more than 500 E2E tests that cover main functional units. But some new features still not covered, We should find this one and add to list for  watching.

**Comment by SkorikSergey** [comment]
Not covered features on Dashboard:
- the **Diagnostic** feature(for Che 6.2.0 it doesn't work - https://github.com/eclipse/che/issues/8501);
- Che documentation;
- a stack details page;
- a factory details page;
- **Config** tab on workspace details page.

**Comment by musienko-maxim** [comment]
Duplicated
