### ISSUE TITLE
Can't install Codenvy

### ISSUE THREAD

**Issue by Dog2puppy** [codenvy/codenvy#2607]
When trying to install Codenvy using `docker run codenvy/cli start` I get an error. 

**Reproduction Steps:**
1. Install Ubuntu 16.04
2. Install Docker
3. Run `docker run codenvy/cli start`

**Codenvy version:** None   

**OS and version:** Ubuntu 16.04   

**Docker version:** 

```
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:11:19 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:09:53 2017
  OS/Arch:      linux/amd64
  Experimental: false
```

   

**Codenvy cli.log output:** None(?)

**Comment by eivantsov** [comment]
@Dog2puppy do share more details about an error.

**Comment by Dog2puppy** [comment]
I ended up fixing it. It was something about a docker.sock file I think.
