### ISSUE TITLE
I can't SSH to CodeCommit 

### ISSUE THREAD

**Issue by CodenvLover** [codenvy/codenvy#2612]
Hi,
I get a connection timeout when I try to ssh to my repo on us-east-1 region,
Any Idea?

**Comment by eivantsov** [comment]
@CodenvLover we need to whitelist your server IP.

**Comment by CodenvLover** [comment]
@eivantsov here is the host I'm trying to ssh to  git-codecommit.us-east-1.amazonaws.com

**Comment by CodenvLover** [comment]
Any Updates

**Comment by skryzhny** [comment]
Whitelisted, please recheck.

**Comment by CodenvLover** [comment]
I still get connection timeout, git clone ssh://git-codecommit.us-east-1.amazonaws.com/v1/repos/SampleRepository

**Comment by skryzhny** [comment]
It works for me.
Can you attach screenshot?

**Comment by CodenvLover** [comment]
Yeah, it's working 
Thank you so much

**Comment by scrong1** [comment]
> @CodenvLover we need to whitelist your server IP.

how can i give codenvy my ip?email?email adress is?
