### ISSUE TITLE
node_modules folder disappears when booting workspace

### ISSUE THREAD

**Issue by DimitrK** [codenvy/codenvy#2616]
Whenever I boot the workspace the `node_modules` folder isn't there although I did `npm install` in a previous session. I have to run `npm install` all over again each time

**Reproduction Steps:**
I am going to describe the things I did here:

1. Created a new stack
```
{
  "name": "Node-8-LTS",
  "id": "stackuiispv469xg5wafm",
  "source": {
    "type": "image",
    "origin": "eclipse/node"
  },
  "description": "Default Node Stack with Node 8 .",
  "scope": "general",
  "tags": [
    "Ubuntu",
    "Git",
    "Node.JS",
    "NPM"
  ],
  "creator": "userdh94w31401lheng1",
  "workspaceConfig": {
    "name": "default",
    "commands": [],
    "projects": [],
    "environments": {
      "default": {
        "recipe": {
          "location": "eclipse/node",
          "type": "dockerimage"
        },
        "machines": {
          "dev-machine": {
            "attributes": {
              "memoryLimitBytes": "2147483648"
            },
            "servers": {},
            "agents": [
              "org.eclipse.che.exec",
              "org.eclipse.che.terminal",
              "org.eclipse.che.ws-agent",
              "org.eclipse.che.ssh"
            ]
          }
        }
      }
    },
    "defaultEnv": "default",
    "links": []
  },
  "components": [
    {
      "name": "Node.JS",
      "version": "8.9.4"
    },
    {
      "name": "NPM",
      "version": "5.6.0"
    }
  ]
}
```

***Notice*** _Although I did specify different NodeJS & NPM versions that didn't do the trick. I still was running the versions provided on default Node stack (Node: 7.7.3, NPM: 4.4.1)_

2. I cloned a project from bitbucket through a HTTPS link & granted access to codenvy.

3. Navigated to project folder and run `npm install`.

Everything was done and I was able to run a server. Each time I am booting the workspace eversince I  have to install node_modules all over again.

**Codenvy version:**    Online codenvy editor

**Comment by eivantsov** [comment]
@DimitrK project backup mechanism in Codenvy uses rsync that respects .gitignore.

**Comment by CodenvLover** [comment]
hello, @eivantsov I didn't receive any updates about this 
[issue] (https://github.com/codenvy/codenvy/issues/2612)
Could please help?
