### ISSUE TITLE
Unable to edit the .js files in a blank stack

### ISSUE THREAD

**Issue by arunkumar413** [codenvy/codenvy#2631]
Hi Team,

I'm not able to edit the JavaScript files in a blank stack. The editor pane doesn't show up when double clicked on the file in the side bar.

![js](https://user-images.githubusercontent.com/7776779/36720809-1346cad4-1bcf-11e8-9329-05412d1bd45a.png)

**Comment by commd** [comment]
Was this issue resolved?

**Comment by arunkumar413** [comment]
@commd I'm no longer using code evny. Shifted to desktop based tools instead. Please feel free to close this ticket
