### ISSUE TITLE
I can't delete command from commands explorer neither from command pallete

### ISSUE THREAD

**Issue by andreSants** [codenvy/codenvy#2635]
There is no way to delete commands on the IDE or using the terminal that I am aware of.
On right click of mouse no menu shows up.

Go to commands explorer, try to delete using delete key on keyboard or right click of the mouse does not open a menu.

Codenvy version 5.22.2
"linux", version: "3.10.0-693.17.1.el7.x86_64", arch: "amd64"

**Comment by bobbyb2024** [comment]
When looking at the Run Commands window, there is a minus sign icon at the far right of the column, this will remove a command from the commands explorer.  However, commands can also be defined in your Workspace Config of your actual workspace.  IE, go to the dashboard, click configure workspace, choose the config tab and you can see where the commands are defined.

**Comment by andreSants** [comment]
I was able to do it using the config tab. The Run Commands window does not have this minus sign on my workspace as shown in the image.
thanks a lot for your help.
![commandwindom](https://user-images.githubusercontent.com/36920077/36974516-d9cefb06-206e-11e8-8ff7-987c57c3b257.png)

**Comment by ypajiec** [comment]
It's repeated in Firefox
In Chromium all fine
