### ISSUE TITLE
Installation is not working for me

### ISSUE THREAD

**Issue by juulliian** [codenvy/codenvy#2644]
When I try to install codenvy with `docker run codenvy/cli start` the following error occurs:

```
INFO: Welcome to Codenvy!
INFO: 
INFO: You are missing a mandatory parameter:
INFO:    1. Mount 'docker.sock' for accessing Docker with unix sockets.
INFO:    2. Or, set DOCKER_HOST to Docker's location (unix or tcp).
INFO: 
INFO: Mount Syntax:
INFO:    Start with 'docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock' ...
INFO: 
INFO: DOCKER_HOST Syntax:
INFO:    Start with 'docker run -it --rm -e DOCKER_HOST=<daemon-location> ...'
INFO: 
INFO: Possible root causes:
INFO:    1. Your admin has not granted permissions to /var/run/docker.sock.
INFO:    2. You passed '--user uid:gid' with bad values.
INFO:    3. Your firewall is blocking TCP ports for accessing Docker daemon.
```
I already turned off my firewall and granted permissions to `/var/run/docker.sock`. I use an account with full permissions.

I'm on Debian 8.10 and Docker Version is 
Client:
 Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.9.4
 Git commit:	7390fc6
 Built:	Tue Feb 27 22:17:57 2018
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.1-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	7390fc6
  Built:	Tue Feb 27 22:16:30 2018
  OS/Arch:	linux/amd64
  Experimental:	false

**Comment by ghost** [comment]
@Julian135 do you have `-v /var/run/docker.sock:/var/run/docker.sock` in your run syntax?
