### ISSUE TITLE
Workspace can not be opened

### ISSUE THREAD

**Issue by rokibhasansagar** [codenvy/codenvy#2672]
The Codenvy [Web IDE](https://codenvy.io/dashboard/#/) can not load any workspace, but making/editing the workspace is possible.

I tried "Self Diagnostics" to check if something wrong on my side,
It gave me the error "Workspace Tests Connectivity checks to Dockerized workspaces : ERROR" and "Error while starting the workspace : Workspace has been destroyed"

I created and started many workspaces, but they can not load/open for use.
It is happening for almost three days.

The Self Diagnostics log output can be seen here: https://pastebin.com/raw/zuzWiqjr

**Comment by rokibhasansagar** [comment]
For two days, "https://codenvy.io/_app/89DCC19D33BB1FCE36EEA76C880C3366.cache.js" is taking like forever to download (minimum 320 seconds, but still not getting complete file) and load into browser in the Web IDE.

__Info: Maximum size of the script I got is 6,467,184 bytes and total characters are 6,467,184. I guess this is not the complete file.__
(Using Firefox 60 in Windows 10 x64 RS3, and 2mbps broadband internet)

Without loading the script, I can not start work, despite the workspace being started.

Why that much data on a single script?
Why not load multiple scripts for easy and faster loading?

**Comment by AdroitAdorKhan** [comment]
Maybe it's your Browser/Internet Issue. I have been using on a 2mbps line too, and sometimes it doesn't want to load. You might clear your browser's cache.

Try using Google Chrome, and check if any other device/app eating your bandwidth!

**Comment by rokibhasansagar** [comment]
Thanks @AdroitAdorKhan for the reply.
But there was no other app running during the issue and bandwidth was also being using only by Firefox.
During issue, I tried from my phone also, but the problem remained.

Update: Today after several attempts and long wait of 30 minutes, my workspace got fully loaded.
But again, now at this moment, it is taking too very much time and still not loading.

**Comment by AdroitAdorKhan** [comment]
Then, it could be a problem with your ISP. Better contact them, if they had blocked any domain or resource that might be required to run Codenvy. 

Try on a different network or using VPN.
