### ISSUE TITLE
Do we have a helm chart with it?

### ISSUE THREAD

**Issue by LinuxSuRen** [codenvy/codenvy#2725]

**Comment by sr229** [comment]
Heya, Codenvy is no longer maintained. As referencing the Eclipse Che team:

> All of the enterprise features are now in Eclipse Che, and Codenvy will be shutdown 
> once user migration to `che.openshift.io` has been done.

I suggest using Che's Helm chart instead.

**Comment by LinuxSuRen** [comment]
Thanks for your response.
