### ISSUE TITLE
Is  Codenvy support TLSv1.2?

### ISSUE THREAD

**Issue by basictomonokai** [codenvy/codenvy#2735]
Is  Codenvy support TLSv1.2?

Bitbucket is disable support for TLSv1 and TLSv1.1 effective 1 December 2018.

Console message is follows.

> remote: Bitbucket Cloud will be disabling support for TLSv1 and TLSv1.1 effective 1 December 2018.
> remote: Please make sure your TLS version is updated.
> remote: For more info: https://bitbucket.org/blog/deprecating-tlsv1-tlsv1-1-2018-12-01
> To https://bitbucket.org/xxxx/xxxx.bitbucket.io.git

I used Git on Codeenvy and cloned Bitbucket repositry.

What i should to do something?
*My wksp is wksp-95lf.

Please tell me.

**Reproduction Steps:**

**Codenvy version:**    5.22.1

**OS and version:**    Ubuntu 16.04.4 LTS

**Docker version:** ???

**Comment by sr229** [comment]
Codenvy is based on a legacy Eclipse Che (v5.x), so I think there's a lot of upstream changes that were not mainlined to Codenvy that are in Eclipse Che. I suggest signing up for OpenShift.io instead.

**Comment by basictomonokai** [comment]
> Codenvy is based on a legacy Eclipse Che (v5.x), so I think there's a lot of upstream changes that were not mainlined to Codenvy that are in Eclipse Che. I suggest signing up for OpenShift.io instead.

Thank you for suggestion.

Yesterday,I tried access git from codenvy to bitbucket.

Result is ok.

I think codenvy is supported TLSv1.2.
