### ISSUE TITLE
Network connectivity issue

### ISSUE THREAD

**Issue by uBlock-user** [codenvy/codenvy#2742]
Can't connect to the SA-MP game-server I'm running at 52.207.182.18:7777, what do I need to do to make it work ?

**OS and version:**    Ubuntu latest version

**Docker version:** <!--- docker not found  

**Codenvy cli.log output:**  dont know what that is

**Comment by http403** [comment]
You're in the wrong place I believe.

**Comment by uBlock-user** [comment]
The VM doesn't have network connectivity so I can't connect to my game server that's an issue for me.

**Comment by http403** [comment]
I don't get it. Can you clarify how your game server related to Codenvy?

**Comment by uBlock-user** [comment]
I run a virtual machine on Codenvy.io, and installed a game server, everything went fine and but I can't connect to the game-server in my sa-mp client software because there's no UDP port connectivity. What's not to get ? Please don't argue on this any further, unless you know the so called "right place". I'm looking for a solution, not a debate on this.
