### ISSUE TITLE
Existing workspaces taking 10+ minutes to load after being stopped

### ISSUE THREAD

**Issue by mpouttuclarke** [codenvy/codenvy#303]
It is taking 10+ minutes to start an existing workspace on the Codenvy Beta while it only takes a couple of seconds to start Che on a local machine after first install. This is unacceptable as Che should have better performance on a server class machine than on a local host. It appears that perhaps the caching features of Docker aren't being used properly or are being bypassed by the Codenvy infrastructure.

For caching best practices:
https://www.ctl.io/developers/blog/post/more-docker-image-cache-tips/

There are also documented issues with Vagrant and Docker, and led to the development of vagrant-cachier. It is actually guaranteed to reduce the amount of coffee consumed while waiting for docker images to load on Vagrant:
http://fgrehm.viewdocs.io/vagrant-cachier/

Also, an apt-cache proxy would help speed the initial installation for any Debian clones:
https://help.ubuntu.com/community/AptProxy

**Comment by mpouttuclarke** [comment]
Also, there may be some load balancer configs to touch in order to ensure maximum host stickiness so that the cache is re-used:
http://rancher.com/the-magical-moment-when-container-load-balancing-meets-service-discovery/

**Comment by mpouttuclarke** [comment]
You can also configure a Squid caching proxy to help speed up some of the less evolved members of the ecosystem such as CentOS and Maven:
http://serverfault.com/questions/580712/how-to-create-yum-cache-server-for-client-machines-in-lan 
 (the LB can usually do this too)

**Comment by TylerJewell** [comment]
To help with the analysis, the engineers will want to do analytics to get data to understand the scenario and the various tiers of work that is being done.  There could be multiple issues:
- recovering from the snapshot
- big projects folder that makes projects recovering slow
- building from docker recipe that has a lot of commands 

Whatever you can provide on the sequence, the image, etc will help.  I would say that we need some sort of analytics of the slowness to find the specific cases where Codenvy is not fast enough and design appropriate solutions.

**Comment by mpouttuclarke** [comment]
Here is the factory URL for my project: http://beta.codenvy.com/f?id=cvl7oomu6ostky1i

FYI: loving the factories BTW.  

The Dockerfile is: https://github.com/LamdaFu/dockerfiles/blob/master/hadoop-dev/Dockerfile 

To reproduce this issue, all you have to do is exec the factory, wait for it to time out due to inactivity, and then exec the factory again.

**Comment by mpouttuclarke** [comment]
FYI: just from executing the factory today I can see it is faster than historically.

**Comment by mpouttuclarke** [comment]
Just ran it again and it is back to what it was, about 10 minutes

**Comment by mpouttuclarke** [comment]
You can also click Workspace -> Stop and then restart the workspace and the same delay happens, a complete re-execution of the entire Dockerfile.

**Comment by eivantsov** [comment]
@mpouttuclarke I have tried to start a workspace from your Dockerfile. It indeed takes much time but this  the time Docker needs to build an image from such a recipe.

The solution would be to build a base images from this Dockerfile, upload it to DockerHub and use on Beta. Docker will pull it for the first time, and then use from cache.

**Comment by eivantsov** [comment]
@mpouttuclarke I think this PR does the trick for you now: https://github.com/codenvy/dockerfiles/pull/42
I am closing the issue.
