### ISSUE TITLE
Managing machine snapshots

### ISSUE THREAD

**Issue by lidoma** [codenvy/codenvy#349]
I take a machine snapshots to hold new state of machine after installing packages. Where these snapshot files stored? Can we have a history of taken snapshots?

And what's the use case of Source URL of machine?

**Comment by eivantsov** [comment]
@lidoma Snapshots are created at Machine > Create Snapshot on Operations Perspective (switcher in the top right corner).

Snapshots are stored in a Docker registry that we run in our infrastructure.

Can you elaborate on source URL of a machine?

**Comment by lidoma** [comment]
@eivantsov Please let me explain what i have in mind by example. I take, for instance, three snapshots  from three different machine states. Can i see a list of these three snapshots according to their taken date which i can choose one of them? As I found out, we can just take one snapshot and restore just that.
I can see a machine property in Targets dialog window which called Source URL? For instance,
```
beta.codenvy.com:5000/0glom19q7sxxxxxx:latest@sha256:85e216cd44b5ce292b01e9ef4f5cf3d61a34f21ec61a8e9afab5c7bf53xxxxxx
```
What's the use case of this URL?

**Comment by eivantsov** [comment]
@lidoma this is the URL to a snapshot image that is pulled.

Codenvy uses the latest snapshot made, and there's no list of available snapshots since when a new snapshot is made, the old one gets deleted.
