### ISSUE TITLE
Copy/paste not working in command configuration dialog (Chrome only)

### ISSUE THREAD

**Issue by mathiasconradt** [codenvy/codenvy#354]
In Chrome (51.0.2704.103 (64-bit)) on Mac OS X its not possible to copy the value from the command configuration dialog fields (i.e. "command line" field) into the clipboard via `Command+c` or otherwise in order to paste it again.

Pressing `Command+c` does not copy the value into the clipboard.

It works fine in Firefox, does not work in Chrome. Haven't tested it in Chrome on Windows yet.

Screenshot: 

![Screensho](https://snag.gy/KY0JVr.jpg)

**Comment by TylerJewell** [comment]
I confirm the issue.  Though this is an upstream issue with eclipse Che, not Codenvy.  Can you open a matching issue for tacking at github.com/eclipse/Che?

**Comment by mathiasconradt** [comment]
Created the ticket at https://github.com/eclipse/che/issues/1667
