### ISSUE TITLE
Running a Java Applet on Codenvy's android emulator

### ISSUE THREAD

**Issue by LGtcc** [codenvy/codenvy#366]
I have a program for a Java applet which runs fine on desktop IDEs but I can't get it to run in Codenvy. When I run the program with a Java7 and VNC runner, it seems to run without errors, and gives me an application link, which takes me to a grey screen. Right clicking allows me to select the emulator, which opens an android emulator; however, I can't see how to load my program into the emulator. Any ideas? Sorry if I'm missing something obvious, I'm very new to both Java and Codenvy.

I've attached a screenshot of my program, and the android emulator as it currently loads.

Thanks

![screenshot](https://cloud.githubusercontent.com/assets/20406497/16744631/d77127b6-47a9-11e6-8c58-8a96dba508e8.jpg)
![screenshot3](https://cloud.githubusercontent.com/assets/20406497/16744639/e10cd86a-47a9-11e6-9c56-2b17ae0f95ea.jpg)

**Comment by ddementieva** [comment]
How did you run your app on the desktop IDEs? Have you tried to call your app directly in the VNC Terminal?

**Comment by LGtcc** [comment]
I've just been using BlueJ, so I right-click on the applet class and select "Run Applet". How would I call the app directly, using the command line?

**Comment by ddementieva** [comment]
@LGtcc You've used Android based environment, where apk is installed in the Terminal with `adb install`.

So you can go to the VNC window, call the Terminal from the context menu and install apk there. 
Can you perhaps provide a tutorial on how to run your app locally?

You can try to run your app in the next generation IDE at beta.codenvy.com with codenvy/ubuntu_jdk8_x11 image (https://hub.docker.com/r/codenvy/ubuntu_jdk8_x11/). Here is the tutorial on how to run a Swing app https://eclipse-che.readme.io/docs/che-and-swing
