### ISSUE TITLE
Adding documentation to use alternative IDE

### ISSUE THREAD

**Issue by ufoscout** [codenvy/codenvy#369]
The codenvy website mentions ( https://codenvy.com/resources/white-papers/localhost-is-killing-software-delivery/ ) :

> Use Any IDE. Whether it is IntelliJ, Sublime, Eclipse, emacs, vi or our browser-based IDE, we are indifferent.

However, no specific documentation seems to be available. 
Could you please provide an example or point me to the related docs. This feature is a quite important point in an evaluation of codenvy that I am preparing for my company.

**Comment by TylerJewell** [comment]
@benoitf - can you comment in this thread on the specifics on how to SSH mount a workspace and / or a project onto a local file system so that it can be used by another IDE?  You have the most experience with this and did the demos on this at EclipseCon in March. If you can jot down the various notes here, I'll add them as a page in the Eclipse Che docs.

@ufoscout - let us know if you want some assistance for helping your team do an on-prem or a more elaborate team-based evaluation. We like to really lean-in and help teams onboard this way.

**Comment by ufoscout** [comment]
@TylerJewell - thanks for your support. We already had a dedicated session from the codenvy team; we got some evaluation licences and now we wonder how to integrate a local IDEs with a codenvy workspace. 
I hope @benoitf will be able to provide support soon.

**Comment by benoitf** [comment]
@ufoscout you may follow https://www.youtube.com/watch?v=oWCPczMK-_8

sshfs user@ip-of-che-agent:/projects /my/local/path -p <ssh-port>

**Comment by TylerJewell** [comment]
@ufoscout - Which company are you with? We'll get the docs better updated to reflect how to setup an IDE to work with a java or non-java workspace.

**Comment by ufoscout** [comment]
@benoitf - thanks for the link, it clarifies well what I needed to know.

@TylerJewell I am having a great time working at Aurea.com

**Comment by ddementieva** [comment]
@ufoscout http://codenvy.readme.io/v4.4/docs/using-desktop-ides

**Comment by ufoscout** [comment]
@ddementieva there is no link on the left menu to reach that page :)

**Comment by TylerJewell** [comment]
@ufoscout - we have a whole new page showing up in 4.6, which has been released, but not yet shipped.  The 4.6 docs has the Desktop IDE mount right at the top of the setup. We also are shipping an experimental CLI that has syntax of `che mount <local-path> <ws-ssh-port>` where the `<local-path>` is your host directory and the port is the SSH port of your workspace.  It uses a super fast fuse-based mount with sshfs and unison for synchronization.  Tested on windows, linux and mac.

You can get a sneak peak of how the new getting started and adding a desktop IDE is here.  https://www.eclipse.org/che/getting-started/download/index2.php
