### ISSUE TITLE
How to run python script?

### ISSUE THREAD

**Issue by iamnaok** [codenvy/codenvy#385]
Hi, I cannot figure out how to run this script https://gist.github.com/mattvukas/9146611

Here it is:
import requests, json
from time import sleep

def getBitcoinPrice():
    URL = 'https://www.bitstamp.net/api/ticker/'
    try:
        r = requests.get(URL)
        priceFloat = float(json.loads(r.text)['last'])
        return priceFloat
    except requests.ConnectionError:
        print "Error querying Bitstamp API"

while True:
	print "Bitstamp last price: $" + str(getBitcoinPrice()) + "/BTC"
	sleep(5)

**Comment by ddementieva** [comment]
When on the Dashboard, go to Workspaces > Stack Library and create a new workspace with Python2.7 stack. Open it in the IDE and create a new project with py file, which contains your script, and requirements.txt file with the following content `Requests` to install requests module. 

In the Terminal, cd your project directory and execute the following command to run your script: sudo virtualenv /env && sudo pip install --upgrade pip && sudo pip install -r requirements.txt && python main.py

**Comment by eivantsov** [comment]
@iamnaok does this suggestion help?

**Comment by eivantsov** [comment]
Closing the issue - do try the suggestion offered by @ddementieva

**Comment by thalesmaoa** [comment]
This suggestion doesn't work. Can you open this issue?
