### ISSUE TITLE
Create a page to be displayed after user is deleted

### ISSUE THREAD

**Issue by ashumilova** [codenvy/codenvy#389]
This should be a simple page saying:
Your account has been deleted. You may recreate it at ${hostname.com}

**Comment by TylerJewell** [comment]
Let's just say, "Your accont has been deleted."  Please lets not give them the recreate message.

**Comment by vkuznyetsov** [comment]
I propose to use the same design as in thank-you page and put "Your account has been deleted." as description. What title we need for account-deleted page?
![codenvy account-deleted](https://cloud.githubusercontent.com/assets/2101815/17249660/a4b163be-55a9-11e6-885b-8ea88ab68017.png)

**Comment by TylerJewell** [comment]
"account" is misspelled.  I like the design.

**Comment by vkuznyetsov** [comment]
![codenvy account-deleted](https://cloud.githubusercontent.com/assets/2101815/17249950/eedb9be8-55aa-11e6-8395-6450c5e52ec7.png)
I fixed the typo .

**Comment by vkuznyetsov** [comment]
This is the url of page {$host}/site/account-deleted
