### ISSUE TITLE
Integrate JPA components/tools with Codenvy infrastructure

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#396]
Things to do:
- Set up PostgreSQL database as a replacement for MongoDB and LDAP
- Bind Jpa based dao implementations instead of Mongo/Ldap
- Migrate all the data using migration tool
- Ensure Codenvy works as expected

**Comment by akorneta** [comment]
#### selenium test results:
```
tests:        300
failures:     69
skipped:      1
success rate: 76.667%
```

**Comment by akorneta** [comment]
|   Selenium test | results  | 
|----------|:-------------:|
| tests |  346|
| failures |  55| 
| skipped |    55   | 
| success rate | 68.208% |
