### ISSUE TITLE
Convert Chrome Store listing to beta.codenvy.com

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#402]
The Chrome Store listing is still pointing to Codenvy 3. It should be updated to use beta.codenvy.com and include the attached two screenshots and this video: https://www.youtube.com/watch?v=y4wdplYj6qs

![new-dashboard-screenshot](https://cloud.githubusercontent.com/assets/7644938/17326759/5e81c3b8-5881-11e6-92d9-b0c17384861e.png)

![1-cloud-ide](https://cloud.githubusercontent.com/assets/7644938/16916832/0468ad5c-4ccd-11e6-8bbd-35ff79ef7f1f.png)

The description should be updated to use the following:
_______
Based on the open source Eclipse Che project, Codenvy is a cloud IDE and developer workspace server that allows anyone to contribute to a project without having to install software.

   •    One-click project onboarding makes getting started easy
   •    Containerized workspaces let you use any stack
   •    Use any programming language or IDE
   •    Integrate version control and issue management seamlessly
   •    Full root access and SSH (so you can use any IDE)
   •    Retain muscle memory with vi and emacs key bindings
   •    Work online, offline with CLI sync, or behind the firewall with Codenvy on-premises

Codenvy is offered as SaaS, on-premises and white label. Or, badge your public git repo to give anyone instant access to review or contribute to your project.
_______

Version should be updated to match the current product version live when the store was updated.

**Comment by TylerJewell** [comment]
@bmicklea - that has old screen shot of dashboard.  Please update.
