### ISSUE TITLE
Swagger doesn't have ID of a particular machine in base path

### ISSUE THREAD

**Issue by AndreyChizhikov** [codenvy/codenvy#403]
**Expected:**
Swagger has base path with ID of a particular machine (e.g. '/33342_node1.nightly4.codenvy-stg.com/wsagent/ext')

**Actual:**
Swagger has base path with '/wsagent/ext'. 

**Affects Version:**
4.3.0

**Comment by TylerJewell** [comment]
@AndreyChizhikov - is this still actual?

**Comment by musienko-maxim** [comment]
Still actual

**Comment by skabashnyuk** [comment]
won't fix
