### ISSUE TITLE
Validate options of Codenvy bootstrap script

### ISSUE THREAD

**Issue by vkuznyetsov** [codenvy/codenvy#404]
Validate options which user passes to Codenvy bootstrap script. 
If option is unknown, display warning at start like the follow:
{noformat}
[CODENVY] Welcome. This program installs Codenvy 3.14.2-SNAPSHOT.
[CODENVY] !!! You passed a parameter named `no-proxy`. This is an unrecognized parameter.
[CODENVY] !!! You passed a parameter named `http-proxy`. This is an unrecognized parameter.
[CODENVY] !!! You passed a parameter named `https-proxy`. This is an unrecognized parameter.
[CODENVY] Proceed? [y/N]
{noformat}

**Comment by dmytro-ndp** [comment]
I propose to change output slightly to handle parameters with value, flags and typos:
> [vagrant@dev ~]$ ./install-codenvy.sh --http-proxy=http://test --unknown typo
> [CODENVY] Welcome. This program installs Codenvy 4.5.1.
> [CODENVY] 
> [CODENVY] !!! You passed a parameter '--http-proxy=http://test'. This is an unrecognized parameter.
> [CODENVY] !!! You passed a parameter '--unknown'. This is an unrecognized parameter.
> [CODENVY] !!! You passed a parameter 'typo'. This is an unrecognized parameter.
> [CODENVY] Proceed? [y/N]: 
> [CODENVY] 
> [CODENVY] You must accept the Codenvy license agreement to install
> ...
