### ISSUE TITLE
Change default dns http://codenvy to any dns which contain dot symbol

### ISSUE THREAD

**Issue by riuvshin** [codenvy/codenvy#407]
Problem:
customers report that our default dns http://codenvy does not work. After investigation we've found that dns services may not work with dns names without dot symbols.

from the official dns service FAQ 
```
Q: Names on the internet are working fine, but looking up local names 
   from /etc/hosts or DHCP doesn't seem to work.

A: Resolver code sometime does strange things when given names without
   any dots in.
```

We must change our default dns to something that contain dot symbol in it.
Proposal: change dns http://codenvy to http://codenvy.onprem

**Comment by tolusha** [comment]
Issue requires docs + tests changing.

**Comment by TylerJewell** [comment]
Issue requires an update to Vagrantfile, as well.

**Comment by tolusha** [comment]
As temporary solution I will update codenvy.properties on production and test installation

**Comment by riuvshin** [comment]
we also should care about how users who installed http://codenvy will update to http://codenvy.onprem

**Comment by riuvshin** [comment]
we will also need to reconfigure preconfigured oAuth for github and google

**Comment by TylerJewell** [comment]
Vagrantfile has been updated with new syntax.
