### ISSUE TITLE
Create a script for diagnostic and collect needed info for support in case of troubleshooting

### ISSUE THREAD

**Issue by riuvshin** [codenvy/codenvy#413]
This is a part of https://github.com/codenvy/codenvy/issues/412 epic

We need create a tool which will simplify collecting any needed info for support customers in case of some problems. That tool should be super easy to execute preferably bash script and on first iteration it should collect needed files or commands output and put it into zip.
Items to collect:
files (note `*` means all files in the folder)
**/var/log/puppet/*
/var/log/nginx/*
/var/log/mongodb/*
/var/log/docker-distribution.log
/var/log/fail2ban.log
/var/log/haproxy.log
/var/log/messages
/var/log/swarm.log
/var/log/yum.log
/etc/puppet/auth.conf
/etc/puppet/autosign.conf
/etc/puppet/fileserver.conf
/etc/puppet/puppet.conf
/home/codenvy/codenvy-data/che-machines-logs/*
/home/codenvy/codenvy-data/logs/*
/home/codenvy/codenvy-data/conf/machine.properties
/home/codenvy/codenvy-data/conf/general.properties
/etc/resolv.conf
/etc/hostname
/etc/hosts**

commands output to collect (please keep them in a separate files with predictable names):
**facter fqdn
hostname
hostname -f
puppet agent -t**

Everything inside of that zip should be well structured to make it easy to understand and analyze.
example:
**zip/
...../logs/
...../configs/
...../commands_output/**

**Comment by riuvshin** [comment]
@skryzhny please take a look on that maybe you will add something

**Comment by skryzhny** [comment]
I think we need to capture few other things too

Files:
**/etc/sysconfig/network-scripts/ifcfg-*
/etc/NetworkManager/*
/var/log/sa/sar*
/etc/yum.repos.d/*
/var/log/yum***

Output of commands:
**iptables-save
nslookup $host_url
df -h
df -i
mount
journalctl --since today
ps auxf
w**

**Comment by eivantsov** [comment]
@riuvshin @skryzhny please try this one on a real Codenvy instance. I have tried it on a freshly installed On-Prem on Digital Ocean. Execute as root:
`curl https://gist.githubusercontent.com/eivantsov/7744cbf9ce6547f2be5e93aa05b5bce2/raw/54a636d9d92753b2066842bb5c8eecdfcafb956a/report.sh | bash`

**Comment by riuvshin** [comment]
@eivantsov seems we need to add check for sudo rights

**Comment by TylerJewell** [comment]
@riuvshin - should we add `codenvy support` as an IM entry?  It will launch this script, and then generate a zip file with the contents.

**Comment by eivantsov** [comment]
I'd leave it as a script in case we need to change smth asap. Changes to im take more time. We may need new commands or files.

**Comment by riuvshin** [comment]
@TylerJewell agree with @eivantsov let's keeps this as a script for now, but we will definitely move this to IM afterwards

**Comment by eivantsov** [comment]
Added an additional check - now only user can run the script https://gist.githubusercontent.com/eivantsov/7744cbf9ce6547f2be5e93aa05b5bce2/raw/0a7ed422a7a4a9440e66be11dd50e0b9744085b7/report.sh
