### ISSUE TITLE
Continuous Integration docs

### ISSUE THREAD

**Issue by ufoscout** [codenvy/codenvy#416]
Hi all,

the entire documentation about Continuous Integration ( http://codenvy.readme.io/docs/continuous-integration ) is as short as:

> Coming soon...

Does it mean that there's no continuous integration but this feature will come soon or does it mean the there is continuous integration and the documentation is coming?
Could you please provide more info about it and, if possible, an informative link or example?

Regards

**Comment by TylerJewell** [comment]
@ufoscout - this page is a placeholder for us authoring documentation on how CI systems can be integrated into Codenvy, such that it is possible for CI systems to have factories w/ context, to generate dev workspaces with the context of the currently running job.

We have the same issue with Version Control and will make it a priority to get these pages drafted.

**Comment by TylerJewell** [comment]
This was long ago updated and we have a section on the docs.codenvy.com related to integrations now.  Sorry we didn't close this.
