### ISSUE TITLE
help plz cant find my data when added some git

### ISSUE THREAD

**Issue by mamadmerlini** [codenvy/codenvy#417]
hi i want to creat antispam/anti_link  robot for telegram  group;( 
and this is my source for creat a bot 
sudo apt-get update

sudo apt-get upgrade

sudo apt-get install libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev libevent-dev make unzip git redis-server g++ libjansson-dev libpython-dev expat libexpat1-dev

cd $HOME

git clone https://github.com/KnightTeam/KnightTeam

cd KnightTeam

chmod +x launch.sh

./launch.sh install

./launch.sh
[http://uupload.ir/files/s2ad_capture.png](url)
but when i type this
git clone https://github.com/KnightTeam/KnightTeam
i want that for sudo in config.lua but there is no data added here :( where can i find my folder proeject
when i added this gitub ?

**Comment by TylerJewell** [comment]
Do not add projects with git clone.  Instead, in the IDE, go to Workspace -> Import Project.  Import the project through the wizard.

**Comment by eivantsov** [comment]
@mamadmerlini you can git clone your projects, however, not in`$HOME` but in `/projects`. You may then refresh project tree or the entire page, and find your freshly cloned project there. You may need to configure it, i.e. give it a project type then (you will see a red cross on the project icon).

**Comment by eivantsov** [comment]
@mamadmerlini have you been able to resolve the issue?

**Comment by mamadmerlini** [comment]
Tnx

در تاریخ ۲۰ ژوئیهٔ ۲۰۱۶ ۱۰:۴۲، "Eugene Ivantsov" <notifications@github.com>
نوشت:
