### ISSUE TITLE
Bitbucket oAuth is broken

### ISSUE THREAD

**Issue by ddementieva** [codenvy/codenvy#426]
Steps to reproduce:
1. Go to Bitbucket settings > OAuth and a new oAuth consumer with the following callback URL: http://$hostname/api/oauth/callback 
2. Save client ID and secret to Puppet configuration on the server in /etc/puppet/manifests/nodes/codenvy/codenvy.pp
3. Run `puppet agent -t`.
4. Try to import some Bitbucket project.

As a result, error will appear, saying that automatic upload is not supported for some providers.

**Comment by bmicklea** [comment]
In the meantime you can work around this by generating an SSH key manually:
- In the IDE go to *Profile > Preferences > SSH > VCS* and create a key
- On the bitbucket.org host, copy the key and save to the Bitbucket *Settings > SSH* keys.

**Comment by mshaposhnik** [comment]
+1 @bmicklea This is not the first time this issue appears. Previous was CODENVY-426 in jira.
In new bitbucket 2.0 api there is no ssh key management anymore (https://developer.atlassian.com/bitbucket/api/2/reference/resource/) so we cant autouplad keys. User need to do that manually.

**Comment by riuvshin** [comment]
So should we close issue? It seems it is normal behaviour.
