### ISSUE TITLE
Sourcegraph factory examples from getting-started page works wrong

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#430]
**Reproduction Steps:**
1. Go to the https://www.eclipse.org/che/getting-started/cloud/
2. Consuming Sourcegraph factory 

**Expected behavior:** The project should be cloned and run. 
**Observed behavior:** We have  just empty folder with unknown project

**Che version:**    4.5.0
**OS and version:** Ubuntu OS 14.0
**Chrome browser**
**Server location** https://beta.codenvy.com
**Additional information:**

**Comment by TylerJewell** [comment]
please provide specific details.

**Comment by benoitf** [comment]
on sourcegraph when cloning the repository on my computer I have

```
$ git clone https://sourcegraph.com/sourcegraph/sourcegraph
Cloning into 'sourcegraph'...
remote: Counting objects: 148092, done.
remote: Compressing objects: 100% (60876/60876), done.
receiving objects:  12% (17772/148092), 2.75 MiB | 792.00 KiB/s
```
but if I try : import project
![image](https://cloud.githubusercontent.com/assets/436777/17029321/160c5d7e-4f6b-11e6-99f5-057b78556ad4.png)

seems like a git/importer regression

**Comment by slemeur** [comment]
Add "severity/blocker" not because the factory is not working, but because of the git/importer regression.

**Comment by riuvshin** [comment]
Can we have factory configuration to be able to reproduce it on test environment?

**Comment by mshaposhnik** [comment]
Found the root of the problem: sourcegraph has client filtering by user-agent, so clients other than native git (we're using JGit now) receive 404 status. Example:
Not working:
`curl -v "https://sourcegraph.com/sourcegraph/sourcegraph/info/refs?service=git-upload-pack`
Working:
`curl -v -H "User-Agent: git/2.1.0" "https://sourcegraph.com/sourcegraph/sourcegraph/info/refs?service=git-upload-pack"`

So we have 2 options here:

1. Start endless discussion with sourcegraph to allow other clients too;
2. Just improve JGit client to always masquerade as native git client;

@slemeur @skabashnyuk @TylerJewell  what do you prefer ?

**Comment by skabashnyuk** [comment]
Yes
Like egit https://github.com/eclipse/egit-github/blob/master/org.eclipse.egit.github.core/src/org/eclipse/egit/github/core/client/GitHubClient.java#L261

**Comment by mshaposhnik** [comment]
Fixed, thanks.
