### ISSUE TITLE
hi new problem with my bot

### ISSUE THREAD

**Issue by mamadmerlini** [codenvy/codenvy#438]
When I close  Your Page(https://beta.codenvy.com)my project my bot going to offline just in the moment

my project :| https://github.com/mamadmerlini/lol

**Comment by TylerJewell** [comment]
@mamadmerlini - please submit an issue with a full set of steps to reproduce in bulleted form. It needs to be reproducible and well explained for an engineer to provide assistance.  The issue can be reopened once that is done.
