### ISSUE TITLE
Python built without readline

### ISSUE THREAD

**Issue by Glycan** [codenvy/codenvy#445]
The default python stack compiles python without readline, making simple REPL scripting rather irritating.

Reproduction Steps:
- create a python wordspace
- run python
- attempt to scroll up with up key

Expected behavior:
-  history scrolls up

Observed behavior:
- enters ^[[A
- doesn't scroll up
- makes me sad

Codenvy version: 4.5.1
OS and version: Chrome 49 on Windows Visa, also happened on a Chromebook.
Additional information:

Problem only started happening recently, didn't happen in an older version of Codenvy: [n/a]
Problem can be reliably reproduced: [Yes]

**Comment by TylerJewell** [comment]
There is a python language server coming from Sourcegraph soon.  This will resolve this issue.

**Comment by TylerJewell** [comment]
This was addressed a few releases ago.  Cleaning up the backlog.
