### ISSUE TITLE
Methods "updateAttributesById" and "updateAttributes" in the ProfileService clean up user lastName in some case of partial update

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [codenvy/codenvy#451]
Method "updateAttributesById" in the ProfileService clean up user lastName in some case of partial update.

Reproduction Steps:

[First Step] Create user and fill his profile
[First Step] Update "firstName" for user profile. Follow we do it with help curl:

curl -X PUT --header 'Content-Type: application/json' --cookie 'Cookie:Cookie:**Your cookie**' --header 'Accept: application/json' -d "{\"firstName\" : \"Luxas\"}" "https://aio.codenvy-dev.com/api/profile/attributes"

Expected behavior:

ProfileService should set new "firstName" in the user profile, but another fields should not be changed.

Observed behavior:

ProfileService set new "firstName" in the user profile and clean up "lastName" to value "<none>".

Codenvy version: 4.6.0
OS and version: ubuntu 14.04

Additional information:

Problem can be reliably reproduced: [Yes]

**Comment by JamesDrummond** [comment]
@vkuznyetsov Can we remove status on this?
