### ISSUE TITLE
Snapshotting mechanics

### ISSUE THREAD

**Issue by soanni** [codenvy/codenvy#455]
Hello Codenvy Team.

This time I want to ask you about snapshots mechanics. 
Situation: 
1. I'm transferring one big product to Codenvy.
2. Product consists of application server and database server. I'm planning to run each tier in its separate container.
3. I created a workspace (from my custom Dockerfile based on you centos/java8 Dockerfile).
4. Imported codebase from Git. This container is application tier.
5. Then i need database, so i'm going to Machines tab and creating new machine from custom Dockerfile. This machine is supposed to be my Oracle DB server for application.
6. Okay, after an hour of container creation (the machine is pretty big, docker image is about 15GB) i got the running machine.
7. checking images

docker images

The machine image is there.

8. Created a snapshot for workspace. btw what's the difference between creating snapshots from Machine->Create snapshot and when i click Snapshot on the workspace icon on the left pane of browser window?? In both cases there is a pop-up window stating that workspace is snapshotting, so in both cases i will have both docker images commited to registry (Oracle machine and Dev machine for workspace itself)?
Checked docker images. Snapshot is there.

9. Stop the workspace.
10. Woke up in the morning. Started the workspace, there are no question whether the system should pull the snapshot. checked docker images no sign of yesterdays snapshot.
And no sign of oracle image itself.

10. Starting to create oracle machine again...

The properties for autosnapshot are default. Codenvy version was 4.4 yesterday. Today i updated to 4.5.1, will see how it works in new version.

**Comment by ddementieva** [comment]
@soanni we've just tried to reproduce the problem with workspace snapshotting at 4.5.1 and failed to do that. 

I workflow:
1. Create any workspace, open it in the IDE, make some changes.
2. Create snapshot manually at the Operations Perspective > Machine.
3. Stop workspace.
4. Start workspace from snapshot (e.g. from the Dashboard).

II workflow:
1. Change `workspace.runtime.auto_snapshot` and `workspace.runtime.auto_restore` to true in the  /etc/puppet/modules/all_in_one/templates/general.properties.erb.
2. Execute `puppet agent -t`.
3. Go back to Codenvy, login, create some workspace, make changes.
4. Stop workspace. It should be automatically snapshotted.
5. Start workspace from snapshot.  

In both cases workspaces should be successfully restored from the snapshots.

Have you already tried it with 4.5.1?

**Comment by eivantsov** [comment]
@soanni as to images that we use for snapshots, they are pushed to a registry and then deleted. You can look for snapshots in `/tmp/registry`

**Comment by soanni** [comment]
@eivantsov What is the mechanism for deletion of snapshot? Every next snapshot will delete the previous right?

**Comment by eivantsov** [comment]
@soanni yes, correct!

**Comment by soanni** [comment]
Regarding stopping/starting the workspace. I set these 2 properties: workspace.runtime.auto_snapshot, workspace.runtime.auto_restore to true. Then i added 1 machine to my workspace, so there are 2 machines now there. Then i stopped the workspace. The snapshot has been created. Then i started the workspace, it started from the snapshot only the second time (the first time there was an error about machine is not found, and i already saw this error days before, so this is not accidental case ) but i can see only one machine (main) now. So i have to add one machine again (it is fast because the image is stored but i expected to see 2 machines after recovering from snapshot).
The machine id in error doesn't belong to any of 2 machines of this workspace.

![workspace_error](https://cloud.githubusercontent.com/assets/5715840/17178580/1a721abe-5427-11e6-8497-a215a1da131b.png)

**Comment by soanni** [comment]
My main concern here that i can see only one machine after recovering from snapshot

**Comment by soanni** [comment]
i queried the database
db.snapshots.find().pretty()


        "_id" : "snapshot4xfqmzkz353dlnf1",
        "workspaceId" : "workspacewnmyevpof43vyrpt",
        "machineName" : "ws-machine",
        "envName" : "wksp-y3c7",
        "type" : "docker",
        "namespace" : "soanni",
        "isDev" : true,
        "creationDate" : NumberLong("1469458134582"),
        "description" : "wksp-y3c7",
        "machineSource" : {
                "type" : "image",
                "location" : "172.30.95.192:5000/rnm32hb5cd1u3wr7:latest@sha256:26eb07fcfee3ffdd353caddda26c35449e1739a7c49cc8e53de34ef8a4f500c4",
                "content" : null
        }
}
{
        "_id" : "snapshot23sghnnjzytka05z",
        "workspaceId" : "workspacewnmyevpof43vyrpt",
        "machineName" : "oracle",
        "envName" : "wksp-y3c7",
        "type" : "docker",
        "namespace" : "soanni",
        "isDev" : false,
        "creationDate" : NumberLong("1469458245512"),
        "description" : "wksp-y3c7",
        "machineSource" : {
                "type" : "image",
                "location" : "172.30.95.192:5000/67s3y9w7c347grx6:latest@sha256:49f58cd2ef71359c702caa77a4fc655536da28cdd73101f3b52c3887e61cd2c2",
                "content" : null
        }
}
{
        "_id" : "snapshotu8e8865ktsfks68u",
        "workspaceId" : "workspaceetkl09d3qokrbccs",
        "machineName" : "ws-machine",
        "envName" : "ACE_1",
        "type" : "docker",
        "namespace" : "soanni",
        "isDev" : true,
        "creationDate" : NumberLong("1469479151568"),
        "description" : "ACE_1",
        "machineSource" : {
                "type" : "image",
                "location" : "172.30.95.192:5000/gmzhhvhff3l8sete:latest@sha256:887729ba953ba8402571455aee18878d92ad75e1eabae6c52e1c32a3d541c455",
                "content" : null
        }
}
{
        "_id" : "snapshotmpg1qbk0jr6f7u66",
        "workspaceId" : "workspaceetkl09d3qokrbccs",
        "machineName" : "oracle",
        "envName" : "ACE_1",
        "type" : "docker",
        "namespace" : "soanni",
        "isDev" : false,
        "creationDate" : NumberLong("1469479237715"),
        "description" : "ACE_1",
        "machineSource" : {
                "type" : "image",
                "location" : "172.30.95.192:5000/c3jtwjlq59pod8t3:latest@sha256:f5390697af37569a5e945c5af6fe1fdc86dd34c8e9714cbfd670a5cb6dd4b41f",
                "content" : null
        }
}
{
        "_id" : "snapshothvio8y68oyeyqgpq",
        "workspaceId" : "workspacewc13hgjpitaacoyp",
        "machineName" : "ws-machine",
        "envName" : "ACE2",
        "type" : "docker",
        "namespace" : "soanni",
        "isDev" : true,
        "creationDate" : NumberLong("1469626884427"),
        "description" : "ACE2",
        "machineSource" : {
                "type" : "image",
                "location" : "172.30.95.192:5000/machine_snapshot_gl2bueeuo4jcxfjf:latest@sha256:91509326fb858f821248941c044a22d9d41141c7f9f9da72d11db785247e8038",
                "content" : null
        }
}
{
        "_id" : "snapshot5hnro5a4wa47c88p",
        "workspaceId" : "workspacewc13hgjpitaacoyp",
        "machineName" : "oracle",
        "envName" : "ACE2",
        "type" : "docker",
        "namespace" : "soanni",
        "isDev" : false,
        "creationDate" : NumberLong("1469626917265"),
        "description" : "ACE2",
        "machineSource" : {
                "type" : "image",
                "location" : "172.30.95.192:5000/machine_snapshot_ttcsahmlejqlrlpt:latest@sha256:bd4a7d708afbe7c4bdd382ac08038778190a0c38f363bfa18d6244ac479b43da",
                "content" : null
        }
}

**Comment by soanni** [comment]
the workspace name is ACE2. so here i can see that both machines have been snapshotted. But after recovery workspace contains only one machine (ws-machine)

**Comment by eivantsov** [comment]
@soanni indeed, when a machine is added to a workspace in a runtime, it's lost after a workspace has stopped. There's a workaround though. Create a workspace with 2 machines in a config. Here's an example:

```
{  
   "defaultEnv":"default",
   "name":"multi-machine",
   "environments":[  
      {  
         "machineConfigs":[  
            {  
               "dev":true,
               "limits":{  
                  "ram":1000
               },
               "servers":[  

               ],
               "envVariables":{  

               },
               "source":{  
                  "type":"dockerfile",
                  "content":"FROM codenvy/ubuntu_jdk8"
               },
               "name":"default",
               "type":"docker"
            },
{  
               "dev":false,
               "limits":{  
                  "ram":1000
               },
               "servers":[  

               ],
               "envVariables":{  

               },
               "source":{  
                  "type":"dockerfile",
                  "content":"FROM codenvy/debian_jdk8"
               },
               "name":"auxilliary",
               "type":"docker"
            }
         ],
         "name":"default"
      }
   ]
}
```

I created a workspace using this config, made changes to both machines, snapshotted each, stopped workspace, started workspace, both machines with my changes are there.

You may also set auto snapshot and restore to true, you will just stop a workspace and both machines will be auto snapshotted.

FYI, it will take a while to snapshot a 15GB machine.

**Comment by soanni** [comment]
@eivantsov  thanks for workaround. However it's not an easy way to create a workspace from lengthy JSON everytime you need a multiple-machine environment. Moreover sometimes during the process of development you can eventually figure out that you need a new machine on the existing environment.
If it is possible to fix this misbehaviour in future version that will be greatly appreciated.

**Comment by eivantsov** [comment]
@soanni yes, it's not an easy way, and @TylerJewell has already shared our plans as to proper multi container workspaces.

Did this workaround work for you?

**Comment by TylerJewell** [comment]
@soanni - the system currently isn't misbehaving. The system is behaving to spec in terms of multiple machines. It is designed purposefully in its current version to have secondary machines launched in this way.  But no fret, no worries!  Multi-machine workspaces defined by docker compose have been in development for a long time and will be shipping soon :)

**Comment by soanni** [comment]
@eivantsov @bmicklea i tried to make a workspace with 3 machines. It created only 1 mschine (for workspace itself). I paste this JSON object here (screenshot_1), the result is (screenshot_2), the JSON object itself is that one
-----------------------------

{  
   "defaultEnv":"default",
   "name":"ACE MULTI",
   "environments":[  
      {  
         "machineConfigs":[  
            {  
               "dev":true,
               "limits":{  
                  "ram":4000
               },
               "servers":[  

               ],
               "envVariables":{  

               },
               "source":{  
                  "type":"dockerfile",
                  "content":"FROM centos\nEXPOSE 4403 8080 8000 22\n# custom tomcat port exposure\nEXPOSE 8888\nRUN yum update -y && \\\n yum -y install sudo openssh-server procps wget unzip mc git curl subversion nmap && \\\n mkdir \/var\/run\/sshd && \\\n sed 's@session\\s*required\\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i \/etc\/pam.d\/sshd && \\\n echo \"%wheel ALL=(ALL) NOPASSWD: ALL\" >> \/etc\/sudoers && \\\n useradd -u 1000 -G users,wheel -d \/home\/user --shell \/bin\/bash -m user && \\\n echo -e \"codenvy2016\\ncodenvy2016\" | passwd user && \\\n sed -i 's\/requiretty\/!requiretty\/g' \/etc\/sudoers\n\nUSER user\n\nLABEL che:server:8080:ref=tomcat8 che:server:8080:protocol=http che:server:8000:ref=tomcat8-debug che:server:8000:protocol=http\n\nENV MAVEN_VERSION=3.3.9 \\\n JAVA_VERSION=8u45 \\\n JAVA_VERSION_PREFIX=1.8.0_45 \\\n TOMCAT_HOME=\/home\/user\/tomcat8\n\nENV JAVA_HOME=\/opt\/jdk$JAVA_VERSION_PREFIX \\\n M2_HOME=\/home\/user\/apache-maven-$MAVEN_VERSION\n\nENV PATH=$JAVA_HOME\/bin:$M2_HOME\/bin:$PATH\n\nRUN mkdir \/home\/user\/tomcat8 && mkdir \/home\/user\/apache-maven-$MAVEN_VERSION && \\\n wget \\\n --no-cookies \\\n --no-check-certificate \\\n --header \"Cookie: oraclelicense=accept-securebackup-cookie\" \\\n -qO- \\\n \"http:\/\/download.oracle.com\/otn-pub\/java\/jdk\/$JAVA_VERSION-b14\/jdk-$JAVA_VERSION-linux-x64.tar.gz\" | sudo tar -zx -C \/opt\/ && \\\n wget -qO- \"http:\/\/apache.ip-connect.vn.ua\/maven\/maven-3\/$MAVEN_VERSION\/binaries\/apache-maven-$MAVEN_VERSION-bin.tar.gz\" | tar -zx --strip-components=1 -C \/home\/user\/apache-maven-$MAVEN_VERSION\/\nENV TERM xterm\n\nRUN wget -qO- \"http:\/\/archive.apache.org\/dist\/tomcat\/tomcat-8\/v8.0.24\/bin\/apache-tomcat-8.0.24.tar.gz\" | tar -zx --strip-components=1 -C \/home\/user\/tomcat8 && \\\n rm -rf \/home\/user\/tomcat8\/webapps\/*\nUSER root\nRUN echo -e \"JAVA_HOME=\/opt\/jdk$JAVA_VERSION_PREFIX\\nM2_HOME=\/home\/user\/apache-maven-$MAVEN_VERSION\\nTOMCAT_HOME=\/home\/user\/tomcat8\\nPATH=$JAVA_HOME\/bin:$M2_HOME\/bin:$PATH\" >> \/etc\/environment\nUSER user\nENV LANG C.UTF-8\n\n############# download ant\nRUN mkdir \/home\/user\/apache-ant-1.9.7 && wget -qO- \"http:\/\/apache-mirror.rbc.ru\/pub\/apache\/\/ant\/binaries\/apache-ant-1.9.7-bin.tar.gz\" | tar -zx --strip-components=1 -C \/home\/user\/apache-ant-1.9.7\nRUN sudo ln -s \/home\/user\/apache-ant-1.9.7\/bin\/ant \/usr\/bin\/ant\n########### cloning custom tomcat\nRUN sudo svn checkout --no-auth-cache https:\/\/subversion.devfactory.com\/repos\/AureaGCE_EGX\/misc\/tomcat-gce-embedded\/distributions\/8.0.28\/ \/home\/user\/8.0.28 --username 'asolodov' --password 'password' \nRUN sudo chmod +x \/home\/user\/8.0.28\/*.sh\nRUN sudo chmod +x \/home\/user\/8.0.28\/bin\/*.sh\n################\nWORKDIR \/projects\n\nCMD sudo \/usr\/bin\/ssh-keygen -A && \\\n sudo \/usr\/sbin\/sshd -D && \\\ntail -f \/dev\/null"
               },
               "name":"default",
               "type":"docker"
            },
			{  
               "dev":false,
               "limits":{  
                  "ram":2000
               },
               "servers":[  

               ],
               "envVariables":{  

               },
               "source":{  
                  "type":"dockerfile",
                  "content":"FROM 892905447879.dkr.ecr.us­east-1.amazonaws.com/aurea/ace:​treatment_v1.0"
               },
               "name":"treatment",
               "type":"docker"
            },
			{  
               "dev":false,
               "limits":{  
                  "ram":2000
               },
               "servers":[  

               ],
               "envVariables":{  

               },
               "source":{  
                  "type":"dockerfile",
                  "content":"FROM 892905447879.dkr.ecr.us­east-1.amazonaws.com/aurea/ace:​oracle_v11gR2"
               },
               "name":"oracle",
               "type":"docker"
            }
         ],
         "name":"default"
      }
   ]
}
![workspace_json_result](https://cloud.githubusercontent.com/assets/5715840/17258356/8487de28-55d7-11e6-85c6-b8ea5d8e9f39.png)
![workspace_json_start](https://cloud.githubusercontent.com/assets/5715840/17258357/8489ff64-55d7-11e6-81fb-278790ba3905.png)

**Comment by soanni** [comment]
version 4.4.0

**Comment by bmicklea** [comment]
@soanni - did you see any errors in the logs or console when you ran the JSON?
@garagatyi and @eivantsov please take a look at the JSON above.

**Comment by eivantsov** [comment]
Can you take a look at operations perspective? Maybe machines are there?

**Comment by soanni** [comment]
i think i know what the problem is. i will check it now. am i missing some parameter in JSON? as i can't create a factory on this workspace with this error

FailedYou are missing a mandatory parameter isDev. For more information, please visit http://docs.codenvy.com/user/project-lifecycle/#configuration-reference

**Comment by soanni** [comment]
@eivantsov yes now i managed to create multiple machine workspace bu now i'm not able to create a factory. the error is 

FailedYou are missing a mandatory parameter isDev. For more information, please visit http://docs.codenvy.com/user/project-lifecycle/#configuration-reference

**Comment by eivantsov** [comment]
@soanni can you share JSON you used to create a workspace?

**Comment by soanni** [comment]
@eivantsov, attaching
[json_workspace_ACE.txt](https://github.com/codenvy/codenvy/files/393522/json_workspace_ACE.txt)
 it

**Comment by soanni** [comment]
@eivantsov @bmicklea the workspace constructing correctly with 3 machines. Project is exported. I analyzed data structures but can't find this isDev parameter. Attached a screenshot with error
![isdev_error](https://cloud.githubusercontent.com/assets/5715840/17292819/556950fe-57fd-11e6-9723-c833bc5ec033.png)

**Comment by soanni** [comment]
this error message appears when the form is loaded

**Comment by mshaposhnik** [comment]
Issue with factory validation is fixed.

**Comment by eivantsov** [comment]
@soanni is the issue with creating and consuming a multi machine Factory resolved for your in the latest Codenvy version? If so, I will close the issue.
