### ISSUE TITLE
Puppet config isn't updated properly in time of changing Codenvy hostname when there are machine nodes

### ISSUE THREAD

**Issue by dmytro-ndp** [codenvy/codenvy#456]
Puppet config becomes misconfigured after the changing Codenvy onprem host name:
1) _/etc/puppet/puppet.conf_ on machine node contained absolute value of **certname** property
Fixup: https://github.com/codenvy/codenvy/blob/master/cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/helper/NodeManagerHelperCodenvy4Impl.java#L245
```
nodeCommands.add(createCommand(format("sudo sed -i 's/certname = %1$s/certname = %2$s/g' /etc/puppet/puppet.conf", node.getHost(), node.getHost().replace(oldHostName, newHostName)), node));
```

2) _/etc/puppet/autosign.conf_ on master wasn't updated with new machine node hostnames.

3) *$swarm_node* variable in _/etc/puppet/manifests/nodes/codenvy/codenvy.pp_ on master wasn't updated with new machine node hostnames.

4) we need to check if existed nodes with new hostname are available before changing hostname.

Codenvy on-prem version: <= 4.6.0-SNAPSHOT
Problem can be reliably reproduced: Yes

**Comment by bmicklea** [comment]
@dmytro-ndp is there a workaround for this?

**Comment by dmytro-ndp** [comment]
yes, I described fixup in description of the issue.
