### ISSUE TITLE
Update codenvy config and update of Codenvy version hung up on https://<hostname> address

### ISSUE THREAD

**Issue by dmytro-ndp** [codenvy/codenvy#459]
Codenvy update from binaries command hung up on because there is wrong url of checking aliveness of codenvy on-prem API server: https://github.com/codenvy/codenvy/blob/792d4fe93d8730d9a8f66af6c44466e22840579e/cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/ConfigManager.java#L375-L375
```
return "http://localhost/api";
```

There should be:
```
return "$host_protocol://$host_url/api";
```

We need to use dns of Codenvy instead of localhost in case of using https protocol when verifying Codenvy aliveness so as SSL-certificate signed to these one.
Use next command instead of HttpTransport:request() method class to avoid hanging up in time of requesting when Codenvy on-prem installed behind the proxy and dns is'not real.
```
curl -X OPTIONS {host_protocol}//:{host_url}/api/
```

_Another possible solution_: to change method **OPTIONS** on **GET** in request to https://codenvy.onprem/api/

Codenvy version: <= 4.6.0-SNAPSHOT
Problem can be reliably reproduced: Yes

**Comment by bmicklea** [comment]
@vkuznyetsov shouldn't this issue have a sprint/... label?
