### ISSUE TITLE
Add record '127.0.0.1 <new-hostname>' into /etc/hosts when changing Codenvy on-prem hostname

### ISSUE THREAD

**Issue by dmytro-ndp** [codenvy/codenvy#464]
Adding record **'127.0.0.1 <new-hostname>'** into _/etc/hosts_ when changing Codenvy on-prem hostname by _Installation Manager_ will allow user:
1) to avoid blocking changing hostname when new hostname unavailable;
2) to avoid going to docker container from API server by using external IP which could lead to usage of closed outside ports.

Codenvy version: <=4.5.1

**Comment by bmicklea** [comment]
This has affected quite a few customers - I'd like this to be considered for next sprint.
