### ISSUE TITLE
Can't checkout git repo in version 4.5.1

### ISSUE THREAD

**Issue by soanni** [codenvy/codenvy#476]
Error screen attached
![git_error_4_5_1](https://cloud.githubusercontent.com/assets/5715840/17180714/5d9f6ed4-542e-11e6-93da-bff7b4a0dbe9.png)

**Comment by eivantsov** [comment]
@soanni You are clocing a repository over htttps, that is most likely a private one. The only way to import a private repo (except for GitHub) is to generate/upload a key, save it to your git hosting account, and use SSH URL to clone a repo.

**Comment by soanni** [comment]
in version 4.4.0 we did the same thing like
https://username:password
It worked out

**Comment by bmicklea** [comment]
@soanni - so in 4.4 you accessed the same repo with the same HTTPS protocol using username and password and it was pulled in?

 My understanding has been the same as @eivantsov that we need SSH keys for private repos.

**Comment by soanni** [comment]
@bmicklea yeah in 4.4 i did excatly the same thing used the same links (https) everything worked

**Comment by bmicklea** [comment]
@vparfonov can you check to see if something changed between 4.4 and 4.5.1 that would prevent someone from pulling from a private repo with https://username:password/...

**Comment by bmicklea** [comment]
@soanni - in the screenshot it looks like you're trying to use Stash but selecting GitHub on the left. Do you get the same error by selecting "git" on the left and using the https://username:password/... syntax?

**Comment by eivantsov** [comment]
@soanni in 4.5.1 we started using JGit rather than native Git. I can confirm that `https://$username:$pass@$host/$account/$repo.git` works in 4.4.0 but does not work in 4.5.1 probably because JGit does not support it.

**Comment by soanni** [comment]
Okay, i got it. thank you
