### ISSUE TITLE
Can't install version 4.4.0

### ISSUE THREAD

**Issue by soanni** [codenvy/codenvy#477]
When i'm trying to install version 4.4.0 with command

bash <(curl -L -s https://start.codenvy.com/install-codenvy) --version=4.4.0

 i got this error message

tail /home/centos/codenvy/install.log
---------------------------------------
[CODENVY] Disable SELinux          - [FAIL]
[CODENVY] {
  "artifacts" : [ {
    "artifact" : "codenvy",
    "version" : "4.4.0",
    "status" : "FAILURE"
  } ],
  "message" : "codenvy:4.4.0 is not installable",
  "status" : "ERROR"
}

**Comment by eivantsov** [comment]
@soanni I have just tested this command on a clean Centos instance. The installer works as expected. Are you trying to install 4.4.0 on a node that already has Codenvy installed or are you using a clean instance?

**Comment by soanni** [comment]
No clean intance

**Comment by soanni** [comment]
this is full log

**Comment by soanni** [comment]
Install java package from 'http://download.oracle.com/otn-pub/java/jdk/8u45-b14/jre-8u45-linux-x64.tar.gz' into the directory '/home/centos/codenvy/jre' ...  [OK]
https://codenvy.com/update/repository/public/download/installation-manager-cli
[CODENVY] Downloading might take several minutes depending on your internet connection. Please wait.
   0%        1%        3%        4%        6%        7%        9%        10%        12%        13%        15%        16%        17%        19%        20%        22%        23%        25%        26%        28%        29%        30%        32%        33%        35%        36%        38%        39%        41%        42%        43%        45%        46%        48%        49%        51%        52%        54%        55%        57%        58%        59%        61%        62%        64%        65%        67%        68%        70%        71%        73%        74%        75%        77%        78%        80%        81%        83%        84%        86%        87%        89%        90%        92%        93%        95%        96%        97%        99%        100%        100%     [CODENVY] {
  "artifacts" : [ {
    "artifact" : "codenvy",
    "version" : "4.4.0",
    "label" : "STABLE",
    "file" : "/home/centos/codenvy/updates/codenvy/4.4.0/codenvy-4.4.0.zip",
    "status" : "DOWNLOADED"
  } ],
  "status" : "OK"
}
[CODENVY] {
  "artifacts" : [ {
    "artifact" : "codenvy",
    "version" : "4.4.0",
    "label" : "STABLE",
    "file" : "/home/centos/codenvy/updates/codenvy/4.4.0/codenvy-4.4.0.zip",
    "status" : "DOWNLOADED"
  } ],
  "status" : "OK"
}
[CODENVY] Disable SELinux          - [FAIL]
[CODENVY] {
  "artifacts" : [ {
    "artifact" : "codenvy",
    "version" : "4.4.0",
    "status" : "FAILURE"
  } ],
  "message" : "codenvy:4.4.0 is not installable",
  "status" : "ERROR"
}
Install java package from 'http://download.oracle.com/otn-pub/java/jdk/8u45-b14/jre-8u45-linux-x64.tar.gz' into the directory '/home/centos/codenvy/jre' ...  [OK]
https://codenvy.com/update/repository/public/download/installation-manager-cli
[CODENVY] Downloading might take several minutes depending on your internet connection. Please wait.
   0%     [CODENVY] {
  "artifacts" : ,
  "status" : "OK"
}
[CODENVY] {
  "artifacts" : [ {
    "artifact" : "codenvy",
    "version" : "4.4.0",
    "label" : "STABLE",
    "file" : "/home/centos/codenvy/updates/codenvy/4.4.0/codenvy-4.4.0.zip",
    "status" : "DOWNLOADED"
  } ],
  "status" : "OK"
}
[CODENVY] Disable SELinux          - [FAIL]
[CODENVY] {
  "artifacts" : [ {
    "artifact" : "codenvy",
    "version" : "4.4.0",
    "status" : "FAILURE"
  } ],
  "message" : "codenvy:4.4.0 is not installable",
  "status" : "ERROR"
}

**Comment by soanni** [comment]
may be sudoer rights

**Comment by soanni** [comment]
no, i corrected sudoer then give the owner rights to the home folder, closed SSH. The same error. I'm installing codenvy on amazon ec2, before version 4.5.1 i did the same things and i installed without any errors (on another instance from the same amazon centos image). Probably the cause is the error 
[CODENVY] Disable SELinux - [FAIL]

**Comment by soanni** [comment]
btw when i trying to install the last version

bash <(curl -L -s https://start.codenvy.com/install-codenvy)

everything is working out

**Comment by TylerJewell** [comment]
Interesting.  If you do version=4.4.2, is there a difference?

Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by soanni** [comment]
i tried it. the message was that there are no such version in the repo. the last versions are 4.4.0,4.5.1

**Comment by soanni** [comment]
yeah, 4.5.1 is installed :)

**Comment by bmicklea** [comment]
@soanni just out of curiosity if you have 4.5.1 why are you wanting to go back to 4.4?

**Comment by soanni** [comment]
@bmicklea 4.5.1 is buggy

https://github.com/eclipse/che/issues/1967

**Comment by soanni** [comment]
on 4.4 everything was ok. I almost loved it (almost because there are some concerns about snapshotting mechanism)

**Comment by eivantsov** [comment]
I cannot reproduce it both on Digital Ocean node and vagrant

**Comment by eivantsov** [comment]
@soanni this is the list of available versions - https://codenvy.com/update/repository/updates/codenvy

A few of them worked for me. Are you certain you are trying on a clean node and the latest installation manager is installed?

**Comment by soanni** [comment]
@eivantsov @dmytro-ndp i tried a couple of other CentOS 7 amazon images and on one of them the installation is going ok. it seems a little bit strange that yesterday i managed to install 4.5.1 easily and struggled with 4.4.0 installation on the same instance.
But the issue is solved anyway. Thank you a lot.
