### ISSUE TITLE
Improve pre-flight check to verify all necessary ports are available

### ISSUE THREAD

**Issue by dmytro-ndp** [codenvy/codenvy#480]
## Pre-Flight Checks Specification
The biggest area where new installations are failing is around networking configuration. Sometimes, certain networking elements cannot be verified easily. 
- [ ] Verify all necessary [ports are open](http://superuser.com/questions/621870/test-if-a-port-on-a-remote-system-is-reachable-without-telnet).   Another [page discussing this](http://serverfault.com/questions/560081/check-port-open-without-telnet). We may need to have a simple bash service which launches a server listening on the port and then launches a client to connect to that port.  There is this description of [nmap](http://stackoverflow.com/questions/1168317/check-status-of-one-port-on-remote-host).  [There is also this description](http://www.commandlinefu.com/commands/view/8075/determine-if-tcp-port-is-open). Since the ephemeral port range is very large, we only need to verify that a couple of the ports are open - a sampling.

- [ ] Output of the pre-flight checks.  This will appear after we test access to the repositories.
```
http://mirrorlist.centos.org                                   [OK]

Verifying ports...
22:           SSH (installation)                               [OK / NOT OK]
80:           HTTP                                             [OK / NOT OK]
81:           HAProxy (workspace routing)                      [OK / NOT OK]
443:          HTTP/s                                           [OK / NOT OK]
444:          HAProxy/s                                        [OK / NOT OK]
32768-65535:  Docker                                           [OK / NOT OK]
```
If there are checks that fail for the port opening, then:
```
Some mandatory ports are not open. Codenvy may not work properly.
You can test open ports with ` ... `.  
Proceed with the installation? [y/N]
```

- [ ] If the `--suppress` flag is provided, then all checks will be ignored and the installation should proceed normally.

**Comment by TylerJewell** [comment]
@dmytro-ndp - hi!  With this improvement, we no longer need to check port 444.
https://github.com/codenvy/codenvy/issues/869

**Comment by TylerJewell** [comment]
Replaced with dockerized solution.
