### ISSUE TITLE
Unexpected disappearense project from the project explorer

### ISSUE THREAD

**Issue by artaleks9** [codenvy/codenvy#481]
**Reproduction Steps:**

1. Create new workspace.
2. Import some project (e.g. https://github.com/idexmai1/Spring_Simple.git).
3. Expand the project.

**Expected behavior:**
The project should be expanded

**Observed behavior:**
The project disappears from the project explorer

**Codenvy version:** 4.6.0
**OS and version:** Ubuntu OS 14.0

**Additional information:**

[disappearense_project.ogv.zip](https://github.com/codenvy/codenvy/files/388154/disappearense_project.ogv.zip)

Related selenium test: StateProjectAfterRestartWsTest

**Comment by riuvshin** [comment]
@artaleks9 can you please provide workspace configuration? it seems you've used 1GB workspace which is not enough.

**Comment by riuvshin** [comment]
Close as duplicate.
