### ISSUE TITLE
Backup subs-system removes projects of workspace in some cases

### ISSUE THREAD

**Issue by garagatyi** [codenvy/codenvy#488]
Recent changes #425 introduced a bug into backup/restore projects process.
In some cases projects of workspace can be removed from backup sub-system.

Reproduction Steps:

1. Start WS
2. Create project
3. Stop WS
4. Broke restore script (network outage during restore will behave in the same way as broken script)
5. Start WS (it will fail)
6. Fix restore script (network outage is gone)
7. Start WS again
8. Stop WS

Expected behavior:

Workspace is up and project is present

Observed behavior:

Workspace is up but no project is in it. And no project in backup storage of workspace.

Codenvy version: 4.6.0-Snapshot

Additional information:

Problem only started happening recently, didn't happen in an older version of Codenvy: [Yes]
Problem can be reliably reproduced: [Yes]

**Comment by JamesDrummond** [comment]
Does this issue also effect eclipse/che project or is it specific to codenvy only?

**Comment by garagatyi** [comment]
Codenvy only
