### ISSUE TITLE
inconsistent results on javascript

### ISSUE THREAD

**Issue by gregeb13** [codenvy/codenvy#489]
** If you are a Codenvy customer or have a trial license please file your issues with Support through email. GitHub issues do not have a response SLA.**

[Short description of problem here]

teaching a class on javascript- 12 students, 10 different results, mostly failing with exact same source
code.

Reproduction Steps:

1- clone this project:https://codenvy.com/ws/tkp/tkp-ce-student
[First Step]
[Second Step]
run spiral.js 
make a few edits. ( 12 different students)
build and run..
[Other Steps...]
Expected behavior:
all 12 students should have the exact same results.

some builds fail, some builds work but no tortoise is shown
some tortoise shows and actually draws a spiral parttern.

totally all over the map.
this code worked fine 8 mos ago.

[Describe expected behavior here]

Observed behavior:

[Describe observed behavior here]

Codenvy version: [Enter Codenvy version here]
OS and version: [Enter OS name and version here]

Additional information:

Problem only started happening recently, didn't happen in an older version of Codenvy: [Yes / No]
Problem can be reliably reproduced: [Yes / No - it's random]
---code is below--

//package org.teachingkidsprogramming.recipes.completed.section01forloops;
package org.teachingkidsprogramming.section01forloops;

import org.teachingextensions.logo.Tortoise;
//import org.teachingextensions.logo.utils.ColorUtils.PenColors;
import org.teachingextensions.virtualproctor.VirtualProctor;

public class SimpleSquare
{
  public static void main(String[] args) 
  {
    //  Show the tortoise --#1
 Tortoise.show();
    //  Make the tortoise move as fast as possible --#6
  
    //  Do the following 4 times --#5.1
    //      Change the pen color of the line the tortoise draws to blue --#4
     // Tortoise.setPenColor(PenColors.Blues.Blue);
      //      Move the tortoise 50 pixels --#2
      //   
      Tortoise.setSpeed(10);   
    for (int j=0; j < 200; j++){    
      for (int i =0; i<4;i++){ 
        Tortoise.move(50);
          Tortoise.turn(90);               
      }
    Tortoise.turn(45);
  }
      
      //      Turn the tortoise to the right (90 degrees) --#3
      
 
    //  Repeat --#5.2
    //
    //  (Optional): Sign your work using the Virtual Proctor 
    //  See your work at http://virtualproctor.tkpjava.org
    VirtualProctor.setClassName("TKPHouse");
    VirtualProctor.setName("LynnLangit");
  }
}

**Comment by eivantsov** [comment]
@gregeb13 i cannot find any .js files in the project you have mentioned. It builds and runs ok for me though.
![vnc](https://cloud.githubusercontent.com/assets/5337267/17283059/1455d954-57b5-11e6-9fe5-24d93d2106d0.png)

**Comment by eivantsov** [comment]
@gregeb13 any update please?

**Comment by gregeb13** [comment]
No-
My class is over- i had 13 students running the same code with various results-
I'm baffled

Learn to code; Code to Learn

**Comment by eivantsov** [comment]
Closing the issue. Feel free to reopen with more details. The project you shared did not have any JS code in it.
