### ISSUE TITLE
PULL reports Failed to get private ssh key

### ISSUE THREAD

**Issue by keithmarsh** [codenvy/codenvy#491]
Pull fails from remote saying Failed to get private ssh key

Reproduction Steps:

Create a blank workspace
open project in ide
profile preferences vcs generate
hostname rhcloud.com
view, select and copy 
create public key in openshift using paste
close
git remotes remotes
add
ssh://xxxxxxxxxxx@yyyyyyyyyyy.rhcloud.com/~/git/zzzz.git/
close
git remotes pull
Failed to get private ssh key. You can create a new SSH key pair in Profile->Preferences->SSH->VCS.

Expected behavior:
On a shell on my machine I can init a git repository and set the remote to the url above and pull

Observed behavior:
Dialog pops up saying 

Failed to get private ssh key. You can create a new SSH key pair in Profile->Preferences->SSH->VCS.

Codenvy version: Version :4.5.1Revision :95cc669178301382Build Time :2016-07-19 10:25:55

Additional information:

Problem only started happening recently, didn't happen in an older version of Codenvy: First try with codenvy

Problem can be reliably reproduced: Yes

**Comment by eivantsov** [comment]
@keithmarsh that is definitely not expected behavior. This flow works with most git hosting providers. I'll register an account and try it myself.

**Comment by eivantsov** [comment]
@keithmarsh can you elaborate on what openshift cloud do you use? Is it OpenShift v2?

**Comment by keithmarsh** [comment]
It's a standard account, not the NetGen one.  I'm using a Tomcat 7 gear.

**Comment by eivantsov** [comment]
@keithmarsh can you point me to the site please?

**Comment by keithmarsh** [comment]
Here you go.
https://openshift.redhat.com/app/login?then=%2Fapp%2Fconsole

**Comment by keithmarsh** [comment]
Fantastic.  That works.  Thank you both.
