### ISSUE TITLE
Apply the new list component to factories list

### ISSUE THREAD

**Issue by ashumilova** [codenvy/codenvy#494]
Grid component should be applied to the list of factories

Mockup of the list needed.

**Comment by slemeur** [comment]
After reviewing the work done on the new list, the overall work is nice. See https://github.com/eclipse/che/pull/1680. There are some little details that are needing some more work (ordered by priority) :

For factories screens:
- [ ] Factories list: Remove the description of the factory from the list
- [ ] Factories list: Make the header consistent with the header of the list of workspaces
- [ ] Factories list: Update the action section - we should not see the “Open in IDE” button anymore, but the actions should be listed as on the workspaces’ list
- [ ] Factory creation: In the “New Factory” form, when creating from “Workspace”, the list of workspaces has not been revisited
- [ ] Factory details: The list of actions and commands have not been revisited
- [ ] Factory details: Remove the "Commands" and "Actions" titles when the table is there.
![screen_shot_2016-08-15_at_10_29_25](https://cloud.githubusercontent.com/assets/1636769/17659505/4b913b9c-62d3-11e6-996d-7e6cf2ffa38a.png)
- [ ] Factory details: For "Commands" and "Actions", we should have an empty state for the table, bellow the "Add" button with a small sentence "No commands configured" / "No actions configured" (possibly with a gray background)
