### ISSUE TITLE
Factories with open file action do not got to the workspace

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#507]
Reproduction Steps:
1) Create the Spring project in the existed workspace.
2) Go to the dashboard and create new factory with open file action.
3) Click on the Done button and next click on the Open button
**Expected behavior:** we should consume the factory with open file feature.

**Observed behavior:**  we stay on the creation page and do not go to the workspace

**Expected behavior:** after clicking on the fires item the Compare button should be enabked
**Observed behavior:** after clicking on the fires item the Compare button still disabled
**Che version:**    4.6.0
**OS and version:** Ubuntu OS 14.0
**Docker version:** 1.11.2
**Che install:**  local bundle

**Comment by riuvshin** [comment]
@ashumilova please take this in current sprint seems a really critical issue.

**Comment by olexii4** [comment]
https://github.com/codenvy/codenvy/pull/540
