### ISSUE TITLE
Reorganize install.codenvycorp.com and start.codenvy.com servers

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#508]
Today we have two servers:
1. `install.codenvycorp.com` with all the binaries (it's a download server)
2. `start.codenvy.com/codenvy-install` automatically executes the bootstrap script

We want:
- [x] Calling `get.codenvy.com` to automatically execute the bootstrap script
- [x] Ideally: `che.eclipse.org/scripts` will house all the che scripts (this can only be done if it won't effect the blog.

**Comment by benoitf** [comment]
the mimetype for sh will need to be text/plain so we can see the content when using URL in browser

`AddType text/plain sh` for Apache2 conf

**Comment by riuvshin** [comment]
Done.
Script is available http://che.eclipse.org/scripts/che.sh

**Comment by TylerJewell** [comment]
@bmicklea - please assign to James to go through and test + update the docs.codenvy.com pages to support this new get.codenvy.com URL.

**Comment by JamesDrummond** [comment]
In doc `https://dash.readme.io/project/codenvy/v4.7/docs/custom-assemblies` it's states `https://get.codenvy.com/codenvy/` downloads the codenvy source code. It downloads `install-codenvy.sh` script when I browse to it. Is this what is suppose to happen?

**Comment by JamesDrummond** [comment]
I updated the upcoming 4.7 documents. Did this need to get done for 4.4 or 4.3 too?

**Comment by TylerJewell** [comment]
yes.  The URL is `https://get.codenvy.com/`.

**Comment by TylerJewell** [comment]
Just 4.7 will be ok.
