### ISSUE TITLE
Share a workspace: User not found message when sharing a workspace

### ISSUE THREAD

**Issue by eivantsov** [codenvy/codenvy#509]
Right now when attempting to add a user to a workspace and this user isn't a Codenvy user yet, there's no clue in User Dashboard why a user cannot be added. That is why it is perceived as bug.

Reproduction Steps:

1. Workspaces > Share
2. Try adding a user noname@codenvy.com
3. Share button is inactive

Expected behavior:

A message show show up - User with email noname@codenvy.com not found. Workspaces can be shared with registered users only.

Observed behavior:

Share button is inactive.

**Comment by ashumilova** [comment]
Resolved
