### ISSUE TITLE
How do I/Am I able to connect to the Tomcat8 server?

### ISSUE THREAD

**Issue by dayv1e** [codenvy/codenvy#516]
Greetings,

I am currently testing https://beta.codenvy.com. My goal is to build and deploy a simple JSF Project.  I have already built the .war file with maven and moved it to  $TOMCAT_HOME/webapps/ROOT.war

The operations perspective tells me that the Tomcat8 server ist listening on: 
http://node3.beta.codenvy.com:41362

tomcat8
8080/tcp
node3.beta.codenvy.com:41362
http://node3.beta.codenvy.com:41362

To which url do I have to connect to see the preview of my project?

**Comment by ddementieva** [comment]
@dayv1e Have you started Tomcat successfully?

Try the following command to deploy war and start Tomcat: `cd ${current.project.path} && mvn clean install && cp ${current.project.path}/target/*.war $TOMCAT_HOME/webapps/ROOT.war && $TOMCAT_HOME/bin/catalina.sh run`. Add it to the CMD widget with http://${server.port.8080} as a Preview URL and run it.

**Comment by eivantsov** [comment]
@dayv1e Any update on this please?
