### ISSUE TITLE
Wrong display status 'Pull request updated' on the 'Pull Request' panel.

### ISSUE THREAD

**Issue by AndreyChizhikov** [codenvy/codenvy#518]
**Reproduction Steps:**
1. Import project from GItHub
2. Click on parent folder for this project
3. Open any file and change it.
4. Open 'Pull Request' panel and create new branch
5. Click on 'Create PR' button
6.Update content in the file.
7. Click on 'Update PR' button

**Expected behavior:**
Pull request has been updated.
Status 'Pull request updated' **with flag**  has been presented in the status area.

**Observed behavior:**
Pull request has been updated.
Status 'Pull request updated' **without flag**  has been presented in the status area.

![update_pr](https://cloud.githubusercontent.com/assets/8051404/17402296/356b7ae2-5a5b-11e6-92df-473b028c9d8b.png)

Codenvy version: 4.6.0
OS and version: Ubuntu 14.04 LTS

**Comment by vinokurig** [comment]
Can not reproduce in 4.8

**Comment by AndreyChizhikov** [comment]
Issue is still actual if you imported project from your own GitHub repo.
