### ISSUE TITLE
Starting auxiliary machines inside workspace during the build

### ISSUE THREAD

**Issue by soanni** [codenvy/codenvy#519]
Hello, Codenvy Team.

I have one really interesting question and i really need your opinion and expertise.
I'm integrating the Java project in Codenvy that requires during the build to pull and run 2 containers from Docker Hub. 
To make long story short maven pulls and starts 2 images using docker-compose.
This is docker-compose file:

-------------------------------------------
version: '2'

services:

  teamcity:
    image: jetbrains/teamcity-server:latest
    ports:
      - "8111:8111"
    volumes:
      - ./data/teamcity_server/datadir:/data/teamcity_server/datadir
      - ./data/teamcity_server/logs:/opt/teamcity/logs

  teamcity-agent:
    image: jetbrains/teamcity-agent
    environment:
      - SERVER_URL=http://teamcity:8111
      - AGENT_NAME=default-agent
    volumes:
      - ./data/teamcity_agent/conf:/data/teamcity_agent/conf
    depends_on:
      - teamcity

--------------------

you can see that it pulls teamcity-server image, exposes port 8111, creates a volume for data to run teamcity on.
the second dependent service is teamcity-agent.
How i'm doing it now:

I created a workspace inherited from centos7/jdk8 image, exposed ports 8111, 7990 needed for the application, installed docker, docker-compose. Dockerfile attached.
In Codenvy server config i enabled priviliged mode for Docker in order to make Docker run inside Docker (workspace). I can start the docker daemon inside workspace with errors and i can build the product also with errors regarding networking. And i understand that running Docker inside Docker and enable priviliged mode is not a best way to go.
What i'm thinking is to find the way to start during the build (we are using maven-wrapper) 2 containers inside host machine (for example using Codenvy REST API) not inside the workspace container. But the build is running inside the workspace container so i don't know is it possible or not. That would be the best way to go here.

Thank you.

**Comment by soanni** [comment]
[QualityGateCentOS.txt](https://github.com/codenvy/codenvy/files/401926/QualityGateCentOS.txt)

**Comment by eivantsov** [comment]
@soanni yes, Docker in Docker is indeed not the best way to go. What you can do is:

* in your Dockerfile

ENV DOCKER_HOST tcp://$IP:2375

where $IP is internal IP of your node. You may need to make sure you can trigger Docker API via this URL, i.e. allow connections from internal network. You may check it this way:

curl http://$IP:2375/version - do it from the host machine (will work for sure) and from the container (not necessarily the one with Docker installer)

So, when a build process triggers Docker in the container, it will actually trigger Docker API on the host machine. As a result, you will see two containers running on the host machine beside the workspace container and containers with auxiliary machines if any. 

Note that Docker version on the host and in the container should match (ideally), at least API versions should be the same for server  (on the host)

**Comment by soanni** [comment]
@eivantsov i'm trying to solve this way

CMD sudo dockerd -H tcp://172.17.42.1:2375 && tail -f /dev/null

But the daemon can't listen on this 172.17.42.1 address (docker0 interface on node instance).
I can ping it, can do
telnet 172.17.42.1 80

But
telnet 172.17.42.1 2375 error No route to host

Of course i can't do inside container 

curl http://172.17.42.1:2375/version

But it works perfectly inside host machine.
Smth is wrong with routing and i can't figure out what's the problem.

**Comment by soanni** [comment]
i'm trying to catch packets on the host

sudo tcpdump -i docker0 dst port 2375

and i can see when i'm doing from container

telnet 172.17.42.1 2375

the host recieves the packets

**Comment by soanni** [comment]
i'm thinking about firewall rules on host.
The container ip is 172.17.0.2
The result of iptables -L on host is

Chain INPUT (policy ACCEPT)
target     prot opt source               destination
f2b-SSH    tcp  --  anywhere             anywhere             tcp dpt:ssh
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
ACCEPT     icmp --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     tcp  --  anywhere             anywhere             state NEW tcp dpt:ssh
ACCEPT     tcp  --  anywhere             anywhere             state NEW tcp dpt:domain
ACCEPT     udp  --  anywhere             anywhere             state NEW udp dpt:domain
ACCEPT     tcp  --  anywhere             anywhere             state NEW tcp dpt:http
ACCEPT     tcp  --  anywhere             anywhere             state NEW tcp dpt:81
ACCEPT     tcp  --  anywhere             anywhere             state NEW tcp dpt:https
ACCEPT     tcp  --  anywhere             anywhere             state NEW tcp dpt:snpp
ACCEPT     tcp  --  anywhere             anywhere             state NEW tcp dpt:ldap
ACCEPT     tcp  --  anywhere             anywhere             state NEW tcp dpt:commplex-main
ACCEPT     tcp  --  anywhere             anywhere             state NEW tcp dpt:irdmi
ACCEPT     tcp  --  anywhere             anywhere             state NEW tcp dpt:cslistener
ACCEPT     tcp  --  anywhere             anywhere             state NEW tcp dpt:zabbix-agent
ACCEPT     tcp  --  anywhere             anywhere             state NEW tcp dpt:zabbix-trapper
ACCEPT     tcp  --  anywhere             anywhere             state NEW tcp dpt:27017
ACCEPT     tcp  --  anywhere             anywhere             state NEW tcp dpt:32001
ACCEPT     tcp  --  anywhere             anywhere             state NEW tcp dpt:32101
ACCEPT     udp  --  anywhere             anywhere             state NEW udp dpt:snmp
ACCEPT     tcp  --  anywhere             anywhere             state NEW tcp dpts:filenet-tms:65535
ACCEPT     tcp  --  anywhere             anywhere             state NEW tcp dpt:ldoms-migr
ACCEPT     tcp  --  anywhere             anywhere             state NEW tcp dpt:8140
ACCEPT     tcp  --  anywhere             anywhere             state NEW tcp dpt:32102
ACCEPT     tcp  --  anywhere             anywhere             state NEW tcp dpt:32202
ACCEPT     tcp  --  anywhere             anywhere             state NEW tcp dpt:postgres
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
DOCKER-ISOLATION  all  --  anywhere             anywhere
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             172.17.0.0/16
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain DOCKER (1 references)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             172.17.0.1           tcp dpt:sd
ACCEPT     tcp  --  anywhere             172.17.0.1           tcp dpt:webcache
ACCEPT     tcp  --  anywhere             172.17.0.1           tcp dpt:irdmi
ACCEPT     tcp  --  anywhere             172.17.0.1           tcp dpt:found
ACCEPT     tcp  --  anywhere             172.17.0.1           tcp dpt:ds-user
ACCEPT     tcp  --  anywhere             172.17.0.1           tcp dpt:ds-srvr
ACCEPT     tcp  --  anywhere             172.17.0.1           tcp dpt:ssh
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:8111
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:webcache
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:irdmi
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:7990
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:found
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:ds-user
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:ds-srvr
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:ssh

Chain DOCKER-ISOLATION (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

Chain f2b-SSH (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

**Comment by soanni** [comment]
yes the default firewall rules on the host is blocking connection from container to host Docker port. In order to allow you need to add this rule 
iptables -I INPUT 4 -i docker0 -j ACCEPT

**Comment by soanni** [comment]
@eivantsov okay now i'm able to start the containers on host from inside the container.
But the thing is after i'm stopping the workspace those containers that were created during the source build are still running. Is there any possible way to make them stopped and destroyed after the workspace is stopped? and if i can somehow make them appear in the machines list on operations perspective with all the features like info about ports, terminal that would be awesome.
Thank you.

**Comment by eivantsov** [comment]
@soanni I'll be closing this issue - creating a workspace using REST API solves this issue. Machines added in the runtime are not saved into a workspace config. Once multi machine workspaces are rolled out this limitation is gone.
