### ISSUE TITLE
How can I get the URL to preview my own server?

### ISSUE THREAD

**Issue by Megabyte918** [codenvy/codenvy#526]
Hello everyone, I recently started using [beta.codenvy.com](https://beta.codenvy.com) do do my coding and testing on, but I am unable to preview my changes because I have no idea how I can access the URL to my server.

I go to the servers tab and I see that It says the server adresses are these:
- node1.beta.codenvy.com:50115
- beta.codenvy.com:444
- node1.beta.codenvy.com:50119
- node1.beta.codenvy.com:50120
- node1.beta.codenvy.com:50117
- node1.beta.codenvy.com:50114

But it also says under "URL" that the url for the server preview is actually this:
https://beta.codenvy.com:444/50118_node1.beta.codenvy.com/wsagent/ext

Unfortunately, none of these are correct and I cannot connect to my server through them. I tried searching online if anyone had the same issue or knew how to get the URL or how to preview but I couldn't find anything so I thought I'd ask here :/

Can anyone help me with getting the URL so I can preview my project? Any help at all would be greatly appreciated :)

**Comment by TylerJewell** [comment]
Hello @Megabyte918.  The information that you are looking for is related to Commands and Previews. A command is used to launcher your server in the workspace and then a preview is used to retrieve its URL.  The preview URL is converted into the right URL:PORT as your server will be running inside of a container that has a Docker epehemeral port, even if you bound it to something like port 9000.

We document this in Eclipse Che's docs, which will work the same in Codenvy as well.
https://eclipse-che.readme.io/docs/previews

One important part about previews is that you must EXPOSE the port in your Dockerfile before the server starts. We expose some ports, for common server bindings. But if you want to use a new port, then the Dockerfile has to explicitly include that EXPORT in it before the ws is created.  We have a feature coming up soon where these ports will be configured in the dashboard where you configure your workspace definition.

**Comment by Megabyte918** [comment]
How can I access my "dockerfile" to expose the ports? Where is it located?

**Comment by TylerJewell** [comment]
Read about provide custom workspace recipes in the docs.  Read the environments, stacks and recipes page.  https://eclipse-che.readme.io/docs/stacks

**Comment by eivantsov** [comment]
@Megabyte918 did you manage to expose the right port for your server? Feel free to ask questions.

**Comment by TylerJewell** [comment]
@Megabyte918 - any follow up here?

**Comment by Megabyte918** [comment]
Sorry sorry, this got buried in emails
I ended up finding it, I created a new workspace and the URL ended up actually being in the servers tab, I don't know why it wasn't working before, but I have it now. Thanks for all your help :)
[Here's where I found it](https://images-1.discordapp.net/.eJwNyEsOhCAMANC7cABa5CO69SQNEjRRS2hdTebuM2_5PuYdl1nNodplBdhPKTx2K8qDWrWNuV2V-im28A2kSuW466MCk3MxJZ98nl3GGAL-a4mTR4-Yl5Bijgk26vqOavvTzPcHAuwimg.cTeOJIXAarbTVzvRId_aqFBe2Ig)

**Comment by kckaiser** [comment]
Thanks @Megabyte918, I was looking everywhere for this.  After looking at your link I happen to go back to my project and see it in the [terminal window here](http://www.clipular.com/c/6105348647944192.png?k=n2wEUEQMuMcCedbwiAUttcvn2AU)

**Comment by Joel-Torres** [comment]
Is there a video tutorial on how to view your pages locally? I'm new at this.
