### ISSUE TITLE
Import from github

### ISSUE THREAD

**Issue by VitaliyAT** [codenvy/codenvy#528]
When I do import project from github it download all to folder '/projectName/', but not like I need in '/'. On Cloud9 it work as I want - clone it to '/'. If I do it manually in terminal I get my folders in '/' + '/.git', but without any files, plus git menu work (active) only under '.git' folder.

**Comment by TylerJewell** [comment]
You can clone manually in the terminal into the / directory.  But Che and Codenvy has a special construct called a project with type.  When a repo is imported it is transformed into a project with its own directory.  The typing then imbues the project with special behaviors and the ide even changes its contents and plugins as a result.

You can change the location of where projects are managed using Che properties.  The default is /projects.

**Comment by VitaliyAT** [comment]
what if part of command prefer **Atom**/**Sublime**/**Brackets**/**WebShtorm** and "offline", others fall in love to **Cloud9**, and some want jump on **codenvy** or **eclipse che** ? As I can understand codenvy it's fork of last one. Anyway in all other platforms it work from root? here from folder - what i will have in repo? is this architecture in  **codenvy** support back push in the same positions as it was pulled?

**Comment by TylerJewell** [comment]
The other products do not let you define your own dockerfile, which you can do with Che.   and that lets you define a working directory which will be the root of installed software along with the location where projects are stored.

The directory is important as this more closely resembles the architecture of classic IDEs like Eclipse, Visual Studio, or Intellij.  Those products define a workspace and project location.

Keep in mind that Che and Codenvy takes the projects and rsyncs them to long term storage.  So there has to be a targeted location for the projects for this replication.

You could change the Che property from /projects to /, though it hasn't been tested for any side affects.

But the rationale is not clear.  A good project structure should allow for operation in any directory for any clone.

**Comment by VitaliyAT** [comment]
Could you suggest some article or video with those best practice of project architecture described? I understand that it's not the theme of github issue, but it give more Codenvy understanding, on what principles it based, with what ideas it made. Thank you.

**Comment by gazarenkov** [comment]
Codenvy/Che works as following:
- it contains single workspace directory as a root of projects. By default it is configured to /projects, it can be changed with property
- all the top level directories (like /projects/dir) are interpreted as "projects". 
- In case if there are no project config information for it - such a directory is considered as not-configured (blank) project. And files are not expected here (just ignored I think)

So, no, making a project inside workspace root is not expected.

And so far I do not see what kind of problem may experience team with different tools preferences taking into account that it uses Git. 
Please elaborate more in details what is the case you blocked (if still actual)
