### ISSUE TITLE
Preload a set of Factories into a CE installation

### ISSUE THREAD

**Issue by TylerJewell** [codenvy/codenvy#530]
Every CE installation should have a default set of Factories that are available within the database and immediately available after installation.  These Factories should have pretty names that make them human readable and easy to consume.

The Factories that we would want should be similar (or identical) to the ones we provide here:
https://www.eclipse.org/che/getting-started/cloud/.

We only want a small number pre-loaded:
1: Vert.x
2: .NET
3: Angular 2
4. C++
5. Java (what we call Java + Maven)
6. Node.js
7. PHP
8. Spring
9. Wildfly

**Comment by skabashnyuk** [comment]
Our solution for this task consist from two parts. 
1. Loader. We think that it should work with folder that contains list of factory json files. It's more reliable solution when single json file. Because it would be very hard to edit one big json file.
2. Preparation and testing of factory json files itself. 

Estimation is about ~5-8 SP (~2-3d)

**Comment by TylerJewell** [comment]
Can you comment more on why we need #2 - don't we already prepare and test factory JSON as part of our smoke tests? 

The loader would take a series of factory.json files and then load them into the database - and give them some sort of pre-defined pretty name, correct?

**Comment by skabashnyuk** [comment]
>Can you comment more on why we need #2 - don't we already prepare and test factory JSON as >part of our smoke tests?

Its more like routine work. Find out the place with correct json files, put in correct place, make  sure we have all the list of factories, test it.

>The loader would take a series of factory.json files and then load them into the database - and >give them some sort of pre-defined pretty name, correct?
yes. Something like https:/blha-blah.com/f?user=prodadmin&name=factorynamefromjson

**Comment by TylerJewell** [comment]
That would be the URL format.  In the UD where the factories are listed, isn't there a pretty-pretty name - something human readable like, "Java / Maven / Spring PetClinic"?

**Comment by skabashnyuk** [comment]
Afaik we don't have something like factory description. Current name should be url friendly and I think it's not quite suitable for that you call "pretty-pretty name".
We can think about it if you want.

**Comment by TylerJewell** [comment]
We do have this name - it appears in the dashboard when you create a factory.  It's already part of our product.

**Comment by TylerJewell** [comment]
Will not support this capability.
