### ISSUE TITLE
Not able to connect with external database on 3306 port

### ISSUE THREAD

**Issue by FenilShah** [codenvy/codenvy#534]
I am using amazon RDS in my application, and want to connect with amazon rds which is running on 3306 port number. It is getting time out.

**Comment by TylerJewell** [comment]
@FenilShah - we do not do anything to block access to external ports from one of our hosted properties like codenvy.com or beta.codenvy.com.  Are you accessing services that perhaps are behind a firewall?  It may be RDS, but there may not be a clean connection from our servers to that endpoint.

**Comment by FenilShah** [comment]
@TylerJewell I am trying to check port status on codenvy. But it is blocking with I don't have permission to access iptables. See the attached screenshot.
![image 6](https://cloud.githubusercontent.com/assets/5196545/17504106/643d605e-5e13-11e6-97ea-d9e21f255545.png)

**Comment by eivantsov** [comment]
@FenilShah there's nothing on beta.codenvy.com that blocks or somehow interferes with outbound connections.

Are you sure your database is set up to accept external connections?

**Comment by FenilShah** [comment]
Yes. I did open it for all IP. I can connect it with my local machine but not able to connect with beta.codenvy.com. It is getting time out.

**Comment by eivantsov** [comment]
@FenilShah I have just tested a simple php script that connects to a remote DB over 3306 port. No issues.

Can you connect to your DB from a local machine?

**Comment by FenilShah** [comment]
Yes, I am able to connect amazon RDS from my local machine, same app is working in my local. Even I also tried to test my app by installing mysql server in codenvy. It works fine but I don't know why it is not able to connect to amazon RDS. Stuck with connectivity.

**Comment by eivantsov** [comment]
Perhaps you have to whitelist beta.codenvy.com IP?

**Comment by FenilShah** [comment]
Let me check. And will get back to you. Thanks.

**Comment by eivantsov** [comment]
@FenilShah let me know if you need IP addresses of beta.codenvy.com machine nodes

**Comment by FenilShah** [comment]
@eivantsov Yes, you were right. It was my RDS blocking this codenvy machine IP.  That's ok, it's my just development database server. So I opened for all IPs, now I am able to connect. Thank you so much for your kind support.
