### ISSUE TITLE
Implement machine's state changes detection for hosted version

### ISSUE THREAD

**Issue by mmorhun** [codenvy/codenvy#539]
In CHE we monitor docker events to find out unexpected stop/kill of containers. It allows us to show user-friendly message in case of OOM and allows to stop API Machine when backend of machine was stopped or became useless.
In hosted version we use swarm, but its support of docker events is incomplete. Because of that, such monitoring is not working. We should find a way how to fix that in hosted.

**Depends on** https://github.com/eclipse/che/issues/1836

**Comment by mmorhun** [comment]
In near future we can use docker swarm mode instead of swarm. It may solve or simplify this problem. In additional, after that, solution with pure swarm will be useless.

**Comment by TylerJewell** [comment]
@vkuznyetsov - can you add some description as to why this improvement will require Docker swarm mode?

**Comment by garagatyi** [comment]
It doesn't. Mykola just suggested to not solve this issue because after moving to swarm mode we will have to rework it. But now this move is delayed, so we should not rely on that.

**Comment by TylerJewell** [comment]
@garagatyi - is this issue still an actual issue?

**Comment by garagatyi** [comment]
Answer requires investigation whether events handling was improved in swarm since we encounter the issue.
