### ISSUE TITLE
Wrong behavior after create pull request on 'Pull request' panel

### ISSUE THREAD

**Issue by AndreyChizhikov** [codenvy/codenvy#546]
Reproduction Steps:
1. Import project from GItHub. It **shouldn't be** in your repo.
2. Click on parent folder for this project
3. Open any file and change it.
4. Open 'Pull Request' panel 
5. Click on 'Create PR' button

Expected behavior:

Fork created  -  **V**
Branch pushed on your fork - **V**
Pull request issued - **V**
Your pull request has been created.

Observed behavior:
Fork created  -  **V**
Branch pushed on your fork - 500 Internal Server Error
![pr-500](https://cloud.githubusercontent.com/assets/8051404/17546473/ed5144aa-5eea-11e6-9b95-6d25d24d7604.png)
![pr-500-headers](https://cloud.githubusercontent.com/assets/8051404/17546478/f3cace1e-5eea-11e6-84c5-7953079b6230.png)

Codenvy version: 4.7.0-SNAPSHOT
OS and version: Ubuntu 14.04 LTS

Additional information:

Problem only started happening recently, didn't happen in an older version of Codenvy:  No
Problem can be reliably reproduced: No - it's random, but this problem occurs frequently.

**Comment by bmicklea** [comment]
@vkuznyetsov can you check if this can be completed for 18-Oct please?

**Comment by bmicklea** [comment]
Is this related to #906

**Comment by vkuznyetsov** [comment]
This issue depends on #906

**Comment by vinokurig** [comment]
Can not reproduce in 5.0 M6
