### ISSUE TITLE
Workspace refusing to start

### ISSUE THREAD

**Issue by alexfeugas** [codenvy/codenvy#557]
Hello,

Sorry to disturb the community with my little issue, but I no longer can start one of my workspaces. 
When I intend to start the workspace, I get a little window prompting "failed".
I know I may not have an answer as it would be difficult to reproduce my issue, but is anyone having the same issue? Any clue of how I could solve it?

Thanks a lot for your help!

Codenvy version: [beta version]
OS and version: [I used the ready-to-go stack for Python]

Additional information:

Problem only started happening recently, didn't happen in an older version of Codenvy: [Yes]
Problem can be reliably reproduced: [ No - it's random]

![image](https://cloud.githubusercontent.com/assets/5181433/17555882/98049944-5f11-11e6-9ebb-d1b339d9eb2a.png)

**Comment by ddementieva** [comment]
@alexfeugas are there any errors in the browser console? Can you send us a screenshot with browser dev console opened?

**Comment by alexfeugas** [comment]
Hi! Thanks for the quick answer. Here it is : 

![image](https://cloud.githubusercontent.com/assets/5181433/17556373/7926380a-5f13-11e6-8429-96cf5d76e8ed.png)

Is it what you were looking for?

**Comment by ddementieva** [comment]
It's known bug: https://github.com/codenvy/codenvy/issues/541. It will be fixed on beta after the beta update.

It happens only with already existing workspaces. Have you tried to create a new one?

**Comment by alexfeugas** [comment]
Yes, it looks like it's working, but I was having source code on this workspace that I don't have saved anywhere else (stupid me :/)
Thanks for the news!!

**Comment by JamesDrummond** [comment]
@alexfeugas Can the issue be closed?

**Comment by alexfeugas** [comment]
Yes, thanks for the help, I can access the workspace again! I'm closing the issue. :)
