### ISSUE TITLE
Container not cleaned up if it failed to start

### ISSUE THREAD

**Issue by eivantsov** [codenvy/codenvy#562]
When a workspace fails to start because of an error in CMD or any other reason, the container isn't cleaned up. As a result, Swarm reserves memory for such a container. 

Reproduction Steps:

1. Start a workspace from a custom recipe with a messed up CMD
2. Workspace fails to start.
3. Run `docker ps -a` to find this container

Expected behavior:

Container should be deleted

Observed behavior:

Container is not deleted

Codenvy version: 4.6.1

**Comment by TylerJewell** [comment]
Can you comment on the severity and relative urgency for a fix?  This seems like an issue that will appear in devops mode but once a system is optimized then this would not be common.

**Comment by eivantsov** [comment]
@TylerJewell right now ALL failed containers are not cleaned and swarm reserves RAM for them.

**Comment by TylerJewell** [comment]
Let's label it a blocker.

**Comment by mmorhun** [comment]
Fixed
