### ISSUE TITLE
Remove outdated factory.policies.match parameter

### ISSUE THREAD

**Issue by mshaposhnik** [codenvy/codenvy#566]
factory.policies.match  was moved to factory.policies.create, but forgotten to remove old one.

Reproduction Steps:
None.

Codenvy version: 4.7.0-SNAPSHOT

Additional information:

None

**Comment by TylerJewell** [comment]
@mshaposhnik - is this still an accurage bug?

**Comment by mshaposhnik** [comment]
Yes
