### ISSUE TITLE
Workspace Connection Error at creation

### ISSUE THREAD

**Issue by anthonyrichir** [codenvy/codenvy#567]
I get a 'Workspace Connection Error' when I tried to create a new Java workspace from any project sample. 

Reproduction Steps:

From dashboard, create a new workspace using the Java stack.
Use 3GB of RAM.
Use one of the template projects.

Expected behavior:

The workspace gets created and opens up.

Observed behavior:

I get a 'Workspace Connection Error'
> It seems that your workspace is running, but we cannot connect your browser to it. This commonly happens when Che was not configured properly. If your browser is connecting to workspaces running remotely, then you must start Che with the --remote:<ip-address> flag where the <ip-address> is the IP address of the node that is running your Docker workspaces.Please restart Che with this flag. You can read about what this flag does and why it is essential at: https://eclipse-che.readme.io/docs/configuration#envrionment-variables

Codenvy version: beta
OS and version: Windows 10

Additional information:

Problem can be reliably reproduced: Yes

Log file:
> [DOCKER] Step 1 : FROM codenvy/ubuntu_jdk8
[DOCKER] latest: Pulling from codenvy/ubuntu_jdk8 
[DOCKER] Digest: sha256:83a1cfefdf56dc8194055b6c2e97ec2ce1c7819f4102420a83e6e5f35e0f3138 
[DOCKER] Status: Image is up to date for codenvy/ubuntu_jdk8:latest 
[DOCKER] ---> 5fca53411e54
[STDOUT] 2016-08-12 08:50:57,890[main]             [INFO ] [o.a.c.s.VersionLoggerListener 89]    - Server version:        Apache Tomcat/8.0.32
[STDOUT] 2016-08-12 08:50:57,893[main]             [INFO ] [o.a.c.s.VersionLoggerListener 91]    - Server built:          Feb 2 2016 19:34:53 UTC
[STDOUT] 2016-08-12 08:50:57,893[main]             [INFO ] [o.a.c.s.VersionLoggerListener 93]    - Server number:         8.0.32.0
[STDOUT] 2016-08-12 08:50:57,893[main]             [INFO ] [o.a.c.s.VersionLoggerListener 95]    - OS Name:               Linux
[STDOUT] 2016-08-12 08:50:57,894[main]             [INFO ] [o.a.c.s.VersionLoggerListener 97]    - OS Version:            3.10.0-327.4.5.el7.x86_64
[STDOUT] 2016-08-12 08:50:57,894[main]             [INFO ] [o.a.c.s.VersionLoggerListener 99]    - Architecture:          amd64
[STDOUT] 2016-08-12 08:50:57,898[main]             [INFO ] [o.a.c.s.VersionLoggerListener 101]   - Java Home:             /opt/jdk1.8.0_45/jre
[STDOUT] 2016-08-12 08:50:57,898[main]             [INFO ] [o.a.c.s.VersionLoggerListener 103]   - JVM Version:           1.8.0_45-b14
[STDOUT] 2016-08-12 08:50:57,898[main]             [INFO ] [o.a.c.s.VersionLoggerListener 105]   - JVM Vendor:            Oracle Corporation
[STDOUT] 2016-08-12 08:50:57,899[main]             [INFO ] [o.a.c.s.VersionLoggerListener 107]   - CATALINA_BASE:         /home/user/che/ws-agent
[STDOUT] 2016-08-12 08:50:57,899[main]             [INFO ] [o.a.c.s.VersionLoggerListener 109]   - CATALINA_HOME:         /home/user/che/ws-agent
[STDOUT] 2016-08-12 08:50:57,900[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.config.file=/home/user/che/ws-agent/conf/logging.properties
[STDOUT] 2016-08-12 08:50:57,900[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
[STDOUT] 2016-08-12 08:50:57,900[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xms256m
[STDOUT] 2016-08-12 08:50:57,901[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xmx2048m
[STDOUT] 2016-08-12 08:50:57,901[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.security.egd=file:/dev/./urandom
[STDOUT] 2016-08-12 08:50:57,901[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.dir=/home/user/che/ws-agent/logs
[STDOUT] 2016-08-12 08:50:57,902[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.level=INFO
[STDOUT] 2016-08-12 08:50:57,902[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote
[STDOUT] 2016-08-12 08:50:57,902[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.ssl=false
[STDOUT] 2016-08-12 08:50:57,903[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
[STDOUT] 2016-08-12 08:50:57,903[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.local.conf.dir=/mnt/che/conf
[STDOUT] 2016-08-12 08:50:57,903[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.endorsed.dirs=/home/user/che/ws-agent/endorsed
[STDOUT] 2016-08-12 08:50:57,903[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.base=/home/user/che/ws-agent
[STDOUT] 2016-08-12 08:50:57,904[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.home=/home/user/che/ws-agent
[STDOUT] 2016-08-12 08:50:57,904[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.io.tmpdir=/home/user/che/ws-agent/temp
[STDOUT] 2016-08-12 08:50:58,140[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 425]  - Initializing ProtocolHandler ["http-nio-4401"]
[STDOUT] 2016-08-12 08:50:58,163[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 72]   - Using a shared selector for servlet write/read
[STDOUT] 2016-08-12 08:50:58,167[main]             [INFO ] [o.a.catalina.startup.Catalina 591]   - Initialization processed in 649 ms
[STDOUT] 2016-08-12 08:50:58,227[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 332]  - The JMX Remote Listener has configured the registry on port 32002 and the server on port 32102 for the Platform server
[STDOUT] 2016-08-12 08:50:58,228[main]             [INFO ] [o.a.c.core.StandardService 435]      - Starting service Catalina
[STDOUT] 2016-08-12 08:50:58,228[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.0.32
[STDOUT] 2016-08-12 08:50:58,305[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 910]        - Deploying web application archive /home/user/che/ws-agent/webapps/wsagent.war
[STDOUT] 2016-08-12 08:51:05,978[ost-startStop-1]  [INFO ] [.e.c.a.v.i.f.e.LoEventListener 48]   - Subscribing to event service: class org.eclipse.che.api.vfs.impl.file.event.LoEventListener
[STDOUT] 2016-08-12 08:51:05,982[ost-startStop-1]  [INFO ] [.e.c.a.v.i.f.e.VfsEventService 55]   - Starting virtual file system event service: LoEventService
[STDOUT] 2016-08-12 08:51:05,985[ost-startStop-1]  [INFO ] [.e.c.a.v.i.f.e.VfsEventService 55]   - Starting virtual file system event service: HiEventService
[STDOUT] 2016-08-12 08:51:06,378[s polled Thread]  [INFO ] [o.e.c.p.m.server.rmi.RmiClient 130]  - Port/Name:9991/MavenRemoteServerImpl9b79cb6e
[STDOUT] 
[STDOUT] Fri Aug 12 08:51:08 UTC 2016 - [localhost-startStop-1] Product-specified preferences called before plugin is started
[STDOUT] 2016-08-12 08:51:08,604[rest.WSClient-0]  [INFO ] [.c.a.c.n.WSocketEventBusClient 223]  - Open connection to wss://beta.codenvy.com/api/eventbus/?token=machinedpy7t0yx0fib77t1nyybe1ulp89qrk6f8bh4ip9c9rz5q053h244yujhotofzo4gy2uen02j1pfkucvc5bm78uoo6isvjf1pyadkvkltp9mszqmwtn9xsw2bet8f40g6. 
[STDOUT] 2016-08-12 08:51:08,893[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 974]        - Deployment of web application archive /home/user/che/ws-agent/webapps/wsagent.war has finished in 10,587 ms
[STDOUT] 2016-08-12 08:51:08,895[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1030]       - Deploying web application directory /home/user/che/ws-agent/webapps/ROOT
[STDOUT] 2016-08-12 08:51:08,967[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1142]       - Deployment of web application directory /home/user/che/ws-agent/webapps/ROOT has finished in 72 ms
[STDOUT] 2016-08-12 08:51:08,976[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 470]  - Starting ProtocolHandler ["http-nio-4401"]
[STDOUT] 2016-08-12 08:51:08,983[main]             [INFO ] [o.a.catalina.startup.Catalina 642]   - Server startup in 10815 ms

**Comment by nikodll** [comment]
The same happens for me. What is also remarkable is when I switch to the deploying workspace it shows message  "Getting info about registered project types..." and hangs

**Comment by ddementieva** [comment]
@anthonyrichir Are there any errors in the browser dev console? You may need to unblock 444 port to make it work.

You can also check if websockets are not blocked in your network, e.g. at https://websocketstest.com/

**Comment by anthonyrichir** [comment]
https://websocketstest.com/ says is seem to work for me.

But during the creation of a workspace, I see this error in the browser (Chrome) console:
> WebSocket connection to 'wss://beta.codenvy.com:444/34455_node1.beta.codenvy.com/wsagent/ext/ws?toke…8kjw8bkz58hp9e6bc5emz5ktqhqzkvivqa2dtwjsrhb8t0vj6n6o6xxjf7s52lb1r26dv8gyvd' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT
error when starting remote extension Event {isTrusted: true, type: "error", target: WebSocket, currentTarget: WebSocket, eventPhase: 2…}

And if I try to open the workspace afterwards, I also get the same problem as @nikodll .

I'll try to unblock port 444.

**Comment by ddementieva** [comment]
@anthonyrichir Looking at your network settings is a good idea.

**Comment by nikodll** [comment]
It has also revealed the 444 port problem for me, which is indeed blocked on our network. The workaround turned out to be: 1) Download [Opera beta](http://www.opera.com/computer/beta) 2) Enable VPN: Settings->Privacy & Security -> Enable VPN 3) Redeploy your workspace.
Thank you, Daria for your hint about 444 port connection.

**Comment by anthonyrichir** [comment]
Thanks @nikodll for the tip, it's indeed working with a VPN, the port is not blocked on my machine but probably somewhere on my network.
