### ISSUE TITLE
codenvy push to openshift through ssh

### ISSUE THREAD

**Issue by sealmu** [codenvy/codenvy#573]
can't initialize "git clone" to openshift in any way I've tried. only to GitHub it was successfully.

**Comment by TylerJewell** [comment]
Sorry - this is not a helpful issue.  Please provide a complete report according to our best practices and then perhaps an engineer can take a look.

https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#writing-good-bug-reports-and-feature-requests

**Comment by eivantsov** [comment]
@sealmu  you may want to take a look at this issue - https://github.com/codenvy/codenvy/issues/491

**Comment by eivantsov** [comment]
@sealmu any update on this one please?

**Comment by TylerJewell** [comment]
Closing - no response.
