### ISSUE TITLE
Puppet doesn't change /etc/hosts

### ISSUE THREAD

**Issue by soanni** [codenvy/codenvy#574]
Hello, Codenvy Team.
It seems that puppet doesn't change record in /etc/hosts when you manually change $host_url in 
/etc/puppet/manifests/nodes/codenvy/codenvy.pp

I noticed that when i installed Codenvy v4.6.2 with option --hostname=codenvy.aurea.org.
Then i dediced to manually change $host_url to codenvy.aurea.com.
I ran puppet agent -t
But after that the line 127.0.0.1 codenvy.aurea.org was still presented in /etc/hosts

**Comment by TylerJewell** [comment]
@dmytro-ndp @riuvshin @tolusha @eivantsov

**Comment by soanni** [comment]
the bad thing that puppet now doen't reconfigure the system. after running it in debug mode 
sudo puppet agent -t --debug i can see
----------------------
Debug: Creating new connection for https://codenvy.aurea.org:8140
Debug: Using cached certificate_revocation_list for ca
Debug: Starting connection for https://codenvy.aurea.org:8140
-------------
so it still uses codenvy.aurea.org hostname and https protocol
And it's hanging after this line

**Comment by tolusha** [comment]
@soanni 
To change hostname use `im` command:
`codenvy config --hostname <new_host_name>`

**Comment by eivantsov** [comment]
@soanni I think you have resolved the issue with changing the hostname, correct? I will close the issue - feel free to reopen or contact us through Zendesk ticket system.
