### ISSUE TITLE
Notify user of old workspaces

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#580]
Problem:
Users can create a large number of workspaces over time and if snapshotting is turned on each workspace will have a snapshot leading to large per-user storage requirements.  This is avoidable because in most cases the number of workspaces the user is actively working on is small.

Possible solution:
1a. Allow the admin to set a configuration parameter to define the maximum age (in days) of an unused workspace (Tn) before users will be notified.
1b. Allow admin to disable workspace age notification check.
2. System does a daily search for workspaces that are older than Tn.
3a. Provide a popup in the dashboard for the user who owns the workspace: "The following workspaces haven't been used in Tn days." : https://github.com/codenvy/codenvy/issues/942
3b. Send an email to the user and admin:
- Subject: "Codenvy: inactive workspaces"
- Body: "The following workspaces haven't been used in Tn days:"
- List for each workspace: workspace name; username who owns the workspace; date of last access

**Comment by TylerJewell** [comment]
@bmicklea - you defined this as a "snapshot".  But I think - for simplicity - we should do this for workspaces instead.  I think that the user will just lose the entire workspace and have it deleted - not just the snapshot.  This will be a more efficient cleanup of the system overall.  And if in the future admins just want to remove snaps - we can add that as an option.

**Comment by mmorhun** [comment]
@bmicklea unused workspace is a workspace which wasn't run T days. Right?

**Comment by bmicklea** [comment]
@mmorhun I've updated the issue to use "inactive" language - that is a workspace that hasn't been run in T days.

**Comment by vkuznyetsov** [comment]
@bmicklea After we implement a limitation for storage per user then this issue might be not actual at all.
