### ISSUE TITLE
Allow per user overrides for all resource limit configs

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#582]
Most enterprises set the workspace and RAM limitations for their organization. However, in all enterprises there are certain developers who need exceptional resources for their work. Codenvy should allow the admin to override the limit settings on a per-user basis.

Ultimately this should be done through the UI, but in the meantime allowing this to be executed through an enhancement to the Permissions API will allow enterprises to use the feature sooner. The API would have to support:
- Adding overrides to a user
- Listing overrides per install (list of all users with overrides and what those overrides are) - no input parameter needed
- Listing overrides per user (list of the overrides for a particular user) - would require the input of the user's email

This may be part of the "organization" work that is going on. Ideally the system would let you identify a user in the database and provide them with overrides of one or more workspace and RAM limitations.

**Comment by gazarenkov** [comment]
Well, by our model:
- Organizations have hierarchy
- User which is a member of top Organization MAY have permission to create sub-organization and to set resource limits (assign licence)  - that's what may be called Admin permissions in this sense

So conceptually "Admin" may create sub-organization of one user and assign dedicated licence (resources) to it (actually to this user)

**Comment by bmicklea** [comment]
That's fine - for usability we may implement an in-client default that grants admin privileges for a sub-organization to everyone who has admin privileges to the parent organization.

**Comment by TylerJewell** [comment]
It is a clever way to handle it.  The next step is for sergey to propose a CLI syntax.  Let's look and agree on it.

**Comment by tolusha** [comment]
@TylerJewell We don't need @sleshchenko to design CLI syntax. We just need a real user cases.

**Comment by dmytro-ndp** [comment]
It seems we need have this issue be done before https://github.com/codenvy/codenvy/issues/409

**Comment by tolusha** [comment]
It is not actual anymore concerning CLI part.

**Comment by bmicklea** [comment]
Correct - but can we see an outline of the planned API methods to handle this?
