### ISSUE TITLE
"dot" files not visible in project explorer tree

### ISSUE THREAD

**Issue by jlindenger** [codenvy/codenvy#583]
Codenvy-beta workspace project explorer does not show hidden (e.g. "dot") files. 

Reproduction Steps:

1. In project explorer... right-click on project -> new -> file
2. Add a file with a filename like ".somerc" and type some stuff so it saves.
3. Close the file in the editor.
4. Refresh the project explorer

Expected behavior:

1. Should add the named "dot" file to the filesystem.
2. Should show file in the project explorer filesystem tree.

Observed behavior:

1. File is successfully added to the filesystem. In console, you can "ls" to find it.
2. File is not visible in the project explorer. It appears to be generating the tree with a "ls" style listing rather than an "ls -a" style listing.

Codenvy version: 4.6.2 (Current at beta.codenvy.com)

**Comment by TylerJewell** [comment]
Did you activate hidden files?  It's a menu option - this may need to be turned on.

**Comment by eivantsov** [comment]
@jlindenger @TylerJewell Show/Hide hidden files does not work for me on beta.codenvy.com. I will check how it goes with a current master and if I can reproduce it, then label it as a bug.

@jlindenger thanks for letting us know.

**Comment by ddementieva** [comment]
@jlindenger Bug confirmed.

**Comment by jlindenger** [comment]
@ddementieva's suggestion about refreshing the page seems to work. I think this implies that right click - "refresh..." in the "Project Explorer" pane may be the actual issue.

**Comment by TylerJewell** [comment]
We've implemented improvements into che that has made this go away - should be ok now.
