### ISSUE TITLE
Cannot ping api.nasa.gov at beta.codenvy.com

### ISSUE THREAD

**Issue by kaloyan-raev** [codenvy/codenvy#588]
I am exploring the Factories capabilities at beta.condenvy.com. My project makes requests to api.nasa.gov, but this host name is not resolved in the Codenvy workspace. Other host names like google.com and yahoo.com are resolved correctly. So it looks like it's a matter of a DNS setup. Please, add api.nasa.gov to the list of the allowed hosts.

Reproduction Steps:

1. Create a PHP workspace.
1. Open a Terminal.
1. Execute ```ping api.nasa.gov```

Expected behavior:

The ```api.nasa.gov``` host name is resolved successfully.

Observed behavior:

Error printed: ```ping: unknown host```

Codenvy version: beta.codenvy.com
OS and version: beta.codenvy.com

Additional information:

Problem only started happening recently, didn't happen in an older version of Codenvy: Don't know
Problem can be reliably reproduced: Yes

**Comment by TylerJewell** [comment]
@riuvshin @skryzhny - guys FYI.  This looks like another issue that came in at the same time where a user on the beta.* domain was unable to ping out of the workspace.

**Comment by eivantsov** [comment]
@kaloyan-raev we did have issues with DNS. It should be OK now.

**Comment by kaloyan-raev** [comment]
@eivantsov Yes. I can access api.nasa.gov now. Thank you for the quick resolution!
