### ISSUE TITLE
Empty logs and no error message while it is impossible to start from a factory

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#590]
On beta.codenvy.com, the factory is failing to load properly the workspace. The machine is not starting and there is no error message and the logs are empty.

Reproduction Steps:

1. Click on a factory
2. The factory loading screen is displayed but nothing happen

Expected behavior:
After a certain period of time, the product is displaying an error message to the user. Moreover, if there is a problem it should be possible to analyze it from the logs.

Observed behavior:
The loading screen is hanging forever. No error message is displayed
The logs are completely empty.

![screen shot 2016-08-17 at 10 16 08](https://cloud.githubusercontent.com/assets/1636769/17729491/c3b0333e-6464-11e6-849f-2b8b37acbc1d.png)

Codenvy version: 4.6.2

Additional information:
After initial analyze, it seems the problem is due to a connectivity trouble with DockerHub. 

Problem only started happening recently, didn't happen in an older version of Codenvy: Yes
Problem can be reliably reproduced: Yes at this moment

**Comment by JamesDrummond** [comment]
@slemeur Is this still a bug?

**Comment by slemeur** [comment]
It is still happening from time to time.

Just reproduced with 5.0.0-M4

There is not output for "Workspace initializing...". And the outputs for "Start workspace runtime" didn't show up before a long time (and sometime does not display at all).  

![loading-no-outputs](https://cloud.githubusercontent.com/assets/1636769/19044663/8f4bed58-8995-11e6-8e31-2675037d1053.gif)

**Comment by TylerJewell** [comment]
I have never been able to see it.  We cannot leave this issue open unless we have stack trace or dev console, or a way to reproduce it within QA.
