### ISSUE TITLE
Missing project types in Project Configuration wizard

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#591]
The Project Configuration wizard is missing few project types. 

Reproduction Steps:

The problem is actually random and not reproductible 100%. Sometime the Project Configuration wizard is displaying all the project types properly, and sometime it is not. 

1. Create a new workspace
2. Import a project from a github repository
3. Open the Project Configuration wizard

Expected behavior:

The Project Configuration wizard is displaying the complete list of project types.

Observed behavior:

The Project Configuration wizard is missing Maven. 

Codenvy version: 4.6.2 - beta.codenvy.com

Additional information:

Problem only started happening recently, didn't happen in an older version of Codenvy: Yes
Problem can be reliably reproduced: No - it's random

**Comment by eivantsov** [comment]
@slemeur it is expected behavior. If there's no Maven (M2_HOME env) in a workspace, we do not start Maven plugin and disable creation of Maven and Java projects since it does not make any sense.

**Comment by TylerJewell** [comment]
Let's discuss this.  It was not expected from a user point of view.  I think we made the system too smart.  As a user I want all pt always visible as I may choose to install maven later and configure my own maven home.

**Comment by gazarenkov** [comment]
"to install maven later and configure my own maven home." - yes, that's what desktop env (IDE) user would expect. As a Codenvy user I would expect to choose right workspace template (factory, stack, whatever) and use it or make it myself once and forget, reproducing my workspace over and over again.

**Comment by TylerJewell** [comment]
No - that is not true.

This is a viable scenario:
1. Blank workspace.
2. Blank pt.
3. Install some additional maven software.
4. Add maven PT.

We need to support this use case, otherwise, the product is confusing.

**Comment by gazarenkov** [comment]
Is not it possible if you restart workspace after step 3?

But it is not obvious to me why I would choose Codenvy over desktop to implement this scenario.

**Comment by TylerJewell** [comment]
It is expected that if user chooses blank PT and blank project, then they expect our WS to behave just like desktop scenario.  If user chooses a different kind of ws / stack / template, then maybe we can do special behaviors.  But we have a few scenarios where we do things differently and the end user is not aware of it - cannot be notified, and so it comes across as bug.  So best to make blank ws truly blank and turn off any special handling.
