### ISSUE TITLE
Workspace is not deleted after finishing selenium test

### ISSUE THREAD

**Issue by artaleks9** [codenvy/codenvy#593]
We need to delete workspaces after finishing the selenium tests by API methods.

**Reproduction Steps:**
Run a selenium test in the 'qa' project (e.g. 'DialogAboutTest')

**Expected behavior:**
the workspace should be deleted after finishing test.

**Observed behavior:**
the workspace is not deleted.

**_Codenvy version:**_\* 4.7.0
**OS and version:** Ubuntu 14.04 

**Additional information:**
See the attachment:
![log_error](https://cloud.githubusercontent.com/assets/5408906/17730867/6db1f01c-6473-11e6-9ac7-c021dd8703b6.png)

**Comment by JamesDrummond** [comment]
@musienko-maxim What's the status on this?

**Comment by TylerJewell** [comment]
@artaleks9 @vkuznyetsov - is this a product issue, or is this a QA issue?  Is it still actual?

**Comment by artaleks9** [comment]
It is bug to API method, when we delete a workspace in the selenium tests by API.
Still actual.

**Comment by garagatyi** [comment]
Fixed by eclipse/che#3133
