### ISSUE TITLE
 Test on a backup of the workspace falls

### ISSUE THREAD

**Issue by akorneta** [codenvy/codenvy#601]
`WorkspaceFsBackupSchedulerTest#shouldBackupOtherWorkspacesIfBackupOfPreviousFails`   periodically falls when launching all tests in a class with  [trace] (https://gist.githubusercontent.com/akorneta/44730398e725ecf65194aee19969146a/raw/c362dd94f1f85ded6fa41853068b214acf6a6cd1/general%2520scope).
In single scope this test periodically path with [trace] (https://gist.githubusercontent.com/akorneta/b9e68ff2a3408cf0b15362f297d21f0b/raw/2cfcd384ed1b7a5d8f5236c2dad3de3daca51b2d/single%2520scope).
OS: openSUSE 13.2 (x86_64)
 Maven Version: 3.3.9

**Comment by mmorhun** [comment]
Fixed
