### ISSUE TITLE
Add needed infrastructure to use overlay network with Docker Swarm

### ISSUE THREAD

**Issue by garagatyi** [codenvy/codenvy#606]
To use multihost networking we need to use overlay network with Swarm. It requires key-value storage.

**Comment by gazarenkov** [comment]
@garagatyi could you please elaborate to have an idea of what it means in terms of additional effort

**Comment by riuvshin** [comment]
here is a good example of using it https://gist.github.com/tombee/7adb7072c7fcdb9e6931

**Comment by garagatyi** [comment]
Overlay network allows communication between containers deployed on different nodes of docker cluster. Without that feature containers will not be eble to communicate with each other by internal ports. Instead of that they will have to use randomly assigned external ports that makes usage of a set of containers much harder.

**Comment by riuvshin** [comment]
@garagatyi  I've added etcd puppet module and configure docker to be able to work with overlay networking, currently it works only in AIO mode but this should be enough to continue your work. You can use my branch https://github.com/codenvy/deployment/tree/codenvy-606

**Comment by garagatyi** [comment]
Thanks!

**Comment by riuvshin** [comment]
Done.
