### ISSUE TITLE
Unexpected disappearance of java file from project explorer after create package

### ISSUE THREAD

**Issue by artaleks9** [codenvy/codenvy#607]
Sometimes we have an unexpected disappearance of java file from project explorer after creating new package into plain java project.

**Reproduction Steps:**
- Create or import plain java project (e.g. https://github.com/idexmai1/plainJavaProject.git).
- Expand the project and open a java file.
- Create new package.

**Expected behavior:**
the java file does not disappear from the project explorer

**Observed behavior:**
the java file disappears from the project explorer

**Codenvy version:** 4.7.0
**OS and version:** Ubuntu 14.04

**Additional information:**
The related selenium test: 'RunPlainJavaProjectTest'.
See the attachment:
![javafile_after_create_package](https://cloud.githubusercontent.com/assets/5408906/17809333/903b9df2-661e-11e6-96e5-d66fe8f1d83c.gif)

**Comment by bmicklea** [comment]
@artaleks9 if the project explorer is refreshed does the file re-appear?

**Comment by artaleks9** [comment]
Yes, the file appears after refresh.

**Comment by artaleks9** [comment]
The bug is not reproduced.
