### ISSUE TITLE
Code intelligence and auto complete not working

### ISSUE THREAD

**Issue by nmvega** [codenvy/codenvy#611]
Hello friends...

While accessing the IDE editor through Chrome or Firefox, code completion and pop-up intelligence don't appear to work. I tried **<ctrl-space>** (which I read somewhere is the keystroke to use), **Tab,** etc., but they don't work. Btw, I set the keybindings to VI. Perhaps I'm doing something wrong. =:) Here is some additional information. Thank you.

Codenvy version: [4.6.2]
OS and version:                                                    
   NAME="Ubuntu"                                                                               
  VERSION="14.04.5 LTS, Trusty Tahr"                                                          
   ID=ubuntu                                                                                   
   ID_LIKE=debian                                                                              
   PRETTY_NAME="Ubuntu 14.04.5 LTS"                                                            
   VERSION_ID="14.04"

**Comment by JamesDrummond** [comment]
@nmvega I had the issue when I first starting use codenvy. It should be "Ctrl+space".

**Comment by nmvega** [comment]
Thanks you James. Somehow my message above got botched. The above actually had read  **I tried <ctrl+space> (which I read somewhere is the keystroke to use), Tab, etc.,**  but somehow the sentence got munged. So indeed, I tried that first. Sadly it does not work.Thanks for your reply, btw! :)

**Comment by JamesDrummond** [comment]
What programming language and file are you trying this on? Try creating a new project `console-java-simple` with the standard java workspace stack. Then try `ctrl+space` in file `HelloWorld.java`.

**Comment by nmvega** [comment]
I'm trying it on Python3. Okay, will try it (Java) tomorrow and report 
back. Thank you.

**Comment by JamesDrummond** [comment]
I think only java has a plugin that provides intellisense features. However, there is an upcoming enhancement to provide support for many more languages using a language server [https://github.com/eclipse/che/issues/1287](https://github.com/eclipse/che/issues/1287) .

@eivantsov Do you know what programming languages currently have intellisense?

**Comment by eivantsov** [comment]
It's Java and JavaScript only.
