### ISSUE TITLE
No logs displayed when starting a workspace from a factory

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#612]
![screen shot 2016-08-22 at 10 16 06](https://cloud.githubusercontent.com/assets/1636769/17848049/b711aba8-6851-11e6-977c-5f38f247c73b.png)

There are no logs displayed in the factory loading screen, for the step "starting workspace runtime"

Reproduction Steps:
Try the following factory: http://beta.codenvy.com/f?id=g873lob5z6k703vn

Expected behavior:
The workspace's runtime outputs are streamed and displayed on the screen.

Observed behavior:
No outputs displayed. While if you started the workspace from the IDE the outputs are there.

Codenvy version: 4.6.2

**Comment by eivantsov** [comment]
@slemeur I was unable to reproduce this one. Can you repeatedly reproduce it?
![factory](https://cloud.githubusercontent.com/assets/5337267/17958543/54c07bec-6aa3-11e6-82d2-8a51cfbb4a63.png)
