### ISSUE TITLE
Revamp list's header

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#613]
Along with the work done on https://github.com/eclipse/che/issues/2179

As part of the work done to simplify the list and grips in UD.
We needt improve the way we are displaying description of UD's sections.

Here is the design:
![2 - workspace list header](https://cloud.githubusercontent.com/assets/1636769/17850700/c61c5334-685e-11e6-8b43-f5a053af2a48.png)

Labels of each pages:
*Dashboard:*
Access your recently used workspaces and Factories, or create a new workspace. Clicking on your user name at the bottom will open up account and (with sufficient permissions) administration settings.

*Workspaces:*
A workspace is composed of projects, environments and commands. Create a new workspace or manage an existing workspace (start, stop, reconfigure or delete).  Learn more.

Learn more will redirect to: 
http://codenvy.readme.io/docs/environments

*Factories:*
Factories enable workspace automation and are packaged as a consumer-friendly URL. Create new Factories to onboard your team, or integrate with your toolchain.  Learn more.

Learn more will redirect to:
http://codenvy.readme.io/docs/factories

*Administration:*
Control the configuration and policies for your installation.

**Comment by ashumilova** [comment]
Resolved
