### ISSUE TITLE
Describe configuration changes related to "Consolidated database"

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#616]
Since I don't know for which version it will be. I've created dedicated to "Consolidated database" issue
All changes and necessary commands will be described in comments to this issue

**Comment by evoevodin** [comment]
For migration:
- build [jpa-migration-tool](https://github.com/codenvy/deployment/tree/jpa-integration/automation/jpa-migration-tool) 

```
mvn clean compile assembly:single
```
- check default configuration properties
 
```
java -jar jpa-migration-tool-${project.version}-jar-with-dependencies.jar show-config
``` 

_`${project.version}`_  - the version of the project in _jpa-integration_ branch(should be current one)

- perform migration 
```
java -jar jpa-migration-tool-${project.version}-jar-with-dependencies.jar migrate
```
if default configuration properties are not okay, you can override them by specifying an absolute path to the custom configuration properties with a flag `-config-file`,  also you can change default properties by editing _configuration.properties_ in jar file, please note that custom properties will override default properties with the same keys.

**Comment by JamesDrummond** [comment]
@skabashnyuk Can you place a `kind` label on this?
