### ISSUE TITLE
Dashboard doesn't check if usage of Codenvy on-prem is legal according to license terms

### ISSUE THREAD

**Issue by dmytro-ndp** [codenvy/codenvy#621]
Codenvy on-prem version 4.6.2 and later.

Dashboard doesn't check legality of Codenvy on-prem in case of there is regular user logged in.
https://beta.codenvy.com/api/permissions/system service returns 404 NOT FOUND in this case, but https://beta.codenvy.com/im/license/legality method is still accessible for regular user.

**Comment by olexii4** [comment]
https://github.com/codenvy/codenvy/pull/679/commits/20e5b0a2972c25a496ebce94d6eec733f1a51bff
