### ISSUE TITLE
Gitlab integration

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#628]
We need to find out the best way how we can clone and push for private Gitlab repositories.
Also we should consider that customers can have a personal installations of Gitlab server

Possible scenarios
- We can use login password authentication.
- We  can configure Gitlab as OAuth2 provider, implement Authenticator. Use OAuth2 token to clone and push, or upload ssh key.

**Comment by TylerJewell** [comment]
@JamesDrummond - we will need really superb docs in docs.codenvy.com about gitlab integration.  Due by sept. 15th - we have multiple customer installations for this.

**Comment by bmicklea** [comment]
Just a point of clarification - this is currently in the codenvy repo but is this being added to Che?

**Comment by JamesDrummond** [comment]
@bmicklea This is in regards to factories that have private gitlab projects. I think for the che git docs though I should add how to import private repos which requires setting up the ssh keys as shown above before you import the project.

**Comment by mkuznyetsov** [comment]
SSH key usecase above is currently working on beta.codenvy.com

**Comment by bmicklea** [comment]
@JamesDrummond yes, part of this is Codenvy docs (factories) and the other is private repos with GL in Che docs.
