### ISSUE TITLE
New UX mecanism for system notifications

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#631]
In order to display proper system notification we'll add a new UX mecanism to handle those in UD.
This issue will impact #408 #406 

The ability to close the warning message, is a good idea because it lets the user being able to continue using the product normally - the notification reported might not affect him directly and could be ignored in certain cases - so it would not necessarily need to be displayed all the time.

We'd need a notification handling mechanism. We already have in place the notifications that are raised when the user is performing certain actions - or when the system is running into a certain state. 
Taking the "Low RAM" notification:

When the state of system is getting low on RAM resources, we'd display the notification to the user.
The notification would still be accessible from a notification menu
When the user try to start a new workspace/machine, we'd raise again the notification (in the context)
We’d just need a way to display all the current (and still accurate) notifications.

![da5457e8-5fe4-11e6-9fe1-d0f9dd6f082e-1](https://cloud.githubusercontent.com/assets/1636769/17984914/ac25397a-6b13-11e6-9490-c0191b6ac2c7.png)

I still want to display those notifications from the left navigation menu - as it is available from UD and IDE with a consistent way.

**Comment by TylerJewell** [comment]
@slemeur - should this issue be moved to Eclipse Che as it's a functional UX issue?

**Comment by slemeur** [comment]
Closing, as it has been handled in codenvy.
