### ISSUE TITLE
Github push error

### ISSUE THREAD

**Issue by MoonBrew** [codenvy/codenvy#640]
Unable to push local commits to github.

Reproduction Steps:

1.    Go to https://www.eclipse.org/che/getting-started/cloud/ and create a workspace using existing github repo url and wizard.
2.    Add a new file to your project and commit.
3.    Select git -> remote -> push.

Expected behavior:

Local git repo changes gets pushed to github repo

Observed behavior:

You get index-pack abnormal exit error

Codenvy version: Next generation
OS and version: Android 4.4.4

Additional information:

Am I new to github and linux: Yes
Problem can be reliably reproduced: Yes

**Comment by MoonBrew** [comment]
Closed this because I think this pertains to my lack of knowledge on git

**Comment by ddementieva** [comment]
@MoonBrew Have you tried to generate SSH key for the GitHub at Profile > Preferences > SSH > VCS with `Generate key and upload it to Github` button?
