### ISSUE TITLE
help on ip address

### ISSUE THREAD

**Issue by danielhoset27** [codenvy/codenvy#641]
how do i find my workspace ip address

**Comment by TylerJewell** [comment]
If you are inside of Che / Codenvy, you can open the terminal and then type `ifconfig`.  If you are outside of the product, you can run `docker ps` to identify the ID of the container powering the workspace.  You can then do `docker exec <ws-id> ifconfig`.

What are you researching?

**Comment by danielhoset27** [comment]
thats the internal ip i need external ip

**Comment by ddementieva** [comment]
@danielhoset27 Do you mean you need to get something like preview URL?

You can check it at the Operations Perspective > Servers tab. Server Address consists of your workspace hostname and port randomly chosen from the ephemeral port range.

**Comment by eivantsov** [comment]
@danielhoset27 can you please elaborate?

**Comment by shunyozo** [comment]
cant find the operations perspective, pls show a screenshot if possible, thanks
