### ISSUE TITLE
Add form for adding AWS user credentials for ECR in the Codenvy dashboard

### ISSUE THREAD

**Issue by mmorhun** [codenvy/codenvy#642]
A user should be able to add multiple AWS user credentials for ECR.
Each record has following format:
```
{
    id: <aws-account-id(digits only)>,
    region: <aws-region>,
    access-key-id: <key id>,
    secret-access-key: <key value>
}
```
All records should be saved in the user preferences in a list (like docker registry credentials).
User should be able to add/remove and edit them.

**Comment by bmicklea** [comment]
We will address this through configuration files instead of UD.
