### ISSUE TITLE
Any way to debug a plain java code in codenvy?

### ISSUE THREAD

**Issue by plinyar** [codenvy/codenvy#643]
Cannot debug simple java project

**Reproduction Steps:**

I started "Java + Gradle" workspace in codenvy, set breakpoint to a line in main(), and tried to configure Debug Configurations.

**Expected behavior:**
Entering step-by-step execution of my java code

**Observed behavior:**
Unfortunately, changing any option is this dialog results in error "Can not connect to: ..." (localhost or whatever).

May be a problem in that I don't know the url of the server where the java code runs. I tried "ws-machine", or result of "hostname" bash command in console - no luck.

Do somebody know, is that functionality available in Codenvy?

Codenvy version: Running on https://codenvy.com/ on 2016-08-29
OS and version: Chrome browser 52 on Windows 7

**Comment by ddementieva** [comment]
@plinyar Have you tried to use beta.codenvy.com to debug your Gradle app? 

Follow the instructions in the Tutorial https://eclipse-che.readme.io/docs/che-and-gradle to create and run Gradle application at beta.codenvy.com. 

Find more info on how to debug you Gradle application in beta.codenvy.com at https://eclipse-che.readme.io/docs/debug

**Comment by plinyar** [comment]
Thanks, the last link made this work!
