### ISSUE TITLE
Can't create target on beta.codenvy.com

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#646]
When selecting "Edit Targets" from the Run menu on beta.codenvy.com the resulting panel does not include a "+" button or any way to create the target.

Reproduction Steps:
- Open a workspace at beta.codenvy.com
- Select Run > Edit Targets

Expected behavior:
There should be some way (like a "+" sign) to create a target.

Observed behavior:
No way to create a target.

Codenvy version: 4.6.2
OS and version: n/a

Additional Info:
If this feature is meant to be disabled in beta.codenvy.com then the Edit Targets... option in the Run menu should be grayed out or removed.

Problem only started happening recently, didn't happen in an older version of Codenvy: Not sure...
Problem can be reliably reproduced: Yes

**Comment by JamesDrummond** [comment]
@vparfonov In 5.0.0-M4 I can add ssh targets. Is this issue now resolved?
