### ISSUE TITLE
After consuming a factory a maven project becomes invalid (regression)

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#650]
**CHE-1818**
**Reproduction Steps:**
Precondition: create 
1. Create project in a worksapce and consume factory from this one (we can use dasboard or IDE)
2. Consume the factory
**Expected behavior:** The new workspace should be created without errors. The project should be cloned without errors. Dependencies should be resolved
**Observed behavior:** We have errors after resolving the project:
![selection_004](https://cloud.githubusercontent.com/assets/1640058/18056395/5c085234-6e14-11e6-9483-dcc334109cfc.png)

_This problem create mistakes in the  next seleniu tests:_
ChecFactoryWithMultiModuleTest
CheckOpenFileFeatureTest
CheckRunCommandFeatureTest
CreateFactoryFromDashBoard
CreateSimpleFactoryFromIDETest

**Che version:**   4.7.0-RC2-SNAPSHOT, rev: 15998af27fadd66e
**OS and version:** Ubuntu OS 14.0
**Docker version:** 1.12.0
**Che install:**  local vagrant

**Comment by bmicklea** [comment]
Blocker because of regression.

**Comment by riuvshin** [comment]
I believe that issue is related to branch CHE-1818 which @garagatyi  working on it is not affected on 4.7.0

**Comment by TylerJewell** [comment]
@support - please reverify.

**Comment by musienko-maxim** [comment]
It is not actual
