### ISSUE TITLE
Cannot create a factory from Dashboard templates

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#654]
**CHE-1818**

**Reproduction Steps:**
1. Go to the Dashboard ->Factories -> Template -> can used Minimal or Tempalte

**Expected behavior**: should be created the valid factory from template 

**Observed behavior:** we have a error like: Not a JSON Object: ... Factory with id 'undefined' was not found
![selection_005](https://cloud.githubusercontent.com/assets/1640058/18058179/d68480a8-6e1b-11e6-9b0c-093d509e362e.png)

**The sample of data in the request:**

`-----WebKitFormBoundaryz2RuJ66aQBtDzitf
Content-Disposition: form-data; name="factory" `

`{"v":"4.0","workspace":{"projects":[{"links":[],"name":"Spring","attributes":{"languageVersion":["1.6"],"language":["java"]},"type":"maven","source":{"location":"https://github.com/codenvy-templates/web-spring-java-simple.git","type":"git","parameters":{"keepVcs":"false","branch":"3.1.0"}},"modules":[],"path":"/Spring","mixins":["git"],"problems":[]}],"defaultEnv":"wss","name":"wss","environments":[{"machineConfigs":[{"dev":true,"limits":{"ram":2048},"source":{"location":"https://dockerfiles.codenvycorp.com/templates-4.0/factory/factory-dockerfile","type":"dockerfile"},"name":"dev-machine","type":"docker"}],"name":"wss"}],"links":[]}}
------WebKitFormBoundaryz2RuJ66aQBtDzitf--  `

**Che version:**   4.7.0-RC2-SNAPSHOT, rev: 15998af27fadd66e
**OS and version:** Ubuntu OS 14.0
**Docker version:** 1.12.0
**Che install:**  local vagrant

**Comment by bmicklea** [comment]
Blocker because of regression.

**Comment by riuvshin** [comment]
I believe that issue is related to branch CHE-1818 which @garagatyi  working on it is not affected on 4.7.0

**Comment by bmicklea** [comment]
Why was this closed?  Is it fixed?  If so please add a milestone label. If not please explain why it was closed.
