### ISSUE TITLE
Factory with direct URL feature does not work

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#655]
**CHE-1818**
**Reproduction Steps:**

After consuming the factory like in this template: https://aio.codenvy-dev.com/f?url=https://github.com/musienko-maxim/quickstart

**Expected behavior:** Should be created the new  workspace. The quick started project should be cloned.

**Observed behavior:** We have 500 error. See screenshot also 

![selection_006](https://cloud.githubusercontent.com/assets/1640058/18058735/646c54b6-6e1e-11e6-8394-a5248aaae97f.png)

Additional information:

**Che version:**   4.7.0-RC2-SNAPSHOT, rev: 15998af27fadd66e
**OS and version:** Ubuntu OS 14.0
**Docker version:** 1.12.0
**Che install:**  local vagrant

**Request data:** 

`{"environments":{"quickstart":{"machines":{"ws-machine":{"servers":{},"agents":["ws-agent"]}},"recipe":{"type":"compose","content":"---\nversion: null\nservices:\n  ws-machine:\n    ports: []\n    dependsOn: []\n    build: null\n    links: []\n    command: []\n    environment: {}\n    memLimit: 2097152000\n    containerName: null\n    labels: {}\n    expose: []\n    volumesFrom: []\n    volumes: []\n    image: \"codenvy/ubuntu_jdk8\"\n    entrypoint: []\n","contentType":"application/x-yaml"}}},"defaultEnv":"quickstart","projects":[{"links":[],"name":"quickstart","attributes":{},"type":"blank","source":{"location":"https://github.com/musienko-maxim/quickstart","type":"git","parameters":{"branch":"master"}},"path":"/quickstart","problems":[],"mixins":[]}],"name":"musienko-maxim","commands":[],"links":[]}`

**Comment by bmicklea** [comment]
Blocker because of regression.

**Comment by riuvshin** [comment]
I believe that issue is related to branch CHE-1818 which @garagatyi  working on it is not affected on 4.7.0

**Comment by garagatyi** [comment]
Cannot reproduce. Probably is already fixed.
