### ISSUE TITLE
Just created github key is not stored (regression)

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#656]
Reproduction Steps:
1. Go to the Preferences -> VCS
2. Click on 'Octocat' icon, generate new key (authorize by oAuth window if it need)

**Expected behavior:** the new key should appear in the widget

**Observed behavior:** there is no any keys.

**Che version:**   4.7.0-RC2-SNAPSHOT, rev: 15998af27fadd66e
**OS and version:** Ubuntu OS 14.0
**Docker version:** 1.12.0
**Che install:**  local vagrant

**Additional information:**
I have tried check just added key by next API url: https://aio.codenvy-dev.com/api/ssh/vcs. But i got empty JSON

**Comment by bmicklea** [comment]
Blocker because of regression.

**Comment by JamesDrummond** [comment]
@mkuznyetsov To use the 'Octocat' icon you need to setup oauth in the che.properties. See [https://eclipse-che.readme.io/docs/git](https://eclipse-che.readme.io/docs/git) . I think the intent of the 'Octocat' icon is to make it easier to use github if the che.properties includes values for the oauth properties. I think an enhancement might be to disable this icon if the oauth have not been set in the che.properties file and give a hover over message that tells the user to set these values to enable.

**Comment by TylerJewell** [comment]
@JamesDrummond - enhancements have to be treated as separate issues apart from blocker bugs, under a different issue label & id.  So for the blocker, we just need to solve the issue for the behavior that has regressed.  And if there are additive behaviors that should be added, please file those in a different ticket and get UX-input on how the experience should be.

**Comment by JamesDrummond** [comment]
@bmicklea Issue #2253 I don't think this is related to this issue as the 'Octocat' icon is suppose to use oauth. 'Octocat' icon when pressed creates private/public keys, transfers the public key to github through oauth authentication and creates the entry in the VCS window.

**Comment by JamesDrummond** [comment]
@TylerJewell I don't think this is a blocker/bug. I think this is per the specifications. I will add a separate issue for the enhancement. Just wanted to bring it up here for discussion here but didn't intend to hijack this issue.

**Comment by riuvshin** [comment]
I believe that issue is related to branch CHE-1818 which @garagatyi working on it is not affected on 4.7.0

**Comment by JamesDrummond** [comment]
@musienko-maxim What is the status on this with the release of 5.0.0-M4?

**Comment by TylerJewell** [comment]
@support - please reverify.

**Comment by musienko-maxim** [comment]
It is not actual
