### ISSUE TITLE
Add support in server side of AWS user credentials for ECR configured in dashboard

### ISSUE THREAD

**Issue by mmorhun** [codenvy/codenvy#660]
Allows, using credentials configured by a user in the dashboard, access AWS ECRs for push/pull and build docker images.
Related to #642

**Comment by bmicklea** [comment]
Would this work be required if the AWS ECR was configured in a config file?  Or is this only for dashboard configuration?

**Comment by bmicklea** [comment]
We will address this through configuration files instead of UD.
