### ISSUE TITLE
Add ability to configure registry for snapshots for each workspace

### ISSUE THREAD

**Issue by mmorhun** [codenvy/codenvy#663]
For now, registry, in which all snapshots of all workspaces is stored, defined in Codenvy system properties. We need to allow to a user configure this parameter per workspace (UI issue for this is [here](https://github.com/codenvy/codenvy/issues/662)). When a user do not configure this parameter for a workspace, value from Codenvy system properties will be used as default.

**Comment by bmicklea** [comment]
No need for UI - this can be addressed through configuration files.

**Comment by garagatyi** [comment]
We will address this through configuration files instead of on a per-workspace basis.
