### ISSUE TITLE
Rework members of organizations to fix build

### ISSUE THREAD

**Issue by sleshchenko** [codenvy/codenvy#673]
For now build of [codenvy-hosted-api-organization](https://github.com/sleshchenko/codenvy/tree/organizations/wsmaster/codenvy-hosted-api-organization) fails because of changes in https://github.com/codenvy/codenvy/commit/0745562066888e7971563b6a5275f44a8bad66cc
It is need to rework members in the same way to fix build and keep old functionality

**Comment by bmicklea** [comment]
@sleshchenko is this issue closed?  Was there a PR merged for this already?

**Comment by sleshchenko** [comment]
@bmicklea Yes, It is already merged into master https://github.com/codenvy/codenvy/commit/4e72d461e594f35f016bbe58a44965d1c7bd5731 Sorry that I forgot to close it
