### ISSUE TITLE
installation manager resource check doesn't work with substituted directory

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#676]
If I use the installation manager with `--install-directory=<directory>` flag then the installation manager pre-flight checks should show the amount of disk space on my install directory. Instead it seems to still be checking the home directory.

Reproduction Steps:
- Execute the installation manager CURL with the `--install-directory` flag, noting the free space in the passed in directory and the free space in the /home directory.

Expected behavior:
The disk space available in the IM resource checks should equal the disk space for the passed in install-directory.

Observed behavior:
The disk space available in the IM resource checks seem to equal the disk space in the /home directory.

Codenvy version: 4.7
OS and version: RHEL 7.2

Additional information:
Problem can be reliably reproduced: Yes with customer system

**Comment by dmytro-ndp** [comment]
@bmicklea: 
> The disk space available in the IM resource checks should equal the disk space for the passed in install-directory.
We should check /home directory on availability of 1GB so as there are two accounts created as well:
- /home/codenvy / - to hold Codenvy on-prem ws master + workspaces files + ....;
- /home/codenvy-im - to hold Installation Manager Server.

**Comment by bmicklea** [comment]
Yes, I misunderstood what this option did. I'm closing as not relevant.
