### ISSUE TITLE
Potential data inconstistency between recipes, stacks and related permissions.

### ISSUE THREAD

**Issue by mshaposhnik** [codenvy/codenvy#677]
We have a functionality, which removing **recipe** or **stack** when latest permission with  `setPermission` action is removed (because nobody can manage this stack/permission anymore).

This method can  potentially be source of race conditions, when performing search by permissions in one thread, another thread can add/or remove another `setPermission`, so appropriate domain object (**stack** or **recipe**) will not be deleted, or vice versa, deleted despite another `setPermission` is added.
Same can happen when performing deletion of two users having `setPermission` to same object - they will see `setPermission` of each other, and base object will not be removed.

As a result, a solitary objects may be present in the DB, or user accidentally will not get permission to the stack/recipe. This cannot be fixed using simple JPA locks mechanism, because permissions is a separate table, so we can't lock it for removes/inserts by design.

Need to find a way to isolate those transactions using JPA locks mechanisms or manually managing somehow.

**Comment by skabashnyuk** [comment]
Possibility of this issue is extremely low.

**Comment by slemeur** [comment]
As we migrate and consolidate databases, I'm closing this issue.
