### ISSUE TITLE
Which ip address to Authorize while Connecting to Google Cloud SQL instance from Codenvy ?

### ISSUE THREAD

**Issue by toimransyed** [codenvy/codenvy#690]
Which ip address to Authorize while Connecting to Google Cloud SQL instance from Codenvy ?

**Comment by ddementieva** [comment]
@toimransyed Can you specify which Codenvy version you are using, Classic Codenvy (Codenvy 3)  or the next generation Codenvy (Codenvy 4)?

**Comment by toimransyed** [comment]
@ddementieva I am using classic (codenvy3)

**Comment by toimransyed** [comment]
@ddementieva @benoitf Can you please help?

**Comment by ddementieva** [comment]
@toimransyed If you want to connect through our datasource server, its current IP address is `54.162.0.254`.

If you want to connect directly to the Google Cloud SQL instance, you need to authorize our runners IPs: 
`54.161.206.8`
`54.166.39.167`
`54.197.103.71`
`23.23.63.112`

**Comment by toimransyed** [comment]
Thanks @ddementieva
