### ISSUE TITLE
Codenvy Milestone 4.7.1

### ISSUE THREAD

**Issue by JamesDrummond** [codenvy/codenvy#692]
## Milestone Overview
- NOTE: This release includes changes from Eclipse Che [milestone 4.7.1](https://github.com/eclipse/che/issues/2354).

For more information about our development process please see our [development process] (https://github.com/eclipse/che/wiki/Development-Process) page.

## Schedule
This release will be a development release available on GitHub only.

**Target Release Dates**
- Code complete milestone: **September 7**
- GitHub release complete (QA verified) milestone: **September 8**
- Release shipped milestone: **September 9**

#### Code complete milestone
- [x] Code complete
- [x] Smoke tests started

#### Release candidate created milestone
- [x] Release candidate created
- [x] Test cycles started
- [x] Docs reviewed

#### GitHub release complete (QA verified) milestone
- [x] Release complete
- [x] Release notes updated
- [x] Release information updated on GitHub

## Target Milestone Issues
The following issues are targeted for inclusion in the milestone. As issues are closed they are checked. Stretch goals are indicated with "*Stretch*" before the item.

**Comment by bmicklea** [comment]
@JamesDrummond please update or delete this.

**Comment by bmicklea** [comment]
@JamesDrummond - there were no Codenvy-specific issues?

**Comment by JamesDrummond** [comment]
@bmicklea No there was not any Codenvy-specific issues for this milestone.
