### ISSUE TITLE
Doesn't display a list of existing factories

### ISSUE THREAD

**Issue by olexii4** [codenvy/codenvy#694]
Doesn't display a list of existing user factories. Reproduced only  after page refresh.

Reproduction Steps:

1. Create a new factory.
2. Go to the factories list.
3. Refresh factories list page. 

Expected behavior:

Showing list of factories

Observed behavior:

Didn't have any factories in list 

Codenvy version: 4.8

Additional information:

**Request URL**: https://nightly4.codenvy-stg.com/api/factory/find? 
                        creator.userId=usernjdvwxz21ucm0o6r&maxItems=15&skipCount=0

**Status Code:**  500 Internal Server Error

**Response:**  Not a JSON Object: [{"name":"memoryLimitBytes","value":"2147483648"}]

Problem only started happening recently, didn't happen in an older version of Codenvy: Yes
Problem can be reliably reproduced: Yes

**Comment by garagatyi** [comment]
@riuvshin is it blocker?

**Comment by riuvshin** [comment]
I thinks yes.

**Comment by mkuznyetsov** [comment]
Fixed by script:
https://github.com/codenvy/codenvy/issues/680#issuecomment-245920877
