### ISSUE TITLE
Create a tool to import users from codenvy.com to codenvy.io

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#696]
We need to make a tool to migrate users and profiles from codenvy.com to codenvy.io. Only users that doesn't exists in codenvy.io should be migrated.

**Comment by TylerJewell** [comment]
Question - what if a user exists in both locations and the user has credit card data in Codenvy.com?  Do we preserve that data and history?

**Comment by skabashnyuk** [comment]
@TylerJewell up to you. I don't see any value to invent some complex logic of merging users. If you see please share.

**Comment by skabashnyuk** [comment]
We can think about that. Do you see any other important information to move?

**Comment by TylerJewell** [comment]
Let's plan to move any field from c3 that doesn't exist in c4 over.  This would be whether users are a duplicate or not.  I think it is just billing data but there could be other data.  Analytics does not need to be saved.   What about access history?

**Comment by skabashnyuk** [comment]
>What about access history?
What is it?

**Comment by TylerJewell** [comment]
If we store any information in our database about when or what a user accesses or logs in, saving that history would be useful.

**Comment by skabashnyuk** [comment]
AFAIK we don't have anything like that.

**Comment by skabashnyuk** [comment]
Dod of this issue is create tool for one time migration during C3 close. If we need to do it many times it can cause some strange errors that I would like to avoid.

**Comment by TylerJewell** [comment]
This tool needs to be run at the same time that we disable c3, or at least *turn off* any new account creation on c3.  Or, what we do is to change the "create account" link on c3 to redirect to codenvy.io so that only way for people to create new accounts is on c4 at that point.

**Comment by evoevodin** [comment]
I propose the next migration strategy.

### A few things to know
User has 3 unique attributes:
- _id_ - the identifier of user (it is generated by us it looks like `user5aykko6hahok6iji`)
it is generally unique, mandatory and not updatable 
- _name_ - the name of the user, it may be something like `user_ivan` it is generally unique, mandatory and updatable
- _email_ - the email of the user, it is generally unique, mandatory and updatable

From the described context the best possible way to link users on _c3_ and _codenvy.io_ is to match them by their emails.

### The strategy   

Let's say we are going to migrate the user with the following data:

```json
{
    "id" : "user123",
    "name" : "user_123",
    "email" : "user_123@gmail.com"
}
```

In this case we can be in 2 possible situations:

#### The user with such email exists

```json
{
    "id" : "user321",
    "name" : "user_321",
    "email" : "user_123@gmail.com"
}
```

It means that user is already registered on codenvy.io and 
doesn't need any migration as he was forced to fill his profile 
information on the registration flow, i don't think it's necessary to 
try and merge his profile information as we don't know for sure which 
is the freshest.

#### The user with such email doesn't exist

In this case we should try and migrate the user and his profile, 
if attempt is failed, report the fail and continue migrating the other users.
As this is not regular migration which should be performed by all the 
customers we can analyze errors after and decide what to do with 
those users who were not migrated successfully. 

Describes migration strategy is pretty simple and straightforward, it migrates only users and their profiles when users information is missing from codenvy.io database.

@TylerJewell, @skabashnyuk is it okay for you?
