### ISSUE TITLE
beta.codenvy.com Share function does not work

### ISSUE THREAD

**Issue by Ulimo** [codenvy/codenvy#700]
When going into a workspace in the codenvy beta and clicking on share, add member, the share button is grayed out, even though a correct email address is entered.

Reproduction Steps:

1. Create a new workspace
2. Go into the workspace settings
3. Click share
4. Click add member
5. Try and enter an email address
6. It is not possible to click share, even when removing disabled from the button in chrome dev tools, the user is not added.

Expected behavior:
The user should be added

Observed behavior:
The button is not clickable, and the user is not added.

Codenvy version: 4.7
OS and version: Codenvy beta web

**Comment by TylerJewell** [comment]
This behavior is expected right now.  Currently you can only share with others that also already have an existing Codenvy account.  We know that the information provided does not make this clear and also the expectation is that users want to invite anyone with an email address.  We will do another release that adds this ability soon.  @jamesdrummond can you link in the related issues for this to track

**Comment by Ulimo** [comment]
Sorry, missunderstood that you had to press enter when you had typed the email. A possible fix would be that you run the same command when you click outside the email box?

**Comment by JamesDrummond** [comment]
This is related to #529

**Comment by Ulimo** [comment]
You could close this if you would like and I could open one with the correct topic?

**Comment by TylerJewell** [comment]
@JamesDrummond - I think there are different issues, but I cannot find them.  I think the issues were about making it clear that within the share window - that users needed to be existing users and / or offering basic invites (not attached to factories) through emails alone. If you don't have the issues, I think @ashumilova has it.

Also @ashumilova - see the feedback from @Ulimo - it wasn't obvious that someone had to press enter when typing the email.

**Comment by ashumilova** [comment]
@Ulimo thank you for feedback, really have this UX issue that enter should be pressed - and there are ways to solve it. 
@TylerJewell we used to fix this issue https://github.com/codenvy/codenvy/issues/509 that we did not notify the user, that the provided email was not registered.

**Comment by MPNull** [comment]
@Ulimo you can always close your own issue :)

**Comment by eivantsov** [comment]
Closing this and let's track https://github.com/codenvy/codenvy/issues/529
