### ISSUE TITLE
Create docs for common UI customizations for white label installs

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#704]
This document outlines a set of common UI customizations that white label license holders want to make: https://drive.google.com/a/codenvy.com/file/d/0B4Go3CnInfkoWWh3Y200YllCWjg/view?usp=sharing

Please outline the steps needed to execute each of these items. Also add the following:

- Change any locations of "Help" (e.g. in the footer) to point to a different URL.
- Explain how to replace the logo in the loading screen as well as how to delete it.

**Comment by ashumilova** [comment]
https://docs.google.com/a/codenvy.com/document/d/1PRDwzeTFEViOp0lbLbIQoTssg9_HQVnuISC3AA_4IRc/edit?usp=sharing

**Comment by bmicklea** [comment]
Perfect, thanks Anna.
