### ISSUE TITLE
[Question] Auto-complete/Code-list

### ISSUE THREAD

**Issue by MPNull** [codenvy/codenvy#705]
Hello. Since I didn't found any community forum to ask questions I'll ask it here then. How do I can enable auto-complete system. In Visual Studio we're talking about Intellisense, but would be awesome if I can enable it to Codenvy somehow that it will show all available variables and usage tips.

We're talking about similar system than Intellisense, but for Codenvy. I found some information about it, but nothing related to how do I enable it. Since I don't know what it is called so I have no good keywords to search.

@TylerJewell @ddementieva maybe you know :+1: 

![](http://crm.vdsnickt.eu/wp-content/uploads/2009/07/Intellisense-4.jpg)

**Comment by ddementieva** [comment]
@MPNull There is auto-complete feature available only for Java and Javascript in Codenvy right now.

Try `ctrl+space` (Linux, Windows), `cmd+space` (mac).

**Comment by MPNull** [comment]
Works fine! Thank you!
