### ISSUE TITLE
Sometimes recently imported maven project may lose project type

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#707]
**Reproduction Steps:**
 Import the maven by GIT several times.

**Expected behavior:**
The project should be configured as maven always
**Observed behavior:**
Sometimes configured as blank
![anim](https://cloud.githubusercontent.com/assets/1640058/18386542/67cfb92e-76a0-11e6-8d89-4ce2f9faff6d.gif)

**Observed behavior:**
The command is duplicated

**Che version:**    5.0.0-M1  
**OS and version:** Ubuntu 14.04 LTS
**Docker version:** 1.12
**Che install:**   nightly server.
**Additional information:** This hapenes because the Contribution plugin may override the project type.

**Comment by vzhukovskii** [comment]
Time spent: 1d.
Time spent to merge: 1d.

**Comment by musienko-maxim** [comment]
Has been reproduced again in the  5.0.0-M3 version

**Comment by riuvshin** [comment]
moved to M5
