### ISSUE TITLE
Mounting volumes to workspaces - ideal solution

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#709]
Ideally mounting volumes to workspace would be possible through both the user dashboard and workspace / compose / factory definitions.

Capabilities
- Allow Codenvy admins to define a set of available mounts in the Codenvy configuration and through the admin dashboard.
- Codenvy should check to ensure they're not mounting /etc or /bin.
- When users create workspaces (single or multi-machine) or factories in the user dashboard they are presented with a selector that allows them to see all the defined mount points and choose the ones they want for each machine. When selecting a mount point they would have to provide an alias for it.
- Alternatively users can define the mount points in their workspace / factory definition.
- The syntax might look something like the following:

```
{ "machineName: "ws-main",
   ....,
   ....,
   "mountPoints":[
    { 
     "mountPoint":"/folder1",
      "alias": "/data"
    },
    { 
      "mountPoint":"/folder2",
      "alias":"/shared"
    } 
  ]

},
{
 "machineName: "machine-oracle",
   ....,
   ....,
   "mountPoints":[
    { 
     "mountPoint":"/folder1",
      "alias": "/logs"
    }
  ]
}
```

**Comment by TylerJewell** [comment]
This enterprise feature will still be useful for k8s.  We will need to move this to Eclipse Che once we have a valid installation of Che on k8s.

**Comment by eivantsov** [comment]
Yes, this can be theoretically possible with k8s persistent volume claims. However, there's no reason why this issue should be opened. k8s allows PVCs and cluster admin makes sure PVs are created and thus PVCs can be satisfied.

I am +1 for closing it, unless you think Che will provide some UI to manage k8s or OSIO cluster (very unlikely)

**Comment by eivantsov** [comment]
Closing the issue. k8s will offer own mechanisms of sharing data between pods and host.
