### ISSUE TITLE
assembly descriptor contains a *nix-specific root-relative-reference (starting with slash) / (Windows build issues)

### ISSUE THREAD

**Issue by motorina0** [codenvy/codenvy#710]
Building codenvy does not simply work with `mvn clean install`.
I'm describing below one of the problems and the found solution.
Please close this issues if the solution is accepted.

**Reproduction Steps:**
run `mvn clean install`

**Expected behavior:**
Build runs without errors.

**Observed behavior:**
Error:

> OS=Windows and the assembly descriptor contains a *nix-specific root-relative-reference (starting with slash) /

**Codenvy version:**  4.6.2
**OS and version:** Windows 7

**Additional information:**
Solution:
 - open all the files from` /site/assembly/assembly-*.xml`
 - replace `<outputDirectory>/</outputDirectory>` with `<outputDirectory>${file.separator}</outputDirectory>`

**Comment by ddementieva** [comment]
@motorina0 If you think it's a proper fix, create a pull request and our engineers will review.
