### ISSUE TITLE
I were wondering what's the reason for Codenvy loading the external POM file forever?

### ISSUE THREAD

**Issue by MPNull** [codenvy/codenvy#721]
If I add a new dependency to POM file. It works good once since it's my first start of application, but what's weird the dependency added to POM file (after) I have ran the application once will stay on this stage all the time:

```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building java-app 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/org/what/ever/dependency/it/is/whatever-1.0.pom
```

Basically it works if I restart the workspace by stopping it and running it again when it starts downloading hundred of files on start.

I've tried to "build" and I have tried "run" also I have tried commands directly from terminal: mvn install, mvn package and mvn compile, but all of those commands does the same. Maven will keep "downloading" the file without any results. As I mentioned before: It will work if I restart the workspace, but it's pretty frustrating to restart the workspace every single time I add a dependency. It wouldn't be problem for everyone, but as I'm a hobbyist so I test different kind of things and many dependencies by exploring nice things so I can learn more about Java and Maven dependencies.

**Comment by TylerJewell** [comment]
That does seem like unusual behavior.  @mmorhun @musienko-maxim @vparfonov @svor - please take a look and consider offering some advice as to what may be happening here.

**Comment by MPNull** [comment]
@TylerJewell I will add a video today since I don't know how to explain, but I will try explain it: Right now I can build application successfully (once) on every instance of workspace.

First:
1. I create a workspace no matter it is new or old I'm using. I choose Java template.
2. I navigate to workspace options/settings/preferences (whatever) and I create new project so Codenvy will import the simple console app "HelloWorld"
3. I add the maven dependencies plugin in order to make sure that the dependencies are copied to correct places that JAR is able to use them. (Issue we were talking about before)

The problem persist like this:
1. Start workspace
2. Add dependency (one dependency)
3. Build application (works as long as I don't add more dependencies on same run of workspace)
4. Add dependency (the secondary dependency on same run of workspace)
5. Build application (keeps loading POM)

No problem at all, everything works:
1. Start workspace
2. Add dependency (one dependency)
3. Build application
4. Add dependency (the secondary dependency)
5. Restart workspace
6. Build application (works with two dependencies, now I can build it as many times as I wish with two dependencies, BUT if I add third dependency now and I don't restart workspace it will keep loading the POM file again so basically I have to restart again the workspace in order to build the application)

Everything works fine after restart. I don't have to restart it on everytime I build the application. Only if I have built it already before adding a dependency.

**Comment by ddementieva** [comment]
@MPNull Which dependencies are you adding?

**Comment by eivantsov** [comment]
@MPNull can you provide update on this issue?

**Comment by eivantsov** [comment]
@MPNull I'd love to help you - can you provide me with some hints on how I can reproduce the issue?

**Comment by TylerJewell** [comment]
Closed - no response.
