### ISSUE TITLE
Setup & persist workspace (i.e. nvm, firebase-tools, polymer-cli, etc)

### ISSUE THREAD

**Issue by cywalker** [codenvy/codenvy#723]
Hi,

How do you persist a workspace?
I am trying to setup a workspace to support polymer & firebase development.
There is not a stack that has these components & dependencies (i.e. with later versions of node).
I have tried using snapshots, etc but can not seem to get persistance.

My test case is setting up nvm, restarting / snapshotting the workspace and trying to run nvm again (i.e. nvm -v). Before restarting / snapshotting I get the version, after nvm is not installed.

I am installing nvm using the following in the terminal;
```
curl https://raw.githubusercontent.com/creationix/nvm/v0.15.0/install.sh | bash
source ~/.nvm/nvm.sh
```

What is the correct way to setup a workspace in beta.codenvy.com and have changes outside of project files persist?

Any help greatly appreciated - thanks.
Cy.

**Comment by TylerJewell** [comment]
Hi @cywalker - It's possible that if you are using http://beta.codenvy.com, that this particular system does not auto-snapshot your workspaces when you stop them. There was a period of time where we had disabled auto-snapshotting for users as we were experimenting with functionality.  If this is still disabled, then in the Workspace menu you have a snapshot action that you can perform.  And if you do this manually, then when you restart the workspace, it will be restarted from the snapshot instead of the base image.  Can you give that a go?

**Comment by cywalker** [comment]
thanks - i gave that a go (got propmted 'do you want to recover from
snapshot' and selected yes) with the same result.
also, updated .bashrc seemed to revet (had appended line but missing on
restart)

On 11/09/2016 10:29 am, "Tyler Jewell" <notifications@github.com> wrote:

Hi @cywalker <https://github.com/cywalker> - It's possible that if you are
using http://beta.codenvy.com, that this particular system does not
auto-snapshot your workspaces when you stop them. There was a period of
time where we had disabled auto-snapshotting for users as we were
experimenting with functionality. If this is still disabled, then in the
Workspace menu you have a snapshot action that you can perform. And if you
do this manually, then when you restart the workspace, it will be restarted
from the snapshot instead of the base image. Can you give that a go?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/codenvy/codenvy/issues/723#issuecomment-246147685>, or mute
the thread

**Comment by TylerJewell** [comment]
@ddementieva @skryzhny - any ideas on what is going on here?

**Comment by cywalker** [comment]
Thanks - I have tested again & session has persisted within the snapshot.
However, at this time, I had to open workspace 2x before receiving prompt to recover from snapshot.

I will keep mindful of this while using beta - thanks.
