### ISSUE TITLE
Tweaking linting settings in editor

### ISSUE THREAD

**Issue by jlindenger** [codenvy/codenvy#724]
Is there any way to tweak the linting settings being used in the code editor pane? The editor seems to be able to recognize the file-type correctly and connect to the right linter, but I can't find any way to configure the it for a given project.

For example, I'm currently working on some JavaScript files and having the linter go crazy because I'm using ES6 syntax. I'd love to be able to either:
1. drop an .eslintrc file like [the one the dashboard code uses](https://github.com/codenvy/codenvy/blob/f1a51865d174d1c62435fdbee937f8ad7f1c07ec/dashboard/.eslintrc) in the project directory (and/or whatever other linter config files apply to the various languages used in the project), or
2. configure the linters for the project through preferences

Codenvy version: 4.7.2 (Current at beta.codenvy.com)

**Comment by TylerJewell** [comment]
@jlindenger - Sorry - somehow this issue slipped through my fingers.  This would need to be an enhancement to Eclipse Che (github.com/eclipse/che). We use Che's editor, which inherits from Orion.  And this sort of customization would be an extension to that.
