### ISSUE TITLE
Can not share workspace to another user

### ISSUE THREAD

**Issue by vinokurig** [codenvy/codenvy#725]
'Share' button in 'Share workspace' dialog does nothing.

**Reproduction Steps:**

1. Open configuration page of a workspace in dashboard.
2. Go to 'Share' tab.
3. Click 'Add member'.
4. Add a member.
5. Click 'Share' button

**Expected behavior:**

The member should be added to the permissions list of the workspace.

**Observed behavior:**

Nothing happens.

**Codenvy version:** 5.0.0-M1-SNAPSHOT
**OS and version:** Ubuntu 16, Chrome 53.0.2785.101 (64-bit)

Problem only started happening recently, didn't happen in an older version of Codenvy: Yes
Problem can be reliably reproduced: Yes

![screenshot from 2016-09-12 10-54-42](https://cloud.githubusercontent.com/assets/7668752/18428963/8b6d73ea-78d9-11e6-8a5d-ef4916030b77.jpg)

**Comment by ashumilova** [comment]
Fixed by https://github.com/codenvy/codenvy/issues/836
