### ISSUE TITLE
Add support for centrally setting multiple AWS ECR keys for image pulls

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#727]
Use Case:
As an admin I can setup a group of private AWS ECR container registries by inputting the account, region, registry ID and keys. These registries will then be available for developers in my organization to pull images from. When a developer pulls an image from one of these private registries the keys stored by the admin in Codenvy will be used (the user won't be asked for keys). Snapshots of the developer workspaces will be stored outside of ECR.

Requirements:
- Codenvy Admin can setup a group of available private AWS ECR registries (including account, region and keys) that can be accessed by users.
- All configuration is done through config files, no UI for AWS ECR registry setup.
- Developers can pull images for their workspaces from any of these pre-configured registries without being asked for keys.
- Developers use the normal UI in Codenvy to set the images to pull from, no unique UI is needed.
- Snapshots are stored in the normal location (not in the ECR).

Related Issues:
- [x] Enable support for multiple AWS ECR registries per install #742
- [x] Add ability to configure registry for snapshots for each workspace #663

**Comment by bmicklea** [comment]
Related to https://github.com/codenvy/codenvy/issues/524

**Comment by garagatyi** [comment]
I closed #663 since we decided to not configure snapshots location on per-workspace basis.

Requirements and Use Case sections in description of this PR says that support of ECR for snapshot management is not needed. Do we still need #515 #632 eclipse/che#2273 ? Because if we don't have to save snapshots into ECR these issues are out of scope for the use case.

**Comment by bmicklea** [comment]
I've removed #515 and #632 from this epic. I think eclipse/che#2273 is still needed though since Aurea still needs to be able to configure multiple AWS ECR registries from a config file.

**Comment by garagatyi** [comment]
eclipse/che#2273 is needed for snapshots management. I've asked Mykola to update the title.

**Comment by bmicklea** [comment]
So without that people can setup multiple AWS ECR registries through the configuration files with #742 ?

**Comment by garagatyi** [comment]
Yes
