### ISSUE TITLE
Customizing stacks

### ISSUE THREAD

**Issue by vlad-tury** [codenvy/codenvy#739]
I am implementing a custom plugin for Codenvy.
Part of this plugin is also to change the appearance of the UI.
First TODO:
    - remove all the predefined stacks and stack libraries
    - add myOwnDefined stack

**Reproduction Steps:**

1. Modify the stacks.json file by removing all the existing stacks and adding myOwnDefined stack
2. Make a deployment

**Expected behavior:**
3. After the deployment, if I want to add a new workspace I have just myOwnDefined stack

**Observed behavior:**

3. After the deployment, if I want to add a new workspace I have all the predefined stacks and also myOwnDefined stack

After a little digging I have observed that the stack data is persisted in a Mongo db database from where it is fetched when codenvy is started I assume.

I would have some questions here:
- What is the best way to remove all the stacks and keep just mine?
- Is there some config or utilitary service where I can specify that the stacks should not be retrieved from DB storage and that I will send them in stacks.json
- What are the default credentials for mongo db instance. I cannot connect to mongo db to query the stacks collection and remove the stacks in order to be sure that the stacks come from the DB.
- What are the default credentials to be able to delete stacks programatically via the Stacks API?

Thank you.
**Codenvy version:** 4.6.2
**OS and version:** CentOS 7.2

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: I don't know
Problem can be reliably reproduced: Yes

**Diagnostic bundle**
Execute the script on [this page](https://github.com/codenvy/codenvy/wiki/Support-Diagnostics) and post public link to the bundle here.
[report.zip](https://github.com/codenvy/codenvy/files/472279/report.zip)

**Comment by ddementieva** [comment]
@vlad-tury Execute the following commands to remove stacks from the mongo db:

```
# Stop Codenvy service
service codenvy stop

# Login to the mongo db, remove stacks and exit
mongo -u SuperAdmin -p password admin
use organization
db.stacks.remove({acl: {$elemMatch: {user:"*", actions:{$in: ["search"]}}}})
exit

# Start Codenvy service
service codenvy start
```

**Comment by vlad-tury** [comment]
@ddementieva Thank you for the quick response.
I got one more question. Is there a setting somewhere that can do the following?:
- if the setting is true, discard all the stacks from the database and use only those that I have provided?

**Comment by eivantsov** [comment]
@vlad-tury no, there's no such a setting. Running the above commands manually is the only way out right now.

**Comment by vlad-tury** [comment]
@eivantsov : OK, got it.

Regarding the stacks loading process I see a difference between the Eclipse Che and Codenvy.
For Eclipse Che it was enough to add stack.json to /myOwn-ide-assembly-main/src/assembly/stacks/stacks.json.

Eclipse Che knew to overwrite the stacks.json from /che-core-ide-stacks/src/main/resources/stacks.json with the one that I provided.

When I moved to Codenvy this does not work anymore. It seems that the predefined stacks are taken from Che, loaded in the system, then my defined stacks are taken and loaded as well.

What is the way to specify that I want the default predefined stacks overwritten with my own when before the *-all-in-one zip file is created.

Also I have observed that in the packaged archive that is deployed, stacks appear in 2 places:
- \onpremises-ide-packaging-tomcat-codenvy-allinone-4.6.2.zip\stacks\stacks.json
- \onpremises-ide-packaging-tomcat-codenvy-allinone-4.6.2.zip\webapps\dashboard.war\assets\html\che-stack.json

Why are there 2 such json files and how can I make sure that in this files only my stacks appear.

Thank you for the support!

**Comment by ddementieva** [comment]
@vlad-tury \onpremises-ide-packaging-tomcat-codenvy-allinone-4.6.2.zip\webapps\dashboard.war\assets\html\che-stack.json is unnecessary file. We'll delete it.

**Comment by TylerJewell** [comment]
@vlad-tury - we have been doing a lot of work for Che and Codenvy on stack loading, stack editing within the UD. This will be a much stronger creation process.  This will be part of the 5.0 GA release which is now starting its milestone builds.  You have uncovered the best practice for uploading a custom set of stacks within Codenvy.

If you are looking for consistency about loading stacks from Che / Codenvy, the underlying storage mechanisms are different, so a stacks.json in one will not necessarily be the same file / location in the other.  One thing you may consider is that the stacks has a REST API.  You may want to write a quick script that allows you attach to che / codenvy and then removes all stacks you don't want and then loads the stacks you do want.  This script would work (mostly) identically between the two systems.  You would run this when the system first boots.  That may not be ideal if you are looking to create white lable packages, though.

**Comment by vlad-tury** [comment]
@ddementieva , @TylerJewell , @eivantsov - Thank you for the support.
Indeed I have seen in the Issues page a lot of tasks regarding the stacks loading process.
My fix consisted at this point of manually deleting the stacks from the MongoDB database and making sure that in my *-allinone-*.zip I have the correct stacks.
You are right. though. For the first installation we need some sort of script that cleans the stacks collections from the database, so we know that we start with a clean plate.

Regarding the consistency issue between Che and Codenvy, is there a documentation of some sort that describes what are the application areas that differ between Che and Codenvy.

If there is not one, is it something you might think about for the future?
It would make the life of the person that worked with Che and now is passing to Codenvy much easier.

**Comment by TylerJewell** [comment]
I agree that having great docs about how to migrate extensions and customizations from Che to codenvy is a good idea.  It is probably premature for us to write such a document just yet as we are still learning about how to handle migrations ourselves.   

What we are trying to do now is to provide really good independent documentation for each system independently and then when we uncover areas like this where users struggle to switch, we want to go back into the product and think about how to evolve it to make it simpler.  

@bmicklea - this use case of importing stacks after a first install is legitimate and not something that is in the UI.  So we have to help with instructions for how to do it manually.

**Comment by TylerJewell** [comment]
Going to close this as I think the core issue has been resolved.
