### ISSUE TITLE
upload file option is disabled

### ISSUE THREAD

**Issue by joonspoon** [codenvy/codenvy#744]
I'm trying to add a jar to my project, but Project > Upload File is greyed out. 

Here's my workspace: https://beta.codenvy.com/dashboard/#/ide/joonspoon/robot

Problem can be reliably reproduced:yes

**Comment by ddementieva** [comment]
@joonspoon Can you verify that you've chosen folder or the project in the Project Explorer, not file?

Project > Upload File is active when you choose some folder or the project itself where you want to upload some file.

**Comment by joonspoon** [comment]
Thank you Daria! 

That solved my issue. I hadn't clicked on the folder.

Now when I go to configure the classpath, the "Add JAR" button is greyed out. 

Can you help me with that too?

**Comment by eivantsov** [comment]
@joonspoon what is you project type? Maven or Java? If Maven, then this is expected behavior since you control deps in `pom.xml`
