### ISSUE TITLE
Delete unnecessary stack json file

### ISSUE THREAD

**Issue by ddementieva** [codenvy/codenvy#751]
In the packaged archive that is deployed, stacks appear in 2 places:
- \onpremises-ide-packaging-tomcat-codenvy-allinone-4.6.2.zip\stacks\stacks.json
- \onpremises-ide-packaging-tomcat-codenvy-allinone-4.6.2.zip\webapps\dashboard.war\assets\html\che-stack.json

Why are there 2 such json files? We need to delete unnecessary stack json file.

**Comment by TylerJewell** [comment]
@ashumilova - is this still actual, or does the new M7 with stacks resolve this?

**Comment by ashumilova** [comment]
it's still actual, it's old trash in our dashboard source code.
