### ISSUE TITLE
Stacks recipe are not displayed in the list of workspaces

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#752]
The stack information is not displayed in the list of workspaces.

![screen shot 2016-09-15 at 16 23 37](https://cloud.githubusercontent.com/assets/1636769/18554092/6a419570-7b63-11e6-8bbf-e30c42fdb268.png)

Seems reproductible with workspaces that were created before 4.7.x

**Codenvy version:** 4.7.2

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: Yes
Problem can be reliably reproduced: Yes

**Comment by slemeur** [comment]
This is fixed with 5.0.0-M7

<img width="1558" alt="screen shot 2016-10-28 at 15 04 48" src="https://cloud.githubusercontent.com/assets/1636769/19807332/e694cb28-9d1f-11e6-8406-fbc46293848e.png">

**Comment by slemeur** [comment]
This issue is still accurate with 5.0.0-M7

<img width="1558" alt="screen shot 2016-10-28 at 16 46 40" src="https://cloud.githubusercontent.com/assets/1636769/19810523/1fa41dca-9d2e-11e6-8911-d45db347091f.png">

The workspace which is not displaying its stack name was using "java+mysql" stack

**Comment by slemeur** [comment]
@ashumilova + @olexii4 : what is your thinking on this?

**Comment by olexii4** [comment]
https://github.com/eclipse/che/commit/0f99f900c89a706035793a782333708c38dd0bf5
