### ISSUE TITLE
After consuming a factory by Direct URL the terminal does not work

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#755]
**Reproduction Steps:**
Consume a factory by direct URL and launch the terminal
**Expected behavior:**
Terminal should work
**Observed behavior:**
Terminal cannot establish connection by WebSocket
![anim](https://cloud.githubusercontent.com/assets/1640058/18580474/7f2b5de4-7c04-11e6-997a-f994b34c3466.gif)

**Che version:**   5.0.0-M1
**OS and version:** UBUNTU 14  
**Browser **  Chrome browser v.51.

**Comment by riuvshin** [comment]
regression

**Comment by bmicklea** [comment]
@vparfonov is there anyone working on this Vitalii?

**Comment by bmicklea** [comment]
Does this only affect factories that are referencing repo URLs directly?  Or does this behavior affect all Factories with `/f?` syntax?

**Comment by musienko-maxim** [comment]
In the 5.0.0.-M4 version can not reproduce
