### ISSUE TITLE
Factories aren't opening from dashboard

### ISSUE THREAD

**Issue by AndreyChizhikov** [codenvy/codenvy#766]
**Reproduction Steps:**
1.Create factory on dashboard
2. Click 'Open' factory

**Observed behavior:**
 Factory is not opening in editor
![create_factory](https://cloud.githubusercontent.com/assets/8051404/18625712/f28c8910-7e58-11e6-8083-d0132d87a2a1.gif)

**Codenvy version:** 5.0.0-M2-SNAPSHOT
**OS and version:**  Ubuntu 14.04 LTS

Problem only started happening recently, didn't happen in an older version of Codenvy: Yes 
Problem can be reliably reproduced: Yes

**Comment by ashumilova** [comment]
Resolved

**Comment by AndreyChizhikov** [comment]
Reproduce

**Comment by ashumilova** [comment]
Fixed.
