### ISSUE TITLE
Page with settings of factory  is not openning on dashboard

### ISSUE THREAD

**Issue by AndreyChizhikov** [codenvy/codenvy#767]
**Reproduction Steps:**
1. Try to opening any created factory on dashboard

**Observed behavior:**
Page with settings of factory  is not loading
![open_factory](https://cloud.githubusercontent.com/assets/8051404/18626189/10d02b5e-7e5c-11e6-92a3-ca082e495630.gif)

Codenvy version: 5.0.0-M2-SNAPSHOT
OS and version: Ubuntu 14.04 LTS

Problem only started happening recently, didn't happen in an older version of Codenvy: Yes 
Problem can be reliably reproduced: Yes

**Comment by ashumilova** [comment]
Fixed
