### ISSUE TITLE
GAE appcfg Rollback

### ISSUE THREAD

**Issue by joaquimcarmona** [codenvy/codenvy#769]
I have the same problem as described here:
[https://groups.google.com/a/codenvy.com/forum/#!topic/codenvy/frIw3e9CQJ0](url)

i.e., when deploying a GAE app I get the following error message:

> 09:54:13  Failed to deploy to Google App Engine due to an error: Error posting to URL: https://appengine.google.com/api/appversion/create?app_id=rede-160318&version=1& 409 Conflict Another transaction by user joaquim.carmona is already in progress for app: s~rede-160318, version: 1. That user can undo the transaction with "appcfg rollback".

I proceeded as suggested 

> Hi, This problem may be caused by the failed deploy process. It is possible to do an appcfg rollback in the Terminal during the project runtime with <./appcfg.sh rollback /home/user/app> command, if you have a Java project, and with <./appcfg.py rollback /home/user/app> command for the Python and PHP projects. You can run your project with Run > Run option and you'll find the Terminal in the Runner Tab.

with the following result.

![160919](https://cloud.githubusercontent.com/assets/12966705/18627371/7de0f05c-7e52-11e6-8670-c4c1b59f6f9b.png)

How should I do the rollback?

Thanks in advance.

Regards

J Carmona

**Comment by eivantsov** [comment]
@joaquimcarmona I strongly recommend that you use beta.codenvy.com which is a new generation system. Although there's no GAE plugin there, you can perform all deployments via the command line https://eclipse-che.readme.io/docs/che-and-gae

**Comment by joaquimcarmona** [comment]
Thank you for your prompt reply.

The link you sent is not for java apps... Is there one for these?

Did I do something wrong with the rollback command in the terminal window?

Regards

Joaquim Carmona

A Seg, 19 de Set de 2016, 12:38, Eugene Ivantsov <notifications@github.com>
escreveu:

**Comment by eivantsov** [comment]
@joaquimcarmona yes, you are executing this command in a wrong directory. Find directory with GAE SDK in `/home/user`

**Comment by joaquimcarmona** [comment]
Thank you.

I got it to work like this:

1. changed directory to _/home/user/appengine.../bin_
2. used _./appcfg.sh --oauth2  rollback /home/user/app_
3. input id and password when requested
4. went to the site whose address is displayed as requested and authorized access
5. copied the code displayed back in the terminal window.
