### ISSUE TITLE
Find factory functionality doesn't work in swagger

### ISSUE THREAD

**Issue by garagatyi** [codenvy/codenvy#783]
Swagger is used as API client to test Codenvy API. But Find factory functionality works incorrect because this API requires not annotated query params, so swagger parser doesn't found it and doesn't show input field for these params.

Url of this functionality is swagger: https://aio.codenvy-dev.com/swagger/#!/factory/getFactoryByAttribute

Error:

```
{
  "message": "Query must contain at least one attribute"
}
```

**Codenvy version:** 5.0.0-M2-Snapshot

**Comment by skabashnyuk** [comment]
won't fix.
