### ISSUE TITLE
Factory accepting is broken in UD

### ISSUE THREAD

**Issue by garagatyi** [codenvy/codenvy#784]
Factory accepting is broken in UD.

**Reproduction Steps:**

Accept factory https://beta.codenvy.com/f?id=w1th701vh0c9ekfv on beta.

**Expected behavior:**

Factory is accepted, workspace started.

**Observed behavior:**

UD hangs. Error appears in dev tools console of browser.
![image](https://cloud.githubusercontent.com/assets/1851863/18660208/e5fc19a8-7f17-11e6-86aa-92f7c2e72d02.png)

**Codenvy version:** 5.0.0-M1-Snapshot

**Comment by riuvshin** [comment]
@garagatyi can you please provide correct factory url because this one in description does not exist. It says `Factory with id 'w1th701vh0c9ekfv' was not found`

**Comment by garagatyi** [comment]
No, I lost it. But I suppose that error still can be fixed.

**Comment by ashumilova** [comment]
For now - cannot reproduce the error

**Comment by riuvshin** [comment]
Agree seems it is not actual any more
