### ISSUE TITLE
Cannot run factory from SaaS Cloud on beta

### ISSUE THREAD

**Issue by AndreyChizhikov** [codenvy/codenvy#785]
**Reproduction Steps:**
Try to run factory from :
https://www.eclipse.org/che/getting-started/cloud/
**Observed behavior:**
![factory-eclipse](https://cloud.githubusercontent.com/assets/8051404/18660413/f097e710-7f18-11e6-8236-f4e16cec50e2.png)

**Codenvy version:** 5.0.0-M1
**OS and version:**  Ubuntu 14.04 LTS

**Additional information:**
https://beta.codenvy.com
Problem only started happening recently, didn't happen in an older version of Codenvy: Yes 
Problem can be reliably reproduced: Yes 

Factory to reproduce: http://beta.codenvy.com/f?id=9skz1321dxbqpj5j 
(Vert.x verticle)

**Comment by garagatyi** [comment]
It is because some factories use URLs to dockerfiles hosted on codenvycorp.com which returns content type header octet stream. Docker doesn't support that. We should workaround that somehow.

**Comment by slemeur** [comment]
Why it was working perfectly before?

**Comment by garagatyi** [comment]
It wasn't. It was not tested.

**Comment by slemeur** [comment]
It was. All the factories on the getting started page on eclipse Che website were using this mecanism...

https://www.eclipse.org/che/getting-started/cloud/

**Comment by skryzhny** [comment]
I changed content-type for https://dockerfiles.codenvycorp.com/templates-4.0/factory/factory-dockerfile
Can you retest?

**Comment by slemeur** [comment]
Still the same with the vertex factory

**Comment by riuvshin** [comment]
just tested on beta
spring rest guide - works.

**Comment by riuvshin** [comment]
seems that @skryzhny fixed issue, @slemeur  can you recheck this? btw please be patient it took a while to start ws due to agents and heavy loading on beta 1st time I thought it hung on crane but after 1-2 mins it finally started.

**Comment by riuvshin** [comment]
it is fixed by https://github.com/codenvy/codenvy/issues/779
