### ISSUE TITLE
After running  factory, project isn't present in workspace

### ISSUE THREAD

**Issue by AndreyChizhikov** [codenvy/codenvy#788]
**Reproduction Steps:**
1. Run factory ['eXo Task add-on'](http://beta.codenvy.com/f?id=vu1kgww8udkbd6ie) from  [Saas Cloud](https://www.eclipse.org/che/getting-started/cloud/)
2. Try to open project
**Observed behavior:**
Project has not been imported.
![open-project](https://cloud.githubusercontent.com/assets/8051404/18664800/debac904-7f2c-11e6-9fbd-0ee7775686c0.png)

Codenvy version: 5.0.0-M1
OS and version: Ubuntu 14.04 LTS

Additional information:
https://beta.codenvy.com
Problem only started happening recently, didn't happen in an older version of Codenvy: Yes 
Problem can be reliably reproduced: Yes

**Comment by JamesDrummond** [comment]
Please verify if this issue still exists.

**Comment by ashumilova** [comment]
Issue confirmed by @olexii4

**Comment by olexii4** [comment]
Depends on   https://github.com/codenvy/codenvy/issues/1697

**Comment by olexii4** [comment]
I copied factory with id=vu1kgww8udkbd6ie and add it to https://nightly.codenvy-stg.com -  problem was confirmed.
When I copy the factory's workspace recipe to custom gist and add 'RUN sudo usermod -p "*" exo'  - all problems are gone.
