### ISSUE TITLE
Add support for AWS ECRs configuration properties in puppet

### ISSUE THREAD

**Issue by mmorhun** [codenvy/codenvy#789]
We need to support with puppet set of properties which is kept AWS ECRs credentials.
Each AWS ECR can be configured with 4 properties:
```
docker.registry.aws.<registry-name>.id=
docker.registry.aws.<registry-name>.region=
docker.registry.aws.<registry-name>.access_key_id=
docker.registry.aws.<registry-name>.secret_access_key=
```
None of them are allowed to be null or empty.

Also we need migration.
Before we have only one set for only one Amazon registry:
```
docker.registry.aws.id=
docker.registry.aws.region=
docker.registry.aws.access-key-id=
docker.registry.aws.secret-access-key=
```
Which could be empty.
So if it empty, we should remove them. If not, convert to new format.
For example:
`docker.registry.aws.access-key-id=<some_id>` => `docker.registry.aws.default.access_key_id=<some_id>`

Is needed for #742

**Comment by riuvshin** [comment]
done
