### ISSUE TITLE
Implement workspace cap that prevents users from running more than X workspaces

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#792]
As an admin I need a way to set a limit on the number of workspaces a user can run simultaneously. This limit should be called: `limits.user.workspaces.run.count`

This would prevent situations where developers chew up too many resources on simultaneously running workspaces.

Default value: 3

**Comment by vinokurig** [comment]
@bmicklea What default value should be set for this property? How about maximum 10 started workspaces per user?

**Comment by bmicklea** [comment]
@vinokurig default should be 3
