### ISSUE TITLE
Add "Settings" page on Team details

### ISSUE THREAD

**Issue by ashumilova** [codenvy/codenvy#798]
_Team settings:_
![8 - team details - settings simplified](https://cloud.githubusercontent.com/assets/1636769/18912843/d9208bb0-8584-11e6-9b3f-9013aff9899c.png)

The section related to **Team repositories** and **Team Integrations** are out of scope for first phase
A team leader will be able to require each developers of the team to configure certain settings. Those can be access to private repositories and servers, databases.

**Comment by gazarenkov** [comment]
What is Team Resources section for?
It does not reflect any Workspace setting.

**Comment by slemeur** [comment]
It is all integration with servers, databases and services that might be necessary while working in a team. Team admin, might configure specials workspaces with commands which will be executed on external services.

**Comment by slemeur** [comment]
FYI - it is out of scope as first phase

**Comment by gazarenkov** [comment]
@slemeur  the question is - how it will impact Workspace configuration, I see no relation with the model

**Comment by slemeur** [comment]
There might need to adapt the model a little bit.

Let me explain a bit the use case.

Our customers often have heterogeneous context and various internal services that are used by the developers. It can be private git repositories, private registries or servers... All of this is internal in general. 
When a team lead is sharing a workspace, he wants to ensure that the developers are going to setup access to those private resources properly. They might need authentication, credential, SSH keys.

There are two ways a team lead would be able to require those settings:
 1- for any of the workspaces created as part of the team
 2- for specific workspaces templates of the team

In the case *1*, the settings are asked to the user, when he is joining the team. This way, the settings are configured once - and used for all workspaces.

In the case *2*, the settings are asked to the user, when he is creating his own workspace based on a workspace template.

**Comment by gazarenkov** [comment]
I am confused
You mentioned 
"It can be private git repositories, private registries or servers"

OK
VCS Registry is a part of project configuration (sources)
Docker Registry is a part of machine (environment) configuration
You have a Repository in this UI (which should also have a type in general case BTW)

BUT 
You also have Team Integration section with some A10, AWS, OpenShift things.
What is it?

As for the user private data - I do not understand why it is bound to Workspace/Template.
It is user's data, not team's or workspace's.
So if I ask to store it once I do not expect to to do that over and over again?

**Comment by slemeur** [comment]
No and that's the goal. 
If developers of the team have configured accesses to internal repositories - from Team Level - then it will not be asked for each workspace. It will be asked once and shared to all workspaces the developers will have in this team.

Team Integration are external or internal services that are used in workspaces. The developers, as part of the team, need to configure them, in order to be able to use it.

**Comment by gazarenkov** [comment]
You commented on the second issue only.
As I understand what you said is that developer will be able to configure his security properties ONES, on-demand and from several places. If so, I am ok with this.

On the first issue - mapping between "Team Integration" and workspace data is still not clear to me.

**Comment by slemeur** [comment]
![8 - team details - settings simplified](https://cloud.githubusercontent.com/assets/1636769/18912828/c6f04ca0-8584-11e6-92f2-110220d72942.png)

Mockups with the only needed part to start with Phase 1

**Comment by slemeur** [comment]
**For Phase1:**
Only the already implemented CAPs in the API are needed.

@sleshchenko : Could you please confirm the ones that are already in place?

**Comment by ashumilova** [comment]
depends on https://github.com/codenvy/codenvy/issues/1073 and https://github.com/codenvy/codenvy/issues/1074

**Comment by ashumilova** [comment]
https://github.com/codenvy/codenvy/pull/1844
