### ISSUE TITLE
Ability to create a workspace in a Team

### ISSUE THREAD

**Issue by ashumilova** [codenvy/codenvy#801]
User is able to choose team on worskpace creation page
![create workspace in team](https://cloud.githubusercontent.com/assets/1636769/18707105/e1097642-7ff4-11e6-8bc9-00208ec8ccda.png)

**Comment by gazarenkov** [comment]
1/ Workspace's Resource Owner (i.e. Team) can not be updated. It is assigned when workspace created. So I do not see the needs in several Team buttons.
2/ I would recommend disabling "Delete" when workspace is running

**Comment by slemeur** [comment]
1/ The flow to create a workspace or edit it, will use the same UI. Those buttons will be unactive when the workspace will be edited. #1769

2/ I would prefer asking the user to confirm his choice and be notified about the impacts.

**Comment by gazarenkov** [comment]
Ok

**Comment by ashumilova** [comment]
https://github.com/codenvy/codenvy/pull/1844
