### ISSUE TITLE
SSH key never gets injected into workspace machine

### ISSUE THREAD

**Issue by eivantsov** [codenvy/codenvy#804]
Cannot ssh into a workspace machine with a private key

**Reproduction Steps:**
1. Upload or generate key at Profile > Preferences > SSH > Machine
2. Restart a workspace

**Expected behavior:**

The key gets injected into `~/.ssh/authorized_keys`

**Observed behavior:**

The key does not get injected into `~/.ssh/authorized_keys`

**Codenvy version:** 5.0-M3-SNAPSHOT

**Additional information:**

It looks like we expect userID on getOwner while userName gets returned which explains why this problem does not occur in Che.

Expecting userID here - https://github.com/eclipse/che/blob/master/plugins/plugin-machine/che-plugin-machine-ext-server/src/main/java/org/eclipse/che/ide/ext/machine/server/ssh/KeysInjector.java#L72-72

**Comment by bmicklea** [comment]
@eivantsov will this prevent mounts from working?

**Comment by eivantsov** [comment]
@bmicklea only using ssh keys.

**Comment by benoitf** [comment]
Like a blocker for ssh stuff (connecting with ssh workpace keys)
I've provided a fix with https://github.com/eclipse/che/pull/3036
