### ISSUE TITLE
Copying json file of workspace does not work on the dashboard

### ISSUE THREAD

**Issue by artaleks9** [codenvy/codenvy#808]
**Reproduction Steps:**
* Select a workspace and press the 'Export As A File'
* Try to copy json file by 'Ctrl + C' or 'Clipboard'.  

**Expected behavior:**
The json file should be copied.

**Observed behavior:**
The json file is not copied.

**Codenvy version:** 5.0.0-M3
**OS and version:** ubuntu 14.04 LTS

**Additional information:**
Problem can be reliably reproduced: Yes

**Comment by olexii4** [comment]
3h
