### ISSUE TITLE
Unexpected errors in the Ws-machine console after consuming Sourcegraph factory

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#810]
**Reproduction Steps:**
1. Go to the https://www.eclipse.org/che/getting-started/cloud/ page and try to launch  Sourcegraph example.

**Expected behavior:**
We should go to the workspace without errors. Project should be valid.
**Observed behavior:**
We have problem like on screenshot:
![selection_015](https://cloud.githubusercontent.com/assets/1640058/18712682/35417fde-8018-11e6-851c-240fc5312949.png)

**Codenvy version:** 5.0.0-M3
**OS and version:** ubuntu 14.04 LTS

**Comment by bmicklea** [comment]
Perhaps related to: https://github.com/codenvy/codenvy/issues/915

**Comment by TylerJewell** [comment]
Factory removed.
