### ISSUE TITLE
Running factory with 'PHP' template from SaaS Cloud comes with error

### ISSUE THREAD

**Issue by AndreyChizhikov** [codenvy/codenvy#816]
**Reproduction Steps:**
1. Start factory with  [PHP](http://beta.codenvy.com/f?id=5ayat0naxlljn3p2) template from [SaaS Cloud](https://www.eclipse.org/che/getting-started/cloud/)

**Observed behavior:**
`ERROR (org.eclipse.che.api.promises.client.callback.PromiseHelper): Error: Value for required attribute is not initialized java:java.source.folder`

![php](https://cloud.githubusercontent.com/assets/8051404/18714426/593dd12a-801e-11e6-9ecc-d32b03c290bb.png)

**Codenvy version:** 5.0.0-M2
**OS and version:** Ubuntu 14.04 LTS

**Additional information:**
https://beta.codenvy.com
Problem can be reliably reproduced: Yes

**Comment by kaloyan-raev** [comment]
I can reproduce the problem with the [PHP](http://beta.codenvy.com/f?id=5ayat0naxlljn3p2) factory, but not with the [AstroSplash](https://beta.codenvy.com/f?url=https://github.com/kaloyan-raev/AstroSplash) factory of my own.

So I suspect that it is a problem with the factory configuration.

@AndreyChizhikov Could you post the actual configuration of the [PHP](http://beta.codenvy.com/f?id=5ayat0naxlljn3p2) factory?

I noticed the Che tries to configure the web-php-simple project as a Java project, which is wrong. Perhaps, the project type is not set correctly in the factory configuration.

**Comment by TylerJewell** [comment]
@support - please reverify

**Comment by bmicklea** [comment]
Can't reproduce on 5.9
