### ISSUE TITLE
Improve error message when creating a factory from a workspace without projects.

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#819]
The error message displayed when creating a factory from a workspace without any projects is not clear. 

Instead of: "Unable to create factory from this workspace, because it does not contains projects with source storage set and/or specified path"

Use: "Factory can't be created. The selected workspace has no projects defined. Project sources must be available from an external storage."

![screen shot 2016-09-21 at 18 48 37](https://cloud.githubusercontent.com/assets/1636769/18720604/e104fc74-802c-11e6-9ee7-2348607ca6e6.png)

**Codenvy version:** 5.0.0-M2

**Comment by riuvshin** [comment]
error says that it is not possible to create factory for workspace wihtout projects, if we have that error handling maybe it is normal behaviour?

**Comment by slemeur** [comment]
yeah that was the issue but the error message is not clear. I changed the description of the issue

**Comment by ashumilova** [comment]
This restriction comes from here https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryService.java#L473 . But this is conceptual question - whether we continue saying that factory always describes workspace+project(s) or it can be empty workspace as well.

**Comment by ashumilova** [comment]
changed message
