### ISSUE TITLE
Impossible to upload factory configuration file

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#820]
Upload file for factory is not working.
![screen shot 2016-09-21 at 18 55 42](https://cloud.githubusercontent.com/assets/1636769/18720662/2c78ddce-802d-11e6-9de2-d1580ecafcb1.png)

**Reproduction Steps:**

1. Go to Factories
2. Create a new factory and select tab "Config"
3. Click on "Upload File"

**Expected behavior:**
A popup is displayed and allow the user to provide his config file.

**Observed behavior:**
Nothing is happening. No popup displayed

**Codenvy version:** 5.0.0-M2

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: Yes
Problem can be reliably reproduced: Yes

**Comment by ashumilova** [comment]
Fixed
