### ISSUE TITLE
Editor not displayed to create a factory from template

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#821]
When you are authoring a factory from the Dashboard, user has the ability to write the factory configuration file from a *minimal* or a *complete* template.
The editor is not shown

**Reproduction Steps:**
1. Go to *Factories* and create a new factory
2. Select tab "Template" and hit "Minimal" or "Complete"

**Expected behavior:**

The editor is displayed
**Observed behavior:**

No editor displayed, so it is not possible to write the factory.

**Codenvy version:** 5.0.0-M2

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: Yes
Problem can be reliably reproduced: Yes

**Comment by riuvshin** [comment]
editor should not be show here AFAIK, you first select template than click create and then will appear factory settings with editor.

**Comment by ashumilova** [comment]
Added editor
