### ISSUE TITLE
Switching editor tabs should move the highlight in the project explorer

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#824]
When I select an editor tab the project explorer should automatically highlight that file in the project explorer so I can see where the file is in the repo's structure.

We may want this to be an option the user can set in preferences so they can choose this behavior or the current behavior.

**Comment by TylerJewell** [comment]
I believe that this should be moved to Eclipse Che repository.

**Comment by bmicklea** [comment]
Good point - closing and replacing with https://github.com/eclipse/che/issues/2934
