### ISSUE TITLE
Can't load project types: Error

### ISSUE THREAD

**Issue by samtoomer** [codenvy/codenvy#833]
Open Java workspace containing 1 project
Starting workspace agent is displayed
Can't load project types: Error shown in centre of sceen
dev-machine console is shown below

Problem only started happening recently, didn't happen in an older version of Codenvy: Yes
Problem can be reliably reproduced: No - it's random

**Comment by eivantsov** [comment]
@samtoomer how much ram did you allocate for this workspace?

**Comment by motorina0** [comment]
Same problem for me on Codenvy 4.6.2. I've tried 1GB and 2 GB for the workspaces. For me it reproduces every time.

Last log lines from `/home/codenvy/codenvy-data/che-machines-logs/machineh53utuzmo6e6b3ss/1`
```
[STDOUT] 2016-09-27 08:42:37,448[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1030]       - Deploying web application directory /home/user/che/ws-agent/webapps/ROOT
[STDOUT] 2016-09-27 08:42:37,497[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1142]       - Deployment of web application directory /home/user/che/ws-agent/webapps/ROOT has finished in 49 ms
[STDOUT] 2016-09-27 08:42:37,501[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 470]  - Starting ProtocolHandler ["http-nio-4401"]
[STDOUT] 2016-09-27 08:42:37,505[main]             [INFO ] [o.a.catalina.startup.Catalina 642]   - Server startup in 7876 ms
[STDOUT] 2016-09-27 08:42:37,734[nio-4401-exec-1]  [WARN ] [o.e.c.impl.ContainerResponse 93]     - Client has aborted connection. Response writing omitted.
[STDOUT] 2016-09-27 08:42:37,734[nio-4401-exec-2]  [WARN ] [o.e.c.impl.ContainerResponse 93]     - Client has aborted connection. Response writing omitted.
[ERROR] Command output read timeout is reached. Process is still running and has id 17 inside machine
```

Browser:
![cant_load_project_types](https://cloud.githubusercontent.com/assets/2951406/18866774/12ebceee-84aa-11e6-9b27-1433b25ee514.png)

**Comment by eivantsov** [comment]
Make sure port 444 is opened.

**Comment by motorina0** [comment]
```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
f2b-SSH    tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:22
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            state RELATED,ESTABLISHED
...
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            state NEW tcp dpt:444
```

**Comment by motorina0** [comment]
Unfortunately after several attempts to start workspaces the error message changed:

> Unable to start workspace. Error when trying to start the workspace: Restoring of workspace workspaceovag0xjzojifn7x7 filesystem terminated on codenvy.onprem node. Process failed. Exit code 255

**Comment by motorina0** [comment]
Hm, so I found my problem. I have installed codenvy directly on a CentOS instance.
Basically, I have not used `vagrant up`, but ran the script at `http://start.codenvy.com/install-codenvy`

With F12 I can see in the browser:
![cant_load_project_types_3](https://cloud.githubusercontent.com/assets/2951406/18872737/a274b926-84c4-11e6-84aa-99e878044b73.png)

192.168.56.100 basically points to nothing.

I now have two questions:
  - is it incorrect to directly run `install-codenvy` ?
  - where can I change the value of `192.168.56.100`, to point to `codenvy.onprem` ?

**Comment by TylerJewell** [comment]
Sorry this writeup is not clear.   Please follow posting guidelines and provide full details on environment and steps to reproduce the error.

**Comment by motorina0** [comment]
@TylerJewell: sorry for that. Submitted new issue #853.

**Comment by TylerJewell** [comment]
@samtoomer - this pull request will make it so that you only need port 443 on our public cloud.  we'll deploy it soon.  Going to close this issue as you can track the other issue.

https://github.com/codenvy/codenvy/issues/869
