### ISSUE TITLE
Recipe for creating new machine is not present

### ISSUE THREAD

**Issue by artaleks9** [codenvy/codenvy#834]
**Reproduction Steps:**
* Open the IDE and switch to the 'Operations Perspective'.
* Go to 'Machine' -> 'Create..' and try to create new machine

**Expected behavior:**
Should be displayed the  recipe after typing into tag field.
 
**Observed behavior:**
The recipe is not displayed.

**Codenvy version:** 5.0.0-M3
**OS and version:** 14.04

**Additional information:**
Problem can be reliably reproduced: Yes 
See the atachment:
![create-machine](https://cloud.githubusercontent.com/assets/5408906/18778686/35604006-817e-11e6-9ba1-604ed7033149.png)

**Comment by gazarenkov** [comment]
I think creation standalone machine is not a sufficient usecase anymore.

**Comment by JamesDrummond** [comment]
@gazarenkov  I don't see 'Create...' in 'Machine' using M4. Was it taken out? If so, can we close this issue?

**Comment by musienko-maxim** [comment]
In earlier versions this widget worked like here: 
![anim](https://cloud.githubusercontent.com/assets/1640058/19111183/dcf4dcf0-8b06-11e6-9d64-84ab51d1631d.gif)
But after implementing docker compose feature i do not know this widget actual or not.

**Comment by musienko-maxim** [comment]
The problem still actual

**Comment by TylerJewell** [comment]
Closing - will not fix.  We should remove the operations view now that we have stack and server editing in UD.
