### ISSUE TITLE
Dashboard: bottom left button doesn't open a drop-down list.

### ISSUE THREAD

**Issue by vkuznyetsov** [codenvy/codenvy#835]
**Reproduction Steps:**

1. Goto https://nightly4.codenvy-stg.com/dashboard/#/
2. Try to click on bottom left button in nav bar.

**Expected behavior:**

Drop-down list appeared.

**Observed behavior:**

Nothing happened.

https://nightly4.codenvy-stg.com

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: Yes
Problem can be reliably reproduced: Yes

**Comment by vkuznyetsov** [comment]
We expect this drop-down after clicking the button.
![dashboard logout](https://cloud.githubusercontent.com/assets/2101815/18783575/25946f46-8195-11e6-810f-b8141ac2aac9.png)

**Comment by olexii4** [comment]
https://github.com/eclipse/che/pull/2572

**Comment by olexii4** [comment]
3h
