### ISSUE TITLE
Sharing permission is not working

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#836]
The button to share permission to a workspace does not work.

**Reproduction Steps:**

1. Open details of one of your workspace, go into "Share" tab
2. Input the email address of user you know is already having an account 
3. Click button "share"

**Expected behavior:**
It adds the user in the workspace developers

**Observed behavior:**
It is impossible to click on the "Share" button.
![screen shot 2016-09-22 at 16 33 40](https://cloud.githubusercontent.com/assets/1636769/18785833/eb3eb1e8-819a-11e6-99f8-8bbd93fc3392.png)

**Codenvy version:** 5.0.0-M2

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: Yes
Problem can be reliably reproduced: Yes

**Comment by ashumilova** [comment]
Log work - 1h
