### ISSUE TITLE
How do you find your public ip of your codenvy machine?

### ISSUE THREAD

**Issue by MineMooreALT** [codenvy/codenvy#841]
in the title.

**Comment by ddementieva** [comment]
@MineMooreALT Switch to the Operations Perspective  > Servers tab. Find all server addresses there.

**Comment by MineMooreALT** [comment]
Could you take a screenshot? i dont know whwere that is.

**Comment by TylerJewell** [comment]
You can switch into the ops perspective with the little switcher icon in the upper right corner of the IDE.  It's on the IDE tool bar.

**Comment by MineMooreALT** [comment]
http://imgur.com/a/UQVoH Where is the button here?

**Comment by TylerJewell** [comment]
In the far, upper right corner - there is a toggle button there.

**Comment by MineMooreALT** [comment]
I clicked on servers but it dosent seem like my server ip. http://imgur.com/a/5kvha

**Comment by TylerJewell** [comment]
You have to use the DNS entry - because your workspace can move to different containers, and we can move containers onto different physical nodes with IP addresses.  But you can lookup that domain name and get the current IP for that container / server.

**Comment by MineMooreALT** [comment]
The url one?

**Comment by MineMooreALT** [comment]
I am so confused sorry.

**Comment by ddementieva** [comment]
@MineMooreALT On which port have you started your server? It needs to be exposed in the recipe. And then you'll be able to find the corresponding published port in the Servers tab.

**Comment by MineMooreALT** [comment]
Im running ws server on port 778

**Comment by ddementieva** [comment]
@MineMooreALT Which stack have you used to run a workspace? Have you exposed 778 port in your recipe?

**Comment by MineMooreALT** [comment]
Nodejs and ide

**Comment by MineMooreALT** [comment]
and i dont know if i exposed it

**Comment by ddementieva** [comment]
@MineMooreALT You'll need to create a new workspace from a custom stack with 778 port exposed. On the Dashboard click `Add Workspace` button, choose Custom stack > Write your own stack option and paste the following content there:
```
FROM codenvy/node
EXPOSE 778
```
![create-ws-dashboard](https://cloud.githubusercontent.com/assets/6860395/18955455/3c0e6766-8660-11e6-8032-f40df42ef8fa.png)


After the workspace is started, switch to the Operations Perspective > Servers tab and find a corresponding server address there.

![server-address](https://cloud.githubusercontent.com/assets/6860395/18955471/4519ea42-8660-11e6-98c8-59b70ced59ca.png)

**Comment by MineMooreALT** [comment]
Ok thanks! and why does your container have localhost as the ip?

**Comment by MineMooreALT** [comment]
Just tried this and the Container wont even start I get this error: Error
response from docker API, status: 500, message: Error response from daemon:
couldn't get vxlan id for "10.0.80.0/24": failed to allocate vxlan id: no
bit available

**Comment by ddementieva** [comment]
@MineMooreALT We've experienced some problems with beta. They are fixed. 

Can you try to create new workspace again?

**Comment by TylerJewell** [comment]
Closing as issues were resolved.

**Comment by mathiasconradt** [comment]
The issue that @MineMooreALT reported happened again today on Codenvy on a [workspace](https://codenvy.io/dashboard/#/workspace/mathiasconradt/ubuntu-java-maven) that worked fine 2 weeks ago. Today I wanted to start it again, but it fails with:

> Start of environment default failed. Error: Error response from docker API, status: 500, message: Error response from daemon: couldn't get vxlan id for "10.0.0.0/24": failed to allocate vxlan id: no bit available

**Comment by xbtsw** [comment]
I am testing with setting up a stack on codenvy.io however the "perspective switcher" is sometimes missing. 
![image](https://cloud.githubusercontent.com/assets/4098537/22170300/f2868342-df30-11e6-9d02-116171c98622.png)
For the exact same workspace, it was here yesterday however not there for today. I tried re-login, refresh, clear browser cache, restart workspace without snapshot nothing helped.

When this happens, checking from the "workspace" doesn't help either:
![image](https://cloud.githubusercontent.com/assets/4098537/22170326/335d441e-df31-11e6-967c-edc03c57a74d.png)

**Comment by ramirovelazco** [comment]
I have this problem as well. no perspective switcher. just like @xbtsw

**Comment by TylerJewell** [comment]
This Eclipse Che PR will fix the problem - https://github.com/eclipse/che/pull/3866
