### ISSUE TITLE
beta: workspace never start

### ISSUE THREAD

**Issue by imrehg** [codenvy/codenvy#842]
Workspaces never starts.

**Reproduction Steps:**
- created new blank workspace
- start it

**Expected behavior:**

IDE to appear (I guess? I never had a successful workspace to see what I should see)

**Observed behavior:**

Continue loading.

In the Chromium console:

```
Failed to load resource: the server responded with a status of 404 (Not Found) https://beta.codenvy.com/api/permissions/system
Preloading IDE javascript /ide-resources/_app/5F4469412D8FD8B31741254EC8BD88BC.cache.js vendor-dbdc29a564.js:71983
Failed to load resource: the server responded with a status of 404 (Not Found) https://beta.codenvy.com/imrehg/default?uid=555585 
Failed to load resource: the server responded with a status of 404 (Not Found) https://beta.codenvy.com/imrehg/default?uid=959362
```

Lots of missing resources, or other issues. Looking at the second line, for example, resource is not returned as js, it's a web page. https://beta.codenvy.com/source/scripts/vendor-dbdc29a564.js

**Codenvy version:** [beta](https://beta.codenvy.com)
**OS and version:** ArchLinux x86_64, Chromium 53.0.2785.116 

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: Yes
Problem can be reliably reproduced:  Yes

**Comment by ddementieva** [comment]
@imrehg Have you tried to open it in the different browser? Can you try it, e.g. in Chrome? 

Can you also send a screenshot with browser dev console opened?

**Comment by imrehg** [comment]
@ddementieva same issue in Firefox 48.0.2 on ArchLinux, and exactly the same issue on WinXP Chrome 48 as well. Screenshots attached.

**Linux Chromium**:

![codenvybeta](https://cloud.githubusercontent.com/assets/38863/18841698/2ffd03ea-83d8-11e6-826b-129e7dabe43e.png)

**Linux Firefox**:

![codenvybetafirefox](https://cloud.githubusercontent.com/assets/38863/18841705/361a6f60-83d8-11e6-9391-9d8fd2ec2b90.png)

**WinXP Chrome**:

![virtualbox_windows xp_26_09_2016_23_57_37](https://cloud.githubusercontent.com/assets/38863/18841741/4fb533c4-83d8-11e6-9769-36a69045483c.png)

**Comment by ddementieva** [comment]
@imrehg Is there any timeout for the websockets? Can you wait for the `cannot get project type` error and keep browser dev console opened? 

Or switch to the Network tab in the browser dev console and find any failed requests there.

**Comment by imrehg** [comment]
@ddementieva how long that would take? Waiting ~30mins I never got such an error, and haven't seen any websockets timeout. The 404 requests in the network is `https://beta.codenvy.com/api/permissions/system` and `https://beta.codenvy.com/imrehg/default?uid=472384` (default is the workspace's name), just as the console shows above.
The dev console is like this:

![codenvy2](https://cloud.githubusercontent.com/assets/38863/18871832/d8dd976e-847c-11e6-85d1-d72fd6c22f20.png)

Networks tab, ordered by response code:

![codenvy2network](https://cloud.githubusercontent.com/assets/38863/18871838/e5424234-847c-11e6-95b5-685cdc7456da.png)

**Comment by eivantsov** [comment]
@imrehg 

Can you create a new workspace from dashboard and open a dev console on the below screen?

![image](https://cloud.githubusercontent.com/assets/5337267/18876670/3930dac6-84d3-11e6-9b50-c6d0570a6f9b.png)

**Comment by eivantsov** [comment]
Try hitting F5 or try in an incognito window.

**Comment by imrehg** [comment]
@eivantsov that's pretty much what I did above, or you mean doing it any different way? Just asking to understand. Anyways, created a new workspace, waited for it to be set up, opened in incognito window, everything seems to be the same, 404 errors in the console and workspace never finishes loading.

![codenvy-new-blank](https://cloud.githubusercontent.com/assets/38863/18879407/c297069e-8499-11e6-8609-7caa387266fb.png)

**Comment by eivantsov** [comment]
@imrehg If you repeatedly refresh the page you are at, does it change anything?  The green bulb next to a workspace name means that Codenvy considers the workspace to be OK.

**Comment by imrehg** [comment]
@eivantsov no matter how many times I refresh the page, nothing changes, can never get to the workspace, and the same entries in the console. Those workspaces can started/stopped/managed from the https://beta.codenvy.com/dashboard/#/workspaces page just fine, so can get to "green bulb" any time.

**Comment by eivantsov** [comment]
@imrehg i wonder if trying to access beta on a different connection fixes the problem

**Comment by TylerJewell** [comment]
@ddementieva @imrehg - if you are both available, may I suggest a live screenshare?  @ddementieva - please suggest a time that works for you and then you can create a google hangout for @imrehg to join.  I think we have to see it live to diagnose the issue.

**Comment by eivantsov** [comment]
@imrehg let me know when it's a good time for you to do screenshare? I am 100% confident those are network related issues since the service works ok for other users. The only thing that is mysterious to me is that there are no errors in console.

**Comment by imrehg** [comment]
@eivantsov I'm 100% confident that it is not a network issue. Using the beta site from a different network does not fix the problem (used home ADSL and phone 4G with the same results). On the other hand, I registered another user, and on the same network the new user does work, can use the workspaces/IDE. So to recap: I have one user account that never works, and another one that works just fine.

For what it's worth, the original account I set up by connecting to Github. The second one I set up by email/password.

Not sure what you mean, there are errors in the console: I always get 404s for the `https://beta.codenvy.com/<username>/<workspacename>?uid=<uid>` for the problem account (see the original report on top)

**Comment by TylerJewell** [comment]
@imrehg - that is wild.  Do you know when you created the original user account - the one that is faulty vs. when you created the new user account?

**Comment by ddementieva** [comment]
@imrehg Can you send registration emails of both your accounts on beta at support@codenvy.com?

**Comment by imrehg** [comment]
@TylerJewell I think it was created on Aug 31

@ddementieva sent email, thanks!

**Comment by JamesDrummond** [comment]
@imrehg When was the last time you were able to use `beta.codenvy.com` successfully with the account that is not working?

**Comment by imrehg** [comment]
@JamesDrummond never

**Comment by TylerJewell** [comment]
@imrehg  - since you were swapped over to the support channel, I will assume that the issue got resolved and will close this issue.

**Comment by imrehg** [comment]
@TylerJewell no, the issue persists, haven't heard anything back on support for the last 3 weeks or so.

**Comment by bmicklea** [comment]
@imrehg Sorry for the miscommunication. This was assigned to an engineer and they are investigating this as part of this sprint. In the meantime, can you sign up for an account at codenvy.io with a different email?

**Comment by imrehg** [comment]
@bmicklea no worries. Yes, I've already did that, see the discussion in this thread above :)

**Comment by bmicklea** [comment]
Good news, maybe next time I'll learn to read!  Oops...

**Comment by eivantsov** [comment]
@imrehg you can now start workspaces with your "broken" account.
