### ISSUE TITLE
Show/Hide panels based on user credentials

### ISSUE THREAD

**Issue by vlad-tury** [codenvy/codenvy#843]
Is there the possibility to show/hide certain panels based on the user credentials?

What I want is that the Console panel is visible only for admins and not for regular users.

If this is possible I would like to extend this to other panels/parts that I do not want shown to regular users.

I do realize that this might not be easy because:
- the panels that I want shown/hidden are in Che
- the user information is in Codenvy.

Please let me know if you had the request before and how was it done.
Thank you.

**Comment by TylerJewell** [comment]
Vlad:  this is possible in Codenvy.  Which customer are you with?  These sorts of changes and requests should be channeled through customer support.   While we do share the codenvy code base publicly, these sorts of modifications are not part of the fair source license.  We need to look at a support and distribution license.

**Comment by eivantsov** [comment]
Closed due to inactivity.
