### ISSUE TITLE
Standard installation on a single server - Can't load project types: Error

### ISSUE THREAD

**Issue by motorina0** [codenvy/codenvy#853]
I have installed codenvy onprem as "Standard installation on a single server" on a CentOS 7.2 image.
Can not create new projects.

**Reproduction Steps:**
- run `bash <(curl -L -s https://start.codenvy.com/install-codenvy)  --version=4.6.2`
(http://codenvy.readme.io/docs/installation#install)
- login on the newly created instance of codenvy (as admin)
- create a new workspace
- start the workspace

**Expected behavior:**
 - the workspace is started and I'm able to create a new Project

**Observed behavior:**
 - the workspace is started, but I receive an error (Can't load project types: Error) :
![cant_load_project_types_4](https://cloud.githubusercontent.com/assets/2951406/18879234/3299c552-84dc-11e6-8987-0bec2eef4812.png)

 - if I hit F12 (in Chrome), I can see that it is trying to make some requests to `192.168.56.110`
 - if I run `cat /etc/hosts`
```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

127.0.0.1 guest
::1       guest

127.0.0.1 puppet

127.0.0.1 codenvy.onprem

```

**Codenvy version:** 4.6.2
**OS and version:** CentOS 7.2.1511 (Core) 

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: [Yes]
Problem can be reliably reproduced: [Yes]

**Diagnostic bundle**
Execute the script on [this page](https://github.com/codenvy/codenvy/wiki/Support-Diagnostics) and post public link to the bundle here.
[report.tar.zip](https://github.com/codenvy/codenvy/files/495907/report.tar.zip)

**Comment by ddementieva** [comment]
@motorina0 Can you check hosts file on your local machine, cause it looks like browser resolves codenvy.onprem DNS to point to 192.168.56.110 IP? Make sure that codenvy.onprem points to the 104.238.146.221 and access your Codenvy installation by this DNS.

**Comment by motorina0** [comment]
@ddementieva I did the changes in the `hosts ` file. Now I'm still getting the error, but the logs are different.

![wsagent_timeout](https://cloud.githubusercontent.com/assets/2951406/18903647/ecf1af60-8562-11e6-962e-c61808bbe307.png)

I've checked `iptables `for ports `81 `and `444`. It looks OK:
```
[root@myremote~]# iptables -L -n
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
f2b-SSH    tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:22
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            state RELATED,ESTABLISHED
ACCEPT     icmp --  0.0.0.0/0            0.0.0.0/0
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 32768:65005
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
...
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            state NEW tcp dpt:80
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            state NEW tcp dpt:81
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            state NEW tcp dpt:443
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            state NEW tcp dpt:444
```

I have also stopped firewalld, just to be sure, but no improvement.
```
[root@myremote~]# systemctl disable firewalld
[root@myremote~]# systemctl stop firewalld
```

Which is the next step?

**Comment by motorina0** [comment]
I have also tried the following, but with no success.
 - open `/etc/puppet/manifests/nodes/codenvy/codenvy.pp`
 - set `$machine_extra_hosts = "codenvy.onprem:104.238.146.221"`
 - run `puppet agent -t` (http://codenvy.readme.io/docs/networking)

Outcome:
 - problem still reproduces (the 502, not the timeout)
![bad_gateway](https://cloud.githubusercontent.com/assets/2951406/18905563/6ed336b2-856c-11e6-87b6-3b8cda219400.png)

**Comment by ddementieva** [comment]
@motorina0 I've added `104.238.146.221 codenvy.onprem` to the hosts file on my local machine and everything worked OK for me. So, make sure that 81 port is not blocked in your network.

**Comment by eivantsov** [comment]
Same on my side:

![image](https://cloud.githubusercontent.com/assets/5337267/18905763/57c3017c-856d-11e6-8766-3cb53a566685.png)

**Comment by motorina0** [comment]
On my machine (Windows) I had the following in `c:\Windows\System32\drivers\etc\hosts `:
![win_hosts_old](https://cloud.githubusercontent.com/assets/2951406/18906938/49d7ef8c-8572-11e6-9b9d-be49a57f8827.png)
This I assume was created by Vagrant when doing the Vagrant install (not the standalone one) on my machine.

After the below change, it worked fine on my machine:
![win_hosts_new](https://cloud.githubusercontent.com/assets/2951406/18907027/a08c10d8-8572-11e6-8b6a-e331d3617444.png)

Half the problem is now solved :+1:

**Comment by motorina0** [comment]
Next:
  - try using codenvy on a clean Windows machine
  - there is **nothing** on the hosts file (besides the defaults)
  - check open port using:
     - http://portquiz.net:81/ - OK
     - in PowerShell - OK
         - Test-NetConnection -InformationLevel detailed -ComputerName 104.238.146.221 -Port 81

Outcome:
![err_name_not_resolved](https://cloud.githubusercontent.com/assets/2951406/18907849/fa255ade-8575-11e6-9f1d-b89185c257df.png)

**Comment by eivantsov** [comment]
@motorina0 you need to make sure codenvy.onprem points to the IP address you use to access Codenvy. That will solve all issues.

**Comment by eivantsov** [comment]
Alternatively you may setup a DNS server or use other methods to make sure the browser can resolve codenvy.onprem DNS.

**Comment by motorina0** [comment]
@eivantsov : I agree with that :). 
But I can not ask all potential users to update their `hosts ` file in order to use codenvy.
Isn't there a way to access directly the IP and work? Or access a domain (just like the trial codenvy servers)?

**Comment by eivantsov** [comment]
You may configure a real DNS and change hostname for the installation as per this DNS.

You have installed Codenvy with default settings where codenvy.onprem is the default DNS.

**Comment by motorina0** [comment]
Thanks @eivantsov .
If I understand correctly, then when installing codenvy I should use something of the form:
`bash <(curl -L -s https://start.codenvy.com/install-codenvy) --hostname=ide.mydomain.com`

Or is there more to it?

If that is the only change for the standalone server installation, then this issue can be closed.

**Comment by eivantsov** [comment]
@motorina0 yes, you may specify hostname when installing with a custom hostname. You can also change it after the installation.
