### ISSUE TITLE
Enhancement request: Command to unlink Codenvy from Google

### ISSUE THREAD

**Issue by chrisjj** [codenvy/codenvy#864]
Please add a command to unlink CE from Google. CE support has confirmed there's no such command.

If a Google account has been linked to CE by a past GAW Deploy, GAE Deploy uses that account regardless. If I need to use another account but am blocked from logging in to the linked account, I'm stuck.

**Comment by TylerJewell** [comment]
@chrisjj - is this for codenvy.com, or beta.codenvy.com?

**Comment by chrisjj** [comment]
I'm using codenvy.com .

**Comment by TylerJewell** [comment]
Ok, got it.  We have a different approach to connecting / disconnecting to GAE in the next-generation platform. The GAE plug-in is not as advanced, but it does offer more command line control.

**Comment by chrisjj** [comment]
The lack of a GAE Deploy menu command discourages me from your non-beta version.

**Comment by TylerJewell** [comment]
Thanks for the thoughts.  Codenvy is based upon eclipse Che open source.  And the community can get involved to provide their own plugins and pull requests which eventually roll into codenvy.

We invested man years of engineering into the previous plugin and there was little commercial opportunity with google.  There was a lot of investment but no profit, just losses.  So we need the community to maintain it now with Che.

**Comment by chrisjj** [comment]
Tyler

> We invested man years of engineering into the previous plugin and there
> was little commercial opportunity with google. There was a lot of
> investment but no profit, just losses.
>
Sympathies. Thanks for the explanation.

> So we need the community to maintain it now with Che.
>
Understood. I'll hope to see good news there, whereupon I'll try it.

Good luck!

C
