### ISSUE TITLE
Inform admin about important changes in update command output after update of Codenvy on-prem

### ISSUE THREAD

**Issue by dmytro-ndp** [codenvy/codenvy#865]
We need to have an ability to display update specific info in terminal after the successful update of Codenvy on-prem, for example, for update to 5.0.0-M4:
```
[vagrant@dev ~]$ codenvy install
[CODENVY] Unzip Codenvy binaries to /tmp/codenvy [OK]
[CODENVY] Configure Codenvy                      [OK]
[CODENVY] Patch resources before update          [OK]
[CODENVY] Move Codenvy binaries to /etc/puppet   [OK]
[CODENVY] Update Codenvy                         [OK]
[CODENVY] Patch resources after update           [OK]
[CODENVY] {
  "artifacts" : [ {
    "artifact" : "codenvy",
    "version" : "5.0.0-M4",
    "status" : "SUCCESS"
  } ],
  "status" : "OK",
  "message" : "All users' passwords have been reset. If your Admin user is 'admin', then your password has been set to 'password'. This has been done as part of an internal database consolidation that increases system security."
}
```

Message should be in yellow color.

It is needed for issue https://github.com/codenvy/codenvy/issues/845.

**Comment by riuvshin** [comment]
can we have that message with some color ? I think we have to make sure user will receive that message.

**Comment by dmytro-ndp** [comment]
We can display this message in yellow.

**Comment by bmicklea** [comment]
The message should look like this (but in yellow):

[CODENVY] All users' passwords have been reset. If your Admin user is 'admin', then your password has been set to 'password'. This has been done as part of an internal database consolidation that increases system security.

**Comment by bmicklea** [comment]
@skabashnyuk can we send the normal password reset emails to all users in the database either as part of the upgrade or immediately after upgrade?

**Comment by skabashnyuk** [comment]
@bmicklea We never send emails like that. Before we send emails only for SAAS users.

**Comment by bmicklea** [comment]
@dmytro-ndp how is this progressing?

**Comment by dmytro-ndp** [comment]
Example of update command output:
![update_info](https://cloud.githubusercontent.com/assets/1197777/19021492/9184d96a-88cb-11e6-924a-fbe2e6939a23.png)

**Comment by TylerJewell** [comment]
Here is shorter language.
"This is a one-time event to increase security with an internal database consolidation."
