### ISSUE TITLE
Installer/updater not working behind proxy

### ISSUE THREAD

**Issue by kmoughon** [codenvy/codenvy#866]
Continually getting errors during install.
 cat codenvy/install.log 
Install package 'wget'...  [OK]
Install package 'unzip'...  [OK]
Install java package from 'http://download.oracle.com/otn-pub/java/jdk/8u45-b14/jre-8u45-linux-x64.tar.gz' into the directory '/root/codenvy/jre' ...  [OK]
https://codenvy.com/update/repository/public/download/installation-manager-cli
[CODENVY] WARNING: automatic update of IM CLI client failed. See logs for details.

[CODENVY] Downloading might take several minutes depending on your internet connection. Please wait.
[CODENVY] {
  "message" : "Can't establish connection with https://codenvy.com",
  "status" : "ERROR"
}

i have checked out proxy and firewall logs and there are no attempts made to either for https://codenvy.com/update/repository/public/download/installation-manager-cli. 

i am using the bash install script with the --proxy, --http-proxy-for-installation  and the --https-proxy-for-installation flags, and ~.bashrc, /etc/yum.conf, and /etc/wgetrc files are configured correctly. the install makes it to 23% where the error reported above occurs.

**Comment by eivantsov** [comment]
@kmoughon can you manually reach https://codenvy.com from the instance that you use to install Codenvy?

Also, can you share the command that you use to install Codenvy? With all the --proxy arguments?

**Comment by kmoughon** [comment]
Here is the exact command for the install:
bash <(curl -L -s --proxy 10.170.127.228:3128 https://start.codenvy.com/install-codenvy) --http-proxy-for-installation=http://10.170.127.228:3128/ --https-proxy-for-installation=https://10.170.127.228:3128/

 I have run the report script that you provided, is there a way i can send it to you directly rather than post it here?

**Comment by TylerJewell** [comment]
@kmoughon - when I have done hands on some installations for customers, they usually do not have their proxy server with an `https://` protocol. They are usually only `http`.  I see that your curl command and your `--https-proxy-for-installation` are both using `https`.  Can you verify that maybe this should only be `http` with your company?

**Comment by kmoughon** [comment]
@TylerJewell good catch, i was using that incorrectly. However running it with the --https-proxy-for-installation pointing to http results in the same error. Here is the variation of the install i ran:
bash <(curl -L -s --proxy 10.170.127.228:3128 https://start.codenvy.com/install-codenvy) --http-proxy-for-installation=http://10.170.127.228:3128/ --https-proxy-for-installation=http://10.170.127.228:3128/

**Comment by TylerJewell** [comment]
You didn't fix `--proxy` in the curl statement.

**Comment by kmoughon** [comment]
Agreed, but that only applies to the initial request to download the install script, which is working. the install process fails later while executing the script not in retrieving the script.
Tried again with the following in case:
bash <(curl -L -s --proxy 10.170.127.228:3128 http://start.codenvy.com/install-codenvy) --http-proxy-for-installation=http://10.170.127.228:3128/ --https-proxy-for-installation=http://10.170.127.228:3128/ 
and result was the same.

**Comment by TylerJewell** [comment]
@dmytro-ndp - I am at a loss.  Any ideas what in the initial phases of bootstrapping could cuase this particular error message even though we have passed along the properly proxy IP + port?

**Comment by dmytro-ndp** [comment]
@kmoughon: actually bootstrap script doesn't support trailing "/" at end of proxy URL in options. So, the correct variant should be as follow:

> bash <(curl -L -s --proxy 10.170.127.228:3128 https://start.codenvy.com/install-codenvy) --http-proxy-for-installation=http://10.170.127.228:3128 --https-proxy-for-installation=https://10.170.127.228:3128

**Comment by TylerJewell** [comment]
Ahhh!  I thought we had cleanup functions to remove trailing spaces from those input parameters.  Maybe we should also add a capability to drop the `s` from any https URLs.  That is pretty bad form, but I think this is the 3rd or 4th time someone has made this innocent mistake.

**Comment by dmytro-ndp** [comment]
@TylerJewell: do you think we should create an issue and fix it ASAP?

**Comment by TylerJewell** [comment]
I am not sure it is ASAP, but let's write the issue as:
1. when bootstrap script runs, if value for any of the proxy / no proxy statements, then we should do a check.
2. If https or / at the end, then we should pause and print out question to installer.

"You provided a proxy with 'https://' or a trailing '/'. This is uncommon. Are you sure?  y/N".  If they choose no, then terminate.  If they choose yes, then continue.

**Comment by kmoughon** [comment]
I can confirm that removing the trailing slashes solved the problem. Thank you for your help guys.

**Comment by TylerJewell** [comment]
@dmytro-ndp - go ahead and open the issue as described below where we can alert people when we detect a URL with a trailing slash.

**Comment by dmytro-ndp** [comment]
@TylerJewell: IMHO proxy url with https is not so uncommon that we should interrupt installation.
Issue to work arounf proxy url with trailing slash: https://github.com/codenvy/codenvy/issues/886
