### ISSUE TITLE
Investigate if requests to dockerhub are made when using localy built workspace images

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#880]
Recently I got this error in swarm log:

```
level=error msg="HTTP error: Error while pulling image: Get https://index.docker.io/v1/repositories/eclipse-che/workspace***************_machine*************_******_dev-machine/images: dial tcp: lookup index.docker.io on 10.1.0.5:53: no such host" status=500
```

While this error related to our DNS servers reliability, I believe we don't need to attempt to pull images for workspaces from dockerhub, as they are built locally.

Need to investigate if this behaviour because of some runtime errors or swarm/docker always tries to pull docker images from external repositories while images built locally.

**Codenvy version:** 5.0.0.5-M2
**OS and version:** Centos 7.2

**Comment by mshaposhnik** [comment]
In trying to reproduce we switched ON debug on docker and swarm, start/stop workspaces, switch on & off DNS service and network connection but similar requests wasn't detected. Seems we need a clearer way to reproduce (if the problem still persist)

**Comment by TylerJewell** [comment]
I have sometimes noticed in the new CLI that it attempts to pull from dockerhub with docker.io, and the DNS names get confused, even though I already have the images locally cached.  I am starting to think that there may be some weird docker-engine issue that appears in limited scenarios.
