### ISSUE TITLE
Error when creating a new Python Google App Engine project

### ISSUE THREAD

**Issue by deathmagicmedia** [codenvy/codenvy#892]
When creating a new Python Google App Engine project, I am receiving an error. I have tried two (2) different methods.

**Method 1**
1) Sign into the Dashboard on codenvy.com
2) Click Projects
3) Click New Project
4) Select Python Google App Engine
5) Fill in the Name and Description
6) The following error appears:
Error while creating the project
Conflict: Required attribute value is initialized with null value gae:hasConfigFile

**Method 2**
1) Sign into the Dashboard on codenvy.com
2) Click Projects
3) Open an existing project in the IDE
4) Right click on the project folder
5) Click New
6) Click Project...
7) Select Python Google App Engine
8) Fill in the Name and Description
9) Click Next
10) Fill in an Application ID
11) Error occurs:
Next button does not work

Tested on Windows 7 Professional using:
Mozilla Firefox 49.0.1
Google Chrome 53.0.2785.143m
Opera 40.0.2308.62

**Comment by TylerJewell** [comment]
@deathmagicmedia - Yes, I can confirm the issue.  I am going to label this a bug.  As a work around, please consider creating an account at beta.codenvy.com, a next generation system. It doesn't have some of the nice click through menus for establishing a GAE project, but overall you can still work with GAE and have a lot more flexiblity.  We will - before the end of the year - be sunsetting the legacy codenvy.com and migrating all accounts into beta.codenvy.com, which will be rebranded into codenvy.io.

**Comment by deathmagicmedia** [comment]
@TylerJewell - Thank you for the feedback. I tried the beta.codenvy.com option, but I cannot find the deployment feature.

Found a temporary fix on www.codenvy.com:
1) Sign into the Dashboard on codenvy.com
2) Click Projects
3) Click New Project
4) Select Python Google App Engine
5) Fill in the Name and Description
6) Ignore the error and click Projects
7) Open the project in the IDE
8) Click File
9) Click Project Configuration
10) Click Python Google App Engine
11) Click Save
12) The deployment button will become available

**Comment by TylerJewell** [comment]
@deathmagicmedia - we dont' have the same sort of GAE support in the next generation system.  It's more flexible, but a bit more challenging to use.  We are based upon Eclipse Che, and they have a how-to explanation for GAE here.

https://eclipse-che.readme.io/docs/che-and-gae

**Comment by TylerJewell** [comment]
@JamesDrummond - please link this together with other questions on GAE.  Let's review all docs, and verify we have a tutorial around how to install GAE utilities into a workspace and then use it with a python or PHP project.

**Comment by themcclure** [comment]
The readme.io doc links are commonly referred to but they all give me a "Not Yet Active" page.

Is there a new document repo?

Thanks!

**Comment by TylerJewell** [comment]
Everything is now at docs.codenvy.com

**Comment by bmicklea** [comment]
@deathmagicmedia - have you been able to try the tutorial?  I think this issue can be closed but would like to get confirmation.

**Comment by deathmagicmedia** [comment]
@bmicklea - Yes, I have. Thank you. Forgot to thank everyone and close the issue due to a deadline.
