### ISSUE TITLE
How do I run Java Swing GUI programs on Codenvy

### ISSUE THREAD

**Issue by zhangtianyi2001** [codenvy/codenvy#893]
I want to test Swing programs on Codenvy but I don't know how to. My question might sound stupid but I have never used these before.
**Reproduction Steps:**
I opened a workspace with ubuntu_jdk8_x11 docker file.
Then I tried to build its default project, and it shows in the console " preview http://node4.beta.codenvy.com:33467/". When I click on it, it  shows this site cannot be reached. 

**Expected behavior:**

I read https://eclipse-che.readme.io/docs/che-and-swing ; I think it also says to click on the url to start noVNC. But it does not work.

**Codenvy version:**  5.0.0-M4
**OS and version:** server: ubuntu_jdk8_x11 client: Chrome53

**Additional information:**

I'm not sure I'm doing this right. Is there any way to test Swing programs on Codenvy?

Problem can be reliably reproduced: Yes

**Comment by TylerJewell** [comment]
@zhangtianyi2001 - what happens is that we run a VNC server inside of your workspace. VNC is a way to take your normal GUI application like Swing and it translates it into a presentation that can be sent into a window in your browser. It's your application, but we are broadcasting it into your browser. The URL that you access in the preview URL provides a way to access the VNC server.

Sorry that you ran into an issue here.  @ddementieva - will you please inspect this and give a hand?

**Comment by ddementieva** [comment]
@zhangtianyi2001 The problem was that VNC server has not been started during the workspace start. 

@eivantsov has changed codenvy/ubuntu_jdk8_x11 image, so the problem should be fixed now.

You can now follow the tutorial https://eclipse-che.readme.io/docs/che-and-swing to test your swing app.

**Comment by zhangtianyi2001** [comment]
@ddementieva Thank you very much. I have solved the problem now.

**Comment by 20avva** [comment]
@ddementieva the tutorial page is still not active?

**Comment by eivantsov** [comment]
@zhangtianyi2001 here you go http://www.eclipse.org/che/docs/tutorials/swing/index.html

**Comment by simaipeter** [comment]
I have this same problem, should I opena  new ticket ?

**Comment by eivantsov** [comment]
@simaipeter can you share details? What exactly failed?

**Comment by simaipeter** [comment]
http://www.eclipse.org/che/docs/tutorials/swing/index.html

Ran trough this, made a stack, made a workspace, imported the project.
Then made the Maven command, set the preview url.
No matter what I do after running it I get a preview url with a random nodexx.codenvy.io:yyyy random port number and the Browser says it is unreachable. Same with 6080 port.
example: http://node16.codenvy.io:34093/

**Comment by eivantsov** [comment]
![image](https://user-images.githubusercontent.com/5337267/34150737-e8f5e9da-e4b1-11e7-825b-c662c8131a03.png)

make sure the ephemeral port range isn't filtered in your network. I was able to connect to your app

**Comment by simaipeter** [comment]
![image](https://user-images.githubusercontent.com/13217698/34150785-b4794c40-e4a9-11e7-9b9f-c28bed657f8e.png)
It might be filtered then because I am at work currently. Thank you :)
