### ISSUE TITLE
The Yeoman Alfresco sample from eclipse getting start page does not work (regression)

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#914]
**Reproduction Steps:**
- Go to the https://www.eclipse.org/che/getting-started/cloud/  and start the Yeoman Alfresco sample
  **Expected behavior:**
  The sample should work

**Observed behavior:**
We have problem like: 
![selection_001](https://cloud.githubusercontent.com/assets/1640058/19148156/11013670-8bc4-11e6-8120-c074a74ef29a.png)

**Codenvy version: 5.0.0-M4**
**OS and version:** Ubuntu 14 TLS, Chrome browser

**Comment by benoitf** [comment]
This issue is part of the more global issue #1570
