### ISSUE TITLE
Sourcegraph sample from Che getting started page broken (regression)

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#915]
**Reproduction Steps:**
* Go to the https://www.eclipse.org/che/getting-started/cloud/  and start the Sourcegraph sample

**Expected behavior:**
The sample should work

**Observed behavior:**
We have problem like: 
![selection_002](https://cloud.githubusercontent.com/assets/1640058/19148269/83d0d70a-8bc4-11e6-9d19-ff9c85c38c11.png)

**Codenvy version: 5.0.0-M4**
**OS and version:** Ubuntu 14 TLS, Chrome browser

**Comment by JamesDrummond** [comment]
Removed from list of quickstart.
