### ISSUE TITLE
Add dashboard UI for changing user permissions

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#920]
In Codenvy you can share a workspace with users by adding them to the workspace. However, you can't alter their access permissions through the UI. Only through the API.

It would be helpful to be able to select one or more users and click a "Permissions" button. When pressed this would bring up a popup:
- Title: Edit Workspace Permissions
- List all permissions with checkboxes beside each
- Buttons at the bottom are "Save" and "Cancel"

The popup should be styled like other popups in the product.

**Codenvy version:** 5.0.0-M4

**Comment by bmicklea** [comment]
@slemeur not sure if you want a design for this - it's pretty straightforward I think but it's up to you.

**Comment by TylerJewell** [comment]
I believe this scenario is handled by the team enhancements.

**Comment by TylerJewell** [comment]
@bmicklea @slemeur - is this issue still actual or does team management capabilities manage properly?

**Comment by bmicklea** [comment]
@TylerJewell still an issue - you can add people through the UI but can't select their permissions except via the API.

**Comment by eivantsov** [comment]
This issue was moved to eclipse/che#5662
