### ISSUE TITLE
Allow users with "manageCodenvy" permission to stop workspace and get information about workspace

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#921]
Codenvy admins may wants to know information about workspace, like owner, etc.
And in some cases when they see suspicious activity in workspace they may want to stop it. 
Related to https://github.com/codenvy/enterprise/issues/7

**Comment by gazarenkov** [comment]
One side note: as discussed please rename System level permissions from <something>Codeny to <something>System 
Like manageCodenvy -> manageSystem
@sleshchenko

**Comment by sleshchenko** [comment]
Yes. But it is another issue. Let's implement checking of manageCodenvy on workspace stopping and getting workspace info. And create issue about renaming "manageCodenvy" action on system permission domain to "manageSystem"

**Comment by gazarenkov** [comment]
sure, just need to rename it ASAP, before GA
