### ISSUE TITLE
Study: Active Directory Large group support

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#924]
During synchronization Active Directory we found the problem if group is very large.
Instead of "member" or "members" attribute we found "member;0-2999" attribute.
Looks like AD has some "special" way to handle large multivalued attributes.
We need to study this case and find the way how we should handle  such big groups.

see more 
- https://msdn.microsoft.com/en-us/library/cc223322.aspx
- https://msdn.microsoft.com/en-us/library/cc223242.aspx
- http://stackoverflow.com/questions/22355213/retrieve-all-members-of-large-ad-groups
- https://gallery.technet.microsoft.com/scriptcenter/List-Members-of-Large-Group-0eea0132

**Comment by mshaposhnik** [comment]
AD supports paging of group members on all modern versions.
By default, chunk size is 1500 but may be reconfigured.
So, by default, when there is more than one chunk,  it return properties in form:
```
member:<none>
member;range=1-1500:<user_dn_1>, <user_dn_2>
```
To query other ranges, need to specify it explicitly:
```
member;range=1500-2000
```

When server responds with the '*' value as the upper parameter, it meant that it is last chunk:
```
member;range=1500-*
```

**Comment by mshaposhnik** [comment]
Fixed by https://github.com/codenvy/codenvy/pull/952
