### ISSUE TITLE
Stopped IDE should provide clear state and options to the user

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#932]
If you stop a workspace from the IDE, the IDE goes into a weird blank mode.  There is nothing here that helps to explain that the workspace is offline.  Also, why is the Project > Import From Codenvy Config active?  The other active menus make sense because they link off to help or support.

![image 2](https://cloud.githubusercontent.com/assets/7644938/19214550/8f458fea-8d54-11e6-9010-3570628543f2.png)

If the workspace has been stopped, this view needs to be dramatically different - so that it's user friendly to explain what has happened and what options the user has.  

**Codenvy version:** 5.0.0-M5
**OS and version:** beta.codenvy.com

**Comment by slemeur** [comment]
This is a regression - The IDE should not be displayed in this state. 

![restart](https://cloud.githubusercontent.com/assets/1636769/18316200/04069d0e-751a-11e6-9618-ada933306c14.png)

(From https://https://github.com/eclipse/che/issues/1760)

**Comment by slemeur** [comment]
Please @vitaliy-guliy + @ashumilova give a look on this issue. 
We have some situations where the loader is not properly displayed.

**Comment by slemeur** [comment]
Reproduced on nightly server.
Apparently, client is not receiving all of the workspace's event.

Estimate: 2-3 days. (could be shorter depending on investigation)

**Comment by vitaliy-guliy** [comment]
Spent 6 days
