### ISSUE TITLE
Stop the workspace when a snapshot is executed

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#933]
Snapshotting doesn't work properly.  I think this is because somehow the workspace is not being stopped after a snapshot.  I tried snapshotting from the left nav.  I tried snapshotting from the UD.  Both say that the snapshot is completed, but when I restart the workspace, changes that I make to /tmp/ are not restored.

The solution should be to stop the workspace anytime a snapshot action is executed. While the workspace is being snapshotted the workspace should not be accessible.

**Codenvy version:** 5.0.0-M5
**OS and version:** beta.codenvy.com

**Comment by slemeur** [comment]
Issue for team/platform.
Could you please give a look @skabashnyuk ?

**Comment by evoevodin** [comment]
I tried to create snapshot on beta and then to restore from it and everything worked fine.
Steps are:
- Create a new workspace from any stack
- Create a new file in home `cd ~ && touch new-file`
- Right click on the left menu -> Snapshot
- Stop the workspace from dashboard or any other place
- Go to dashboard and select the stopped workspace
- Click *OPEN*
- Ide will ask you whether you want to recover from snapshot or not, press *YES*
- Profit. The file `~/new-file` exists

You probably tried to start the workspace from UD, which doesn't restore a snapshot by default in codenvy(but it does in che), to restore in codenvy you have to press YES in IDE or add a workspace attribute `auto_restore` -> `true`.

> The solution should be to stop the workspace anytime a snapshot action is executed.

I don't agree on that as workspace users may pick different strategies for work, e.g. you can switch off automatic snapshotting and snapshot manually when needed, which probably shouldn't stop the workspace. 

I'd probably say that the behaviour is expected and defined by [this](https://github.com/codenvy/deployment/blob/4d558290fde8cc1a2089d8451a6a669af406efa2/puppet/modules/all_in_one/templates/general.properties.erb#L52) property.

**Comment by ashumilova** [comment]
What we can propose - add controls on dashboard's workspace page - for user to be able to configure auto-restore and auto-snapshotting? Or run/stop workspace with checkbox to restore/snapshot?

**Comment by TylerJewell** [comment]
I think we want to remove controls for users, not give them more controls.  It is too confusing I think to allow this much configurability.

For now I think that onorem admins should only have a single choice - either snapshotting always stops a ws or it does not.   

I believe that if we had more time we should remove all buttons from ud and IDE that give users any choice to snapshot a ws.  Instead the only choices should be stop ws with snapshot, or stop ws without snapshot.

**Comment by ashumilova** [comment]
We have this property [here](https://github.com/codenvy/deployment/blob/4d558290fde8cc1a2089d8451a6a669af406efa2/puppet/modules/all_in_one/templates/general.properties.erb#L49), so it's configured at one place. 
Snapshot can be done only for running workspaces, but not clear - why we are going to stop workspace after snapshotting? 
1. Is this issue still blocker? I can create another one for removing snapshot stuff from IDE and dashbaord.
2. stop ws with snapshot or stop ws without snapshot must be UI options or per system?

**Comment by TylerJewell** [comment]
Are you on the team-leaders alias from the weekend?  I will double check.  But there is a situation where a user will snapshot the workspace in the IDE either on the left nav or from the IDE.  However, even though the ws is snapshot the only way the workspace recovers from that snapshot is if it is stopped.  If you do not stop the ws and go into the dashboard to reload the same workspace, it does not load it from a snap.  And so the usage is confusing to the user.

**Comment by gazarenkov** [comment]
I'd say we need 2 options for stopping workspace in UI and no other options to make a snapshot
: 
- stop 
- stop with snapshot (only manually, not for stopping by timeout or so)

**Comment by TylerJewell** [comment]
The default should be "stop" (with snapshot), and "stop without snapshot".

**Comment by ashumilova** [comment]
Issue for handling snapshot creation state https://github.com/eclipse/che/issues/2763

**Comment by ashumilova** [comment]
Removed snapshot stuff from dashboard.
