### ISSUE TITLE
Remove extra workspace running notification.

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#934]
When we start a workspace that has been stopped, we are getting 2 "workspace running" notifications when only one is necessary.

**Codenvy version:** 5.0.0-M5
**OS and version:** beta.codenvy.com

**Comment by slemeur** [comment]
Please @vitaliy-guliy give a fix to this issue. This is something we discussed.

**Comment by slemeur** [comment]
Estimate: 30min

Will be fixed during next sprint.

**Comment by vitaliy-guliy** [comment]
Done with
https://github.com/codenvy/codenvy/issues/932
