### ISSUE TITLE
Clarify messages in UD for snapshotting

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#936]
When we are snapshotting in the UD we are not printing nice messages.  We print "snapshot_creating" and "snapshot_created".  Those are code-style messages.  We should be printing out something like "Creating snapshot...", and then "Snapshot created".  Also, the dot for the workspace is an identical color for creating a snapshot vs. snapshot created - it's the "workspace is off" color.  I think during the snapshot creation process we should be showing the animated rolling vertical bars.  And then after snapshot, we should then move to the gray button.

**Codenvy version:** 5.0.0-M5
**OS and version:** beta.codenvy.com

**Comment by slemeur** [comment]
Cross link with https://github.com/eclipse/che/issues/1758

**Comment by slemeur** [comment]
This one needs to be discussed @vitaliy-guliy and @ashumilova

**Comment by slemeur** [comment]
Will be taken during next sprint.

**Comment by ashumilova** [comment]
Fixed by this PR https://github.com/eclipse/che/pull/2875
