### ISSUE TITLE
Java content assist keyboard shortcut does not work in Codenvy Beta

### ISSUE THREAD

**Issue by zhangtianyi2001** [codenvy/codenvy#939]
I turned on "Show Content Assist Automatically", but it has never shown automatically. I tried Ctrl+Space and Ctrl+Alt+Space as the Key Bindings catalogue said so, but it does not work. The only way is to click on "Assistant" on top menu bar and click "Content Assist". Is there any way to make keyboard shortcut work or make content assist automatically show up?

I'm using java-default stack on Codenvy Beta on Chrome.

**Comment by TylerJewell** [comment]
@zhangtianyi2001 - can you provide more details about your browser, OS, internationalization version combination?  I just ran a test on Windows 10, Chrome browser - created a simple Java application, opened some Java source code, and then clicked Ctrl + Space.  Auto-complete recommendations appeared right away.

It's possible that if you have imported a complicated Java project, that it takes a moment for your workspace to resolve dependencies before intellisense will work. But we display the status of that work in the lower right corner.

**Comment by zhangtianyi2001** [comment]
@TylerJewell I just figured out the problem. The shortcut happened to coincide with my operating system's IME (Chinese/Japanese IME) switching shortcut. The OS might have higher priority than browser so the shortcut triggered OS's feature instead of webpage's. When I disabled all the IMEs the Content Assist worked fine. Thanks.

**Comment by TylerJewell** [comment]
Yep - I was suspicious of something like that.  Eventually, one of our partners is going to work on a rich keybinding capability to help detect, test and override this sort of stuff.
