### ISSUE TITLE
Wrong behavior after create workspace from Node.js template (SaaS Cloud)

### ISSUE THREAD

**Issue by AndreyChizhikov** [codenvy/codenvy#944]
**Reproduction Steps:**
1. Login to https://beta.codenvy.com
2. Go to https://www.eclipse.org/che/getting-started/cloud/ 
3. Launch workspace from [Node.js](http://beta.codenvy.com/f?id=af9r928owfulum17)  template

**Observed behavior:**

- Notification with message 'Project: web-nodejs-simple Sources cannot be cloned.Value for required attribute is not initialized java:java.source.folder '  was showed
- Item 'External Libraries' is present in the Project explorer
- Error message: `[ws-machine] npm ERR! Linux 3.10.0-327.13.1.el7.x86_64
[ws-machine] npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--no-bin-links"
[ws-machine] npm ERR! node v6.6.0
[ws-machine] npm ERR! npm  v3.10.8
[ws-machine] 
[ws-machine] npm ERR! Maximum call stack size exceeded
[ws-machine] npm ERR! 
[ws-machine] npm ERR! If you need help, you may report this error at:
[ws-machine] npm ERR!     
[ws-machine] 
[ws-machine] npm ERR! Please include the following file with any support request:
[ws-machine] npm ERR!     /projects/web-nodejs-simple/npm-debug.log`

![node](https://cloud.githubusercontent.com/assets/8051404/19239509/055924f6-8f0f-11e6-9fee-5b90564cccaf.png)

**Codenvy version:** 
**OS and version:** Ubuntu 14.04 LTS

**Additional information:**
Problem can be reliably reproduced: Yes 
 Codenvy host: https://beta.codenvy.com

**Comment by riuvshin** [comment]
factory should be updated same as here https://github.com/eclipse/che/commit/ca9aac259316403c011dda15c02968815cc00c9c

**Comment by riuvshin** [comment]
@ddementieva seems it is you who own that factory can you please update it?

**Comment by ddementieva** [comment]
@AndreyChizhikov @riuvshin Factory has been updated.

You can check it with https://beta.codenvy.com/f?id=af9r928owfulum17

**Comment by AndreyChizhikov** [comment]
Commands are working correctly now but this fix is only for the third problem.

**Comment by musienko-maxim** [comment]
fixed
