### ISSUE TITLE
The editor is not updated after git checkout branch

### ISSUE THREAD

**Issue by artaleks9** [codenvy/codenvy#946]
**Reproduction Steps:**
* Create new branch and checkout in it. 
* Open a file, add content and commit changes.
* Checkout into first branch. 

**Expected behavior:**
The content of file should be updated after git checkout according to the branch.

**Observed behavior:**
The content of file is not updated after git checkout.

**Codenvy version:** beta.codenvy.com (ver.5.0.0-M5)
**OS and version:** 14.04

**Additional information:** 

Problem can be reliably reproduced: Yes

**Comment by riuvshin** [comment]
And more if editor is not upadate it means it will auto save wrong content in previous branch which is pretty bad, @vparfonov this is pretty bad bug not blocker but I would love to have this fixed asap.

**Comment by artaleks9** [comment]
Right now this bug is not reproduced on the local CHE neither on the hosted version.
