### ISSUE TITLE
Problems for java autocompletion with eclipse tycho based projects

### ISSUE THREAD

**Issue by TristanFAURE** [codenvy/codenvy#948]
Java build path is not well recognized with Maven Tycho projects

create a maven project using git (for instance : https://git.eclipse.org/r/gendoc/org.eclipse.gendoc)

the git clone is well done and the parent pom is recognized. However with Tycho I don't have in this project main/java/src project structure and the auto completion/java navigation is not available

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: No
Problem can be reliably reproduced: Yes
Tested on 5.0.0 M5

**Comment by TylerJewell** [comment]
@vparfonov - I haven't come across a project that uses maven that does'nt follow the traditional /main/java/src structure before.  Is this limitation an issue with the maven plugin that we have built?

@TristanFAURE - as a workaround, you can set the project type to javac, and you can explicitly define the source and library locations, which will activate java intellisense.

**Comment by eivantsov** [comment]
@TristanFAURE I have imported your project locally and opened it with InjelliJ that does not seem to know how to correctly import it. Although plugin docs say that all you need is to have it in your pom, it does not work out of the box in a default Java + Maven environment.

**Comment by TristanFAURE** [comment]
Hello,
it is an Eclipse RCP plugin set
I don't know how it is supposed to work on Intellij but on Eclipse the IDE uses manifest information.

Nevertheless on che, if I run mvn clean package on my project he build is correct that's why I think all the data is present.

**Comment by eivantsov** [comment]
Yes, Maven build will work. By manifest, do you mean .properties files that are there in each module?

**Comment by TristanFAURE** [comment]
Actually I was talking about manifest.mf files. It is something specific to eclipse plugin development and tycho maven plugin.
Tycho analyses the manifest.mf files to build.

By the way for my usage of Che it is not mandatory to have all the stuff working, if I could specify that my sources are in src folder to have completion / recognition on jdk types it would be a good first start

**Comment by eivantsov** [comment]
Well, you may try adding:

```
 <build>
 <sourceDirectory>src</sourceDirectory>
 </build>
```

to your pom(s)

**Comment by TristanFAURE** [comment]
I confirm that adding these lines in the pom transforms my src directory in a recognized java source directory

Thanks
