### ISSUE TITLE
Dashboard: Factory Command ui is not very friendly to long commands

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#951]
1. I expect to see a bit larger inputs to be able to edit long command
2. In UI you see input name "Param" but it's not a param. It's command itself
   <img width="1440" alt="2016-10-11 15 57 28" src="https://cloud.githubusercontent.com/assets/1614429/19271092/be0954be-8fcb-11e6-94e0-30a64569f91d.png">

**Comment by TylerJewell** [comment]
I think this is a Che issue.  It affects any location where commands are added / removed.

**Comment by TylerJewell** [comment]
@ashumilova - is this still actual? I think the redesign probably solves this.  Close if necessary.

**Comment by ashumilova** [comment]
not actual
