### ISSUE TITLE
Investigate how to provide personal team

### ISSUE THREAD

**Issue by ashumilova** [codenvy/codenvy#958]
Now there are just organizations. But we need some kind of organization that will be used as personal one.
User should have one and only one personal organization. He should be able to use default free resources here. He should be able to create suborganizations (aka teams) and redistribute resources between them.

**Comment by sleshchenko** [comment]
Personal organization will be simple organization but with some specific:
- information about personal organization can be stored in user profile as read only attribute
- user isn't able to remove his personal organization
- user isn't able to leave it
- user is able to create other organizations but they will not be personal so they will no have free resources here
