### ISSUE TITLE
Error pushing to GitHub origin repo

### ISSUE THREAD

**Issue by Teg79** [codenvy/codenvy#968]
** If you are a Codenvy customer or have a trial license please file your issues with Support through email. GitHub issues do not have a response SLA.**

Error pushing to GitHub origin repo

**Reproduction Steps:**

- Login with GitHub OAuth2
- Create an empty workspace
- Clone an existing project from GitHub
- Make a commit
- Push to the origin

**Expected behavior:**

Push done

**Observed behavior:**

Push failed, I have to use the terminal, enter the project dir, write 'git push' and enter manually my GitHub credentials.

**Codenvy version:** The codenvy.com online version (next gen)
**OS and version:** macOS 10.12.1 with Chrome

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: No
Problem can be reliably reproduced: Yes

**Diagnostic bundle**
Execute the script on [this page](https://github.com/codenvy/codenvy/wiki/Support-Diagnostics) and post public link to the bundle here.

**Comment by JamesDrummond** [comment]
@bmicklea I used my github account to login, imported a github project using the https clone url address, and I could NOT commit. The is a severity/blocker.

**Comment by eivantsov** [comment]
@JamesDrummond what is the error message?

Also note that you cannot push to an http repo unless you have generated a key for GitHub through oAuth (not login)

**Comment by bmicklea** [comment]
@JamesDrummond I am able to push once I have my key setup. The steps I took:

1. Cloned a project I had push rights to using the HTTPS url.
2. Clicked the menu item Profile > Preferences.
3. In dialog box select the SSH / VCS subitem.
4. Click the octacat logo to create a new key and push to my GitHub account. This uses oAuth.
5. In dialog box select Git / Committer and added my name and email (I think this is optional but I always do it).
6. Used the git menu to Add to Index > Commit > Push.

**Comment by JamesDrummond** [comment]
@bmicklea Sorry guys forgot to press the octocat. Everything works for me.

**Comment by JamesDrummond** [comment]
@Teg79 Did you press the octocat in the preferences>vcs?

**Comment by JamesDrummond** [comment]
Is there a way for us to popup a window to help users if the don't know or forget to press the button. Maybe some steps to try to get it to work or link to [https://eclipse-che.readme.io/docs/git#git-using-oauth](https://eclipse-che.readme.io/docs/git#git-using-oauth)? probably something I should have looked at before replying here.

**Comment by eivantsov** [comment]
@JamesDrummond yes, maybe the error message should be more user friendly

**Comment by Teg79** [comment]
No, I didn't, now it's working!
Sorry it was my mistake, after cloning from GitHub I thought it was already connected with OAuth

Teg

Francesco

**Comment by TylerJewell** [comment]
@JamesDrummond - to your question about automating granting oAuth rights to push back whenever you create an account the first time with your oAuth credentials.  There are two philosophies to security today - one that when a user creates an account, you ask for all of the privilges needed for any possible function in advance.  The other is that oAuth should ask for additional rights each time a user does something that requires additional rights.  I tend to think that we should go for the latter, as that will make the overall system's architecture cleaner.

**Comment by bmicklea** [comment]
No problem Francesco - we'll be making the error message more clear going forward. If you want you can follow that here: https://github.com/eclipse/che/issues/2804

**Comment by smitpatelx** [comment]
# First and Simple solution ::
* Try this command ```git push -f origin master```.
* This command will forcefully do all the changes needed to your repository.

# Recomended Solution ::
* Delete ```.git``` directory from the folder.
* Then execute these commands :
```
git init
git add .
git commit -m "First Commit"
git remote add origin [url]
git push -u origin master
OR
git push -f origin master 
```

Only use ```git push -f origin master``` if ```-u``` dont work for you.

## This will solve almost any kind of errors occured while pushing your files.
### Thnk me later !!
