### ISSUE TITLE
Some commands from the Bitnami factories are not performed in the IDE (regression)

### ISSUE THREAD

**Issue by musienko-maxim** [codenvy/codenvy#970]
**Reproduction Steps:**
Try to use the bitnami factory like: https://nightly5.codenvy-stg.com/f/?url=https%3A%2F%2Fgithub.com%2Fbitnami%2Fbitnami-docker-laravel%2Ftree%2Fche

**Expected behavior:**
Should be created a workspace and 'run' command shoud be executed without errors.
**Observed behavior:**
We have errors:
`ws-machine] /bin/sh: 1: source: not found
[STDERR] /bin/sh: 1: source: not found` 

![selection_007](https://cloud.githubusercontent.com/assets/1640058/19435076/7fda85aa-9471-11e6-9565-2e5a2d28f1dd.png)

**Che version:**    5.0.0-M6  
**OS and version:**   Ubuntu 14.04  TLS

**Comment by benoitf** [comment]
It's because default interpreter is now SH and not bash I will see how I can provide the use of bash for factories

**Comment by benoitf** [comment]
linked to https://github.com/eclipse/che/issues/2811

**Comment by benoitf** [comment]
@musienko-maxim this issue could be closed, no ?

**Comment by benoitf** [comment]
fixed by https://github.com/eclipse/che/pull/2838 a long time ago.
