### ISSUE TITLE
Error message displayed when stopping a workspace

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#976]
There is a wrong error message displayed when user is stopping a workspace just created from a factory.

![screen shot 2016-10-18 at 10 48 30](https://cloud.githubusercontent.com/assets/1636769/19470805/341db83e-9521-11e6-9b40-553da32bc32b.png)

**Reproduction Steps:**

1- Start from the factory PetClinic
2- Wait the workspace created and all dependencies resolved
3- Start tomcat with the run command
4- Stop the workspace by doing a right click in the left sidebar

**Expected behavior:**
The workspace is stopped and the wizard at the top is proposing to restart the workspace

**Observed behavior:**
An error message saying "OutOfMemory" is displayed.

See the attached animated gif.
![bug-stop-ws](https://cloud.githubusercontent.com/assets/1636769/19470877/781bc8dc-9521-11e6-94ab-2767305571a9.gif)

**Codenvy version:** 5.0.0-M5

**Additional information:**
Problem only started happening recently, didn't happen in an older version of Codenvy: Yes
Problem can be reliably reproduced: Yes

**Comment by vitaliy-guliy** [comment]
It looks it's a server side issue.
@skabashnyuk please give a look on it.

**Comment by garagatyi** [comment]
It's not server-side error. As far as I remember it's related to OOM detection in UD. @benoitf as far as I remember you implemented OOM detection in UD, so can you take a look to this issue

**Comment by benoitf** [comment]
I think the issue here is that we listen to events but we don't unregister from events on eventbus when we stopping workspace
And then we get container destroyed error (which is true) but it's expected as we stopped the workspace.
so it's to unregister from websocket events after we stop workspace

**Comment by TylerJewell** [comment]
No longer actual.
