### ISSUE TITLE
Infinite loop while creating a workspace from a factory

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#977]
For some reason, there is an infinite loop while starting a workspace from a factory.

**Reproduction Steps:**

1- Open the following factory: https://beta.codenvy.com/f?id=r3pbh9wv7tjvbws7 (from Nuxeo)

**Observed behavior:**

The creation + booting of the workspace is running into an infinite loop. 
See the animated gif:
![infinite-loop-while-starting-from-factory](https://cloud.githubusercontent.com/assets/1636769/19471407/688bff0c-9523-11e6-9d1d-c2debe443682.gif)

Moreover, while there is this, issue the browser tab is using 100% of the computer and high RAM consumption.

See the attached factory.json
[nuxeo-factory.json.zip](https://github.com/codenvy/codenvy/files/535753/nuxeo-factory.json.zip)

**Codenvy version:** 5.0.0-M5

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: Yes
Problem can be reliably reproduced: Yes

**Comment by akorneta** [comment]
Probably seems that it's not factory problem at all, it's something wrong with agent(based on the logs). It looks like agent trying to connect by the socket connection to the master and it happens [here](https://github.com/eclipse/che/blob/master/core/che-core-api-core/src/main/java/org/eclipse/che/api/core/notification/WSocketEventBusClient.java#L267).
Also I tried the nuxeo-factory.json on my aio instance and it works fine
![img](https://cloud.githubusercontent.com/assets/12269156/19761549/23c5c5a6-9c3f-11e6-8ebd-a45acbd0a880.png)

**Comment by mkuznyetsov** [comment]
Couldn't reproduce infinite loop neither with given factory, nor with custom factory based on given JSON
