### ISSUE TITLE
"No workspace selected. Unable to open IDE" while loading a factory

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#985]
While opening a workspace it is possible to see a weird message, before the glowing logo is displayed.
It makes the experience unfriendly and not polished.

See the attached animated gif:
![loading-bug](https://cloud.githubusercontent.com/assets/1636769/19511320/106a3158-95e7-11e6-9a96-1ca64770a320.gif)

**Reproduction Steps:**
1. Open factory from https://github.com/codenvy-demos/spring-petclinic

**Expected behavior:**
The workspace is opened without displaying error message.

**Observed behavior:**
The workspace is opened and while it is opening, it is possible to see during very few seconds this screen:
![loading-bug-no-workspace-loaded](https://cloud.githubusercontent.com/assets/1636769/19511265/e463f0ee-95e6-11e6-835a-c8a324143145.png)

**Codenvy version:** 5.0.0-M5

**Comment by vitaliy-guliy** [comment]
The workspace has to be selected in the navbar.
Issue is related to the dashboard team.

https://github.com/eclipse/che/blob/master/dashboard/src/app/ide/ide.html

**Comment by vitaliy-guliy** [comment]
@ashumilova could you please give a look?

**Comment by ashumilova** [comment]
Took to the next sprint.

**Comment by slemeur** [comment]
thanks.

**Comment by ashumilova** [comment]
Fixed by https://github.com/eclipse/che/issues/2820
