### ISSUE TITLE
beta.codenvy.com: Import project from Google Cloud Platform Version control System

### ISSUE THREAD

**Issue by Xaver2k** [codenvy/codenvy#988]
Hello, i have an Android project setup and in sync with Google Cloud Platforms VCS. Can someone provide me a step to step guide how to import my project to Codenvy, please?

**Comment by TylerJewell** [comment]
Much of Codenvy is based upon Eclipse Che.  We are working ot make sure tha the docs are synchronized and aligned.  But in the mean time, you can learn about how to use Che as an IDE here: https://eclipse-che.readme.io/docs/

Dont' worry about all of the Che setup stuff - Codenvy automates that.  But take a look at all of the tutorials and Che IDE scenarios.

**Comment by isaacserafino** [comment]
I feel this is an important question about how to import a Google Cloud project into the version of Che used in Codenvy. I have the same question. I have found few answers about how to import G-Cloud projects into Che, and the few I have found seem to refer to options that I cannot find in Codenvy. I would really like it if it were possible to get an answer to this question somehow.

**Comment by TylerJewell** [comment]
Is it not as simple as grabbing the git URL remote references of the Google Cloud repository and then using that with a standard git clone?

**Comment by isaacserafino** [comment]
Thank you very much for your prompt and helpful answer. I think I'll work on setting up a "credential provider" for that route, next.

What I think was going on, was maybe there is (or was in a previous version) a Google Cloud _plugin_ for Che that is not present in my Codenvy workspace? That would also be useful for running GAE "locally" for testing on Codenvy, and deploying to GAE. I also can't seem to find information about such a plugin or how to install it. But, I would be happy to communicate about further issues in a different venue or thread.

Thank you again.

**Comment by TylerJewell** [comment]
In a version of Codenvy (not Che) from 2+ years ago, we used to maintain a GAE plugin that automated the deployment of projects from Codenvy into Google.  We discontinued that plugin as the PaaS platform APIs were changing too frequently and it became too costly for us to maintain support for the plugins.

So now the interface is strictly a pure git interface.
