### ISSUE TITLE
SSL Check

### ISSUE THREAD

**Issue by maxibanki** [codenvy/codenvy#991]
**_FEATURE**_
An Feature, which could help a lot of people is a SSL check. On activating HTTPS in the config, the script should check if the certificate exists, if it is valid, or is it in the correct format.

**Comment by eivantsov** [comment]
@maxibanki Can you elaborate on the use case? Are you a user of your own Codenvy installation?

**Comment by maxibanki** [comment]
Yes, I'm a hosting an own instance of codenvy. Once I want to activate SSL through the cli, the setup, or the "waiting for when codenvy alife(reachable)" is infinity, because my haproxy has an certificate error. Just an feature, which doesn't need everyone, but which improve the SSL error handling. At least you need to decide if its possible or if its needed in the installer.

**Comment by TylerJewell** [comment]
We have a slick solution coming for this.  We are going to package configuration into a simpler approach, and one of the tactics is around detecting SSL configurations.

**Comment by eivantsov** [comment]
@maxibanki I will close this issue, and you are welcome to try a new way to install Codenvy - https://codenvy.io/docs/admin-guide/installation/index.html
