### ISSUE TITLE
There is no user name in the bottom left corner in dashboard.

### ISSUE THREAD

**Issue by vkuznyetsov** [codenvy/codenvy#994]
There is no user name in the bottom left corner in dashboard for user created with an email and a username.

Step to reproduce:
1. Create a new account with email and username
2. Click on the link in confirmation email
3. Goto Dashboard

Expected result:
- There is Username in the left bottom corner if a user filled out his profile or any other user friendly text if user name empty in a user profile.

Actual result:
- Only Gravatar Icon in the corner.
  ![codenvy account](https://cloud.githubusercontent.com/assets/2101815/19566277/6030abe8-96f2-11e6-8477-c17c4074713c.png)

**Comment by slemeur** [comment]
+1 with this bug The information given to create the account without oauth, must be taken in the user profile
