### ISSUE TITLE
There is no way to make persistent changes to machine

### ISSUE THREAD

**Issue by jdeslip** [codenvy/codenvy#998]
None of my changes to the workspace/machine seem to be saved when I stop and restart a workspace. 

For example, if I use the terminal to apt-get install some software, or update the android SDK tools, all of these changes are lost the next time I start the workspace. 

I gather the "snapshots" feature should enable these sorts of changes to be persistent, but I don't see any way to take a snapshot in the beta site. Is this a paid only feature? I see there is a greyed out "machine" menu - I can only guess what the options/commands are under that menu.

Codenvy Version: 5.0.0-M5

**Comment by jdeslip** [comment]
Well, I see now you can right click on the workspace name on the left and select "snapshot". But, it never seems to finish.

**Comment by TylerJewell** [comment]
Hi jdeslip - this is a known issue.  But there is a workaround.  We have some hot fixes coming in M6, which is releasing soon.

**Comment by JamesDrummond** [comment]
@TylerJewell #933 is now closed and PR is merged. Can we close this issue and #918 ?

**Comment by TylerJewell** [comment]
@JamesDrummond - I believe that we should wait for products to be released before we close an issue.  PR merged is probably not suitable, especially if the original poster is a customer / outsider who cannot verify it.

**Comment by TylerJewell** [comment]
All of these changes have been pushed into production.
